### PR TITLE
Update dependancies

### PR DESCRIPTION
**Pull request by dmitryax**
github.com/klauspost/compress v1.15.4
github.com/jackc/pgx/v4 v4.16.1
github.com/golangci/golangci-lint v1.46.1
k8s.io/kubelet v0.24.0
go.uber.org/atomic v1.9.0

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@dmitryax please fix the lint

**Comment by dmitryax** [comment]
@bogdandrutu it's fixed

**Review by codeboten — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please resolve conflicts

**Comment by dmitryax** [comment]
@codeboten @bogdandrutu this is ready to merge

**Pull request merged**
