### PR TITLE
[chore]Bump examples demo image to 0.67.0

### LINKED ISSUE #16613: Examples are not up-to-date
### Component(s)

examples/demo

## Description

Some examples of this repository are either not working anymore or are out-of-date. I've been experiencing issues with `exporters.logging.verbosity` key which has been added recently but isn't working in few examples (see [slack discussion](https://cloud-native.slack.com/archives/CJFCJHG4Q/p1670232767580809)). 

I've made a tour of the examples to check whether they are out-of-date or not working anymore, results are in [#Actual Result](#actual-result). 

## Steps to Reproduce

**For not working examples**: 

1. Be at the root of the repository 
2. Run `docker compose -f examples/${EXAMPLE_NAME}/docker-compose.yml`

**To check whether it is up-to-date or not** (reading Dockerfile / docker-compose.yml works too):

1. Be at the root of the repository
2. Update the example configuration by adding the following exporter (this piece of config is recent enough to check if images are up to date):

```yaml
exporters:
    logging:
        verbosity: detailed
```
3. Run `docker compose up -f examples/${EXAMPLE_NAME}/docker-compose.yml`

## Expected Result

All examples should be working and up-to-date.

## Actual Result

| Example name | Is working | Is up-to-date |
| ------------ | ---------- | ------------- |
| couchbase   |    ❌        |       ❌        |
| demo            |      ✅      |      ❌         |
| kubernetes   |     Unknown       |         Unknown      |
| nomad          |       Unknown     |         Unknown      |
| tracegen      |    ❌        |      ✅         |
| tracing         |    ✅        |      ✅         |

**There is no input for `kubernetes` and `nomad`, new inputs for them are welcomed!**

### Couchbase error

```
$ opentelemetry-collector-contrib/ docker compose up -f examples/couchbase/docker-compose.yml
1 error(s) decoding:

* 'Deploy.Resources.Limits.cpus' expected type 'string', got unconvertible type 'float64', value: '0.5'
```

### Tracegen error

```
$ opentelemetry-collector-contrib/examples/tracegen docker compose up
unable to prepare context: path "../../tracegen" not found
```

### Demo out-of-date

It is running image `otel/opentelemetry-collector-contrib-dev:latest` which hasn't been updated for a long time, it should be updated or using Dockerfile from `tracing` example.

### Collector version

e58554a

## Environment
OS: MacOS, v13.0.1
Compiler(if manually compiled): go1.19.3
Arch: arm64 (Apple Silicon M1)

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackycsl**
**Description:** <Describe what has changed.>

Update the docker image used from `otel/opentelemetry-collector-contrib-dev:latest` to `otel/opentelemetry-collector:0.66.0`

**Link to tracking Issue:** 
#16613

**Testing:** <Describe what testing was performed and which tests were added.>
Run docker-compose up and make sure Jaegar, Zipkin, and Prometheus can display the data.

**Documentation:** <Describe the documentation added.>
[Opentelemtry Demo Documentation](https://opentelemetry.io/docs/collector/getting-started/#demo) is still relevant.

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
0.67.0 is out, could we bump to that?

**Comment by jackycsl** [comment]
> 0.67.0 is out, could we bump to that?
Sure

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Can you rebase against/merge main?

**Comment by mx-psi** [comment]
Ah, that was not enough, we needed #16846. Can you rebase again?

**Pull request merged**
