### PR TITLE
Made six more metrics enabled by default.

### PR DESCRIPTION
**Pull request by samiura**
**Description:** Enabled six more metrics enabled by default. 

**Link to tracking Issue:** #31613

**Testing:** <Describe what testing was performed and which tests were added.> Integration tests, Unit tests and Manual visualization of newly defaulted metrics on tools like Splunk's IMM/Grafana.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Review by djaglowski — CHANGES_REQUESTED** [review]
At a minimum, I do not believe we can make this change unless there is a feature gate to control it.

**Comment by atoulme** [comment]
Sorry, I missed that. Yes, a feature gate might be needed then.

**Comment by dmitryax** [comment]
The mdatagen provides a way to migrate optional metrics to default with warnings, not feature gates. Please follow https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/scraping-receivers.md#adding-a-new-default-metric-or-turning-an-existing-optional-metric-into-default

**Comment by astencel-sumo** [comment]
As of writing this, I don't see any justification for this change in the related [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31613). We shouldn't move forward with this PR until there's an agreement on the issue that this change should be introduced.

**Comment by samiura** [comment]
Thank you all for the comments, I have already closed the issue. Hence, closing the PR here.

**Pull request closed without merging**
