### PR TITLE
Update dependencies Logz.io exporter

### PR DESCRIPTION
**Pull request by yotamloe**
**Description:** <Describe what has changed.>
Logz.io [exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/logzioexporter) upgrade 🚀
Update versions of `jaeger-logzio` -> [1.0.3](https://github.com/logzio/jaeger-logzio), and `logzio-go` -> [1.0.2](https://github.com/logzio/logzio-go) 
**Link to tracking Issue:** <Issue number if applicable>
#3736 and #3702
**Testing:** <Describe what testing was performed and which tests were added.>
No tests added
From logzioexporter directory:
`go test -v -covermode=atomic -race`
output:
```
PASS
coverage: 96.6% of statements
```
**Documentation:** <Describe the documentation added.>
No documentation added

### CODE REVIEW

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
Please split this into upgrade deps/ add functionality

**Comment by yotamloe** [comment]
@bogdandrutu Thanks for your update.
I will open a new PR for new functionalities as soon as this one will be merged

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by bogdandrutu** [comment]
There are some issues, all checks are failing

**Comment by yotamloe** [comment]
@bogdandrutu Thanks a lot for your help. I suspect that `func TestEndToEnd(t *testing.T)` this test of `prometheusexecreceiver` is failing regardless of the changes I made in this PR... I ran it independently from the most updated collector version (not including my PR) and it keep failing. How can we progress?

**Pull request merged**
