### PR TITLE
[receiver/k8sobject] support log body format setting

### LINKED ISSUE #25857: [receiver/k8sobject] request giving a option to use raw json object to represent k8s object
### Component(s)

receiver/k8sobjects

### Describe the issue you're reporting

As an example of the event watcher, the receiver uses the map to represent the event object:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/919e970437054b739ce50998451ea25cfdb1d394/receiver/k8sobjectsreceiver/unstructured_to_logdata.go#L75-L78
this result taht the event JSON format will be like(use file exporter):
```
{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"observedTimeUnixNano":"1692261066062813364","body":{"kvlistValue":{"values":[{"key":"type","value":{"stringValue":"ADDED"}},{"key":"object","value":{"kvlistValue":{"values":[{"key":"lastTimestamp","value":{"stringValue":"2023-08-17T08:31:06Z"}},{"key":"type","value":{"stringValue":"Normal"}},{"key":"reportingComponent","value":{"stringValue":""}},{"key":"apiVersion","value":{"stringValue":"v1"}},{"key":"message","value":{"stringValue":"Started container shell"}},{"key":"firstTimestamp","value":{"stringValue":"2023-08-17T08:31:06Z"}},{"key":"count","value":{"intValue":"1"}},{"key":"eventTime","value":{}},{"key":"kind","value":{"stringValue":"Event"}},{"key":"metadata","value":{"kvlistValue":{"values":[{"key":"resourceVersion","value":{"stringValue":"8018197"}},{"key":"creationTimestamp","value":{"stringValue":"2023-08-17T08:31:06Z"}},{"key":"managedFields","value":{"arrayValue":{"values":[{"kvlistValue":{"values":[{"key":"operation","value":{"stringValue":"Update"}},{"key":"apiVersion","value":{"stringValue":"v1"}},{"key":"time","value":{"stringValue":"2023-08-17T08:31:06Z"}},{"key":"fieldsType","value":{"stringValue":"FieldsV1"}},{"key":"fieldsV1","value":{"kvlistValue":{"values":[{"key":"f:message","value":{"kvlistValue":{}}},{"key":"f:reason","value":{"kvlistValue":{}}},{"key":"f:source","value":{"kvlistValue":{"values":[{"key":"f:component","value":{"kvlistValue":{}}},{"key":"f:host","value":{"kvlistValue":{}}}]}}},{"key":"f:type","value":{"kvlistValue":{}}},{"key":"f:count","value":{"kvlistValue":{}}},{"key":"f:firstTimestamp","value":{"kvlistValue":{}}},{"key":"f:involvedObject","value":{"kvlistValue":{}}},{"key":"f:lastTimestamp","value":{"kvlistValue":{}}}]}}},{"key":"manager","value":{"stringValue":"kubelet"}}]}}]}}},{"key":"name","value":{"stringValue":"node-shell-4113b2c5-d7e8-4b5d-903f-c8c59f0e537b.177c1e793d86209c"}},{"key":"namespace","value":{"stringValue":"kube-system"}},{"key":"uid","value":{"stringValue":"cffdab10-3631-4af5-bdf6-63ea3b6c02bc"}}]}}},{"key":"source","value":{"kvlistValue":{"values":[{"key":"component","value":{"stringValue":"kubelet"}},{"key":"host","value":{"stringValue":"workload-04"}}]}}},{"key":"involvedObject","value":{"kvlistValue":{"values":[{"key":"kind","value":{"stringValue":"Pod"}},{"key":"namespace","value":{"stringValue":"kube-system"}},{"key":"name","value":{"stringValue":"node-shell-4113b2c5-d7e8-4b5d-903f-c8c59f0e537b"}},{"key":"uid","value":{"stringValue":"1299adf6-a2ae-47a2-a19a-a50eadb32e3a"}},{"key":"apiVersion","value":{"stringValue":"v1"}},{"key":"resourceVersion","value":{"stringValue":"8018190"}},{"key":"fieldPath","value":{"stringValue":"spec.containers{shell}"}}]}}},{"key":"reason","value":{"stringValue":"Started"}},{"key":"reportingInstance","value":{"stringValue":""}}]}}}]}},"attributes":[{"key":"k8s.resource.name","value":{"stringValue":"events"}},{"key":"event.domain","value":{"stringValue":"k8s"}},{"key":"event.name","value":{"stringValue":"node-shell-4113b2c5-d7e8-4b5d-903f-c8c59f0e537b.177c1e793d86209c"}}],"traceId":"","spanId":""}]}]}]}
```
after structure, its body looks like this:
```
{
  "body": {
    "kvlistValue": {
      "values": [
        {
          "key": "type",
          "value": {
            "stringValue": "ADDED"
          }
        },
        {
          "key": "object",
          "value": {
            "kvlistValue": {
              "values": [
                {
                  "key": "lastTimestamp",
                  "value": {
                    "stringValue": "2023-08-17T08:31:06Z"
                  }
                },
                {
                  "key": "type",
                  "value": {
                    "stringValue": "Normal"
                  }
                },
                {
                  "key": "reportingComponent",
                  "value": {
                    "stringValue": ""
                  }
                },
                {
                  "key": "apiVersion",
                  "value": {
                    "stringValue": "v1"
                  }
                },
                {
                  "key": "message",
                  "value": {
                    "stringValue": "Started container shell"
                  }
                },
                {
                  "key": "firstTimestamp",
                  "value": {
                    "stringValue": "2023-08-17T08:31:06Z"
                  }
                },
                {
                  "key": "count",
                  "value": {
                    "intValue": "1"
                  }
                },
                {
                  "key": "eventTime",
                  "value": {}
                },
                {
                  "key": "kind",
                  "value": {
                    "stringValue": "Event"
                  }
                },
                {
                  "key": "metadata",
                  "value": {
                    "kvlistValue": {
                      "values": [
                        {
                          "key": "resourceVersion",
                          "value": {
                            "stringValue": "8018197"
                          }
                        },
                        {
                          "key": "creationTimestamp",
                          "value": {
                            "stringValue": "2023-08-17T08:31:06Z"
                          }
                        },
                        {
                          "key": "managedFields",
                          "value": {
                            "arrayValue": {
                              "values": [
                                {
                                  "kvlistValue": {
                                    "values": [
                                      {
                                        "key": "operation",
                                        "value": {
                                          "stringValue": "Update"
                                        }
                                      },
                                      {
                                        "key": "apiVersion",
                                        "value": {
                                          "stringValue": "v1"
                                        }
                                      },
                                      {
                                        "key": "time",
                                        "value": {
                                          "stringValue": "2023-08-17T08:31:06Z"
                                        }
                                      },
                                      {
                                        "key": "fieldsType",
                                        "value": {
                                          "stringValue": "FieldsV1"
                                        }
                                      },
                                      {
                                        "key": "fieldsV1",
                                        "value": {
                                          "kvlistValue": {
                                            "values": [
                                              {
                                                "key": "f:message",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              },
                                              {
                                                "key": "f:reason",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              },
                                              {
                                                "key": "f:source",
                                                "value": {
                                                  "kvlistValue": {
                                                    "values": [
                                                      {
                                                        "key": "f:component",
                                                        "value": {
                                                          "kvlistValue": {}
                                                        }
                                                      },
                                                      {
                                                        "key": "f:host",
                                                        "value": {
                                                          "kvlistValue": {}
                                                        }
                                                      }
                                                    ]
                                                  }
                                                }
                                              },
                                              {
                                                "key": "f:type",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              },
                                              {
                                                "key": "f:count",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              },
                                              {
                                                "key": "f:firstTimestamp",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              },
                                              {
                                                "key": "f:involvedObject",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              },
                                              {
                                                "key": "f:lastTimestamp",
                                                "value": {
                                                  "kvlistValue": {}
                                                }
                                              }
                                            ]
                                          }
                                        }
                                      },
                                      {
                                        "key": "manager",
                                        "value": {
                                          "stringValue": "kubelet"
                                        }
                                      }
                                    ]
                                  }
                                }
                              ]
                            }
                          }
                        },
                        {
                          "key": "name",
                          "value": {
                            "stringValue": "node-shell-4113b2c5-d7e8-4b5d-903f-c8c59f0e537b.177c1e793d86209c"
                          }
                        },
                        {
                          "key": "namespace",
                          "value": {
                            "stringValue": "kube-system"
                          }
                        },
                        {
                          "key": "uid",
                          "value": {
                            "stringValue": "cffdab10-3631-4af5-bdf6-63ea3b6c02bc"
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "key": "source",
                  "value": {
                    "kvlistValue": {
                      "values": [
                        {
                          "key": "component",
                          "value": {
                            "stringValue": "kubelet"
                          }
                        },
                        {
                          "key": "host",
                          "value": {
                            "stringValue": "workload-04"
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "key": "involvedObject",
                  "value": {
                    "kvlistValue": {
                      "values": [
                        {
                          "key": "kind",
                          "value": {
                            "stringValue": "Pod"
                          }
                        },
                        {
                          "key": "namespace",
                          "value": {
                            "stringValue": "kube-system"
                          }
                        },
                        {
                          "key": "name",
                          "value": {
                            "stringValue": "node-shell-4113b2c5-d7e8-4b5d-903f-c8c59f0e537b"
                          }
                        },
                        {
                          "key": "uid",
                          "value": {
                            "stringValue": "1299adf6-a2ae-47a2-a19a-a50eadb32e3a"
                          }
                        },
                        {
                          "key": "apiVersion",
                          "value": {
                            "stringValue": "v1"
                          }
                        },
                        {
                          "key": "resourceVersion",
                          "value": {
                            "stringValue": "8018190"
                          }
                        },
                        {
                          "key": "fieldPath",
                          "value": {
                            "stringValue": "spec.containers{shell}"
                          }
                        }
                      ]
                    }
                  }
                },
                {
                  "key": "reason",
                  "value": {
                    "stringValue": "Started"
                  }
                },
                {
                  "key": "reportingInstance",
                  "value": {
                    "stringValue": ""
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

I expect the body just contain the raw event json object which can easy parse by downstream componment like fluenbit and friendly for storage .etc.

I have not context to know why use map but I suggest that we can have option to control it wheather using map or raw json.

I can sent a PR to imporve it.

### PR DESCRIPTION
**Pull request by Frapschen**
resolve: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25857

### CODE REVIEW

**Comment by Frapschen** [comment]
after enabled this option, the out will like:
```
{
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "observedTimeUnixNano": "1692270279314761000",
              "body": {
                "stringValue": "{\"object\":{\"action\":\"Binding\",\"apiVersion\":\"v1\",\"eventTime\":\"2023-08-17T11:04:39.328643Z\",\"firstTimestamp\":null,\"involvedObject\":{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"name\":\"kpanda-apiserver-5f9767966-fm282\",\"namespace\":\"kpanda-system\",\"resourceVersion\":\"147333625\",\"uid\":\"5495acf1-8e59-4c2b-a635-94504f42a73e\"},\"kind\":\"Event\",\"lastTimestamp\":null,\"message\":\"Successfully assigned kpanda-system/kpanda-apiserver-5f9767966-fm282 to demo-dev-worker5\",\"metadata\":{\"creationTimestamp\":\"2023-08-17T11:04:39Z\",\"managedFields\":[{\"apiVersion\":\"events.k8s.io/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:action\":{},\"f:eventTime\":{},\"f:note\":{},\"f:reason\":{},\"f:regarding\":{},\"f:reportingController\":{},\"f:reportingInstance\":{},\"f:type\":{}},\"manager\":\"kube-scheduler\",\"operation\":\"Update\",\"time\":\"2023-08-17T11:04:39Z\"}],\"name\":\"kpanda-apiserver-5f9767966-fm282.177c26da5f55dd03\",\"namespace\":\"kpanda-system\",\"resourceVersion\":\"147333630\",\"uid\":\"d37fd962-f8e5-4c4e-9e7a-b6ba8cdd0b82\"},\"reason\":\"Scheduled\",\"reportingComponent\":\"default-scheduler\",\"reportingInstance\":\"default-scheduler-demo-dev-master2\",\"source\":{},\"type\":\"Normal\"},\"type\":\"ADDED\"}"
              },
              "attributes": [
                {
                  "key": "k8s.resource.name",
                  "value": {
                    "stringValue": "events"
                  }
                },
                {
                  "key": "event.domain",
                  "value": {
                    "stringValue": "k8s"
                  }
                },
                {
                  "key": "event.name",
                  "value": {
                    "stringValue": "kpanda-apiserver-5f9767966-fm282.177c26da5f55dd03"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

The event is well formatted into JSON and saved in the body, it's easy to handle for downstream components. if we sent it to Fluentbit, it's `stdout` plugin print:
```
[121] v1_logs: [[1692270283.406964094, {"k8s.resource.name"=>"events", "event.domain"=>"k8s", "event.name"=>"skoala-ui-5fcfddf54b-5mnlx.177c1673fcc40020"}], {"message"=>"{"object":{"apiVersion":"v1","count":2,"eventTime":null,"firstTimestamp":"2023-08-17T06:04:07Z","involvedObject":{"apiVersion":"v1","fieldPath":"spec.containers{skoala-ui-container}","kind":"Pod","name":"skoala-ui-5fcfddf54b-5mnlx","namespace":"skoala-system","resourceVersion":"146563301","uid":"7ef3ca2d-fcf9-44ca-a50b-8ec7f176cf5d"},"kind":"Event","lastTimestamp":"2023-08-17T10:04:19Z","message":"Liveness probe failed: Get \"http://10.233.127.31:15020/app-health/skoala-ui-container/livez\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","metadata":{"creationTimestamp":"2023-08-17T10:04:23Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:source":{"f:component":{},"f:host":{}},"f:type":{}},"manager":"kubelet","operation":"Update","time":"2023-08-17T10:04:23Z"}],"name":"skoala-ui-5fcfddf54b-5mnlx.177c1673fcc40020","namespace":"skoala-system","resourceVersion":"147333771","uid":"2937878d-7092-46bd-8b4b-1fa12b78d5c5"},"reason":"Unhealthy","reportingComponent":"","reportingInstance":"","source":{"component":"kubelet","host":"demo-dev-master1"},"type":"Warning"},"type":"DELETED"}"}]
```

if we sent the event log in map format, Fluentbit will encounter the error:
```
[2023/08/17 17:01:04] [error] [otel]: invalid value type in pack_any_value
[2023/08/17 17:01:04] [error] [otel] Failed to convert log record body
[2023/08/17 17:01:04] [error] [otel] marshalling error
```

**Comment by crobert-1** [comment]
Failing test is frequency of issue #25849

**Review by dmitryax — CHANGES_REQUESTED** [review]
I don't think this is something that should be added to the receiver. Let's continue the discussion in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25857#issuecomment-1682909967

**Review by TylerHelmuth — COMMENTED** [review]
I agree with @dmitryax, I shared my thoughts in the issue.

**Pull request closed without merging**
