### PR TITLE
Improving the error message when failing to sign the request

### PR DESCRIPTION
**Pull request by alanprot**
**Description:** <Describe what has changed.>
Improving the error message when failing to sign the request.

When using roleArn and agent fail to talk to STS, the error message can be very missleading.

Ex:

If the container has no network to STS, the error logged will be something like:

```
Permanent error: Post \"https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-some-id/api/v1/remote_write\": RequestCanceled: request context canceled\ncaused by: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Wrapping this error make clear that the error was actually signing the request and not when calling the service (AWS Prometheus).

### CODE REVIEW

**Review by Aneurysm9 — COMMENTED** [review]
Please add a changelog entry.

**Review by codeboten — COMMENTED** [review]
Thanks for the contribution @alanprot! Please address @Aneurysm9's comments and we can get this merged!

**Comment by jeromeinsf** [comment]
This is still a valid PR

**Review by alolita — APPROVED** [review]

**Comment by jeromeinsf** [comment]
@anuraaga  Can you please review this PR?

**Comment by jeromeinsf** [comment]
> This PR was marked stale due to lack of activity. It will be closed in 7 days.

Once again, this is still a valid PR and I believe the comments were addressed

**Review by anuraaga — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Pull request merged**
