### PR TITLE
Moving fluentforwardreceiver to contrib repo.

### PR DESCRIPTION
**Pull request by paulosman**
**Description:** 

This is one of two PRs intended to address https://github.com/open-telemetry/opentelemetry-collector/issues/2675. This PR adds fluentforwardreceiver to the contrib repo, the other removes it from the [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) repo.

Collector Repo PR: https://github.com/open-telemetry/opentelemetry-collector/pull/2723

**Link to tracking Issue:** 

https://github.com/open-telemetry/opentelemetry-collector/issues/2675

**Testing:** 

Confirmed that the project builds locally.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please also move TestLog10kDPS/FluentBitToOTLP from core to this repo.

**Comment by paulosman** [comment]
> Please also move TestLog10kDPS/FluentBitToOTLP from core to this repo.

Done - unfortunately, it's failing, but I can't see how that would be related to this change. Maybe the test is brittle/flappy?

**Comment by bogdandrutu** [comment]
@paulosman looks like no data are received, may be something with ports?

**Comment by tigrannajaryan** [comment]
I believe Fluentbit needs to be installed on CI. These bits need to come from core repo (and remove them from there):
https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.github/workflows/build-and-test.yml#L247
https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.circleci/config.yml#L94

**Comment by bogdandrutu** [comment]
@paulosman please make sure you also install fluentbit in circleci

**Comment by paulosman** [comment]
> I believe Fluentbit needs to be installed on CI. These bits need to come from core repo (and remove them from there):
> https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.github/workflows/build-and-test.yml#L247
> https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.circleci/config.yml#L94

Done. E2E tests seem to be passing now! Thanks.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
