### PR TITLE
[exporter/prometheus] Exemplars for monotonic sums

### PR DESCRIPTION
**Pull request by ghost**
**Description:** 

This will add metrics exemplars to the Prometheus exporter for monotonic sum metrics (i.e. counters in Prometheus).  Note that this could possibly be a breaking change if users are producing monotonic sums with exemplars, have enabled open metrics export format in this exporter and exemplar ingest in Prometheus, but have not enabled the `pkg.translator.prometheus.NormalizeName` feature gate and their metric names do not already follow the convention required by OpenMetrics, i.e. the name ends in `_total`.  In the breaking cases, the exporter reports the type of the metric as `unknown` and then Prometheus appears to drop the metric on ingest due to the presence of the exemplar data.

As the feature gate is currently private to the prometheus translator package, wasn't sure how best to proceed:
1. make the translater package feature gate public and only produce exemplars on counters if enabled.
2. create an additional option/feature gate to control counter exemplar output.
3. Do nothing and just mark the change as breaking in the changelog.

**Link to tracking Issue:** #18201 

**Testing:**

Unit tests have been added to ensure exemplars get produced when converting OTel monotonic sums.
I've also tested this manually with the [OTel demo project](https://github.com/open-telemetry/opentelemetry-demo).

**Documentation:**

Updated README to include a note about which metric types currently support exemplars.

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Review by kovrus — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please rebase to pick up changes to run go1.20 unit tests

**Comment by jlawrienyt** [comment]
> Please rebase to pick up changes to run go1.20 unit tests

Done

**Comment by jlawrienyt** [comment]
@dashpole or @codeboten can you approve the workflow so that it runs tests/linting/etc?

**Comment by jlawrienyt** [comment]
Hey folks, anything else I need to do here before this is merged?

**Review by codeboten — APPROVED** [review]

**Pull request merged**
