### PR TITLE
[receiver/jaeger] mark featuregates as stable

### PR DESCRIPTION
**Pull request by codeboten**
This allows us to remove the deprecated modules. Pinging @frzifus as the original author

### CODE REVIEW

**Review by frzifus — COMMENTED** [review]
Does it make sense to wait? Since the featuregate never worked.

**Comment by codeboten** [comment]
@frzifus it does, i meant to leave this as a draft to see if some of the other deps can be updated once this is removed

**Comment by MovieStoreGuy** [comment]
> Does it make sense to wait? Since the featuregate never worked.

Is there anything you wanted to wait for?

**Comment by dmitryax** [comment]
@frzifus can you please clarify why the feature gate never worked?

**Comment by frzifus** [comment]
Sure, the gate is evaluated inside the factory function. Since this function is called right at the beginning when the collector starts, the  command line arguments are not parsed. Therefore its always "disabled".

It should be fixed once https://github.com/open-telemetry/opentelemetry-collector/pull/8478 is merged.

cc @dmitryax

**Comment by codeboten** [comment]
@frzifus now that 0.89.0 is out and the feature gate issue has been addressed, should this PR be revived for the next release?

**Comment by frzifus** [comment]
sure, since it does not work for so long, it should be removed in 0.91.0, right?

**Comment by codeboten** [comment]
with v0.90.0 out, this should be good to go now. @frzifus @dmitryax

**Review by frzifus — APPROVED** [review]
Yes, thx!

**Comment by atoulme** [comment]
`panic: no removal version set for Stable gate "receiver.jaegerreceiver.replaceThriftWithProto"`

**Review by atoulme — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]
🎉

**Pull request merged**
