### PR TITLE
[exporter/kinetica] mark Unmaintained

### PR DESCRIPTION
**Pull request by TylerHelmuth**
#### Description

This exporter was added as a vendor-specific component via https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24294. It [no longer has its vendor sponsor as a code owner](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36229). 

Following our [Unmaintained guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/component-stability.md#unmaintained), this component is now considered unmaintained.

@am-kinetica @kyle-sutton please respond if Kinetica is interested in continuing to maintain this component.

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
Reviewed the component and agreeing with the diagnosis.

**Comment by am-kinetica** [comment]
@TylerHelmuth @atoulme We at Kinetica are certainly interested in maintaining the exporter component and contributing updates and fixes to it. We were off track for some time but do plans around it. What do we have to do ? Thanks.

**Comment by TylerHelmuth** [comment]
@am-kinetica please follow [these instructions](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#member) to become of the open telemetry org and then you can be a code owner again.

**Comment by am-kinetica** [comment]
@TylerHelmuth - I think I have already become a member. What do I need to do to remove the `unmaintained` status ?

**Comment by TylerHelmuth** [comment]
@am-kinetica please open a PR to change its status

**Comment by am-kinetica** [comment]
@TylerHelmuth What are the steps to follow to get rid of the unmaintained status for the kinetica-exporter ?

**Pull request merged**
