### PR TITLE
Cleanup more deps in all modules

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by jrcamp — APPROVED** [review]
🧹

**Review by jrcamp — CHANGES_REQUESTED** [review]
nm, tests failed :(

**Comment by bogdandrutu** [comment]
I like the "github.com/microsoft/ApplicationInsights-Go" vs "github.com/Microsoft/ApplicationInsights-Go" 👎

**Review by jrcamp — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@jrcamp can you approve?

**Pull request merged**
