### PR TITLE
[chore] move logicmonitor exporter to generated lifecycle tests

### PR DESCRIPTION
**Pull request by Frapschen**
Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27849

### CODE REVIEW

**Review by songy23 — APPROVED** [review]
LGTM, pinging code owners @khyatigandhi6, @avadhut123pisal

**Review by atoulme — APPROVED** [review]
LGTM

**Comment by atoulme** [comment]
Pinging code owners @bogdandrutu @khyatigandhi6 @avadhut123pisal

**Comment by avadhut123pisal** [comment]
LGTM.

**Pull request merged**
