### PR TITLE
Switch SAPM receiver to internal data model

### PR DESCRIPTION
**Pull request by dmitryax**

### CODE REVIEW

**Comment by dmitryax** [comment]
@tigrannajaryan please take a look

**Review by tigrannajaryan — APPROVED** [review]
Please post before/after perf test results once we have both receiver and exporter merged.

**Comment by dmitryax** [comment]
Performance degraded because we introduced OTLP translation additionally to OC. Once exporter is migrated it should be improved. Test results:

Before:
```
Test                                    |Result|Duration|CPU Avg%|CPU Max%|RAM Avg MiB|RAM Max MiB|Sent Items|Received Items|
----------------------------------------|------|-------:|-------:|-------:|----------:|----------:|---------:|-------------:|
Metric10kDPS/OpenCensus                 |PASS  |     17s|    31.7|    33.7|         30|         38|   1047200|       1047200|
Trace10kSPS/SAPM                        |PASS  |     15s|    26.8|    27.7|         44|         55|    150000|        150000|
```

After:
```
Test                                    |Result|Duration|CPU Avg%|CPU Max%|RAM Avg MiB|RAM Max MiB|Sent Items|Received Items|
----------------------------------------|------|-------:|-------:|-------:|----------:|----------:|---------:|-------------:|
Trace10kSPS/SAPM                        |PASS  |     15s|    29.0|    30.0|         52|         64|    149000|        149000|
```

**Review by pjanotti — APPROVED** [review]
LGTM

**Comment by tigrannajaryan** [comment]
> Performance degraded because we introduced OTLP translation additionally to OC. Once exporter is migrated it should be improved. Test results:

@dmitryax makes sense. Let's see where we land after migrating the exporter. It will be useful to compare "before" results from this PR to "after" results when exporter is also migrated.

**Pull request merged**
