### PR TITLE
[chore] remove toolchain directive

### PR DESCRIPTION
**Pull request by codeboten**
Unclear why these ended up here, removing them.

### CODE REVIEW

**Review by bryan-aguilar — APPROVED** [review]

**Comment by bryan-aguilar** [comment]
```
 cd /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/tools && go build -o /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/builder -trimpath go.opentelemetry.io/collector/cmd/builder
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/builder --skip-compilation --config cmd/otelcontribcol/builder-config.yaml --output-path cmd/otelcontribcol
Flag --output-path has been deprecated, use config distribution::output_path
2024-02-13T16:25:27.662Z	INFO	internal/command.go:123	OpenTelemetry Collector Builder	{"version": "", "date": "unknown"}
2024-02-13T16:25:27.666Z	INFO	internal/command.go:159	Using config file	{"path": "cmd/otelcontribcol/builder-config.yaml"}
2024-02-13T16:25:27.666Z	INFO	builder/config.go:109	Using go	{"go-executable": "/opt/hostedtoolcache/go/1.21.7/x64/bin/go"}
2024-02-13T16:25:27.667Z	INFO	builder/main.go:67	You're building a distribution with non-aligned version of the builder. Compilation may fail due to API changes. Please upgrade your builder or API	{"builder-version": "0.94.0"}
2024-02-13T16:25:27.674Z	INFO	builder/main.go:91	Sources created	{"path": "cmd/otelcontribcol"}
2024-02-13T16:25:27.674Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["get", "cloud.google.com/go"]}
2024-02-13T16:25:28.070Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["mod", "tidy", "-compat=1.20"]}
2024-02-13T16:25:28.606Z	INFO	builder/main.go:142	Getting go modules
2024-02-13T16:25:28.606Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["mod", "download"]}
2024-02-13T16:25:28.735Z	INFO	builder/main.go:98	Generating source codes only, the distribution will not be compiled.
make --no-print-directory -C cmd/otelcontribcol fmt
Makefile:4: warning: overriding recipe for target 'lint'
../../Makefile.Common:197: warning: ignoring old recipe for target 'lint'
cd /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/tools && go build -o /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/goimports -trimpath golang.org/x/tools/cmd/goimports
gofmt  -w -s ./
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/goimports -w  -local github.com/open-telemetry/opentelemetry-collector-contrib ./
Generated code is out of date, please run "make genotelcontribcol" and commit the changes in this PR.
```

**Comment by TylerHelmuth** [comment]
@codeboten ready to rebase

**Review by songy23 — APPROVED** [review]
Need another rebase

**Comment by atoulme** [comment]
rebased

**Comment by atoulme** [comment]
It fails because the dependency on the builder is different from the rest of core, we need to update all of core dependencies.

**Review by djaglowski — APPROVED** [review]

**Comment by atoulme** [comment]
Should this PR be closed?

**Review by atoulme — APPROVED** [review]

**Pull request merged**
