### PR TITLE
[receiver/kubeletstats] Add pod and container state metrics

### PR DESCRIPTION
**Pull request by sirianni**
# Description
Add the following state metrics to `kubeletstats` receiver:
* `k8s.pod.state`
* `k8s.container.state`
* `k8s.container.last_termination_state`

### Note
There is potential overlap here with the following metrics from `k8sclusterreceiver`
* [`k8s.pod.phase`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/documentation.md#k8spodphase)
* [`k8s.pod.status_reason`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/documentation.md#k8spodstatus_reason)
* [`k8s.container.ready`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8sclusterreceiver/documentation.md#k8scontainerready)

The above metrics don't work well for our use case for two main reasons:
1. These metrics encode the enumeration in the metric value, instead of as an attribute.  See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24425 for more details.
2. There are scalability issues in collecting this from the `k8sclusterreciver` singleton.  Collecting these metrics directly from the `kubelet` via a daemonset OTel Collector deployment pattern scales nicely with the size of the k8s cluster.

# Testing
A new unit test was added using the `pods.json` test fixture.

This was also tested manually using the `debug` exporter.

#### `k8s.container.state` metric
```
ResourceMetrics #11
Resource SchemaURL: 
Resource attributes:
     -> k8s.pod.uid: Str(317c571a-affc-4039-8fba-7fa6992b84ed)
     -> k8s.pod.name: Str(nginx-75bf547d49-27jhb)
     -> k8s.namespace.name: Str(default)
     -> k8s.container.name: Str(nginx)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/kubeletstatsreceiver development
Metric #0
Descriptor:
     -> Name: k8s.container.state
     -> Description: Current state of the container
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> state: Str(waiting)
     -> reason: Str(ImagePullBackOff)
StartTimestamp: 2023-10-25 15:09:54.571128664 +0000 UTC
Timestamp: 2023-10-25 15:09:55.612832344 +0000 UTC
Value: 1
```

#### `k8s.pod.state` metric
```
ResourceMetrics #20
Resource SchemaURL: 
Resource attributes:
     -> k8s.pod.uid: Str(e4becd6e-cf43-4b24-9724-3e7faf757124)
     -> k8s.pod.name: Str(sirianni-test)
     -> k8s.namespace.name: Str(default)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope otelcol/kubeletstatsreceiver development
Metric #0
Descriptor:
     -> Name: k8s.pod.state
     -> Description: Current state of the pod
     -> Unit: 1
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> phase: Str(Running)
     -> reason: Str()
StartTimestamp: 2023-10-25 15:35:28.270921058 +0000 UTC
Timestamp: 2023-10-25 15:35:29.318908321 +0000 UTC
Value: 1
```

My company is also running this code in production.  Here are some screenshots showing how we use it in the Datadog UI
image
image

# Documentation
New metrics are added automatically to `documentation.md`

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@sirianni are you available to bring this issue/pr up at a SIG meeting?

**Comment by sirianni** [comment]
> @sirianni are you available to bring this issue/pr up at a SIG meeting?

When is the meeting?

**Comment by sirianni** [comment]
Here is the [Datadog Agent PR](https://github.com/DataDog/integrations-core/pull/2605) I referenced in today's SIG call that mentions the scalability issues using a cluster-wide collector (i.e. kube-state-metrics) for this data.

**Comment by cmergenthaler** [comment]
Why has this been closed? If there are scaling issues with the current solution, wouldn't it make sense to include it in the kubelet receiver?

**Comment by sirianni** [comment]
> IMO Resource model is well documented in otel, its not really a signal but the way otel represents entities.

Yes, I am aware of that.  But can you answer my specific questions?  

OTel does not specify a mechanism to track, encode, and export "state changes" to resource attributes as first-class things.

**Comment by sirianni** [comment]
> we transmit them with logs, traces, metrics.

But what metric would you transmit it with?  All of them?  And how would this be queried?  In most backends you can't query "resource attributes" as first class things.  Resource attributes are simply extra tags on metrics.

This is what I meant by "piggybacking of an existing metric".

**Pull request closed without merging**
