### PR TITLE
[processor/servicegraph] Add to component list

### PR DESCRIPTION
**Pull request by mapno**
**Description:** Adds the `servicegraph` processor to the component list, to be included in the contrib distribution.

**Link to tracking Issue:** #14899

### CODE REVIEW

**Comment by JaredTan95** [comment]
@mapno hi, If we want to release components in the final dist. we also need to update the manifest in https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml.
would you be able to open a PR to update it?

**Comment by sherifkayad** [comment]
@JaredTan95 @mapno I initially thought it's a releaser issue and filed https://github.com/open-telemetry/opentelemetry-collector-releases/issues/217 .. I think the servicegraphprocessor needs to be included to the release manifest yes.

**Comment by mapno** [comment]
Thanks for the review @JaredTan95. Fixed the lint issues (hopefully) and opened a PR to the releases repository.

**Review by JaredTan95 — APPROVED** [review]
LGTM

**Comment by dmitryax** [comment]
The process is marked as _in development_. Please update it at least to Alpha if it's ready before merging this

**Comment by sherifkayad** [comment]
@dmitryax I think that would make sense to set the status as alpha or something .. however, the Span Processor is also development and is released in the contrib image.. just for my understanding, if plug-ins are in development, does this mean they shouldn't be included in the release?

**Comment by dmitryax** [comment]
> just for my understanding, if plug-ins are in development, does this mean they shouldn't be included in the release?

Yes, I believe it does. Even if it's dont stated anywhere. This is

**Comment by dmitryax** [comment]
_In development_ status says that it's not ready for use. We don't want to add components in distributions that are not ready.

From the docs describing _In development_ status:

> Not all pieces of the component are in place yet and it might not be available as part of any distributions yet

Does servicegraph processor have all the pieces in place and can be actually used?

**Comment by sherifkayad** [comment]
@mapno maybe you also need to change the stability in the README file of the plug-in? .. I remember seeing it as development earlier.

**Review by jpkrohling — COMMENTED** [review]
Once the readme is changed with the new stability level, this will be ready to be merged.

**Comment by mapno** [comment]
Done now 👍

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
