### PR TITLE
[docs] Add status header for awskinesis exporter

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>
Add status header for awskinesis,pls review :)

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
The change looks good, pinging @Aneurysm9 @MovieStoreGuy to confirm stability status

**Comment by Frapschen** [comment]
@Aneurysm9 @MovieStoreGuy can you review this PR?

**Comment by Frapschen** [comment]
can I mark this exporter as alph since the owners not reply anything for a long time and get this PR merged ?

**Review by Aneurysm9 — APPROVED** [review]

**Comment by codeboten** [comment]
Retriggering CI by closing/opening PR

**Review by codeboten — APPROVED** [review]

**Pull request merged**
