### PR TITLE
[exporter/prometheusremotewrite] Dead links 

### LINKED ISSUE #10979: [exporter/prometheusremotewrite] Dead links
```
(cd exporter/prometheusremotewrite && make checklinks)

FILE: ./README.md

  5 links checked.

FILE: ./DESIGN.md
  [✖] #1.2-gaps-and-assumptions

  12 links checked.

  ERROR: 1 dead links found!
  [✖] #1.2-gaps-and-assumptions → Status: 404
```

### PR DESCRIPTION
**Pull request by my-git9**
fix: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10979

### CODE REVIEW

**Comment by djaglowski** [comment]
Another link on this component appears to be failing.
```
FILE: exporter/prometheusremotewriteexporter/DESIGN.md
  [✓] https://cortexmetrics.io/docs/api/ → Status: 200
  [✓] https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/ → Status: 200
  [✓] https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage → Status: 200
  [✓] https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto#L22 → Status: 200
  [✓] https://prometheus.io/docs/prometheus/latest/storage/#overview → Status: 200
  [✓] https://github.com/open-telemetry/opentelemetry-collector/issues/[12](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:13)55 → Status: 200
  [✖] https://github.com/open-telemetry/opentelemetry-collector/issues/1422 → Status: 404
  [✓] https://github.com/open-telemetry/opentelemetry-specification/issues/731 → Status: 200
  [✓] https://github.com/spf[13](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:14)/viper → Status: 200
  [✓] #12-gaps-and-assumptions → Status: 200
  [✓] img/cortex.png → Status: 200
  [✓] img/timeseries.png → Status: 200
  12 links checked.
  ERROR: 1 dead links found!
  [✖] https://github.com/open-telemetry/opentelemetry-collector/issues/[14](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:15)[22](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:23) → Status: 404
Check that anchor links are lowercase
Error: Process completed with exit code 1.
```

**Comment by my-git9** [comment]
> Another link on this component appears to be failing.
> 
> ```
> FILE: exporter/prometheusremotewriteexporter/DESIGN.md
>   [✓] https://cortexmetrics.io/docs/api/ → Status: 200
>   [✓] https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/ → Status: 200
>   [✓] https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage → Status: 200
>   [✓] https://github.com/prometheus/prometheus/blob/master/prompb/remote.proto#L22 → Status: 200
>   [✓] https://prometheus.io/docs/prometheus/latest/storage/#overview → Status: 200
>   [✓] https://github.com/open-telemetry/opentelemetry-collector/issues/[12](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:13)55 → Status: 200
>   [✖] https://github.com/open-telemetry/opentelemetry-collector/issues/1422 → Status: 404
>   [✓] https://github.com/open-telemetry/opentelemetry-specification/issues/731 → Status: 200
>   [✓] https://github.com/spf[13](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:14)/viper → Status: 200
>   [✓] #12-gaps-and-assumptions → Status: 200
>   [✓] img/cortex.png → Status: 200
>   [✓] img/timeseries.png → Status: 200
>   12 links checked.
>   ERROR: 1 dead links found!
>   [✖] https://github.com/open-telemetry/opentelemetry-collector/issues/[14](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:15)[22](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6946077624?check_suite_focus=true#step:4:23) → Status: 404
> Check that anchor links are lowercase
> Error: Process completed with exit code 1.
> ```

Thanks for your review, this issue https://github.com/open-telemetry/opentelemetry-collector/issues/1422 seems miss. 
Shoud we delete the link or a whole sentence？

**Comment by djaglowski** [comment]
I'm not familiar enough with this component to suggest that we should change the contents of the readme. Ideally, we will figure out why this link is reported as dead and make the appropriate change. (I don't see why the tool suggests it is 404, but we should figure this out if possible.)

**Comment by my-git9** [comment]
> I'm not familiar enough with this component to suggest that we should change the contents of the readme. Ideally, we will figure out why this link is reported as dead and make the appropriate change. (I don't see why the tool suggests it is 404, but we should figure this out if possible.)

I found the issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4968
The pr: https://github.com/open-telemetry/opentelemetry-collector/pull/1422 will be redirect to issue:https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4968

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
