### PR TITLE
[receiver/apachespark] Adding Spark receiver implementation

### PR DESCRIPTION
**Pull request by mrsillydog**
Description: Implementation of an OTel receiver for Apache Spark.

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21046

Testing: Manual testing against a locally running Spark instance, automated unit testing, and automated integration testing against a Spark instance in a docker container.

Documentation: Standard OTel documentation.

### CODE REVIEW

**Comment by mrsillydog** [comment]
I've moved this into Ready for Review despite the gendependabot failure - running make gendependabot locally hasn't resulted in any changes, so I'm hopeful that getting feedback going will give me a better opportunity to roll that fix in with others.

**Comment by djaglowski** [comment]
@mrsillydog, please rebase and try `make gendependabot` again.

**Comment by djaglowski** [comment]
@mrsillydog, this PR is too large to be reviewed properly. Please break it up into several PRs. [This documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component) provides general guidelines but roughly:

1. All the files where the receiver is simply added to a list of components, plus the config and factory.
2. Metrics defined in metadata.yaml, as well as all files generated from this.
3. The remainder of the implementation.

**Comment by mrsillydog** [comment]
@djaglowski First of the three PRs is [here.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21971)

**Comment by mrsillydog** [comment]
For posterity: the contents of this pull request were reviewed, revised, and merged in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22017 and  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22163

**Pull request closed without merging**
