### PR TITLE
Prometheus fix inf bucket count

### PR DESCRIPTION
**Pull request by balintzs**
**Description:** <Describe what has changed.>
`+Inf` bucket counts are handled incorrectly in both `prometheusexporter` and `prometheusremotewriteexporter`.

In prometheus this bug was taken care of by the following PR: https://github.com/prometheus/client_golang/pull/1148
For `prometheusremotewriteexporter` we need to make the same fix and assign value of the total count to the `+Inf` bucket as well.

This issue caused New Relic to drop our histogram datapoints that had invalid values. It was a problem with 0.61.0 as well, but became much worse with 0.62.0. We built a custom image updating `github.com/prometheus/client_golang` to the SHA version (`dcea97eee2b3257f34fd3203cb922eedeabb42a6`) that contained our fix and the issue disappeared:
Screenshot 2022-10-19 at 12 48 49

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4975

### CODE REVIEW

**Review by dashpole — APPROVED** [review]
lgtm

Are you planning to fix the prometheus exporter separately?

**Comment by balintzs** [comment]
> Are you planning to fix the prometheus exporter separately?

This change fixed it: https://github.com/prometheus/client_golang/pull/1148

Or is there something I missed?

**Comment by dashpole** [comment]
I just noticed a change in pkg/translator/prometheusremotewrite/helper.go, but not in the prometheus exporter.  Is the dependency bump all that is required for that exporter?

**Comment by balintzs** [comment]
> I just noticed a change in pkg/translator/prometheusremotewrite/helper.go, but not in the prometheus exporter. Is the dependency bump all that is required for that exporter?

Yes, as far as I can tell, that is all that is required.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
