### PR TITLE
fluentforwardreceiver: register metrics view to expose metrics

### PR DESCRIPTION
**Pull request by pmalek-sumo**
**Description:** Register the metrics which are already defined in the receiver but unregistered.

**Link to tracking Issue:** N/A

**Testing:** N/A

**Documentation:** N/A

### CODE REVIEW

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
Using of opencensus in the collector for metrics is discourage since we need to move to otel-go, I think we should postpone this unless critical.

**Comment by pmalek-sumo** [comment]
> Using of opencensus in the collector for metrics is discourage since we need to move to otel-go, I think we should postpone this unless critical.

Is there an issue that tracks this? Is there an alternative that we can use or a plugin that already uses `otel-go` that I could base my work on?

**Comment by pmalek-sumo** [comment]
It seems we'll have to wait for https://github.com/open-telemetry/opentelemetry-collector/issues/4198.

**Comment by pmalek-sumo** [comment]
It seems that this was not merged due to 

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5857#pullrequestreview-785910246

but a bit later on, this one got merged https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6363

using the same `"go.opencensus.io/stats/view"` for exporting metrics. If that's the case can we then revisit this PR (I can push it once again) and review it?

@bogdandrutu ?

**Pull request closed without merging**
