### PR TITLE
Add support of Pod UID extraction to k8sprocessor

### PR DESCRIPTION
**Pull request by dmitryax**
This commit allows to extract k8s Pod UID and set it as "k8s.pod.uid" attribute according to OpenTelemetry conventions

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]
LGTM. We may need to submit semantic convention to add "k8s.pod.uid" to https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions#kubernetes later.

**Review by owais — APPROVED** [review]

**Comment by owais** [comment]
LGTM

**Comment by dmitryax** [comment]
> LGTM. We may need to submit semantic convention to add "k8s.pod.uid" to https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions#kubernetes later.

Sounds good. I'll submit a PR once we make it work on our end

**Comment by dmitryax** [comment]
@tigrannajaryan @owais could you merge it? I don't have permissions for that

**Pull request merged**
