### PR TITLE
[chore] first pass at cleaning up license

### PR DESCRIPTION
**Pull request by codeboten**
Linked to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21288

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Comment by dmitryax** [comment]
Same comment as in https://github.com/open-telemetry/opentelemetry-collector/pull/7589#issuecomment-1530591734

**Comment by atoulme** [comment]
We can just clean up the files in this PR and discuss the tooling in a separate PR.

**Comment by codeboten** [comment]
After discussing this w/ @dmitryax, we agreed that it makes sense to check the license using the same check as the opentelemetry-go-build-tools repo, as addlicense doesn't check the formatting of the license.

I've updated `checklicense` to use `awk` instead.

**Review by dmitryax — APPROVED** [review]
LGTM. @codeboten thank you!

**Pull request merged**
