### PR TITLE
Trigger windows e2e tests when windows-related files change

### PR DESCRIPTION
**Pull request by ArthurSens**
#### Description
We've noticed that many of the CI failures on main come from Windows e2e tests. We want to be more proactive in catching those failures, so this PR changes the workflow triggering Windows e2e tests to ensure they run on Pull Requests that change Windows-related files, even if the label `Run Windows` is absent.

It does so by looking at changed files. If the word `windows` is present in the file name, it triggers the workflow.

#### Link to tracking issue
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36788

### CODE REVIEW

**Review by songy23 — APPROVED** [review]
LGTM

cc @pjanotti

**Review by dmitryax — APPROVED** [review]
LGTM. It can help in some cases, but it doesn't provide a strong guarantee that we catch any change breaking windows tests. I think we need to enable them on merge queue.

**Comment by ArthurSens** [comment]
> LGTM. It can help in some cases, but it doesn't provide a strong guarantee that we catch any change breaking windows tests. I think we need to enable them on merge queue.

Sounds good to me, we can revert this PR once merge queue is enabled :)

**Comment by dmitryax** [comment]
> If I understand correctly, merge queues only run workflows marked as required on PRs. That means that we'd need to run windows tests on every PR, right?

I'm not sure, but my understanding is that it's not required. We could make Windows tests be required on merge queue but not run them for every PR. @mx-psi @jade-guiton-dd please correct me

**Pull request merged**
