### PR TITLE
[exporter/logicmonitorexporter] Response handling mechanism changes

### PR DESCRIPTION
**Pull request by khyatigandhi6**
**Description:** <Describe what has changed.>
1. Instead of single log message, multiple log messages can be sent in single request.
2. Response handling mechanism is changed.

**Testing:** 
Unit Test Cases

### CODE REVIEW

**Comment by khyatigandhi6** [comment]
There are no user facing changes. Please add 'Skip Changelog' label.

**Comment by mx-psi** [comment]
@avadhut123pisal can you take a look?

**Comment by avadhut123pisal** [comment]
> @avadhut123pisal can you take a look?

sure.

**Comment by avadhut123pisal** [comment]
LGTM

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
