### PR TITLE
[docs] Add status header for awsfirehose receiver

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>
Add status header for awsfirehose receiver.

### CODE REVIEW

**Comment by mx-psi** [comment]
@pjanotti to review as a CODEOWNER

**Comment by Frapschen** [comment]
@pjanotti can you have time to review this PR?

**Comment by djaglowski** [comment]
I suggest we label this as alpha for now. @pjanotti please propose another status if you disagree.

**Comment by Frapschen** [comment]
change status header to alpha.

**Comment by mx-psi** [comment]
Can you fix the merge conflict @Frapschen ?

**Comment by Frapschen** [comment]
> Can you fix the merge conflict @Frapschen ?

done

**Comment by mx-psi** [comment]
:( looks like Github Actions have decided not to run. Mind pushing an empty commit @Frapschen? You can do (assuming you have no staged changes):

```
git commit -m "[empty] retrigger CI" --allow-empty
```

**Comment by Frapschen** [comment]
#11174 tall why ci  not triggered

**Review by codeboten — APPROVED** [review]

**Pull request merged**
