### PR TITLE
dockerstatsreceiver: migrate to newer semconv version

### PR DESCRIPTION
**Pull request by narcis96**
Description: The version of semconv is upgraded from v1.6.1 to v1.27.0

This is a trivial upgrade. The semconv attributes' value have been compared using [go-otel-semconv-comparator](https://github.com/narcis96/go-otel-semconv-comparator). All attributes used by this component have the same value in both versions.

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095

Testing: Tests passed

### CODE REVIEW

**Comment by narcis96** [comment]
PTAL 

@rmfitzpatrick
@jamesmoessis
@andrzej-stencel

**Review by jamesmoessis — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]

**Comment by narcis96** [comment]
PTAL @rmfitzpatrick

**Comment by narcis96** [comment]
Kind reminder @rmfitzpatrick @mx-psi

**Comment by mx-psi** [comment]
Needs `make generate`

**Comment by narcis96** [comment]
> Needs `make generate`

done

**Pull request merged**
