### PR TITLE
receiver: add UNIX Domain Socket receiver

### LINKED ISSUE #396: receiver: add OpenCensus-PHP-Daemon
Last year, we designed a daemon that'd receive stats from individual PHP processes and then apply aggregations on them before forwarding them to the agent as per https://docs.google.com/document/d/1CRiRq_wpzOuG9VKM_eaImcrS12Iie2V7LePnH9AwclU/ and it receives data via a UNIX Domain Socket. The daemon is currently present at https://github.com/census-instrumentation/opencensus-php/tree/1327147dc2ea99c06df01db4daa8c4ab2656514d/daemon.

That requires OpenCensus-PHP users to deploy that local daemon which is an extra tack on and not too flexible for OpenCensus-PHP users. This issue is a feature request for us to move that daemon as a receiver to the agent. I'll work on moving that here and linking it directly to the agent.

/cc @greggdonovan

### PR DESCRIPTION
**Pull request by odeke-em**
Brings in the UNIX Domain Socket receiver that allows
OpenCensus-PHP stats to be aggregated by a third party
daemon. This daemon has been living in the OpenCensus-PHP
repository for a couple of months but becomes tricky
for OpenCensus-PHP users so bringing it in also
will allow a less hop.
Design at
https://docs.google.com/document/d/1CRiRq_wpzOuG9VKM_eaImcrS12Iie2V7LePnH9AwclU/

Fixes open-telemetry/opentelemetry-collector#396

### CODE REVIEW

**Comment by odeke-em** [comment]
For clarity, this PR brings in the code from https://github.com/census-instrumentation/opencensus-php/tree/1327147dc2ea99c06df01db4daa8c4ab2656514d/daemon

**Comment by ecourreges-orange** [comment]
If I am seeing this correctly, you have brought in the opencensus-php daemon (standalone) as-is and renamed it udsreceiver, but it doesn't implement the concept of opentelemetry service receiver, so your pull request would probably not be accepted as-is.
Look at how the other receivers have a config and a factory.
Are you currently working on integrating it?  
I am not a go developer (yet) and wanted to focus on implementing the Unix Domain socket exporter for opencensus-cpp.  
I suppose I need to run it as standalone in addition to the opentelemetry-service in the mean time.
Thanks.

**Comment by jrcamp** [comment]
@odeke-em do you plan on working on this PR any more? I agree with @ecourreges-orange that this would need to be modified to work as a standard receiver.

**Comment by pjanotti** [comment]
Hi @odeke-em - I'm closing the PR since it is stale for a long time. If you want to proceed with some form of it please open an issue to add the desired capability and address the comments above.

**Pull request closed without merging**
