### PR TITLE
[exporter/tanzuobservabilityexporter] Use 0.10.4 of wavefront-sdk-go

### PR DESCRIPTION
**Pull request by keep94**
**Description:** <Describe what has changed.>
Use 0.10.4 of wavefront-sdk-go

**Link to tracking Issue:** #13417

### CODE REVIEW

**Review by oppegard — APPROVED** [review]
lgtm

**Comment by keep94** [comment]
hello @Aneurysm9. My tech lead has approved this PR. Will you please have a look at it?  I noticed in my diffs that the collector already depends on v0.10.3 of the wavefront-sdk-go library.  I can delete the bump to v0.10.4 if you'd rather pick that up in the normal release process.

**Comment by keep94** [comment]
Hi @Aneurysm9. Do you have some time to review this PR?  If not, is there someone else who can have a look at this PR?

**Comment by oppegard** [comment]
Hi @Aneurysm9, this looks good to me. When you have a moment, can you merge?

**Review by codeboten — APPROVED** [review]

**Pull request merged**
