### PR TITLE
[prometheus] Recommend copying resource attrs. into metric labels

### PR DESCRIPTION
**Pull request by gouthamve**
https://docs.google.com/document/d/1gG-eTQ4SxmfbGwkrblnUk97fWQA93umvXHEzQn2Nv7E/edit?disco=AAAAzwSMgJ8

It was recommended to convert this recommendation into a blog-post, but I think making it part of the documentation might be better.

### CODE REVIEW

**Review by kovrus — COMMENTED** [review]
lgtm

Not sure whether the example with grouping is necessary, mentioning joins when selecting by resource attributes gives a good picture already.

**Review by dashpole — APPROVED** [review]
Thanks!

**Comment by gouthamve** [comment]
> Not sure whether the example with grouping is necessary, mentioning joins when selecting by resource attributes gives a good picture already.

I think it is important because selecting and grouping are both common operations but require subtly different queries. (group_left empty or with labels).

**Comment by gouthamve** [comment]
@dashpole @kovrus Could you restart the failed tests?

**Comment by gouthamve** [comment]
@dashpole Can we merge this?

**Pull request merged**
