### PR TITLE
exporter/azureblobexporter First PR

### LINKED ISSUE #8823: New component: Azure Blob Exporter
## The purpose and use-cases of the new component

This exporter saves logs and traces to [Azure Blob Storage](https://azure.microsoft.com/services/storage/blobs/).

## Example configuration for the component
The following settings are required:

- `connection_string` (no default): Azure Blob Storage connection key, which can be found in the Azure Blob Storage resource on the Azure Portal.

The following settings can be optionally configured:

- `logs_container_name` (default = "logs"): Name of the container where the exporter saves blobs with logs.
- `traces_container_name` (default = "traces"): Name of the container where the exporter saves blobs with traces.

Example:

```yaml
exporters:
  azureblob:
    connection_string: DefaultEndpointsProtocol=https;AccountName=accountName;AccountKey=+idLkHYcL0MUWIKYHm2j4Q==;EndpointSuffix=core.windows.net
```

## Telemetry data types supported
Logs, Traces

### PR DESCRIPTION
**Pull request by eedorenko**
Description:
azureblobexporter exports logs and traces to Azure Blob Storage

Fixes #8823 

Documentation:
Readme describing exporter functionality and configuration.

### CODE REVIEW

**Comment by jpkrohling** [comment]
Please, follow the process described here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

This PR will *not* get reviewed before a sponsor is found.

**Comment by eedorenko** [comment]
I _did_ follow the process described here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components
The issue #8823 is open. Waiting for a sponsor to be assigned (in a round-robin fashion as far as I understand).

**Comment by jpkrohling** [comment]
Sorry, I was just concerned that you might have invested time in coding a component without having a sponsor first. If you can't find a volunteer first, we'll assign one. Have you tried finding a sponsor yet?

**Comment by eedorenko** [comment]
No, I haven't. The component has been developed because it was needed for the customer's implementation. So the investment in development would have happened anyway.

**Comment by eedorenko** [comment]
The PR is waiting for a sponsor of #8823

**Pull request closed without merging**
