### PR TITLE
[chore] Fix TestPerfCounter_Reset test

### PR DESCRIPTION
**Pull request by pjanotti**
#### Description

Fix the TestPerfCounter_Reset that is failing consistently. 

```terminal
=== FAIL: . TestPerfCounter_Reset (0.00s)
    watcher_test.go:131: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/winperfcounters/watcher_test.go:131
        	Error:      	Both arguments must be pointers
        	Test:       	TestPerfCounter_Reset
```

Root case: after upgrading `testify` circa of 2 weeks ago, since it included:

> NotSame should fail if args are not pointers https://github.com/stretchr/testify/issues/1661 by @sikehish in https://github.com/stretchr/testify/pull/1664

See https://github.com/stretchr/testify/releases

#### Testing

Local test run

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
Ugh :( this one again... i had to fix a bunch of these because of the change in testify

**Comment by pjanotti** [comment]
@codeboten I would love to have `Run Windows` on (or always running Windows without the label) to avoid such "Windows" cases - tracked via #34385

**Review by atoulme — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Comment by pjanotti** [comment]
# CI failures: 

Windows failures are #36481 

OPAMP failure: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12242789600/job/34151180181?pr=36726#step:8:823

` githubgen` on `check-codeowners`: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12242789468/job/34150903475?pr=36726#step:4:25

**Comment by dmitryax** [comment]
Thanks @pjanotti!

**Pull request merged**
