### PR TITLE
Add k8s makefile targets

### PR DESCRIPTION
**Pull request by ChrsMark**
**Description:** <Describe what has changed.>

First attempt for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32348.

**Link to tracking Issue:** <Issue number if applicable> https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32348

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by andrzej-stencel** [comment]
I agree it's useful, but perhaps worth adding a little documentation, perhaps in the examples/kubernetes/README.md file, an example on how to use these kind make targets?

**Comment by ChrsMark** [comment]
Good idea @andrzej-stencel! I wonder though if this place is the best to host such a developer docs files 🤔 If that's our best option here, I can add new md file in this directory called `dev-docs.md` cause I think the `README.md` one seems to be related to the logs specific example?

**Comment by andrzej-stencel** [comment]
> Good idea @andrzej-stencel! I wonder though if this place is the best to host such a developer docs files 🤔 If that's our best option here, I can add new md file in this directory called `dev-docs.md` cause I think the `README.md` one seems to be related to the logs specific example?

Sure, let's add the docs whenever you see fit, the important thing is to get it in. We can move it around later if we want. It doesn't need to be well cooked either, I think "quick & dirty" is good for starters too. It's not like it's a product we have to maintain afterwards. :slightly_smiling_face:

**Comment by ChrsMark** [comment]
@andrzej-stencel, thank's for the feedback here. I have added the respective docs. Let me know what you think.

note: if we land this for now I'm planing on adding additional targets (in follow-up PRs) for the `deployment` mode as well.

**Review by andrzej-stencel — APPROVED** [review]

**Pull request merged**
