### PR TITLE
[connector/exceptions] Always add span name as a dimension in the output metrics and log records

### PR DESCRIPTION
**Pull request by niftyhoot**
**Description:**
This change adds span.name as one of the default fields attached to the output logs and metrics.
This can help isolate the root cause of problems to specific endpoints within a service.

**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32162

**Testing:** 

Unit Test Updated and Passed.
Verified by label by sending the metrics to the prometheus exporter.
Verified that logs output has span.name by sending the output to Splunk HEC exporter

**Documentation:**
Updated README.md and Changelog file

### CODE REVIEW

**Comment by marctc** [comment]
Overall looks good, thanks!! I have a question before approving: is it any case that span names are dynamically generated? I'm concern if that happens in sort of scenarios in can led to cardinality explosion.

**Comment by niftyhoot** [comment]
> Overall looks good, thanks!! I have a question before approving: is it any case that span names are dynamically generated? I'm concern if that happens in sort of scenarios in can led to cardinality explosion.

Very good question. It is quite possible and I was planning to propose the exclude dimension option soon after this PR.
Current default dimensions of exception.message is actually a far greater risk than span.name
Very common to see volatile details and multi-line contents in exception.message label and systems like Prometheus dont like labels with long string values.

However, a mechanism wherein dimensions for Logs and dimensions for Metrics outputs are independently listed and the ability to ignore (on a per services basis) where one or more such dimension can result in cardinality explosions is certainly needed. Ideally, it should be a mix of dynamic (subject to some sort of total cardinality limit and based on past heuristics) and static wherein a rogue service is explicitly listed to be use a non-default dimension set. Happy to create a GH issue and publish a PR if you'd be okay with that.

**Review by marctc — APPROVED** [review]

**Comment by niftyhoot** [comment]
@marctc @jpkrohling @bogdandrutu - using the new-comer card and thus taking the liberty to ask a dumb question - what should be the next step here? would someone from code-owners group run any additional tests and merge this automatically ?

**Review by jpkrohling — APPROVED** [review]

**Comment by niftyhoot** [comment]
@marctc @jpkrohling @bogdandrutu - can one you please help with merging of this PR ?

**Pull request merged**
