### PR TITLE
[receiver/vcenter] Metric attributes for host and vm performance metrics

### PR DESCRIPTION
**Pull request by schmikei**
**Description:** Making this in order to better communicate a potential solution after digging deeper into @BominRahmani's PR

So I did some pretty intense digging into this  PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23669 Bomin was initially trying to solve. And felt like i should share my findings as some things were confusing.

1. The comment I made [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23669#discussion_r1283268584) appears to be the Graph component in the UI doing the aggregation as the Performance manager API does not report these values. It’s frustrating when you cannot trust the UI’s display of this information vs the API. I validated this by running the receiver against another environment since I didn’t really want to trust recordings for this particular change in case it was environment specific. 
2. I think the solution with Resource Attributes may be the best way forward, I spiked out a `object` PR which i think is a good enough solution for this case. 
3. @djaglowski  I’d like your expertise and knowledge on the naming of this metric attribute, since it can contain a variety of things port numbers, network interface names, Hard Drive names etc. Still debating whether we want to be more specific for maybe like `vcenter.disk.name` RA but currently was just following the pattern for vCenter's reporting structure. 

**Link to tracking Issue:** <Issue number if applicable>

Close #23669

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by schmikei** [comment]
@djaglowski @BominRahmani can you guys take a look at this and let me know if you feel the solution is sufficient?

**Review by BominRahmani — APPROVED** [review]

**Comment by BominRahmani** [comment]
LGTM!

**Comment by djaglowski** [comment]
> it can contain a variety of things port numbers, network interface names, Hard Drive names etc. Still debating whether we want to be more specific for maybe like vcenter.disk.name

Do we have a way to know the difference? I don't see much value in modeling multiple types of resources using the same attribute, if we can't tell them apart.

**Comment by schmikei** [comment]
> > it can contain a variety of things port numbers, network interface names, Hard Drive names etc. Still debating whether we want to be more specific for maybe like vcenter.disk.name
> 
> Do we have a way to know the difference? 

I think we have two bits of info we can gleam from.

1. The vCenter metric name the sample is coming from
2. If something is numeric in nature i.e. differentiating a port number from a nic, etc.

Its hard to generalize for every environment as well since the API is not restrictive on what exactly comes back in the Instance identifier per metric. Still feeling flexible about what the right approach here is but still want to provide value. So that may mean scoping to the metric in this case might make sense, however these are literal resources we are identifying the datapoint with.

**Comment by schmikei** [comment]
Discussed a tad bit further and I think we have a consensus that these belong as metric attributes. I've added a featuregate for this breaking change even though its in alpha. Might have to adjust per the upcoming release.

**Review by djaglowski — APPROVED** [review]
Thanks for iterating on this @schmikei

**Pull request merged**
