### PR TITLE
[chore] Add observIQ distribution to component READMEs

### PR DESCRIPTION
**Pull request by djaglowski**

### CODE REVIEW

**Comment by atoulme** [comment]
LGTM, feel free to use alphabetical order for the distros? Or don't worry about it, and mdatagen down the road can sort alphabetically.

**Comment by atoulme** [comment]
I see it now - aws was not in alphabetical order. OK, we can figure this out separately from this PR.

**Comment by djaglowski** [comment]
Yeah, I considered alphabetical, but thought `core` and `contrib` should appear first and second respectively. Maybe those are hardcoded and then alphabetize the rest? As you said, we can decide in mdatagen.

**Review by songy23 — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
> Yeah, I considered alphabetical, but thought core and contrib should appear first and second respectively. Maybe those are hardcoded and then alphabetize the rest? As you said, we can decide in mdatagen.

core+contrib and rest in alphabetic order is what we aggreed on in thttps://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21383

**Comment by atoulme** [comment]
We will make mdatagen output distro links in the right order. I have opened https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22051 to follow up.

**Pull request merged**
