### PR TITLE
Add metrics translations in Signalfx exporter

### PR DESCRIPTION
**Pull request by dmitryax**
Introduce optional metric translation in signalfxexporter to produce metrics in a format that is backward-compatible with SignalFx naming conventions

### CODE REVIEW

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
@dmitryax let's please try to split this PR in ~500 maximum lines changes.

**Comment by dmitryax** [comment]
@bogdandrutu I split it with the first batch in 678 lines. Splitting it further would not be that easy. Could you please take a look https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/477 ?

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by dmitryax** [comment]
@bogdandrutu I've submitted another PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/489 instead
Closing this one

**Pull request closed without merging**
