### PR TITLE
RabbitMQ exporter implementation

### PR DESCRIPTION
**Pull request by swar8080**
**Description:** 
This is the completed implementation of the rabbitmq exporter. 

**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28891

**Testing:**
- Unit tests
- Happy path with rabbitmq running locally and in the cloud, testing different configuration options
- Error cases
  - Fail to connect during start-up
  - Invalid credentials
  - Connection lost midway through publishing to the queue. The component attempts reconnecting on the next publish attempt
- Concurrent publishing, both with and without connection issues

**Documentation:** 
Updated README with more configuration options

### CODE REVIEW

**Comment by swar8080** [comment]
FYI @atoulme this is ready for review (since you're the component sponsor)

**Review by atoulme — APPROVED** [review]
The code looks good but I didn't test it myself. This can land and we can add a test like this one to make sure no leaks are present in a subsequent PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/zipkinreceiver/package_test.go

**Comment by evan-bradley** [comment]
@swar8080 Could you resolve the conflicts?

**Comment by swar8080** [comment]
@evan-bradley the pipeline passed if you want to merge

**Pull request merged**
