### PR TITLE
[exporters/skywalking] Mark as unmaintained

### PR DESCRIPTION
**Pull request by jpkrohling**
Related to #23796, this marks the SkyWalking exporter as deprecated.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]
Thanks for keeping track of this component and documenting the efforts made along the way.

**Comment by TylerHelmuth** [comment]
I dont remember how we've done it in the past but maybe a changelog entry telling users "this is deprecated" would be a good idea.

**Comment by jpkrohling** [comment]
Yeah, I'm adding it, was just too slow :-)

**Review by crobert-1 — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by jpkrohling** [comment]
Despite this having been reviewed, I'd feel more comfortable if another maintainer would merge this.

**Review by evan-bradley — APPROVED** [review]

**Pull request merged**
