### PR TITLE
[receiver/redis] Seconds as unit for redis.cmd.latency metric.

### PR DESCRIPTION
**Pull request by bjandras**
**Description:** Changed unit for `redis.cmd.latency` metric from microseconds to seconds.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6942

### CODE REVIEW

**Comment by bjandras** [comment]
This is a folow-up to PR #26569, so it can skip the changelog.

**Review by crobert-1 — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Just confirming the latency metrics have not been published in a release yet? Otherwise this would be a breaking change

**Comment by bjandras** [comment]
@codeboten Not to my knowledge. The PR that introduced latency metrics has been merged recently. This PR is a response to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26569#discussion_r1325118897.

**Comment by crobert-1** [comment]
> @codeboten Not to my knowledge. The PR that introduced latency metrics has been merged recently. This PR is a response to [#26569 (comment)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26569#discussion_r1325118897).

I confirmed new metrics were merged yesterday, and have not been released yet.

**Review by codeboten — APPROVED** [review]
Thanks for confirming @bjandras @crobert-1

**Pull request merged**
