### PR TITLE
[chore] Switch back to upload-artifact v3

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
I think v4 is broken (or the way we are using the action is no longer supported in v4).  Switching back to v3 for now to fix our CI.

**Link to tracking Issue:** <Issue number if applicable>

I think https://github.com/actions/upload-artifact/issues/471

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@TylerHelmuth can you clarify what breaks? This PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30091 passed all required CI checks.

**Comment by TylerHelmuth** [comment]
@bogdandrutu https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30091/checks didn't run all the checks (I'm not actually sure how you were able to merge).

Renovatebot PRs need closed and reopened to trigger CI once the `go mod tidy` commit comes through.

**Review by songy23 — APPROVED** [review]
@bogdandrutu  I think https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30091 went in effect only after it is merged. Now this step `Run actions/upload-artifact@v4` keeps failing in all workflows https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/build-and-test.yml

**Comment by TylerHelmuth** [comment]
> Renovatebot PRs need closed and reopened to trigger CI once the go mod tidy commit comes through.

NVM this only bumped the actions.

Yes I agree with @songy23

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
