### PR TITLE
Prepare v0.40.0

### LINKED ISSUE #4477: Update contrib to the latest core

### LINKED ISSUE #4480: Prepare contrib release

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes open-telemetry/opentelemetry-collector#4477
Closes open-telemetry/opentelemetry-collector#4480

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Should this PR wait until the 0.40.0 tag is completed in core?

**Comment by jpkrohling** [comment]
> Should this PR wait until the 0.40.0 tag is completed in core?

This is the first step in the release doc, I suppose this is only to make sure the current collector core won't break contrib.

**Review by codeboten — COMMENTED** [review]
🤔 somewhat surprised this broke the correctness tests

**Comment by codeboten** [comment]
> 🤔 somewhat surprised this broke the correctness tests

Ah i see, i missed this change: https://github.com/open-telemetry/opentelemetry-collector/commit/62a65529ef941b064541ff05c4a3e182c58f6150

**Comment by jpkrohling** [comment]
I just added a new commit to this PR, fixing the change from GetStateChannel to GetState.

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
Looks like the prometheus change broke the tests
```
panic: test timed out after 5m0s

goroutine 150178 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.17.3/x64/src/time/sleep.go:180 +0x4a
```

**Comment by jpkrohling** [comment]
True, I just restarted the test thinking it was a flaky test, but I need to look deeper into this.

**Comment by jpkrohling** [comment]
I fixed the Prometheus tests and a couple of missing `go.mod` entries for items in this repo (Memcached, for instance). The other changes are made by the steps listed in the release procedure. Given that I've had approval by @codeboten already, I'm merging this to proceed with the release.

**Review by mx-psi — COMMENTED** [review]
Just saw your message on Slack, wanted to say it looks good even if already merged :)

**Comment by jpkrohling** [comment]
Thanks! I wasn't sure anyone was working today :-)

**Pull request merged**
