### PR TITLE
Add regex processor

### PR DESCRIPTION
**Pull request by atoulme**
**Description:** 
This PR adds a new processor that can manipulate log record bodies according to regular expressions in sed format.

* [ ] Sponsor: TBD
* [x] A complete config.go, which will show how your component will look like to users
* [x] README.md with some basic information about your component. 
* [x] versions.yaml
* [ ] CODEOWNERS with at least the sponsor and the component's author
* [ ] internal/components tests
* [ ] go.mod at the root of the repository and cmd/configschema
* [ ] dependabot
* [x] The skeleton of the component, potentially using the helpers
* [x] Makefile

**Link to tracking Issue:**
#7396

**Testing:**
Just the structure and not wired yet, some unit tests.

**Documentation:**
README.md

### CODE REVIEW

**Comment by jpkrohling** [comment]
@atoulme, could you please make sure this PR is following the guidelines (#6926)?

**Comment by atoulme** [comment]
@jpkrohling added checklist, thank you

**Comment by jpkrohling** [comment]
I'm converting to draft, until at least the sponsor is found.

**Comment by atoulme** [comment]
@anuraaga could I interest you in sponsoring this component? Anyone you'd think would be a good person to sponsor?

**Comment by MovieStoreGuy** [comment]
I think this would be replace by https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor ? 

Or at the very least I can see this functionality existing inside the transform processor.

**Comment by anuraaga** [comment]
Hi @atoulme - yeah this is definitely in scope for a function in the transform processor, it could look something like (assuming making the right hand expression truly sed-specific) `execute_sed(body, "s/foo/bar")` (and the same function could also be e.g. `execute_sed(attributes["author"], "s/anuraaga/atoulme")`. Hoping to get the traces skeleton for transform processor in by next week, and then would need to add metrics and logs support, and add a bunch of functions.  Does this block you too much @atoulme?

**Comment by atoulme** [comment]
I'm not blocked, I just need to make sure we land this properly, and it needs to be accessible to our users. This is a required feature for otel to gain traction with enterprise environments. It might be worth going back to the bug coming with this PR and tie to the transformprocessor to clarify the intent like you just did. Thank you, I'll close this PR.

**Pull request closed without merging**
