### PR TITLE
[exporter/coralogixexporter] Update codeowners

### PR DESCRIPTION
**Pull request by povilasv**
**Description:** <Describe what has changed.>

Changing Coralogixexporter's Codeowners.

I believe I do no need to add changelog for this change.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by matej-g — APPROVED** [review]

**Review by oded-dd — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]
Approving based on existing code owner's review.

**Review by codeboten — CHANGES_REQUESTED** [review]
I don't believe all the owners added meet the requirement of becoming a code owner https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner

Mainly the requirement of being a member of the OpenTelemetry organization

**Comment by TylerHelmuth** [comment]
I know @povilasv is a member of the OpenTelemetry Organization (he's one of our Helm approvers 👋 ), and it looks like @matej-g is as well, but @OrNovo is not.  If the PR is updated to include only @povilasv @matej-g then we're in compliance with our rule.  Once @OrNovo is a community member and meeting our other requirements he could be added in the future.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by evan-bradley** [comment]
My bad, I was under the impression from previous discussions around code ownership that the community member requirement was more of a soft rule when it came to vendors owning vendor-specific components. I'm good with stricter enforcement of that rule.

**Review by atoulme — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Thanks @povilasv!

**Pull request merged**
