### PR TITLE
Upgrade otel collector core, fix changes after no nil Status

### PR DESCRIPTION
**Pull request by bogdandrutu**
Important changes only in Honeycomb exporter, will wait for their review.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
/cc @paulosman @lizthegrey @MikeGoldsmith the previous status logic was not confirming with specs and [proto](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/trace/v1/trace.proto#L230).

Please check the change, if this is not good and a quick fix is possible I will do it.

**Review by jpkrohling — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Ping @paulosman @lizthegrey @MikeGoldsmith

**Comment by bogdandrutu** [comment]
Last ping @paulosman @lizthegrey @MikeGoldsmith

**Comment by paulosman** [comment]
Looks fine to me. :+1:

**Review by paulosman — APPROVED** [review]

**Pull request merged**
