### PR TITLE
[exporter/loki] Remove deprecated configuration parameters

### PR DESCRIPTION
**Pull request by kovrus**
**Description:** <Describe what has changed.>

Remove deprecated configuration parameters. The support of labels.{attributes/resource}, labels.record, tenant, and format configuration parameters are dropped in favor of attribute hints for configuring the exporter.

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15653

### CODE REVIEW

**Comment by kovrus** [comment]
cc: @gouthamve @mar4uk

**Review by mar4uk — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Needs some rebase

**Review by codeboten — COMMENTED** [review]
Please rebase if this PR is still useful.

**Comment by kovrus** [comment]
Closing this PR. It is out of sync and the decision on how to proceed with this issue is not yet made.

**Pull request closed without merging**
