### PR TITLE
k8seventsreceiver & k8sobjectsreceiver: migrate to latest semconv version

### PR DESCRIPTION
**Pull request by narcis96**
Description: The version of semconv is upgraded from to v1.6.1 and v1.9.0 to v1.27.0

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095

Testing: Tests passed

### CODE REVIEW

**Review by TylerHelmuth — CHANGES_REQUESTED** [review]
Upgrading semconv is risky. Please confirm that no attributes emitted by this component change bc of this upgrade.

**Comment by narcis96** [comment]
> Upgrading semconv is risky. Please confirm that no attributes emitted by this component change bc of this upgrade.

I confirm that risk is 0. The semconv attributes' value have been compared using [go-otel-semconv-comparator](https://github.com/narcis96/go-otel-semconv-comparator) resulting in 0 diffs.

**Comment by narcis96** [comment]
> Upgrading semconv is risky. Please confirm that no attributes emitted by this component change bc of this upgrade.

@TylerHelmuth

I used [go-otel-semconv-comparator](https://github.com/narcis96/go-otel-semconv-comparator) to check that that all constants from the older semconv version have the same value inside the newer semconv version. Thus it is safe to do this upgrade. Check the existing upgrades: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095

**Comment by ChrsMark** [comment]
Checked were conventions are used:

https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector-contrib+path%3Areceiver%2Fk8seventsreceiver+semconv.&type=code&ref=advsearch

https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-collector-contrib+path%3Areceiver%2Fk8sobjectsreceiver+semconv.&type=code&ref=advsearch

It appears it'd be safe to upgrade since `k8s.namespace.name` and `k8s.node.name` haven't changed.

**Review by ChrsMark — APPROVED** [review]

**Comment by narcis96** [comment]
PTAL: @dmitryax @TylerHelmuth @hvaghani221

**Review by TylerHelmuth — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]

**Pull request merged**
