### PR TITLE
Update mezmoexporter codeowners

### PR DESCRIPTION
**Pull request by seeruyy**
Add myself as a code owner.

### CODE REVIEW

**Review by gjanco — APPROVED** [review]

**Review by TylerHelmuth — COMMENTED** [review]
@seeruyy please see the contributing guide's instructions for becoming a code owner: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner.  You need to be a member of the OpenTelemetry org first so that issues and PRs can be assigned to you.

**Comment by gjanco** [comment]
I Support

**Comment by gjanco** [comment]
> @seeruyy please see the contributing guide's instructions for becoming a code owner: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner. You need to be a member of the OpenTelemetry org first so that issues and PRs can be assigned to you.

Not sure if we need to do something else?  Is the slack requirement new?

**Comment by TylerHelmuth** [comment]
@gjanco I don't think the Collector community would hold Slack requirement against you.  The community membership requirement currently exists so that we have the ability to assign issues and PRs to code owners.  

It looks like you aren't a member either.  I assume you've submitted some PRs/worked some issues already.  Can you submit for membership? Following [these steps](https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements) all you need to do is open an issue in the community repo.  I will be a sponsor and I hopefully @codeboten will as well.

@seeruyy, assuming you haven't contributed yet, I suggest submitting a few PRs or working some issues in the contrib repo.  Could be anything, even documentation.  Once you've contributed something we can support you for community membership.

Thanks for working with us here.  These rules help us ensure that our code owners are committed to the role and all our admin CI works properly.

**Pull request closed without merging**
