### PR TITLE
[receiver/k8sobjects] Fix empty `event.name` attribute when using watch mode

### PR DESCRIPTION
**Pull request by hvaghani221**
**Description:** 
event.name attribute is empty when collecting any resource using watch mode. 

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16542

### CODE REVIEW

**Comment by harshit-splunk** [comment]
@dmitryax can you please review it?

**Comment by dmitryax** [comment]
@harshit-splunk If you look at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/semantic_conventions/events.md, I don't think it's semantically correct to populate `event.name` with k8s resource name. I think it should be `pod created`, `pod removed` or something like that. I think we need to use another resource attribute for setting k8s resource name on. The name probablyshould be OTel  `k8s.resource.name`, `k8s.resource.type`. It should be aligned with https://kubernetes.io/docs/reference/using-api/api-concepts/ and OTel conventions

**Comment by harshit-splunk** [comment]
@dmitryax, using `k8s.resource.name`  makes sense.

Creation/deletion of any resource is only detected when watching the event. 

What does `Pull/Watch <resource name> from <coma separated namespaces> namespace` sounds like for `event.name` attribute? I think it fairly identifies the event.
For example
- Pull pods from all namespace
- Watch events from default namespaces

**Comment by harshit-splunk** [comment]
@dmitryax PTAL

**Comment by dmitryax** [comment]
I don't think `Watch <resource name> from <coma separated namespaces> namespace` is a good event. With the watch, we receive k8s event. So we need to use the actual name of the received event instead. k8sevents receiver use [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8seventsreceiver/k8s_event_to_logdata.go#L83). Does that work?

**Review by dmitryax — APPROVED** [review]
LGTM

**Pull request merged**
