### PR TITLE
[receiver/fluentforward] Convert attributes with nil value to AttributeValueTypeEmpty

### PR DESCRIPTION
**Pull request by gregoryfranklin**
msgpack fields with a nil value are currently being converted to the string `"<nil>"` because they are being caught by the default case `fmt.Sprintf("%v", val)`

Using AttributeValueTypeEmpty would seem like a better mapping.

**context**
I have a source that is sending log messages with fields that have a bool or null value.  When it is null, that is currently being converted into a string which means the field becomes bool or string.  Logging backends such as elasticsearch are fine with bool or null but having a field that is bool or string will not work.  Exporters (that support null values) therefore need to know if a value is supposed to be null and the OpenTelemetry type for that is AttributeValueTypeEmpty.

### CODE REVIEW

**Comment by gregoryfranklin** [comment]
Not stale - waiting for review.

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
LGTM, but an approval from the code owner (@dmitryax) would also be good to have.

**Review by dmitryax — COMMENTED** [review]
Looks good to me. Please add the change in CHANGELOG.md

**Comment by jpkrohling** [comment]
@gregoryfranklin, would you please add an entry to the changelog? This is all that is missing to get this PR merged.

**Comment by gregoryfranklin** [comment]
I've added the changelog entry.  The unittest appears to have failed for reasons unrelated to my change and needs to be re-run?

**Comment by jpkrohling** [comment]
It's probably a flaky test. I created an issue to track it and restarted the tests for this PR.

**Review by dmitryax — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
