### PR TITLE
[receiver/fluentforward] Add case to handle uint64 timestamp

### PR DESCRIPTION
**Pull request by bhogayatakb**
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11435

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Lint errors, please fix

**Comment by bhogayatakb** [comment]
@bogdandrutu  Linting applied & Commit Ammended

**Comment by bhogayatakb** [comment]
Let me know if there is anything I could do for the failing checks, @bogdandrutu @dmitryax

**Comment by dmitryax** [comment]
@bhogayatakb can you please add a changelog entry and a test case?

**Comment by bhogayatakb** [comment]
There was a testcase expecting uint to be an invalid type. As we are considering uint as a valid type for timestamp - this testcase should no longer be relevant, right ?

**Comment by bhogayatakb** [comment]
@dmitryax added changelog entry and made changes in test cases, there is a failing check regarding integration test for rabbitmq, should I be making any changes to pass that test ?

**Review by codeboten — COMMENTED** [review]
I've restarted the job 👍🏻

**Comment by bhogayatakb** [comment]
@dmitryax @bogdandrutu checks passed, is it good to go ?

**Pull request merged**
