### PR TITLE
[chore] Pick up new tests generated by mdatagen

### PR DESCRIPTION
**Pull request by dmitryax**
Follow-up to https://github.com/open-telemetry/opentelemetry-collector/pull/9940

### CODE REVIEW

**Comment by crobert-1** [comment]
_Needs `make gotidy`_

**Comment by dmitryax** [comment]
The tests are expected to fail until https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32331 is merged

**Comment by codeboten** [comment]
Sorry @dmitryax, missed this and ended up taking the changes in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32352

**Comment by codeboten** [comment]
No longer needed now that https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32352 is merged

**Pull request closed without merging**
