### PR TITLE
[chore][pkg/stanza]: Move reader's logic to a new tracker 

### PR DESCRIPTION
**Pull request by VihasMakwana**
**Description:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29273#issuecomment-1811199166

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by VihasMakwana** [comment]
@djaglowski ^

**Review by djaglowski — COMMENTED** [review]
Thanks for working on this @VihasMakwana. This is pretty close to what I had in mind [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29273#issuecomment-1811305805), but I think we should break this into incremental changes.

I suggest first we create a separate `internal/fileset` package. Then we can start using it directly in `fileconsumer.go`. Then finally we can pull all the related logic into a new `internal/tracker` package.

**Comment by VihasMakwana** [comment]
@djaglowski up for review. PTAL!
Thanks

**Comment by djaglowski** [comment]
@VihasMakwana, do you mind if we continue with the proposed steps here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30219#pullrequestreview-1811302873

I think we need to make these changes incrementally. If we first integrate the fileset directly in place of the existing mechanisms, this will be a much clearer diff. Then extracting a tracker package will just be a refactoring, rather than a refactoring + functionality change.

**Comment by VihasMakwana** [comment]
@djaglowski Really sorry about the misunderstanding from my end.
Yeah, that makes sense. Let's start with that.
Much Thanks!

**Comment by VihasMakwana** [comment]
Closing. Will raise a new one.

**Pull request closed without merging**
