### PR TITLE
[cmd/mdatagen] has been moved to opentelemetry-collector

### LINKED ISSUE #30497: Delete cmd/mdatagen from contrib
### Component(s)

cmd/mdatagen

### Describe the issue you're reporting

cmd/mdatagen is moving to opentelemetry-collector.

Perform the following actions:
* [x] Deprecate the cmd/mdatagen with a "Deprecated" comment - #30498
* [x] Publish a new version of the package with the deprecation
* [x] Sync up the code changes from contrib to core
* [x] Delete the code

### PR DESCRIPTION
**Pull request by codeboten**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30497

### CODE REVIEW

**Comment by dmitryax** [comment]
@atoulme do we have any contrib's exclusive functionality in mdatagen right now. If so, we need to think of wrapping core's version instead of removing the whole module. I do agree we should not keep a copy of it here

**Comment by dmitryax** [comment]
We can probably keep mdatagen experimental features in contrib for now. But eventually, they should all be moved to core and we need to remove this module

**Comment by atoulme** [comment]
> do we have any contrib's exclusive functionality in mdatagen right now
We do, quite a bit. All the test generation, I take it.

I certainly hope we will follow a mindful deprecation cycle of this code rather than deleting it outright, right?

**Comment by codeboten** [comment]
> I certainly hope we will follow a mindful deprecation cycle of this code rather than deleting it outright, right?

I would expect this code to be moved to the core repo no?

> This deletion here doesn't address the go:generate instructions to generate code in modules, do we mean to add mdatagen through install_tools?

Yes. That's the plan, this is still in draft.

**Comment by atoulme** [comment]
> > I certainly hope we will follow a mindful deprecation cycle of this code rather than deleting it outright, right?
> 
> I would expect this code to be moved to the core repo no?

Yes, of course, since we're moving. But I'm pointing to the fact that per Go guidelines, we should first deprecate the package with https://pkg.go.dev/github.com/AviatrixDev/opentelemetry-collector-contrib/cmd/mdatagen

And given our rate of change with mdatagen, I'd certainly appreciate if we can sync up and make sure we don't miss anything in the move.

> 
> > This deletion here doesn't address the go:generate instructions to generate code in modules, do we mean to add mdatagen through install_tools?
> 
> Yes. That's the plan, this is still in draft.

Nice!

**Comment by codeboten** [comment]
> I'd certainly appreciate if we can sync up and make sure we don't miss anything in the move.

100% i opened this PR mostly not to forget to finish moving mdatagen :)

**Comment by atoulme** [comment]
Filing https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30497 to follow up and keeping track

**Pull request closed without merging**
