### PR TITLE
Add AND and OR to the parser

### LINKED ISSUE #10195: [processor/transform] Add AND and OR capability to WHERE condition
**Is your feature request related to a problem? Please describe.**
The transform processor currently accepts a WHERE clause with a single condition:

`set(name, "test") where name != "test"`

But there are times where multiple conditions are needed in order to filter to the correct data.

**Describe the solution you'd like**
The processor's grammar should be updated to allow ANDing and ORing together any number of conditions.  AND conditions should take precedence.  Conditions should be able to be grouped using `(` `)`

Example:
 `set(name, "test") where (name != "test" and attribute["test"] != "something") or resource.attribute["test"] == "something"`

### PR DESCRIPTION
**Pull request by kentquirk**
Add complex expressions to WHERE clauses in the grammar.

**Description:**
The transform processor currently accepts a WHERE clause with a single condition, but there are times where multiple conditions are needed in order to filter to the correct data.

This (when finished) will update the grammar to allow AND and OR with proper precedence, as well as grouping with parentheses.

**Link to tracking Issue:** <Issue number if applicable>
Fixes #10195. 

**Testing:**

- [x] The lexer builder was extracted to a separate function
- [x] Tests were added for the lexer to ensure that keywords are not confused with other identifiers
- [x] Failing tests were added for the parser with complex conditions
- [x] New types added to the grammar (Expression, etc) to support more elaborate expressions
- [x] Grammar structured to handle precedence correctly
- [x] Expression evaluation will be extracted to a more general structure
- [x] More lexer tests
- [ ] More parser tests to confirm proper operation

**Documentation:** 
- [ ] Grammar extensions documented

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@kentquirk heads up, the TQL was moved to pkg/telemetryquerylanguage/tql. I suspect a majority of your changes will need to be applied there instead of directly in the transform processor. I am currently working on a PR to update the transform processor to use the new package.

**Comment by kentquirk** [comment]
oof. On the one hand, this is the right call. On the other hand, I was planning to submit this today. Sigh. I will open a new PR and close this once that one's ready. Thanks for the heads up.

**Comment by TylerHelmuth** [comment]
The good news is that the new package is the exact code from the processor right now, so a copy and paste should be straightforward.

**Comment by kentquirk** [comment]
Closing this in favor of #12213.

**Pull request closed without merging**
