### PR TITLE
[hostmetrics receiver/filesystem] Track virtual partitions

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** 
This would allow the `filesystem scraper` to capture virtual partition information when enabled.

**Link to tracking Issue:** 
[15680](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15680)

**Testing:**

No additional tests have been added since it keeps the existing behaviour

**Documentation:**

Not sure how best to document this considering the sub scrapers don't expose their config just the auto gen metric configuration.

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
I believe there is a bug in the CI for the changelog, it looks like it is checking a directory that doesn't exist.

**Comment by jamesmoessis** [comment]
I think they moved the changelogs to `.chloggen`. 

I support this addition, since there are use cases for monitoring virtual filesystems like tmpfs. 

Can you add tests to `config_test.go`?

**Comment by MovieStoreGuy** [comment]
> I think they moved the changelogs to .chloggen.

However, the auto generated code published the changelog to `unreleased` as per the contribution guide, hence my confusion.

**Comment by djaglowski** [comment]
@MovieStoreGuy, the contribution guide was updated to refer to `.chloggen` instead of `unreleased`, at the same time as the directory was switched. It's possible your main branch is out of date. Otherwise, we must have missed a reference, but I can't find it.

**Review by evan-bradley — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]
LGTM, but ideally @dmitryax should take a look as code owner.

**Review by dmitryax — APPROVED** [review]
LGTM

**Pull request merged**
