### PR TITLE
[exporter/awss3exporter] Add the ability to assume the role provided by s3uploader.role_arn

### PR DESCRIPTION
**Pull request by thomasbaldwin**
**Description:** <Describe what has changed.>

Adding a feature - This feature allows role assumption for s3 exportation. It is especially useful on Kubernetes clusters that are using [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

**Testing:**

Deployed to a Kubernetes cluster as well as an EC2 instance and verified it would assume the correct role and publish logs to the respective s3 bucket.

**Documentation:**

README updated

### CODE REVIEW

**Review by SkylerRogers — APPROVED** [review]

**Comment by atoulme** [comment]
Thank you for your contribution! Please follow the following instructions:
* From the exporter/awss3 folder, please type `make tidy`
* From the root of the repository, please type `make chlog-new`. Please fill in the changelog with information, including an issue related to the work you are performing. You can use this PR number as issue.

I also expect our CLA check will ask you to accept our contributor license agreement. Please follow prompts.

**Comment by thomasbaldwin** [comment]
> Thank you for your contribution! Please follow the following instructions:
> 
> * [ ]  From the exporter/awss3 folder, please type `make tidy`
> * [ ]  From the root of the repository, please type `make chlog-new`. Please fill in the changelog with information, including an issue related to the work you are performing. You can use this PR number as issue.
> * [x]  I also expect our CLA check will ask you to accept our contributor license agreement. Please follow prompts.

thanks @atoulme! updated as well as added some tests!

**Review by atoulme — APPROVED** [review]

**Comment by thomasbaldwin** [comment]
hey @fatsheep9146! would you like me to keep updating the branch to keep in sync with main for merge, or is that something the reviewer who merges typically will handle?

**Comment by thomasbaldwin** [comment]
hey @songy23, sorry to bother, but any chance you would be able to help me out to get this merged in?

**Review by songy23 — APPROVED** [review]

**Comment by songy23** [comment]
@open-telemetry/collector-contrib-maintainer this should be good to go 🙏

**Pull request merged**
