### PR TITLE
[wip][chore] migrate away from opencensus over to otel

### LINKED ISSUE #33471: Migrate from opencensus library: exporter/splunkhec

### PR DESCRIPTION
**Pull request by codeboten**
This migrates the opencensus metrics to opentelemetry via mdatagen. Note that there is functionality to override the metric names in this exporter that isn't supported out of the box w/ mdatagen. This will be configurable via the configuration of metric views in `service::telemetry::metrics::views` in the future.

One option to get around this in the short term would be to not use mdatagen and just use otel directly.

Closes #33471

Pinging @atoulme as you may have thoughts on how to move this work forward.

### CODE REVIEW

**Comment by atoulme** [comment]
Thanks @codeboten I can try to look at it soon.

**Comment by codeboten** [comment]
Thanks @atoulme, any update on this?

**Comment by crobert-1** [comment]
_FYI, looks like a lot of checks are failing and from what I can tell they're related to this PR. It would be helpful to fix those before reviewing._

**Comment by codeboten** [comment]
@crobert-1 i was leaving this in draft until I know which way I should be addressing the shortcomings of this PR (regarding the configuration for the component that currently allows users to rename their emitted metrics)

**Comment by codeboten** [comment]
As per the comment in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33924#issuecomment-2209883804, going to close this one in favour of #33924

**Pull request closed without merging**
