### PR TITLE
Update New Relic exporter.

### PR DESCRIPTION
**Pull request by a-feld**
**Description:** This updates the New Relic exporter.

Changes include:
* Adds support for Logs
* Updates to the configuration format (see example)
* Removal of common attributes (use opentelemetry collector resource processor to add attributes)
* Performance improvements
* Optimizations to the New Relic payload to reduce payload size
* Metrics generated for monitoring the exporter
* Insert Key vs License keys are auto-detected in some cases
* Collector version information is properly extracted via the application start info parameters

🚨  This PR drops support for cumulative metrics being sent to New Relic via a collector. 🚨 

This is being done for the following reasons:
1. Transforming a cumulative to delta metric is a stateful operation that requires careful routing consideration. Supporting cumulative metrics means that a customer would need to consider their collector deployment routing strategy.
2. With the prior implementation, if data arrives out of order at the collector (which can happen for various reasons), the transform would display data that is potentially inaccurate (interval computation).
3. The state held in the internal transformer was not persistent. It did not survive restarts and would be evicted if data was not observed for a period of 20 minutes. This could lead to missing data points.

We believe that solutions exist today, such as New Relic's [prometheus scraper](https://github.com/newrelic/nri-prometheus) that currently work around these issues and provide a better experience.

**Testing:** Updated unit tests

**Documentation:** Updated readme

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@alanwest @a-feld @jack-berg @nrcventura please review :)

**Comment by a-feld** [comment]
Thanks the team is looking, I think @nrcventura was going to add a bit more code coverage! I'll push this back into draft. Sorry about the premature "ready for review" 😄

**Comment by a-feld** [comment]
We've been discussing this PR at length within the team and we all agree that it's important to document some of the important breaking changes in this PR.

🚨  This PR drops support for cumulative metrics being sent to New Relic via a collector. 🚨 

This is being done for the following reasons:
1. Transforming a cumulative to delta metric is a stateful operation that requires careful routing consideration. Supporting cumulative metrics means that a customer would need to consider their collector deployment routing strategy.
2. With the prior implementation, if data arrives out of order at the collector (which can happen for various reasons), the transform would display data that is potentially inaccurate (interval computation).
3. The state held in the internal transformer was not persistent. It did not survive restarts and would be evicted if data was not observed for a period of 20 minutes. This could lead to missing data points.

We believe that solutions exist today, such as New Relic's [prometheus scraper](https://github.com/newrelic/nri-prometheus) that currently work around these issues and provide a better experience.

**Review by alanwest — APPROVED** [review]

**Comment by alanwest** [comment]
@bogdandrutu This is good to go now.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
