### PR TITLE
[hostmetrics] change cpu.load.average metric units

### PR DESCRIPTION
**Pull request by povilasv**
**Description:** <Describe what has changed.>

The system.cpu.load_average.5m uses 1 as unit, which is reserved for utilization metrics - https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units

CPU Load Average does not track utilization and can go above 

**Link to tracking Issue:** <Issue number if applicable>

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29914

**Testing:** <Describe what testing was performed and which tests were added.>
-

**Documentation:** <Describe the documentation added.>
- generated

### CODE REVIEW

**Comment by dmitryax** [comment]
Given the definition
```
CPU load is the number of processes which are being executed by CPU or waiting to be executed by CPU. So CPU load average is the average number of processes being or waiting executed over past 1, 5 and 15 minutes.
```
Should the unit be `{cpu}`? @braydonk @mx-psi WDYT?

**Comment by bogdandrutu** [comment]
"default unit 1" it is default for all the metrics not only for utilization. See https://github.com/open-telemetry/semantic-conventions/blob/b2e2c64b3f16b3d70b867cbaefc01936f23c1f4c/docs/general/metrics.md?plain=1#L195 and can read also https://unitsofmeasure.org/ucum.

**Comment by bogdandrutu** [comment]
@dmitryax we can have it as `"{cpu}"` but we should not have as empty string.

**Comment by braydonk** [comment]
> Should the unit be `{cpu}`?

My instinct is probably not? `{cpu}` is used elsewhere to represent a number of CPUs, which doesn't feel appropriate for load average.

`1` actually would make sense as a unit in a system with a single CPU with a single core (a good explanation is in the [uptime manpage](https://man7.org/linux/man-pages/man1/uptime.1.html)). The reason this can exceed `1` is because it can go up to 1 for every core on the system.

I am not sure how to handle this scenario as this is a strange metric. If I were to suggest something now, I would say it should be its own unit `{load_avg}`. I'm curious to hear other suggestions on this.

**Comment by mx-psi** [comment]
+1 to doing `{thread}` after reading @povilasv's links

**Comment by braydonk** [comment]
Thanks for the additional documentation, it seems I misunderstood what the load average really meant.

`{thread}` is [already a unit](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/metadata.yaml#L154) in process metrics for the `process.threads` metric.* In that metric, the unit refers to an actual tangible number of threads, whereas this metric refers to an average. So similarly to `{cpu}` as a unit, using `{thread}` here would be a clash with the other usage of that as a unit.

* The unit there is `{threads}` plural, which I'm pretty sure it's not supposed to be. That will probably be changed in semantic conventions updates along with the name of the metric to `process.thread.count`.

**Comment by braydonk** [comment]
Maybe it's fine then. I can't see any other example in semantic conventions of this case ever occurring (using the same unit for a specific number or average) but if that's not against the rules then `{thread}` is fine as a unit.

**Review by dmitryax — APPROVED** [review]
`{thread}` sounds good to me

**Pull request merged**
