### PR TITLE
[chore] fix distribution test ; ensure namedpipereceiver is in the distribution

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Fix the distribution test that checks that components of stability alpha or above are in otelcontribcol.
Add the namedpipereceiver component to otelcontribcol as part of this fix.

### CODE REVIEW

**Review by andrzej-stencel — APPROVED** [review]
This fixes the test incorrectly reporting components as deprecated even though they're not. 

There's still one issue with this test in that it reports components as in development even if only some of the signals are in development while other signals are in other status (examples: [Load Balancing exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.92.0/exporter/loadbalancingexporter/metadata.yaml#L6-L7), [SQL Query receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.92.0/receiver/sqlqueryreceiver/metadata.yaml#L6-L7)). I believe this is a logic error in this test; instead of checking for existence of a development stability, it should check for existence of an alpha or higher stability. This is however an issue that is not introduced in this PR but existed before as well.

**Comment by atoulme** [comment]
@astencel-sumo thanks for the review, I have done another pass to catch components partly in development.

**Review by dmitryax — APPROVED** [review]
LGTM. This logic will be moved to mdatagen to determine whether tests need to be rendered, right?

**Comment by atoulme** [comment]
Yes, though those tests check the presence of the component in cmd/otelcontribcol, we might need a lib to read ocb manifests so we can make assertions against them.

**Pull request merged**
