### PR TITLE
[splunkhecexporter]Add metric_type as key which maps to the type of the metric

### PR DESCRIPTION
**Pull request by Saber-W**
**Description:**
Currently, some metadata isn't stored into Splunk HEC when converting. This PR adds `metric_type` to the fields of Splunk event to transfer this info. The type of metric could be one of: gauge, sum, histogram or summary.

**Link to tracking Issue:**
#3289 

**Testing:**
Update related unit testing `Test_metricDataToSplunk`.

### CODE REVIEW

**Comment by Saber-W** [comment]
cc @bogdandrutu @tigrannajaryan @Aneurysm9 @anuraaga @djaglowski @dmitryax @owais

**Comment by tigrannajaryan** [comment]
@Saber-W lint job failed. Please make sure the build passes.
```
make[1]: Leaving directory '/home/circleci/project/exporter/sentryexporter'
make -C ./exporter/splunkhecexporter lint
make[1]: Entering directory '/home/circleci/project/exporter/splunkhecexporter'
golangci-lint run --allow-parallel-runners
metricdata_to_splunk_test.go:510: File is not `gofmt`-ed with `-s` (gofmt)
						"metric_type": "IntSum",
make[1]: *** [../../Makefile.Common:93: lint] Error 1
make[1]: Leaving directory '/home/circleci/project/exporter/splunkhecexporter'
make: *** [Makefile:149: for-all-target-./exporter/splunkhecexporter] Error 2
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/circleci/project/exporter/signalfxexporter'

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by Saber-W** [comment]
Hi @tigrannajaryan, sure. It's the gofmt issue, which should be fixed now.

**Comment by atoulme** [comment]
LGTM thanks for the contrib!

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Thank you @Saber-W

**Comment by Saber-W** [comment]
Thanks!

**Pull request merged**
