### PR TITLE
stanza receivers - support offset file

### PR DESCRIPTION
**Pull request by djaglowski**
This is a possible implementation for #2287. Several design decisions are not fully aligned with the discussion in that thread. My primary goal is to provide what I think is the simplest & least fragile implementation first, and from there to highlight alternate options and what drawbacks they may introduce. 

Without attempting to rationalize the design choices yet, here is how this implementation works:

Each logs receiver includes a new config section, shown here with default values:

```
filelog/example:
  include: [ ... ]
  operators: [ ... ]
  offsets_file:
    enabled: false
    path: ""
```

There are three configuration states supported:
1. disabled (path is ignored)
2. enabled with the default path
3. enabled with a custom path

The default path consists of an OS-dependent directory (`%ProgramData%/otelcol` for windows, `/val/lib/otelcol` otherwise), and a filename that corresponds to the component `name`.

If a custom path is specified, the directory must exist and the collector must have sufficient permissions to create the offsets file in that directory. Otherwise, receiver creation will fail.

If the default directory is to be used, and it does not exist, then the component attempts to recursively create the directory. If this fails, so does receiver creation.

Each instance of a stanza-based receiver _must_ use an independent offsets file. This can only become a problem with custom settings.

### `offsets_file` as a struct vs single field

_Note: Whether or not this functionality should be enabled or disabled by default is covered in the next section._

To support the three configuration states, I considered using a single field with the following rules:
1. No value, or empty string implies fully default behavior (`offsets_file: ""`)
2. A special value enables the default file (`offsets_file: "enabled"` or `offsets_file: true`)
3.  A path enables a custom file (`offsets_file: /my/offsets_file.db`)

Although this is simple enough, I dislike the approach because:
1. The magic value is unintuitive
2. The pattern does not extend well if we need to add related configuration options later

I suspect this is not a controversial structure, but I wanted to note the alternative because this may appear a little verbose. 

### Default Configuration

As far as I can tell, this is the first component that attempts to establish any concept of an `otelcol` directory. In the longer term, I suspect the responsibility for creating and organizing this directory should be handled by the collector itself. This implementation ignores this consideration, but I'm calling it out in case anyone thinks we should plan for it.

In any case, there are several ways in which the default directory may not be available to the receiver. It may not exist or the collector may not have sufficient permissions to access it. This implementation tries to create the directory if necessary, but it can fail. 

Should we assume that the directory exists and is accessible, and fail otherwise? I did not want to make this assumption yet, so I chose to disable the functionality by default. This should be inverted if we are comfortable with the assumptions.

### Shared vs Independent Offset Files

The decision to use independent offset files was mostly driven by simplicity of implementation, and by some concerns I have about whether `bbolt` can be efficiently and safely synchronized. The documentation lists quite a number of [caveats](https://github.com/etcd-io/bbolt#caveats--limitations) which I do not yet fully understand. 

I believe it may be possible to synchronize a single `bbolt` database, but it appears to require that all receivers must ultimately operate on a single file descriptor, and possibly that `bbolt` transactions must be used.

In any case, I avoided the complexity for now because I don't see a major downside to using independent files. This is not aligned with the discussion in #2287, but I'd like to suggest that it might be a reasonable approach. Certainly this design choice should be considered carefully though.

### CODE REVIEW

**Comment by djaglowski** [comment]
@tigrannajaryan This PR is not quite "ready for review", but would you mind reviewing the design when you have a chance.

**Comment by tigrannajaryan** [comment]
@djaglowski here is an alternate approach I was thinking about: what if Collector core provided a Key-value store as a service to all components?

Some benefits:
- This would allow all Collector data to be stored in a single file. I think each component writing its own file and makes their own decision about where to place it by default can end up with components writing files here and there in uncontrollable way which makes managing/administration of the Collector much more complicated.
- The centralized service will also handle synchronization issues.
- When Collector configuration is changed and some component is removed from the config the centralized solution can detect this after the Collector restart and remove that component's data (which is now garbage). With file-per-component approach we will leave the garbage on file system, there is no one to delete it.

The obvious downside is that we will have to come up with some reasonable generic Key-value service in the core and expose it in the Component interface and that is more complicated and requires more stakeholders to agree.

Can you clarify which operations we need from the storage? Is it set(key,value), get(key) and delete(key) or there is more? Do we need iteration? Any sort of transaction support (to set multiple key-values atomically)?

I can't think of a reason why we would want each receiver to store offsets in a separate file? Are there such reasons? If not then I would prefer to merely have an option to disable offset storage and just enable it by default. This way there is nothing to configure in the most typical cases (assuming centralize KV store, which defines the location).

We will need to decide how we configure the location of the central KV store. It can be either via an extension or even perhaps a top-level setting if we consider it to be a fundamental part of Collector core.

One other use that we have for a central KV store: persistent queues/buffers for pipelines (can be part of queued_retry).

**Comment by djaglowski** [comment]
@tigrannajaryan I really like your idea. This would be a much cleaner approach overall, and it will simplify component implementation in many cases.

> Can you clarify which operations we need from the storage? Is it set(key,value), get(key) and delete(key) or there is more? Do we need iteration? Any sort of transaction support (to set multiple key-values atomically)?

`set(key, value)`, `get(key)`, and `delete(key)` would be minimally sufficient for offset tracking. However, batched versions would be used if they are available. To my knowledge, atomic transactions are not needed in this particular use case. (I suspect they would be helpful in others though.

Log receivers currently use `string` keys, and `[]byte` values. I'm sure a case can be made for other key/value types, but an interface that would work well for offset tracking might be roughly:
```
Get(string) []byte
Set(string, []byte)
Delete(string) // []byte?

// Using map to force uniqueness of keys
GetAll(map[string]bool) // set of strings - bool not meant to be meaningful
SetAll(map[string][]byte)
```
The bulk operations could be enhanced further to optionally support atomic transactions.

> I can't think of a reason why we would want each receiver to store offsets in a separate file? Are there such reasons?

I can think of some possible benefits but I don't think these make a strong case for multiple files:
1. It might be beneficial to isolate load per component. If one component is extremely read/write intensive, it may affect performance of other components. The degree to which this is a concern probably depends on the KV store implementation.
2. In a debugging/troubleshooting scenario, one might wish to clear all state for one particular component. Separate files makes this easy. There are other ways to accomplish this though, such as a CLI on the collector binary, or perhaps allowing direct access to the KV store via another tool.


> If not then I would prefer to merely have an option to disable offset storage and just enable it by default. This way there is nothing to configure in the most typical cases (assuming centralize KV store, which defines the location).

I agree with this, but we should make sure we are clear and confident about whether the default settings are actually expected to work in the vast majority of cases. Is it a reasonable assumption that the collector has read/write access to `/lib/var/otelcol` (or whatever other default directory we choose)? Can/should it create the default directory if it does not already exists? If there is a lack of permissions, should it fail to run, or run without the KV store?

I think we can enable by default if we understand the expected rate of failure and are comfortable with it. I don't have a good sense of what the expectations are here, but I can imagine this being a frustration for users in at least some cases.

**Comment by tigrannajaryan** [comment]
@djaglowski if you plan to work on this then I think the next step is to come up with a design for the centralized KV-store, particularly what it looks like in the core, how it is configured (e.g. file location), how it is exposed as a service to components. It may be worth creating a Google doc for the design to allow easier commenting and the doc link from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2287

**Comment by djaglowski** [comment]
@tigrannajaryan I'll plan on driving this forward.

Closing this PR and will pick up the conversation on #2287 as suggested.

**Pull request closed without merging**
