### PR TITLE
[processor/deltatocumulative] Adjust Config struct and MaxStreams validates

### PR DESCRIPTION
**Pull request by rodrigomageste**
**Description:** The Config struct was changed from JSON to mapstructure to parse the configuration correctly. Additionally, the validation of MaxStreams was adjusted to consider values of 0.

**Testing:** Unit tests were added for the config.go file.

### CODE REVIEW

**Review by RichieSams — APPROVED** [review]
Needs a signed CLA. But code looks good to me

**Review by tombrk — APPROVED** [review]

**Review by nicacioliveira — APPROVED** [review]
🚀 thank you, Mageste 🙏🏼

**Comment by sh0rez** [comment]
@rodrigomageste contributing is the perfect way to get started! nice to have you here :)

**Review by djaglowski — APPROVED** [review]

**Review by crobert-1 — COMMENTED** [review]
Could you also add goleak tests to this component? I realize it's not relevant to this change in particular, but we're trying to include it for every new component. It should be a pretty simple addition, [explained here in docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components).

**Pull request merged**
