### PR TITLE
Adding all components for testbed

### LINKED ISSUE #33193: testbed not working with transform processor in config
### Component(s)

testbed

## Description
When we use a test configuration with transform processor, the test case is failing.
## Steps to Reproduce
Create a test with transform processor.
Say, in [tests/resource_processor_test.go/TestMetricResourceProcessor(...)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e85e670ca2e564e871ae5f4987c85d3d531d4684/testbed/tests/resource_processor_test.go#L113) we add a new transform processor.
Now it looks like this
```
processors := map[string]string{
				"resource":  test.resourceProcessorConfig,
				"transform": "\n  transform:\n",
			}
```
Run the test

## Expected Result
Test should pass.
Because, the transform processor doesn't do anything (it's empty).
## Actual Result
Test case failing with the following error 
```
2024/05/22 23:48:51 Time out waiting for LoadGenerator isn't ready
    test_case.go:289: Time out waiting for LoadGenerator isn't ready
    resource_processor_test.go:153: 
                Error Trace:    /Users/<username>/Downloads/otelcol_test_temp/opentelemetry-collector-contrib/testbed/tests/resource_processor_test.go:153
                Error:          Received unexpected error:
                                rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:60360: connect: connection refused"
                Test:           TestMetricResourceProcessor/set_attribute_on_empty_resource
2024/05/22 23:48:51 Gracefully terminating Agent pid=4557, sending SIGTEM...

```

### Collector version

v0.100.0

## Environment
OS: Mac OS Sonoma Version 14.5 (23F79)
Compiler(if manually compiled): go version go1.22.3 darwin/arm64

PS: I'm not sure what `if manually compiled` means.
I ran the test with the command `TESTS_DIR=tests make e2e-test`

### OpenTelemetry Collector configuration
(taken from `configStr` [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e85e670ca2e564e871ae5f4987c85d3d531d4684/testbed/tests/resource_processor_test.go#L115))

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "127.0.0.1:60989"
exporters:
  otlp:
    endpoint: "127.0.0.1:60990"
    
    
    tls:
      insecure: true
    compression: "none"
processors:
  
  transform:


  resource:
    attributes:
    - key: label-key
      value: new-label-value
      action: update
    - key: resource-type
      from_attribute: opencensus.resourcetype
      action: upsert
    - key: opencensus.resourcetype
      action: delete



extensions:
  pprof:
    save_to_file: /Users/<username>/Downloads/otelcol_test_temp/opentelemetry-collector-contrib/testbed/tests/results/TestMetricResourceProcessor/update_and_rename_existing_attributes/cpu.prof
  

service:
  extensions: [pprof, ]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform,resource]
      exporters: [otlp]
```

### Log output
(testbed/tests/results/TestMetricResourceProcessor/set_attribute_on_empty_resource/agent.log)

```shell
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'processors': unknown type: "transform" for id: "transform" (valid values: [attributes resource batch memory_limiter])
2024/05/23 20:40:13 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'processors': unknown type: "transform" for id: "transform" (valid values: [attributes resource batch memory_limiter])
```

### Additional context

We use a collector config with a series of different processors that do different operations on incoming data.
I am trying to have inputs and expected outputs and test the config if it's doing what is expected.

Can the testbed be used to test the configs with only these processors [attributes resource batch memory_limiter]?
Can't we test other processors?
If not, what is the recommended way to test a pipeline with a series of processors?

### PR DESCRIPTION
**Pull request by swamisriman**
**Description:** <Describe what has changed.>
Adding all components from otelcontribcol to oteltestbedcol.

**Link to tracking Issue:**
Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33193

**Testing:**
When using the following processors in [tests/resource_processor_test.go/TestMetricResourceProcessor(...)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e85e670ca2e564e871ae5f4987c85d3d531d4684/testbed/tests/resource_processor_test.go#L113), the test passes.
See the linked issue for context.
```go
processors := map[string]string{
				"resource":  test.resourceProcessorConfig,
				"transform": "\n  transform:\n",
			}
```

### CODE REVIEW

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by rogercoll** [comment]
Do we want to add all the components to the binary even if they are not used in the `tests/testbed` package? What would be the benefit?

**Comment by rogercoll** [comment]
Should we update the contributing guides accordingly? New components should be added to the binary too: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

**Comment by swamisriman** [comment]
> What would be the benefit?

@rogercoll 
I feel that it would keep the experience consistent across `otelcontribcol` and `oteltestbedcol`.

>Users of the OpenTelemetry Collector are also encouraged to build their own custom distributions with the OpenTelemetry Collector Builder, using the components they need from the core repository, the contrib repository, and possibly third-party or internal repositories.

Taken from [repo README](https://github.com/open-telemetry/opentelemetry-collector-contrib?tab=readme-ov-file#opentelemetry-collector-contrib).
I think the same principle applies here.

Also, I don't think we are publishing any pre-built testbed binaries (are we??)

**Comment by rogercoll** [comment]
Another approach would be to remove the testbed binary in favor of the otelcolcontrib one, related PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34849

**Comment by swamisriman** [comment]
oh...yeah
that would be even neater - to use the same contrib binary for tests too.

**Comment by swamisriman** [comment]
So, what do you say guys?
Shall we skip this in favour of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34849 ?

**Pull request closed without merging**
