### PR TITLE
[receiver/journald]: add support for `all` configuration

### PR DESCRIPTION
**Pull request by meridional**
**Description:** 
This commit adds support for `all` to journald
receiver, which allows full output, including
unprintable characters and lines that are too long.

**Link to tracking Issue:** #30920 

**Testing:** unit test and manual test.

**Documentation:** receiver/journaldreceiver/README.md and pkg/stanza/docs/operators/journald_input.md

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]
LGTM, Thanks!

**Comment by djaglowski** [comment]
LGTM as well. Please sign the CLA and we can get this merged.

**Comment by meridional** [comment]
Thanks for reviewing. I've signed the CLA.

**Review by djaglowski — APPROVED** [review]
Thanks @meridional. I've restarted CI and will merge this as soon as it's all green.

**Pull request merged**
