### PR TITLE
[pkg/translator/opencensus] Remove usage of Map.Sort

### PR DESCRIPTION
**Pull request by dmitryax**
Replace it with comparetrest.CompareMetrics.

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6688

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Please rebase

**Comment by dmitryax** [comment]
Rebased

**Review by TylerHelmuth — COMMENTED** [review]
@dmitryax the PR title doesn't seem to line up with the changes in the PR as I don't see a removal of `Map.Sort` anywhere.  Did something go wrong with the rebase?

**Review by codeboten — COMMENTED** [review]
Looks like coreinternal's usage of sort was removed, is this all that was expected in this PR?

**Comment by dmitryax** [comment]
> Looks like coreinternal's usage of sort was removed, is this all that was expected in this PR?

Yes, that's correct. And `pkg/translator/opencensus` is the only consumer of those functions

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
