### PR TITLE
Enable AWS X-Ray receiver

### PR DESCRIPTION
**Pull request by hencrice**
**Description:** <Describe what has changed.>
Added X-Ray receiver to the top-level go.mod so that it will be included in the collector-contrib binary

**Link to tracking Issue:** <Issue number if applicable>
N/A

**Testing:**
Existing unit tests run

**Documentation:**
N/A

### CODE REVIEW

**Comment by bogdandrutu** [comment]
can you run again `make gotidy`

**Comment by hencrice** [comment]
`make gotidy` fails even on latest master:
```
$ make gotidy
make for-all CMD="rm -fr go.sum"
make[1]: Entering directory '/home/ubuntu/opentelemetry-collector-contrib'
running rm -fr go.sum in ./exporter/alibabacloudlogserviceexporter
running rm -fr go.sum in ./exporter/awsxrayexporter
running rm -fr go.sum in ./exporter/azuremonitorexporter
running rm -fr go.sum in ./exporter/carbonexporter
running rm -fr go.sum in ./exporter/elasticexporter
running rm -fr go.sum in ./exporter/honeycombexporter
running rm -fr go.sum in ./exporter/jaegerthrifthttpexporter
running rm -fr go.sum in ./exporter/kinesisexporter
running rm -fr go.sum in ./exporter/lightstepexporter
running rm -fr go.sum in ./exporter/newrelicexporter
running rm -fr go.sum in ./exporter/sapmexporter
running rm -fr go.sum in ./exporter/sentryexporter
running rm -fr go.sum in ./exporter/signalfxexporter
running rm -fr go.sum in ./exporter/splunkhecexporter
running rm -fr go.sum in ./exporter/stackdriverexporter
running rm -fr go.sum in ./extension/observer
running rm -fr go.sum in ./extension/observer/hostobserver
running rm -fr go.sum in ./extension/observer/k8sobserver
running rm -fr go.sum in ./internal/common
running rm -fr go.sum in ./internal/common/awsxray/testdata/sampleapp
running rm -fr go.sum in ./internal/common/awsxray/testdata/sampleserver
running rm -fr go.sum in ./processor/k8sprocessor
running rm -fr go.sum in ./processor/metricstransformprocessor
running rm -fr go.sum in ./processor/resourcedetectionprocessor
running rm -fr go.sum in ./receiver/awsecscontainermetricsreceiver
running rm -fr go.sum in ./receiver/awsxrayreceiver
running rm -fr go.sum in ./receiver/carbonreceiver
running rm -fr go.sum in ./receiver/collectdreceiver
running rm -fr go.sum in ./receiver/k8sclusterreceiver
running rm -fr go.sum in ./receiver/kubeletstatsreceiver
running rm -fr go.sum in ./receiver/prometheusexecreceiver
running rm -fr go.sum in ./receiver/receivercreator
running rm -fr go.sum in ./receiver/redisreceiver
running rm -fr go.sum in ./receiver/sapmreceiver
running rm -fr go.sum in ./receiver/signalfxreceiver
running rm -fr go.sum in ./receiver/simpleprometheusreceiver
running rm -fr go.sum in ./receiver/statsdreceiver
running rm -fr go.sum in ./receiver/wavefrontreceiver
running rm -fr go.sum in ./testbed
make[1]: Leaving directory '/home/ubuntu/opentelemetry-collector-contrib'
make for-all CMD="go mod tidy"
make[1]: Entering directory '/home/ubuntu/opentelemetry-collector-contrib'
running go mod tidy in ./exporter/alibabacloudlogserviceexporter
running go mod tidy in ./exporter/awsxrayexporter
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter tested by
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter.test imports
        go.opentelemetry.io/collector/config/configcheck tested by
        go.opentelemetry.io/collector/config/configcheck.test imports
        go.opentelemetry.io/collector/service/defaultcomponents imports
        go.opentelemetry.io/collector/receiver/prometheusreceiver imports
        github.com/prometheus/prometheus/discovery imports
        github.com/prometheus/prometheus/discovery/kubernetes imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/discovery imports
        github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
Makefile:59: recipe for target 'for-all' failed
make[1]: *** [for-all] Error 1
make[1]: Leaving directory '/home/ubuntu/opentelemetry-collector-contrib'
Makefile:50: recipe for target 'gotidy' failed
make: *** [gotidy] Error 2
```

**Comment by bogdandrutu** [comment]
@hencrice not sure why, see:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/801

**Comment by hencrice** [comment]
Not sure either. Maybe I will just pull from master after yours is merged in

**Comment by hencrice** [comment]
> You may need something like this:
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4ce8e848b511634b0b9d77b79a18c5675907ea35/receiver/simpleprometheusreceiver/go.mod#L16

@bogdandrutu Yea that seems to do the job. Updated PR.

**Comment by bogdandrutu** [comment]
Can you rerun make command, it should not add 8K lines

**Comment by bogdandrutu** [comment]
need to rebase, I merged another related PR, sorry

**Comment by hencrice** [comment]
@bogdandrutu `replace github.com/googleapis/gnostic => github.com/googleapis/gnostic v0.3.1` seems to cause around 200 lines to be added to multiple go.sum files.

**Comment by hencrice** [comment]
This is closed in favor of #815

**Pull request closed without merging**
