### PR TITLE
bugfix(metricstransformprocessor): transform ops are not working with…

### PR DESCRIPTION
**Pull request by srikanthccv**
… experimental_match_labels

**Description:** <Describe what has changed.>

My understanding is that match labels feature of `metricstransformprocessor` should only be used for filtering purposes and any modifications are supposed to be done with `operations`. But the current logic is returning new clone by changing the label set. Any update operation made [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor/metrics_transform_processor.go#L255) is not effective since modifications are done new clone, ideally this shouldn't be the case.

### CODE REVIEW

**Review by bogdandrutu — COMMENTED** [review]
@punya you are the owner of this :)

This does seem that changes the logic of the action.

**Comment by lonewolf3739** [comment]
I suspect this commit introduced the bug https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/c167034d1b6e0007d18187bff690065f0305405c#diff-af107eca7cedf98ffb6bf13be93997299c3abf55208d28d432a907e3683661f9L81-L93

**Comment by mx-psi** [comment]
cc @punya, could you take a look as codeowner?

**Comment by punya** [comment]
@bogdandrutu, @mx-psi, I missed this earlier. I will take a look today.

**Pull request closed without merging**
