### PR TITLE
[chore] remove codeowners who didn't become members after a period of wait

### LINKED ISSUE #30552: Ensure that all codeowners are members of the OpenTelemetry organization
### Component(s)

_No response_

### Describe the issue you're reporting

_See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868 for the last campaign_

Not all [codeowners](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS) of this repository are members of the OpenTelemetry github organization, which membership is associated with membership of the OpenTelemetry project.

The [guidelines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) enforce membership because it allows to assign and ping codeowners on issues or pull requests. Unfortunately, if you try to create an issue or assign a PR to a codeowner who is not member of OpenTelemetry, the workflow fails. I would like to fix this issue.

Going forward, I would also ideally like to make sure that we check that codeowners are members of the github organization whenever the codeowners file is touched.

The process to become a member of OpenTelemetry is straightforward. Open [this issue template](https://github.com/open-telemetry/community/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.md&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) on the [community project](https://github.com/open-telemetry/community) to get started.

I have identified a list of codeowners who are not currently members of OpenTelemetry. I will ping them in this issue below.
1. Please cross your name to indicate you have seen this message.
2. (optional) Please get in touch over Slack: I have created a slack channel for the purpose of codeowner discussions, [#otel-collector](https://cloud-native.slack.com/archives/C01N6P7KR6W). Feel free to reply here as well and provide clarifications if any information is incorrect.
3. Please work towards membership. Feel free to use 2. for any questions.
4. If I don't hear from you in the next 60 days (tentative), I will open an issue to follow up. The issue will offer to either help you become a member or open a pull request to move to emeritus status.

* [ ] @Caleb-Hurshman
* [ ] @MaxKsyunz
* [ ] @MitchellGale
* [ ] @YANG-DB
* [ ] @asaharn
* [x] @billmeyer
* [x] @emreyalvac
* [ ] @shaochengwang
* [ ] @yiyang5055
* [ ] @am-kinetica
* [x] @mcube8
* [x] @sokoide
* [x] @zdaratom
* [x] @braydonk

Thank you and apologies for the inconvenience.

### PR DESCRIPTION
**Pull request by atoulme**
Alternative or first step to #36227 

This PR removes codeowners who didn't become members after a long wait.

Fixes #30552

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]

**Comment by atoulme** [comment]
Rebased to fix conflicts ; also keeping @emreyalvac since he has started working on his membership request.

**Comment by TylerHelmuth** [comment]
@open-telemetry/collector-contrib-approvers i plan to merge this by end-of-week unless we get objections. Will merge sooner if we get enough approvals.

**Review by songy23 — APPROVED** [review]

**Comment by songy23** [comment]
Indeed there are some issues with allowlist on mainline: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/11801390829/job/32874673060

could you fix as well?

**Review by mx-psi — APPROVED** [review]
Pinging the code owners from affected components: @Aneurysm9 @shaochengwang @mxiamxia @bryan-aguilar @asaharn @ag-ramachandran @am-kinetica @wgliang @yiyang5055

**Review by MovieStoreGuy — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Comment by asaharn** [comment]
Hi @atoulme @mx-psi, I think there is some confusion. I am still an active contributor along with @ag-ramachandran for ADX Exporter component. May I know how can I become a member to fix this?

**Comment by TylerHelmuth** [comment]
@asaharn @ag-ramachandran follow the instructions [here](https://github.com/open-telemetry/community/blob/main/guides/contributor/membership.md#member). I'll be one of your sponsors.

**Comment by asaharn** [comment]
Thank you so much @TylerHelmuth  @mx-psi. I will raise the ticket and update you.

**Comment by asaharn** [comment]
Here is the ticket https://github.com/open-telemetry/community/issues/2446

**Pull request merged**
