### PR TITLE
Add `k8sevents` receiver - part 1

### PR DESCRIPTION
**Pull request by hprajapati-splunk**
This PR adds the config and factory for a `k8sevents` log receiver.(#5047)

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Just small points, thanks!

**Review by dmitryax — COMMENTED** [review]
LGTM, just few nits

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by tigrannajaryan** [comment]
@hprajapati-splunk is part 2 of this coming?

**Pull request merged**
