### PR TITLE
[Azure Monitor Exporter] Add  support to SpanEvents of type Exception

### PR DESCRIPTION
**Pull request by JorTurFer**
**Description:** 
Even the specification defines how to treat exceptions, the azure monitor exporter doesn't implement the mapping between SpanEvents with name `exception`. To be able to use this exporter in our applications (and I guess that we are not the only with this requirement), we need to properly map the exceptions to the expected application insights table.
This PR adds support to it, processing the SpanEvents and generate the proper envelopes for events with event name `exception`

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16260

**Testing:** Following the already existing tests, I created a test to check that we don't create new envelops in there is any event attached to the span without the proper name and another test checking that in case of having the proper information, the envelope is generated with the correct information. I have also tested this on my on infrastructure to check that it works, but I can't reflect that in the PR (I could attach a picture, but it doesn't make sense IMO)

**Documentation:** I only added a note explaining that exception events are mapped to Application Insights Exceptions

### CODE REVIEW

**Comment by JorTurFer** [comment]
I'm not sure if I have to update the changelog with this change, I'd say yes, but I prefer to wait before doing it

**Comment by TylerHelmuth** [comment]
Pinging @pcwiese as code owner

**Comment by pcwiese** [comment]
I was just polishing up a PR for mapping span events (including the Exceptions). If we go with this PR as a start, you need to do that piece also. Do you want to take that on?

**Comment by JorTurFer** [comment]
> I was just polishing up a PR for mapping span events (including the Exceptions). If we go with this PR as a start, you need to do that piece also. Do you want to take that on?

Depending on how much work you have already done xD I mean, if you need some weeks for having it ready, we can wait, if you need some months, we need these features :)
I'm willing to contribute with that features too. I plan to open another PR during next week, adding support to metrics.
If you tell me how do you want to map SpanEvents, I can add all of them in this PR if you want.

**Comment by JorTurFer** [comment]
I mean, if you tell me the destination for events which aren't exceptions, I can generate the telemetry items for them and return them as part of the slice I added for exceptions.

**Comment by JorTurFer** [comment]
In fact, as part of this PR I mapped exceptions to AI.Exceptions and others to AI.CustomEvents and I undo the changes to map only Exceptions because I wasn't sure about CustomEvents 
[open-telemetry/opentelemetry-collector-contrib@`654a14f` (#16333)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16333/commits/654a14f05ba8adf8db647b2ea614390424603ca4#diff-5c67450d7f58fdb220e758610d122cea8dee20d07d8cd5baed646ba559ee9f89R296-R309)

**Comment by pcwiese** [comment]
> 

I was actually nearly finished with the PR and was trying to get one out tomorrow. For metrics, I believe someone has a PR out , but I haven't taken a serious look yet.  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14916

**Comment by JorTurFer** [comment]
> I was actually nearly finished with the PR and was trying to get one out tomorrow. For metrics, I believe someone has a PR out , but I haven't taken a serious look yet. #14916

Nice!, I can close this PR in that case. I started because I didn't see any in progress work, and we need this feature to migrating our apps to otel and I hadn't got any answer to the issue I opened (don't worry, I know how complex it to manage OSS projects, these things sometime happen).
So, if you are near to finish, I'll wait. One question, is there any support for CustomEvents incoming? I mean, how are you going to map other events with AI Telemetry items?

**Comment by JorTurFer** [comment]
For our use case that Telemetry Item is needed, but I can't see anything in the specification about that, the closes things could be Logger.Events (Events API), but I'd like to know if these events will be added to CustomEvents or they will be more traces

**Comment by pcwiese** [comment]
It decided internally to map span events to the traces table.
customevents table is something different I think and not covered yet. A
snippet from that conversation...

"It sounds like agreement has converged on mapping OTel span events to AI
message telemetry (landing in the "traces" kusto table).

And in the future it looks like OTel will introduce "Real User Monitoring"
events open-telemetry/oteps#169
<https://github.com/open-telemetry/oteps/issues/169>, which would map to AI
event telemetry (landing in the "customEvents" kusto table).

I'm planning to go ahead and update the Java exporter mapping accordingly
(currently it is mapping OTel span events to event telemetry).

**Comment by JorTurFer** [comment]
Thanks for the clarification.
I guess that we need to look for a workaround for customEvents, but at least you have given me a lot of useful information.
I close this PR (your branch looks so much better than mine xD) and I'll just wait. Let me know if I can help with something :)

**Pull request closed without merging**
