### PR TITLE
Translate exception event into xray exception

### PR DESCRIPTION
**Pull request by anuraaga**
Use new exception semantic conventions for populating xray exception instead of translating HTTP.

### CODE REVIEW

**Review by pjanotti — APPROVED** [review]

**Comment by pjanotti** [comment]
LGTM @anuraaga - I will wait on the thumbs up from @kbrockhoff before merging.

**Comment by kbrockhoff** [comment]
The new code looks good. It is where we want to end up at. I suggest keeping the old logic as an alternate path for backward compatibility. It will take awhile for the new exception semantic conventions into all the SDKs and for existing applications to be re-instrumented.

**Comment by anuraaga** [comment]
Thanks @kbrockhoff changed so if there aren't any exception events we follow the previous opencensus behavior.

**Comment by kbrockhoff** [comment]
LGTM

**Pull request merged**
