### PR TITLE
UDP receiver async - fix panic during shutdown (async mode only)

### LINKED ISSUE #29120: UDP receiver async - panic during shutdown (async mode only)
### Component(s)

pkg/stanza, receiver/udplog

## Description
When udp-receiver is configured to run in async mode (and only then), when stopping or restarting, panic happens due to trying to write to closed channel.
When stop is called, it closes the messageQueue channel, signaling to processMessagesAsync to stop running. However, readMessagesAsync sometimes tries to write into the closed channel (depends whether the method is currently reading from the closed connection or currently trying to write to the channel), and as a result, panic error happens.
readMessagesAsync needs to finish before closing the channel.

## Steps to Reproduce
Restart strato once or twice

## Expected Result
No panic should happen. udp receiver should stop gracefully.

## Actual Result
Panic happens

### Collector version

0.88.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hovavza**
**Description:** 
Link to tracking Issue: Fixes #29120
Fixing a bug - panic happens during stop method in async mode only (didn't affect the default non-async mode).
When stop is called, it closes the messageQueue channel, signaling to processMessagesAsync to stop running. However, readMessagesAsync sometimes tries to write into the closed channel (depends whether the method is currently reading from the closed connection or currently trying to write to the channel), and as a result, panic error happens.

Separated between wg (waitGroup that serves non-async code and processMessagesAsync) & the new wg_reader (waitGroup serving readMessagesAsync only). This allows us to first stop readMessagesAsync, wait for it to finish, before closing the channel.
Instead, stop (in async mode) should do the following:
1. Close the connection - signaling readMessagesAsync to stop - the messageQueue channel will remain open until that method is done so there's no risk of panic (due to writing to a closed channel).
2. Wait for readMessagesAsync to finish (wait for new wg_reader).
3. Close messageQueue channel (signaling processMessagesAsync to stop)
4. Wait for processMessagesAsync to finish (wait sg).

**Link to tracking Issue:** 29120

**Testing:** Unitests ran. Ran concrete strato, stopped & restarted multiple times, didn't see any panic (and stop completed successfully as expected)

**Documentation:** None.

### CODE REVIEW

**Comment by atoulme** [comment]
The changes make sense to me, is there a way to write a test to reproduce the issue?

**Comment by hovavza** [comment]
> The changes make sense to me, is there a way to write a test to reproduce the issue?

I'm not sure how. There is the TestInput test method that would fail if the Stop method failed (including panic), including in the async mode. However, it's a matter of luck and volume. The readMessagesAsync method needs to be after the read-from-port line and before the channel addition while the Stop is called. In low traffic scenarios like the tests, this wouldn't happen.

**Comment by crobert-1** [comment]
Hello @hovavza, can you update the PR description with the following line?
```
Link to tracking Issue: Fixes #29120
```
This will allow GitHub to properly link this to the issue it's fixing.

**Comment by hovavza** [comment]
@djaglowski @crobert-1 @atoulme , can we complete this PR?

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
