### PR TITLE
Fix default docker_observer endpoint on Windows

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
The default endpoint for the `docker_observer` is incorrect on Windows: it should be `npipe:////./pipe/docker_engine` on Windows. Without this change the observer fails on its default configuration on Windows.

Updated `extension/observer/dockerobserver` and `internal/docker` (including respective tests) to have a per OS default value for endpoint that allows the observer to work with default config on Windows.

**Link to tracking Issue:** N/A

**Testing:**
Manual tests using the following config:
```yaml
extensions:
  docker_observer:

receivers:
  receiver_creator:
    watch_observers: [docker_observer]
    receivers:
      nginx:
        rule: type == "container" and name matches "nginx" and port == 80
        config:
          endpoint: '`endpoint`/status'
          collection_interval: 10s

exporters:
  debug:
    verbosity: detailed

service:
  extensions: [docker_observer]
  pipelines:
    logs:
      receivers: [receiver_creator]
      processors: []
      exporters: [debug]
```

**Documentation:**
- [X] Updated readme files
- [X] chloggen (~~pending PR number~~)

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Does this need a changelog?

**Comment by pjanotti** [comment]
Yes, I was waiting the PR number to create one.

**Comment by pjanotti** [comment]
also more `go mod tidy` ...

**Comment by pjanotti** [comment]
Unrelated windows-unit-test failures, see #34252

```terminal
=== FAIL: compression/zstd TestMRUReset (0.00s)
    mru_test.go:83: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/otelarrow/compression/zstd/mru_test.go:83
        	Error:      	Not equal: 
make[2]: *** [../../Makefile.Common:126: test] Error 1
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestMRUReset

make[1]: *** [Makefile:179: internal/otelarrow] Error 2
=== FAIL: compression/zstd TestMRUReset (re-run 1) (0.00s)
make[1]: *** Waiting for unfinished jobs....
    mru_test.go:83: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/otelarrow/compression/zstd/mru_test.go:83
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestMRUReset
```

**Comment by pjanotti** [comment]
Another hit on #34252 https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10187830131/job/28182733995?pr=34358#step:6:514

**Comment by pjanotti** [comment]
Not sure about this one https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10187830131/job/28182730990?pr=34358#step:6:21 ... kicking it again...
```terminal
/usr/bin/sh: line 1: D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum: Device or resource busy
make[2]: *** [../../Makefile.Common:126: test] Error 126
make[1]: *** [Makefile:179: processor/cumulativetodeltaprocessor] Error 2
make[1]: *** Waiting for unfinished jobs....
D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags=""
```

**Comment by pjanotti** [comment]
Also hitting #34297

**Review by rmfitzpatrick — APPROVED** [review]

**Comment by pjanotti** [comment]
Similar to the [above](), but,  a different component and symptom  https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10207176086/job/28241472190?pr=34358#step:6:21

```terminal
/usr/bin/sh: line 1: D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum: cannot execute: required file not found
make[2]: *** [../../Makefile.Common:126: test] Error 127
make[1]: *** [Makefile:179: pkg/batchperresourceattr] Error 2
make[1]: *** Waiting for unfinished jobs....
D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags=""
```

**Review by atoulme — APPROVED** [review]

**Comment by crobert-1** [comment]
> /label os:windows

Just an FYI, I don't believe adding labels via comments works on PRs. ([Source](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e96d3b341c0b9e130062efd52126aa357e4eb3fc/.github/workflows/add-labels.yml#L8))

**Comment by pjanotti** [comment]
@crobert-1 yes, you're right that didn't work here - it did work earlier on an issue 👍🏼

**Comment by pjanotti** [comment]
Another hit on `gotestsum` https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10287492291/job/28470657160?pr=34358#step:6:20

```terminal
D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags=""
/usr/bin/sh: line 1: D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum: Device or resource busy
make[2]: *** [../../Makefile.Common:126: test] Error 126
make[1]: *** [Makefile:179: processor/probabilisticsamplerprocessor] Error 2
make[1]: *** Waiting for unfinished jobs....
D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags=""
```

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
