### PR TITLE
[exporter/file] add encoding extension support

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
This adds support to set an encoding extension on the file exporter, overriding the format type.

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please fix lint https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8292532526/job/22694195902?pr=31774#step:8:548

**Review by MovieStoreGuy — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
Need a rebase

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Do we want to deprecate and remove `format` config later?

**Comment by atoulme** [comment]
Yes, much later.

**Pull request merged**
