### PR TITLE
Add deprecation notice for New Relic Exporter

### PR DESCRIPTION
**Pull request by jack-berg**
As mentioned in the README, the New Relic exporter for the collector has been made obsolete. We're deprecating it with a May 1st 2022 removal date.

/cc @alanwest @sharrmander @nrcventura

### CODE REVIEW

**Comment by dashpole** [comment]
Should we make more noise?  for the deprecation of the stackdriver exporter, we log the deprecation: exporter/stackdriverexporter/factory.go

**Comment by dashpole** [comment]
This should also be listed in the changelog

**Comment by bogdandrutu** [comment]
Logging a deprecation "log entry" is good.

**Comment by jack-berg** [comment]
Changelog entry and deprecation logging added 👍

**Review by nrcventura — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
