### PR TITLE
[storagetest] Build out package for more flexible test cases

### PR DESCRIPTION
**Pull request by djaglowski**
The storagetest package exists to enable testing the usage of
storage extensions. This PR extends and cleans up the package
so that it can be used for a far larger set of test cases.

### CODE REVIEW

**Comment by djaglowski** [comment]
@open-telemetry/collector-contrib-approvers, PTAL. This will enable sufficient testing on #12871.

**Comment by djaglowski** [comment]
@collector-contrib-approvers, is anyone able to please review this?

**Review by dmitryax — APPROVED** [review]

**Comment by kentquirk** [comment]
@djaglowski this broke tests -- branches based on the current main are failing the impi tests:

```
/Library/Developer/CommandLineTools/usr/bin/make -C extension/storage impi
storagetest/host_test.go: Import groups are not in the proper order: ["Std" "Third party" "Third party"]
storagetest/extension_test.go: Import groups are not in the proper order: ["Std" "Third party" "Third party"]
```

**Comment by TylerHelmuth** [comment]
I am working on a fix

**Comment by TylerHelmuth** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13402

**Pull request merged**
