### PR TITLE
chore: update exporter/influxdbexporter and receiver/influxdbreceiver dependency

### PR DESCRIPTION
**Pull request by jacobmarble**

### CODE REVIEW

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
This PR depends on updating the core dependency as well. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4317

**Comment by jacobmarble** [comment]
> This PR depends on updating the core dependency as well. See #4317

I have rebased and pushed.

**Review by jpkrohling — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@jacobmarble please rebase, I remember to see some of the upgrades already

**Comment by jacobmarble** [comment]
@bogdandrutu PTAL

**Pull request merged**
