### PR TITLE
Add collector config wizard

### PR DESCRIPTION
**Pull request by pmcollins**
Attempting to get @jjackson-s 's changes tidied up and committed. His PR is here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4592

(I am unable to update that PR because its source is a branch in his private fork. Will be reaching out to him separately.)

### CODE REVIEW

**Comment by jevon-23** [comment]
Hey, sorry I got super busy with school work and moving so I couldn't really find work to fix up the PR.

Is there anything you need for me to do?

**Comment by jevon-23** [comment]
Also can you send over your email again to me? I ended up losing it once I lost my company email was lost.

**Comment by jevon-23** [comment]
Also if I could remember before, the branch was having a merge conflict with one of the go.mod files in a subdirectory. The rest should be good.

**Comment by pmcollins** [comment]
Hey Jevon, good to hear from you! I rebased your PR on the latest main and made some tweaks. Works fine on my machine, including tests. Can you grab this code and force push to your branch? I think we're really close, apparently just needs a god mod tidy?

Emails are `pablo.collins at gmail` and `pcollins at splunk`.

**Comment by jevon-23** [comment]
> Hey Jevon, good to hear from you! I rebased your PR on the latest main and made some tweaks. Works fine on my machine, including tests. Can you grab this code and force push to your branch? I think we're really close, apparently just needs a god mod tidy?
> 
> Emails are `pablo.collins at gmail` and `pcollins at splunk`.

Good to hear from yo was well! And yes sounds good, I will be in between my classes soon and will try to make the changes you need. I'm pretty sure that the PR has closed, should I just update my branch and let you know?

**Comment by jevon-23** [comment]
> > Hey Jevon, good to hear from you! I rebased your PR on the latest main and made some tweaks. Works fine on my machine, including tests. Can you grab this code and force push to your branch? I think we're really close, apparently just needs a god mod tidy?
> > Emails are `pablo.collins at gmail` and `pcollins at splunk`.
> 
> Good to hear from yo was well! And yes sounds good, I will be in between my classes soon and will try to make the changes you need. I'm pretty sure that the PR has closed, should I just update my branch and let you know?

never mind, looked back and noticed that you guys reopened it. I will soon make the changes necessary and update the PR with what is needed.

**Comment by pmcollins** [comment]
> > > Hey Jevon, good to hear from you! I rebased your PR on the latest main and made some tweaks. Works fine on my machine, including tests. Can you grab this code and force push to your branch? I think we're really close, apparently just needs a god mod tidy?
> > > Emails are `pablo.collins at gmail` and `pcollins at splunk`.
> > 
> > 
> > Good to hear from yo was well! And yes sounds good, I will be in between my classes soon and will try to make the changes you need. I'm pretty sure that the PR has closed, should I just update my branch and let you know?
> 
> never mind, looked back and noticed that you guys reopened it. I will soon make the changes necessary and update the PR with what is needed.

Thanks Jevon, whatever you'd prefer is fine. I wanted to give you a chance to get this PR over the line (I've made the necessary changes to minimize work for you) so that you can get attribution for the lines of code when it merges if you're interested.

**Comment by jjackson-s** [comment]
Updated the code and pushed it, but accidentally made a change using my personal account instead of my splunk one, so I am currently waiting to be verified by the CLA and everything should be good.

**Comment by jjackson-s** [comment]
> > > > Hey Jevon, good to hear from you! I rebased your PR on the latest main and made some tweaks. Works fine on my machine, including tests. Can you grab this code and force push to your branch? I think we're really close, apparently just needs a god mod tidy?
> > > > Emails are `pablo.collins at gmail` and `pcollins at splunk`.
> > > 
> > > 
> > > Good to hear from yo was well! And yes sounds good, I will be in between my classes soon and will try to make the changes you need. I'm pretty sure that the PR has closed, should I just update my branch and let you know?
> > 
> > 
> > never mind, looked back and noticed that you guys reopened it. I will soon make the changes necessary and update the PR with what is needed.
> 
> Thanks Jevon, whatever you'd prefer is fine. I wanted to give you a chance to get this PR over the line (I've made the necessary changes to minimize work for you -- feel free to grab the code in this PR and force push to your branch) so that you can get attribution for the lines of code when it merges if you're interested.
> 
> If that's not important to you though I'm more than happy to finish this up so you can focus on your studies. :-)

Thanks! After the CLA goes through for my other account, I'll let you know if I think I can get it done in a reasonable time.

**Comment by jevon-23** [comment]
Hey @pmcollins, would you be willing to hop on a zoom or anything and get this situated? I tried doing it and was running into issues with the mod files and merges.

**Comment by pmcollins** [comment]
Yes definitely @jjackson-s. Any time is fine, just let me know what works for you.

**Comment by jevon-23** [comment]
> Yes definitely @jjackson-s. Any time is fine, just let me know what works for you.

Sounds good. Today is pretty packed for me but can we meet sometime tomorrow around afternoon around 2:30 p.m. PST? or is that too late?

**Comment by jjackson-s** [comment]
Hey @pmcollins , if you have sometime tomorrow after 2 can we hop on a zoom?

**Comment by pmcollins** [comment]
That works @jjackson-s -- I assume it's 2pm Pacific (but Eastern works too)? Maybe we can set it up via the CNCF Slack? Details here: https://github.com/open-telemetry/community#communication

**Comment by codeboten** [comment]
@pmcollins @jjackson-s is this PR still needed or is the plan to get #4592 merged instead?

**Pull request closed without merging**
