### PR TITLE
Add option to configure scrape timeout for prometheus exec receiver

### PR DESCRIPTION
**Pull request by yotamloe**
I used this receiver with [Prometheus/cloudwatch_exporter](https://github.com/prometheus/cloudwatch_exporter) The wait for the response from cloudwatch API took more than the static 10s scrape timeout, So I added a new option to configure `scrape_timeout`

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
cc @keitwb as a codeowner

**Comment by mx-psi** [comment]
@keitwb friendly ping

**Review by keitwb — APPROVED** [review]
Looks good.

**Comment by keitwb** [comment]
@tigrannajaryan can you look and merge if all looks good?

**Review by tigrannajaryan — APPROVED** [review]
LGTM
@bogdandrutu @dmitryax I recall you recently mentioned something about re-working scrapers. Does this in any way conflict with what you intend to do or good to merge?

**Comment by mx-psi** [comment]
@bogdandrutu @dmitryax friendly ping, see message above by Tigran

**Comment by mx-psi** [comment]
@yotamloe please fix the merge conflict

**Comment by dmitryax** [comment]
@mx-psi @tigrannajaryan Sorry for delayed response, it does not conflict with the new interface for scrapers that I'm working on

**Review by dmitryax — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Thanks @yotamloe for the PR and for the patience while it was reviewed.

**Pull request merged**
