### PR TITLE
[receiver:elasticsearchreceiver]: Add two additional cluster level metric

### LINKED ISSUE #13748: [receiver/elasticsearchreceiver]: Add two cluster level metrics
### Enhancement

Add the following cluster level metrics for the `elasticsearchreceiver`:

* `elasticsearch.cluster.pending_tasks`
* `elasticsearch.cluster.in_flight_fetch`

### PR DESCRIPTION
**Pull request by davidji99**
Fixes #13748

### CODE REVIEW

**Comment by djaglowski** [comment]
Please split this into two PRs. I think the fact that the PR is titled so vaguely is a good indication that unrelated things are being done here.

**Comment by davidji99** [comment]
> Please split this into two PRs. I think the fact that the PR is titled so vaguely is a good indication that unrelated things are being done here.

I'm only adding three more metrics in this PR: elasticsearch.cluster.in_flight_fetch, elasticsearch.cluster.pending_tasks,
and elasticsearch.node.cache.count.
  
I will update the title to be more descriptive.

**Comment by davidji99** [comment]
> > Please split this into two PRs. I think the fact that the PR is titled so vaguely is a good indication that unrelated things are being done here.
> 
> @djaglowski
> 
> I'm only adding three metrics in this PR: elasticsearch.cluster.in_flight_fetch, elasticsearch.cluster.pending_tasks, and elasticsearch.node.cache.count.
> 
> I will update the title to be more descriptive.

bump @djaglowski

**Review by djaglowski — CHANGES_REQUESTED** [review]
Please split this into two PRs, one that adds the cluster metrics, the other for the node metric.

**Comment by davidji99** [comment]
@djaglowski 

I've re-worked this PR to include just the two new cluster-level metrics. I will open separate PR for the other node level metric.

Please review.

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
