### PR TITLE
[docs] Add status header for SAP HANA receiver

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** 
Add status header for SAP HANA receiver

### CODE REVIEW

**Review by pmm-sumo — CHANGES_REQUESTED** [review]
Technically, this is in development since it is not part of contrib distribution (yet) though I believe it could be added there @dehaansa ?

**Comment by dehaansa** [comment]
> Technically, this is in development since it is not part of contrib distribution (yet) though I believe it could be added there @dehaansa ?

What do you mean by "not part of the contrib distribution"? It's added to the contrib collector in components.go, my understanding was that was the main portion of adding to the contrib distribution

**Review by codeboten — COMMENTED** [review]
@dehaansa you'll need to add it to the manifest to have it be included: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

**Review by dehaansa — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
