### PR TITLE
[exporter/sumologic]: update configuration format

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

- Change configuration format to be inline with [Sumo Logic one](https://github.com/SumoLogic/sumologic-otel-collector/tree/v0.77.0-sumo-0/pkg/exporter/sumologicexporter)

**Link to tracking Issue:**

Part of #23059

**Testing:** N/A

**Documentation:** Readme changed

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
cc: @astencel-sumo

**Comment by sumo-drosiek** [comment]
I can split this PR on two parts if needed:

- changing configuration format in readme
- changes deprecation

**Comment by astencel-sumo** [comment]
Yes, I think it's better to create two separate PRs for these two changes.

**Comment by sumo-drosiek** [comment]
> Yes, I think it's better to create two separate PRs for these two changes.

Restoring to previous state then

**Review by andrzej-stencel — APPROVED** [review]
LGTM, this is just a README formatting change in preparation for future deprecations :+1:

**Comment by codeboten** [comment]
Restarting integration test, the failure may have been addressed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23187

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
