### PR TITLE
[chore] update jaeger dep and remove koanf 1.5 dep

### LINKED ISSUE #26567: [pkg/translator/jaeger] Bump github.com/jaegertracing/jaeger from 1.41.0 to 1.49.0 broke tests
### Component(s)

pkg/translator/jaeger

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6147608956/job/16679659646?pr=26563

```
go test -race -timeout 300s -parallel 4 --tags="" -cover ./... -covermode=atomic -args -test.gocoverdir="/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit"
--- FAIL: TestProtoToTraces (0.01s)
    --- FAIL: TestProtoToTraces/two-spans-with-follower (0.00s)
        jaegerproto_to_traces_test.go:313: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/translator/jaeger/jaegerproto_to_traces_test.go:313
            	Error:      	Not equal: 
            	            	expected: ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013440)}
            	            	actual  : ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013638)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -70,3 +70,3 @@
            	            	         ParentSpanId: (data.SpanID) (len=8) {
            	            	-         00000000  00 00 00 00 00 00 00 00                           |........|
            	            	+         00000000  af ae ad ac ab aa a9 a8                           |........|
            	            	         },
            	Test:       	TestProtoToTraces/two-spans-with-follower
    --- FAIL: TestProtoToTraces/a-spans-with-two-parent (0.00s)
        jaegerproto_to_traces_test.go:313: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/translator/jaeger/jaegerproto_to_traces_test.go:313
            	Error:      	Not equal: 
            	            	expected: ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013458)}
            	            	actual  : ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013878)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -70,3 +70,3 @@
            	            	         ParentSpanId: (data.SpanID) (len=8) {
            	            	-         00000000  00 00 00 00 00 00 00 00                           |........|
            	            	+         00000000  af ae ad ac ab aa a9 a8                           |........|
            	            	         },
            	Test:       	TestProtoToTraces/a-spans-with-two-parent
FAIL
```

### Collector version

mainline

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### LINKED ISSUE #28647: remove koanf v1.5 dependency
### Component(s)

_No response_

### Describe the issue you're reporting

i'm trying to get the last of the koanf v1.5 dependencies cleaned up, once the next jaeger release (v1.51.0) is out, we'll be down to a single dependency in the contrib repo that relies on koanf v1.5: the jaegerexporter

That component has been removed from the repo at v0.85.0, but it remains as a dependency for the testbed (to generate jaeger data for the jaeger receiver tests)... there's a couple of things we could do here and i was curious what people here thought of the options:

1. remove the jaeger generation test from the testbed
2. remove the jaegerexporter and generate data using some other tool
3. release a v0.85.1 patch for jaegerexporter to remove the koanf dependency

### PR DESCRIPTION
**Pull request by codeboten**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28647

After this is merged contributors can finally use go workspaces in this repo.

Fixes #26567

### CODE REVIEW

**Comment by codeboten** [comment]
not stale, waiting on [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27636)

**Comment by codeboten** [comment]
There's a change in jaeger v1.45.0 that causes the pkg/translator/jaeger test to fail:

```
--- FAIL: TestProtoToTraces (0.00s)
    --- FAIL: TestProtoToTraces/two-spans-with-follower (0.00s)
        jaegerproto_to_traces_test.go:313: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/translator/jaeger/jaegerproto_to_traces_test.go:313
            	Error:      	Not equal: 
            	            	expected: ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013470), state:(*internal.State)(0xc0001f2e2c)}
            	            	actual  : ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013668), state:(*internal.State)(0xc0001f318c)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -70,3 +70,3 @@
            	            	         ParentSpanId: (data.SpanID) (len=8) {
            	            	-         00000000  00 00 00 00 00 00 00 00                           |........|
            	            	+         00000000  af ae ad ac ab aa a9 a8                           |........|
            	            	         },
            	Test:       	TestProtoToTraces/two-spans-with-follower
    --- FAIL: TestProtoToTraces/a-spans-with-two-parent (0.00s)
        jaegerproto_to_traces_test.go:313: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/translator/jaeger/jaegerproto_to_traces_test.go:313
            	Error:      	Not equal: 
            	            	expected: ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc000013488), state:(*internal.State)(0xc0001f2e4c)}
            	            	actual  : ptrace.Traces{orig:(*v1.ExportTraceServiceRequest)(0xc0000138a8), state:(*internal.State)(0xc00022a84c)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -70,3 +70,3 @@
            	            	         ParentSpanId: (data.SpanID) (len=8) {
            	            	-         00000000  00 00 00 00 00 00 00 00                           |........|
            	            	+         00000000  af ae ad ac ab aa a9 a8                           |........|
            	            	         },
            	Test:       	TestProtoToTraces/a-spans-with-two-parent
FAIL
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger	coverage: 95.4% of statements
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger	0.378s
FAIL
```

@frzifus @yurishkuro it looks like maybe this change: https://github.com/jaegertracing/jaeger/commit/0ee275a53eca8774268e432d2c912d6f4ef563e8, any thoughts on how this test should change to address the failure?

**Comment by yurishkuro** [comment]
@codeboten yes, that's the change. It allows a lone follows-from reference to be treated as a parent. However, the OTLP span that the Jaeger span is compared against after translation does not define parent ID. The tests can be fixed with this change:
```diff
diff --git a/pkg/translator/jaeger/jaegerproto_to_traces_test.go b/pkg/translator/jaeger/jaegerproto_to_traces_test.go
index 3ea43570d8..a75be85c87 100644
--- a/pkg/translator/jaeger/jaegerproto_to_traces_test.go
+++ b/pkg/translator/jaeger/jaegerproto_to_traces_test.go
@@ -919,6 +919,7 @@ func generateTracesTwoSpansWithFollower() ptrace.Traces {
        span.SetName("operationC")
        span.SetSpanID([8]byte{0x1F, 0x1E, 0x1D, 0x1C, 0x1B, 0x1A, 0x19, 0x18})
        span.SetTraceID(spans.At(0).TraceID())
+       span.SetParentSpanID(spans.At(0).SpanID())
        span.SetStartTimestamp(spans.At(0).EndTimestamp())
        span.SetEndTimestamp(spans.At(0).EndTimestamp() + 1000000)
        span.SetKind(ptrace.SpanKindConsumer)
```

However, it would cause breaks in some other conversion tests, for the same reason - one side does not include the reference and/or ParentID.

**Comment by yurishkuro** [comment]
Yes, I believe translation code is incorrect. For instance, in `makeJaegerProtoReferences`, the parentID is unconditionally translated into CHILD_OF reference, but it should be conditional on _not having a link_ with the same parentID, i.e.

1. process all links and convert them to references
2. if neither of them mentioned parentID, then prepend a CHILD_OF reference with that ID

Probably a similar issue in Thrift translation.

**Review by atoulme — APPROVED** [review]

**Pull request merged**
