### PR TITLE
fix: property endpoint is ignored when using instrumentation_key

### PR DESCRIPTION
**Pull request by hgaol**
**Description:** <Describe what has changed.>

Fixing a bug

**Link to tracking Issue:**  #33971 

**Testing:** It's just one line and simple, so I just tested locally. If test cases needed, I can provide in this PR.

**Documentation:** if no connection string and endpoint is provided, then use it instead of the default one.

### CODE REVIEW

**Comment by hgaol** [comment]
Hi @dashpole , @pcwiese and @bogdandrutu , is there anyone could help to review this PR? thx!

**Comment by dashpole** [comment]
Looks like @pcwiese is the codeowner, and is the person you need to review before this can be merged

**Comment by hgaol** [comment]
Looks no response for about one month, could anyone else help on that or any suggestion? @dashpole @bogdandrutu

**Review by pcwiese — APPROVED** [review]

**Review by dashpole — APPROVED** [review]
The fix is trivial, so i'm approving.  It would be good to have unit tests to catch these sorts of problems in general, though

**Comment by michaelkira** [comment]
> The fix is trivial, so i'm approving. It would be good to have unit tests to catch these sorts of problems in general, though

Thanks @dashpole  What else is needed to get pr merged? It seems @hgaol dont have permission to merge the pr

**Pull request merged**
