### PR TITLE
[processor/transform] Add Concat factory function

### LINKED ISSUE #12476: [processor/transform] Add ability to concat strings
**Is your feature request related to a problem? Please describe.**
There are situations where a user might need to combine existing fields to be used as an argument in an Invocation.  [Here is an example.](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1657799193277499).  At the moment the TQL has no build-in capability to do this and the transform processor has not function that can do it.

**Describe the solution you'd like**
I think we have 2 options.

1. **Add a "Concat" factory to the transform processor that takes 2 string arguments and returns a concatenation of the 2 string.** This is a solution that should be implemented now.
2. ~~Add something to the TQL so it knows how to do this natively.~~ We should do this, but in the future.  For now, to enhance the transform processor, we'll use a Factory.  

I'm leaning towards option 1, as it is simpler to implement and factories are already a defined pattern.

### PR DESCRIPTION
**Pull request by evan-bradley**
**Description:**

Add the `Concat` factory function to the transform processor as a follow-up to #13120.

**Link to tracking Issue:**

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12476

**Testing:**

Integration tests were added to the transform processor.

**Documentation:**

No documentation was changed.

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@TylerHelmuth personal opinion, JOIN is too generic and may be confusing, especially since I can think of "joining metrics, logs" etc. Have you consider a better name?

**Comment by TylerHelmuth** [comment]
@bogdandrutu could always update the name to be JoinStrings

**Comment by bogdandrutu** [comment]
or `concat`? both options are better than just `join`

**Comment by TylerHelmuth** [comment]
Concat is good with me

**Comment by evan-bradley** [comment]
I'll open a follow-up PR to rename it to Concat.

**Comment by evan-bradley** [comment]
I combined the factory rename in the TQL with the changes in this PR. If we want to make the TQL changes separately, let me know and I will open a new PR for them.

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
