### PR TITLE
[exporter/azuredataexplorerexporter]: Fixes ingestion issue due to compression prop missing

### PR DESCRIPTION
**Pull request by asaharn**
**Description:** 
Data Ingestion to ADX failure fix, by adding a compression prop in ingestion properties 

**Link to tracking Issue:** 
#35353 

**Testing:** <Describe what testing was performed and which tests were added.>
Successful ingestions
image

**Documentation:** <Describe the documentation added.>
No Doc required

### CODE REVIEW

**Review by ag-ramachandran — APPROVED** [review]

**Comment by asaharn** [comment]
Hi @andrzej-stencel Gentle reminder for a review on the PR

**Comment by asaharn** [comment]
@dmitryax @andrzej-stencel please review the PR.

**Comment by crobert-1** [comment]
Would it be worth it to document this in the component's README? If this could cause any unexpected results for users it may be worth it, but I'm relying on the expertise of others here to know if it's necessary or not.

**Comment by asaharn** [comment]
Hi @crobert-1 This is an internal change that is not impacting the end users.  I think documentation is not required since this is a bugfix.

**Comment by asaharn** [comment]
Hi @dmitryax this is critical fix for us, can we get someone to approve and merge this fix?

**Review by andrzej-stencel — APPROVED** [review]
Does this mean the exporter did not work at all before this fix? Is this related to a change in Azure?

**Pull request merged**
