### PR TITLE
[exporter/datadogexporter] Unexport private struct and const

### PR DESCRIPTION
**Pull request by lastchiliarch**
**Description:** <Describe what has changed.>

 make MaxMetaValLen and PayLoad private

**Link to tracking Issue:** <Issue number if applicable>

#4056

**Testing:** <Describe what testing was performed and which tests were added.>

Unit Test

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
👍

**Comment by ericmustin** [comment]
lgtm, i think we need someone to allow workflow to run tho.

**Review by bogdandrutu — APPROVED** [review]

**Comment by lastchiliarch** [comment]
> lgtm, i think we need someone to allow workflow to run tho.

Thanks a lot.  By the way, TestEndToEnd seems unstable, how can I deal with the failed unittest?

**Comment by bogdandrutu** [comment]
@lastchiliarch please rebase, the main branch is fixed

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
