### PR TITLE
[chore] Improving life cycle tests reporting

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** 

Adds running the lifecycles in parallel and named subtests to improve visibility into time spent.

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
Running your branch locally @codeboten ,  I was able to get this working:

```
smarciniak@HYWTN6M2FP  cmd/otelcontribcol  ⇅ codeboten/update-otel-jun5  make test-with-cover
mkdir -p /Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/cmd/otelcontribcol/coverage/unit
go test -race -timeout 300s -parallel 4 --tags="" -cover ./... -covermode=atomic -args -test.gocoverdir="/Users/smarciniak/Development/OpenSource/opentelemetry-collector-contrib/cmd/otelcontribcol/coverage/unit"
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol	273.031s	coverage: 44.8% of statements
```

**Comment by MovieStoreGuy** [comment]
Sorry, added in @codeboten branch to see if I didn't luck out on my machine.

**Comment by dmitryax** [comment]
Does it require the core dep upgrade? It seems unrelated

**Comment by MovieStoreGuy** [comment]
> Does it require the core dep upgrade? It seems unrelated

Core dep upgrade is where @codeboten found the error. Unfortunately, I haven't setup the Atlassian workspace with actual runners (or at least to my knowledge), so the easiest way for me to test effectively is to raise it against contrib.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
