### PR TITLE
[receiver/postgresql] Enable component

### PR DESCRIPTION
**Pull request by vmihailenco**
**Description:**
No code changes, but just enabling postgresqlreceiver so we can start using it.

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6983

**Testing:**
I've compiled this locally with `make otelcontribcol` and have been running the collector for few days. Collector is stable and PostgreSQL metrics are coming in as expected.

Accompanying PR in releases: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/52

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
@djaglowski please confirm that this component is ready to go

**Review by djaglowski — APPROVED** [review]
The component is ready. Thanks @vmihailenco!

**Comment by jpkrohling** [comment]
Once the conflicts are resolved, I'll merge this PR.

**Review by codeboten — APPROVED** [review]
Thanks!

**Review by codeboten — COMMENTED** [review]
Please rebase

**Comment by jpkrohling** [comment]
I don't know why, but I still can't merge this:

image

**Comment by vmihailenco** [comment]
Rebased, PTAL

**Comment by vmihailenco** [comment]
```
golangci-lint run --allow-parallel-runners
level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

This seems to be a common problem with other PRs as well....

**Review by codeboten — COMMENTED** [review]
Please rebase one more time, the problem with the lint target was addressed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7169

**Comment by vmihailenco** [comment]
Done. Unittests seems unrelated

```
=== RUN   TestEndToEndSummarySupport
    end_to_end_test.go:181: Left-over unmatched Prometheus scrape content: "test_scrape_samples_post_metric_relabeling 0 1642230746261test_scrape_samples_scraped 0 1642230746261test_scrape_series_added 0 1642230746261test_up 0 1642230746261"
```

**Comment by jpkrohling** [comment]
Thank you for your patience! This is now merged.

**Pull request merged**
