### PR TITLE
Add error checks in datadog, elasticsearch and loadbalancer exporters

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
**Description:** <Describe what has changed.>

adds errorcheck in datadog, elasticsearch and loadbalancer exporters

**Link to tracking Issue:** #9749 

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
My gut says these should be broken out into separate PRs, 1 per exporter.  Will be easier to review and will keep the commit history cleaner.

**Comment by pmm-sumo** [comment]
Linter seems to fail:
```
Error: internal/translator/elastic/metadata.go:101:25: Error return value of `service.MarshalFastJSON` is not checked (errcheck)
	service.MarshalFastJSON(w)
```

**Comment by mx-psi** [comment]
Agree with Tyler, I think it would be preferable to have different components in different PRs (with maybe the exception of components that are tightly related, like components from the same vendor or supporting the same technology)

**Comment by DiptoChakrabarty** [comment]
Sure Ill close this one and open 3 new separate PRs

**Comment by DiptoChakrabarty** [comment]
added #9964 #9965 #9966

**Pull request closed without merging**
