### PR TITLE
chore: bump testcontainers-go to 0.18.0

### PR DESCRIPTION
**Pull request by mdelapenya**
**Description:** <Describe what has changed.>

In the light of the recent release of testcontainers-go, which removes the replace directive with Docker, this PR is bumping all the modules using it to that new version.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

```shell
#for each go module
go run ./... -v -count=1 -tags=integration
```

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
Thanks, @mdelapenya!

**Comment by mdelapenya** [comment]
> Thanks, @mdelapenya!

My pleasure 😊 I decided to jump in because dependabot is not smart enough to resolve the replace directives that were removed in the lady release

**Review by djaglowski — APPROVED** [review]

**Comment by mdelapenya** [comment]
@djaglowski @dmitryax how would you see adding your project to the users of testcontainers-go here? https://golang.testcontainers.org/#who-is-using-testcontainers-go https://github.com/testcontainers/testcontainers-go/blob/main/docs/index.md#who-is-using-testcontainers-go

It would be wonderful having you there 😊

**Comment by dmitryax** [comment]
I'm up for that!

**Comment by djaglowski** [comment]
@mdelapenya, I think that would be great!

**Comment by dmitryax** [comment]
@mdelapenya @djaglowski I submitted a PR https://github.com/testcontainers/testcontainers-go/pull/861

**Pull request merged**
