### PR TITLE
[receiver/sshcheck] enable Windows

### LINKED ISSUE #30650: [receiver/sshcheck] Windows support
### Component(s)

receiver/sshcheck

### Describe the issue you're reporting

It is unclear to me why Windows is not supported for the sshcheckreceiver. The README doesn't mention why it's not supported, and I don't see any code libraries used that might be OS specific.
I have opened [a draft PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30648) to try and run Windows tests on this component and see if they fail.

### PR DESCRIPTION
**Pull request by atoulme**
Removes the checks forbidding to use sshcheckreceiver on Windows.

Fixes #30650

### CODE REVIEW

**Comment by atoulme** [comment]
@codeboten @nslaughter please take a look

**Review by pjanotti — APPROVED** [review]
LGTM

**Comment by atoulme** [comment]
Still waiting for review.

**Review by codeboten — APPROVED** [review]
Thanks @atoulme!

**Review by codeboten — COMMENTED** [review]
@atoulme the readme needs to be regenerated https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8760447193/job/24045427581?pr=30648#step:17:304

**Pull request merged**
