### PR TITLE
[receiver/awscloudwatch] Fix validation in some scenarios

### LINKED ISSUE #14952: [receiver/awscloudwatch]
## Description
validation for named configs will not work as expected as the `createDefaultConfig` creates a non-nil autodiscover config. 

I think for now we should remove the validation check as it is handled later on. 

### Collector version

v0.62.0

## Environment
OS: Darwin
Compiler(if manually compiled): go 18.5

### OpenTelemetry Collector configuration

```yaml
profile: 'kschmitt'
    region: us-east-2
    logs:
      poll_interval: 10s
      groups:
        autodiscover: null
        named:
          /aws/eks/dev-eks-0/cluster:
            names: [kube-apiserver-audit-ea9c831555adca1815ae04b884b30566]
```

### Log output

```shell
2022-10-14 09:55:17.414048 I | collector server run finished with error: failed to get config: invalid configuration: receiver "awscloudwatch" has invalid configuration: both autodiscover and named configs are configured, Only one or the other is permitted
```

### Additional context

i will submit a PR for this shortly

### PR DESCRIPTION
**Pull request by schmikei**
**Description:** Since the default config obtains an `autodiscover` config, the real config loading runs into issues more often than expected. We should remove the constriction so exclusive named config users can use the receiver. 

**Link to tracking Issue:** Resolves #14952

**Testing:** Existing tests and this is now a valid config:

```yaml

receivers:
  awscloudwatch:
    region: us-east-2
    logs:
      poll_interval: 10s
      groups:
        named:
          /aws/eks/dev-eks-0/cluster:
            names: [kube-apiserver-audit-ea9c831555adca1815ae04b884b30566]

```

**Documentation:** Updated documentation to reflect this change.

### CODE REVIEW

**Comment by djaglowski** [comment]
> Since the default config obtains an autodiscover config, the real config loading runs into issues more often than expected. We should remove the constriction so exclusive named config users can use the receiver.

Am I understanding correctly that `autodiscover` is never nil, because it is the default? Therefore, is was impossible to use `named` groups because validation of the config checks that only one mode is used?

**Comment by djaglowski** [comment]
Ok, as proposed the config ends up in an ambiguous state where both `autodiscover` and `named` are set. 

The correct way to handle this is to implement a custom unmarshal function for the config. Basically, we can check if `autodiscover` was actually set, and if not, nil out the corresponding struct.

It should look pretty much like this (adapted from fileexporter):
```go
// Unmarshal a confmap.Conf into the config struct.
func (cfg *Config) Unmarshal(componentParser *confmap.Conf) error {
	if componentParser == nil {
		return errors.New("empty config for file exporter")
	}
	// first load the config normally
	err := componentParser.Unmarshal(cfg, confmap.WithErrorUnused())
	if err != nil {
		return err
	}
	// check if user actually specified autodiscover, or if just autoinitialized
	if !componentParser.IsSet("autodiscover") {
		cfg.Autodiscover = nil
	}
	return nil
}
```

**Comment by schmikei** [comment]
@djaglowski that seemed to be a great solution, added a couple more tests to validate that these changes are safe and resolve the issue

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
