### PR TITLE
[pkg/stanza/fileconsumer] Add trie and test cases

### PR DESCRIPTION
**Pull request by VihasMakwana**
Description: Add Trie data structure and keep it separate from PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23056

Testing: Relevant test cases added

### CODE REVIEW

**Comment by VihasMakwana** [comment]
@djaglowski I created this new PR. The previous one will be a mess if I revert in the same PR.

**Review by djaglowski — COMMENTED** [review]
The tests in this PR are substantially less thorough than those I contributed in https://github.com/VihasMakwana/opentelemetry-collector-contrib/pull/2.

Those cases were designed to give me confidence that the trie behaves as I expected. We've agreed to remove `Put`'s ability to update fingerprints, but this should only affect some specific assertions. All of those sequences should still be tested. Will you please restore the test cases and change only the assertions directly related to the `Put` function's update capability?

**Comment by VihasMakwana** [comment]
@djaglowski done, sorry bout that.

**Comment by VihasMakwana** [comment]
@djaglowski 
- **_TODO how do we know we need to call Put()?_**
    - If any match returns false, it would mean that it's a new file and we will call Put(). If it returns true, we would move to next files and skip this one as it will be a duplicate.

**Comment by djaglowski** [comment]
>   * If any match returns false, it would mean that it's a new file and we will call Put(). If it returns true, we would move to next files and skip this one as it will be a duplicate.

I agree.

I'm going through my test cases in enough detail that I'm just going to make another PR to update the assertions as I understand them now.

**Comment by VihasMakwana** [comment]
> > * If any match returns false, it would mean that it's a new file and we will call Put(). If it returns true, we would move to next files and skip this one as it will be a duplicate.
> 
> I agree.
> 
> I'm going through my test cases in enough detail that I'm just going to make another PR to update the assertions as I understand them now.

sounds fair, you'd wanna be sure that TRIE behaves as expected.

**Comment by VihasMakwana** [comment]
I can add you to my repo, you can commit directly if you want to?

**Comment by djaglowski** [comment]
That's ok. I'd prefer to do it through PR anyways 👍

**Comment by djaglowski** [comment]
I made the PR. Tests passed all my expectations now. I'll take another look tomorrow with fresh eyes but I think this may be good to go.

**Comment by djaglowski** [comment]
@VihasMakwana, my PR is [here](https://github.com/VihasMakwana/opentelemetry-collector-contrib/pull/4). It also includes some lint fixes.

**Comment by VihasMakwana** [comment]
@djaglowski I think we are good to go. I believe we can skip the changelog for this, as we did for my previous PR. I will include trie in threadpool PR's changelog. 
Let me know if you think otherwise.

**Comment by djaglowski** [comment]
I agree with skipping the changelog. Ultimately, this is an internal package and not in itself a user-facing concern. We'll add a changelog describing the user-facing behavior that it enables, when the rest of the solution is in place.

**Review by djaglowski — APPROVED** [review]
Thanks for persisting on this @VihasMakwana. I'm looking forward to seeing how well it supports the concurrent handling of files that we're aiming for.

**Pull request merged**
