### PR TITLE
Replace traceKey with traceID

### LINKED ISSUE #1541: Replace traceKey with traceID in processors that map spans
The tail-sampling and group-by-trace processors hold a map of spans grouped by trace ID. Previously, the trace ID was a simple [16]byte array, which made these processors use custom types or conversions as the map key. This is not necessary anymore, so, the code for those processors can be simplified.

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Description: replaced the map keys using custom types/strings for traceIDs to use pdata.TraceID instead.

Link to tracking Issue: Closes #1541

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please fix the lint errors

**Comment by bogdandrutu** [comment]
Just need a rebase after #1545 is merged

**Comment by jpkrohling** [comment]
Rebased.

**Comment by jpkrohling** [comment]
Green!

**Pull request merged**
