### PR TITLE
fix(pkg/stanza/input/file/reader): skip building fingerprint in case of configuration change

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

If customer changes fingerprint_size while offset is behind the value,
it is going to panic as it is unable to rebuild fingerprint

Reproduction:
logs/file.txt
```
this is some file for testing purposes

```

use this configuration
```
extensions:
  file_storage:
    directory: ./
    timeout: 10s
receivers:
  filelog:
    include:
      - logs/file.txt
    fingerprint_size: 16
    start_at: beginning
exporters:
  logging:
    logLevel: debug
service:
  extensions:
    file_storage
  pipelines:
    logs:
      receivers:
        - filelog
      exporters:
        - logging
```

run again with ioncreased fingerprint_size

```
extensions:
  file_storage:
    directory: ./
    timeout: 10s
receivers:
  filelog:
    include:
      - logs/file.txt
    fingerprint_size: 17
    start_at: beginning
exporters:
  logging:
    logLevel: debug
service:
  extensions:
    file_storage
  pipelines:
    logs:
      receivers:
        - filelog
      exporters:
        - logging
```

The error occures:

```
2022-06-01T17:19:54.955+0200    info    file/file.go:174        Started watching file   {"kind": "receiver", "name": "filelog", "operator_id": "file_input", "operator_type": "file_input", "path": "logs/file.txt"}
panic: runtime error: slice bounds out of range [:39] with capacity 18

goroutine 141 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*Reader).Read(0xc000aa8a20, {0xc000cee000, 0x27?, 0x4000})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.52.0/operator/input/file/reader.go:234 +0x190
bufio.(*Scanner).Scan(0xc000bc4f80)
        bufio/scan.go:215 +0x865
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*Reader).ReadToEnd(0xc000aa8a20, {0x53ba918, 0xc000c68680})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.52.0/operator/input/file/reader.go:134 +0x216
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*InputOperator).poll.func1(0xc00043cf90?)
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.52.0/operator/input/file/file.go:155 +0x5c
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*InputOperator).poll
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.52.0/operator/input/file/file.go:153 +0x198
```

**Link to tracking Issue:** N/A

**Testing:** ToDo

**Documentation:** in code comments

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
This is draft as I want to add some unit tests to the PR

**Comment by sumo-drosiek** [comment]
Not sure, how this change affects this code:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/90efffd0a7ee403579e5b196713c4ca73e3ebafe/pkg/stanza/operator/input/file/fingerprint.go#L59-L75

There shouldn't be an issue for increasing the fingerprint size. I will test it for decreasing the fingerprint size, but I consider PR ready to review

**Comment by sumo-drosiek** [comment]
for decreasing the `fingerprint_size`, file is going to be read again, which is not a new behavior and I would rather resolve it in separate issue

@djaglowski WDYT?

**Comment by djaglowski** [comment]
Am I correct in thinking that this only affects fingerprints that have been loaded from a storage extension? If so, I wonder if we could detect this and normalize the fingerprints during startup. This would seem to be preferable to adding complexity to the ongoing read loop.

**Comment by sumo-drosiek** [comment]
> Am I correct in thinking that this only affects fingerprints that have been loaded from a storage extension?

Yes, it affects only fingerprints which have been loaded from storage

> If so, I wonder if we could detect this and normalize the fingerprints during startup.
So, as I understand flow correctly, you propose to add logic to this function: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c522cef4ae42262ac8f7e5922d0729f615b3da07/pkg/stanza/operator/input/file/file.go#L324-L361

**Comment by sumo-drosiek** [comment]
> Only thing I would ask is that new test cases be added rather than adding to the existing "GrowAndStop" test.

Sure, I was considering that, but it will be mostly copy of the `GrowAndStop`

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
