### PR TITLE
Refresh expired credentials in awsprometheusremotewrite

### LINKED ISSUE #7955: awsprometheusremotewrite sign request with expired credentials
**Describe the bug**
When credentials are managed by an external process (i.e. using env AWS_SHARED_CREDENTIALS_FILE), RoundTripper implementation for AWS Prometheus Remote Write is using expired credentials to sign the Sigv4 request, producing a constant server response of 403 and dropping packages until the collector is restarted and credential file is read again.

**Steps to reproduce**
- Create a valid Credential file with temporary credentials (STS). For this explanation let's assume the credentials expires in 1h.
- Define the environment variable AWS_SHARED_CREDENTIALS_FILE and point it to the path of the credential file.
- Configure the exporter (awsprometheusremotewrite) and start the collector process (the user running the process must have read permissions over the shared credential file).
- Wait until the credentials expires
- 403 errors will start appearing in the logs after the credential is expired. 

`error":"Permanent error: remote write returned HTTP status 403 Forbidden; err = <nil>: {\"message\":\"The security token included in the request is expired\"}`

- Generate a new set of temporary credentials and overwrite the shared credential file. This simulates the external process updating the credentials.
- Wait until the next trip, the error won't change.
- Restart the collector, new credentials are read and metrics pushed as expected.

**What did you expect to see?**
When the credential used to sign the request is expired, I expected the module to re-read the credentials from the chain looking for a set of fresh credentials to use in the signing process and no drop of packages.

**What did you see instead?**
Credential chain is not refreshed when credentials expires.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: "Ubuntu 20.04.3 LTS" and "MacOSX (Monterrey)" 
Compiler(if manually compiled): v0.44.0

**Additional context**

@alolita

### PR DESCRIPTION
**Pull request by rafaelpereyra**
**Description:** 

Added logic to validate if the current credentials are expired and force a refresh of them before signing the request to avoid dropping packages

Two cases are considered:

- role_arn is specified in the exporter configuration: In this case, the credential is aware of the expiration date and the logic can be applied.
- role_arn is **not** specified, then usually the credentials are considered long term (expiration date = time.Time{}) and the check cannot be performed. We can only infer the credentials are invalid based on the response from the server (403), and then refresh the credentials before failing the Roundtrip. If the file was properly updated, the next trip will be successful but packet loss will occur. A deeper change in the logic can be added to retry the package but the recommended approach in this case would be to pass a role_arn in the configuration.

**Link to tracking Issue:** Fix #7955

**Testing:** Both conditions were tested for over 1h and there was no errors in the transmission when `role_arn` was specified and a temporary packet loss when not specified as expected.

**Documentation:** N/A

### CODE REVIEW

**Comment by rafaelpereyra** [comment]
cc @alolita

**Review by codeboten — COMMENTED** [review]
Thanks for the contribution @rafaelpereyra, please sign the CLA

**Comment by rafaelpereyra** [comment]
> Thanks for the contribution @rafaelpereyra, please sign the CLA

I did signed it (twice). Not sure how to update the PR or if I need to create a new PR.

**Comment by Aneurysm9** [comment]
Thank you for the contribution.  I think I agree with your assessment on handling the 403 response.  We can always add retries later if it seems necessary.  Can you please add some unit tests for this new functionality?

@erichsueh3 please ensure this gets included in the sigv4 auth extension PR.

**Comment by rafaelpereyra** [comment]
> @rafaelpereyra Thank you for the contribution. I think I agree with your assessment on handling the 403 response. We can always add retries later if it seems necessary. Can you please add some unit tests for this new functionality?
> 

Unsure how to mock the expired credentials case. `StaticProvider` will always return `false` for `IsExpired` so I'll need to do some research. 

Any pointers or ideas are more than welcome :)

**Review by anuraaga — COMMENTED** [review]
I think this deserves a deeper dive before trying this change. Handling 403 to manage refresh in a caller like this is not the intention of the aws sdk I believe.

The code seems to indicate creds are automatically refreshed if expired for each call to sign

https://github.com/aws/aws-sdk-go/blob/9429e7516ba9e1a2d463f960ae7c0f46facaf2ff/aws/signer/v4/v4.go#L344
https://github.com/aws/aws-sdk-go/blob/9429e7516ba9e1a2d463f960ae7c0f46facaf2ff/aws/credentials/credentials.go#L237

I'd like to understand first why this isn't working as advertised if it's possible. Could it be a bug in the aws sdk v1?

**Comment by rafaelpereyra** [comment]
My initial impression was that this could be a bug in the sdk too. However upon reading the code, the sdk is behaving as expected when shared credentials is the provider. This credentials will not expire once [retrieved](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/credentials/shared_credentials_provider.go#L72)

This would explain why the Sign function doesn't refresh the credentials in when calling getCredentials [here](https://github.com/aws/aws-sdk-go/blob/9429e7516ba9e1a2d463f960ae7c0f46facaf2ff/aws/signer/v4/v4.go#L344) 
and therefore we only get the error when sending the request to the server and returns 403. This also explains why I can't refresh such credentials before sending the event (is not expired and will return the same credentials in memory without reading the credential chain).

When the role_arn is specified in the prometheus exporter configuration however, the provider is different now and is aware of the [expiration](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/credentials/stscreds/assume_role_provider.go#L128) (15 min default)


One thing I can do to minimize the impact on the current module, is move the validation of the expiration date inside the if clause. This will minimize the risk of having issues when role_arn is not specified in the configuration (new code won't be executed at all)

```
	if len(si.roleArn) != 0 {
		expiration, err := si.signer.Credentials.ExpiresAt()
		if err != nil {
			expiration = time.Time{} // Avoid errors in the the if condition
		}
			
		if expiration.IsZero() && si.signer.Credentials.IsExpired() {
			// Under an assumed role, Credential expiration will be known so we update the credentials before requesting the Signature
			// and avoid dropping data.
			auth := AuthConfig{
				Region:  si.region,
				Service: si.service,
				RoleArn: si.roleArn,
			}
			si.signer.Credentials, err = getCredsFromConfig(auth)
			if err != nil {
				return nil, fmt.Errorf("error refreshing credentials: %v", err)
			}
		}
	}	

```

I can remove the 403 check, however if the remote endpoint returns 403 the packages are already lost so I see no harm attempting to recover the new credentials.

**Comment by AustinWentz** [comment]
Hi, we are facing a similar issue when exporting with X-Ray. Temporary credentials are expired and refreshed, but they are not picked up by the collector. Any updates on this PR?

**Comment by mhausenblas** [comment]
Note that `awsprometheusremotewriteexporter` [will be removed](https://github.com/aws-observability/aws-otel-collector/tree/main#adot-collector-built-in-components) and replaced by `prometheusremotewrite` along with the [sigv4 auth extension](https://github.com/open-o11y/opentelemetry-collector-contrib/tree/main/extension/sigv4authextension). The PR at hand was one of the [inputs](https://github.com/open-o11y/opentelemetry-collector-contrib/pull/1302#discussion_r809704008) we used.

Going forward, we (AWS) are in the process of putting together supporting material for migrating to the new setup and also include it in the upcoming ADOT collector release.

**Comment by AustinWentz** [comment]
Thanks for following up on this! Our team is happy to hear.

**Comment by rafaelpereyra** [comment]
Awesome @mhausenblas thanks!

**Pull request closed without merging**
