### PR TITLE
Fix(CI): 'update-otel' make target fails with 'go-chi' dependency issue

### LINKED ISSUE #8837: [CI]  'update-otel' make target fails with 'go-chi' dependency issue
**Describe the bug**
[opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) has a dependency on `gopkg.in/DataDog/dd-trace-go.v1 v1.37.0`. `gopkg.in/DataDog/dd-trace-go.v1 v1.37.0` has a dependency on `github.com/go-chi/chi v4.0.0-rc1`. However, the tag has been removed from the repository for `v4.0.0-rc1`.

This means then that the `update-otel` target fails as follows:

```console
$ make update-otel

/Library/Developer/CommandLineTools/usr/bin/make update-dep MODULE=go.opentelemetry.io/collector VERSION=main
/Library/Developer/CommandLineTools/usr/bin/make for-all-target TARGET="updatedep"
/Library/Developer/CommandLineTools/usr/bin/make -C ./cmd/configschema updatedep
/Users/mhickey/go/src/github.com/open-telemetry/opentelemetry-collector-contrib/internal/buildscripts/update-dep
go: gopkg.in/DataDog/dd-trace-go.v1@v1.37.0 requires
	github.com/go-chi/chi/v4@v4.0.0-rc1: reading github.com/go-chi/chi/go.mod at revision v4.0.0-rc1: unknown revision v4.0.0-rc1
make[3]: *** [updatedep] Error 1
make[2]: *** [for-all-target-./cmd/configschema] Error 2
make[1]: *** [update-dep] Error 2
make: *** [update-otel] Error 2
```

**Steps to reproduce**
Run `make update-otel`

**What did you expect to see?**
The target runs and updates are performed as appropriately.

**What did you see instead?**
The error message shown above.

**What version did you use?**
Version: main

**What config did you use?**
Config: NA

**Environment**
OS: darwin/amd64
Compiler(if manually compiled): 1.17.2

**Additional context**
see https://github.com/go-chi/chi/issues/713 and https://github.com/DataDog/dd-trace-go/issues/1220 for more details about the dependency issue.

### PR DESCRIPTION
**Pull request by hickeyma**
This PR replaces the chi dependency with `v4.0.0` until the issue is resolved with the `dd-trace-go` module.

Fixes #8837 

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>

### CODE REVIEW

**Comment by hickeyma** [comment]
Don't think a changeling is required.

**Comment by hickeyma** [comment]
Getting fails on `loadtest/TestMetricsFromFile` and `unittest`. The errors are as follows..


`unittest`:

```console
=== RUN   TestEndToEnd
[17684](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17684)
    receiver_test.go:118: 
[17685](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17685)
        	Error Trace:	receiver_test.go:118
[17686](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17686)
        	            				receiver_test.go:100
[17687](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17687)
        	            				receiver_test.go:72
[17688](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17688)
        	Error:      	Should be true
[17689](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17689)
        	Test:       	TestEndToEnd
[17690](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689034341?check_suite_focus=true#step:8:17690)
        	Messages:   	timestamp_now metric not found
```

`loadtest/TestMetricsFromFile` 

```console
--- FAIL: TestMetricsFromFile (3.16s)
[294](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:294)
FAIL
[295](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:295)
exit status 1
[296](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:296)
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/tests	80.561s
[297](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:297)
# Test PerformanceResults
[298](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:298)
Started: Fri, 25 Mar 2022 08:39:24 +0000
[299](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:299)

[300](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:300)
Test                                    |Result|Duration|CPU Avg%|CPU Max%|RAM Avg MiB|RAM Max MiB|Sent Items|Received Items|
[301](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:301)
----------------------------------------|------|-------:|-------:|-------:|----------:|----------:|---------:|-------------:|
[302](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:302)
Metric10kDPS/Carbon                     |PASS  |     16s|    93.5|   111.3|         63|         90|    443100|        443100|
[303](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:303)
Metric10kDPS/OpenCensus                 |PASS  |     15s|    30.7|    31.3|         67|         94|   1049300|       1049300|
[304](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:304)
Metric10kDPS/OTLP                       |PASS  |     15s|    36.3|    36.7|         68|         96|   1049300|       1049300|
[305](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:305)
Metric10kDPS/OTLP-HTTP                  |PASS  |     15s|    38.8|    39.7|         64|         90|   1050000|       1050000|
[306](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:306)
Metric10kDPS/SignalFx                   |PASS  |     15s|    54.8|    55.0|         70|         95|   1049300|       1049300|
[307](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5689071865?check_suite_focus=true#step:14:307)
MetricsFromFile                         |FAIL  |      3s|    33.0|    33.0|         31|         95|      3074|          2914|RAM consumption is 95 MiB, max expected is 94 MiB
```

Not really sure what is causing this. I would appreciate any feedback.

Also, am getting 'timeout' issues when trying to run the test locally.

**Comment by hickeyma** [comment]
Update => Test passing locally.

**Comment by mx-psi** [comment]
Meant to write a comment but forgot to do it 😅 I don't think the test failures are related to the changes on this PR, you can ignore them (and/or raise an issue so that they get fixed). I requested a review from @Aneurysm9 since he also faces the `go-chi` issue and can verify that this solves it for him.

**Comment by hickeyma** [comment]
Thanks @mx-psi. Seems to be some flakiness going on. Tests are passing now! :)

**Review by Aneurysm9 — APPROVED** [review]

**Comment by Aneurysm9** [comment]
This is the same workaround we applied in the [AWS distro](https://github.com/aws-observability/aws-otel-collector/blob/main/go.mod#L310).  Can confirm it was working there.

Please ensure you've merged `origin/main` recently as it seems that this branch has out-of-date test workflow definitions.

**Comment by hickeyma** [comment]
Thanks for review and feedback @Aneurysm9.

> Please ensure you've merged origin/main recently as it seems that this branch has out-of-date test workflow definitions.

Rebased.

**Comment by hickeyma** [comment]
@mx-psi Looks like the load tests that are failing are flakes.

**Review by mx-psi — APPROVED** [review]

**Comment by hickeyma** [comment]
Rebased there again. If this is good to go, does someone mind merging this? It's just that there will potentially lots of changes around the Go module dependencies.

**Comment by mx-psi** [comment]
> Rebased there again. If this is good to go, does someone mind merging this? It's just that there will potentially be lots of changes around the Go module dependencies.

I marked as ready to merge, a maintainer will give a final look and should merge it soon :)

**Review by codeboten — APPROVED** [review]

**Comment by hickeyma** [comment]
Thanks for the reviews folks and the merge.

**Pull request merged**
