### PR TITLE
Add setStatus operation for spanprocessor

### PR DESCRIPTION
**Pull request by TomRoSystems**
**Description:** Added possibility to change span status and description.

**Link to tracking Issue:** #4754 

**Testing:**  Added two unit tests in span_test.go

**Documentation:** Updated README inside spanprocessor and added two examples with comments in `config.yaml`

### CODE REVIEW

**Review by mx-psi — CHANGES_REQUESTED** [review]

**Review by mx-psi — COMMENTED** [review]
Looking good, just one more thing to fix from my side

**Review by mx-psi — APPROVED** [review]

**Review by johnbley — APPROVED** [review]
LGTM

**Review by dmitryax — APPROVED** [review]

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
Sorry, we need to finalize the transform processor configs before adding new functionality

**Comment by iNikem** [comment]
@bogdandrutu Are there any delivery estimates for that pre-requirement?

**Comment by TomRoSystems** [comment]
> Sorry, we need to finalize the transform processor configs before adding new functionality

Hi @bogdandrutu 

Could you please link corresponding issue that should be done first?

**Comment by bogdandrutu** [comment]
Here is the design doc https://github.com/open-telemetry/opentelemetry-collector/pull/4444

**Comment by iNikem** [comment]
One more use-case for this PR is if somebody is unhappy with https://github.com/open-telemetry/opentelemetry-specification/pull/1998, then using this new processor they can set status back to error

**Comment by bogdandrutu** [comment]
Because of the recent spec change we need this functionality before the stable transform processor is designed.

**Review by bogdandrutu — APPROVED** [review]
Because of the recent spec change we need this functionality before the stable transform processor is designed.

@TomRoSystems @iNikem fyi this functionality will be deprecated soon (and replace by the transform processor), so consider to not use it unless critical.

**Comment by iNikem** [comment]
> Because of the recent spec change we need this functionality before the stable transform processor is designed.
> 
> @TomRoSystems @iNikem fyi this functionality will be deprecated soon (and replace by the transform processor), so consider to not use it unless critical.

@bogdandrutu is there some description/issue/anything about this "transform processor"?

**Comment by ivomagi** [comment]
+1, can we get some transparency to expected transform processor design and the any estimates on release date / deprecation date? There are several asks for the possibility to get the possibility for overriding the span status set by instrumentations and looking for guidance how to enable such use cases while taking the upgrade path into account @bogdandrutu

**Comment by mx-psi** [comment]
@iNikem @ivomagi IIUC this is the design doc for that processor https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5886#issuecomment-973114178

**Pull request merged**
