### PR TITLE
prometheusreceiver: Add trim_metric_suffixes configuration option

### PR DESCRIPTION
**Pull request by dashpole**
**Description:**

Adds a new configuration option: `trim_metric_suffixes` to the prometheus receiver.  When set to true, suffixes will be trimmed from metrics.  This replaces use of the`pkg.translator.prometheus.NormalizeName` feature-gate in the prometheus receiver, but leaves it for exporters.

The first commit simplifies the usage of the feature-gate. The tests and implementation were passing around an entire registry when it wasn't necessary.

**Link to tracking Issue:**

Part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21743
Part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8950

**Testing:**

Unit tests.

**Documentation:**

Added to the README.

cc @gouthamve @dmitryax

### CODE REVIEW

**Comment by dmitryax** [comment]
Why do we need `pkg.translator.prometheus.NormalizeName` feature gate if it is controlled by config options now? Maybe we should just deprecate it as the first step? Keeping `add_type_and_unit_suffixes` disabled for some time on the exporter side would be the same as keeping `pkg.translator.prometheus.NormalizeName` in alpha the state, but it maybe it's even unnecessary...

**Comment by dashpole** [comment]
The feature gate is useful if we still consider the feature alpha.  Do you think we need to resolve https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23208 before graduating it to beta?

If everyone agrees it is beta, we can remove it as part of adding the config options.

**Comment by dmitryax** [comment]
> Do you think we need to resolve https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23208 before graduating it to beta?

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23208 is only about the receiver. Given that the option `trim_metric_suffixes` is off by default, it won't affect users unless they explicitly enable it. I think we can just mark the config option as experimental and subject to change until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23208 is resolved

**Comment by dashpole** [comment]
That works for me. I'll update this to remove the feature gate from the receiver path.

**Comment by dashpole** [comment]
@dmitryax done

**Review by dmitryax — APPROVED** [review]

**Comment by dashpole** [comment]
Fixed `make tidy`

**Review by gouthamve — APPROVED** [review]
LGTM

**Pull request merged**
