### PR TITLE
[receiver/solacereceiver]: Updates to Solace Receiver to use latest semantic conventions - v1.25.0

### PR DESCRIPTION
**Pull request by oodigie**
**Description:** Updated the relevant attribute keys to match the latest semantic conventions (v1.25.0).

**Link to tracking Issue:** N/A

**Testing:** Updated unit tests to accommodate renamed attribute keys

**Documentation:** N/A

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Thanks @oodigie, please sign the CLA

@mcardy please review as code owner

**Review by mcardy — APPROVED** [review]

**Comment by oodigie** [comment]
Thanks for the review @mcardy. 
@codeboten, I have signed the CLA but waiting on our internal CLA Manager to approve. They are having some issues with the dashboard and not seeing my signed request(s) so I have opened a Jira bug for this. Hopefully, this will be resolved and we will have the signed CLA approved soon.

**Comment by codeboten** [comment]
Thanks for the update @oodigie, sometimes `/easycla` helps, didn't see to in this case.

**Comment by oodigie** [comment]
@codeboten, the signed CLA has been approved.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
