### PR TITLE
[receiver/googlepubsub] Add Google Cloud Logging encoding

### PR DESCRIPTION
**Pull request by alexvanboxel**
**Description:** 
This commit addresses the need to accept logs from Google Cloud Platform
into an OpenTelemetry pipeline. The goal is to introduce the
`cloud_logging` encoding option for the receiver, allowing users to
seamlessly integrate Cloud Logging logs into their OpenTelemetry
pipeline.

**Link to tracking Issue:**
#23184

**Testing:**
Added tests for parsing LogEntries

**Documentation:**
Added the option to the README.md

### CODE REVIEW

**Comment by weyert** [comment]
I would be interested in this functionality too. Anyway I could assist?

**Comment by alexvanboxel** [comment]
> I would be interested in this functionality too. Any way I could assist?

The PR is ready implementation-wise, but let's see if we agree on the spec first see: https://github.com/open-telemetry/opentelemetry-specification/pull/3775 and https://github.com/open-telemetry/opentelemetry-specification/issues/3774

**Comment by alexvanboxel** [comment]
I'm the receiver's CODEOWNER. Note for reviewers: this is mainly an implementation by @kamalmarhubi; I've changed some conversions to match the `semconv` as much as possible. I had hoped first to add it to the spec, but I will do it the other way around: commit the receiver, then add a note in the spec on compatibility.

**Comment by alexvanboxel** [comment]
@atoulme, I've rebased (so as not to conflict with the new trace/metric imports). Could you give the PR a ready-to-merge? The `go.mod` file is hard to keep up to date as it contains extra imports.

**Comment by weyert** [comment]
Lovely! Exciting to try this out to forward Cloud Logging logs via Dataflow to otel-collector :)

**Comment by alexvanboxel** [comment]
> Lovely! Exciting to try this out to forward Cloud Logging logs via Dataflow to otel-collector :)

I'll try to fix the merge conflict by next Collector SIG meeting, because it's hard to get momentum on this. BTW, you don't need Dataflow for this, just Log routing.

**Comment by weyert** [comment]
Any news on this PR?

**Comment by alexvanboxel** [comment]
> Any news on this PR?

Live is hard as a CODEOWNER without "merge" power. @atoulme or @dashpole can someone with the power merge this?

**Comment by atoulme** [comment]
I also cannot merge anything. @open-telemetry/collector-contrib-maintainer can.

**Comment by alexvanboxel** [comment]
> I also cannot merge anything. @open-telemetry/collector-contrib-maintainer can.

Maybe you can accept the code review; the ready-for-merge label doesn't appear because I've pushed this?

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
