### PR TITLE
Improve error reporting in the Honeycomb exporter.

### PR DESCRIPTION
**Pull request by paulosman**
The honeycomb exporter uses the Honeycomb GO SDK ([libhoney-go](https://github.com/honeycombio/libhoney-go)) under the hood. The SDK collects HTTP responses in a separate queue that can be consumed by reading a channel. This change adds response queue reporting to the honeycomb exporter.

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]

**Comment by paulosman** [comment]
Thanks for the :+1: @tigrannajaryan . Do you want me to bump the testbed limits for those metrics tests, or is someone else planning to do that in a separate PR?

**Comment by tigrannajaryan** [comment]
Let me rerun and see if we are consistently failing or it is a result of unstable machine performance.

**Comment by tigrannajaryan** [comment]
I bumped some resource limits on perf tests. Please rebase, let's see if they pass now.

**Comment by paulosman** [comment]
> I bumped some resource limits on perf tests. Please rebase, let's see if they pass now.

Unfortunately not. Not sure if it's related, but I'm seeing some errors in the loadtest output:

```
2020/05/13 13:41:08 Cannot send metrics: Post "http://localhost:38927/v2/datapoint": EOF
2020/05/13 13:41:08 Cannot send metrics: Post "http://localhost:38927/v2/datapoint": dial tcp 127.0.0.1:38927: connect: connection refused
```

**Comment by tigrannajaryan** [comment]
> Unfortunately not. Not sure if it's related, but I'm seeing some errors in the loadtest output:
> 
> ```
> 2020/05/13 13:41:08 Cannot send metrics: Post "http://localhost:38927/v2/datapoint": EOF
> 2020/05/13 13:41:08 Cannot send metrics: Post "http://localhost:38927/v2/datapoint": dial tcp 127.0.0.1:38927: connect: connection refused
> ```

These are just post effects of terminating the Collector after resource limits are exceeded. The root cause is resource usage. Unclear why this builds of this PR insist on using more than other PRs. CircleCI slowdowns do happen but this PRs seems to be hitting it consistently. Let me rerun again and see what happens.

A stable perf test environment seems to become higher priority.

**Comment by paulosman** [comment]
> These are just post effects of terminating the Collector after resource limits are exceeded. The root cause is resource usage. Unclear why this builds of this PR insist on using more than other PRs. CircleCI slowdowns do happen but this PRs seems to be hitting it consistently. Let me rerun again and see what happens.
> 
> A stable perf test environment seems to become higher priority.

Cool. Yeah, in the meantime I can try and do some profiling to see if there's a reason this branch would be consuming more CPU and Memory. It seems odd since it's just reading from a channel and logging, but I can look closer.

**Comment by paulosman** [comment]
> These are just post effects of terminating the Collector after resource limits are exceeded. The root cause is resource usage. Unclear why this builds of this PR insist on using more than other PRs. CircleCI slowdowns do happen but this PRs seems to be hitting it consistently. Let me rerun again and see what happens.
> 
> A stable perf test environment seems to become higher priority.

Okay, confirmed it's not the code but one of the dependencies that came along. I'll keep digging, it'll be important to find out what's causing it because the difference is real (running tests locally on this branch vs master results in much higher CPU usage on this branch).

**Comment by tigrannajaryan** [comment]
Weird that this keeps failing while other PRs pass. Can this be an actual regression due to updated dependencies?

**Comment by tigrannajaryan** [comment]
> 
> Okay, confirmed it's not the code but one of the dependencies that came along. I'll keep digging, it'll be important to find out what's causing it because the difference is real (running tests locally on this branch vs master results in much higher CPU usage on this branch).

OK, just saw your comment after I submitted mine :-)

**Comment by paulosman** [comment]
> OK, just saw your comment after I submitted mine :-)

Jinx :-) Yup, I'm going to go through the new dependencies one-by-one. It's annoying, but probably something that would bite us down the road anyway. I'll update this branch once I've finished doing the bisect locally.

**Comment by paulosman** [comment]
FYI @tigrannajaryan. It seems like [upgrading golang/protobuf from 1.3.5 to 1.4.1](https://github.com/honeycombio/opentelemetry-exporter-go/commit/5d0ff7327b68f05500237459d67e9adc55373a53#diff-37aff102a57d3d7b797f152915a6dc16L7) is at least part of the problem. Running tests locally, I'm seeing a ~ 30% spike in CPU usage on the OpenCensus metrics test when that's the only change.

I'm going to unwind the dependency on our Go SDK exporter in a future PR, but for now, pinning to a commit before the v0.4.3 tag gets the testbed tests passing.

**Comment by bogdandrutu** [comment]
Please rebase.

**Comment by paulosman** [comment]
Closing - functionality included in GH-248

**Pull request closed without merging**
