### PR TITLE
[exporter/loki]. Rename resources to resource field in JSON format

### PR DESCRIPTION
**Pull request by mar4uk**
**Description:** <Describe what has changed.>
Lokiexporter sends `resources` field to Loki in JSON format. This name is not following the opentelemetry log data model specification: https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-resource
The field name should be `resource`

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21161

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
Does this affect the lokireceiver in any way?

**Comment by mar4uk** [comment]
> Does this affect the lokireceiver in any way?

No, it doesn't affect lokireceiver

**Comment by mar4uk** [comment]
please don't merge, this change needs more consideration

**Comment by mar4uk** [comment]
PR is ready for review

**Comment by mar4uk** [comment]
@kovrus @jpkrohling could you please take a look?

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
@mar4uk, sorry I missed this one. If this is still relevant, please rebase and I'll merge, as it looks good to me.

**Comment by mar4uk** [comment]
Let's keep `resources` as it is. It doesn't look like an urgent issue. It is a more cosmetic improvement

**Pull request closed without merging**
