### PR TITLE
Change the way that X-Ray exporter annotation converter work

### PR DESCRIPTION
**Pull request by XinRanZhAWS**
Description:
In the past, X-Ray doesn’t support “.”. So we have a translator in x-ray export to translates it to “_” before sending traces to X-Ray Service.

To match otel naming style, x-ray service team decide to change their service to support both "." type and "" type of naming. In this case the translator that translate "." to "" is no-longer needed. This PR change the way this translator work

X-Ray PMs agree on rolling out this change by using feature-gate

Testing:
Unit test

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please add a changelog

**Comment by XinRanZhAWS** [comment]
> Please add a changelog

Added, thanks

**Review by songy23 — APPROVED** [review]

**Comment by XinRanZhAWS** [comment]
@songy23 Hi Yang, thanks for you time :) Can you please help me to trigger the test run again? I found some lint issue and fixed :(

**Review by mxiamxia — APPROVED** [review]

**Review by srprash — APPROVED** [review]

**Comment by XinRanZhAWS** [comment]
@atoulme @songy23 Hi Team, I taken a look at the test result and I believe it's fine. The only issue on the test is not related to my code (it's seems not even a issue, just an accidental terminate on the run). If you think the test is enough, can you help us merge the code? If not, can you try to rerun the test again? Thanks

**Pull request merged**
