### PR TITLE
[exporter/datadog] Add `metrics::summaries::mode` setting; deprecate `metrics::report_quantiles`

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

- Add new `metrics::summaries::mode` setting.
- Deprecate `metrics::report_quantiles` in favor of `metrics::summaries::mode`.

**Link to tracking Issue:** #8845

**Testing:** Add unit tests for invalid mode; test manually. The existing unit tests for `cumulative_monotonic_mode` are enough to check the deprecation system

**Documentation:** Updated the docs to reflect the new option

### CODE REVIEW

**Comment by jpkrohling** [comment]
Interesting, the conflict I have when checking out this PR is different: 

```
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
	both modified:   exporter/datadogexporter/factory_test.go
```

Right now, GitHub tells me the conflict is at the changelog. @mx-psi, could you please take a look?

**Comment by mx-psi** [comment]
> Interesting, the conflict I have when checking out this PR is different:
> 
> ```
> Unmerged paths:
>   (use "git restore --staged <file>..." to unstage)
>   (use "git add <file>..." to mark resolution)
> 	both modified:   exporter/datadogexporter/factory_test.go
> ```
> 
> Right now, GitHub tells me the conflict is at the changelog. @mx-psi, could you please take a look?

I fixed that on 0817d8789058d0b6e7dcd0b2ef2d0e3938baa4a6, I think. Anyway, all conflicts fixed now!

**Review by KSerrania — APPROVED** [review]
LGTM

**Comment by mx-psi** [comment]
@jpkrohling if everything looks good, could this be merged?

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
