### PR TITLE
Rename service.AppSettings to service.CollectorSettings to reflect core change

### PR DESCRIPTION
**Pull request by eddyleelin**
**Description:** 
Renamed calls to API that will change from service.AppSettings to service.CollectorSettings in the core repo. To be merged with [PR 3268](https://github.com/open-telemetry/opentelemetry-collector/pull/3268) on opentelemetry-collector.

**Link to tracking Issue:** 
Addresses [#3175](https://github.com/open-telemetry/opentelemetry-collector/issues/3175)

**Testing:**
Local `make` with `make otel-from-tree` using the corresponding changes in core PR 3268 returns a clean report.

**Documentation:**
- [ ] Merge PR 3268 in the core repo.
- [ ] Add to the contrib change log if necessary.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
```
cmd/otelcontribcol/main.go:47:36: CollectorSettings not declared by package service (typecheck)
func runInteractive(params service.CollectorSettings) error {
                                   ^
cmd/otelcontribcol/main_others.go:21:25: CollectorSettings not declared by package service (typecheck)
func run(params service.CollectorSettings) error {
                        ^
cmd/otelcontribcol/main.go:42:24: CollectorSettings not declared by package service (typecheck)
	if err := run(service.CollectorSettings{BuildInfo: info, Factories: factories}); err != nil {
	                      ^
make[1]: *** [Makefile.Common:93: lint] Error 1
make[1]: Leaving directory '/home/circleci/project'
make: *** [Makefile:149: for-all-target-/home/circleci/project] Error 2
```

**Comment by eddyleelin** [comment]
Thanks for the note @tigrannajaryan; this error will be fixed when [PR 3268](https://github.com/open-telemetry/opentelemetry-collector/pull/3268) is merged!

**Comment by alolita** [comment]
Will wait for #3268 to be re-reviewed and merged.

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3268 is now merged.

**Comment by bogdandrutu** [comment]
@eddyleelin please rebase and run `make update-otel` so you get the latest version of the collector.

**Comment by eddyleelin** [comment]
Thanks, I have updated the branch. Tests look good!

**Review by tigrannajaryan — COMMENTED** [review]
I only see *.mod and *.sum files modified. Any *.go files supposed to be modified?

**Comment by tigrannajaryan** [comment]
The build fails, unclear what the problem is. Please rebase from main.

**Comment by alolita** [comment]
@eddyleelin please fix the tests (setup, integration tests) that are failing.

Workflow: build-publish

    setup - Failed
    cross-compile - Blocked
    windows-msi - Blocked
    unit-tests - Blocked
    lint - Blocked
    rpm-package - Blocked
    loadtest - Blocked
    deb-package - Blocked
    build-examples - Blocked
    windows-test - Success
    integration-tests - Failed
    publish-check-2 - Blocked

**Comment by bogdandrutu** [comment]
This is done.

**Pull request closed without merging**
