### PR TITLE
[receiver/prometheusexec] Remove keitwb as codeowner

### PR DESCRIPTION
**Pull request by jpkrohling**
Requested here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6911#issuecomment-1004867993

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by codeboten — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Should @keitwb be removed from other components as well? 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/73d8da64fba8cbfd2ac9dfbd04a390e5c86f36d3/.github/CODEOWNERS#L129-L130

**Comment by jpkrohling** [comment]
cc @keitwb

**Comment by bogdandrutu** [comment]
@jpkrohling please replace this with @dmitryax , per @emaderer recommendation :D

**Comment by jpkrohling** [comment]
@dmitryax, looks like @keitwb wants to be removed from both the Prometheus exec and from statsd receivers. Would you want to become code owner for both, or only for the Prometheus one?

**Comment by dmitryax** [comment]
@jpkrohling I can take ownership of both

**Comment by jpkrohling** [comment]
PR updated

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
