### PR TITLE
[connector/spanmetrics] CHANGELOG is fixed to reflect the correct fea…

### LINKED ISSUE #35766: Release notes of 0.109.0 has incorrect feature gate for spanmetrics
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

The v0.109.0 release notes on page https://github.com/open-telemetry/opentelemetry-collector-contrib/releases talks about:

> The feature flag connector.spanmetrics.legacyLatencyMetricNames

**Steps to reproduce**

1. Dockerfile with Otelcollector built together with spanmetrics. Final line of Dockerfile:
`CMD ["/otelcol-custom", "--config=/etc/otel-collector-config.yml", "--feature-gates=connector.spanmetrics.legacyLatencyMetricNames" ]`

2. Build docker image
3. Run docker image

**Expected result**
Running instance of the otelcollector

**Actual result**
`Error: invalid argument "connector.spanmetrics.legacyLatencyMetricNames" for "--feature-gates" flag: no such feature gate "connector.spanmetrics.legacyLatencyMetricNames". valid gates: [component.UseLocalHostAsDefaultHost connector.spanmetrics.legacyMetricNames processor.tailsamplingprocessor.metricstatcountspanssampled service.noopTracerProvider telemetry.disableHighCardinalityMetrics telemetry.useOtelWithSDKConfigurationForInternalTelemetry]
`

*Proposed change*
Since the software is already released with the feature gate **connector.spanmetrics.legacyMetricNames**, I propose to change the Release notes of v0.109.0 to mention the correct feature gate.

### PR DESCRIPTION
**Pull request by tbeemster**
#### Description
The wrong feature gate was exposed in the CHANGELOG, this has been corrected to the correct feature gate 'connector.spanmetrics.legacyMetricNames'

#### Link to tracking issue
Fixes #35766 

#### Documentation
CHANGELOG.md is updated to have the correct feature gate name.

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
PR looks good, please sign the CLA @tbeemster

**Comment by tbeemster** [comment]
I've just signed the CLA and rebased

**Comment by songy23** [comment]
Looks like your commit has 2 authors @timbeemster @tbeemster and both need to sign CLA 

or you can create a new PR with commit only from @tbeemster

**Comment by tbeemster** [comment]
Hi @songy23 , sorry for the late response.
I've accidentally committed with 2 authors. I've removed the one that did not have the CLA signed and rebased on main again.
Let me know if this is sufficient to be merged.

Best regards,

Tim

**Review by MovieStoreGuy — APPROVED** [review]

**Pull request merged**
