### PR TITLE
[chore] Remove unused pkg/translator/opencensus replacements

### PR DESCRIPTION
**Pull request by dmitryax**

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
Is this something an automated tool like crosslink should be able to do for us?

**Comment by dmitryax** [comment]
> Is this something an automated tool like crosslink should be able to do for us?

Yes, I think so. Currently crosslink cannot remove stuff

**Comment by Aneurysm9** [comment]
> > Is this something an automated tool like crosslink should be able to do for us?
> 
> Yes, I think so. Currently crosslink cannot remove stuff

It should be possible to use the [`--prune` option](https://github.com/open-telemetry/opentelemetry-go-build-tools/tree/main/crosslink#prune---prune---p) for `crosslink` to remove unnecessary `replace` statements.

**Comment by dmitryax** [comment]
Thanks, @Aneurysm9 . The flag looks like doesn't work. I'll submit a PR. But `prune` subcommand does work https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18668

**Comment by dmitryax** [comment]
Ok, looks like I had an outdated version locally. `--prune` works as well

**Pull request merged**
