### PR TITLE
[receiver/dockerstats] Fix ToMetricLabels behaviour

### LINKED ISSUE #21113: [receiver/dockerstat] Only one label/envVar is added even if when multiple are selected
### Component(s)

receiver/dockerstats

## Description
When running the `dockerstat receiver` I noticed that setting `container_labels_to_metric_labels` with 2 or more labels results in just either one of the labels included as a resource attribute.

```
receivers:
  docker_stats:
    container_labels_to_metric_labels:
      "com.docker.compose.config-hash": "com.docker.compose.config-hash"
      "com.docker.compose.container-number": "new.name"
```

## Steps to Reproduce
Run the exporters with 2 or more entries of `container_labels_to_metric_labels`

## Expected Result
Both labels included 

## Actual Result
Only one of the two was present at a time. 

Screenshot 2023-04-24 at 15 49 21

## Root cause

Basically [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/691044b6efe94f713a36c4abd43a844331491464/receiver/dockerstatsreceiver/receiver.go#L148-L148) we are using directly `labels` without saving a local copy. 
Therefore when running the loop multiple `resourceMetricsOptions` are appended, but all shares the save value for `label`, i.e. the latest one applied.

The following code solves the issue:
```go
	for k, label := range r.config.ContainerLabelsToMetricLabels {

		l := label  <- Adding this shadows the loop variable

		if v := container.Config.Labels[k]; v != "" {
			resourceMetricsOptions = append(resourceMetricsOptions, func(ras metadata.ResourceAttributesSettings, rm pmetric.ResourceMetrics) {
				rm.Resource().Attributes().PutStr(l, v)
			})
		}
	}
```

I checked into the code and envVars are affected as well when setting `env_vars_to_metric_labels`.

Ideally, we would need a fix and a test covering such use-case I can take the ownership of such fix if you want
. 
Notice that there are currently discussions regarding modifying the configuration experience and the implementation to include labels. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13848

### Collector version

691044b6ef

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by paologallinaharbur**
**Description:** 
Only one label/envVar was added even if multiple ones were specified
by ContainerLabelsToMetricLabels or EnvVarsToMetricLabels.
Adding a local variable shadowing the loop one solves the issue.

Without such fix the `label` variable assumes the value of the last element computed in the loop.

More details can be find reading https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21113

**Link to tracking Issue:** 
Fix https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21113

**Testing:** 
The tests that were already existing have been updated to cover the broken use-case

### CODE REVIEW

**Review by jamesmoessis — APPROVED** [review]
Thanks!

**Comment by paologallinaharbur** [comment]
Is there some other work needed? I fear is getting stale 😕

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
I am rerunning your failing test run, approved and marked the PR as ready to merge.

**Comment by paologallinaharbur** [comment]
Thanks, @atoulme, I force-pushed to rebase and trigger tests execution again, but I've not changed the code.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
