### PR TITLE
Revert "Update dependencies Logz.io exporter"

### PR DESCRIPTION
**Pull request by bogdandrutu**
Reverts open-telemetry/opentelemetry-collector-contrib#4386

Corrupted dependency:

```
go: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/logzioexporter@v0.0.0-00010101000000-000000000000 requires
        github.com/logzio/jaeger-logzio@v1.0.3 requires
        github.com/logzio/logzio-go@v1.0.2 requires
        github.com/StackExchange/wmi@v1.2.0: verifying go.mod: checksum mismatch
        downloaded: h1:rcmrprowKIVzvc+NUiLncP2uuArMWLCbu9SBzvHz7e8=
        sum.golang.org: h1:3eOhrUMpNV+6aFIbp5/iudMxNCF27Vw2OZgy4xEx0Fg=
```

### CODE REVIEW

**Comment by yotamloe** [comment]
@bogdandrutu Thanks for the heads up :)
How can I test the software so this issue won't happen again, or how can I recreate it?

**Comment by bogdandrutu** [comment]
This is not your fault, is the dependency problem. Not sure how can you test it, besides making sure that you use dependencies that are doing the right thing :D

**Comment by yotamloe** [comment]
I see.
I tried to recreate it with no success, can you tell me what test or check led you to the error? I'm trying to figure out how to fix it. @bogdandrutu Thanks for helping out

**Comment by bogdandrutu** [comment]
Fixed this by cleaning my golang cache.

**Pull request closed without merging**
