### PR TITLE
[chore] update runner to latest

### LINKED ISSUE #16450: [gh-actions] build-package jobs are failing on the ubuntu-22.04 runners
GitHub actions runner `ubuntu-latest` tag was recently upgraded from Ubuntu 20.04.5 to Ubuntu 22.04.1.

The `build-package` job is failing now. We need to investigate and update it to work on the latest Ubuntu version.

Failing job examples:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3528442298/jobs/5918829725#logs
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3528442298/jobs/5918829832

### PR DESCRIPTION
**Pull request by codeboten**
Fixes #16450

Leaving in draft to test out the build w/ ubuntu-latest

### CODE REVIEW

**Comment by atoulme** [comment]
Reopening. Let's see if it's getting better.

**Comment by codeboten** [comment]
> Reopening. Let's see if it's getting better.

No there was an issue w/ cgroups permission + docker socket in the latest ubuntu. I tested some workaround but couldn't get it to work. I'm guessing we may need to change how rpm/deb packages are built in this repo if we want to see it work....

an alternative i hadn't thought about until just now would be to change those workflows to use the goreleaser since that's what we use in the releases repo anyways.

**Comment by atoulme** [comment]
That sounds sensible regardless of this bug. We found this bug because of rpm and deb testing of a systemd service in ubuntu docker images, and I'm not sure goreleaser deals with testing.

**Comment by codeboten** [comment]
> That sounds sensible regardless of this bug. We found this bug because of rpm and deb testing of a systemd service in ubuntu docker images, and I'm not sure goreleaser deals with testing.

Yeah I'm looking at alternatives for that test as well. Will follow up on this PR once I have something working

**Pull request closed without merging**
