### PR TITLE
[chore] change @astencel-sumo to @andrzej-stencel

### PR DESCRIPTION
**Pull request by andrzej-stencel**
I have changed my GitHub username following https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username.

### CODE REVIEW

**Review by kasia-kujawa — APPROVED** [review]
😢

**Comment by andrzej-stencel** [comment]
> @andrzej-stencel Do you wanna be part of Sumo Logic Processor?

I will create a pull request removing myself.

**Comment by sumo-drosiek** [comment]
> I will create a pull request removing myself.

Could you add remaining team members? I forget about this component and would be grateful for that 🙏

**Review by sumo-drosiek — APPROVED** [review]

**Comment by andrzej-stencel** [comment]
@sumo-drosiek I've created https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32507 (depends on this PR).

**Review by songy23 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
