### PR TITLE
[telemetrygen] add makefile targets

### LINKED ISSUE #18835: [telemetrygen] make docker image and push to docker hub
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

~Telemetrygen is not shipped by the project right now.~

We are shipping telemetrygen but there are no make targets for the tool.

### Describe the solution you'd like

Add a make target for making telemetrygen and its docker image.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Adds makefile targets for telemetrygen

**Link to tracking Issue:**
Fixes #18835

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]
Code LGTM, but does this actually fix #18835? I think it fixes the first part, but it does not push it to Dockerhub, right?

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
> Code LGTM, but does this actually fix #18835? I think it fixes the first part, but it does not push it to Dockerhub, right?

telemetrygen is published as part of `publish-stable`

**Comment by ArthurSens** [comment]
👋 -- I ended up here while looking for `telemetrygen` at dockehub, but [couldn't find it](https://hub.docker.com/u/otel?page=1&search=telemetrygen). Do I have wrong expectations that a container called `telemetrygen` was supposed to exist? Is it published as a binary inside another container?

**Comment by mx-psi** [comment]
@ArthurSens I think it is not in Dockerhub but it is in GHCR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pkgs/container/opentelemetry-collector-contrib%2Ftelemetrygen

**Comment by ArthurSens** [comment]
Aaah ok ok, thank you

**Pull request merged**
