### PR TITLE
OTel-Arrow receiver timeout propagation 

### PR DESCRIPTION
**Pull request by jmacd**
**Description:** Receiver side of https://github.com/open-telemetry/otel-arrow/issues/227. The exporter side is https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34733.
 
**Link to tracking Issue:** https://github.com/open-telemetry/otel-arrow/issues/227

**Testing:** A new end-to-end integration test. ✅ 

**Documentation:** Since this is expected of gRPC receivers, no docs are changed.

### CODE REVIEW

**Review by mwear — COMMENTED** [review]
This needs a go.mod update

```
Error: ../../receiver/otelarrowreceiver/internal/arrow/arrow.go:44:2: missing go.sum entry for module providing package github.com/open-telemetry/opentelemetry-collector-contrib/internal/grpcutil (imported by github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otelarrowreceiver/internal/arrow);
```

**Comment by jmacd** [comment]
This PR will not pass its automatic checks until https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34733 merges. Otherwise I need to re-gen go.mod files which will introduce merge conflicts. It's easier to leave this PR until the other merges.

**Comment by jmacd** [comment]
I plan to leave this in draft until https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34733 merges.

**Review by moh-osman3 — APPROVED** [review]
LGTM!

**Review by mwear — APPROVED** [review]

**Review by moh-osman3 — APPROVED** [review]

**Comment by jmacd** [comment]
The test failure is unrelated.

**Comment by jmacd** [comment]
This PR is a month old. Please merge!

**Review by codeboten — APPROVED** [review]

**Pull request merged**
