### PR TITLE
[chore] Revert "[receiver/hostmetrics] Hostmetrics receiver scrape all processes on linux (#18924)"

### PR DESCRIPTION
**Pull request by dmitryax**
This reverts #18924 as it broke Windows tests

### CODE REVIEW

**Comment by dmitryax** [comment]
cc @jskiba. Feel free to fix the Windows tests, so we don't need to merge this PR

**Comment by jskiba** [comment]
@dmitryax actually isn't this one https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20438 the problem?

**Comment by dmitryax** [comment]
> @dmitryax actually isn't this one https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20438 the problem?

That one was fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20441

**Comment by dmitryax** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4550771721/jobs/8024105149 should show the failures introduced by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18924 and this PR should pass. Let's see

**Comment by dmitryax** [comment]
It appeared to be both changes affected the Windows tests. While fixing what I introduced, I saw errors related to hostmetrics processor errors. I just cannot find them anymore

**Comment by dmitryax** [comment]
@jskiba here you can see the errors https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4550771721/jobs/8024618666

**Comment by jskiba** [comment]
@dmitryax PR is ready, it just needs `Skip changelog` label

**Comment by dmitryax** [comment]
@jskiba Can you please rebase? I merged a fix for other Windows tests

**Pull request closed without merging**
