### PR TITLE
[prometheusremotewriteexporter] Correctly run all prw unit tests, and skip intentional WAL failure.

### PR DESCRIPTION
**Pull request by dashpole**
**Description:**

While working on a different PR, I found that PRW tests are not actually running each case.  It runs the last case a whole bunch of times instead.  Declaring the test case as a local var fixes this, but uncovers a WAL test failure.  This PR skips that test only for the WAL case.

The failure for the WAL case:

```
--- FAIL: Test_PushMetrics (8.22s)
    --- FAIL: Test_PushMetrics/WAL (0.00s)
        --- FAIL: Test_PushMetrics/WAL/5xx_case (4.11s)
            exporter_test.go:667:
                	Error Trace:	exporter_test.go:667
                	Error:      	An error is expected but got nil.
                	Test:       	Test_PushMetrics/WAL/5xx_case
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter	12.401s
FAIL
```

Follow-up from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4751.

### CODE REVIEW

**Comment by Aneurysm9** [comment]
Unfortunately, I'm not sure it's a simple fix.  The issue seems to be the expectation of an error returned from `PushMetrics()` when a `5xx` response is provided, but the data flow is changed when a WAL is in use and a non-error return happens once the data is persisted to the WAL.  

I think it might make sense to separate this out so that it is only tested for the non-WAL case and then separately test for correct handling of server errors when a WAL is in use.

**Comment by dashpole** [comment]
Sounds good.  I'll go ahead and add that onto this PR when I get the chance

**Comment by dashpole** [comment]
Updated to skip the test when the WAL is in use.  I also cleaned up the cases a bit so all tests don't have to set `skipForWal: false`

**Comment by dashpole** [comment]
Failing because of #9255

**Comment by dashpole** [comment]
This is still waiting on review, and fixes important Prometheus unit tests.

**Review by djaglowski — APPROVED** [review]
LGTM

**Pull request merged**
