### PR TITLE
[connector/servicegraph] Fix histogram metrics miss unit

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>

I found the servicegraph histogram metrics missing unit.
This PR will add a proper unit to metrics like [spanmetrics connector does.](			metric.SetUnit(p.config.Histogram.Unit.String()))

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by t00mas** [comment]
I find the change straightforward and LGTM.

I'm more concerned about the situations around this being a breaking change vs. when it isn't. 

I'm leaning towards this being a breaking change as it is now, so it should either be declared as breaking, or non-breaking if we first have this as opt-in. Then it can be moved to opt-out later on.

**Comment by Frapschen** [comment]
@t00mas I believe it will not introduce breaking change if the user uses `prometheusexporter` or `prometheusremotewriteexporter` to exporter metrics. 

however, if the user uses `clickhouseexporter`(save data in native OTLP format), it will be a breaking change.

**Review by mwear — APPROVED** [review]
LGTM. Codeowners, could you take a look? cc: @jpkrohling @mapno @JaredTan95

**Comment by jpkrohling** [comment]
cc @mapno

**Review by mapno — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]
LGTM, sorry about the merge conflicts though :/

**Comment by Frapschen** [comment]
@jpkrohling please merge https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34933 first

**Comment by jpkrohling** [comment]
Merged that one.

**Comment by Frapschen** [comment]
@jpkrohling Ready to merge

**Review by codeboten — APPROVED** [review]

**Pull request merged**
