### PR TITLE
[exporter/loadbalancing] Allow non-exist hostname on startup

### PR DESCRIPTION
**Pull request by Gentoli**
**Description:** <Describe what has changed.>

loadbalancing exporter will crash on startup if the hostname does not resolve, this add startup order requirements to the collectors pods.

This change allows the collector to start when:
- hostname do not exists
- SRV record (headless k8s service) in the hostname have no members

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7051

**Testing:** <Describe what testing was performed and which tests were added.>
Unit test, running locally.

**Documentation:** <Describe the documentation added.>
None

### CODE REVIEW

**Comment by jpkrohling** [comment]
@mapno, are you interested in reviewing this one?

**Review by jpkrohling — APPROVED** [review]
Looks great, just a minor possible improvement to a comment, nothing really blocking.

**Review by codeboten — APPROVED** [review]

**Review by mapno — APPROVED** [review]
LGTM. Although, I was wondering if there should be a mechanism to stop the exporter if DNS resolutions have been failed for an extended period of time

**Comment by jpkrohling** [comment]
I think we have a counter for the number of successful resolutions. Monitoring that number should be enough, right?

**Pull request merged**
