### PR TITLE
[chore] Update the collector core dependency to the latest commit

### PR DESCRIPTION
**Pull request by dmitryax**
- Add `//nolint:staticcheck` comments on usages of `Host.GetExporters` deprecated in https://github.com/open-telemetry/opentelemetry-collector/pull/7390

### CODE REVIEW

**Review by andrzej-stencel — APPROVED** [review]
:see_no_evil:

**Comment by dmitryax** [comment]
The tests are fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23025

**Review by codeboten — COMMENTED** [review]
Ready for a rebase

**Review by songy23 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
@dmitryax is there a follow up issue to track removing GetExporters usage completely?

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
