### PR TITLE
cmd/telemetrygen: add HTTP export for logs

### LINKED ISSUE #18867: [pkg/telemetrygen] log subcommand support --otlp-http flag
### Component(s)

cmd/telemetrygen

### Is your feature request related to a problem? Please describe.

telemetrygen log subcommand should support --otlp-http flag to send log data by http scheme.

### Describe the solution you'd like

telemetrygen log subcommand should support --otlp-http flag to send log data by http scheme.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by axw**
**Description:**

Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18867

**Testing:**

Ran opentelemetry-collector locally with debug exporter, then used telemetrygen with `--otlp-http` with and without `--otlp-insecure`.

**Documentation:** None

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please add a changelog

**Comment by atoulme** [comment]
Please take a look at the failing test:
```
--- FAIL: TestConfig_HTTPPath (0.00s)
    --- FAIL: TestConfig_HTTPPath/LogsConfigEmptyDefaultUrlPath (0.00s)
        config_test.go:15: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/telemetrygen/config_test.go:15
            	Error:      	Not equal: 
            	            	expected: ""
            	            	actual  : "/v1/logs"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-
            	            	+/v1/logs
            	Test:       	TestConfig_HTTPPath/LogsConfigEmptyDefaultUrlPath
FAIL
```

**Review by atoulme — APPROVED** [review]

**Comment by axw** [comment]
Thanks for the review @atoulme, and apologies for sending fixes in dribs and drabs - was doing this around KubeCon & travel :)

I can't merge, can you please do that for me?

**Comment by atoulme** [comment]
I can’t merge either. A maintainer will.

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
