### PR TITLE
[chore] add status checks to mdatagen

### LINKED ISSUE #21265: Validate cmd/otelcontribcol/builder-config.yaml as part of CI
### Component(s)

_No response_

### Is your feature request related to a problem? Please describe.

Right now, components are not always added to the test suite when they should be.

### Describe the solution you'd like

Make sure that all components that are not in development are properly tested in cmd/otelcontribcol.

Down the road, we can add more checks to metadata.yaml.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by atoulme**
Taken after #21264 this adds checks to status metadata if it is present.

Fixes #21265

### CODE REVIEW

**Review by dmitryax — COMMENTED** [review]
LGTM. Please check the failing tests

**Review by codeboten — COMMENTED** [review]
We should wait on the resolution of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21382 before moving forward w/ this change

**Review by codeboten — COMMENTED** [review]
Needs a rebase, the changes look good

**Comment by atoulme** [comment]
I have rebased and simplified the code changes a bit so they merge without clashing with other developments.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
