### PR TITLE
[github-actions] Install tools instead of relying on cache

### PR DESCRIPTION
**Pull request by djaglowski**

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Would it make sense to remove the tool cache here? I've seen issues w/ the tools cache before

**Comment by djaglowski** [comment]
> Would it make sense to remove the tool cache here? I've seen issues w/ the tools cache before

I think so, certainly if we're going to install tools every time anyways.

**Comment by dmitryax** [comment]
I think caching is still helpful to reduce the CI time. Did you try to look what's the reason for the latest failures? I can look into that as well

**Comment by djaglowski** [comment]
I've not been able to pin down the reason that caching started failing. It certainly seems worth getting to the bottom of though, since it will help us make an informed decision about whether to restore it or not. Help is certainly welcome.

**Comment by djaglowski** [comment]
I've opened #9280 to track the need to determine the cause of caching failure, but I recommend we move forward with merging this fix in order to unblock development.

**Review by codeboten — COMMENTED** [review]
In the past, I've updated dependencies in the `internal/tools` directory to force a rebuild of the tools cache. I can't remember if we ever got to the bottom of why this happens though.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9281

**Comment by dmitryax** [comment]
I'm not sure merging this PR is needed at this point. Looks like it's recovered already. We can keep the PR until the next incident, if the root cause is not fixed by that time we can merge it?

**Comment by djaglowski** [comment]
I'll close this PR because #9281 appears to have solved it, but I don't believe it resolved on its own. #9279 still presents the problem, which I believe is the newest PR excluding Alex's fix. PRs opened prior to the issue emerging appear to have continued working.

**Comment by djaglowski** [comment]
Closing in favor of #9281

**Pull request closed without merging**
