### PR TITLE
httpheader extension: Expose HTTP headers as ClientInfo.Auth

### PR DESCRIPTION
**Pull request by disq**
**Description:** New auth extension to expose HTTP headers as ClientInfo.Auth fields, which then can be used in the processor pipeline, as in:

```go
info := client.FromContext(ctx)
// TODO add nil check for info.Auth
val := info.Auth.GetAttribute("X-Forwarded-For")
if str, ok := val.(string); ok {
	fmt.Println("the ip was", val)
}
```

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This is an interesting approach, but I think it would make more sense to have a new field in the `client.Info` to hold the connection metadata (or headers, if we want to use that terminology).
https://github.com/open-telemetry/opentelemetry-collector/blob/4dcb3388a1687f10875d41b9757fd80f6b5eb269/client/client.go#L98-L109

Then, the confighttp/configgrpc would populate it, in a similar way it does with the client IP:
https://github.com/open-telemetry/opentelemetry-collector/blob/4dcb3388a1687f10875d41b9757fd80f6b5eb269/config/confighttp/clientinfohandler.go#L39-L51

**Comment by disq** [comment]
> This is an interesting approach, but I think it would make more sense to have a new field in the `client.Info` to hold the connection metadata (or headers, if we want to use that terminology)

I agree, this is more of a band aid approach while waiting for the collector code to mature (and hopefully we can have these helpers upstream in the future). My use case is a bit different and this was a pain point for us with the http receivers, so wanted to send it in rather than having it sit in a private repo.

**Comment by bogdandrutu** [comment]
@disq please provide the motivation for this. @jpkrohling do you know why this is useful?

**Comment by disq** [comment]
@bogdandrutu we're using OTLP basically as an analytics suite, to collect anonymous usage information (and crash/error reporting to an extent) on a [CLI tool](https://docs.cloudquery.io/docs/cli/telemetry). Promscale/Grafana for reporting. This extension enables us to use a "geoip processor" to inject geolocation data into traces as the main collector runs behind a load balancer. I was thinking it might be useful for others.

**Comment by jpkrohling** [comment]
> do you know why this is useful?

This has been requested a few times in the past, including here: https://github.com/open-telemetry/opentelemetry-collector/issues/2401

**Comment by jpkrohling** [comment]
> I agree, this is more of a band aid approach while waiting for the collector code to mature

I think we now have everything in place to accommodate this feature. Wold you be willing to give it a try?

**Comment by disq** [comment]
> > I agree, this is more of a band aid approach while waiting for the collector code to mature
> 
> I think we now have everything in place to accommodate this feature. Would you be willing to give it a try?

I'll see what I can do, hopefully this week.

**Pull request closed without merging**
