### PR TITLE
[chore] restrict where lifecycle tests run for dockerstats receiver

### PR DESCRIPTION
**Pull request by atoulme**
Alternative to #31485

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by atoulme** [comment]
Windows failure is unrelated.

**Comment by dmitryax** [comment]
> Windows failure is unrelated

looks like active directory receiver lifecycle tests flaky/broken?

**Comment by djaglowski** [comment]
Looks like the failure is the same problem for a different component. Should we just apply both fixes here?

**Comment by dmitryax** [comment]
> Looks like the failure is the same problem for a different component. Should we just apply both fixes here?

Sorry, merged before seeing your comment

**Comment by djaglowski** [comment]
No worries. I'll open another PR

**Comment by djaglowski** [comment]
Actually, @atoulme was right - that failure appears very similar but is not due to the same cause. Looking into it.

**Pull request merged**
