### PR TITLE
[exporter/tanzuobservability] Support queued retries

### PR DESCRIPTION
**Pull request by oppegard**
**Description:** 
Added support for the `retry_on_failure` and `sending_queue` exporter helpers.

**Testing:**
Unit tests passed, and manually tested new config options for our exporter in failure scenarios.

**Documentation:**
Updated our README with the new config options

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please review @thepeterstone

**Review by thepeterstone — APPROVED** [review]
Looks good to me

**Comment by tigrannajaryan** [comment]
Closed/reopened to trigger CI that was stuck.

**Comment by oppegard** [comment]
@tigrannajaryan or other maintainers: anything I can do to move this along?

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
