### PR TITLE
[.github] Simplify workflow

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:**

I think we can get rid of these jobs, since the `deb`s and `rpm`s are created in opentelemetry-collector-releases.

### CODE REVIEW

**Review by fatsheep9146 — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]
I can't recall these checks ever revealing anything actionable, so fully agree with them being removed.

**Review by codeboten — CHANGES_REQUESTED** [review]
The installation of the deb/rpm packages has definitely caught issues in the past where the service would fail to start. I'd recommend adding a similar test somewhere if we don't want the checks here. Pinging @atoulme who reminded me of this on another issue where i suggested the same thing

**Comment by mx-psi** [comment]
> The installation of the deb/rpm packages has definitely caught issues in the past where the service would fail to start

Shouldn't this be covered by e2e tests? It doesn't make a lot of sense to me to build a deb/rpm that we never end up using just for this.

**Comment by codeboten** [comment]
> Shouldn't this be covered by e2e tests? It doesn't make a lot of sense to me to build a deb/rpm that we never end up using just for this.

Sure, I don't know if it's possible to run the installation test without an installable package :) This might be a chicken and egg problem. I'm in support of adding these tests where it makes sense, I just don't want to lose the ability to test for regressions

**Comment by mx-psi** [comment]
> > Shouldn't this be covered by e2e tests? It doesn't make a lot of sense to me to build a deb/rpm that we never end up using just for this.
> 
> Sure, I don't know if it's possible to run the installation test without an installable package :) This might be a chicken and egg problem. I'm in support of adding these tests where it makes sense, I just don't want to lose the ability to test for regressions

Ahhh, so you are talking about the systemd service, not the Collector service (as in, `go.opentelemetry.io/collector/service`). Sorry, I got confused there by the term :smile: 

I guess then my question is... is the systemd service on this repository consistent with the systemd service on [releases](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol/otelcol.service)? Do we have any automated way of making sure they keep on being consistent over time?

I am tempted to close this and file an issue on releases to add these tests there, since that seems like the right place to test things in (with the final artifacts that we actually release to users). Would that make sense to you?

**Comment by mx-psi** [comment]
Closing in favor of open-telemetry/opentelemetry-collector-releases/issues/439

**Pull request closed without merging**
