### PR TITLE
[exporter/mezmoexporter] unexport mezmo structs

### PR DESCRIPTION
**Pull request by atoulme**
Those structs don't need to be exported as part of the Go API.

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Comment by dmitryax** [comment]
After merging few similar PRs, I released that these are breaking api changes. Given that we now have a separate changelog for API, we should utilize it. @atoulme can you please add changelog entry for this one and for others?

**Comment by atoulme** [comment]
This one needs a changelog for sure. Do we need it for others where it's only test code?

**Review by dashpole — APPROVED** [review]

**Comment by dmitryax** [comment]
> Do we need it for others where it's only test code?

Technically yes. They can potentially still be used outside.

**Review by dmitryax — APPROVED** [review]

**Comment by atoulme** [comment]
Alright I will create a separate PR for all the changelogs I missed.

**Pull request merged**
