### PR TITLE
jmxreceiver: update integration test for new release

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
**Description:**
These changes include the latest JMX Metric Gatherer release in the integration test and provide a compatible script and parameterization adjustment.  Can be used to supersede https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5374.

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
I'm not experiencing the integration test failure locally but will try to debug.

**Comment by mx-psi** [comment]
@rmfitzpatrick do you plan to continue working on this?

**Comment by rmfitzpatrick** [comment]
@mx-psi yes, with the aim of resolving https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5874 in the process.  I haven't had a clear moment to continue investigating unfortunately.

**Comment by djaglowski** [comment]
@dehaansa or @Mrod1598, would you be willing to take this issue?

**Comment by rmfitzpatrick** [comment]
Will attempt this at a later date.

**Pull request closed without merging**
