### PR TITLE
Modify kinesisexporter to support metrics/traces to otlp_proto encoding

### PR DESCRIPTION
**Pull request by irisgve**
**Description:**
 - Builds on top of the existing `kinesisexporter` to support exporting both metrics and traces
 - Add support for sending out in OTLP proto bytes format
    - Adds an additional `encoding` option to allow users to choose from supported encodings
    - Only supported encoding at the moment is OTLP proto bytes
    - This required moving over to a more generic kinesis producer library: [omnition](https://github.com/signalfx/omnition-kinesis-producer) from [opencensus-go-exporter](https://github.com/signalfx/opencensus-go-exporter-kinesis) which was serializing the data to jaeger format
- Adds marshallers for OTLP to marshal metrics and traces from the `pData` format

**Link to tracking Issue:**
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1305

**Testing:** 
- Added unit tests for the existing and new functions
- Tested e2e with custom OT collector to local and deployed kinesis streams

**TODOs:**
- [ ]  Support to send out to jaeger format as the existing kinesis exporter supported

**Documentation:**
- [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/master...atlassian-forks:master#diff-90e7217b66136e7a4ab87ec3492adbc218786c4e2b21c81496e81b8039b201e7)

### CODE REVIEW

**Comment by Excaleo** [comment]
One current risk is that there is no backwards implementation with the original kinesis producer. Currently we have 2 pathways but haven't decided on a direction yet. 

Ideally we create a jaeger marshaller which adheres to the `Marshaller` interface however this would not be backwards compatible because the current implementation marshals and sends individual spans to kinesis rather than a whole batch.

My current ideas are:
1. Have a separate code path/function for the jaegar encoding which marshals and sends individual spans to kinesis. 100% backwards compatible, but it's less 'clean' because it doesn't use the marshaller interface

2. Send batches of zipkin spans instead. This would not be backwards compatible but we would be able to create a marshaller.

Any input would be appreciated.

**Comment by owais** [comment]
Thanks for the PR. The end goal sounds good to me but there is a lot going on this in PR. We are adding support for metrics, adding support for OTLP, switching from jaeger to OTLP as default, as far as I can tell we are also removing Jaeger support (may be I didn't look well enough) and there is some considerable refactoring going on. From the UX perspective, this also adds breaking changes as it swaps jaeger with OTLP and changes config structure. I suggest to split this PR into multiple ones that work towards the same end goal but divide the work into independent logical items. For example:

1. Refactor kinesis exporter to use exporter helper functionality, new producer implementation etc.
2. Add OTLP support while keeping Jaeger as default to not break things. We can print warning if user does not specify a default value with the idea that we'll switch over to OTLP after a few releases.
3. Add metrics support on top of this.

**Comment by owais** [comment]
Also noticed some other things like making the exporter struct private. This may also break things. Suggest to try not changing public interface of the package at all if possible. Also, personally I feel making structs that are returned by public functions private can be very annoying for consumers. Sometimes users want to type check or cast to a specific implementation but hiding the implementation makes that impossible to do. I'd rather hide fields inside a struct from external packages but if the public API of the package returns a struct, I think it's useful to keep the struct itself public as well.

**Comment by bogdandrutu** [comment]
@irisgve I think you should try to split the PR into more "focused" and simpler PRs, that are easier to review :)

**Comment by irisgve** [comment]
Thanks @owais and @bogdandrutu! That makes sense. We'll work to split this PR up.

**Comment by tigrannajaryan** [comment]
@irisgve I will close this PR for now. Looking forward to the smaller PRs coming. Please feel free to reference this PR in the new ones.

**Pull request closed without merging**
