### PR TITLE
processor/datadogprocessor: update github.com/DataDog/datadog-agent/pkg/trace

### PR DESCRIPTION
**Pull request by mackjmr**
**Description:** 

This PR upgrades `github.com/DataDog/datadog-agent/pkg/trace` from `v0.44.0-rc.6` to `v0.45.0-rc.1`.

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Does this need any changelog notes?

**Comment by mackjmr** [comment]
@mx-psi no changelog needed here, the changes brought in by this upgrade were added in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20923 and these apply to the exporter.

**Comment by mackjmr** [comment]
@mx-psi I'm not able to add the Skip Changelog label, could you please add it for me ?

**Comment by atoulme** [comment]
Done.

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
