### PR TITLE
[chore] remove deprecated components

### PR DESCRIPTION
**Pull request by bogdandrutu**
The following components have been removed from the distribution as deprecated:

awsprometheusremotewriteexporter
elasticexporter
honeycombexporter

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
I LGTM but I believe we should get approvals from code owners as well.

cc @Aneurysm9 @alolita @axw @simitt @jalvz @lizthegrey @MikeGoldsmith

**Comment by dmitryax** [comment]
@bogdandrutu why this is a blocker for release?

**Review by lizthegrey — COMMENTED** [review]
+2 Approve of removing honeycomb exporter.
+0 on the other changes, no opinion/review performed of them

**Comment by bogdandrutu** [comment]
@dmitryax they are not in the distribution for at least two versions anyway and got approval from owners when we removed from the distros.

The reason to be a blocker is to not release anymore artifacts that we don't include in the distros.

**Comment by dmitryax** [comment]
I just found that the change log entry is missing. I believe we should add it and mention all the removed components

**Comment by axw** [comment]
FWIW, it is/was fine by me to remove elasticexporter.

**Pull request merged**
