### PR TITLE
update Honeycomb Exporter and its dependencies

### PR DESCRIPTION
**Pull request by lizthegrey**
**Description:**
Update Honeycomb Exporter v0.8.0 compatibility

**Link to tracking Issue:**
https://github.com/honeycombio/opentelemetry-exporter-go/issues/81

**Testing:**
Run circleci

**Documentation:**
n/a dep update only

### CODE REVIEW

**Comment by lizthegrey** [comment]
Build failing due to https://github.com/open-telemetry/opentelemetry-collector/issues/1366

**Comment by lizthegrey** [comment]
Failing:
`TestMetric10kDPS/OpenCensus: test_case.go:327: CPU consumption is 81.0%, max expected is 70%`

Likely due to regression in v0.6.0 collector.

**Review by flands — APPROVED** [review]

**Comment by lizthegrey** [comment]
> Failing:
> `TestMetric10kDPS/OpenCensus: test_case.go:327: CPU consumption is 81.0%, max expected is 70%`
> 
> Likely due to regression in v0.6.0 collector.

No, this is an OpenCensus regression. Making a separate test PR to demonstrate the problem and submitting it to OpenCensus.

**Comment by lizthegrey** [comment]
wtf, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/469 still works. okay, back to the drawing board.

**Comment by lizthegrey** [comment]
Yup, the issue seems to have been the accidental upgrade of protobuf to v1.4.x

https://github.com/open-telemetry/opentelemetry-collector/pull/1308#issuecomment-659181332

**Pull request merged**
