### PR TITLE
Migrate k8s processor to new dataformat

### LINKED ISSUE #262: K8S Processor Passthrough mode not working with Jaeger
Among changes in internal data format is [removal of SourceFormat attribute](https://github.com/open-telemetry/opentelemetry-collector/commit/e44607a8045f327d4e98dcb60d689f4d184c9115#diff-0e6ca11168918e81d990fd9005b9671cL356), which was used by the [processor logic in certain cases](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/k8sprocessor/processor.go#L102-L106). 

The passthrough mode seems to no longer work when spans are sent using Jaeger gRPC (and possible some of the other formats as well)

### PR DESCRIPTION
**Pull request by owais**
Migrate k8sprocessor to new internal data format

Also use the oppurtunity to introduce k8s API auth from internal/common/k8sconfig package.

Also fixes #262

**Testing:** Manual local testing and updated unit tests

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by dmitryax** [comment]
@owais could you check if we can improve the coverage?

**Comment by owais** [comment]
I thought we already did improve coverage of this processor in this commit ). I think we basically cover all the processor code paths. I can add tests to cover all options but don't think they add much value.

**Comment by dmitryax** [comment]
That's just to make make codecov happy so we can merge it. Looks like you moved some parts around which were not covered before :(

**Pull request closed without merging**
