### PR TITLE
Newrelic exporter updates

### PR DESCRIPTION
**Pull request by jack-berg**
- Marked unsupported metric as permanent error.
- Force the interval to be valid even if 0.

### CODE REVIEW

**Review by nrcventura — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
```
#!/bin/bash -eo pipefail
grep ^otelcontribcol-all-sys Makefile|fmt -w 1|tail -n +2|circleci tests split|xargs make
GOOS=darwin  GOARCH=amd64 make otelcontribcol
make[1]: Entering directory '/home/circleci/project'
GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ./bin/otelcontribcol_darwin_amd64 \
	-ldflags "-X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.GitHash=313cc4ef8 -X github.com/open-telemetry/opentelemetry-collector-contrib/internal/version.Version=v0.31.0-3-g313cc4ef8 -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcontribcol
exporter/newrelicexporter/factory.go:21:2: missing go.sum entry for module providing package github.com/newrelic/newrelic-telemetry-sdk-go/telemetry (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/newrelicexporter); to add:
	go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/newrelicexporter@v0.0.0-00010101000000-000000000000
make[1]: *** [Makefile:201: otelcontribcol] Error 1
make[1]: Leaving directory '/home/circleci/project'
make: *** [Makefile:215: otelcontribcol-darwin_amd64] Error 2

```

**Review by alanwest — APPROVED** [review]
@tigrannajaryan I think @nrcventura fixed the go.sum issues... but not sure why EasyCLA is giving this PR grief all of the sudden ☹️   ... any thoughts?

**Review by alanwest — CHANGES_REQUESTED** [review]
Oops, approved prematurely, @jack-berg looks like there are some failing tests

**Comment by tigrannajaryan** [comment]
EasyCLA is good now.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
