### PR TITLE
Update github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector to v0.30.1

### PR DESCRIPTION
**Pull request by dashpole**
**Description:**

Update the gcp collector dependency.  It includes one additional commit on top of v0.30.1, which removes the dependency on opencensus translation: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/390.

Forked from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9920, since it requires some additional changes to keep tests working.

### CODE REVIEW

**Comment by dashpole** [comment]
cd @codeboten @bogdandrutu

**Review by bogdandrutu — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Thanks @dashpole!

**Comment by bogdandrutu** [comment]
@dashpole please rebase

**Comment by dmitryax** [comment]
@dashpole I see that googlecloudexporter has `github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector` dependency which uses `github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/opencensus` as another dependency. I'm curious if this interdependency is planned to be resolved? Looks like this is the only place where gcp depends on contrib https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/traces_test.go#L270

**Comment by dashpole** [comment]
Thanks for reminding me.  I'll try and resolve that this week

**Comment by dashpole** [comment]
This PR now includes the commit that removes the opencensus translation dependency.  PTAL!

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
