### PR TITLE
Stackdriver Exporter: Update insecure clients to explicitly connect with insecure connections

### PR DESCRIPTION
**Pull request by dinooliva**
…th insecure connections

### CODE REVIEW

**Comment by dinooliva** [comment]
@rghetia - ptal

**Review by rghetia — COMMENTED** [review]
Can you please create an issue and describe the problem?
LGTM otherwise.

**Comment by dinooliva** [comment]
Fixes #77

**Review by rghetia — APPROVED** [review]

**Review by tigrannajaryan — COMMENTED** [review]
Please update PR description and commit message to reflect that this is about Stackdriver exporter.

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
