### PR TITLE
Update core to latest in preparation for this week release

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Please resolve conflict

**Comment by bogdandrutu** [comment]
@codeboten done, was doing that but my computer is super slow to rebuild everything

**Review by dmitryax — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Looks like one `"on"` was missed in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/21e9c86af89b8a1da85c806142c4af5db4331962/exporter/skywalkingexporter/README.md

**Comment by bogdandrutu** [comment]
@codeboten done

I like how copy/paste works in this project :D

**Review by codeboten — APPROVED** [review]

**Pull request merged**
