### PR TITLE
[chore] move googlecloudpubsub exporter to generated lifecycle tests

### PR DESCRIPTION
**Pull request by Frapschen**
Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27849

### CODE REVIEW

**Review by fatsheep9146 — APPROVED** [review]

**Comment by atoulme** [comment]
@alexvanboxel please review as codeowner, thanks!

**Review by alexvanboxel — APPROVED** [review]
LGTM

**Comment by dmitryax** [comment]
@Frapschen can you please rebase?

**Comment by atoulme** [comment]
I rebased.

**Comment by dmitryax** [comment]
Is it expected to be no changes in the diff?

**Comment by atoulme** [comment]
I think this was applied through the generalization of tests then. Closing!

**Pull request closed without merging**
