### PR TITLE
[chore] Skip flaky test on Windows

### LINKED ISSUE #32397: [receiver/googlecloudspanner] Test TestItemCardinalityFilter_Filter fails intermittently on Windows runs
### Component(s)

receiver/googlecloudspanner

### Describe the issue you're reporting

[CI/CD failure link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8694703823/job/23844185019?pr=32176)

Failure output:
```
Running target 'test' in module 'receiver/googlecloudspannerreceiver' as part of group 'receiver-1'
C:/mingw64/bin/make --no-print-directory -C receiver/googlecloudspannerreceiver test
D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout [30](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8694703823/job/23844185019?pr=32176#step:7:31)0s -parallel 4 --tags=""
✓  internal/filterfactory (cached)
✓  internal/metadata (cached)
✖  internal/filter (434ms)
✓  internal/datasource (2.156s)
✓  . (5.051s)
✓  internal/metadataconfig (1.778s)
✓  internal/metadataparser (1.744s)
✓  internal/statsreader (1.891s)

DONE 288 tests, 1 skipped, 1 failure in 13.253s

✖  internal/filter (888ms)

=== Skipped
=== SKIP: internal/statsreader TestStatsReaders_Read (0.00s)
    statsreaders_mockedspanner_test.go:123: Flaky test - See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6[31](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8694703823/job/23844185019?pr=32176#step:7:32)8

=== Failed
=== FAIL: internal/filter TestItemCardinalityFilter_Filter (0.10s)
    logger.go:146: 2024-04-15T19:22:05.611Z	DEBUG	Added item to cache	{"seriesKey": "key1", "timestamp": "2021-10-13T20:30:00.000Z"}
    logger.go:146: 2024-04-15T19:22:05.660Z	DEBUG	Added item to cache	{"seriesKey": "key2", "timestamp": "2021-10-13T20:30:00.000Z"}
    logger.go:146: 2024-04-15T19:22:05.661Z	DEBUG	Skip item	{"seriesKey": "key3", "timestamp": "2021-10-13T20:30:00.000Z"}
    logger.go:146: 2024-04-15T19:22:05.661Z	DEBUG	Added item to cache	{"seriesKey": "key5", "timestamp": "2021-10-13T20:30:05.000Z"}
    logger.go:146: 2024-04-15T19:22:05.661Z	DEBUG	Added item to cache	{"seriesKey": "key4", "timestamp": "2021-10-13T20:30:10.000Z"}
    logger.go:146: 2024-04-15T19:22:05.661Z	DEBUG	Skip item	{"seriesKey": "key6", "timestamp": "2021-10-13T20:30:10.000Z"}
    logger.go:146: 2024-04-15T19:22:05.662Z	DEBUG	Added item to cache	{"seriesKey": "key3", "timestamp": "2021-10-13T20:30:20.000Z"}
    logger.go:146: 2024-04-15T19:22:05.662Z	DEBUG	Skip item	{"seriesKey": "key6", "timestamp": "2021-10-13T20:30:20.000Z"}
    itemcardinality_test.go:1[43](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8694703823/job/23844185019?pr=32176#step:7:44): 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/googlecloudspannerreceiver/internal/filter/itemcardinality_test.go:143
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestItemCardinalityFilter_Filter
    logger.go:1[46](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8694703823/job/23844185019?pr=32176#step:7:47): 2024-04-15T19:22:05.716Z	DEBUG	Added item to cache	{"seriesKey": "key3", "timestamp": "2021-10-13T20:30:20.000Z"}
    logger.go:146: 2024-04-15T19:22:05.716Z	DEBUG	Added item to cache	{"seriesKey": "key6", "timestamp": "2021-10-13T20:30:20.000Z"}

DONE 2 runs, 289 tests, 1 skipped, 1 failure in 15.777s
make[2]: *** [../../Makefile.Common:126: test] Error 1
make[1]: *** [Makefile:165: receiver/googlecloudspannerreceiver] Error 2
```

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
Since `receiver/googlecloudspanner` is unmaintained I'm opting to simply skip the flaky test on Windows.

**Link to tracking Issue:**
Workaround for #32397

**Testing:**
N/A

**Documentation:**
N/A

### CODE REVIEW

**Review by samiura — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]
I entirely agree skipping is the right move for now.  Slight nit though, I might leave the original issue open in the case of this component finding a maintainer. While we have the component in `contrib` it makes sense to keep its issues. If we get to the point of removing it we can go through and close all related issues 👍 

_If that's agreeable, we can remove the `Fix` prefix before the issue number in the PR description._

**Review by codeboten — APPROVED** [review]

**Comment by crobert-1** [comment]
[Another test](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10946967052/job/30394655819#step:8:146) in the same file failed on Windows:
```
itemcardinality_test.go:199: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/googlecloudspannerreceiver/internal/filter/itemcardinality_test.go:199
        	Error:      	"[0xc000089800 0xc000089[83](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10946967052/job/30394655819#step:8:84)0 0xc000089860]" should have 4 item(s), but has 3
        	Test:       	TestItemCardinalityFilter_FilterItems
```
_We can add a skip now or later, whatever's easier_

**Comment by pjanotti** [comment]
@crobert-1 let me add the skip for `TestItemCardinalityFilter_FilterItems` now. If others pop up I will feel tempted to use a build tag to skip all tests in Windows.

**Comment by manu2** [comment]
Looking into the issue.

**Pull request merged**
