### PR TITLE
Add information about security documentation to exporter README

### PR DESCRIPTION
**Pull request by flands**
Attempts to address #2230, #2231, #2232, #2233

### CODE REVIEW

**Comment by flands** [comment]
@mx-psi @arminru @gramidt @alolita FYI

**Review by gramidt — APPROVED** [review]
LGTM! . On a related note, I started a discussion for integration with external secret stores and systems here: https://github.com/open-telemetry/opentelemetry-collector/issues/2469 .

**Review by mx-psi — APPROVED** [review]
Thanks! LGTM, would like to know @alolita's thoughts on this :)

**Review by arminru — APPROVED** [review]
Thank you, @flands!

**Review by bogdandrutu — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@alolita if you have any concerns please file an issue and will adress.

**Pull request merged**
