### PR TITLE
[receiver/splunkhec] fix memory leak

### LINKED ISSUE #34886: splunkhec receiver memory leak
### Component(s)

receiver/splunkhec

## Description
We've uncovered what appears to be a memory leak in the splunkhec receiver that surfaced around version 0.102.0. We run the the receiver in both a metric and log pipeline. We are not sending logs using hec yet the collector is holding 2gb of heap under (*ObsReport).StartLogsOp (obsreport.go:L#95).
## Steps to Reproduce
splunkhec receiver in logs and metrics pipeline 

## Expected Result
Memory remains stable

## Actual Result
Memory grows until we trigger the memory limiter then the collector gc's

35C08CF1-ECDD-4999-AFE6-21BEA453619A_1_105_c

49D534B1-3EF8-4949-B671-7B4C66E8E1E7

### Collector version

0.106.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

When we remove the splunhecreceiver from the logs pipeline the memory is stable. At the moment we only have applications sending metrics to the hec receiver in the impacted clusters.

### PR DESCRIPTION
**Pull request by atoulme**
**Description:** 
Fix memory leak when the receiver is used for both metrics and logs at the same time

**Link to tracking Issue:** <Issue number if applicable>
Fixes #34886

### CODE REVIEW

**Review by crobert-1 — COMMENTED** [review]
Is there any way to add tests for this?

I'm pretty unfamiliar with this component, but it surprises me that no tests needed updated even though a few function signatures changed. I assume this functionality is covered by tests, just at a higher functional level?

**Comment by atoulme** [comment]
@crobert-1 I think that might need a bigger follow up where we'd have this being tracked as a bug across the board. This is likely to happen for any component where we start, but don't end an obsreport operation. I also think this might be something we could start to make easier on people or use tracing for.

**Comment by atoulme** [comment]
We should probably have better tests for this. Alternatively, we could also rip out all the obsreport code.

**Comment by crobert-1** [comment]
> @crobert-1 I think that might need a bigger follow up where we'd have this being tracked as a bug across the board. This is likely to happen for any component where we start, but don't end an obsreport operation. I also think this might be something we could start to make easier on people or use tracing for.

Can you open an issue to track this?

**Comment by atoulme** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34931 is open to track this.

**Review by crobert-1 — APPROVED** [review]

**Pull request merged**
