### PR TITLE
Replace path.Join method with filepath.Join method

### LINKED ISSUE #6480: Standardized testdata config filepath pattern
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6459#discussion_r759550623, there is a current test pattern for specifying config files of the form:

```go
cfg, err := configtest.LoadConfigAndValidate(path.Join(".", "testdata", "config.yaml"), factories)
```

This invocation is slightly problematic for two reasons:

1. the initial "." is unnecessary.
2. `path.Join()` hardcodes the separator as "/" instead of picking it up from the os like `filepath.Join()` does, which is used by the underlying koanf loader. 

**Describe the solution you'd like**
Replace all `path.Join(".",` with `filepath.Join(`

**Describe alternatives you've considered**
Using embed could be preferable to using paths and loaders overall since the underlying byte slice would be available in the packages.  I have superficially confirmed that embedded items in test functions don't make their way to the final build using hexdump, but a more rigorous assessment would be necessary.  Since the existing helper works with paths and uses* the config map loaders, requiring embed directives as replacements and using bytes directly is probably overkill for most cases.

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
**Description:** <Describe what has changed.>

This replaces the path.Join to filepath.Join  in the testing files

**Link to tracking Issue:** <Issue number if applicable>
Closes #6480
**Testing:** <Describe what testing was performed and which tests were added.>
No tests added , make commands

**Documentation:** <Describe the documentation added.>
None

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
There are some compilation issues:

```
golangci-lint run --allow-parallel-runners
config_test.go:35:48: undeclared name: `filepath` (typecheck)
	cfg, err := servicetest.LoadConfigAndValidate(filepath.Join("testdata", "config.yaml"), factories)
	                                              ^
config_test.go:18:2: "path" imported but not used (typecheck)
	"path"
	^
```

**Comment by bogdandrutu** [comment]
@DiptoChakrabarty please fix lint, please fix the linked issue (I don't think that is what you wanted to link), please explain the motivation (probably the linked issue has that, but because of the wrong linked issue I don't understand why).

**Comment by jpkrohling** [comment]
> please fix the linked issue (I don't think that is what you wanted to link), please explain the motivation (probably the linked issue has that, but because of the wrong linked issue I don't understand why).

I had the issue open here so I fixed that part. Looks like @DiptoChakrabarty missed a 0 :-)

**Review by codeboten — COMMENTED** [review]
Change looks good, happy to approve once CI passes. 👍

**Review by bogdandrutu — APPROVED** [review]
Happy with the change, @codeboten please merge when ready :)

**Comment by DiptoChakrabarty** [comment]
> config_test.go:18:2: "path" imported but not used (typecheck)
> 	"path"

fixed

**Comment by bogdandrutu** [comment]
@DiptoChakrabarty need more fixes.

**Review by bogdandrutu — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Looks like a few more fixes are needed

```
# github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver [github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver.test]
Error: ./integration_test.go:27:2: imported and not used: "path"
Error: ./integration_test.go:93:16: undefined: filepath
Error: ./integration_test.go:160:25: undefined: filepath
Error: ./integration_test.go:262:23: undefined: filepath
```

**Review by codeboten — COMMENTED** [review]
Please resolve the conflicts, i think we're almost there!

**Comment by bogdandrutu** [comment]
@codeboten I think this is still not done yet.

**Comment by DiptoChakrabarty** [comment]
> @codeboten I think this is still not done yet.

rebased it should work

**Comment by jpkrohling** [comment]
There are a couple of linting issues:

```
golangci-lint run --allow-parallel-runners
Error: config_test.go:18:2: "fmt" imported but not used (typecheck)
	"fmt"
	^
Error: config_test.go:19:2: "os" imported but not used (typecheck)
	"os"
	^
```

**Comment by jpkrohling** [comment]
Linting is still failing:

```
misspell -error ./README.md ./client.go ./client_test.go ./codegen.go ./config.go ./documentation.md ./factory.go ./info.go ./info_test.go ./internal/metadata/generated_metrics_v2.go ./keyspace.go ./keyspace_test.go ./metadata.yaml ./metric_functions.go ./metric_functions_test.go ./redis_e2e_test.go ./redis_scraper.go ./redis_scraper_test.go ./redis_svc.go ./redis_svc_test.go
config_test.go:53: File is not `gofmt`-ed with `-s` (gofmt)

make[2]: *** [../../Makefile.Common:95: lint] Error 1
```

You might want to follow the contribution guidelines to see how you can run these checks locally.

**Comment by DiptoChakrabarty** [comment]
My apologies but I am unable to run the tests in my system but I want to complete this PR , I would like to use the gh actions if its okay

**Pull request merged**
