### PR TITLE
Webhookreceiver - option to add a required header

### PR DESCRIPTION
**Pull request by greatestusername**
**Description:** 
Adding a feature - Allow option of adding a required header for incoming webhook requests. If header doesn't match, returns a 401.

**Link to tracking Issue:** [<24270>](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24270)

**Testing:** Added tests for config of required header setting and receiver handling of missing or incorrect required header

**Documentation:** Configuration is documented in the README.md and config/config_test

### CODE REVIEW

**Comment by greatestusername** [comment]
I dont think I can address this for the [build-and-test / coverage test]([Details](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5646390028/job/15295292363?pr=24452)). I assume someone just needs to re-kick it off?
image

**Review by atoulme — APPROVED** [review]

**Review by shalper2 — APPROVED** [review]

**Review by shalper2 — APPROVED** [review]
perfect! tyvm

**Comment by dmitryax** [comment]
Is this only needed for authentication? `HTTPServerSettings` already has the `auth` option which can utilize https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension with pretty similar outcome...

**Comment by greatestusername** [comment]
> Is this only needed for authentication? `HTTPServerSettings` already has the `auth` option which can utilize https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension with pretty similar outcome...

This is specifically for expecting an arbitrary header rather than authorizing a basic auth request. That extension does seem like a great way to basic auth if that is required by a webhook though! Thanks for pointing it out

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
