### PR TITLE
exporter/uptraceexporter: remove uptraceexporter (replaced with OTLP)

### PR DESCRIPTION
**Pull request by vmihailenco**
At Uptrace we've added native support for [OTLP protocol](https://docs.uptrace.dev/guide/collector.html#configuration) so there is no much sense to maintain custom exporter anymore. uptraceexporter was never added to the otelcontribcol binary and AFAIK none is actively using it. But just in case, uptraceexporter can be replaced with OTLP using the following config:

```yaml
exporters:
  otlp:
    endpoint: otlp.uptrace.dev:4317
    headers: { 'uptrace-dsn': '<dsn>' }
    compression: on
```

Thanks everyone for keeping the code updated :+1:

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Do you want to keep this and deprecate it initially?

**Comment by vmihailenco** [comment]
If you say so, but to re-iterate uptraceexporter is not enabled in [components](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/otelcontribcol/components.go) so the only way to use it is a custom build (and AFAIK none did that).

Should I add a deprecated notice to the readme and some warnings to the code?

**Comment by bogdandrutu** [comment]
@vmihailenco makes sense, please rebase and we remove then :)

**Comment by vmihailenco** [comment]
Done, PTAL

**Comment by tigrannajaryan** [comment]
@vmihailenco this is great. I hope to see more vendors adopt OTLP!

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
