### PR TITLE
[receiver/elasticsearch] Fix issues/17867 by adding "/nodes" to the request path

### PR DESCRIPTION
**Pull request by junhuangli**
**Description:** <Describe what has changed.>

Fix issues/17867 by adding "/nodes" to the request path. 
ES API Reference - https://www.elastic.co/guide/en/elasticsearch/reference/7.17/cluster-stats.html

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17867

**Testing:** <Describe what testing was performed and which tests were added.>
Manually tested the API with ES 7.17.8

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by djaglowski** [comment]
I apologize for missing this issue when it was originally filed.

@davidji99, @junhuangli, I'm wondering if there is a reasonable way to cover this endpoint in the integration test. Perhaps the container can be run as a 1-node "cluster"?

**Comment by djaglowski** [comment]
@junhuangli, thanks for the contribution. Please sign the CLA

**Comment by junhuangli** [comment]
Thanks for replying @djaglowski, I just signed the CLA. Let me know if there is anything else I should do.
And to avoid this kind of issue in the future, adding a 1-node es is the best solution. Let me know if you want me to help on that too.

**Comment by djaglowski** [comment]
@junhuangli, thanks for signing the CLA. You may need to bump the PR in order to get the check to pass.

**Comment by djaglowski** [comment]
> And to avoid this kind of issue in the future, adding a 1-node es is the best solution. Let me know if you want me to help on that too.

Help would be most welcome! We have an existing integration test [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/elasticsearchreceiver/integration_test.go). Maybe there is a way to update it to cover the endpoint.

**Comment by junhuangli** [comment]
seems like it is not working with a dummy space change. should I close this pull request and create a new one?

**Comment by djaglowski** [comment]
@junhuangli, I'm not sure but I seem to recall that easycla does not require reopening the PR. Let's give it a few hours and try `/easycla` again.

**Comment by junhuangli** [comment]
Seems like the CLA doesn't like my first commit which didn't have my email. It doesn't work even if I rollback that commit. Have to close this pull request. Will open a new one soon

**Comment by junhuangli** [comment]
Created [19414](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19414) to solve the CLA issue

**Pull request closed without merging**
