### PR TITLE
[receiver/huaweicloudces] add implementation

### PR DESCRIPTION
**Pull request by narcis96**
Description
Adds initial implementation of huaweicloudces.

Link to tracking issue
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34953

### CODE REVIEW

**Review by mwear — APPROVED** [review]

**Comment by dmitryax** [comment]
@narcis96 please rebase

**Comment by narcis96** [comment]
@dmitryax  rebase done

**Comment by narcis96** [comment]
@fatsheep9146  PTAL

**Comment by dmitryax** [comment]
Sorry for the delay. it need another rebase

**Comment by narcis96** [comment]
@dmitryax  rebase done

**Pull request merged**
