### PR TITLE
[exporter/clickhouseexporter] Sort attribute maps before insertion #33634

### LINKED ISSUE #33634: ClickHouse exporter produces duplicates and poor compression without sorting attributes
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

The default table created by the exporter isn't a good pattern for optimizing compression and removing duplicates.  ClickHouse does not sort the map values, so even though there may be duplicate records the order of their attributes may be different.  This causes ClickHouse to treat them as unique records for storage and merge trees.  This also effects ClickHouses compression so the same data takes up a lot more disk.

### Describe the solution you'd like

We identified this issue and the solution was to use a NULL Engine for the primary table the Exporter writes to, then using a Materialized View we explicitly sort the attributes before insert.
` mapSort(`Attributes`) as Attributes, `

After this the compression rate for billions of rows was greater than 250, making the storage needed much less.  It also eliminated duplicates and helped streamline the increase functions so we could avoid extra processing.

This makes the initial table creation a bit trickier but it is critical in my experience.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by earwin**
#### Description
Our attributes are stored as Map(String, String) in CH.
By default the order of keys is undefined and as described in #33634 leads to worse compression and duplicates in `group by` (unless carefully accounted for).
This PR uses the `column.IterableOrderedMap` facility from clickhouse-go to ensure fixed attribute key order.

It is a reimplementation of #34598 that uses less allocations and is (arguably) somewhat more straightforward.

I'm **opening this as a draft**, because this PR (and #34598) are blocked by https://github.com/ClickHouse/clickhouse-go/issues/1365 (fixed in https://github.com/ClickHouse/clickhouse-go/pull/1418)

In addition, I'm trying to add the implementation of `column.IterableOrderedMap` used to clickhouse-go upstream: https://github.com/ClickHouse/clickhouse-go/pull/1417
If it is accepted, I will amend this PR accordingly.

#### Link to tracking issue
Fixes #33634

#### Testing
The IOM implementation was used in production independently.
I'm planning to build otelcollector with this PR and cut over my production to it in the next few of days.

### CODE REVIEW

**Comment by dmitryax** [comment]
Please add a changelog entry

**Review by hanjm — APPROVED** [review]

**Review by SpencerTorres — APPROVED** [review]
Appreciate the contribution, glad to see this implemented. The compression benefits will be great!

**Comment by hanjm** [comment]
@dmitryax could you help run ci? thank you.

**Comment by hanjm** [comment]
@open-telemetry/collector-contrib-approvers hi，anyone could help run ci? thank you.

**Comment by ChrsMark** [comment]
@Frapschen @dmitryax mind taking a look?

**Comment by SpencerTorres** [comment]
@earwin I appreciate your patience, the CI can be a bit difficult with all of the linting scripts. It looks like the CI is passing now though

@crobert-1 I don't have permission to merge, let me know if you can get in touch with the right approvers for this. It's an important change that has been open for a while. Thanks!

**Comment by OneCyrus** [comment]
we are waiting for this merge as well. 

looks like @crobert-1 is away for some time according to his status. 
image

maybe someone else can approve the merge?

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
