### PR TITLE
Install gcc before running Windows tests

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** <Describe what has changed.>

Fix CircleCI `windows-tests` suite.

**Link to tracking Issue:** #1270

**Testing:** The CircleCI `windows-test` passes on this branch

**Documentation:** n/a

### CODE REVIEW

**Comment by mx-psi** [comment]
cc @james-bebbington, I believe this fixes issue #1270, could you have a look? The `loadtest` failed but this is unrelated.

**Review by james-bebbington — APPROVED** [review]
That's interesting. Your fix looks fine to resolve this issue for now.

However, I recall @tigrannajaryan had concerns with enabling CGO in this repository. Of note, it looks like the only reason the Windows build currently succeeds (with `CGO_ENABLED=0`) is because this component (datadog exporter) hasn't been added to the root `go.mod` yet (also note it looks like the datadog agent only imports "C" in relevant files that are behind a windows build flag, so non-Windows builds will be okay).

Not sure what the longer term plans are to support this / include this component in the otelcontribcol binary?

**Comment by mx-psi** [comment]
Thanks for having a look!

> Of note, it looks like the only reason the Windows build currently succeeds (with CGO_ENABLED=0) is because this component (datadog exporter) hasn't been added to the root go.mod yet (also note it looks like the datadog agent only imports "C" in relevant files that are behind a windows build flag, so non-Windows builds will be okay).

The Windows build bit makes sense to me. I can build locally on macOS and Linux with the component activated (running `make otelcontribcol`) so it looks to me like it is a Windows only problem, yes.

> Not sure what the longer term plans are to support this / include this component in the otelcontribcol binary?

We were planning on opening a PR for including this component on the binary soon-ish (after #1216 and #1226 get merged). If this becomes a problem we will probably include a first version with limited support on Windows (disabling the bits that need CGo) until we can avoid using CGo on Windows.

I too would like to hear @tigrannajaryan about this.

**Comment by ericmustin** [comment]
👋 Hi all, I work with @mx-psi . We spoke briefly at the SIG y'day. Just echo'ing his comments here which are that we'd be comfortable with limited Windows support for the datadogexporter first release for now. To that effect, this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1266,  contains both the final portion of our trace export code, and also has been updated to reflect the proposed limited Windows support (we'd only support metrics export on Windows, since trace translation/export relies on the imports which are causing issues on Windows Builds, so we won't build those components)

**Review by tigrannajaryan — CHANGES_REQUESTED** [review]
We do not allow cgo in Collector. This has been discussed in the past and decided against.

**Comment by mx-psi** [comment]
> We do not allow cgo in Collector. This has been discussed in the past and decided against.

Thanks for chiming in @tigrannajaryan. As Eric said, we are disabling the Cgo dependent bits on #1266 so that the tests can pass again. Let us know if you would rather have these changes on a separate PR to fix the CircleCI check more quickly.

**Comment by mx-psi** [comment]
Closing in favour of #1274

**Pull request closed without merging**
