### PR TITLE
[extension/honeycombauthextension] add honeycomb authenticator

### PR DESCRIPTION
**Pull request by mdreizin**
**Description:** <Describe what has changed.>

This extension provides Honeycomb authentication for making requests to [Honeycomb OpenTelemetry API](https://docs.honeycomb.io/getting-data-in/opentelemetry-overview/#using-the-honeycomb-opentelemetry-endpoint).

**Link to tracking Issue:** <Issue number if applicable>

None

**Testing:** <Describe what testing was performed and which tests were added.>

Added unit and integration tests.

**Documentation:** <Describe the documentation added.>

Added `README.md` with a description of what this extension does and how to use it.

### CODE REVIEW

**Comment by Aneurysm9** [comment]
Thank you for your interest in contributing this.  Can you please review the [contributing guidelines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components) and ensure that the new component process is followed?  Does this component have a sponsor, ideally someone from Honeycomb who is willing to be a code owner.  Since this appears to serve primarily to add static gRPC metadata (and ideally also HTTP headers, though I don't see that in the implementation) is there a more generalized AuthN extension that could serve this purpose?

**Comment by mdreizin** [comment]
@Aneurysm9 Thank you for your feedback.

This extension will be useful if you would like to have a common config, but have different auth headers (eg. `dev`, `prod`, etc.):

```yaml
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
spec:
  env:
    - name: HONEYCOMB_TEAM
      valueFrom:
        secretKeyRef:
          name: otel-hc
          key: team
    - name: HONEYCOMB_DATASET
      valueFrom:
        secretKeyRef:
          name: otel-hc
          key: dataset
```

**Comment by Aneurysm9** [comment]
That is already possible through environment variable substitution:

```yaml
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": $HONEYCOMB_TEAM
      "x-honeycomb-dataset": $HONEYCOMB_DATASET
```

**Comment by mdreizin** [comment]
@Aneurysm9 Oh, I didn’t know that. Thank you for sharing that. This PR is useless :)

**Comment by Aneurysm9** [comment]
Not totally useless, at the least it calls out that we could improve our documentation.  Is there any documentation you looked to expecting guidance on how to do this where we should have more information about this capability?

**Comment by mdreizin** [comment]
@Aneurysm9 We are using a custom version of otel collector, which does not/did not support environment variable substitution. That was my fault, I did not check [the documentation](https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables). I am going to update it to the latest version, and I hope everything will be ok.

**Pull request closed without merging**
