### PR TITLE
[testbed] - Add test cases covering `retry` scenarios with queuing disabled 

### PR DESCRIPTION
**Pull request by VihasMakwana**
**Description:** 
-> This PR adds a new set of correctness test cases for retryable errors.

### CODE REVIEW

**Comment by VihasMakwana** [comment]
@djaglowski can you take a look at this one too, if time permits?

**Comment by fatsheep9146** [comment]
Sorry for delay, I will review this pr soon

**Comment by VihasMakwana** [comment]
@fatsheep9146 Thanks for responding! so you know, this PR is a follow-up of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27251.

**Comment by VihasMakwana** [comment]
@bogdandrutu can you take a look at this?

**Comment by fatsheep9146** [comment]
@VihasMakwana could you check about the failed checks？

**Comment by fatsheep9146** [comment]
Nicely ping @VihasMakwana

**Pull request closed without merging**
