### PR TITLE
[connector/servicegraphconnector]fix README for Supported Pipeline Types

### PR DESCRIPTION
**Pull request by Wudadada**
#### Description
This PR corrects the documentation in the README for servicegraphconnector, updating the Supported Pipeline Types section to accurately describe that the connector receives traces and outputs metrics. This update clarifies the correct pipeline configuration, reducing potential confusion for users.

#### Testing
This change only affects documentation, so no additional tests were needed.

### CODE REVIEW

**Review by JaredTan95 — APPROVED** [review]
nice ctach!

**Review by fatsheep9146 — COMMENTED** [review]
There is a failed ci, could you please check about that? https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/11833665410/job/33020325789?pr=36367
```
Generated code is out of date, please run "make generate" and commit the changes in this PR.
```

**Comment by Wudadada** [comment]
> There is a failed ci, could you please check about that? https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/11833665410/job/33020325789?pr=36367
> 
> ```
> Generated code is out of date, please run "make generate" and commit the changes in this PR.
> ```

I think the branch wasn’t up-to-date when running the CI; I’ve updated it now.

**Comment by Wudadada** [comment]
@fatsheep9146 hi，is there an issue with the CI? When I run 'make generate', it reverts to the original incorrect description.

**Comment by Wudadada** [comment]
After further clarification and re-evaluation, I realized that I misunderstood the definitions of Exporter Pipeline Type and Receiver Pipeline Type for the traces_to_metrics connector.

The correct types are:
	•	Exporter Pipeline Type: traces, as it processes trace data from the traces pipeline.
	•	Receiver Pipeline Type: metrics, as it outputs metrics data to the metrics pipeline.

In the PR, I incorrectly proposed that the Exporter Pipeline Type should be metrics and the Receiver Pipeline Type should be traces, which does not align with the intended functionality of the connector. Therefore, I am closing this PR as it is based on a misunderstanding.

Apologies for any confusion caused, and thank you for reviewing!

**Pull request closed without merging**
