### PR TITLE
honeycomb exporter: don't emit default proc id + starttime

### PR DESCRIPTION
**Pull request by chris-smith-zocdoc**
**Description:** 
Fixes a bug where the honeycomb exporter would emit default values for the process id and process start time

**Testing:** 
Added tests

@lizthegrey @paulosman

### CODE REVIEW

**Comment by chris-smith-zocdoc** [comment]
Unrelated Tests are failing `go unit test ./... + coverage in /home/circleci/project/exporter/carbonexporter`

**Review by paulosman — APPROVED** [review]
LGTM!

**Review by tigrannajaryan — APPROVED** [review]
LGTM

**Comment by tigrannajaryan** [comment]
Please fix the build. honeycombexporter tests are failing.

**Comment by chris-smith-zocdoc** [comment]
@tigrannajaryan sorry about that, pushed a fix.

It looks like the test failed because it was relying on the timezone of machine for its date formatting. Is this something that can be fixed in the honeycomb exporter? 
```
 - 			"opencensus.start_timestamp":             string("2020-09-08T16:15:12-04:00"),
 + 			"opencensus.start_timestamp":             string("2020-09-08T20:15:12Z"),
```

**Pull request merged**
