### PR TITLE
Remove impossible conditions from Unmarshaler

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Please solve the conflicts

**Review by codeboten — COMMENTED** [review]
Please take a look at the conflict

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
@bogdandrutu  looks like some tests need to be updated as well

**Review by JaredTan95 — APPROVED** [review]

**Comment by mx-psi** [comment]
```
2022-11-14T08:31:26.6779986Z     factory_test.go:222: customUnmarshaller() error = result must be addressable (a pointer), wantErr false
```

from `receiver/kubeletstatsreceiver	`

**Review by codeboten — COMMENTED** [review]
@bogdandrutu PTAL

**Review by jpkrohling — APPROVED** [review]

**Pull request closed without merging**
