### PR TITLE
[receiver/<scrapers>] Add several scrapers to components.go

### LINKED ISSUE #9676: [receiver/<scrapers>] Add to components.go
The following scrapers are not under active development and I believe should be included in the contrib release:
- `apachereceiver`
- `couchdbreceiver`
- `elasticsearchreceiver`
- `mongodbreceiver`
- `nginxreceiver`
- `rabbitmqreceiver`

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #9676

### CODE REVIEW

**Comment by djaglowski** [comment]
Supersedes #9572

**Comment by TylerHelmuth** [comment]
Might be out of scope of this PR, but as part of adding these components to components.go, should we also update their READMEs with the appropriate Stability Level (if it needs it). I would expect each component being added to be Alpha or higher.

**Comment by djaglowski** [comment]
@TylerHelmuth, all of these are currently Beta according to their readmes.

**Review by codeboten — COMMENTED** [review]
@djaglowski are you planning on adding these to the releases repo as well?

**Comment by djaglowski** [comment]
@codeboten, that was my plan.

**Comment by djaglowski** [comment]
Load tests are failing in the same way as #9224. The root cause is well described by @cpheps [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9224#issuecomment-1109917053), but basically boils down to the fact that each new component added to the collector increases its memory footprint.

**Comment by djaglowski** [comment]
@codeboten I've rebased after #9684 and load tests are now passing.

**Review by dmitryax — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
