### PR TITLE
[chore] add missing approvers to auto_assign.yml

### PR DESCRIPTION
**Pull request by andrzej-stencel**

### CODE REVIEW

**Comment by crobert-1** [comment]
Note: This PR and #27033 are duplicates of each other. #27033 adds some sorting, so I'd tend to go with that one.

**Comment by bryan-aguilar** [comment]
ha @astencel-sumo and I probably had the same idea after the SIG meeting.

**Comment by bryan-aguilar** [comment]
I have no preference. I shall leave it to the maintainers to close the duplicate.

**Review by codeboten — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by astencel-sumo** [comment]
Superseded by #27033

**Pull request closed without merging**
