### PR TITLE
Move the jaeger thrift http exporter from core to contrib repo

### PR DESCRIPTION
**Pull request by objectiser**
**Description:**
This PR is to enact action item 3 from https://github.com/open-telemetry/opentelemetry-collector/issues/618#issuecomment-597924424. Not sure if possible to preserve history, but this code was copied from [here](https://github.com/open-telemetry/opentelemetry-collector/tree/cfd62511c09366d32d712b5583a77abb8d068deb/exporter/jaeger/jaegerthrifthttpexporter).

**Link to tracking Issue:**
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/618

**Testing:**
Uses existing tests copied from core repo.

**Documentation:**
Text from exporter README (jaeger thrift http section) has been extracted and added to a new README in the exporter's folder.

### CODE REVIEW

**Comment by objectiser** [comment]
The testbed is currently failing due to the duplicate exporter for `jaeger_thrift_http`. Should I change the contrib exporter to `jaeger_thrift`?

**Comment by pjanotti** [comment]
@objectiser just to be 100% sure: no actual code changes just taking the files as they are.

Regarding the error, we can rename it temporarily so we can do the merges on the repos independently, but before we release and tag another contrib we go back to `jaeger_thrift_http` that requires a new tag on core (to be done after the receiver is removed from there). The alternative is to remove first from core publish a new one and then merge this one. I prefer to do the former @tigrannajaryan @owais

**Comment by objectiser** [comment]
> just to be 100% sure: no actual code changes just taking the files as they are.

@pjanotti Yes that is correct.

**Review by pjanotti — CHANGES_REQUESTED** [review]
It actually LGTM @objectiser, just setting as "request changes" so we can coordinate correctly.

**Comment by pjanotti** [comment]
@objectiser could you please push a change with `jaeger_thrift` so we can clean the build? This way we get ready to merge this one.

**Review by pjanotti — APPROVED** [review]
LGTM, could you please rebase @objectiser

**Review by owais — APPROVED** [review]

**Comment by objectiser** [comment]
@pjanotti @owais ready to review/merge.

**Comment by objectiser** [comment]
@pjanotti @owais please review/merge, thanks.

**Pull request merged**
