### PR TITLE
add exemplars support to prometheusremotewriteexporter

### PR DESCRIPTION
**Pull request by anneelisabethlelievre**
Signed-off-by: Anne-Elisabeth Lelievre <anneelisabethwlelievre@hotmail.com>

Hello, this is the implementation of #5192 to support exemplars  for the prometheus remote write exporter.

Thanks

### CODE REVIEW

**Comment by anne-eli** [comment]
I looked at the error in the "build-publish" but I'm not sure to understand how I can resolve this, if anyone can help me with this. thanks :) .

**Review by codeboten — COMMENTED** [review]
Just a few questions. It would be great to get a second review from one of the `awsprometheusremotewriteexporter` codeowners.

Ping @alolita @anuraaga @rakyll

**Review by codeboten — APPROVED** [review]
Thanks for addressing my comments, @anuraaga please review and approve if your comments have been addressed.

**Review by anuraaga — APPROVED** [review]

**Review by gouthamve — COMMENTED** [review]
I'm super new to the code base but I think making sure the traceid label is present in as many exemplars is important. Otherwise the exported exemplars are not very useful in Prometheus.

Other than that, good job! I can't wait to see this merged!

**Comment by anneelisabethlelievre** [comment]
I created this PR [6140](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5578) to fix this in the span metrics processor with the current changes of this PR and everything seems to be ok now when sending metrics to cortex.

**Comment by anneelisabethlelievre** [comment]
> > @anne-eli we are currently having the following errors when sending metrics to Cortex:
> > ```
> > {"level":"error","ts":1635446592.7831264,"caller":"exporterhelper/queued_retry.go:199","msg":"Exporting failed. The error is not retryable. Dropping data.","kind":"exporter","name":"prometheusremotewrite/0/metrics/2","error":"Permanent error: remote write returned HTTP status 400 Bad Request; err = <nil>: exemplar missing labels, timestamp: 0 series: {__name__=\"harbour_tracing_latency_bucket\", le=\"2000\", operation=\"opentelemetrycollector_controller\", service_name=\"fleet-tracing-operator.fleet-system\", span_kind=\"SPAN_KIND_UNSPECIFIED\", status_code=\"STATUS_C","dropped_items":4,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send\n\t/build/vendor/go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:199\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send\n\t/build/vendor/go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:132\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1\n\t/build/vendor/go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry_inmemory.go:105\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.ConsumerFunc.Consume\n\t/build/vendor/go.opentelemetry.io/collector/exporter/exporterhelper/internal/bounded_queue.go:103\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BoundedQueue).StartConsumersWithFactory.func1\n\t/build/vendor/go.opentelemetry.io/collector/exporter/exporterhelper/internal/bounded_queue.go:82"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > maybe related to: #5263
> 
> @secat I'm on it

I created this PR [6140](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5578) to fix this in the span metrics processor with the current changes of this PR and everything seems to be ok now when sending metrics to cortex.

**Review by secat — APPROVED** [review]

**Comment by anneelisabethlelievre** [comment]
Please do not merge this PR, I just found 2 little issues, I'll commit 2 fixes today, thanks.

**Review by codeboten — CHANGES_REQUESTED** [review]
Blocking as requested https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5578#issuecomment-963491531

**Comment by anneelisabethlelievre** [comment]
> Blocking as requested [#5578 (comment)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5578#issuecomment-963491531)

I just pushed some new changes in this PR and here are the 2 changes I added :

1. When we loop through the attributes of the exemplars in the "getPromExemplars" method, I now use the `Range` and `AsString()` to convert an OTLP AttributeValue object of any type to its equivalent string.

before:

```
exemplar.FilteredAttributes().Range(func(key string, value pdata.AttributeValue) bool {
promLabel := prompb.Label{
    Name:  key,
    Value: value.AsString(),
  }
  
  promExemplar.Labels = append(promExemplar.Labels, promLabel)
  
  return true
})
```

now:

```
labels := exemplar.FilteredAttributes().AsRaw()
for key, value := range labels {
  promLabel := prompb.Label{
    Name:  key,
    Value: value.(string),
  }
  
  promExemplar.Labels = append(promExemplar.Labels, promLabel)
}
```

2.  When I tested with this fix: [6140](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6140), this processor now append the exemplar data and does not add a exemplar to a specific bucket index, so now in this exporter, we simply loop through all the examplars that we receive and no longer take the bucket index as a reference. I also realised that the "le" value for an exemplar wasn't correct so in the `addExemplars` func, so to fix that, I scan the bucket bound from the smallest to the biggest and add the exemplar to the first bound where it is smaller than the bound.

Finally, I re-tested sending to prometheus and cortex and everything looks ok now. In prometheus, the "le" values are ok now.

image

I know some unit tests are failing but I don't thinks so this is not related to my changes.

cc: @codeboten

**Review by codeboten — APPROVED** [review]
Thanks for the fixes @anneelisabethlelievre! You're right the failures are unrelated.

**Pull request merged**
