### PR TITLE
[processor/resourcedetection] Add EKS cluster name subsection in README

### LINKED ISSUE #34139: Documentation missing example config for enabling k8s.cluster.name in EKS
### Component(s)

processor/resourcedetection

## Description
The current documentation for the Resource Detection Processor indicates that the attribute `k8s.cluster.name` is fetched by the EKS detector.
>     * cloud.provider ("aws")
>     * cloud.platform ("aws_eks")
>     * k8s.cluster.name

This may be misleading as the retrieval of `k8s.cluster.name` is actually disabled by default (unlike `cloud.provider` and `cloud.platform`), but this is not indicated anywhere in the documentation. The example configuration provided also does not clarify how it can be enabled.

## Steps to Reproduce
Use the example configuration for EKS provided in the document to install opentelemetry-collector:
```yaml
processors:
  resourcedetection/eks:
    detectors: [env, eks]
    timeout: 15s
    override: false
```

## Expected Result
The opentelemetry-collector indicates that it has retrieved the value `k8s.cluster.name`:
```
info	internal/resourcedetection.go:139	detected resource information	{"kind": "processor", "name": "resourcedetection/eks", "pipeline": "logs", "resource": {"cloud.platform":"aws_eks","cloud.provider":"aws","k8s.cluster.name":"<cluster-name>"}}
```

## Actual Result
The opentelemetry-collector does not retrieve `k8s.cluster.name`:
```
info    internal/resourcedetection.go:139    detected resource information    {"kind": "processor", "name": "resourcedetection/eks", "pipeline": "traces", "resource": {"cloud.platform":"aws_eks","cloud.provider":"aws"}}
```

### Collector version

0.103.1

### Environment information

Helm Chart: [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/opentelemetry-collector-0.95.0/charts/opentelemetry-collector)
Version: 0.95.0

### OpenTelemetry Collector configuration

```yaml
exporters:
  otlphttp:
    endpoint: <redacted>
    tls:
      insecure: false
      insecure_skip_verify: false
processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 10000
    timeout: 1s
  k8sattributes:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection/eks:
    detectors: [env, eks]
    timeout: 15s
    override: false
receivers:
  jaeger: null
  prometheus: null
  zipkin: null
service:
  pipelines:
    logs:
      exporters: [otlphttp]
      processors: [memory_limiter, k8sattributes, batch, resourcedetection/eks]
      receivers: [otlp]
    metrics:
      exporters: [otlphttp]
      processors: [memory_limiter, k8sattributes, batch, resourcedetection/eks]
      receivers: [otlp]
    traces:
      exporters: [otlphttp]
      processors: [memory_limiter, k8sattributes, batch, resourcedetection/eks]
      receivers: [otlp]
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aaajhs**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34139

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please sign the CLA

**Comment by aaajhs** [comment]
@songy23 Done

**Review by songy23 — APPROVED** [review]
LGTM

**Review by mwear — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]

**Review by ChrsMark — APPROVED** [review]
While adding this example is indeed useful I think the motivation for it surfaces a more generic issue. That has to do with how intuitive and useful is the current format of the attributes' documentation. Users reading the main `README.md` have to head to the `metadata.yaml` files to look for more precise "documentation". Not all users might be familiar with this though.
Maybe having an autogenerated `.md` file listing all the attributes like how it's done in the receivers' docs would be useful?

**Comment by codeboten** [comment]
> While adding this example is indeed useful I think the motivation for it surfaces a more generic issue. That has to do with how intuitive and useful is the current format of the attributes' documentation. Users reading the main `README.md` have to head to the `metadata.yaml` files to look for more precise "documentation". Not all users might be familiar with this though. Maybe having an autogenerated `.md` file listing all the attributes like how it's done in the receivers' docs would be useful?

@ChrsMark I agree, can you open an issue to add this mdatagen?

**Review by codeboten — APPROVED** [review]

**Pull request merged**
