### PR TITLE
[chore][pkg/translator/azure] Add missing code owner @cparkins

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

This fixes inconsistency introduced with the creation of this package. In #25096 @cparkins was added as a code owner in the [metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/azure/metadata.yaml) but not the top level `CODEOWNERS` file.

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
Change looks good, is the PR in the description correct? It looks like metadata was only modified in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25096

**Comment by cparkins** [comment]
Oops! I saw this and didn't change it.

**Comment by crobert-1** [comment]
> Change looks good, is the PR in the description correct? It looks like metadata was only modified in #25096 

Corrected it to #25096, thanks for catching!

**Comment by atoulme** [comment]
Might need to add him to cmd/githubgen/allowlist.txt as well since he's not a member yet.

**Comment by TylerHelmuth** [comment]
@cparkins can you approve the PR if you agree with being added as a code owner?

**Review by cparkins — APPROVED** [review]

**Comment by cparkins** [comment]
@TylerHelmuth - Done! Wasn't even aware I could approve or how to do it 👍

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
