### PR TITLE
Add skywalking log exporter - part 2

### PR DESCRIPTION
**Pull request by liqiangz**
Description: This PR follows #4956 --  the concrete implementation of the component

Link to tracking Issue: apache/skywalking#6209

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
You seem to be missing some tests for the newly added code to the main code. I would like to see a few tests, especially for the client-side stream pooling.

**Comment by wu-sheng** [comment]
@liqiangz Thanks for adding this. Once this is merged, please update SkyWalking's log doc, https://skywalking.apache.org/docs/main/latest/en/setup/backend/log-analyzer/#log-files-collector, which will show up at https://skywalking.apache.org/docs/main/latest/en/setup/backend/log-analyzer/#collection.

Please list `OpenTelemetry Log Exporter` as another new source, and targeting to docs on OTEL's website or GitHub's readme.

**Review by jpkrohling — COMMENTED** [review]
I would like to get the NumStreams logic out of this PR for now, discussing it in a separate issue. If we see that it does bring benefits, we can try to have it applied more generically.

**Comment by jpkrohling** [comment]
I mean to not use a custom made connection pool, like this:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b9ce2c4a3b142260227b392d6d99da80347b97b4/exporter/skywalkingexporter/skywalking.go#L99-L113

Unless another maintainer is familiar with this pattern. @bogdandrutu, @tigrannajaryan), would you mind looking at this part of the PR?

**Comment by tigrannajaryan** [comment]
>Unless another maintainer is familiar with this pattern. @bogdandrutu, @tigrannajaryan), would you mind looking at this part of the PR?

I haven't reviewed the code in details but at a glance it appears to open a fixed number of concurrent gRPC streams and uses round-robin over the streams to send the requests over the streams. This is fairly standard and typically increases the throughput, potentially at the cost of higher CPU usage per unit of data. One gRPC stream typically does not saturate the bandwidth in my experiments. For tiny requests I saw up to 3-4x throughput increase with concurrent streams.

I think it is fine if high throughput is the goal (is it?).

Make sure you don't do any queueing or retrying yourself and just rely on queued_retry to do its job.

I hope I am reading the code correctly. Correct me if I misunderstood something.

**Comment by liqiangz** [comment]
> I haven't reviewed the code in details but at a glance it appears to open a fixed number of concurrent gRPC streams and uses round-robin over the streams to send the requests over the streams. This is fairly standard and typically increases the throughput, potentially at the cost of higher CPU usage per unit of data. One gRPC stream typically does not saturate the bandwidth in my experiments. For tiny requests I saw up to 3-4x throughput increase with concurrent streams.
> 
> I think it is fine if high throughput is the goal (is it?).
> 
> Make sure you don't do any queueing or retrying yourself and just rely on queued_retry to do its job.
> 
> I hope I am reading the code correctly. Correct me if I misunderstood something.

@jpkrohling  Based on the comments above, do I still use stream pooling or remove it?

**Comment by jpkrohling** [comment]
@tigrannajaryan, thank you for your insight!

> do I still use stream pooling or remove it?

It's fine to keep it.

**Comment by jpkrohling** [comment]
Tests restarted. I'll merge this once it passes the CI, but please make sure to create an issue to track the conversion of the benchmark to a real benchmark. Or remote it, as this was mostly useful for checking whether the performance would be better with multiple go routines to send data.

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
