### PR TITLE
rename NewParser* -> NewConfigMap*

### PR DESCRIPTION
**Pull request by codeboten**
Follow up to core pr: https://github.com/open-telemetry/opentelemetry-collector/pull/4032

### CODE REVIEW

**Comment by bogdandrutu** [comment]
This needs an update for the collector.

**Comment by bogdandrutu** [comment]
@codeboten build fails

**Comment by codeboten** [comment]
I re-ran `make update-otel` and pushed the new changes. Not sure what caused the build to fail initially.

**Review by mx-psi — APPROVED** [review]

**Comment by codeboten** [comment]
Ah i see whats happening now. The tests are failing because of this issue https://github.com/open-telemetry/opentelemetry-collector/issues/4043

**Pull request merged**
