### PR TITLE
kafka-compression-config: Expose compression configs for kafka exporter #6079

### PR DESCRIPTION
**Pull request by Sprakhar97**
**Description:**
Exposing compression codec and compression level as configs to the user in order to leverage compression options available in kafka producer.
**Link to tracking Issue:** 
#6079

### CODE REVIEW

**Comment by Sprakhar97** [comment]
@codeboten can you please approve the workflows.

**Comment by bputt-e** [comment]
Does this compete with PR #7385

**Comment by bputt-e** [comment]
@codeboten can you please approve the workflows.

**Comment by codeboten** [comment]
@bputt-e it wasn't clear from the conversation here whether this PR conflicts with #7385, I was waiting to hear back from @Sprakhar97

**Pull request closed without merging**
