### PR TITLE
[receiver/k8scluster] Disable flaky TestReceiver

### PR DESCRIPTION
**Pull request by jpkrohling**
See #9002

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Linter failed.

**Comment by djaglowski** [comment]
Ironically, another [flaky test](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6020707052?check_suite_focus=true#step:8:1167) failed. (Disabled in #9255)

**Review by djaglowski — COMMENTED** [review]
The error presented on this PR, but on a different test, [TestReceiverTimesOutAfterStartup](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6038443724?check_suite_focus=true#step:8:16418) and was previously noted to have occurred on [TestFactory](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6986) as well.

We can disable tests one at a time, but it seems skipping individual tests may not avoid the flakiness in this case.

**Comment by jpkrohling** [comment]
I'm changing this to draft, as #9332 might help here.

**Comment by jpkrohling** [comment]
Closing, as not sure this is still relevant after all the cleaning we did already.

**Pull request closed without merging**
