### PR TITLE
AzureMonitorExporter - Populate ai.cloud.role and ai.cloud.roleinstance correctly

### PR DESCRIPTION
**Pull request by youngbupark**
## Description

**Problem:** TL;DR; azuremonitorexporter does not populate ai.cloud.instance and ai.cloud.roleinstance.

**Root cause:** azuremonitorexporter creates exporter using [NewTraceExporterOld](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/azuremonitorexporter/traceexporter.go#L714) for opencensus tracedata. [resource to oc translator](https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/internaldata/resource_to_oc.go#L54) converts provider's resource attributes to opencensus' `Node.ServiceInfo`, `Node.Identifier`, and `Resource.Labels`, but previous exporter implementation looked up only `Node.Attributes` map field to get `service.name`, `service.namespace`, and `service.instance.id`. These attributes do not exist `traceData.Node.Attributes` map.

**Fix:**
* Use `traceData.Node.ServiceInfo.Name` for [ai.cloud.role](https://github.com/microsoft/ApplicationInsights-dotnet/blob/master/NETCORE/Schema/PublicSchema/ContextTagKeys.bond#L85)
* Use `traceData.Node.Identifier.HostName` for [ai.cloud.roleinstance](https://github.com/microsoft/ApplicationInsights-dotnet/blob/master/NETCORE/Schema/PublicSchema/ContextTagKeys.bond#L89) - Previous code refers to wrong attribute, service.instance.id, which is not machine name.
* Extract service.namespace from `traceData.Resource.Labels`

## Link to tracking Issue

#187 

### End-To-End test - the below flows are working as expected.
1. opentelemetry-go 0.5.0 sdk + oltp exporter -> otel collector
2. opentelemetry-go 0.5.0 sdk + jaeger exporter -> otel collector
3. opentelemetry-dotnet master branch + jaeger exporter -> otel collector

### Unit-test
1. Populate no attributes to envelope if no resource attributes are given
2. Populate `service.name` and `host.hostname` resource attributes to `ai.cloud.role` and `ai.cloud.roleinstance` in envelope
3. Populate `service.namespace` and custom resource attributes to envelope

**Documentation:** N/A

### CODE REVIEW

**Comment by youngbupark** [comment]
I signed it

**Comment by bogdandrutu** [comment]
@youngbupark it looks that something is not working with the CLA.

**Comment by youngbupark** [comment]
> @youngbupark it looks that something is not working with the CLA.

Yeah I will sign up by tomorrow.

**Comment by youngbupark** [comment]
@bogdandrutu All checks, including CLA, have passed now.

**Comment by youngbupark** [comment]
@SergeyKanzhelev @pcwiese @bogdandrutu Can you please review this pr ? 

I have validated the below combinations: 
* opentelemetry-go 0.5.0 sdk + oltp exporter -> otel collector
* opentelemetry-go 0.5.0 sdk + jaeger exporter -> otel collector
* opentelemetry-dotnet master branch + jaeger exporter -> otel collector

ai.cloud.role and ai.cloud.roleinstance are propagated as expected.

**Review by pcwiese — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
