### PR TITLE
[exporter/loki] Don't auto-promote tenant attribute

### LINKED ISSUE #21045: [exporter/loki]: Attribute used as hint always added as loki label
### Component(s)

exporter/loki

### Describe the issue you're reporting

It seems like when I add a hint for org-id using `loki.tenant` it also becomes added as a loki label. This seems like an unnecessary overhead since it will always have the same value for the same tenant. 

For example if I use the `k8s.namespace.name` resource attribute for `loki.tenant` it will also add a loki label called `k8s_namespace_name` which will always have the same value within the tenant.

```yaml
processors:
  resource/loki_tenant_from_k8s_namespace:
    attributes:
    - action: insert
      key: loki.tenant
      value: k8s.namespace.name
```

Is automatcially adding a loki label for the `loki.tenant` hint value expected behavior or do I have a misconfiguration?

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #21045

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@mar4uk, @gouthamve, I have to fix other tests, but can you please take a look at the tests that are part of this PR and confirm this is how we want to convert OTLP to Loki? I think it makes sense, but I would like a second opinion.

**Comment by mar4uk** [comment]
I think it makes sense 👍

**Comment by jpkrohling** [comment]
@mar4uk, this is now ready for review.

**Review by mar4uk — APPROVED** [review]

**Comment by jpkrohling** [comment]
@dmitryax got auto-assigned when I first opened, the others are code owners. I then marked this as draft, and you got assigned when I marked as ready again. Perhaps a bug on our GHA on assigning reviewers?

**Review by evan-bradley — APPROVED** [review]

**Pull request merged**
