### PR TITLE
Remove usage of GitHash in AWS components, planing to remove it, included in version

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by bogdandrutu** [comment]
It is already included in the version, see https://github.com/open-telemetry/opentelemetry-collector/pull/2992 and https://github.com/open-telemetry/opentelemetry-collector/pull/2388

**Comment by mxiamxia** [comment]
Thanks. It's fine to be removed and `version` is enough.

**Review by mxiamxia — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]
LGTM since the version would include the same info. I'll make sure this is communicated to the team working on adding what would have been another use of it before they put up a PR.

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
