### PR TITLE
Improvements to the awsprometheusremotewriteexporter

### PR DESCRIPTION
**Pull request by rakyll**
- Improvements to language and formatting
- Providing a realistic workspace URL
- Removing sending_queue due to lack of support
- aws_auth.service has to be always "aps", removing it from documentation
- Adding a note that aws_auth.region has to match the workspace region
- Documenting aws_auth.role_arn

Related to https://github.com/open-telemetry/opentelemetry-collector/pull/2951

### CODE REVIEW

**Comment by rakyll** [comment]
cc @odeke-em

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @rakyll!

**Comment by rakyll** [comment]
This change relies on https://github.com/open-telemetry/opentelemetry-collector/pull/2951.

**Comment by rakyll** [comment]
Removed the dependency to open-telemetry/opentelemetry-collector#2951, this is ready for review.

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
