### PR TITLE
[receiver/kafkametrics] Fix issue with incorrect consumer offset

### LINKED ISSUE #33309: [receiver/kafkametrics] Kafka consumer offset gives a random value instead of an actual offset
### Component(s)

receiver/kafkametrics

## Description

It seems there is an issue in the code:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kafkametricsreceiver/consumer_scraper.go#L145

For the consumer offset (`RecordKafkaConsumerGroupOffsetDataPoint`) it should send `consumerOffset` instead of `offsetSum`.

## Steps to Reproduce

0) Precondition: having Kafka topic with more than 1 partition.
1) Run the receiver, use debug output.
2) Compare Kafka consumer offset metrics with actual in the Kafka ui.

## Expected Result

The Kafka consumer offset represent actual consumer offset value

## Actual Result

We can see that consumer offset value doesn't match with the actual value from Kafka ui.

### Collector version

v0.101.0

## Environment
Any

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by an-mmx**
Fixes: #33309 

**Description:** Fix issue when consumer offset store random value

**Link to tracking Issue:** none

**Testing:** none

**Documentation:** none

### CODE REVIEW

**Review by samiura — APPROVED** [review]

**Comment by an-mmx** [comment]
> Please add a changelog. Any chance you can add a test as well?

Changelog added. 
As for the tests, unfortunately, I'm not so much matur in golang.

**Comment by an-mmx** [comment]
ping

**Comment by an-mmx** [comment]
@dmitryax ping

**Review by atoulme — APPROVED** [review]
Approved as @samiura has reviewed and approved.

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
