### PR TITLE
[receiver/dockerstat] fix integration tests

### PR DESCRIPTION
**Pull request by gsanchezgavier**
**Description:** <Describe what has changed.>

While diving into this receiver integration test I noticed this issue:
- The assertion logic of `TestDefaultMetricsIntegration` and `TestAllMetricsIntegration`, `TestMonitoringAddedContainerIntegration` falsely passed, even if there were no containers running, I removed the container creation on the first 3 tests and the test passed.
  - I have added a more strict assert function.

I have also 
- `TestDefaultMetricsIntegration` and `TestAllMetricsIntegration` were testing the same behavior.
  - I have removed `TestAllMetricsIntegration`
- The asserts mechanism didn't allow running them in Parallel with independence.
  - new assert check metrics related to the `container.id` generated for the test.
- The behavior in `TestRemovedContainerRemovesRecordsIntegration` could be tested in a similar way as the `TestMonitoringAddedContainerIntegration`
  - I have removed the test and added it as part of `TestMonitoringAddedAndRemovedContainerIntegration`

**Link to tracking Issue:** <Issue number if applicable>
While it is not completely related I discovered this while working on #21097 
**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>
From what I understood from the contrib guide this PR would not require an entry in the changelog since it is not user related, but let me know if I'm mistaken.

### CODE REVIEW

**Review by MovieStoreGuy — APPROVED** [review]
Thank you for fixing this issue!

Pinging @jamesmoessis , @rmfitzpatrick as code owners to make sure they are okay with the change.

**Comment by MovieStoreGuy** [comment]
When you get a chance @gsanchezgavier , please have a look at the linter and test output.

Considering this is just changing tests, I am happy to skip the changelog here.

**Comment by gsanchezgavier** [comment]
Thanks, fixed the lint issues, not sure what you mean by test output, I saw they were[ passing on the CI](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4786839471/jobs/8517041298?pr=21110#step:5:112)
```sh
go test -race -timeout 360s -parallel 4 -tags=integration,"" -run=Integration -coverprofile=integration-coverage.txt -covermode=atomic ./...
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver	11.168s	coverage: 81.9% of statements
```

**Comment by MovieStoreGuy** [comment]
> Thanks, fixed the lint issues, not sure what you mean by test output, I saw they were[ passing on the CI](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4786839471/jobs/8517041298?pr=21110#step:5:112)
> 
> ```shell
> go test -race -timeout 360s -parallel 4 -tags=integration,"" -run=Integration -coverprofile=integration-coverage.txt -covermode=atomic ./...
> ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver	11.168s	coverage: 81.9% of statements
> ```
I was meaning the linting step :)

**Comment by MovieStoreGuy** [comment]
Could I ask you to rebase your branch against main again. Not exactly sure as to why the deb package is failing to build.

**Comment by gsanchezgavier** [comment]
I updated the branch, 
Pinging @jamesmoessis in case this PR notification got lost, thanks!

**Review by TylerHelmuth — APPROVED** [review]

**Comment by jamesmoessis** [comment]
Sorry @gsanchezgavier, I did miss this notification. Thanks for fixing the issue!

**Pull request merged**
