### PR TITLE
[processor/deltatocumulative]: mdatagen telemetry

### LINKED ISSUE #33573: Migrate otel metrics to use mdatagen: deltatocumulative processor

### PR DESCRIPTION
**Pull request by tombrk**
**Description:** <Describe what has changed.>

Uses recently introducted `telemetry:` feature of `mdatagen` to define the internal telemetry exported from this component.

Leaves the general `telemetry` package in-place, as it also does error handling (for now). Changing so requires a deeper refactor that will be done later

**Link to tracking Issue:** 
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33573

**Testing:** not needed

**Documentation:** changed to auto-generated

### CODE REVIEW

**Comment by sh0rez** [comment]
no changelog needed imo

**Review by codeboten — APPROVED** [review]
Awesome, thanks @sh0rez!

**Comment by codeboten** [comment]
Looks like some linting is still needed. Please update the description to include the following to automatically close the issue:

Fixes #33573

**Review by codeboten — APPROVED** [review]
Thanks @sh0rez

**Pull request merged**
