### PR TITLE
Update Prometheus to main

### PR DESCRIPTION
**Pull request by gouthamve**
I'm trying to implement OTLP receive endpoint in Prometheus and ran into incompatible types.

Basically this PR: https://github.com/prometheus/prometheus/pull/11935 was merged 3 days after the last release 😭

Error encountered:
```
../../../../pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.71.0/histograms.go:90:19: cannot use pSpans (variable of type []*prompb.BucketSpan) as type []prompb.BucketSpan in struct literal
../../../../pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.71.0/histograms.go:92:19: cannot use nSpans (variable of type []*prompb.BucketSpan) as type []prompb.BucketSpan in struct literal
```

But this makes me concerned. If I succeed in getting an OTLP endpoint merged into Prometheus, it means there is a circular dependency now.

`pkg/translator/prometheusremotewrite` imports `prometheus/prometheus` and `prometheus/prometheus` will import `pkg/translator/prometheusremotewrite`.

Not sure how to solve the dependency. Will speak to Prometheus team as well.

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Not sure if you'll run into the same problem, but here's an issue i raised when i tried to update the prom dependency at the beginning of the week: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18403

**Comment by gouthamve** [comment]
Hrm, all the tests are passing now (well except an unrelated load-test). I am not sure it is still a problem @codeboten

**Comment by kovrus** [comment]
> Hrm, all the tests are passing now (well except an unrelated load-test). I am not sure it is still a problem @codeboten

That test will be dropped  by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18519

**Review by codeboten — COMMENTED** [review]
@kovrus is right, @gouthamve please rebase to pick up the change to remove that test

**Comment by gouthamve** [comment]
@codeboten done!

**Review by codeboten — APPROVED** [review]

**Pull request merged**
