### PR TITLE
[*/datadog] bump opentelemetry-mapping-go to v0.9.0

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** <Describe what has changed.>

Bump opentelemetry-mapping-go modules to v0.9.0. This includes:

- DataDog/opentelemetry-mapping-go/pull/218 and DataDog/opentelemetry-mapping-go/pull/220
- DataDog/opentelemetry-mapping-go/pull/219
- DataDog/opentelemetry-mapping-go/pull/213
- DataDog/opentelemetry-mapping-go/pull/202

### CODE REVIEW

**Comment by mx-psi** [comment]
cc @mackjmr @liustanley

**Review by songy23 — COMMENTED** [review]
~~Should be superseded by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29774~~

NVM the changelogs are still needed.

**Review by liustanley — APPROVED** [review]
LGTM for these two changes:
https://github.com/DataDog/opentelemetry-mapping-go/pull/213
https://github.com/DataDog/opentelemetry-mapping-go/pull/202

**Review by songy23 — APPROVED** [review]
Please rebase after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29774 is merged. Currently blocked by the v0.50.0-rc.7 deps upgrade.

**Review by mackjmr — APPROVED** [review]

**Pull request merged**
