### PR TITLE
[pkg/pdatatest] support Profiles signal comparison

### LINKED ISSUE #36232: [pkg/pdatatest] Support profiles signal comparison
### Component(s)

pkg/pdatatest

### Is your feature request related to a problem? Please describe.

With introduction of profiles signal, we should add the adequate functionality also for profiles signal comparison library for testing.

### Describe the solution you'd like

Add `CompareSignals` function same as it's done for other signal types

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by odubajDT**
#### Link to tracking issue
Fixes #36232

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
It would be great to have someone familiar with profiles review this too.

**Comment by odubajDT** [comment]
> It would be great to have someone familiar with profiles review this too.

I am still adding `CompareOptions` + unit tests to be sure everything is working as expected. But a pre-review would be very appreciated!

**Comment by odubajDT** [comment]
@mx-psi could you have a look please ?

**Review by mx-psi — APPROVED** [review]
This looks reasonable to me. @dmathieu could you also take a look?

**Comment by mx-psi** [comment]
@odubajDT can you fix the merge conflicts?

**Review by dmathieu — APPROVED** [review]

**Pull request merged**
