### PR TITLE
[receiver/mysqlreceiver] Add integration test

### PR DESCRIPTION
**Pull request by Mrod1598**
**Description:** <Describe what has changed.>
Added integration test to mysqlreceiver.

### CODE REVIEW

**Comment by djaglowski** [comment]
@Mrod1598 Please fix lint

**Comment by Mrod1598** [comment]
> @Mrod1598 Please fix lint

fixed with merge from master

**Comment by djaglowski** [comment]
@Mrod1598, the tests are not yet being run. Please add `mysqlreceiver` to `INTEGRATION_TEST_MODULES` in the root `Makefile`.

**Comment by djaglowski** [comment]
Confirmed tests run and pass.
```
make -C receiver/mysqlreceiver do-integration-tests-with-cover
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mysqlreceiver'
running go integration test ./... + coverage in /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mysqlreceiver
=== RUN   TestMySqlIntegration
=== RUN   TestMySqlIntegration/Running_mysql_version_8.0
=== PAUSE TestMySqlIntegration/Running_mysql_version_8.0
=== RUN   TestMySqlIntegration/Running_mysql_version_5.7
=== PAUSE TestMySqlIntegration/Running_mysql_version_5.7
=== CONT  TestMySqlIntegration/Running_mysql_version_8.0
=== CONT  TestMySqlIntegration/Running_mysql_version_5.7
2021/12/21 16:38:16 Starting container id: 5ebfadf5e36f image: testcontainers/ryuk:0.3.3
2021/12/21 16:38:16 Waiting for container id 5ebfadf5e36f image: testcontainers/ryuk:0.3.3
2021/12/21 16:38:16 Container is ready id: 5ebfadf5e36f image: testcontainers/ryuk:0.3.3
2021/12/21 16:38:42 Starting container id: 5530711bf58f image: a72c930f-55f5-4642-a394-669db4e36f16:7be6a59b-985c-4186-870e-8c64990ffb80
2021/12/21 16:38:42 Starting container id: f0cf450e8e75 image: 872d9f8f-4371-463a-834d-a266de631a96:3fe53ada-decc-43ab-9230-ac8125589c85
2021/12/21 16:38:42 Waiting for container id 5530711bf58f image: a72c930f-55f5-4642-a394-669db4e36f16:7be6a59b-985c-4186-870e-8c64990ffb80
2021/12/21 16:38:42 Waiting for container id f0cf450e8e75 image: 872d9f8f-4371-463a-834d-a266de631a96:3fe53ada-decc-43ab-9230-ac8125589c85
2021/12/21 16:38:54 Container is ready id: 5530711bf58f image: a72c930f-55f5-4642-a394-669db4e36f16:7be6a59b-985c-4186-870e-8c64990ffb80
2021/12/21 16:38:56 Container is ready id: f0cf450e8e75 image: 872d9f8f-4371-463a-834d-a266de631a96:3fe53ada-decc-43ab-9230-ac8125589c85
--- PASS: TestMySqlIntegration (0.00s)
    --- PASS: TestMySqlIntegration/Running_mysql_version_5.7 (50.43s)
    --- PASS: TestMySqlIntegration/Running_mysql_version_8.0 (51.97s)
PASS
coverage: 94.4% of statements
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver	52.032s	coverage: 94.4% of statements
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mysqlreceiver/internal/metadata	[no test files]
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/mysqlreceiver'
```

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
