### PR TITLE
chore: update InfluxDB dependencies

### PR DESCRIPTION
**Pull request by jacobmarble**
**Description:**
When converting from OTel to line protocol with either of the Prometheus-style schemata, we follow the [OTel guidance for Prometheus](https://github.com/open-telemetry/opentelemetry-specification/blob/49a3a1add39c74c659467c8b2a44efc3e1bb23eb/specification/metrics/datamodel.md#otlp-metric-points-to-prometheus). Specifically:

>    OpenTelemetry Sums follows this logic:
>    ...
>    If the aggregation temporality is cumulative and the sum is non-monotonic, it MUST be converted to a Prometheus Gauge.

**Link to tracking Issue:** <Issue number if applicable>

https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/8341
https://github.com/influxdata/influxdb-observability/issues/50
https://github.com/influxdata/influxdb-observability/pull/51

**Testing:** <Describe what testing was performed and which tests were added.>
Tests added to dependencies (see PR 51 above) and no change to otelcontribcol in this PR.

**Documentation:** <Describe the documentation added.>
None needed. This is a bug fix.

### CODE REVIEW

**Comment by pmm-sumo** [comment]
Seems that linter failed:

```
go: downloading github.com/influxdata/influxdb-observability/influx2otel v0.2.14
go: updates to go.mod needed; to update it:
	go mod tidy
```

Also, changelog entry is missing

**Comment by codeboten** [comment]
> Also, changelog entry is missing

This change is probably ok without changelog. I've added the label to it

**Comment by codeboten** [comment]
> This change is probably ok without changelog. I've added the label to it

This is just based on the title of the PR. According to the description this is also a bugfix... If it's the latter, please add a changelog, if the former, please update the description :)

**Comment by jacobmarble** [comment]
> please add a changelog
Done.

> Seems that linter and unittest failed
I found `make gotidy` and `make golint`. Let's see if this helps.

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
