### PR TITLE
Span event filter 

### PR DESCRIPTION
**Pull request by purkhusid**
**Description:** Span event filter processor
Adds a new filter to the filterprocessor which allows filtering span events

The span events can be filtered by attributes and names

**Testing:**
* Added tests for the processor logic
* Added tests for config

**Documentation:**
The documentation was updated with an example and there are examples in `testdata`

### CODE REVIEW

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
@punya please decide on the final configuration for the filtering.

**Comment by jharley** [comment]
This would be great functionality to have added. I'm curious if it could be extended to also be able to filter "[Span Events](https://opentelemetry.io/docs/go/instrumentation/#events)" (as opposed to just events that are Spans)? It would be great to match and remove unwanted Span Events added by auto-instrumentation (Istio and Envoy, most notably)

**Comment by purkhusid** [comment]
@jharley That is exactly what this does. And funnily enough filtering Istio/Envoy span events is also the exact use case I had when I created this.

**Comment by jharley** [comment]
> That is exactly what this does

Amazing! Thank you for contributing it: my apologies for misreading. I clearly need more coffee this morning. 😊

**Comment by CVirus** [comment]
This is still needed if you ask me.

**Pull request closed without merging**
