### PR TITLE
[exporter/datadog] Fix canceling on `createTracesExporter`

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** <Describe what has changed.>

Fixes a bug introduced in #9426 where a context is incorrectly canceled via `defer` instead of being canceled only when the function errors out.

It was spotted by @gbbr on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9426#discussion_r866521743.

Since this has not been out on any release, no changelog note is needed.

### CODE REVIEW

**Comment by mx-psi** [comment]
I am marking this as a blocker since it affects the Datadog exporter functionality (missing host metadata).

**Review by gbbr — APPROVED** [review]
👍🏻

**Comment by mx-psi** [comment]
Ci failure is unrelated: trying to fix on #9799

**Review by KSerrania — APPROVED** [review]

**Comment by mx-psi** [comment]
@djaglowski we need this to be merged before Wednesday, since this addresses an important bug that would land on the next release otherwise. Could you have a look?

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
