### PR TITLE
[processor/tailsampling] fix `InvertNotSampled` decision precedence when inside and sub policy

### PR DESCRIPTION
**Pull request by jamesrwhite**
**Description:**

This fixes the handling of AND policies that contain a sub-policy with invert_match=true. Previously if the decision from a policy evaluation was `NotSampled` or `InvertNotSampled` it would return a `NotSampled` decision regardless, effectively downgrading the result.

This was breaking the documented behaviour that inverted decisions should take precedence over all others.

This is related to the changes made in open-telemetry/opentelemetry-collector-contrib#9768 that introduced support for using invert_match within and sub policies.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33656

**Testing:**

I tested manually that this fixes the issue described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33656 and also updated the tests. If you have any suggestions for more tests we could add let me know.

**Documentation:**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Thank you for the PR! This might need a changelog entry: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-a-changelog-entry

**Review by jpkrohling — APPROVED** [review]

**Comment by jamesrwhite** [comment]
@jpkrohling I've added a changelog entry but I wasn't sure whether to classify this as a breaking change or not? The behaviour now matches the documentation with this change but it could be a breaking change for people if they were relying on the old behaviour.

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
I believe this is a bug fix.

**Comment by karinhawk** [comment]
We implemented tail sampling using v0.100.0 of the collector, and want to upgrade to the latest version, but have encountered being unable to replicate behaviour we took from the documentation examples of this repo (namely, the backwards compatibility policy) since that upgrade.

It seems that since v0.104.0 when this bug fix was merged that behaviour is no longer possible. I believe that the documentation examples are now not representative of the possible sampling decisions, which is misleading.

We liked the pattern of being able to sample everything but an array of services, which you would then create policies on what traces to keep from those services, as it made for a lean set of policies.

Our sampling used to work with the following, but now does not, as the "inverted not sample decision" is taking precedence over every subsequent "sample" or "not sample" policy made for those services - meaning those services will always NOT be sampled:

```
      {
        name: 'backwards-compatibility-policy',
        type: 'and',
        and: {
          and_sub_policy: [
            {
              name: 'services-using-tail_sampling-policy',
              type: 'string_attribute',
              string_attribute: {
                key: 'service.name',
                values: [
                  'otel-demo*',
                ],
                invert_match: true,
                enabled_regex_matching: true,
              },
            },
            {
              name: 'sample-all-policy',
              type: 'always_sample',
            },
          ],
        },
      },
       ...subsequent policies sampling the 'otel-demo' services
```
Keeping backwards compatibility with sampling services not ready to implement tail sampling at 100% is extremely important to us as we have such a large estate.

I understand this bug fix was needed, but would love some help to see if this behaviour can in fact be replicated after this change - it was working so well for us!

**Comment by jpkrohling** [comment]
@karinhawk, we have another issue covering this, right?

**Pull request merged**
