### PR TITLE
[internal/coreinternal] Supports pattern for delete and hash actions on attraction

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**
Add supportfor `pattern` configuration for `delete` and `hash` actions to attribute attraction 

**Link to tracking Issue:**
N/A

**Testing:**
unit tests

**Documentation:**
update README, incode docs

### CODE REVIEW

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
@punya please finalize the configuration for "transformation" processors.

**Comment by pmalek-sumo** [comment]
This is not `stale`. Any chance we can move forward with this? Is there any work we can help with? @punya @bogdandrutu

**Comment by punya** [comment]
@anuraaga has been working on transformation config DSL.

**Comment by astencel-sumo** [comment]
We still don't have a definite answer on what should happen with this proposed change. Should this pull request be closed because there is a conflicting proposed change?

**Comment by pmalek-sumo** [comment]
Still not stale. @punya @anuraaga any progress with DSL?

Can we help with this perhaps?

**Comment by jpkrohling** [comment]
@sumo-drosiek, what's the state of this one?

**Comment by pmalek-sumo** [comment]
> @sumo-drosiek, what's the state of this one?

Hi @jpkrohling 👋 

@sumo-drosiek is out for the next couple of weeks. The PR seems to have been complete from our PoV but @bogdandrutu commented that there is some work w.r.t DSL which should be used here.

I wanted to bring this subject on Agent's SIG (unfortunately I won't be able to join today though) so that we can pick this up and make some progress.

**Comment by jpkrohling** [comment]
That's fine, thanks for the status update.

**Pull request closed without merging**
