### PR TITLE
[testbed] Add zstd compression end-to-end tests for OTLP/HTTP

### PR DESCRIPTION
**Pull request by tigrannajaryan**

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Test failed as expected https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5315184475/jobs/9623279446?pr=23456

**Comment by tigrannajaryan** [comment]
This is now ready for review.

**Comment by tigrannajaryan** [comment]
@open-telemetry/collector-contrib-approvers this is ready for review.

**Review by TylerHelmuth — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
LGTM

**Review by atoulme — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
