### PR TITLE
[exporter/awsxraytranslator] Fixing dropped exception when non-error status code

### PR DESCRIPTION
**Pull request by atshaw43**
**Description:** 
Fixing a bug where the exception in an event is dropped when the status code is not Error.

**Tracking Issue**
https://github.com/aws-observability/aws-otel-community/issues/38

**Testing:**
Added 4 unit tests covering cases where there is and is not an exception in an event for the status codes of OK and UNSET.

**Documentation:**
No documentation added.

### CODE REVIEW

**Comment by wangzlei** [comment]
attach the github issue https://github.com/aws-observability/aws-otel-community/issues/38

**Review by wangzlei — APPROVED** [review]
LGTM!

**Comment by TylerHelmuth** [comment]
@atshaw43 please sign the CLA.

**Comment by srprash** [comment]
LGTM.
However, this PR partially addresses the ask in the [issue](https://github.com/aws-observability/aws-otel-community/issues/38). As per [the docs](https://aws-otel.github.io/docs/getting-started/x-ray#otel-span-attributes-translation), the `awsxrayexporter` will still drop non-error span events.

**Comment by willarmiros** [comment]
> will still drop non-error span events

Do we have handling for any events in the exporter? I'm not sure if that should be tracked separately, as we've previously discussed there's not really a great way to represent events in X-Ray today.

**Comment by atshaw43** [comment]
@TylerHelmuth Can you re-review the PR?
Thanks,
Adam

**Comment by atshaw43** [comment]
> 

@willarmiros I talked with Prashant offline. It is not sent downstream as an event, we translate it into a cause which is consumed downstream. We should be good.

**Comment by srprash** [comment]
To add to @atshaw43 comment above ^^.

Exceptions are the only specific type of OTel span events that we handle within the xray exporter since we can translate them to `cause` and `exception` on the segment representation.

**Comment by atshaw43** [comment]
> @atshaw43 happy to review once all of @willarmiros questions are answered. Since @willarmiros is the code owner, I'll defer to him for now.

Bumping.
We have addressed the question.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by atshaw43** [comment]
@TylerHelmuth
Thanks for the quick turn around. I really appreciate it!
Is there anything I need to do to kick off the merge to master? Do I need to alert a maintainer?

**Comment by TylerHelmuth** [comment]
@atshaw43 it would be good if @willarmiros can leave a review.  If he approves I'll add the "ready-to-merge" label.

**Review by willarmiros — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
