### PR TITLE
[chore][receiver/journald] remove duplicate function NewFactory and pass checkapi

### PR DESCRIPTION
**Pull request by sakulali**
**Description:**
Remove duplicate function NewFactory and pass checkapi since we should only keep one NewFactory.

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26304

**Testing:**
go run cmd/checkapi/main.go .
go test for journaldreceiver

**Documentation:**

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Review by djaglowski — COMMENTED** [review]
I'm not sure I understand what is being solved here.

Journald is a linux specific component, so this change introduces a factory for non-linux usage, but it does nothing? It seems like it. may cause other problems.

**Review by djaglowski — APPROVED** [review]
Nevermind my previous question. I understand the changes now.

**Comment by sakulali** [comment]
> Nevermind my previous question. I understand the changes now.

Thanks for reviews @djaglowski! I should make it clear in the description that we should only keep one NewFactory.

**Comment by sakulali** [comment]
CI seems go wrong(seems not related with this PR), but i have no idea about that.

```
stanza/operator/input/udp/udp.go:142: File is not `gofmt`-ed with `-s` `-r 'interface{} -> any'` (gofmt)
level=info msg="[runner] processing took 32.17115ms with stages: exclude-rules: 11.786536ms, identifier_marker: 8.651115ms, path_prettifier: 4.33792ms, autogenerated_exclude: 3.482249ms, nolint: 3.399537ms, skip_dirs: 390.69µs, source_code: 48.711µs, cgo: 37.53µs, filename_unadjuster: 19.466µs, max_same_issues: 5.27µs, uniq_by_line: 3.145µs, max_from_linter: 2.225µs, max_per_file_from_linter: 1.694µs, path_prefixer: 1.634µs, path_shortener: 851ns, severity-rules: 561ns, sort_results: 501ns, fixer: 480ns, skip_files: 392ns, exclude: 342ns, diff: 301ns"
level=info msg="[runner] linters took 15.6624762s with stages: goanalysis_metalinter: 15.630148672s"
level=info msg="File cache stats: 229 entries of total size 1.1MiB"
			New: func() interface{} {
level=info msg="Memory: 211 samples, avg is 403.6MB, max is 699.6MB"
level=info msg="Execution took 22.229189021s"
make[2]: *** [../../Makefile.Common:177: lint] Error 1
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/stanza'
```

**Pull request merged**
