### PR TITLE
[connector/servicegraph] Coalesce different attr sets into single ScopeMetrics metric entry

### LINKED ISSUE #33998: [connector/servicegraph] Unit test failure: TestConnectorConsume/test_fix_failed_label_not_work
### Component(s)

connector/servicegraph

### Describe the issue you're reporting

[Failing CI/CD action link
](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9854192691/job/27233186145?pr=33458)

Failure occurred in unrelated PR, running on ubuntu.

Failure output:
```
Running target 'test-with-cover' in module 'connector/servicegraphconnector' as part of group 'connector'
make --no-print-directory -C connector/servicegraphconnector test-with-cover
mkdir -p /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit
/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 600s -parallel 4 --tags="" -cover -covermode=atomic -args -test.gocoverdir="/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit"
✖  . (79ms) (coverage: 87.3% of statements)
✓  internal/metadata (1.02s) (coverage: 83.3% of statements)
✓  internal/store (1.121s) (coverage: 92.7% of statements)

DONE 31 tests, 2 failures in 7.887s

✖  . (38ms) (coverage: 87.3% of statements)

=== Failed
make[2]: *** [../../Makefile.Common:131: test-with-cover] Error 1
=== FAIL: . TestConnectorConsume/test_fix_failed_label_not_work (0.01s)
make[1]: *** [Makefile:179: connector/servicegraphconnector] Error 2
    logger.go:146: 2024-07-09T18:45:05.793Z	INFO	Started servicegraphconnector
    logger.go:146: 2024-07-09T18:45:05.793Z	INFO	Shutting down servicegraphconnector
    logger.go:146: 2024-07-09T18:45:05.796Z	DEBUG	edge completed	{"client_service": "foo", "server_service": "bar", "connection_type": "", "trace_id": "b3a53e9c2ac533afc48b511c2f368dc1"}
    logger.go:146: 2024-07-09T18:45:05.796Z	DEBUG	edge completed	{"client_service": "foo", "server_service": "bar", "connection_type": "", "trace_id": "c6aafb2dcf4d71c81ae52e50e8f805ee"}
make: *** [Makefile:131: gotest-with-cover] Error 2
    logger.go:146: 2024-07-09T18:45:05.796Z	DEBUG	edge completed	{"client_service": "foo", "server_service": "bar", "connection_type": "", "trace_id": "7af657de319d6a57967bc241882ea94f"}
    connector_test.go:129: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/servicegraphconnector/connector_test.go:129
        	Error:      	Received unexpected error:
        	            	the following errors occurred:
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_client_seconds": missing expected datapoint: map[client:foo connection_type: failed:false server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_client_seconds": unexpected datapoint: map[client:foo connection_type: failed:true server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_client_seconds": missing expected datapoint: map[client:foo connection_type: failed:true server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_client_seconds": unexpected datapoint: map[client:foo connection_type: failed:false server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": missing expected datapoint: map[client:foo connection_type: failed:false server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": unexpected datapoint: map[client:foo connection_type: failed:true server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": missing expected datapoint: map[client:foo connection_type: failed:true server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": unexpected datapoint: map[client:foo connection_type: failed:false server:bar]
        	Test:       	TestConnectorConsume/test_fix_failed_label_not_work

=== FAIL: . TestConnectorConsume (0.01s)

=== FAIL: . TestConnectorConsume/test_fix_failed_label_not_work (re-run 1) (0.01s)
    logger.go:146: 2024-07-09T18:45:07.902Z	INFO	Started servicegraphconnector
    logger.go:146: 2024-07-09T18:45:07.902Z	INFO	Shutting down servicegraphconnector
    logger.go:146: 2024-07-09T18:45:07.904Z	DEBUG	edge completed	{"client_service": "foo", "server_service": "bar", "connection_type": "", "trace_id": "b3a53e9c2ac533afc48b511c2f368dc1"}
    logger.go:146: 2024-07-09T18:45:07.905Z	DEBUG	edge completed	{"client_service": "foo", "server_service": "bar", "connection_type": "", "trace_id": "c6aafb2dcf4d71c81ae52e50e8f805ee"}
    logger.go:146: 2024-07-09T18:45:07.905Z	DEBUG	edge completed	{"client_service": "foo", "server_service": "bar", "connection_type": "", "trace_id": "7af657de[319](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9854192691/job/27233186145?pr=33458#step:9:320)d6a57967bc241882ea94f"}
    connector_test.go:129: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/servicegraphconnector/connector_test.go:129
        	Error:      	Received unexpected error:
        	            	the following errors occurred:
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": missing expected datapoint: map[client:foo connection_type: failed:false server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": unexpected datapoint: map[client:foo connection_type: failed:true server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": missing expected datapoint: map[client:foo connection_type: failed:true server:bar]
        	            	 -  resource "map[]": scope "traces_service_graph": metric "traces_service_graph_request_server_seconds": unexpected datapoint: map[client:foo connection_type: failed:false server:bar]
        	Test:       	TestConnectorConsume/test_fix_failed_label_not_work

=== FAIL: . TestConnectorConsume (re-run 1) (0.01s)

DONE 2 runs, 33 tests, 4 failures in 8.913s
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by evantorrie**
Tests in `connector/servicegraph` were failing because the servicegraph `buildMetrics()` code was creating multiple metric entries for the same metric name within a single MetricScope. Although this may not be forbidden by the Otel specification, I think there is a general assumption that a metric name does not appear more than once within the same MetricScope.
Instead, different values (e.g. with different sets of attribute values) should be created as separate datapoints within the same metric.

The `pmetrictest.CompareScopeMetrics` test functionality is not designed to handle multiple metric entries with the same `Name()`.  Instead, it is assumed that in cases where Order is ignored, the [first entry found in the actual metrics which matches the name of the expected metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ca9a8d14df471ed6a7dda7562ddfe659ec52127d/pkg/pdatatest/pmetrictest/metrics.go#L186-L195) *must* be the metric to compare.

This fix changes the `buildMetrics()` code to create one metric within a scope, and instead create multiple datapoints per metric when there are entries where the datapoint attribute set is unique (i.e. all entries in the internal maps `serviceGraphConnector.req{Total,FailedTotal,ServerDurationSecondsCount}` are coalesced into a single named metric as appropriate.)

_Note_: I don't have any past experience working with servicegraphconnector, but just observing that `collectClientLatencyMetrics()` and `collectServerLatencyMetrics()` both range over the same map - `p.reqServerDurationSecondsCount`, although the actual values collected in `collectClientLatencyMetrics()` are from `p.reqServerDurationSeconds{Count,Sum,BucketCounts}` and the values collected in `collectServerLatencyMetrics()` are from `p.reqClientDurationSeconds{Count,Sum,BucketCounts}`.   

This seems a little asymmetrical, but I don't have enough experience to say whether this is an error or not.

**Description:**  Fixes #33998 

**Testing:** All other unit tests now complete, and the previously failing unit test now works reliably.

**Documentation:** No documentation added. This is a unit test fix.

### CODE REVIEW

**Comment by evantorrie** [comment]
No changelog entry as this is a fix for a flaky unit-test.

**Review by t00mas — APPROVED** [review]
This makes sense 👍🏼

**Review by jpkrohling — CHANGES_REQUESTED** [review]
I believe the following PR has the same purpose as this, but might be a better solution. If this PR here has further improvements, we can consider merging it as well. I'm blocking this, so that we can take that into account before merging.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34076

**Comment by evantorrie** [comment]
Restore skipped test introduced in #34120

**Comment by evantorrie** [comment]
> I believe the following PR has the same purpose as this, but might be a better solution. If this PR here has further improvements, we can consider merging it as well. I'm blocking this, so that we can take that into account before merging.
> 
> #34076

#34076 was not successful in fixing the servicegraph connector flaky test. The root cause of the error is at a higher level than the order of datapoint attributes within a metric.  As mentioned earlier

> The pmetrictest.CompareScopeMetrics test functionality is not designed to handle multiple metric entries with the same Name(). Instead, it is assumed that in cases where Order is ignored, the [first entry found in the actual metrics which matches the name of the expected metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ca9a8d14df471ed6a7dda7562ddfe659ec52127d/pkg/pdatatest/pmetrictest/metrics.go#L186-L195) must be the metric to compare.

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Would it make sense to undo #34076 as part of this PR?

**Comment by evantorrie** [comment]
As far as I can tell from #34076, it attempts to sort all datapoint slices based on a canonicalized order of the attributes within each datapoint.

The existing `compare{Number,Histogram,Summary}DataPointSlices` functions in `pmetrictest` check for each "expected" datapoint whether there exists an "actual" datapoint using the [following test to determine if the datapoints](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f3fdea38e65f2679e5d312b9a9311b42aa37dcda/pkg/pdatatest/pmetrictest/metrics.go#L304-L312) match.

`if reflect.DeepEqual(edp.Attributes().AsRaw(), adp.Attributes().AsRaw())`

If there is a match, but they are not in the same index order `if e != a`, then it will append an error indicating the out-of-order data attributes.

The only way to avoid an OutOfOrderErr and [get to the point of comparing the actual values](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f3fdea38e65f2679e5d312b9a9311b42aa37dcda/pkg/pdatatest/pmetrictest/metrics.go#L329-L336) is to ensure that the order of the metric datapoints within a DataPointSlice are *exactly* the same between the expected and the actual which is what #34076 does by [sorting both `expected` and `actual` in the same way](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34076/files#diff-797373b088f69c436450a14d33b05c8e40bda2eaa255c989e70d1e9327a6f941R185-R188).

So no, I don't think #34076 needs to be reverted.

It's a useful option, particularly if there are multiple datapoints within a single Resource::Scope::Metric structure, and it's non-deterministic as to which order they will be added.

I do see that the merged commit didn't fix the copy/paste error on the function comment for `IgnoreDatapointAttributesOrder()` though (it still refers to `IgnoreMetricAttributeValue`).  

Fixing that comment is not really part of this PR, but I can put it in as an additional commit to avoid opening/merging another PR just for that comment change.

**Comment by jpkrohling** [comment]
Thanks for the comments. I'll merge this as is, the comment can be fixed on a follow up PR

**Pull request merged**
