### PR TITLE
Adding @MovieStoreGuy as a owner of the kinesis exporter

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
I would like to add myself as a code owner for the kinesis exporter.

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Review by owais — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
Huh, I tried to see if I could resolve the load-tests on my local machine however, they appear not run on macOS so I will raise an issue for that once I get a free moment.

**Comment by bogdandrutu** [comment]
please rebase

**Comment by MovieStoreGuy** [comment]
@bogdandrutu, @tigrannajaryan ,

Could I ask you to merge this please?
I've raised https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6144 for the failing test cases on my machine and will look at addressing that later.

**Comment by tigrannajaryan** [comment]
Thank you @MovieStoreGuy !

**Pull request merged**
