### PR TITLE
Add TencentCloud LogService exporter

### PR DESCRIPTION
**Pull request by wgliang**
Description:

This PR introduces an exporter for TencentCloud LogService. The exporter works by translating logs into the LogService protobuf format expected by LogService, and sending over HTTP.

Testing:

Manually tested, sending to an LogService's instance.

Documentation:

Added a README, which describes the exporter's config.

### CODE REVIEW

**Review by MovieStoreGuy — COMMENTED** [review]
There was a few things that stood out when reviewing, if you have a chance to have a look and see what you think.

**Comment by wgliang** [comment]
@MovieStoreGuy I agree with these suggestions, and thank you for your time.

**Review by anuraaga — COMMENTED** [review]
We have a template for adding new components through three PRs to reduce the load of reviewing one huge PR

https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

Would you be able to try to split this up using that pattern?

**Comment by wgliang** [comment]
> We have a template for adding new components through three PRs to reduce the load of reviewing one huge PR
> 
> https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component
> 
> Would you be able to try to split this up using that pattern?

To be honest, I started to read this guide, but I don’t know that it is a coincidence or there is always a situation: the opentelemetry-collector-contrib changes very frequently, and the PR of ten days ago has reached the state where it can be merged, but yesterday I wanted to continue the merge and found that there is a lot of gap.
Actually,there are not many core files for a new collector, and the energy consumption caused by splitting into multiple PRs will feel greater. 
And the exporters that I view the history are also a PR to complete.

**Review by anuraaga — APPROVED** [review]

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by wgliang** [comment]
Ready to merge, I see the status that requires the permission of the maintainer to continue. PTAL,thanks. @bogdandrutu @tigrannajaryan

**Comment by wgliang** [comment]
The conflict has been resolved, hope to get feedback.

**Review by bogdandrutu — COMMENTED** [review]
* Add owners for this component;
* Add entry in dependabot file using `make gendependabot`.

**Comment by wgliang** [comment]
@bogdandrutu I have updated based on your comments, please take a look again. Thanks.

**Comment by wgliang** [comment]
@jpkrohling This PR has been repeatedly rebased many times, please help merge it. Thanks. :)

**Comment by wgliang** [comment]
The loadtest and unitest errors seems to have nothing to do with the PR.

**Pull request merged**
