### PR TITLE
[exporter/awsemfexporter] Add config option to retain the initial value of delta metrics (#16218)

### PR DESCRIPTION
**Pull request by mircohacker**
**Description:** 
Some metrics (i.e. Counter) are cumulative in the data model of open telemetry, but AWS EMF expects delta values as contents of the value field. Previously this was solved by dropping the first occurrence of an specific metric label combination and only storing its value as baseline to calculate the difference to the next occurrence of this metric. This is fine for metrics where the value changes a lot and exactness is not important (i.e. `requests{code=200}`). But there are use cases where a metric should track events which do not occur often or have a high cardinality in its labels. In this case the current implementation drops a significant percentage of data. With this PR merged the new configuration flag `retain_initial_value_of_delta_metric` is introduced which changes this behavior. The implementation still tries to compute the delta but when no previous value is found, the received value is then assumed to be the delta value or more exact the previous value is assumed to be 0 or 0 equivalent for summaries. 

This PR does not change the behavior of the exporter in default configuration.

Suggestions for a better name are gladly accepted but this was the best i could come up with.

**Link to tracking Issue:** 
* https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16218
* https://github.com/aws-observability/aws-otel-collector/issues/1653

**Testing:** 
Edit test datapoint_test.go to test both configuration valued for the new flag with expected output. The default case stayed the same and only the behavior for the flag set to `true` changed. The GitHub diff does not recognize that on most lines only the indention changed...
Also:
* `make test benchmark` in dir `exporter/awsemfexporter`
* `make common` in repo root 
* `make gofmt` in repo root

**Documentation:** Documentation was added in Readme, next to the config value as code comments and as changelog entry

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
I don't fully grasp the implication of this, if there is any negative impact adding this in.

As code owner, can I ask you to double check @Aneurysm9 ?

**Comment by MovieStoreGuy** [comment]
Can I ask you to rebase against main @mircohaug ?

**Comment by Aneurysm9** [comment]
> I don't fully grasp the implication of this, if there is any negative impact adding this in.
> 
> As code owner, can I ask you to double check @Aneurysm9 ?

I don't think that there are any unavoidable negative side effects of doing this, particularly since it is opt-in, requiring the user to make a configuration change to accept this behavior.  I'm not 100% sure why it was done this way in the first place and Chesterton's Fence makes me want to keep the default behavior as-is.

**Comment by MovieStoreGuy** [comment]
Can I ask you to fix up the merge conflicts @mircohaug ?

**Comment by mircohaug** [comment]
@MovieStoreGuy I just rebased the branch. This configuration option is intended to be used in a scenario where the collector is deployed as a sidecar to one app instance. When the collector is deployed independently of the app, then it will happen, that the first value seen by the collector is not the first value sent by the app. So the collector sees `requests{code=200} 123` and sends 123 as delta value to AWS EMF when in reality only a few requests are "new". This could trigger all kinds of downstream systems analyzing this metric. In the default configuration this new value would just get ignored and stored as new delta baseline.

@Aneurysm9 I think that this is also the reason it was done this way from the beginning. AWS EMF works on deltas whereas otel works with monotone increasing counters. At some point the conversion has to be made and it is unavoidable to "loose" some information one way or the other.

**Comment by MovieStoreGuy** [comment]
Just some linting issues :) 

I believe you just need to run:
```
make fmt
```

In the directory.

**Review by Aneurysm9 — APPROVED** [review]

**Review by TylerHelmuth — COMMENTED** [review]
@mircohaug please review the lint failures.

**Comment by mircohaug** [comment]
Some merge hiccups 🤷 should be fixed now

**Comment by MovieStoreGuy** [comment]
@mircohaug , could I ask you rebase main again?

**Comment by mircohaug** [comment]
@MovieStoreGuy done

**Review by codeboten — COMMENTED** [review]
Looks like another change snuck in to create a conflict :(

**Comment by mircohaug** [comment]
@codeboten @MovieStoreGuy Rebased it is. It is also kind of tedious...

**Comment by codeboten** [comment]
> @codeboten @MovieStoreGuy Rebased it is. It is also kind of tedious...

💯 agree. Will try to get this pr merge asap. It looks like the change failed tests in the awsemfexporter:

```
 === RUN   TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_1st_delta_sum_count_calculation_retainInitialValueOfDeltaMetric=true
    datapoint_test.go:435: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/awsemfexporter/datapoint_test.go:435
        	Error:      	Max difference between 18 and 17 allowed is 0.002, but difference was 1
        	Test:       	TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_1st_delta_sum_count_calculation_retainInitialValueOfDeltaMetric=true
=== RUN   TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_2nd_delta_sum_count_calculation
=== RUN   TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_3rd_delta_sum_count_calculation
=== RUN   TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_1st_delta_sum_count_calculation_retainInitialValueOfDeltaMetric=false
=== RUN   TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_2nd_delta_sum_count_calculation#01
=== RUN   TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_3rd_delta_sum_count_calculation#01
--- FAIL: TestCalculateDeltaDatapoints_SummaryDataPointSlice (0.00s)
    --- FAIL: TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_1st_delta_sum_count_calculation_retainInitialValueOfDeltaMetric=true (0.00s)
    --- PASS: TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_2nd_delta_sum_count_calculation (0.00s)
    --- PASS: TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_3rd_delta_sum_count_calculation (0.00s)
    --- PASS: TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_1st_delta_sum_count_calculation_retainInitialValueOfDeltaMetric=false (0.00s)
    --- PASS: TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_2nd_delta_sum_count_calculation#01 (0.00s)
    --- PASS: TestCalculateDeltaDatapoints_SummaryDataPointSlice/Detailed_summary_with_3rd_delta_sum_count_calculation#01 (0.00s)
```

**Comment by mircohaug** [comment]
My bad. I wanted to see the tests red as well and forgot to make this one green again 🙈 @codeboten @MovieStoreGuy Im asking you once again to merge this PR 😉

**Review by codeboten — APPROVED** [review]

**Pull request merged**
