### PR TITLE
[chore] Increase Cache Go step timeout to 25min on Windows

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
Increase the timeout of the "Cache Go" step in the `build-and-test-windows` workflow. I had a few failures with that today and glancing at the errors for the workflow I can see a few others.

Few instances below:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6722644168/job/18271035294#step:5:22
* https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6725656509/job/18280490403#step:5:23
* https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6726302253/job/18282301386#step:5:21

**Link to tracking Issue:**
N/A

**Testing:**
N/A

**Documentation:**
N/A

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Comment by dmitryax** [comment]
@pjanotti please rebase, I've just merged a fix to unrelated CI check

**Review by crobert-1 — APPROVED** [review]

**Comment by pjanotti** [comment]
Unrelated test failure: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6736696514/job/18312591773?pr=28859#step:6:124

```terminal
--- FAIL: TestStartAndShutdownLocalFile (0.00s)
    extension_test.go:43: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/jaegerremotesamplingdeprecated/extension_test.go:43
        	Error:      	Received unexpected error:
        	            	error while starting the HTTP server: listen tcp 127.0.0.1:5778: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestStartAndShutdownLocalFile
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/jaegerremotesamplingdeprecated	0.152s
```

**Comment by pjanotti** [comment]
It seems that the failure on `extension/jaegerremotesampling` is happening consistently, last Windows run has another failure too: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6736991443/job/18313496716?pr=28859#step:6:122

```terminal
--- FAIL: TestStartAndShutdownLocalFile (0.01s)
    extension_test.go:43: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/extension_test.go:43
        	Error:      	Received unexpected error:
        	            	error while starting the HTTP server: listen tcp 127.0.0.1:5778: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestStartAndShutdownLocalFile
--- FAIL: TestRemote (2.07s)
    --- FAIL: TestRemote/no_configured_header_additions_and_no_configured_reload_interval (2.07s)
        extension_test.go:116: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/extension_test.go:116
            	Error:      	Received unexpected error:
            	            	error while starting the HTTP server: listen tcp 127.0.0.1:5778: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
            	Test:       	TestRemote/no_configured_header_additions_and_no_configured_reload_interval
        extension_test.go:121: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/extension_test.go:121
            	Error:      	Received unexpected error:
            	            	Get "http://127.0.0.1:5778/sampling?service=foo": dial tcp 127.0.0.1:5778: connectex: No connection could be made because the target machine actively refused it.
            	Test:       	TestRemote/no_configured_header_additions_and_no_configured_reload_interval
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x12084a3]

goroutine 27 [running]:
testing.tRunner.func1.2({0x12cfa00, 0x1c4c6a0})
	C:/hostedtoolcache/windows/go/1.20.10/x64/src/testing/testing.go:1526 +0x372
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.20.10/x64/src/testing/testing.go:1529 +0x650
panic({0x12cfa00, 0x1c4c6a0})
	C:/hostedtoolcache/windows/go/1.20.10/x64/src/runtime/panic.go:890 +0x263
github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling.TestRemote.func1(0xc000395860)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/extension_test.go:122 +0xbe3
testing.tRunner(0xc000395860, 0xc000392750)
	C:/hostedtoolcache/windows/go/1.20.10/x64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.10/x64/src/testing/testing.go:1629 +0x806
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/extension/jaegerremotesampling	2.144s
```

**Review by fatsheep9146 — APPROVED** [review]

**Comment by dmitryax** [comment]
> It seems that the failure on extension/jaegerremotesampling is happening consistently, last Windows run has another failure too: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6736991443/job/18313496716?pr=28859#step:6:122

Hopefully, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28874 will solve this

**Comment by dmitryax** [comment]
Thanks @pjanotti!

**Pull request merged**
