### PR TITLE
Fix flaky k8sprocessor observability test

### PR DESCRIPTION
**Pull request by pmalek-sumo**
**Description:** Fix flaky k8sprocessor observability test

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1093

**Testing:** `go test -c ./observability &&  while ./observability.test -test.count 1; do true ; done`

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]
Thank you @pmalek-sumo !

**Comment by pmalek-sumo** [comment]
It seems that this didn't really fix it for 100% of runs https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/13676/workflows/7c148fd0-a349-4e13-a49d-deb244b92267/jobs/117605

Maybe we should just disable this test after all?

**Comment by tigrannajaryan** [comment]
@pmalek-sumo yes, let's disable it.

**Comment by pmalek-sumo** [comment]
> @pmalek-sumo yes, let's disable it.

Just so that you know, there's one more PR that I pushed to tackle this. Worth giving a shot before disabling: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3389

**Pull request merged**
