### PR TITLE
Extract internal/common/testing/container to internal/containertest

### PR DESCRIPTION
**Pull request by bogdandrutu**
Updates https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7791

Just based on the number of deletions this proves to make sense :)

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by dmitryax** [comment]
Please take a look at failing tests, looks like caused by the change

**Comment by bogdandrutu** [comment]
@dmitryax PTAL

**Comment by dmitryax** [comment]
Please resolve conflicts :)

**Comment by bogdandrutu** [comment]
@dmitryax PTAL :) let's see what reason are you going to find now to avoid the review :))

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
