### PR TITLE
[docs] Add status header for dockerstats receiver

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>
Add status header for dockerstats receiver

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Change looks good, pinging code owner @rmfitzpatrick for confirmation of beta status

**Comment by rmfitzpatrick** [comment]
Given the proposed changes in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9794 I think we'll want to classify this as alpha.

**Comment by djaglowski** [comment]
> Given the proposed changes in #9794 I think we'll want to classify this as alpha.

@Frapschen, please change the status to alpha

**Comment by Frapschen** [comment]
@djaglowski status changed

**Review by rmfitzpatrick — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
