### PR TITLE
[cfgschema] move api files into pkg, add tests

### PR DESCRIPTION
**Pull request by pmcollins**
**Description:** This change makes cfgschema usable from outside the Contrib repo.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20418

**Testing:** Functionality manually tested from within contrib as well as via calls from a different repo.

**Documentation:** Updated usage docs for the command.

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
This is a draft PR so maybe this comment is premature, but it feels like three separate issues are dealt with in this PR:
- Renaming to `cfgmetadatagen`
- Some changes in the logic of how this tool works
- Exposing (a lot of) public API under `pkg/cfgschema`

IMO each of these need its own separate PR

**Comment by pmcollins** [comment]
> This is a draft PR so maybe this comment is premature, but it feels like three separate issues are dealt with in this PR:
> 
> * Renaming to `cfgmetadatagen`
> * Some changes in the logic of how this tool works
> * Exposing (a lot of) public API under `pkg/cfgschema`
> 
> IMO each of these need its own separate PR

Ok, will split it up.

**Comment by pmcollins** [comment]
Sure, will do. Curious though, what are the large amounts of additional public API you are referring to? This change has two exported functions (which need to be exported to be usable by external repos) and no exported types. It also un-exports several types and functions that were previously exported.

Regarding the future of this functionality in Contrib, any thoughts about proposing that it just be removed? (my org would just move it to a repo where we need this functionality) Thanks.

**Comment by Aneurysm9** [comment]
> Curious though, what are the large amounts of additional public API you are referring to?

I have not reviewed the PR.  My statement was based on the statement by @mx-psi that this was "Exposing (a lot of) public API under `pkg/cfgschema`".

**Comment by mx-psi** [comment]
My bad, I misread the diff, "a lot" was not the right choice of words here :) I still think it should go on a separate PR from the other changes

**Pull request closed without merging**
