### PR TITLE
Prepare v0.47.0 release

### LINKED ISSUE #5010: Prepare contrib release v0.47.0

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** Part of v0.47.0 release procedure.
**Link to tracking Issue:** Fixes open-telemetry/opentelemetry-collector#5010

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by mx-psi** [comment]
Let's merge this while I figure out how to solve multimod issues

**Review by pmm-sumo — APPROVED** [review]

**Comment by mx-psi** [comment]
I cherry-picked the commit from #8513 to make the build pass. I also faced open-telemetry/opentelemetry-go-build-tools/issues/46, which explains 2014cd0d9601090565be554ab0bdc622faab0d2d.

**Comment by mx-psi** [comment]
We also need #8514

**Review by codeboten — APPROVED** [review]

**Comment by mx-psi** [comment]
There is a Github Actions incident which is making CI steps not run https://www.githubstatus.com/incidents/fpk08rxnqjz2

**Pull request merged**
