### PR TITLE
[docs] Add status header for tencentcloudlogservice exporter

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>
Add status header for tencentcloudlogservice exporter.

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]
/cc @wgliang @yiyang5055 as code owners to verify beta stability

**Comment by Frapschen** [comment]
hi @wgliang @yiyang5055 can you have time to review this PR?

**Comment by wgliang** [comment]
> hi @wgliang @yiyang5055 can you have time to review this PR?

Thanks for your PR. I want to know how to judge the status of the current version is beat?

**Comment by Frapschen** [comment]
> 

hi ,there is a reference [link](https://github.com/open-telemetry/opentelemetry-collector#beta)

**Comment by wgliang** [comment]
> > 
> 
> hi ,there is a reference [link](https://github.com/open-telemetry/opentelemetry-collector#beta)

LGTM. I agree to this change. Thanks. /cc @TylerHelmuth

**Review by pmm-sumo — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
