### PR TITLE
[receiver/hostmetrics] Migrate memory scraper to the new metrics builder

### PR DESCRIPTION
**Pull request by rogercoll**
Link to tracking Issue: open-telemetry/opentelemetry-collector#10904

### CODE REVIEW

**Comment by dmitryax** [comment]
Hi @rogercoll, thanks for the contribution! There is already an open PR for this scraper https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7312

We can see if this one can be merged first.

If you want to convert any other scraper please check that no one is working on a sub-issue made for the scraper here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6429

**Comment by rogercoll** [comment]
@dmitryax Thanks for the information, I didn't see that the memory scraper update was on process in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6429.

**Comment by dmitryax** [comment]
@rogercoll please resolve linter issues

**Comment by rogercoll** [comment]
@dmitryax Linter issues should be fixed by now.

**Review by dmitryax — APPROVED** [review]
This PR is similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7312, but has a bit more comprehensive test suite

**Review by anuraaga — APPROVED** [review]

**Comment by rogercoll** [comment]
@anuraaga @dmitryax CHANGELOG.md conflics solved.

**Comment by dmitryax** [comment]
@rogercoll please rebase your PR. codegen.go was moved to doc.go

**Comment by rogercoll** [comment]
@dmitryax PR rebased

Regards

**Comment by dmitryax** [comment]
Linter is failing

**Comment by rogercoll** [comment]
Closing as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7312 was merged

**Pull request closed without merging**
