### PR TITLE
[chore] Remove use of deprecated scraperhelper structs/funcs

### PR DESCRIPTION
**Pull request by TylerHelmuth**

### CODE REVIEW

**Review by dmitryax — COMMENTED** [review]
I believe it's an API breaking change for all components since we change the config field. We should put it in the changelog

**Comment by TylerHelmuth** [comment]
@dmitryax we change the field name of the component's config, but not how the end-user interacts with it.  A component's public api isn't supposed to be depended on right?

**Comment by dmitryax** [comment]
> @dmitryax we change the field name of the component's config, but not how the end-user interacts with it. A component's public api isn't supposed to be depended on right?

Right, it's not a _user_ breaking change, but it has to be mentioned in the _api_ changelog since go applications using the components public API has to adopt for this change

**Comment by TylerHelmuth** [comment]
> go applications using the components public API has to adopt for this change

I'll add an API changelog for it, but I thought it was an anti-pattern to directly depend on component packages.

**Review by atoulme — APPROVED** [review]

**Pull request merged**
