### PR TITLE
chore: adds vanity import check.

### PR DESCRIPTION
**Pull request by jcchavezs**
**Description:** This PR adds vanity import for all packages to easy the consumption of the library. 

Follows from https://github.com/open-telemetry/opentelemetry-collector/pull/4180

### CODE REVIEW

**Comment by jcchavezs** [comment]
Ping @mx-psi @bogdandrutu

**Comment by mx-psi** [comment]
needs a rebase (otherwise looks good, although there is less value here since we don't use the fancy `go.opentelemetry.io` vanity URLs on this repo)

**Comment by jcchavezs** [comment]
While we don't use the fancy domain I really think the url is too long that
having this import path at hand is very useful.

José Carlos Chávez


tir. 16. nov. 2021 kl. 10:40 skrev Pablo Baeyens ***@***.***>:

**Comment by jcchavezs** [comment]
Rebase done.

**Review by mx-psi — APPROVED** [review]

**Comment by jcchavezs** [comment]
Could we please merge this before I have to do another rebase? cc @bogdandrutu @carlosalberto

**Review by codeboten — APPROVED** [review]

**Pull request merged**
