### PR TITLE
[extension/jaegerremotesampling] remote sampling gRPC support #6694

### LINKED ISSUE #6694: Add the gRPC server

### PR DESCRIPTION
**Pull request by frzifus**
**Description:** <Describe what has changed.>

This pr adds gRPC support to the jaegerremotesampling extension.

**Link to tracking Issue:** <Issue number if applicable>
- Closes #6694 

**Testing:** <Describe what testing was performed and which tests were added.>
- Unittest

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Once this is ready to be reviewed, move it out of Draft  status and/or ping me.

**Review by jpkrohling — COMMENTED** [review]
This looks really good. Before doing my manual tests on this, I wanted to confirm whether you performed yours and how you did it. Thank you for this PR!

**Comment by frzifus** [comment]
> Before doing my manual tests on this, I wanted to confirm whether you performed yours and how you did it.

I used the following configuration based on the test data located in the `jaegerremotesampling` folder and placed it into the project root (`config.yaml`).

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: debug

extensions:
  pprof:
  jaegerremotesampling:
    source:
      reload_interval: 5s
      file: strategies.json

service:
  extensions: [jaegerremotesampling]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```

The specified [strategies.json](https://raw.githubusercontent.com/jaegertracing/jaeger/v1.36.0/plugin/sampling/strategystore/static/fixtures/strategies.json) is downloaded from the Jaeger project v1.36.0.
As a next step I registered the `jaegerremotesampling` factory in [otelcontribcol(components)](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.56.0/internal/components/components.go#L176), compiled the program and executed it.

```bash
$ make otelcontribcol && ./bin/otelcontribcol_linux_amd64 --config config.yaml
```

As counter part I used this small go program:
```golang
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	jaegergrpc "github.com/jaegertracing/jaeger/cmd/agent/app/configmanager/grpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()
	grpcOptions := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithBlock()}
	conn, err := grpc.DialContext(ctx, "localhost:14250", grpcOptions...)
	if err != nil {
		log.Fatalf("failed to create gRPC connection to collector: %w", err)
	}
	defer conn.Close()

	mgr := jaegergrpc.NewConfigManager(conn)

	doReq := func(svc string) {
		ctx, cancel = context.WithTimeout(context.Background(), time.Minute)
		defer cancel()
		resp, err := mgr.GetSamplingStrategy(ctx, "svc")
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%+v\n", resp)
	}

	for {
		doReq("my-service")
		time.Sleep(15 * time.Second)
	}
}
```

Then I changed the `param` from `0.5` to `0.6` and back again.

**Review by jpkrohling — APPROVED** [review]
LGTM

**Comment by jpkrohling** [comment]
Looks like this is missing the changelog entry. Please, check the contributing guidelines, but basically, you'll need a file within the "unreleased" directory.

**Comment by frzifus** [comment]
added :+1:

**Comment by frzifus** [comment]
@jpkrohling is there something else needed to continue? :)

**Comment by frzifus** [comment]
just rebased

**Review by jpkrohling — APPROVED** [review]
LGTM

**Pull request merged**
