### PR TITLE
tailsamplingprocessor: Optimize tag mutator memory allocations 

### PR DESCRIPTION
**Pull request by brancz**
**Description:**

Since each `tailSamplingSpanProcessor`'s instance is not concurrently
called by the ticker worker (it's a 1-to-1 relationship) we can safely
reuse a slice for the tag mutators used in `makeDecision`. Additionally
the tag mutators themselves were causing a lot of allocations and since
they are static, we created constants for them preventing allocations on
each execution of `makeDecision`.

This improved the `makeDecision` benchmark by ~31%.

```
benchstat old.txt new.txt
name         old time/op  new time/op  delta
Sampling-10  51.8µs ± 1%  35.7µs ± 1%  -30.94%  (p=0.008 n=5+5)
```

**Testing:** Unit tests unchanged; added a benchmark

**Documentation:** Perf improvement so no documentation changes needed.

This was all based on production profiling data at Polar Signals running the collector. Here is a snapshot of the original profiling data we started with: https://pprof.me/52a7fab/

Judging by the production profiling data, a 31% improvement on the `makeDecision` codepath, should translate roughly into a 6% baseline CPU improvement our production deployment of the opentelemetry collector.

The profiling data after improving: https://pprof.me/58c0e84/

This improvement was done as part of the Let's Profile Livestream where we optimize popular open-source projects live: https://www.youtube.com/watch?v=vkMQRjiNTHM

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
I followed this live, and I'm good with the changes as long as the CI is passing (I'm not sure the tests were executed).

https://www.youtube.com/watch?v=vkMQRjiNTHM

**Comment by jiekun** [comment]
This looks cool. I jumped into this PR from the YouTube video as well. Nice job.

**Comment by jiekun** [comment]
> A test is failing on a place that is related to the changes:
> 
> ```
> --- FAIL: TestTraceIntegrity (0.00s)
> panic: runtime error: index out of range [0] with length 0 [recovered]
> 	panic: runtime error: index out of range [0] with length 0
> 
> goroutine 15 [running]:
> testing.tRunner.func1.2({0x112df00, 0xc00016a5a0})
> 	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1526 +0x372
> testing.tRunner.func1()
> 	/opt/hostedtoolcache/go/1.20.10/x64/src/testing/testing.go:1529 +0x650
> panic({0x112df00, 0xc00016a5a0})
> 	/opt/hostedtoolcache/go/1.20.10/x64/src/runtime/panic.go:890 +0x263
> github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*tailSamplingSpanProcessor).makeDecision(0xc000326180, {0x1, 0x2, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
> 	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/tailsamplingprocessor/processor.go:305 +0x14b9
> github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor.(*tailSamplingSpanProcessor).samplingPolicyOnTick(0xc000326180)
> ```
> 
> Anyone willing to pick this up? I can probably take a look eventually, but not _right now_.

I appreciate the optimizations made by the original author. 

The issue with the unit test only required a very small change, but since I am unable to submit it on the original branch, I have opened a separate PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28597. But yes @brancz feel free to add those fix lines to the original branch and I will delete the new pr ^_^

**Comment by jpkrohling** [comment]
I think I was able to add your commits to this PR, @jiekun. Thank you!

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
