### PR TITLE
support multiline filelog receiver in container operator

### PR DESCRIPTION
**Pull request by zeitlinger**
**Description:**

example config where multiline didn't work:

```yaml
    receivers:
      filelog:
        include:
          - /var/log/pods/*/anti-fraud/*.log
        include_file_path: true
        multiline:
          line_start_pattern: '.*stdout F \d{4}-'
        operators:
        - id: container-parser
          type: container
```

input log file - as emitted by the app:

```log
2024-07-02T08:47:51.349Z  INFO 1 --- [http-nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start com
2024-07-02T08:47:52.446Z  WARN 1 --- [http-nio-8080-exec-1] c.m.antifraud.FraudDetectionController   : Exception processing checkOrder(orderPrice=300, shippingCountry=, customerIpAddress=127.0.0.1) - trace_id=832030a81b1a6dbc25eb1cba4b746c6f, span_id=7
                                                                                                                                                                                                                                                            
java.lang.RuntimeException: Fraud Detection Processing Exception                                                                                                                                                                                            
    at com.mycompany.antifraud.FraudDetectionController.checkOrder(FraudDetectionController.java:126)                                                                                                                                                       
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)                                                                                                                                                                     
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)                                                                                                                                                                                            
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)                                                                                                                                              
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)                                                                                                                                      
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)                                                                                                          
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)                                                                                                        
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)                                                                                                             
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)                                                                                                                                 
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)                                                                                                                                                            
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)                                                                                                                                                              
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)                                                                                                                                                          
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)                                                                                                                                                                    
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)                                                                                                                                                                                       
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)                                                                                                                                                                  
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)                                                                                                                                                                                       
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)                                                                                                                                                    
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)                                                                                                                                                            
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)                                                                                                                                                                               
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)                              
```

as written do disk:

```log
2024-07-02T08:47:52.450371265Z stdout F 2024-07-02T08:47:52.446Z  WARN 1 --- [http-nio-8080-exec-1] c.m.antifraud.FraudDetectionController   : Exception processing checkOrder(orderPrice=300, shippingCountry=, customerIpAddress=127.0.0.1) - trace_id=832030a81b1a6dbc25eb1cba4b746c6f, span_id=795d7271a33db5cb, service.name=anti-fraud, service.namespace=shop, service.instance.id=485f3a49-75c7-4f2f-82d2-0cb5b240b2f8, deployment.environment=staging
2024-07-02T08:47:52.450388803Z stdout F 
2024-07-02T08:47:52.450391238Z stdout F java.lang.RuntimeException: Fraud Detection Processing Exception
2024-07-02T08:47:52.450403102Z stdout F 	at com.mycompany.antifraud.FraudDetectionController.checkOrder(FraudDetectionController.java:126)
2024-07-02T08:47:52.450405413Z stdout F 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
2024-07-02T08:47:52.450406896Z stdout F 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-07-02T08:47:52.450408388Z stdout F 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
2024-07-02T08:47:52.450410085Z stdout F 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
```

**Testing:** 

adjusted existing tests

**Documentation:** 

not sure if it's needed - sounds more like this is a bug fix

### CODE REVIEW

**Comment by zeitlinger** [comment]
@cyrille-leclerc fyi

**Review by ChrsMark — COMMENTED** [review]
Can you provide more details for the use-cases you want to cover with this? I assume these logs are split in multiple ones wrapped by the runtime? However, I'd like to see a multi-line example input log that you are trying to parse. By looking into the modified tests that's not clear to me. 

What I'm trying to see here is if the parser itself should be capable of merging multi-line logs or that should happen in a different operator.

**Comment by zeitlinger** [comment]
> Can you provide more details for the use-cases you want to cover with this? I assume these logs are split in multiple ones wrapped by the runtime? However, I'd like to see a multi-line example input log that you are trying to parse. By looking into the modified tests that's not clear to me.
> 
> What I'm trying to see here is if the parser itself should be capable of merging multi-line logs or that should happen in a different operator.

added the complete example

**Comment by ChrsMark** [comment]
Yeap, that's what I had in mind as well. The same can happen with Docker runtime:

```
2024-07-02 08:43:04.283 ERROR 176 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Expected: controller used to showcase what happens when an exception is thrown] with root cause
java.lang.RuntimeException: Expected: controller used to showcase what happens when an exception is thrown
    at org.springframework.samples.petclinic.system.CrashController.triggerException(CrashController.java:33) ~[classes/:na]
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.21.jar:5.3.21]
    ....
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.64.jar:9.0.64]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787) ~[tomcat-embed-core-9.0.64.jar:9.0.64]
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.64.jar:9.0.64]
    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.64.jar:9.0.64]
    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.64.jar:9.0.64]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.64.jar:9.0.64]
    at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

which on the disk is:

```
{"log":"2024-07-02 08:43:04.283 ERROR 176 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Expected: controller used to showcase what happens when an exception is thrown] with root cause\n","stream":"stdout","time":"2024-07-02T08:43:04.283844229Z"}
{"log":"\n","stream":"stdout","time":"2024-07-02T08:43:04.283868402Z"}
{"log":"java.lang.RuntimeException: Expected: controller used to showcase what happens when an exception is thrown\n","stream":"stdout","time":"2024-07-02T08:43:04.283870938Z"}
{"log":"\u0009at org.springframework.samples.petclinic.system.CrashController.triggerException(CrashController.java:33) ~[classes/:na]\n","stream":"stdout","time":"2024-07-02T08:43:04.283872781Z"}
{"log":"\u0009at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]\n","stream":"stdout","time":"2024-07-02T08:43:04.283874835Z"}
{"log":"\u0009at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]\n","stream":"stdout","time":"2024-07-02T08:43:04.283876532Z"}
....
{"log":"\u0009at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.64.jar:9.0.64]\n","stream":"stdout","time":"2024-07-02T08:43:04.284011979Z"}
{"log":"\u0009at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787) ~[tomcat-embed-core-9.0.64.jar:9.0.64]\n","stream":"stdout","time":"2024-07-02T08:43:04.284014543Z"}
{"log":"\u0009at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.64.jar:9.0.64]\n","stream":"stdout","time":"2024-07-02T08:43:04.284017264Z"}
{"log":"\u0009at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.64.jar:9.0.64]\n","stream":"stdout","time":"2024-07-02T08:43:04.284019903Z"}
{"log":"\u0009at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.64.jar:9.0.64]\n","stream":"stdout","time":"2024-07-02T08:43:04.284022413Z"}
{"log":"\u0009at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.64.jar:9.0.64]\n","stream":"stdout","time":"2024-07-02T08:43:04.284025068Z"}
{"log":"\u0009at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]\n","stream":"stdout","time":"2024-07-02T08:43:04.284027625Z"}
{"log":"\n","stream":"stdout","time":"2024-07-02T08:43:04.284030563Z"}
```

Even though I see how supporting this will be useful, I'm not sure if this is something that the container parser should handle as I mentioned already. The scope of the container parser is to parse the known formats and for the parser itself a container log is a standalone item unless it's explicitly said to `recombine` this based on the `P` and `F` tags.
So I wonder if this multi-line merging logic should be applied after the items are parsed with another existent or new operator.

Otherwise if we want to make this logic part of the container parser we should provide the option to explicitly enable this through a setting, clearly document this and provide standalone tests for this.

This will ensure that we won't extend the patterns by default which might mix things up if users accidentally feed the parser/operator with items that match the multi-line pattern:

For example, after some specific set of operations the following ends up in the input of the parser: 
```
{"log":"This is a legit standalone line\n","stream":"stdout","time":"2024-07-02T08:43:04.284027625Z"}
{"log":"This is another legit standalone line\n","stream":"stdout","time":"2024-07-02T08:43:04.284030563Z"}
```

Based on the current patch this will be parsed as `This is a legit standalone line\nThis is another legit standalone line` while it shouldn't.

I would love to heart @djaglowski 's opinion here as well.

Also @TylerHelmuth since the parser covers what the [Helm preset](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-collector-0.95.0/charts/opentelemetry-collector/templates/_config.tpl#L206-L282) was implementing, do you maybe know if this use-case/issue was already reported for the preset as well?

**Comment by zeitlinger** [comment]
> Even though I see how supporting this will be useful, I'm not sure if this is something that the container parser should handle as I mentioned already. The scope of the container parser is to parse the known formats and for the parser itself a container log is a standalone item unless it's explicitly said to `recombine` this based on the `P` and `F` tags. (a bit relevant to how CRI-O treats new-lines/multi-lines: [cri-o/cri-o#5903](https://github.com/cri-o/cri-o/issues/5903)) So I wonder if this multi-line merging logic should be applied after the items are parsed with another existent or new operator.

do you have an alternative proposal?

> Otherwise if we want to make this logic part of the container parser we should provide the option to explicitly enable this through a setting, clearly document this and provide standalone tests for this.

from the users point of view, I think it's clear, because the multiline operator is used.
would it make sense to somehow look if multiline is enabled?

**Comment by djaglowski** [comment]
> > Even though I see how supporting this will be useful, I'm not sure if this is something that the container parser should handle as I mentioned already. The scope of the container parser is to parse the known formats and for the parser itself a container log is a standalone item unless it's explicitly said to `recombine` this based on the `P` and `F` tags. (a bit relevant to how CRI-O treats new-lines/multi-lines: [cri-o/cri-o#5903](https://github.com/cri-o/cri-o/issues/5903)) So I wonder if this multi-line merging logic should be applied after the items are parsed with another existent or new operator.
> 
> do you have an alternative proposal?

I believe the `recombine` operator should be able to handle this. Have you ruled this out? If so, what is the reason?

Barring a reason why `recombine` does not work, I think I agree with @ChrsMark. There is potentially a case to be made that there should be an equivalent way to grab multiline logs regardless of whether they are written through a container runtime, but the reality is that even if we support this feature, the configuration is not equivalent. That is, the user must still write the multiline format in quite a strange way to work around the container wrapper format. e.g. `'.*stdout F \d{4}-'` is a strange way to say "each log starts with a timestamp". I think it would be better to remove the wrapper in a generic way first and then reason about putting the lines back together into a single log, which is exactly what the `recombine` operator does.

> > Otherwise if we want to make this logic part of the container parser we should provide the option to explicitly enable this through a setting, clearly document this and provide standalone tests for this.
> 
> from the users point of view, I think it's clear, because the multiline operator is used. would it make sense to somehow look if multiline is enabled?

I think it's somewhat unclear from the user point of view, because there is a question of whether the multiline pattern is focused on the actual log content, or the way it appears in the file as wrapped in the container format. Documentation could help here but conceptually I think there is a distinction between the way it would actually have to work and the way I'd naturally expect it to work as a user. If the multiline config could be exactly the same as it would be without the container wrapper, then I'd be more in favor of this.

Finally, 100% agree and want to emphasize the point that _if_ we move forward with this we certainly should leave all existing test cases in place so that we know we aren't breaking anything. New tests should be added without changing the existing ones.

**Comment by zeitlinger** [comment]
oh, `recombine` is much better - I didn't see that before.

Thanks for taking the patience to explain :smile: 

For reference, here is the config I'm using now: https://github.com/cyrille-leclerc/my-shopping-cart/blob/78603dacaa436656fd6875c75faf19447ac6c460/k8s/collector-configmap.yaml#L23-L34

**Comment by ChrsMark** [comment]
@zeitlinger great to see that worked!

I think it would make sense to have this use-case as part of the [documentation examples](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.104.0/receiver/filelogreceiver#example---multiline-logs-parsing)?

**Comment by zeitlinger** [comment]
> @zeitlinger great to see that worked!
> 
> I think it would make sense to have this use-case as part of the [documentation examples](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.104.0/receiver/filelogreceiver#example---multiline-logs-parsing)?

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33913

**Pull request closed without merging**
