### PR TITLE
[extension/bearertokenauth] Implement server authenticator

### PR DESCRIPTION
**Pull request by svrakitin**
**Description:** 
Implemented `configauth.ServerAuthenticator` for `bearertokenauth` to be able to use it with receivers.

**Documentation:** 
Added examples with receiver usage.

### CODE REVIEW

**Comment by jpkrohling** [comment]
I see how this could be useful, but I'd rather create another extension for this, with a different name. A bearer token is typically a JWT, which might be signed. The server then just validates the token against the signature. This change here just checks whether a specific string is provided by the caller, much like a static password validation. Having both features in the same component would certainly confuse users.

**Comment by svrakitin** [comment]
@jpkrohling Thanks for a quick reply. Makes sense. It was just convenient to make this extension symmetric as it already implements `configauth.ClientAuthenticator`. :)

I was looking for a way to have some kind of dummy authentication for public collector instances used by web clients and couldn't find any. 

Do you mean something like `basicauth` extension?

**Comment by jpkrohling** [comment]
Yes. Would you be open to contribute a new `basicauth` extension? It could read an input file similar to httpd's htpasswd.

**Comment by svrakitin** [comment]
@jpkrohling Sure, will make a new PR.

**Pull request closed without merging**
