### PR TITLE
- Force windows to fail

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
Working around skipped tests.

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
Not sure why it skipped windows.

**Comment by dmitryax** [comment]
Thanks, @MovieStoreGuy!

**Comment by MovieStoreGuy** [comment]
> Thanks, @MovieStoreGuy!

No worries! 

It looks like it works, I am just double checking that if there is a test failure on linux runners, they still fail.

**Comment by MovieStoreGuy** [comment]
Sweet, sorry reset the head and removed the change that broke for linux tests.

I won't have time to fix the failing windows tests til tomorrow @dmitryax , are you okay to wait that long?

**Comment by dmitryax** [comment]
> I won't have time to fix the failing windows tests til tomorrow @dmitryax , are you okay to wait that long?

No problem at all. It's not an urgent issue. I'll try to look into some of them as well

Thank you!

**Comment by dmitryax** [comment]
@MovieStoreGuy I fixed some tests in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17194 PTAL

**Comment by dmitryax** [comment]
@MovieStoreGuy please rebase, we should be good now

**Comment by MovieStoreGuy** [comment]
Still a test that needs fixing :(

**Comment by atoulme** [comment]
```
2022-12-22T03:13:22.8079957Z === RUN   TestReceiverFlowControlDelayedRetry/Without_error
2022-12-22T03:13:22.8080350Z     receiver_test.go:393: 
2022-12-22T03:13:22.8081346Z         	Error Trace:	D:\a\opentelemetry-collector-contrib\opentelemetry-collector-contrib\receiver\solacereceiver\receiver_test.go:393
2022-12-22T03:13:22.8082037Z         	Error:      	receiveMessage did not return after delay interval
2022-12-22T03:13:22.8082943Z         	Test:       	TestReceiverFlowControlDelayedRetry/Without_error
2022-12-22T03:13:22.8083378Z === RUN   TestReceiverFlowControlDelayedRetry/With_error
2022-12-22T03:13:22.8083880Z --- FAIL: TestReceiverFlowControlDelayedRetry (0.04s)
2022-12-22T03:13:22.8084619Z     --- FAIL: TestReceiverFlowControlDelayedRetry/Without_error (0.02s)
2022-12-22T03:13:22.8085224Z     --- PASS: TestReceiverFlowControlDelayedRetry/With_error (0.01s)
2022-12-22T03:13:22.8085663Z === RUN   TestReceiverFlowControlDelayedRetryInterrupt
2022-12-22T03:13:22.8086192Z --- PASS: TestReceiverFlowControlDelayedRetryInterrupt (0.02s)
2022-12-22T03:13:22.8086668Z === RUN   TestReceiverFlowControlDelayedRetryMultipleRetries
2022-12-22T03:13:22.8087399Z     receiver_test.go:507: 
2022-12-22T03:13:22.8088367Z         	Error Trace:	D:\a\opentelemetry-collector-contrib\opentelemetry-collector-contrib\receiver\solacereceiver\receiver_test.go:507
2022-12-22T03:13:22.8089383Z         	Error:      	receiveMessage did not return after some time
2022-12-22T03:13:22.8090167Z         	Test:       	TestReceiverFlowControlDelayedRetryMultipleRetries
2022-12-22T03:13:22.8090770Z --- FAIL: TestReceiverFlowControlDelayedRetryMultipleRetries (0.04s)
```

**Comment by dmitryax** [comment]
@MovieStoreGuy PTAL https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17198

**Comment by dmitryax** [comment]
@MovieStoreGuy please rebase

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
