### PR TITLE
dependabot updates Mon  2 May 2022 11:41:28 PDT

### PR DESCRIPTION
**Pull request by codeboten**
Bump github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common from 1.0.390 to 1.0.392 in /exporter/tencentcloudlogserviceexporter
Bump github.com/aws/aws-sdk-go from 1.43.45 to 1.44.5 in /internal/aws/cwlogs
Bump google.golang.org/api from 0.76.0 to 0.77.0 in /receiver/googlecloudspannerreceiver
Bump github.com/aws/aws-sdk-go from 1.43.45 to 1.44.4 in /exporter/kafkaexporter
Bump github.com/go-playground/validator/v10 from 10.10.1 to 10.11.0 in /cmd/mdatagen
Bump go.opentelemetry.io/otel/exporters/otlp/otlptrace from 1.6.3 to 1.7.0 in /examples/demo/client
Bump go.opentelemetry.io/otel from 1.6.3 to 1.7.0 in /examples/demo/server
Bump go.opentelemetry.io/otel from 1.6.3 to 1.7.0 in /examples/demo/client
Bump go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp from 0.31.0 to 0.32.0 in /examples/demo/server
Bump go.opentelemetry.io/otel from 1.6.3 to 1.7.0 in /receiver/opencensusreceiver
Bump go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc from 1.6.1 to 1.7.0 in /examples/demo/client
Bump github.com/aws/aws-sdk-go from 1.43.45 to 1.44.4 in /internal/aws/proxy
Bump go.opentelemetry.io/otel/trace from 1.6.3 to 1.7.0 in /receiver/opencensusreceiver
Bump go.opentelemetry.io/otel/sdk/metric from 0.29.0 to 0.30.0 in /examples/demo/client
Bump go.opentelemetry.io/otel/sdk/metric from 0.29.0 to 0.30.0 in /examples/demo/server
Bump github.com/shirou/gopsutil/v3 from 3.22.3 to 3.22.4 in /receiver/hostmetricsreceiver
Bump github.com/google/go-cmp from 0.5.7 to 0.5.8 in /pkg/translator/opencensus
Bump go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc from 0.31.0 to 0.32.0 in /receiver/opencensusreceiver
Bump github.com/google/go-cmp from 0.5.7 to 0.5.8 in /pkg/translator/zipkin
Bump go.opentelemetry.io/otel/metric from 0.29.0 to 0.30.0 in /examples/demo/server
Bump github.com/aws/aws-sdk-go from 1.43.45 to 1.44.4 in /exporter/awscloudwatchlogsexporter
Bump go.opentelemetry.io/otel/sdk from 1.6.3 to 1.7.0 in /receiver/opencensusreceiver
Bump go.opentelemetry.io/otel/sdk from 1.6.3 to 1.7.0 in /examples/demo/client
Bump go.opentelemetry.io/otel/trace from 1.6.3 to 1.7.0 in /examples/demo/server
Bump github.com/aws/aws-sdk-go from 1.43.45 to 1.44.4 in /internal/aws/k8s
Bump go.opentelemetry.io/otel/metric from 0.29.0 to 0.30.0 in /examples/demo/client
Bump cloud.google.com/go/pubsub from 1.20.0 to 1.21.0 in /receiver/googlecloudpubsubreceiver
Bump google.golang.org/api from 0.76.0 to 0.77.0 in /receiver/googlecloudpubsubreceiver
Bump github.com/google/cadvisor from 0.44.0 to 0.44.1 in /receiver/awscontainerinsightreceiver
Bump google.golang.org/api from 0.76.0 to 0.77.0 in /exporter/googlecloudpubsubexporter

### CODE REVIEW

**Comment by dmitryax** [comment]
@codeboten tests are failing. looks like due to breaking change in go otel library

**Comment by codeboten** [comment]
> @codeboten tests are failing. looks like due to breaking change in go otel library

@dmitryax yeah a missed dependency update in the example server code

**Comment by dmitryax** [comment]
@codeboten if you are updating coreto the latest, this PR is needed as well https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9689

**Comment by codeboten** [comment]
I've split the changes to remove `SetName` into a separate PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9690

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
