### PR TITLE
fix: Fix prometheus compliance test

### PR DESCRIPTION
**Pull request by martin-majlis-s1**
**Description:** 

It looks to me, that the compliance test is not correctly reporting it's status:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31293#issuecomment-1948438693

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7931518095/job/21655935440?pr=31293#step:8:77
```
=== NAME  TestRemoteWrite/otelcollector/Counter
    counter.go:35: 
        	Error Trace:	counter.go:35
        	            				main_test.go:106
        	            				main_test.go:70
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Counter
        	Messages:   	found zero samples for {__name__="counter"}
```

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by martin-majlis-s1** [comment]
And now it has indeed failed - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7931735859/job/21656631587?pr=31294#step:8:124

```
FAIL
FAIL	github.com/prometheus/compliance/remote_write	55.663s
FAIL
Error: Process completed with exit code 1.
```

**Comment by TylerHelmuth** [comment]
Can you fix the failing test as part of this PR?

**Comment by martin-majlis-s1** [comment]
@TylerHelmuth : Yes, I wanted to divide this into two steps:
1. Fix the pipeline, so that it fails.
2. Fix the test, so it's passing again

**Comment by martin-majlis-s1** [comment]
The failing test is in the https://github.com/prometheus/compliance - 
https://github.com/prometheus/compliance/blob/12cbdf92abf7737531871ab7620a2de965fc5382/remote_write_sender/cases/counter.go#L35

**Comment by martin-majlis-s1** [comment]
When I check the GHA: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/prometheus-compliance-tests.yml?query=branch%3Amain

I can see, that even on December 6th it was already failing - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7117309131/job/19377748117

I am not able to get to logs from older dates - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4089714931/job/11104774320

**Pull request closed without merging**
