### PR TITLE
Update Prometheus to latest

### LINKED ISSUE #7162: [prometheusreceiver] Update Prometheus libraries to latest versions in prometheus receivers.
**Is your feature request related to a problem? Please describe.**

The current prometheus receiver imports a very old version of prometheus libraries ( `github.com/prometheus/prometheus v1.8.2-0.20210621150501-ff58416a0b02` )  and many important features (some features include tls configurations, https2 support) and bug fixes has gone into them ever since. We need to update to latest version  (2.32.1 / 2021-12-17) to pick those changes if possible.

### PR DESCRIPTION
**Pull request by gouthamve**
This updates the Prometheus dependency to the latest version

This allows us to import some exporters as libraries into my own projects.

Closes #7162

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@Aneurysm9, would you mind taking a look at this one?

**Review by dashpole — APPROVED** [review]
As a note, this does not enable the new "extra scrape metrics": https://prometheus.io/docs/prometheus/latest/feature_flags/#extra-scrape-metrics, which could be done via `scrape.Options{}` in metrics_receiver.go.

**Comment by jpkrohling** [comment]
@gouthamve, could you take a look at the CI failures?

**Comment by Aneurysm9** [comment]
This requires updates to the `go.mod` files of each module using the new dependency.

What about the `prometheusexporter`?

**Comment by Aneurysm9** [comment]
Please run `make gotidy`.  That should fix the issues the CI process is having.

**Comment by jpkrohling** [comment]
Unfortunately, there are go.mod conflicts. Once they are fixed, I'll re-run the tests and merge on gren.

**Review by codeboten — COMMENTED** [review]
Looks like it needs one more `make gotidy`

```
go test -race -v -timeout 300s --tags="" ./...
go: updates to go.mod needed; to update it:
	go mod tidy
```

**Pull request merged**
