### PR TITLE
Added akats7 as codeowner

### PR DESCRIPTION
**Pull request by akats7**
**Description:** 
Hey @crobert-1, got the codeowners are not members error when running `make update-codeowners`. Is that still the correct way to add myself to the codeowners file, should I add my id manually?

### CODE REVIEW

**Comment by crobert-1** [comment]
Can you share your error message? I see you're a [member of the OpenTelemetry community](https://github.com/open-telemetry/community/issues/1872) so I want to confirm it's not failing on your username.

Otherwise, if the command isn't working, you can add yourself manually to the `CODEOWNERS` file.

**Comment by akats7** [comment]
> Can you share your error message? I see you're a [member of the OpenTelemetry community](https://github.com/open-telemetry/community/issues/1872) so I want to confirm it's not failing on your username.
> 
> Otherwise, if the command isn't working, you can add yourself manually to the `CODEOWNERS` file.

Its includes a good chunk of other users as well

**Comment by atoulme** [comment]
You're not a member of the opentelemetry organization and cannot query for members of the organization via the REST API.

**Comment by crobert-1** [comment]
> Its includes a good chunk of other users as well

This is actually an access token issue, you need to [set up a personal access token to be able to properly run](https://github.com/open-telemetry/community/issues/1872) `make update-codeowners`.

You're welcome to update it either way.

**Comment by akats7** [comment]
> > Its includes a good chunk of other users as well
> 
> This is actually an access token issue, you need to [set up a personal access token to be able to properly run](https://github.com/open-telemetry/community/issues/1872) `make update-codeowners`.
> 
> You're welcome to update it either way.

Hmm I was getting an auth error before and then generated a new PAT, maybe missed somethign

**Review by crobert-1 — APPROVED** [review]

**Review by fatsheep9146 — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
