### PR TITLE
[chore] bump prometheus/go-hdb packages

### LINKED ISSUE #24881: Failing to upgrade github.com/SAP/go-hdb to 1.3.13
Failing to upgrade github.com/SAP/go-hdb to 1.3.13 due to a backward incompatible change in golang.org/x/exp https://github.com/golang/exp/commit/302865e7556b4ae5de27248ce625d443ef4ad3ed#diff-ec22fd7f0aec27f1c6dc503e7dd3960c8f5ab781684218aa59b404ada0d48231R29

github.com/SAP/go-hdb was updated https://github.com/SAP/go-hdb/commit/867f8ecebe1614799bec77b03ab3ec8bff1087ff#diff-bd895b31b8e89a49fd8420f2fbdd9bfc78046bd2eefd9c5f5b848c643e9c8d9b while github.com/prometheus/prometheus uses the old version which causes the compile failure:

```
# github.com/prometheus/prometheus/model/labels
../../../../go/pkg/mod/github.com/prometheus/prometheus@v0.44.0/model/labels/labels.go:365:23: type func(a Label, b Label) bool of func(a, b Label) bool {…} does not match inferred type func(a Label, b Label) int for func(a E, b E) int
../../../../go/pkg/mod/github.com/prometheus/prometheus@v0.44.0/model/labels/labels.go:389:23: type func(a Label, b Label) bool of func(a, b Label) bool {…} does not match inferred type func(a Label, b Label) int for func(a E, b E) int
../../../../go/pkg/mod/github.com/prometheus/prometheus@v0.44.0/model/labels/labels.go:594:24: type func(a Label, b Label) bool of func(a, b Label) bool {…} does not match inferred type func(a Label, b Label) int for func(a E, b E) int
../../../../go/pkg/mod/github.com/prometheus/prometheus@v0.44.0/model/labels/labels.go:621:25: type func(a Label, b Label) bool of func(a, b Label) bool {…} does not match inferred type func(a Label, b Label) int for func(a E, b E) int
```

### PR DESCRIPTION
**Pull request by codeboten**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24881

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Looks like this broke the prometheus test: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6897605038/job/18766528283?pr=29314#step:9:378

**Comment by codeboten** [comment]
> Looks like this broke the prometheus test: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6897605038/job/18766528283?pr=29314#step:9:378

Yeah I'm looking into it 😠

**Comment by codeboten** [comment]
I updated the prometheus receiver to ignore a context cancelled error if it's returned by the discovery manager's `Run` func. This change https://github.com/prometheus/prometheus/pull/10569 was causing the component to record a fatal error on shutdown

**Comment by dmitryax** [comment]
Thank you, @codeboten !

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
