### PR TITLE
[chore] fix exhaustive lint for deltatorate processor

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** 
related #23266

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Comment by fatsheep9146** [comment]
ping owner for review @Aneurysm9

**Review by codeboten — APPROVED** [review]

**Comment by atoulme** [comment]
Please resolve the conflict.

**Comment by atoulme** [comment]
Please resolve the conflict.

**Comment by fatsheep9146** [comment]
@atoulme @codeboten After check about the processor, I found this processor do not use pmetric.MetricType const in any switch, so this pr could be closed.

**Pull request closed without merging**
