### PR TITLE
add transform processor to components

### PR DESCRIPTION
**Pull request by ljmsc**
**Description:** added the transform processor to the loaded components so it can be used

### CODE REVIEW

**Comment by djaglowski** [comment]
@anuraaga @Aneurysm9 @bogdandrutu, as the component owners, should this be part of the contrib collector yet?

**Comment by ljmsc** [comment]
> @anuraaga @Aneurysm9 @bogdandrutu, as the component owners, should this be part of the contrib collector yet?

if this shouldn't be part of the contrib collector yet, a comment in the processor readme would be helpful. Currently there is no hint to see why this processor is not working.

**Comment by TylerHelmuth** [comment]
I believe the `transformprocessor` still falls into the "In Developement" stability level.  I think it should not be added to the distro yet, but should have its README updated to match the new Stability Level definitions.

**Comment by ljmsc** [comment]
@TylerHelmuth  thanks for the feedback. I would appreciate it if you update the README. I will close this PR.

**Pull request closed without merging**
