### PR TITLE
[exporter/doris] Second PR (with metrics Implementation) of New component: Doris Exporter

### PR DESCRIPTION
**Pull request by joker-star-l**
**Description:** <Describe what has changed.>

Second PR of New component: Doris Exporter. Implementation of metrics.

**Link to tracking Issue:** #33479 

**Testing:** 

Tested via unit test.

**Documentation:** <Describe the documentation added.>

No additional documentation.

### CODE REVIEW

**Comment by joker-star-l** [comment]
@atoulme Hello, Is there any problem with this PR?

**Comment by atoulme** [comment]
Maybe this can use more unit test coverage, but overall looks ok for a first push.

**Review by atoulme — APPROVED** [review]

**Comment by joker-star-l** [comment]
> Maybe this can use more unit test coverage, but overall looks ok for a first push.

Ok. Thank you.

**Comment by joker-star-l** [comment]
Could someone help me merge this pr?

**Comment by joker-star-l** [comment]
Could someone help me merge this pr? Sorry to ask again.

**Pull request merged**
