### PR TITLE
[receiver/kubeletstats] Do not use multiple metrics builders

### PR DESCRIPTION
**Pull request by dmitryax**
This is a refactoring change to replace multiple metrics builder with one instance.

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
I thought metrics builder couldn't handle kubeletstat's use case with one metric builder. Did the new ability to change start time change that?

**Comment by dmitryax** [comment]
> Did the new ability to change start time change that?

Yes, exactly :)

**Review by TylerHelmuth — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please resolve the conflicts

**Comment by TylerHelmuth** [comment]
@dmitryax do we still need this?

**Comment by dmitryax** [comment]
I had another idea on my mind about this. So it's ok to drop this PR. I'll prepare another one later

**Pull request closed without merging**
