### PR TITLE
[connector/spanmetrics] Change default value of metrics_flush_interval from 15s to 60s

### LINKED ISSUE #31776: [connectors/spanmetrics] Set default metrics_flush_interval=60s
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

The default time interval between the start of two metrics export attempts (`OTEL_METRIC_EXPORT_INTERVAL`) is 60 seconds:  https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#periodic-exporting-metricreader

The default time interval to export metrics generated by spanmetrics should be the same as for regular metrics: 60s instead of 15s for consistency

Having a default flush interval of 15s comes at 4x the cost for users.

### Describe the solution you'd like

Set default `metrics_flush_interval` to 60s

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mar4uk**
**Description:** <Describe what has changed.>
Changed default value of `metrics_flush_interval` setting from 15s to 60s

**Link to tracking Issue:** Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31776

**Testing:** Fixed unit tests

**Documentation:** updated README

### CODE REVIEW

**Comment by crobert-1** [comment]
Just a nit, can you update your PR description to say:
```
Link to tracking Issue: Resolves #31776
```
Having `Resolves` or `Fixes` allows our CI to auto-close the issue 👍

**Review by crobert-1 — APPROVED** [review]

**Comment by djaglowski** [comment]
@portertech, any thoughts on this as code owner?

**Review by djaglowski — APPROVED** [review]

**Comment by portertech** [comment]
@djaglowski thank you for taking care of this, I was away from my desk for a few weeks. Curious, do you consider this a breaking change?

**Comment by djaglowski** [comment]
Yeah, strictly speaking this should probably be considered a breaking change. WDYT though?

**Pull request merged**
