### PR TITLE
[processor/tailsampling] Add metric for sampled/not sampled spans 

### LINKED ISSUE #30482: New counter metric showing number of sampled/not sampled spans
### Component(s)

processor/tailsampling

### Is your feature request related to a problem? Please describe.

I was debugging the input/output rate of spans of a few collectors and was super confused about the numbers I was seeing.

The metric `rate(otelcol_receiver_accepted_spans[5m])` was showing around 12k spans/second, and `rate(otelcol_processor_tail_sampling_count_traces_sampled{policy="mypolicy", sampled="false"}[5m])` was showing around 1k spans/second. Without any failures in the whole pipeline, I was expecting to see an output rate of 11k spans/second when looking at `rate(otelcol_exporter_sent_spans[5m])`, however, the numbers were showing only 6k spans/second.

@matej-g helped me with this and showed how the metric `otelcol_processor_tail_sampling_count_traces_sampled` is actually about traces, not spans, as the name suggests.

### Describe the solution you'd like

It would be useful to have a metric showing the number of sampled/not sampled spans, to verify if input/output rate of spans is working as expected.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ArthurSens**
**Description:** <Describe what has changed.>
Add metrics to measure sampled/not sampled spans.

**Link to tracking Issue:** 
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30482

**Testing:** <Describe what testing was performed and which tests were added.>
None

**Documentation:** <Describe the documentation added.>
None

### CODE REVIEW

**Comment by ArthurSens** [comment]
That's my first time reading the collector codebase, I'm not sure how to build and verify the changes work as I expect 😅

I've tried looking for tests that verify metric values but couldn't find any. Or at least I looked at the wrong place. Do you think they should be added now?

**Comment by tiithansen** [comment]
> That's my first time reading the collector codebase, I'm not sure how to build and verify the changes work as I expect 😅
> 
> I've tried looking for tests that verify metric values but couldn't find any. Or at least I looked at the wrong place. Do you think they should be added now?

There are still some discussions ongoing under the related issue. I will update the PR soon.

**Comment by ArthurSens** [comment]
Sorry for the ping @dashpole @jpkrohling, it's a small PR 😬 

Is there something else I should be doing to get the PR reviewed?

**Review by jpkrohling — COMMENTED** [review]
Sorry for the delay in reviewing this! Given that there might be performance implications in counting the number of spans in a batch, and that this is enabled by default, I would be more comfortable if this was placed behind a feature flag, at least for a couple of versions. Other than that, it looks good to me.

**Review by jpkrohling — APPROVED** [review]

**Comment by ArthurSens** [comment]
Rebase done! Should be ready to merge :)

**Pull request merged**
