### PR TITLE
Remove deprecated in v0.60.0 `extension/headerssetter` module.

### PR DESCRIPTION
**Pull request by kovrus**
**Description:** <Describe what has changed.>

Remove deprecated in v0.60.0 `extension/headerssetter` module. After renaming `extension/headerssetter` to `extension/headerssetterextension` we  kept `extension/headerssetter` module for bwc, see discussion in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13900

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13774

### CODE REVIEW

**Comment by kovrus** [comment]
cc: @mar4uk @gouthamve

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
@kovrus please rebase

**Review by codeboten — COMMENTED** [review]
It looks like go.mod and go.sum are still in the directory causing the codeowners check to fail:

```
FAIL: "extension/headerssetter" not included in CODEOWNERS
```

**Review by jpkrohling — APPROVED** [review]
If the CI turns green, this is ready to be merged.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
