### PR TITLE
[chore] Update collector core dependencies

### PR DESCRIPTION
**Pull request by dmitryax**
Run `make update-otel`

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Review by evan-bradley — COMMENTED** [review]
A search for `default = 5000` in the repo shows that there's a few more exporters where the docs should be updated to reflect the new exporterhelper default queue size. The Dynatrace exporter readme will also need to be updated.

**Comment by dmitryax** [comment]
> A search for default = 5000 in the repo shows that there's a few more exporters where the docs should be updated to reflect the new exporterhelper default queue size. The Dynatrace exporter readme will also need to be updated.

Sure, let me do that.

**Comment by dmitryax** [comment]
Looking into failing load tests before proceeding

**Comment by dmitryax** [comment]
Test failures are expected: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21656

**Pull request merged**
