### PR TITLE
[chore] add @JaredTan95 as triager

### LINKED ISSUE #20897: REQUEST: Add @JaredTan95 as triager
### Component(s)

_No response_

### Describe the issue you're reporting

Hi, 
Currently, I am the code owner of `Skywalking Receiver` and `ElasticSearch Exporter`, and  I also contributed a lot of features to other `processors`.

I am also currently a member of the OTEL organization and I love to be involved and help the community grow positively.
So, I would like to request to become a `Triager` now.

My Github account: @JaredTan95
My PRs: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3AJaredTan95+is%3Aclosed

@atoulme thx for your guidelines~

### PR DESCRIPTION
**Pull request by JaredTan95**
close https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20897

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by dmitryax** [comment]
@JaredTan95 Please add yourself to [this list](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/auto_assign.yml#L13) as well

**Comment by JaredTan95** [comment]
> this list

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/auto_assign.yml#L13 means approvers? So, Do I also need to add myself as an `approver` in [READEME.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/README.md) ?

**Comment by dmitryax** [comment]
> [auto_assign.yml#L13](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/auto_assign.yml#L13) means approvers? So, Do I also need to add myself as an approver in [READEME.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/README.md) ?

Sorry. My bad. I though we auto assign triagers as well

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
