### PR TITLE
28825 count connector resource attributes

### PR DESCRIPTION
**Pull request by 0x006EA1E5**
**Description:** <Describe what has changed.>
Adding a feature:  for count connector, making resource attributes available in addition to attributes

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28825
**Testing:** <Describe what testing was performed and which tests were added.>
Added tests to connector/countconnector/connector_test.go
**Documentation:** <Describe the documentation added.>
None yet...

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please add a changelog

**Comment by crobert-1** [comment]
There is ongoing discussion in the original issue, this shouldn't be merged until the discussion is complete.

**Comment by jpkrohling** [comment]
> There is ongoing discussion in the original issue, this shouldn't be merged until the discussion is complete.

I converted this PR into a draft PR.

**Comment by djaglowski** [comment]
The original issue was closed based on the discussion so I'm closing this PR.

**Pull request closed without merging**
