### PR TITLE
[GoogleCloudSpannerReceiver]: Truncate metric label values for query …

### PR DESCRIPTION
**Pull request by varunraiko**
…text to 1024 characters

Introduced a new config truncate_text, which when set to true will truncate the query text to 1024 characters.

**Description:**
For Google Managed Prometheus(GMP) the limit for the metric label value is 1024 characters. The fields from the SPANNER_SYS.* tables of spanner can have some field values greater that 1024 characters. For example query text can be 64 KB. In order to support the spanner receiver for GMP we will perform the truncation of the metric label value before exporting the value.

**Link to tracking Issue:**
Closes #22075

**Testing:** 
Manual testing with local docker setup done. Unit tests were added for the new config change.
**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by architjugran** [comment]
Add link to tracking issue, and also describe why this change was needed.

Code LGTM

**Review by architjugran — APPROVED** [review]
Also mention that you have tested the changes end-to-end, as discussed offline

**Comment by varunraiko** [comment]
> 

Done

**Comment by varunraiko** [comment]
@jpkrohling a gentle reminder to review this PR?

**Comment by varunraiko** [comment]
@atoulme would it be possible for you to approve this?

**Review by songy23 — APPROVED** [review]

**Comment by varunraiko** [comment]
@songy23 can we merge this PR? We need to add the need-to-merge label, right?

**Comment by songy23** [comment]
@varunraiko label added, a maintainer will merge this PR (I don't have the permission).

**Review by codeboten — APPROVED** [review]

**Pull request merged**
