### PR TITLE
[processor/transform] support substring function

### PR DESCRIPTION
**Pull request by ralphgj**
**Description:** <Describe what has changed.>

Add substring function for transform processor .

**Link to tracking Issue:** <Issue number if applicable>
#17038

**Testing:** <Describe what testing was performed and which tests were added.>
Updated unit tests.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
Please also add an update on this within the readme

**Comment by TylerHelmuth** [comment]
@MovieStoreGuy this is an OTTL function and is described in the ottlfunc readme so we don't need a duplicate in the transform processor's

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by ralphgj** [comment]
I noticed that ottl functions usage seems to be listed in the readme of `pkg/ottl`, so should I also add the `substring` function in the readme of transform processor?

**Review by TylerHelmuth — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
@TylerHelmuth are you able to merge this?

**Comment by TylerHelmuth** [comment]
@MovieStoreGuy I can't bc I'm not a maintainer

**Comment by MovieStoreGuy** [comment]
> @MovieStoreGuy I can't bc I'm not a maintainer

I honestly thought you were, my bad.

**Pull request merged**
