### PR TITLE
Prepare for v0.57.2

### LINKED ISSUE #5773: Prepare contrib release v0.57.2

### PR DESCRIPTION
**Pull request by jpkrohling**
- Update changelog for v0.57.0
- Update versions.yaml
- Update core to v0.57.0

closes https://github.com/open-telemetry/opentelemetry-collector/issues/5773

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Looks like `exporter/datadogexporter/go.sum` was deleted?

**Comment by jpkrohling** [comment]
go.sum was deleted for DataDog's exporter because of a problem with a dependency (see #12934). This PR fixes that dependency on a specific revision, but would be good to have someone at DataDog to give their blessing that this version can safely be used. 

cc @KSerrania @mx-psi @gbbr @knusbaum @amenasria @dineshg13

**Comment by pmcollins** [comment]
@jpkrohling, would it be possible to get this change into the release, or is it too late -- it was merged about an hour ago and we have a customer that needs it:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12931

**Comment by jpkrohling** [comment]
v0.57.0 wasn't released yet for the contrib, so, it might indeed get in. The collector core was retagged with v0.57.1, but it shouldn't affect your component.

**Pull request closed without merging**
