### PR TITLE
[chore] use type in aerospike receiver

### PR DESCRIPTION
**Pull request by atoulme**
This uses metadata.Type in the code of the aerospike receiver.

### CODE REVIEW

**Review by evan-bradley — COMMENTED** [review]
I think this will need a changelog entry since we're changing the instrumentation scope name on the emitted metrics. Per the scraping receivers [stability guarantees](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/scraping-receivers.md#alpha) for a component with alpha stability, I think a breaking change will be fine here, but we can lean on the code owners to make that decision.

**Review by codeboten — CHANGES_REQUESTED** [review]
Requesting change for the same reason as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21272#pullrequestreview-1407890194, @atoulme could you open an issue to track this? It would be good to come to an agreement in the issue and reference it in any changes we make.

**Comment by atoulme** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21382 is filed

**Comment by atoulme** [comment]
No changes to scope name anymore, so we will be good with minimal changes now.

**Review by djaglowski — APPROVED** [review]

**Comment by atoulme** [comment]
@codeboten PTAL

**Review by codeboten — APPROVED** [review]

**Pull request merged**
