### PR TITLE
[mdatagen] [receiver/hostmetrics] Show warnings defined in metadata.yaml

### PR DESCRIPTION
**Pull request by dmitryax**
This change adds a metadata.yaml option to specify a warning that will be shown in case the metric is enabled. 

The new option is used to notify a user about recently deprecated `process.memory.physical_usage` and `process.memory.virtual_usage` metrics emitted by hostmetrics receiver. Look at [receiver/hostmetricsreceiver/internal/scraper/processscraper/metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16536/files#diff-76d9dfe8e00f40881e1643f4143c2d55a7c000a414fd45ac033c5adaf7fa2d35) how it's being applied.

### CODE REVIEW

**Comment by dmitryax** [comment]
@astencel-sumo PTAL

**Review by andrzej-stencel — COMMENTED** [review]
Thanks @dmitryax. If I understand correctly, this feature takes care of the warnings specified here:

- point 1. of [Removing a default metric](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.66.0/docs/scraping-receivers.md#removing-a-default-metric):
  > Show a warning that the metric will be removed if the enabled option is not explicitly set to false in user settings.

- point 2. of [Removing a default metric](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.66.0/docs/scraping-receivers.md#removing-a-default-metric):
  > Make the metric optional. Show a warning that the metric will be removed if the enabled option is set to true in user settings.

- point 1. of [Removing an optional metric](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.66.0/docs/scraping-receivers.md#removing-an-optional-metric):
  > Show a warning that the metric will be removed if the enabled option is set explicitly to true in user settings.

I suppose the other warnings described are not in scope of this change, is my understanding correct?

- step 1 of [Making a default metric optional](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.66.0/docs/scraping-receivers.md#making-a-default-metric-optional):
  > Add a warning that the metric will be turned into optional if enabled field is not set explicitly to any value in user settings.

- step 1. of [Adding a new default metric or turning an existing optional metric into default](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.66.0/docs/scraping-receivers.md#adding-a-new-default-metric-or-turning-an-existing-optional-metric-into-default):
  > Add a warning that the metric will be turned into default if the enabled option is not set explicitly to any value in user settings.

**Comment by dmitryax** [comment]
> I suppose the other warnings described are not in scope of this change, is my understanding correct?

Yes, I'll handle those separately. Goal of this PR is to solve the immediate need for the process scraper

**Review by andrzej-stencel — APPROVED** [review]

**Comment by dmitryax** [comment]
@djaglowski can you please take a look whenever you have a chance?

**Review by djaglowski — APPROVED** [review]
LGTM

**Pull request merged**
