### PR TITLE
[exporter/awss3] Add compression option (27872)

### LINKED ISSUE #27872: awss3export to support gzip
### Component(s)

exporter/awss3

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

When using AWS S3 exporter it would be nice to have ability to select compression for stored objects i.e. gzip

### Describe alternatives you've considered

Current workflow for storing gzipped data is to use AWS Kinesis Exporter and then through Firehose store data to s3 gzipped. But having ability to straightly upload gzipped files to S3 would drop the need to use separate Kinesis stream for just gzipping the data.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pepperkick**
**Description:**
Add `compression` option to compress files using `compress/gzip` library before uploading to S3.

**Link to tracking Issue:**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27872

**Testing:** 

Sent n number of traces through the S3 exporter using k6 to compare sizes. Used Minio as the S3 backend.
| Marshaler | Compression | k6 Requests | k6 Data Sent | S3 Objects | S3 Total Size | 
| --- | --- | --- | --- | --- | --- |
| otlp_json | No | 101 | 118 KB | 101 | 36 KB | 
| otlp_proto | No | 101 | 118 KB | 101 | 11 KB | 
| otlp_json | Yes | 101 | 118 KB | 101 | 21 KB | 
| otlp_proto | Yes | 101 | 118 KB | 101 | 9.9 KB | 

Additionally, new unit test to check file name.

**Documentation:**
- Updated README.md file

### CODE REVIEW

**Comment by atoulme** [comment]
Please take a look at the failing build.

Do you expect the only compression will be .gz only? Could we have multiple types of compression?

**Comment by pepperkick** [comment]
> Please take a look at the failing build.

```
=== Failed
make[2]: *** [../../Makefile.Common:131: test-with-cover] Error 3
=== FAIL: . TestComponentLifecycle/metrics-shutdown (0.00s)
    generated_component_test.go:50: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/opencensusreceiver/generated_component_test.go:50
        	Error:      	Received unexpected error:
make[1]: *** [Makefile:165: receiver/opencensusreceiver] Error 2
make: *** [Makefile:117: gotest-with-cover] Error 2
        	            	failed to bind to address "0.0.0.0:55678": listen tcp 0.0.0.0:55678: bind: address already in use
        	Test:       	TestComponentLifecycle/metrics-shutdown

=== FAIL: . TestComponentLifecycle/traces-shutdown (0.00s)

=== FAIL: . TestComponentLifecycle (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x129e5fc]
```
Seems like there is some port conflict for opencensusreceiver in CI. Not sure but maybe parallel builds?

> Do you expect the only compression will be .gz only? Could we have multiple types of compression?

Good question, the issue only mentioned gzip and it is most used. Only other I can think of is zip compression via `archive/zip` library. 
I can make the compression enum type similar to the marshaler field so new options can be added in future. My concern in this case would be appending the file extension for various types.

**Comment by atoulme** [comment]
sorry for the leading question, I meant we can use the configcompression.Type type: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configcompression/compressiontype.go

I will look at the build and file an issue.

**Comment by pepperkick** [comment]
> sorry for the leading question, I meant we can use the configcompression.Type type: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configcompression/compressiontype.go

Updated code to reuse the `configcompression.Type`. Was not aware of this!

> I will look at the build and file an issue.

Thanks!

**Review by atoulme — APPROVED** [review]

**Pull request merged**
