### PR TITLE
[extension/headersetter] Rename `headerssetter` to `headerssetterextension`

### LINKED ISSUE #13774: Header setter module name should contain "extension"
I should have caught this during the review for the initial version: the header setter extension is currently named "headersetter" in the module and directory name within the "extension" package. Other components do have their types as part of the name, and this is our current convention, so, we should change this. To avoid breaking current users of that extension, we should probably just copy it to the corrected name and deprecate the current one.

### PR DESCRIPTION
**Pull request by kovrus**
**Description:** <Describe what has changed.>

Rename `headerssetter` to `headerssettersextension` and deprecate the `github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetter` module.

**Link to tracking Issue:** <Issue number if applicable>
Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13774

### CODE REVIEW

**Comment by dmitryax** [comment]
I don't think we should strive for maintaining a not breaking developer API in this repo at this point. As long as the configuration interface is not changed (I believe it's still `headersetter` in the config, right?), I'd recommend just moving the module.

cc @jpkrohling

**Comment by kovrus** [comment]
@open-telemetry/collector-contrib-approvers could someone from approvers and maintainer give their opinion on this open modules bwc approach?

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Need a rebase

**Comment by kovrus** [comment]
rebased

**Comment by kovrus** [comment]
cc: @jpkrohling can you please merge it?

**Pull request merged**
