### PR TITLE
[processor/metricstransformprocessor] fix copy exponential histogram

### LINKED ISSUE #27409: Copying an Exponential Histogram results in nil pointer dereference
### Component(s)

processor/metricstransform

## Description
Attempting to perform any operation that copies an exponential histogram will result in a nil pointer dereference error as the code currently calls the incorrect method on the metric. 

## Steps to Reproduce
Have a config that attempts an operation on an exponential histogram metric that results in a copy, such as `combine`

## Expected Result
The metric is correctly processed and exported.

## Actual Result
A nil pointer dereference error is printed to the logs. 

### Collector version

v0.86.0

## Environment
All

### OpenTelemetry Collector configuration

```yaml
processors:
  metricstransform:
    transforms:
      - include: ^<regex_for_exponential_histogram_metric>\.(?P<new_label>.+)$
        match_type: regexp
        action: combine
        new_name: new_metric
```

### Log output

```shell
service/service.go:161	Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2287efb]

goroutine 51 [running]:
go.opentelemetry.io/collector/pdata/pmetric.Histogram.AggregationTemporality(...)
	/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rcv0014/pmetric/generated_histogram.go:45
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mfranklin**
**Description:**
Fixes a bug where the wrong function was called for the exponential histogram type during the copy operation. 

**Link to tracking Issue:** 
Fixes #27409

**Testing:** 
Added a test for `combine` that covers the failing code path. 

**Documentation:** 
No documentation added as this is a simple bug fix.

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Thanks for the fix, @mfranklin!

**Comment by dmitryax** [comment]
@mfranklin can you please add a changelog item to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/.chloggen?

**Comment by crobert-1** [comment]
> @mfranklin can you please add a changelog item to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/.chloggen?

@mfranklin: You can run `make chlog-new` to create the changelog file under the directory Dmitrii's referenced. The [template](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.chloggen/TEMPLATE.yaml) describes what information should be included.

**Comment by mfranklin** [comment]
Changelog added.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
