### PR TITLE
exporter/datadogexporter: bump datadog-agent dependencies

### PR DESCRIPTION
**Pull request by gbbr**
This change bumps the datadog-agent dependencies to contain the latest changes re. removing deprecated pdata methods.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Can you rebase please?

**Review by bogdandrutu — APPROVED** [review]

**Comment by gbbr** [comment]
Done. Thanks for reviewing.

**Review by codeboten — COMMENTED** [review]
Looks like some more changes are needed here

```
../../../../go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/remoteconfig/state@v0.40.0-rc.2/tuf.go:34:20: rootClient.InitLocal undefined (type *client.Client has no field or method InitLocal)
```

**Comment by gbbr** [comment]
Thanks Alex. I reverted that change since it wasn't critical. We'll do it separately.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
