### PR TITLE
[processor/groupbytrace] Extend groupbytrace to logs

### PR DESCRIPTION
**Pull request by davidgargti20**
Extended groupbytrace processor to support logs also

### CODE REVIEW

**Comment by davidgargti20** [comment]
#11770

**Comment by davidgargti20** [comment]
@jpkrohling @dmitryax please review this.

**Comment by davidgargti20** [comment]
@jpkrohling @dmitryax can you please have a look at it

**Comment by jpkrohling** [comment]
I'll review the original issue, as I'm not quite sure right now whether we came to an agreement about this. If you got green light, I'll review this once the build is passing.

**Comment by davidgargti20** [comment]
@jpkrohling could you please look into the issues and tell me the cause of them

**Comment by davidgargti20** [comment]
> This line should have a few hints: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7305611876?check_suite_focus=true#step:8:163

yeah understood need to install porto thanks hopefully it should be resolved by the latest commit

**Comment by davidgargti20** [comment]
@jpkrohling all checks are passing can we have review now

**Review by jpkrohling — CHANGES_REQUESTED** [review]
As mentioned in an earlier comment, I'm not quite sure right now whether we came to an agreement about this. Therefore, I'm blocking this for now.

**Pull request closed without merging**
