### PR TITLE
receiver: migrate to configopaque.String

### PR DESCRIPTION
**Pull request by gbbr**
This change updates sensitive information described in #17273 for all receivers:

- [x] [receiver/aerospike] Use configopaque for password field
- [x] [receiver/awsfirehose] Use configopaque for access_key field
- [x] [receiver/bigip] Use configopaque for password field
- [x] [receiver/cloudfoundry] Use configopaque for password field
- [x] [receiver/couchdb] Use configopaque for password field
- [x] [receiver/elasticsearch] Use configopaque for password field
- [x] [receiver/jmx] Use configopaque for password, keystore_password, truststore_password fields
- [x] [receiver/mongodbatlas] Use configopaque for private_key and secret fields
- [x] [receiver/mongodb] Use configopaque for password field
- [x] [receiver/mysql] Use configopaque for password field
- [x] [receiver/nsxt] Use configopaque for password field
- [x] [receiver/podman] Use configopaque for ssh_passphrase field
- [x] [receiver/postgresql] Use configopaque for password field
- [x] [receiver/pulsar] Use configopaque for auth::Token::Token and auth::athenz::private_key fields
- [x] [receiver/rabbitmq] Use configopaque for password field
- [x] [receiver/redis] Use configopaque for password field
- [x] [receiver/riak] Use configopaque for password field
- [x] [receiver/saphana] Use configopaque for password field
- [x] [receiver/snmp] Use configopaque for auth_password and privacy_password fields
- [x] [receiver/snowflake] Use configopaque for password field
- [x] [receiver/solace] Use configopaque for password field
- [x] [receiver/vcenter] Use configopaque for password field

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
At first glance, the change seems ok to me. Since it is a change that's impacting many different components, I would suggest breaking it up by component.

One more question is whether this is a breaking change or not, as to the end user the change will not be breaking correct? It would only be for users of the components as libraries?

**Comment by gbbr** [comment]
Thanks for taking a look Alex. 

> At first glance, the change seems ok to me. Since it is a change that's impacting many different components, I would suggest breaking it up by component.

I was consulting with @mx-psi before starting and found it a bit tedious to have a separate PR for each component (along with its own individual issue) and asked if I could do them all as part of one PR and was told yes. If that's really important to you, I could split them...

> One more question is whether this is a breaking change or not, as to the end user the change will not be breaking correct? It would only be for users of the components as libraries?

I was following what was in the issue, but I had the same thought. The change log is meant to illustrate the perspective of the user, so in that sense, this is not a breaking change. I agree with that and would be happy to change.

**Comment by mx-psi** [comment]
>> At first glance, the change seems ok to me. Since it is a change that's impacting many different components, I would suggest breaking it up by component.

> I was consulting with @mx-psi before starting and found it a bit tedious to have a separate PR for each component (along with its own individual issue) and asked if I could do them all as part of one PR and was told yes. If that's really important to you, I could split them...

@gbbr @codeboten maybe, as a compromise, we can make a PR for the receivers that have only a `password` field to be made opaque (since, in principle, these should be very similar) and make separate PRs for the rest. Does that sound reasonable to you?

> as to the end user the change will not be breaking correct? It would only be for users of the components as libraries?

Indeed, it will only be a breaking change for users of the components as libraries. I think we generally note these in the changelog (at least for modules that are only libraries like `pkg/ottl`). IMO we should list it but make it clear that the changes are Go API only.

**Comment by gbbr** [comment]
@mx-psi @codeboten what did you decide for this PR? We've already merged a couple as batch changes, maybe we can merge this one too?

**Comment by mx-psi** [comment]
I will leave this up to @codeboten; I can help splitting this if necessary

**Comment by mx-psi** [comment]
@codeboten what should we do about this PR? Should we split it in any way?

**Pull request closed without merging**
