### PR TITLE
[receiver/elasticsearchreceiver] prevent non-existent metrics from being emitted

### PR DESCRIPTION
**Pull request by JonathanWamsley**
**Description:** <Describe what has changed.>
The metric `elasticsearch.cluster.state_update.time` no longer emits metric pairs that do not exist for  `unchanged` attribute such as `context_construction`, `commit`, `completion`, and `master_apply`. This was made [here](https://github.com/elastic/elasticsearch/pull/76771/files#diff-8bbfc581d91f9440e53098ea7d7864aeaeac1fc83a714133e4aafe38eba8ed90R2098) and shown in the latest [8.4 version](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/cluster-nodes-stats.html). Here's a screen shot since headings are not selectable
Screen Shot 2022-09-08 at 4 30 47 PM

**Link to tracking Issue:** <Issue number if applicable>
#13984 

**Testing:** <Describe what testing was performed and which tests were added.>
Expected metrics have been updated for unit and integration tests.

**Documentation:** <Describe the documentation added.>
Added comment where code change was made.

### CODE REVIEW

**Comment by djaglowski** [comment]
Typically, I would agree - we should differentiate between "0" values and non-reported values. However, in this case, it appears that the system is specifically telling us that those values are 0 via the "unchanged" value. Do I have that right?

**Comment by djaglowski** [comment]
If so, I think reporting those metrics as zeros is more accurate and simplifies ingestion.

**Comment by BinaryFissionGames** [comment]
@djaglowski I think the change makes sense. These keys are not ever present on the "unchanged" object, so we shouldn't speculate on their values or emit metrics that will literally always be 0; These metrics are essentially undefined.

**Comment by JonathanWamsley** [comment]
I'd like to add that the `success` and `failure` have a [`publication_time`](https://github.com/elastic/elasticsearch/pull/76771/files#diff-8bbfc581d91f9440e53098ea7d7864aeaeac1fc83a714133e4aafe38eba8ed90R2136) which includes the time measured by `context_construction_time`, `commit_time`, `completion_time` and `master_apply_time`. The `unchanged` state does not have that property.

**Review by djaglowski — APPROVED** [review]
I misunderstood the way that unchanged was represented. I see that it's an object of its own that partially follows another schema, so this makes sense.

**Pull request merged**
