### PR TITLE
Create `internal/metadataproviders` module

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** <Describe what has changed.>

Move the metadata providers for different environments used in the resource detection processor to a new internal module.
The goal is to reduce duplication in the usage of these metadata clients among different components (namely, we want to use some of these in the Datadog exporter).

In the future, it would also be nice to handle things like retries and caching in a common way for all components, to avoid e.g. one component being able to query the AWS EC2 endpoint while another times out; but this is out of scope on this particular PR, which tries to only make minimal changes on the code moved to the new module.

**Link to tracking Issue:** Relates to #1379 and #10424

**Testing:** Original unit tests are kept

### CODE REVIEW

**Comment by mx-psi** [comment]
@Aneurysm9 @pmm-sumo @dashpole would you mind having a look at this? Although the diff is large, the changes are mostly either renames or go.mod/go.sum updates, so it shouldn't take too long to review

**Review by TylerHelmuth — APPROVED** [review]
LGTM

**Review by pmm-sumo — APPROVED** [review]

**Comment by mx-psi** [comment]
Marking as ready to merge since we have two approvals, one from a CODEOWNER

**Review by codeboten — APPROVED** [review]
@mx-psi please resolve the conflicts and we can merge this

**Comment by mx-psi** [comment]
@codeboten Thanks for the ping, should be ready to merge now!

**Pull request merged**
