### PR TITLE
telemetrygen: Allow setting custom paths

### PR DESCRIPTION
**Pull request by gouthamve**
The current description for the flag is wrong.

```
❯ ../../open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen/telemetrygen metrics --otlp-endpoint example.com/v1/metrics  --otlp-http --otlp-insecure
2023-07-25T22:03:45.884+0200	INFO	metrics/metrics.go:56	starting HTTP exporter
Error: failed to obtain OTLP exporter: parse "http://example.com%2Fv1%2Fmetrics/v1/metrics": invalid URL escape "%2F"
```

I couldn't make it easily work with the existing flag because `url.Parse(c.Endpoint)` puts everything in path, and u.Host is unset. This is because url.Parse expects `http://` or `https://` which is set through a different flag.

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please add a changelog as this is user-facing.

**Comment by gouthamve** [comment]
@songy23 Done

**Review by songy23 — APPROVED** [review]
LGTM

**Review by mx-psi — APPROVED** [review]
LGTM, no change needed in logs because of #18867

**Review by atoulme — APPROVED** [review]

**Pull request merged**
