### PR TITLE
[processor/datadog] Use generated headers

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
Updates the `datadogprocessor` to use generated header.  Reviewing the processor I did not see any Warnings that need called out. @mx-psi @gbbr @dineshg13 if there are any appropriate Warnings to list let me know and I'll update the PR.

**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19172

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
@gbbr is this component stateful in any way?

**Comment by TylerHelmuth** [comment]
Pinging @mx-psi @gbbr @dineshg13

**Comment by gbbr** [comment]
Hi @TylerHelmuth, thanks for the PR! In the sense described [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/standard-warnings.md#statefulness), this component is not stateful.

**Review by mx-psi — APPROVED** [review]
LGTM, needs a rebase to fix the lint job

**Pull request merged**
