### PR TITLE
[ci] Check component code owners

### LINKED ISSUE #3871: Check for CODEOWNERS on CI
We have no automatic check for CODEOWNERS on CI. 

A CI check can be added so that
1. every component has a CODEOWNERS line and
2. every component listed on CODEOWNERS actually exists (to prevent typos).

### PR DESCRIPTION
**Pull request by hickeyma**
This PR checks that components have owners (as listed in CODEOWNERS) and that each listed component still exists in the project.

Implementation:

- Check every component has a CODEOWNERS line
- Check every component listed on CODEOWNERS actually exists in the project
- Call through CI job

Fixes #3871

Supersedes #4137

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>
Co-authored-by: Eundoo Song [eundoo.song@gmail.com](mailto:eundoo.song@gmail.com)

### CODE REVIEW

**Comment by hickeyma** [comment]
@mx-psi I have made the change you mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4137#pullrequestreview-714738063.

FYI in CODEOWNERS:

```
extension/observer/dockerobserver/ 
extension/observer/ecstaskobserver/
extension/observer/hostobserver/ 
extension/observer/k8sobserver/
```

These components have different owners. In your comment, we would only check for `extension/observer/`, however we would then miss `extension/observer/ecsobserver`. We could potentially use `extension/observer` as an exception but are there other exceptions?

**Comment by mx-psi** [comment]
> @mx-psi I have made the change you mentioned in [#4137 (review)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4137#pullrequestreview-714738063).
> 
> FYI in CODEOWNERS:
> 
> ```
> [...]
> extension/observer/dockerobserver/ 
> extension/observer/ecstaskobserver/
> extension/observer/hostobserver/ 
> extension/observer/k8sobserver/
> [...]
> extension/storage/dbstorage/
> extension/storage/filestorage/  
> [...]
> processor/resourcedetectionprocessor/
> processor/resourcedetectionprocessor/internal/azure
> ```
> 
> These components have different owners. In your comment, we would only check for `extension/observer/` for example, however we would then miss `extension/observer/ecsobserver`. We could potentially use the above as exceptions to check for but someone could add another level with owners?

@hickeyma So... what I was aiming for is to automatically check that "every new file has an owner" (eventually "every file has an owner" would ideally be true, but we have to start somewhere :) so checking for this + excluding the components currently missing owners from the check is a good start).

For the cases you bring up:

1. `extension/observer` should **not** show up, since there is a line for ownership:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1fbbcd1446749306e0707c39ebcf2e61e8167171/.github/CODEOWNERS#L67

2. `extension/storage` should show up, since e.g. `extension/storage/storagetest` is not owned by anyone
3. `processor/resourcedetectionprocessor` should **not** show up, since there is a line for ownership:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1fbbcd1446749306e0707c39ebcf2e61e8167171/.github/CODEOWNERS#L99

Not sure if that clears things up? I don't know if the approach I mentioned on that comment covers all the cases, but hopefully it's a little clearer what I wanted to do.

**Comment by mx-psi** [comment]
> @mx-psi thanks for the feedback.
> 
> One thing to clarify.
> 
> > `extension/storage` should show up, since e.g. `extension/storage/storagetest` is not owned by anyone
> 
> This does not have. Go module. Is this considered a component then?

It does though, doesn't it? https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4a245c66952441bf0335553492c8f44e674d7246/extension/storage/go.mod#L1 it's not a component but it is a module.

**Review by mx-psi — COMMENTED** [review]
Script looks good to me and the output makes sense (although we can only see the `check_code_owner_existence` part right now). 

I think the next step to make this mergeable is to add an allowlist for the components that are currently lacking a CODEOWNER. We could just have a components allowlist file with a component per line and grep on it just like we do for CODEOWNERS now

**Comment by hickeyma** [comment]
> Script looks good to me and the output makes sense (although we can only see the check_code_owner_existence part right now).

That's because the code owner existence step failed and therefore didn't run the component existence step. This now runs because of the added allowed list.

> I think the next step to make this mergeable is to add an allowlist for the components that are currently lacking a CODEOWNER. We could just have a components allowlist file with a component per line and grep on it just like we do for CODEOWNERS now

Done.

@mx-psi Thanks for the review. Updated and ready for review again.

**Comment by mx-psi** [comment]
Opened #9999 to fix the CODEOWNERS file 9️⃣:nine::nine::nine:

**Review by mx-psi — APPROVED** [review]
LGTM, only thing blocking this is merging the CODEOWNERS fix!

**Comment by hickeyma** [comment]
Thanks for review and pushing the fix to the file. It escaped me but proved to be a useful test! :)

**Comment by mx-psi** [comment]
> Thanks for review and pushing the fix to the file. It escaped me but proved to be a useful test! :)

Definitely! :)

**Comment by mx-psi** [comment]
#10005 should fix the errors, yes

**Comment by djaglowski** [comment]
#10005 is merged. Please rebase

**Review by mx-psi — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]

**Comment by hickeyma** [comment]
Thanks for reviews and merge @mx-psi @pmm-sumo @djaglowski

**Comment by hickeyma** [comment]
Not a bother @djaglowski, always happy to help. Big shout out to @mx-psi as he is driving these improvements and informed me of the PR which needed finishing off. Also, @eundoosong who pushed the original PR.

**Pull request merged**
