### PR TITLE
[chore][cmd/configschema/docsgen/docsgen] Enable goleak

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

Enables `goleak` on the `docsgen` package to catch potential leaking goroutines.

**Link to tracking Issue:** <Issue number if applicable>
#30438

**Testing:** <Describe what testing was performed and which tests were added.>
Test is passing other than referenced failure.

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Looks like we need `make genotelcontribcol`

**Comment by mx-psi** [comment]
```
=== FAIL: docsgen/docsgen  (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 3 in state chan receive, with k8s.io/klog.(*loggingT).flushDaemon on top of the stack:
k8s.io/klog.(*loggingT).flushDaemon(0x14a5[34](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8109823297/job/22165899065?pr=30494#step:8:35)c0)
	/home/runner/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0 in goroutine 1
	/home/runner/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0x19b
]
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/configschema/docsgen/docsgen	3.910s
testing: warning: no tests to run
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 5 in state chan receive, with k8s.io/klog.(*loggingT).flushDaemon on top of the stack:
k8s.io/klog.(*loggingT).flushDaemon(0x14a534c0)
	/home/runner/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0 in goroutine 1
	/home/runner/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0x19b
]
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/configschema/docsgen/docsgen	0.664s

DONE 2 runs, 27 tests, 1 skipped, 1 failure in 286.3[47](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8109823297/job/22165899065?pr=30494#step:8:48)s
make[2]: *** [../../Makefile.Common:126: test] Error 1
make[1]: *** [Makefile:165: cmd/configschema] Error 2
make: *** [Makefile:113: gotest] Error 2
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
```

**Comment by mx-psi** [comment]
Oh, sorry I missed that. Would you mind marking this PR as draft then?

**Comment by crobert-1** [comment]
@mx-psi: This PR should be ready now that it's passing on main. 👍

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
