### PR TITLE
remove oteltestbed collector

### PR DESCRIPTION
**Pull request by codeboten**
This collector is only used by the load tests. This is confusing because it's a custom distro that isn't shipped anywhere. This PR updates the load tests to use the otelcontribcol which is at least closer to the contrib distro. We should probably move to officially shipped distros in the near future.

### CODE REVIEW

**Comment by codeboten** [comment]
Note that this immediately changed the memory consumed by the collector, which is surprising since i didnt change the config:

```
Test                                    |Result|Duration|CPU Avg%|CPU Max%|RAM Avg MiB|RAM Max MiB|Sent Items|Received Items|
----------------------------------------|------|-------:|-------:|-------:|----------:|----------:|---------:|-------------:|
Log10kDPS/OTLP                          |FAIL  |      3s|    12.0|    11.9|         55|        165|     23700|         23500|RAM consumption is 165 MiB, max expected is 120 MiB
Log10kDPS/OTLP-HTTP                     |FAIL  |      3s|     8.1|     8.0|         55|        167|     29400|         29200|RAM consumption is 167 MiB, max expected is 120 MiB
Log10kDPS/filelog                       |FAIL  |      3s|     9.5|     9.4|         57|        172|     31100|         28800|RAM consumption is 172 MiB, max expected is 120 MiB
Log10kDPS/filelog_checkpoints           |FAIL  |      3s|     9.5|     9.4|         58|        176|     32000|         28700|RAM consumption is 176 MiB, max expected is 120 MiB
Log10kDPS/kubernetes_containers         |FAIL  |      3s|    22.5|    22.5|         60|        180|     32300|         29000|RAM consumption is 180 MiB, max expected is 150 MiB
Log10kDPS/kubernetes_containers_parser  |FAIL  |      3s|    26.1|    26.1|         58|        175|     31200|         29000|RAM consumption is 175 MiB, max expected is 150 MiB
Log10kDPS/k8s_CRI-Containerd            |FAIL  |      3s|    23.9|    23.9|         59|        178|     31500|         29100|RAM consumption is 178 MiB, max expected is 150 MiB
Log10kDPS/k8s_CRI-Containerd_no_attr_ops|FAIL  |      3s|    25.3|    25.3|         59|        179|     32600|         29100|RAM consumption is 179 MiB, max expected is 150 MiB
Log10kDPS/CRI-Containerd                |FAIL  |      3s|    14.9|    14.9|         60|        181|     31400|         28900|RAM consumption is 181 MiB, max expected is 150 MiB
Log10kDPS/syslog-tcp-batch-1            |FAIL  |      3s|    25.0|    25.0|         52|        157|     30800|         28300|RAM consumption is 157 MiB, max expected is 150 MiB
Log10kDPS/syslog-tcp-batch-100          |FAIL  |      3s|     8.3|     8.3|         53|        161|     30500|         29100|RAM consumption is 161 MiB, max expected is 150 MiB
Log10kDPS/FluentForward-SplunkHEC       |FAIL  |      3s|    24.2|    24.2|         57|        171|     30200|         27900|RAM consumption is 171 MiB, max expected is 150 MiB
Log10kDPS/tcp-batch-1                   |FAIL  |      3s|    23.7|    23.7|         53|        160|     31400|         29100|RAM consumption is 160 MiB, max expected is 150 MiB
Log10kDPS/tcp-batch-100                 |FAIL  |      3s|     9.5|     9.5|         53|        159|     31400|         29200|RAM consumption is 159 MiB, max expected is 150 MiB
```

**Comment by TylerHelmuth** [comment]
> Note that this immediately changed the memory consumed by the collector, which is surprising since i didnt change the config:

Thanks `init` functions

**Comment by djaglowski** [comment]
The reason a separate build is used is because the contrib build's memory footprint changes based on _all_ components, even if they are not used in the testbed. This means that the testbed's memory thresholds are regularly invalidated and the net result is that tests become very flaky and the thresholds keep getting raised arbitrarily to deal with the problem. [Original explaination.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9684)

**Comment by codeboten** [comment]
This was removed in a separate PR

**Pull request closed without merging**
