### PR TITLE
[chore] Reenable tests and linting disabled due to testconainters-go issue

### PR DESCRIPTION
**Pull request by bryan-aguilar**
**Description:** Dependent on https://github.com/testcontainers/testcontainers-go/issues/1359 being resolved. 

Enable tests that were skipped in #24213

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24240

### CODE REVIEW

**Comment by codeboten** [comment]
@bryan-aguilar https://github.com/codeboten/testcontainers-go/commit/0a89bd262701a4d47c59c83438ec34e4d769b4ef

**Review by codeboten — COMMENTED** [review]
Looks like the integ tests are still failing even after the replace, any idea what's happening there @bryan-aguilar

**Comment by bryan-aguilar** [comment]
I can't tell right now if it's an issue with the pinned psuedo version or the actual docker fix wasn't complete. It does look like `golang` will be relaxing this check in the next patch version though. https://github.com/golang/go/issues/61431

**Comment by bryan-aguilar** [comment]
Replacing the docker version with the a newer sudo version allows the `dockerobersver` tests to pass on my local machine. I am now seeing failures in the `snmp` receiver which I am looking into.

**Comment by bryan-aguilar** [comment]
@djaglowski any chance you could assist me with diving into these receiver failures? I am not familiar with the component.

**Comment by bryan-aguilar** [comment]
I have confirmed locally that running `make integration-test` passes for everything but `snmp` receiver integration tests. Also [this is the docker commit](https://github.com/moby/moby/commit/f022632503d1e58e8008ba38397f0bdea36376f5) I used for the replace statement.

**Comment by bryan-aguilar** [comment]
SNMP test was skipped for separate reason. Re-added skip. ty @djaglowski for pointing that out!

**Review by codeboten — APPROVED** [review]
Thanks for getting this fixed @bryan-aguilar!

**Review by djaglowski — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
