### PR TITLE
SignalFx exporter changes to match code review associated with Splunk HEC exporter

### PR DESCRIPTION
**Pull request by atoulme**
**Description:** 
Some changes trickling down from review of #246 - following the same change recommendations for SignalFx.

### CODE REVIEW

**Review by jrcamp — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@atoulme please more specific PR titles and commit messages. The current title is very generic and does not help the reviewers or future readers of commit history.

**Comment by atoulme** [comment]
Sure thing, done.

**Comment by tigrannajaryan** [comment]
@atoulme you probably need to add some tests to please codecov, I am unable to merge without it stamping the PR.

**Comment by bogdandrutu** [comment]
@atoulme please rebase and add some tests to make codecov happy :)

**Comment by atoulme** [comment]
I rebased and added a test.

**Pull request merged**
