### PR TITLE
chore: fix function names in comment

### PR DESCRIPTION
**Pull request by dockercui**
**Description:** <Describe what has changed.>

 fix function names in comment

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]

**Review by swiatekm — APPROVED** [review]

**Comment by djaglowski** [comment]
Thanks for the contribution @dockercui. Please sign the CLA

**Review by codeboten — COMMENTED** [review]
Thanks @dockercui, please resolve the conflict and we can get this merged

**Review by codeboten — APPROVED** [review]
Thanks @dockercui

**Pull request merged**
