### PR TITLE
[exporter/datasetexporter]: Add metrics reporting

### PR DESCRIPTION
**Pull request by martin-majlis-s1**
**Description:** Add metrics reporting

DataSet exporter maintains its internal queue. So far we have been logging this information. This PR is adding reporting these metrics into the Meter object provided by the Collector.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27650

**Testing:**

* In the contrib repository:
  * build docker image - `make docker-otelcontribcol`
* In the demo repository:
  * Stop dockers: `docker compose down`    
  * Run without feature gate:
    * Run: `docker compose up --abort-on-container-exit 2>&1 | tee out-no-gate.log`
    * There is [205 metrics](http://localhost:8080/grafana/explore?panes=%7B%22RKx%22:%7B%22datasource%22:%22webstore-metrics%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22webstore-metrics%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)
  * Run with enabled metrics:
    * Add following configuration option - `"--feature-gates=telemetry.useOtelForInternalMetrics"` to the `docker-compose.yml`
    * Run: `docker compose up --abort-on-container-exit 2>&1 | tee out-with-gate.log`
    * There is [205 metrics](http://localhost:8080/grafana/explore?panes=%7B%22RKx%22:%7B%22datasource%22:%22webstore-metrics%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22webstore-metrics%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by crobert-1** [comment]
It looks like from the PR title, this change is referencing an issue in another repository as well. If that's a publicly accessible issue please add a link, otherwise we can remove it from the title since you have a "local" issue as well.

**Comment by martin-majlis-s1** [comment]
When I run https://opentelemetry.io/docs/demo/ - metrics, that I have introduced are not logged. Although the call is copy-paste of the example - https://pkg.go.dev/go.opentelemetry.io/otel/metric#example-Meter-Asynchronous_multiple, I can see, that the callback is never called:

```
otel-col                          | 2023-10-25T11:55:09.285Z    info    datasetexporter@v0.86.1-0.20231004185026-b5635a7a90d2/statistics.go:16  AAAAA - reportStatistics - BEGIN        {"kind": "exporter", "data_type": "traces", "name": "dataset"}
otel-col                          | 2023-10-25T11:55:09.285Z    info    datasetexporter@v0.86.1-0.20231004185026-b5635a7a90d2/statistics.go:293 AAAAA - reportStatistics - REGISTRATION {"kind": "exporter", "data_type": "traces", "name": "dataset"}
otel-col                          | 2023-10-25T11:55:09.285Z    info    datasetexporter@v0.86.1-0.20231004185026-b5635a7a90d2/statistics.go:362 AAAAA - reportStatistics - END  {"kind": "exporter", "data_type": "traces", "name": "dataset", "err_is_nil": true}
otel-col                          | 2023-10-25T11:55:09.299Z    info    datasetexporter@v0.86.1-0.20231004185026-b5635a7a90d2/statistics.go:16  AAAAA - reportStatistics - BEGIN        {"kind": "exporter", "data_type": "logs", "name": "dataset"}
otel-col                          | 2023-10-25T11:55:09.299Z    info    datasetexporter@v0.86.1-0.20231004185026-b5635a7a90d2/statistics.go:293 AAAAA - reportStatistics - REGISTRATION {"kind": "exporter", "data_type": "logs", "name": "dataset"}
otel-col                          | 2023-10-25T11:55:09.299Z    info    datasetexporter@v0.86.1-0.20231004185026-b5635a7a90d2/statistics.go:362 AAAAA - reportStatistics - END  {"kind": "exporter", "data_type": "logs", "name": "dataset", "err_is_nil": true}
```

So, it's not obvious, why it's not working.


Other metrics are still there:

Screenshot 2023-10-25 at 13 38 18

**Comment by martin-majlis-s1** [comment]
When I check the existing code from here - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/logs.go#L176 - it's using the `Observable` versions - https://pkg.go.dev/go.opentelemetry.io/otel/metric#example-Meter-UpDownCounter

**Comment by martin-majlis-s1** [comment]
cc: @sirianni since we have been discussing this on Slack

**Comment by sirianni** [comment]
You may have to set the `telemetry.useOtelForInternalMetrics` feature gate

**Comment by martin-majlis-s1** [comment]
Although I have set it, I can see in the logs:
```
otel-col                          | 2023-10-25T13:01:38.359Z    info    service@v0.88.0/telemetry.go:84 Setting up own telemetry...
otel-col                          | 2023-10-25T13:01:38.367Z    info    service@v0.88.0/telemetry.go:157        Serving metrics {"address": ":8888", "level": "Basic"}
```
But the function is not called. I will check this issue - https://github.com/open-telemetry/opentelemetry-collector/issues/7454 - to see, what I am missing.

**Comment by martin-majlis-s1** [comment]
In the logs I can see, that I am updating the metric:

```
prometheus                        | ts=2023-10-31T09:32:52.756Z caller=write_handler.go:212 level=warn component=web msg="Error translating OTLP metrics to Prometheus write request" err="invalid temporality and type combination for metric \"app_currency_counter\""
otel-col                          | 2023-10-31T09:32:52.754Z    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 1, "metrics": 1, "data points": 1}
prometheus                        | ts=2023-10-31T09:32:52.956Z caller=write_handler.go:212 level=warn component=web msg="Error translating OTLP metrics to Prometheus write request" err="empty data points. http.server.duration is dropped; empty data points. http.client.duration is dropped; empty data points. db.client.connections.usage is dropped; empty data points. db.client.connections.usage is dropped"
otel-col                          | 2023-10-31T09:32:53.274Z    info    datasetexporter@v0.88.0/statistics.go:307       AAAAA - reportStatistics - inc Foo by   {"kind": "exporter", "data_type": "traces", "name": "dataset", "foo": 14}
otel-col                          | 2023-10-31T09:32:53.298Z    info    datasetexporter@v0.88.0/statistics.go:307       AAAAA - reportStatistics - inc Foo by   {"kind": "exporter", "data_type": "logs", "name": "dataset", "foo": 14}
otel-col                          | 2023-10-31T09:32:54.126Z    info    datasetexporter@v0.88.0/statistics.go:307       AAAAA - reportStatistics - inc Foo by   {"kind": "exporter", "data_type": "traces", "name": "dataset", "foo": 15}
otel-col                          | 2023-10-31T09:32:54.150Z    info    datasetexporter@v0.88.0/statistics.go:307       AAAAA - reportStatistics - inc Foo by   {"kind": "exporter", "data_type": "logs", "name": "dataset", "foo": 15}
```

There is no indication, that metrics produced by `datasetexporter` are dropped. There is no error produced.


I have no idea, where the problem could be.

@sirianni: Do you, please, have some other idea, where could be the problem?

**Comment by martin-majlis-s1** [comment]
I have found 2 related issues:
* https://github.com/open-telemetry/opentelemetry-collector/issues/5687 
* https://github.com/open-telemetry/opentelemetry-collector/issues/7454

Both of these issues contains some discussion based on which I would guess, that it should be working right now. Although they are not closed.

**Comment by martin-majlis-s1** [comment]
When I update the configuration with:
```
receivers:
  ...
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']

...

    metrics:
      receivers: [httpcheck/frontendproxy, otlp, spanmetrics, prometheus]
      processors: [filter/ottl, transform, batch]
      exporters: [otlphttp/prometheus, debug]
```

And then run it with the flag - `"--feature-gates=telemetry.useOtelForInternalMetrics"`, then I can see, that the callback is called.

```
otel-col                          | 2023-10-31T12:03:16.759Z    info    datasetexporter@v0.88.0/statistics.go:310       AAAAA - reportStatistics - SimpleCounter - down by      {"kind": "exporter", "data_type": "logs", "name": "dataset", "foo": 35}
otel-col                          | 2023-10-31T12:03:16.759Z    info    datasetexporter@v0.88.0/statistics.go:310       AAAAA - reportStatistics - SimpleCounter - down by      {"kind": "exporter", "data_type": "traces", "name": "dataset", "foo": 35}
otel-col                          | 2023-10-31T12:03:16.975Z    info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 1, "log records": 25}
otel-col                          | 2023-10-31T12:03:17.170Z    info    datasetexporter@v0.88.0/statistics.go:330       AAAAA - reportStatistics - CALLBACK BEGIN       {"kind": "exporter", "data_type": "traces", "name": "dataset"}
otel-col                          | 2023-10-31T12:03:17.170Z    info    datasetexporter@v0.88.0/statistics.go:333       AAAAA - reportStatistics - STATS        {"kind": "exporter", "data_type": "traces", "name": "dataset", "stats_is_nil": false}
otel-col                          | 2023-10-31T12:03:17.172Z    info    datasetexporter@v0.88.0/statistics.go:369       AAAAA - reportStatistics - CALLBACK - END       {"kind": "exporter", "data_type": "traces", "name": "dataset"}
otel-col                          | 2023-10-31T12:03:17.172Z    info    datasetexporter@v0.88.0/statistics.go:330       AAAAA - reportStatistics - CALLBACK BEGIN       {"kind": "exporter", "data_type": "logs", "name": "dataset"}
otel-col                          | 2023-10-31T12:03:17.172Z    info    datasetexporter@v0.88.0/statistics.go:333       AAAAA - reportStatistics - STATS        {"kind": "exporter", "data_type": "logs", "name": "dataset", "stats_is_nil": false}
otel-col                          | 2023-10-31T12:03:17.172Z    info    datasetexporter@v0.88.0/statistics.go:369       AAAAA - reportStatistics - CALLBACK - END       {"kind": "exporter", "data_type": "logs", "name": "dataset"}
otel-col                          | 2023-10-31T12:03:17.178Z    warn    internal/transaction.go:123     Failed to scrape Prometheus endpoint    {"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_timestamp": 1698753797164, "target_labels": "{__name__=\"up\", instance=\"0.0.0.0:8888\", job=\"otel-collector\"}"}
otel-col                          | 2023-10-31T12:03:17.274Z    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 1, "metrics": 5, "data points": 5}
otel-col                          | 2023-10-31T12:03:17.378Z    info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 8}
otel-col                          | 2023-10-31T12:03:17.580Z    info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 87}
otel-col                          | 2023-10-31T12:03:18.280Z    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 1, "metrics": 35, "data points": 78}
otel-col                          | 2023-10-31T12:03:18.389Z    info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 2}
otel-col                          | 2023-10-31T12:03:18.992Z    info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 2}
otel-col                          | 2023-10-31T12:03:20.219Z    info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 1, "log records": 1}
otel-col                          | 2023-10-31T12:03:20.885Z    info    client/client.go:489    Buffers' Queue Stats:   {"kind": "exporter", "data_type": "traces", "name": "dataset", "processed": 32, "enqueued": 32, "dropped": 0, "broken": 0, "waiting": 0, "successRate": 1, "processingS": 168.675172925, "processing": 168.675172925}
otel-col                          | 2023-10-31T12:03:20.886Z    info    client/client.go:503    Events' Queue Stats:    {"kind": "exporter", "data_type": "traces", "name": "dataset", "processed": 6335, "enqueued": 6335, "dropped": 0, "broken": 0, "waiting": 0, "successRate": 1, "processingS": 168.675172925, "processing": 168.675172925}
```

But when I check prometheus:
Screenshot 2023-10-31 at 12 56 48

But it's super strange, that `SimpleCounterLoop` is there, but `SimpleCounterCallback` is not. As well as the other observable counters.

**Pull request closed without merging**
