### PR TITLE
[exporter/AlibabaCloudLogServiceExporter] sanitize resources for metrics

### PR DESCRIPTION
**Pull request by shabicheng**
**Description:** <Describe what has changed.>

OpenTelemetry metric's labels contains '.' or others none Letter or Digit characters, the alibabacloudlogserviceexporter do not replace these characters, so promQL will cause errors like "promql error: 1:33: parse error: unexpected character inside braces: '.'"

In last PR #3454, we forget to sanitize resources. So resources like 'service.name' will case PromQL parse error. 

**Link to tracking Issue:** <Issue number if applicable>

#3429

**Testing:** <Describe what testing was performed and which tests were added.>

Unit test has been updated to cover this issue.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by shabicheng** [comment]
@qiansheng91 please review this PR

**Comment by qiansheng91** [comment]
LGTM

**Review by qiansheng91 — APPROVED** [review]
LGTM

**Comment by shabicheng** [comment]
@bogdandrutu @owais hi, could you help merge this PR? Our PR has been used in production and works fine.

**Comment by shabicheng** [comment]
@owais @bogdandrutu please help merge this PR

**Pull request closed without merging**
