### PR TITLE
[receiver/datadog] Span Obfuscation

### PR DESCRIPTION
**Pull request by lopes-felipe**
#### Description
Datadog Agent's span processor has an [obfuscation pipeline](https://github.com/DataDog/datadog-agent/blob/fbe15f71bcaa1b0ed3f8331bf049f1d46e4eeede/pkg/trace/agent/agent.go#L373) that—among other things—obfuscates sensitive data, cleans up span resource names, and extracts particular components into specific span metadata.  

This PR implements the same behavior into the `datadogreceiver`, but disabled by default for retro compatibility with existing users.

#### Link to tracking issue
Fixes

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
@lopes-felipe,

Have you checked to see if any of the existing processors would provide this functionality? 
I am hesitant to allow adding this into

**Comment by lopes-felipe** [comment]
> @lopes-felipe,
> 
> Have you checked to see if any of the existing processors would provide this functionality?
> 
> I am hesitant to allow adding this into the receiver when it could already be achieved with existing functionality. There is also the added concern that this component is effectively bundling the datadog agent into the collector which doesn't sound ideal.

Hey @MovieStoreGuy,

Thank you for the review. Yes, I have checked all the existing processors, and none of them have the capability to clean or/and obfuscate the span data in such a context-aware/structured way as it's done here. 

For instance, like [this simple test](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35593/files#diff-776d8a37714f68338101d91e29a20c8244f19acba413426ad638ed111d8cf9b9R117) demonstrates, it takes a SQL query with comments, aliases, and repetitions ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35593/files#diff-776d8a37714f68338101d91e29a20c8244f19acba413426ad638ed111d8cf9b9R124)), and turn it into a flat, un-aliased, un-commented, deduplicated string ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35593/files#diff-776d8a37714f68338101d91e29a20c8244f19acba413426ad638ed111d8cf9b9R153)), something that is just not possible with any other processor currently available.

I would be more than happy to propose something like this for an existing processor such as [Span Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanprocessor) though, but I guess we could first prove the value of such a focused processing approach as this in a more narrowed-scope component such as Datadog Receiver here.

Finally, regarding bundling the Datadog Agent into the Collector, please correct me if I'm wrong here, but I don't think this particular feature implementation is moving this (very reasonable) concern any further, considering what has already taken place by the Datadog Exporter, and for the very own Datadog Receiver. Still, again, I might be missing something here.

Thank you again for the thoughtful review :)

**Comment by lopes-felipe** [comment]
Hey @MovieStoreGuy, would you mind taking another look at this, considering now my previous comment? Thank you :)

**Comment by MovieStoreGuy** [comment]
Hey @lopes-felipe ,

> Thank you for the review. Yes, I have checked all the existing processors, and none of them have the capability to clean or/and obfuscate the span data in such a context-aware/structured way as it's done here.

Have you looked at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/redactionprocessor ?

I am trying to conscious of is the Datadog receiver doing _too_ much and tightly coupling a receivers role and a processors role. This historical made for a bad experience and has introduced performance issues in those components. 

Realistically I would expect this work to be done within the above redaction processor with configuration defined.

**Comment by lopes-felipe** [comment]
Hey @MovieStoreGuy,

> I am trying to conscious of is the Datadog receiver doing _too_ much and tightly coupling a receivers role and a processors role. This historical made for a bad experience and has introduced performance issues in those components.

I see, and that definitely makes sense. Considering that, I have put up [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35934) to discuss this feature in a more broad, vendor-agnostic approach to the Span Processor. 

I think we can close this now. Thanks.

**Pull request closed without merging**
