### PR TITLE
Remove experimental note

### PR DESCRIPTION
**Pull request by albertteoh**
Signed-off-by: Albert Teoh <albert.teoh@logz.io>

**Description:** 
Remove experimental note as it has been stable for a few months now, and translators appear to be a number of months away.

### CODE REVIEW

**Comment by jkowall** [comment]
So the question I have is should this move to the core collector or stay in contrib?

**Comment by jpkrohling** [comment]
It will probably stay here in contrib for GA. We are right now focusing on removing things from the core, and most of the components would live outside of the core anyway. The main *distribution* might include this one in the future, though.

**Review by jpkrohling — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
We will likely introduce a more formal labeling for stability of individual components soon as part of GA-ing. I suggest we wait for that.

**Comment by jpkrohling** [comment]
Given that this is the only component I can think of with such a notice, isn't it unfair to require this one to keep the note, while others aren't required to add one?

**Pull request closed without merging**
