### PR TITLE
[processor/tailsamplingprocessor] Improve accuracy of `count_traces_sampled` metric 

### LINKED ISSUE #25882: Tail sampling processor "count_traces_sampled" metric is inaccurate
### Component(s)

processor/tailsampling

### Describe the issue you're reporting

It looks like the "count_traces_sampled" metric of the tail sampling processor is inaccurate, or at least it's not calculated how I would expect.

Specifically, given two policies named `"policy1"` and `"policy2"`, the metric values for `{policy="policy1",sampled="false"}` and `{policy="policy2",sampled="false"}`, and those for `{policy="policy1",sampled="true"}` and `{policy="policy2",sampled="true"}` are always equal, although I would expect them to be different, for different policies.

Indeed, looking at the code, they are all calculated based on `finalDecision`, and not each policy's decision:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/06f1f57289d64c13e422b8bfeaeea8221219cb2d/processor/tailsamplingprocessor/processor.go#L264-L288

Why I think that's a bug, and not intended behavior, is that per-policy decisions are actually stored in `trace.Decisions[i]` during evaluation, but then never used anywhere (that I could find).

So I think

```go
	for _, p := range tsp.policies {
		switch finalDecision {
```

should actually be

```go
	for i, p := range tsp.policies {
		switch trace.Decisions[i] {
```

### PR DESCRIPTION
**Pull request by jmsnll**
**Description:** 

Previously, the calculation of `count_traces_sampled` was incorrect, resulting in all per-policy metric counts being the same.

```
count_traces_sampled{policy="policy-a", sampled="false"} 50
count_traces_sampled{policy="policy-a", sampled="true"} 50
count_traces_sampled{policy="policy-b", sampled="false"} 50
count_traces_sampled{policy="policy-b", sampled="true"} 50
```

This issue stemmed from the metrics being incremented based on the final decision of trace sampling, rather than being attributed to the policies causing the sampling.

With the fix implemented, the total sampling count can no longer be inferred from the metrics alone. To address this, a new metric, `global_count_traces_sampled`, was introduced to accurately capture the global count of sampled traces.

```
count_traces_sampled{policy="policy-a", sampled="false"} 50
count_traces_sampled{policy="policy-a", sampled="true"} 50
count_traces_sampled{policy="policy-b", sampled="false"} 24
count_traces_sampled{policy="policy-b", sampled="true"} 76
global_count_traces_sampled{sampled="false"} 24
global_count_traces_sampled{sampled="true"} 76
```

Reusing the `count_traces_sampled` policy metric for this purpose would have either meant:

1. Leaving the policy field empty, which didn't feel very explicit.
2. Setting a global placeholder policy name (such as `final-decision`), which could then potentially collide with existing user-configured policy names without validation.

**Link to tracking Issue:** Fixes #25882

**Testing:** 

Tested with various combinations of `probabilistic`, `latency`, `status_code` and attribute policies (including combinations of `and` and `composite` policies).  

No unit tests were added, open to suggestions for adding tests for metrics but I couldn't find any examples of it being done elsewhere.

**Documentation:** No documentation changes.

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]

**Comment by mx-psi** [comment]
This broke main
 
```
Error: /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/tailsamplingprocessor/metrics.go:93:16: undefined: obsreport
```

@jmsnll @jpkrohling would you be able to do a quick fix? Or should I revert the PR and we can address this more calmly?

**Comment by jmsnll** [comment]
@mx-psi why `obsreport` isn't define isn't immediately obvious to me so maybe best reverting to take a closer look

**Comment by jmsnll** [comment]
Actually a fix has been submitted at #27246

**Comment by mx-psi** [comment]
Indeed :) that should fix it, thanks for taking a look in any case!

**Pull request merged**
