### PR TITLE
Update CODEOWNERS. - remove @pavankrish123(me) frpm bearertoken owners

### PR DESCRIPTION
**Pull request by pavankrish123**
removing myself @pavankrish123(me) frpm bearertoken owners from the file cc: @jpkrohling

### CODE REVIEW

**Comment by atoulme** [comment]
Please edit https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/bearertokenauthextension/metadata.yaml, remove yourself, then from the root, run `make generate gendependabot`

**Comment by pavankrish123** [comment]
will do. thanks @atoulme

**Comment by atoulme** [comment]
Do you also want a changelog item for this? If so, please add a changelog entry under .chloggen by copying TEMPLATE.yaml or run `make chlog-new`

**Review by codeboten — COMMENTED** [review]
@atoulme i don't think a changelog is standard for codeowner changes, i'll add the skip changelog label

**Comment by jpkrohling** [comment]
Thank you for all your help with auth extensions, @pavankrish123!

**Comment by atoulme** [comment]
BTW, if you look at metadata.yaml files, you can add yourself as emeritus codeowner.

**Review by frzifus — APPROVED** [review]

**Comment by pavankrish123** [comment]
sorry closed this PR in favor of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28645. Please take a look into it

**Pull request closed without merging**
