### PR TITLE
Bump GCP dependencies and enable lifecycle tests

### PR DESCRIPTION
**Pull request by damemi**
**Description:**
Replaces https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31979. Updates GCP dependencies and adds calls to `Start()` functions. Also enables shutdown tests for GCP components (ref https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30524)

**Link to tracking Issue:** n/a

**Testing:** Downstream unit and integration tests

**Documentation:** No change

### CODE REVIEW

**Comment by dashpole** [comment]
For the changelog, you can note any changes included in the dependency bump.

You might need to run `make generate` to actually add the generated lifecycle tests.

**Review by songy23 — COMMENTED** [review]
Needs `make gotidy` (maybe `make genotelcontribcol `and make `genoteltestbedcol` as well`

**Review by dashpole — APPROVED** [review]

**Comment by dashpole** [comment]
hmmm... the component lifecycle tests are failing

**Comment by damemi** [comment]
> hmmm... the component lifecycle tests are failing

ah the lifecycle tests call `Start()` https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bc716280fc850cecb83e69bec91c39141ef73f52/exporter/googlecloudexporter/generated_component_test.go#L70 ... is that right?

**Comment by dashpole** [comment]
I think maybe we just want the shutdown, but not the lifecycle test?

**Comment by damemi** [comment]
> I think maybe we just want the shutdown, but not the lifecycle test?

@dashpole I'll try that. We should come back to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30524, or open its own issue to track if it's even possible for us to enable lifecycle.

**Comment by dashpole** [comment]
Feel free to open a tracking issue.

**Review by songy23 — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
