### PR TITLE
[processor/remotetap] Change default endpoint from `:12001` to `localhost:12001`

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Change default endpoint from `:12001` to `localhost:12001`

**Link to tracking Issue:**
#30702

**Documentation:**
Changed README

### CODE REVIEW

**Review by mx-psi — DISMISSED** [review]

**Review by codeboten — COMMENTED** [review]
@mx-psi @atoulme 

As an alpha component, should this not use the `component.UseLocalHostAsDefaultHost` feature gate?

**Comment by mx-psi** [comment]
The rationale was that we could skip it because of it being alpha https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30702#issuecomment-1911060462. I am fine with adding the feature gate instead

**Comment by codeboten** [comment]
@mx-psi there are other alpha components for which we used the feature gate, see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30826/files

I'd go the route of the feature gate to be consistent

**Comment by atoulme** [comment]
Closing as this approach is abandoned.

**Pull request closed without merging**
