### PR TITLE
[receiver/dockerstats] Combine and simplify multiple blockio metrics by making "operation" an attribute

### PR DESCRIPTION
**Pull request by jamesmoessis**
**Description:**

Instead of having several blockio metrics with the operation appended on the name as `.read, .write, .sync, .async, .total, .discard` we pull the operation out into an attribute. This simplifies the code a lot: 
1. Much less generated code, since that scales with amount of metric names.
2. Simplifies the recording logic, as we don't have to map the operation from the stat to a recording function, we put it in an attribute instead. 
3. It also makes sense from an otel/metrics perspective, as it more closely aligns with the approach of the semconv (tending towards using attributes instead of additional metric names where possible). 

This is a breaking change for anyone using the featuregated v2 implementation, which is not enabled by default yet. To my knowledge, no one is using the new v2 implementation yet. 

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9794

**Testing:** 

The tests logic remain the same, but the expected metrics are updates to align with the changes. 

**Documentation:** 

Documentation automatically updated by `go generate`.

### CODE REVIEW

**Comment by jamesmoessis** [comment]
@rmfitzpatrick @MovieStoreGuy FYI + please review if you have time 😄

**Review by MovieStoreGuy — APPROVED** [review]
This change makes sense to me.

**Comment by jamesmoessis** [comment]
Hi @rmfitzpatrick @djaglowski just bumping this PR

**Review by rmfitzpatrick — APPROVED** [review]

**Comment by rmfitzpatrick** [comment]
These changes seem good to me, and I imagine similar updates can be made to the `container.network.io.usage` metrics w/ `direction` and ~`state` attributes, though that may be related to the outcome of https://github.com/open-telemetry/opentelemetry-specification/issues/2726.

**Comment by jamesmoessis** [comment]
@jpkrohling @djaglowski I have codeowner approval and one other approval. Can I get this reviewed/merged please 😃

**Review by jpkrohling — APPROVED** [review]
approving by proxy

**Pull request merged**
