### PR TITLE
[exporter/datadogexporter] Upgrade opentelemetry-mapping-go version and fix breaking changes

### LINKED ISSUE #22917: Bump github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics from 0.2.1 to 0.2.3 causes issue
### Component(s)

exporter/datadog

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5114664886/jobs/9195143629#step:5:189 for more info:

```
Error: ../../exporter/datadogexporter/metrics_exporter.go:189:9: assignment mismatch: 1 variable but exp.tr.MapMetrics returns 2 values
```

### PR DESCRIPTION
**Pull request by songy23**
**Description:** 
Upgrade opentelemetry-mapping-go version and fix breaking changes

**Link to tracking Issue:** <Issue number if applicable>
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22917

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by songy23** [comment]
@mx-psi good catch! Should have run it from the root. Should be fixed now

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Checked with @codeboten that https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5123908913/jobs/9215077004?pr=22952 is safe to ignore

**Comment by songy23** [comment]
`build-and-test / integration-tests` failed due to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18286.

**Review by codeboten — APPROVED** [review]
linting timed-out. restarted the failed jobs

**Pull request merged**
