### PR TITLE
Change Receiver pattern in the awsxrayreceiver

### PR DESCRIPTION
**Pull request by humivo**
**Description:** Make changes to the receiver pattern in the awsxrayreceiver for the receiver.go file.

**Link to tracking Issue:** [Issue #3436](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3436)

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please rebase/squash commits, it is a chaos of 24 commits for 8 lines change

**Comment by humivo** [comment]
> Please rebase/squash commits, it is a chaos of 24 commits for 8 lines change

Ah ok that makes sense.  This should be the last PR for the changes though.

**Comment by bogdandrutu** [comment]
I do understand, but want to make sure you do the clean way :) so please fix.

**Pull request closed without merging**
