### PR TITLE
[pkg/kafka] move internal/kafka to pkg/kafka

### PR DESCRIPTION
**Pull request by vincentfree**
**Description:**

Move internal/kafka to pkg/kafka so that the Authorization configuration can be exported for downstream use.

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30377

**Testing:**
Ensured that all modules which have been touched are still working. Since no extra code has been introduced, no extra tests need to be included.

**Documentation:**

This was mainly a move of files, no new functionality or documentation

### CODE REVIEW

**Comment by vincentfree** [comment]
@dmitryax as promised :)
I have validated that it works for all involved modules but the code coverage failed on my branch probably due to missing configuration for the CI configuration, I expect everything is in order for this PR

**Comment by atoulme** [comment]
Please resolve conflicts.

**Review by dmitryax — APPROVED** [review]
LGTM. Thanks! Please rebase

**Review by bogdandrutu — COMMENTED** [review]
Why exposing all the internal package when only config is needed. There are lots of public types in this package which I am not sure we want to expose publicly if only the config is needed per the issue.

**Comment by dmitryax** [comment]
> Why exposing all the internal package when only config is needed. There are lots of public types in this package which I am not sure we want to expose publicly if only the config is needed per the issue.

Right. That was the original ask actually. I see `IAMSASLClient` `XDGSCRAMClient` unnecessary exposed along with `ConfigureAuthentication`. @vincentfree can you please keep them in the internal module?

**Comment by vincentfree** [comment]
> > Why exposing all the internal package when only config is needed. There are lots of public types in this package which I am not sure we want to expose publicly if only the config is needed per the issue.
> 
> Right. That was the original ask actually. I see `IAMSASLClient` `XDGSCRAMClient` unnecessary exposed along with `ConfigureAuthentication`. @vincentfree can you please keep them in the internal module?

Yea I can move them back

**Review by pavolloffay — APPROVED** [review]

**Pull request closed without merging**
