### PR TITLE
[exporter/sumologic] use generated status header

### PR DESCRIPTION
**Pull request by codeboten**
This PR updates the component to generate the status table using mdatagen. Questions to the code owners:

Does this component require any of the standard warnings? See list: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/standard-warnings.md

See related issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19172

### CODE REVIEW

**Comment by dmitryax** [comment]
Another Q to code owners: is this exporter needed given that there is https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/exporter/sumologicexporter ? :)

**Review by dmitryax — APPROVED** [review]

**Comment by astencel-sumo** [comment]
> Another Q to code owners: is this exporter needed given that there is https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/exporter/sumologicexporter ? :)

This is an excellent question :sweat_smile: and a long-running debate in our team. The history is, we originally created the Sumo Logic exporter in contrib, and then switched to keeping the sources together with the Sumo Logic Distribution for OpenTelemetry Collector at https://github.com/sumologic/sumologic-otel-collector. We have a couple other components in the distro repo, some of them more and some of them less fitting for the contrib repo.

The point I think we all agree on in the team is that we want to keep the presence of Sumo Logic components in the contrib repo as much as possible, big part of it being the popularity of the contrib release among end users.

After having another discussion in the team today, we're at a point where we want to move the Sumo Logic exporter back to the contrib repo. For that to make sense, we'd need to put the [Sumo Logic extension](https://github.com/SumoLogic/sumologic-otel-collector/tree/v0.74.0-sumo-0/pkg/extension/sumologicextension) in contrib repo as well, as it is a crucial part of the Sumo Logic exporter's. Do you think it makes sense @dmitryax?

**Review by andrzej-stencel — APPROVED** [review]

**Comment by dmitryax** [comment]
> After having another discussion in the team today, we're at a point where we want to move the Sumo Logic exporter back to the contrib repo. For that to make sense, we'd need to put the [Sumo Logic extension](https://github.com/SumoLogic/sumologic-otel-collector/tree/v0.74.0-sumo-0/pkg/extension/sumologicextension) in contrib repo as well, as it is an important part of the Sumo Logic exporter's functionality. Do you think it makes sense @dmitryax?

I don't have any objections. I think it's ok to add vendor components other than receivers/exporters. We already have https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/datadogprocessor

cc @open-telemetry/collector-contrib-approvers

**Comment by TylerHelmuth** [comment]
Agreed, all our existing rules state `vendor-specific components` and not a specific type of component.

**Pull request merged**
