### PR TITLE
[exporter/postgres] - initial Revamped PR for new Postgres Exporter Component

### PR DESCRIPTION
**Pull request by destrex271**
#### Description
Adds support for exporting traces, metrics and logs to Postgres.

#### Link to tracking issue
Implements component #35451 & revamped version of PR #35485 since that branch became a mess after merging with upstream

#### Sponsor Details

@philippemnoel from ParadeDB has expressed his intent to sponsor this component since this feature is primarily being developed for this issue in Paradedb https://github.com/paradedb/paradedb/issues/1632

### CODE REVIEW

**Comment by destrex271** [comment]
I am facing some problems in generating the headers right now, will update the PR once done

**Comment by atoulme** [comment]
The sponsor needs to be an approver or maintainer of the contrib project.

**Comment by philippemnoel** [comment]
> The sponsor needs to be an approver or maintainer of the contrib project.

Ah. Then I'm not sure I can help for now.

**Comment by smehboub** [comment]
Hello @destrex271
This feature would be great!
Do you know why it's blocked ?

**Pull request closed without merging**
