### PR TITLE
Fix flaky test - increase file lifespan in rotation tests

### PR DESCRIPTION
**Pull request by djaglowski**
Addresses #1382

### CODE REVIEW

**Comment by djaglowski** [comment]
I retriggered tests hoping to bypass #1380 but we are unfortunately still blocked on this. Otherwise should be good to go.

**Comment by bogdandrutu** [comment]
@djaglowski please rebase, also remove the skip that I added

**Comment by djaglowski** [comment]
@bogdandrutu Thanks, should be all set now.

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Thanks for the fix @djaglowski

**Pull request merged**
