### PR TITLE
Upgrade to core latest PR, fix Permanent->NewPermanent change

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by codeboten — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Linter is not happy.

**Comment by bogdandrutu** [comment]
@tigrannajaryan linter was not happy because I changed a file where there was a use of a deprecated func :D

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
A test is broken, could be due to recent changes in combineerrors or related.

**Comment by codeboten** [comment]
Fixed the test failure caused by `combineerrors` changes, looks like there's still failures caused by environment expansion though.

**Pull request merged**
