### PR TITLE
Add a copy of internal/testdata/ directory from Collector core to Collector contrib

### PR DESCRIPTION
**Pull request by Saber-W**
**Description:**
This PR makes a copy of `internal/testdata` directory from Collector core to Collector contrib repo. It retains the commit history from core.

**Link to tracking Issue:**
[opentelemetry-collector/#3474](https://github.com/open-telemetry/opentelemetry-collector/issues/3474)

### CODE REVIEW

**Comment by Saber-W** [comment]
This is the start PR of the Collector core components migration work. It's ready to be merged.

cc @alolita @bogdandrutu @Aneurysm9 @punya

**Review by punya — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please redo this to include the latest merged PR on core. @punya any other option?

**Comment by punya** [comment]
It doesn't need to be re-done. @Saber-W should be able to merge core's main branch into open-o11y:testdata-migration and update this PR (after resolving merge conflicts and fixing tests).

**Comment by Saber-W** [comment]
Merged the latest changes in Collector core into this branch.

**Comment by bogdandrutu** [comment]
@Saber-W that seem to be your PR not the original PR

**Comment by Saber-W** [comment]
Yeah, merging Collector core main branch into this branch will introduce lots of conflicts. I resolved the conflicts and committed again.

**Comment by bogdandrutu** [comment]
That is not good.

**Comment by Saber-W** [comment]
If we want to keep the entire history, I need to redo this process.

**Comment by bogdandrutu** [comment]
I would say that we want

**Comment by Saber-W** [comment]
We have the latest commit in history now.

**Review by Aneurysm9 — APPROVED** [review]

**Pull request merged**
