### PR TITLE
Add events proxying to SignalFx receiver/exporter

### PR DESCRIPTION
**Pull request by keitwb**
These use the new Log data model to funnel events between the receiver
and exporter.  This primarily is intended for proxying events through
the collector -- the collector does not generate events from scratch at
this time.

### CODE REVIEW

**Comment by asuresh4** [comment]
Looks like the PR could be split into 2. One each for the receiver and exporter?

**Comment by keitwb** [comment]
> Looks like the PR could be split into 2. One each for the receiver and exporter?

Part of reviewing it is to see the whole Signalfx -> pdata.Logs -> SignalFx translation.  If it is two PRs then you have to cross reference the two PRs to see if the translation is right (which is basically the same as one PR at that point), or else just hope it is.

**Comment by bogdandrutu** [comment]
@keitwb not really, I am confident in the capability to review one PR, and able to understand that. If we cannot understand the conversion it means that is not well documented or designed.

**Comment by dmitryax** [comment]
I'm curios if we can use http_forwarder instead https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1014 . In that case we could avoid this complexity unless we need to process the events/logs in the pipeline somehow.

**Comment by keitwb** [comment]
> I'm curios if we can use http_forwarder instead #1014 . In that case we could avoid this complexity unless we need to process the events/logs in the pipeline somehow.

In theory yes but it increases the complexity of the setup of the sender since the signalfx receiver and http forwarder can't share ports and usually SignalFx clients are setup to send to a unified endpoint.

**Pull request closed without merging**
