### PR TITLE
awsxrayreceiver: migrate to newer semconv version

### PR DESCRIPTION
**Pull request by narcis96**
Description: The version of semconv is upgraded from v1.6.1 to v1.18.0

This is a trivial upgrade. The semconv attributes' value have been compared using [go-otel-semconv-comparator](https://github.com/narcis96/go-otel-semconv-comparator). All attributes used by this component have the same value in both versions.

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22095

Testing: Tests passed

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
why v1.18.0 instead of v1.27.0 in other PRs?

**Comment by narcis96** [comment]
> why v1.18.0 instead of v1.27.0 in other PRs?

v1.18.0 is the most newer version that still keep the code from compiling

**Comment by narcis96** [comment]
PTAL

@MovieStoreGuy
@srprash
@wangzlei

**Comment by narcis96** [comment]
Kind reminder here: @MovieStoreGuy @srprash @wangzlei @mx-psi

**Review by MovieStoreGuy — APPROVED** [review]

**Pull request merged**
