### PR TITLE
[chore] Promote Braydon Kains to triager

### PR DESCRIPTION
**Pull request by mx-psi**
#### Description

Promotes @braydonk to triager role.

- PRs reviewed: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+reviewed-by%3Abraydonk+
- PRs authored: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3Abraydonk+
- Issues created: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+author%3Abraydonk+
- Issues commented: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+commenter%3Abraydonk+
- Commits: https://github.com/open-telemetry/opentelemetry-collector-contrib/commits?author=braydonk

cc @open-telemetry/collector-contrib-triagers

### CODE REVIEW

**Review by andrzej-stencel — APPROVED** [review]
:heart: :rocket:

**Review by ChrsMark — APPROVED** [review]
🚀

**Review by braydonk — APPROVED** [review]
Thank you!

**Review by djaglowski — APPROVED** [review]

**Review by dashpole — APPROVED** [review]
🎉

**Review by evan-bradley — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]
🙌

**Review by TylerHelmuth — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Thanks @braydonk!

**Pull request merged**
