### PR TITLE
Add retry loop for flaky tests

### PR DESCRIPTION
**Pull request by kevinearls**
Signed-off-by: Kevin Earls <kearls@redhat.com>

**Description:** <Describe what has changed.>
This adds a retry loop to fix flaky tests.

**Link to tracking Issue:** 
#10368 , #10369 , #10370

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@kevinearls do you know why these tests are failing to properly find open ports?  Is there a bug somewhere in `testutil.GetAvailablePort(t)` that is the root cause that can be fixed?

**Comment by kevinearls** [comment]
@TylerHelmuth No, I don't really.  I tried taking that approach but couldn't figure it out.  Unfortunately I don't really have much more time to spend on this right now.

**Comment by bogdandrutu** [comment]
@kevinearls @TylerHelmuth I have a fix for the root problem, see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10872

**Comment by bogdandrutu** [comment]
@kevinearls thanks for your contribution, we merged the other PR that fixed the root cause.

**Pull request closed without merging**
