### PR TITLE
[pkg/stanza] add symlink related test for fileconsumer

### PR DESCRIPTION
**Pull request by ChrsMark**
**Description:** <Describe what has changed.>

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32292 was closed due to inactivity. This PR resumes from there.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

Co-authored-by: Shaunak Kashyap <ycombinator@gmail.com>

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]
Nice, thanks!

**Comment by ChrsMark** [comment]
@djaglowski can we enable the Windows' execution for this as well? I just want to ensure that it won't end up flaky on Windows :)

**Comment by ChrsMark** [comment]
Hmm, interestingly it failed. Since this test is quite "timing sensitive" I assume that the failure could be related to the timing issues reported at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32715#issuecomment-2107737828?

**Comment by djaglowski** [comment]
> Hmm, interestingly it failed. Since this test is quite "timing sensitive" I assume that the failure could be related to the timing issues reported at [#32715 (comment)](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32715#issuecomment-2107737828)?

Yeah, at some point we really need to find a solution to this. Seems like almost all the tests we skip for windows may be due to this issue.

**Pull request merged**
