### PR TITLE
Add elasticsearchexporter to opentelemetry contrib components list

### PR DESCRIPTION
**Pull request by urso**
**Description:** 

- Update elasticsearch exporter Readme to reflect the current set of supported settings
- Add elasticsearch exporter to the list of exporters in the otelcontribcol default binary

**Link to tracking Issue:** #1800 

**Documentation:** Readme file has been updated to show only settings currently supported. Planned settings not yet implemented are removed for now.

### CODE REVIEW

**Comment by dmitryax** [comment]
I think it worth breaking down into two PRs since there are two different changes

**Review by faec — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Build failed.

**Comment by tigrannajaryan** [comment]
Needs a rebase and the build is still in a failed state.

**Comment by seesharper** [comment]
Hi guys. Any news on this? It would be awesome to be able to export logs to ElasticSearch 😍

**Pull request closed without merging**
