### PR TITLE
[chore] move mezmo exporter to generated lifecycle tests

### PR DESCRIPTION
**Pull request by Frapschen**
Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27849

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
LGTM

**Review by codeboten — COMMENTED** [review]
Pinging code owners @dashpole, @billmeyer, @gjanco, please review

**Comment by atoulme** [comment]
Pinging code owners @dashpole, @billmeyer, @gjanco, please review?

**Comment by atoulme** [comment]
Pinging code owners @dashpole, @billmeyer, @gjanco, please review?

**Review by dashpole — APPROVED** [review]

**Pull request merged**
