### PR TITLE
chore: update CODEOWNERS for Sumo Logic Components

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

#31620 but following the process

Update codeowners for Sumo Logic components with the following list of owners:

- @aboguszewski-sumo
- @kkujawa-sumo 
- @mat-rumian
- @rnishtala-sumo
- @sumo-drosiek 
- @swiatekm-sumo

**Link to tracking Issue:** N/A

**Testing:** N/A

**Documentation:** N/A

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
@astencel-sumo I removed you, so we won't need to do it in the future. Feels bad about it 😭

**Review by swiatekm — APPROVED** [review]

**Review by kasia-kujawa — APPROVED** [review]

**Review by rnishtala-sumo — APPROVED** [review]

**Review by mat-rumian — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]
I believe all that's left is an approval from @aboguszewski-sumo 👍

**Comment by sumo-drosiek** [comment]
and @astencel-sumo as I removed him from extension 😅

**Review by aboguszewski-sumo — APPROVED** [review]

**Review by andrzej-stencel — COMMENTED** [review]
:+1:

**Pull request merged**
