### PR TITLE
[receiver/awscloudwatchmetricsreceiver] AWS CloudWatch metrics receiver

### LINKED ISSUE #15667: New component: AWS CloudWatch metrics receiver
### The purpose and use-cases of the new component

Collect metrics from AWS Cloudwatch metrics and parse them in to OTel pmetric. Some metrics on AWS, such as Lambda memory usage etc, are  only available from CloudWatch — users may want them to be put in one platform for analysis such as Prometheus with Grafana.

### Example configuration for the component

```
receivers:
    awscloudwatchmetrics:
        region: <aws_region>
        profile: <aws_profile> # optional if omitted will use default for current if the AWS credential environment variables are not set
        polling_interval: 60
        metrics:
          named: 
             - namespace: AWS/ALB
                metric_name: RequestCount
             - namespace: AWS/ALB
                metric_name: 500Count
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

_No response_

### Additional context

Functionality is similar to AWSContainerMetrics receiver, maybe extend that instead and make it more generic?

### PR DESCRIPTION
**Pull request by lewis262626**
**Description:** New AWS CloudWatch metrics receiver

**Link to tracking Issue:** Fixes #15667 

**Testing:** Currently only unit tests for `Config` struct. Intending to add unit tests and integration tests

### CODE REVIEW

**Comment by lewis262626** [comment]
cc @jpkrohling @kovrus

**Comment by dmitryax** [comment]
@jpkrohling @kovrus PTAL as sponsors

**Comment by kovrus** [comment]
@lewis262626 would it be possible to split this PR into a few pull requests? We can start with the component stub, then follow up with core logic and wrap it up by adding it to the distribution.  

> Testing: Currently only unit tests for Config struct. Intending to add unit tests and integration tests

So it would be enough to have this kind of testing and skeleton of the component to get the first PR merged.

**Comment by lewis262626** [comment]
@kovrus Ok sure, I'll close this PR and open another one with just the stub

**Pull request closed without merging**
