### PR TITLE
make update-otel

### PR DESCRIPTION
**Pull request by codeboten**
Updating core to prepare for release later this week.

### CODE REVIEW

**Comment by pmm-sumo** [comment]
Seems this test has some problems:

```
make -C ./receiver/cloudfoundryreceiver test
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/cloudfoundryreceiver'
go test -race -v -timeout 300s --tags="" ./...
=== RUN   TestLoadConfig
--- PASS: TestLoadConfig (0.01s)
=== RUN   TestLoadInvalidConfig
--- PASS: TestLoadInvalidConfig (0.00s)
=== RUN   TestInvalidConfigValidation
--- PASS: TestInvalidConfigValidation (0.00s)
=== RUN   TestHTTPConfigurationStructConsistency
    config_test.go:148: 
        	Error Trace:	config_test.go:148
        	            				config_test.go:110
        	Error:      	Not equal: 
        	            	expected: "mapstructure:\"tls,omitempty\""
        	            	actual  : "mapstructure:\"tls\""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(reflect.StructTag) (len=28) "mapstructure:\"tls,omitempty\""
        	            	+(reflect.StructTag) (len=18) "mapstructure:\"tls\""
        	            	 
        	Test:       	TestHTTPConfigurationStructConsistency
        	Messages:   	field TLSSetting tag match
--- FAIL: TestHTTPConfigurationStructConsistency (0.00s)
```

**Comment by jpkrohling** [comment]
This is probably related to https://github.com/open-telemetry/opentelemetry-collector/pull/5256

cc @bogdandrutu

**Comment by codeboten** [comment]
@jpkrohling @pmm-sumo fixed the test

**Comment by jpkrohling** [comment]
`tracegen` check restarted:

```
 > [build 4/4] RUN CGO_ENABLED=0 go build -o /tracegen:
#14 0.956 go: downloading go.uber.org/multierr v1.8.0
#14 0.985 go: downloading golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4
#14 1.040 go: downloading github.com/go-logr/stdr v1.2.2
#14 1.053 go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.7.0
#14 1.192 go: downloading github.com/cenkalti/backoff/v4 v4.1.2
#14 1.215 go: downloading golang.org/x/text v0.3.5
#14 3.786 /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.7.0/runtime/handler.go:11:2: google.golang.org/genproto@v0.0.0-20211118181313-81c1377c94b1: stream error: stream ID 1; INTERNAL_ERROR; received from peer
#14 3.786 /go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.6.1/client.go:23:2: google.golang.org/genproto@v0.0.0-20211118181313-81c1377c94b1: stream error: stream ID 1; INTERNAL_ERROR; received from peer
#14 3.786 /go/pkg/mod/google.golang.org/grpc@v1.45.0/status/status.go:35:2: google.golang.org/genproto@v0.0.0-20211118181313-81c1377c94b1: stream error: stream ID 1; INTERNAL_ERROR; received from peer
#14 3.786 /go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway/v2@v2.7.0/runtime/fieldmask.go:9:2: google.golang.org/genproto@v0.0.0-20211118181313-81c1377c94b1: stream error: stream ID 1; INTERNAL_ERROR; received from peer
```

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
