### PR TITLE
[chore] Remove 'skip' #11451 for tests not in need of fixes

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
Part 2 of #28679 these are the tests that can be re-enabled without requiring any code changes after #28680 is merged.

**Link to tracking Issue:**
Related to #28679

**Testing:**
Local test run on Windows for the affected packages.

**Documentation:**
N/A

### CODE REVIEW

**Comment by pjanotti** [comment]
Marked as draft until #28680 is merged.

**Comment by mx-psi** [comment]
Added `Run Windows` label to test this

**Comment by pjanotti** [comment]
Windows test failure seems unrelated

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6707698682/job/18227881486?pr=28682#step:6:804
```terminal
--- FAIL: TestScrapeMetrics_MuteErrorFlags (0.01s)
    --- FAIL: TestScrapeMetrics_MuteErrorFlags/Process_User_Error_Muted (0.00s)
        process_scraper_test.go:1059: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go:1059
            	Error:      	Not equal: 
            	            	expected: 4
            	            	actual  : 0
            	Test:       	TestScrapeMetrics_MuteErrorFlags/Process_User_Error_Muted
    --- FAIL: TestScrapeMetrics_MuteErrorFlags/Process_User_Error_Unmuted (0.00s)
        process_scraper_test.go:1059: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go:1059
            	Error:      	Not equal: 
            	            	expected: 4
            	            	actual  : 0
            	Test:       	TestScrapeMetrics_MuteErrorFlags/Process_User_Error_Unmuted
        process_scraper_test.go:1064: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_test.go:1064
            	Error:      	An error is expected but got nil.
            	Test:       	TestScrapeMetrics_MuteErrorFlags/Process_User_Error_Unmuted
```

**Comment by pjanotti** [comment]
Windows test error may be related to https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/58ee30b6bbe6c940690c63d5f8882fc5e7b2895b

**Comment by mx-psi** [comment]
I am re-running the tests. @pjanotti would you mind filing an issue for this error?

**Comment by pjanotti** [comment]
@mx-psi the Windows test is broken, it is not a flaky test. Here is the issue #28828

**Comment by dmitryax** [comment]
@pjanotti please rebase

**Comment by pjanotti** [comment]
@dmitryax I just rebased it.

**Review by dmitryax — APPROVED** [review]

**Comment by pjanotti** [comment]
It seems that the Windows runner for group cmd is running out of memory when building the test https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6723405686/job/18274204183?pr=28682

```terminal
make[2]: Entering directory 'D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/otelcontribcol'
go test -race -timeout 300s -parallel 4 --tags="" ./...
# github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol.test
runtime: VirtualAlloc of 51470336 bytes failed with errno=1455
fatal error: out of memory
```

**Comment by dmitryax** [comment]
Ok, we might need to keep some ignores until https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27850 is resolved

**Comment by pjanotti** [comment]
Next error is unrelated: `Test rpm package` failed

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6724441831/job/18277677701#step:12:1
```terminal
#3 ERROR: pulling from host registry-1.docker.io failed with status code [manifests 8.8]: 503 Service Unavailable
```
🤞🏼 will pass on retry

**Comment by dmitryax** [comment]
Thanks @pjanotti!

**Comment by pjanotti** [comment]
Cache Go step, timed out in one of the Windows runners: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6726302253/job/18282301386?pr=28682#step:5:21

Updating the branch will re-trigger the run...

**Comment by pjanotti** [comment]
Created #28859 to deal with the timeouts in "Cache Go" step.

**Comment by pjanotti** [comment]
Unrelated failure on Windows:

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6774556958/job/18411887505?pr=28682#step:6:355
```terminal
--- FAIL: TestPortsNotOpen (0.00s)
    trace_receiver_test.go:129: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated/trace_receiver_test.go:129
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:14250: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestPortsNotOpen
        	Messages:   	should have been able to listen on 14250.  jaeger receiver incorrectly started grpc
FAIL
```

**Comment by pjanotti** [comment]
Hit #9126 

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6777700983/job/18421807676?pr=28682#step:6:214:~:text=race%3A%20limit%20on,215
```terminal
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor	2.912s
```

**Comment by pjanotti** [comment]
Opened #29014 to fix the test issue that this PR is hitting.

**Comment by pjanotti** [comment]
A different error this time:

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6799872496/job/18487138027?pr=28682#:~:text=%2D%2D%2D%20FAIL%3A%20TestDeleteAfterRead_SkipPartials%20(12.36s,112

```terminal
--- FAIL: TestDeleteAfterRead_SkipPartials (12.36s)
    file_test.go:1559: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/file_test.go:1559
        	Error:      	unable to find file "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestDeleteAfterRead_SkipPartials4[107](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6799872496/job/18487138027?pr=28682#step:6:108)455909\\001\\49508273"
        	Test:       	TestDeleteAfterRead_SkipPartials
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer	34.438s
```

**Comment by pjanotti** [comment]
Hit a [previous one](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28682#issuecomment-1795812504) listed above:

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6806236253/job/18507171134?pr=28682#:~:text=%2D%2D%2D%20FAIL%3A%20TestPortsNotOpen%20(0.00s,357
```terminal
--- FAIL: TestPortsNotOpen (0.00s)
    trace_receiver_test.go:129: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated/trace_receiver_test.go:129
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:14250: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestPortsNotOpen
        	Messages:   	should have been able to listen on 14250.  jaeger receiver incorrectly started grpc
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated	1.738s
```

**Comment by pjanotti** [comment]
Next test that needs to be fixed (hit 3 times in this PR)

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6858615031/job/18649646790#step:6:351:~:text=%2D%2D%2D%20FAIL%3A%20TestPortsNotOpen%20(0.00s,358
```terminal
--- FAIL: TestPortsNotOpen (0.00s)
    trace_receiver_test.go:129: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated/trace_receiver_test.go:129
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:14250: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestPortsNotOpen
        	Messages:   	should have been able to listen on 14250.  jaeger receiver incorrectly started grpc
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver/internal/jaegerreceiverdeprecated	1.807s
```

**Comment by pjanotti** [comment]
One clean run :) https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6859943591/job/18653768567?pr=28682 

Updating the branch...

**Comment by mx-psi** [comment]
@pjanotti is this good to merge now?

**Comment by pjanotti** [comment]
@mx-psi it looks like yes, but, just as precaution let's do a few more runs just to prevent bringing more flakiness for windows runs.

**Comment by pjanotti** [comment]
Another clean Windows run, but, a failure unrelated to the change on `unittest-matrix (~1.20.11, receiver-0)` on Ubuntu, component `receiver/awsxrayreceiver`. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6881626006/job/18718421394?pr=28682#step:9:122

```terminal
--- FAIL: TestSegmentsConsumerErrorsOut (0.01s)
    receiver_test.go:194: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/awsxrayreceiver/receiver_test.go:194
        	Error:      	Received unexpected error:
        	            	values for metric 'receiver_refused_spans' did not match, expected '1.000000' got '0.000000'
        	Test:       	TestSegmentsConsumerErrorsOut
FAIL
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver	coverage: 95.5% of statements
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver	0.101s
```

Updating branch to run the tests again...

**Comment by pjanotti** [comment]
Another unrelated failure. This time `integration-tests` component `receiver/kafkametricsreceiver`:

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6882188172/job/18720198927?pr=28682#step:5:273:~:text=%2D%2D%2D%20FAIL%3A%20TestIntegration%20(73.64s,349

```terminal
--- FAIL: TestIntegration (73.64s)
    scraperint.go:121: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/coreinternal/scraperinttest/scraperint.go:121
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/kafkametricsreceiver/integration_test.go:82
        	Error:      	Condition never satisfied
        	Test:       	TestIntegration
    scraperint.go:103: number of resources doesn't match expected: 1, actual: 0
    scraperint.go:109: full log:
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
        Error scraping metrics
    scraperint.go:117: latest result:
        {}
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkametricsreceiver	73.695s
```

**Pull request merged**
