### PR TITLE
chore(sumologic): update codeowners

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

We are not going to be at Sumo Logic anymore, so we should be removed from these components

### CODE REVIEW

**Review by aboguszewski-sumo — APPROVED** [review]

**Review by kasia-kujawa — APPROVED** [review]
Thank you! ❤️

**Review by songy23 — APPROVED** [review]

**Review by mat-rumian — APPROVED** [review]
Thanks @sumo-drosiek :)

**Review by crobert-1 — APPROVED** [review]
If you prefer, you're welcome to add the relevant usernames to an `emeritus` section in the `metadata.yaml` file of each component (example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f1b57a0911f22c936a6bb7dcc79b46d127629fa5/connector/spanmetricsconnector/metadata.yaml#L10)), rather than entirely removing usernames. It's just personal preference though. 👍

**Comment by sumo-drosiek** [comment]
> If you prefer, you're welcome to add the relevant usernames to an `emeritus` section in the `metadata.yaml` file of each component (example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f1b57a0911f22c936a6bb7dcc79b46d127629fa5/connector/spanmetricsconnector/metadata.yaml#L10)), rather than entirely removing usernames. It's just personal preference though. 👍

I'll do it. Thanks!

**Review by mwear — APPROVED** [review]

**Review by rnishtala-sumo — APPROVED** [review]

**Pull request merged**
