### PR TITLE
[exporter/tanzuobservability] exponential histogram adjustment.

### PR DESCRIPTION
**Pull request by keep94**
**Description:** <Describe what has changed.>
Get rid of the smallest negative bucket which always has a count of 0.  This smallest negative bucket with count of 0 was here to give the bucket above it a lower bound. But during testing we found that most histograms have positive values anyway.  It was confusing to see a "<= -1" bucket show up all the time, so we decided to get rid of this bucket.

**Link to tracking Issue:** Issue is private and not linkable.

**Testing:** Unit tests and manual testing with the collector.

### CODE REVIEW

**Comment by dashpole** [comment]
cc @oppegard @thepeterstone
Who are the other CODEOWNERS for this exporter

**Comment by keep94** [comment]
@oppegard and @thepeterstone are the Tech Leads, but they are both out of the office for now. @deosu is going to review the code first.

**Review by deosu — APPROVED** [review]
LGTM

**Review by dashpole — APPROVED** [review]
In the future, it is useful to open issues in this repository (even if you already have issues elsewhere) describing the issue you encountered so others facing the same problem can find it and see the fix here.

**Review by oppegard — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
