### PR TITLE
[pkg/stanza] Make batching behavior configurable

### PR DESCRIPTION
**Pull request by dmitryax**
Expose configuration options to control the batching behavior of the stanza receivers:
  - `batch.max_batch_size`: The maximum number of spans to batch together.
  - `batch.timeout`: The maximum amount of time to wait before sending a batch.

Providing configuration options for batching in the receivers makes it possible to replace the batch processor and prevent data loss when an exporter returns a retriable error.

### CODE REVIEW

**Comment by djaglowski** [comment]
These setting were removed prior to declaring the filelog receiver beta, because it was unclear whether we should be batching at all. ([context](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15355#issuecomment-1286191419))

I think before we re-add these parameters, we should resolve the question of whether pkg/stanza at all. It's not clear to me that there are any real benefits, but it certainly complicates the codebase quite a bit.

**Comment by djaglowski** [comment]
One more reason we may want to remove the complicated conversion logic: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21740#issuecomment-1542369015

**Review by djaglowski — CHANGES_REQUESTED** [review]
I want to make sure we do not expose configuration for batching until we determine whether or not we are keeping the behavior. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21184#issuecomment-1523383842.

I will open an issue to propose that we remove batching from the stanza adapter. If that is rejected, then we will have to add configuration.

**Comment by dmitryax** [comment]
My motivation for this was to establish a pipeline that cannot drop any logs. After https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20511, the only part of a typical pipeline dropping data is the batch processor. Removing it drops the batch size to 100 (hardcoded in stanza receivers), which significantly slows down the whole pipeline.

This change would bring me a short-term solution. The long-term one would be https://github.com/open-telemetry/opentelemetry-collector/issues/4646. I'm good with rejecting this PR in favor of the long-term solution.

**Comment by djaglowski** [comment]
I'm still intending to evaluate ways to simplify the adapter codebase, but I've been sidetracked by some more urgent issues. In the meantime, I'd like to reiterate that adding these settings behind a feature gate seems like a reasonable way to move forward if these controls are presently urgent for anyone.

**Comment by MovieStoreGuy** [comment]
Was there any update on these changes @dmitryax , @djaglowski ?

**Comment by djaglowski** [comment]
Unfortunately, I have not found time for this. The package remains a high priority for me but my priority lately has been on making the `fileconsumer` codebase more maintainable.

**Comment by orloffv** [comment]
@djaglowski any updates?

**Comment by dmitryax** [comment]
@orloffv, I wanted to get this in to remove the batch processor and establish a resilient logs pipeline. The default batching of the filelog receiver is not as performant as the batch processor. This would be a short-term solution. Now, I'm working on a long-term solution that will be applicable to all data types https://github.com/open-telemetry/opentelemetry-collector/issues/8122. So I'm not interested in this PR anymore

**Pull request closed without merging**
