### PR TITLE
Add filereload receiver

### PR DESCRIPTION
**Pull request by newly12**
**Description:** <Describe what has changed.>

Add filereload receiver to support dynamically start/stop partial pipelines(receiver, processor) from configs.

**Link to tracking Issue:** <Issue number if applicable>
#15714 

**Testing:** <Describe what testing was performed and which tests were added.>
UT.

**Documentation:** <Describe the documentation added.>
Please check README doc.

### CODE REVIEW

**Review by mx-psi — CHANGES_REQUESTED** [review]
This needs an issue and sponsor in accordance to the [contributing guidelines for new components](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component). Thanks!

**Comment by newly12** [comment]
Had filed issue. I can fix accordingly per the guidelines suggested if the idea looks good generally. Feel free to let me know if any question.

**Comment by tigrannajaryan** [comment]
This looks very interesting, however I think functionality like this may be more useful if broken down into 3 composable parts:
- Watching of configuration in external file(s). This should work for any part of the config, instead of being a feature of a particular receiver. We already [have a mechanism](https://github.com/open-telemetry/opentelemetry-collector/blob/6b27644724d821cf6b876b32d2718705dd488d0c/confmap/provider.go#L77) for this, but it is not implemented by `fileprovider` config provider yet. We [already allow](https://github.com/open-telemetry/opentelemetry-collector/pull/6276) including external config files, but we don't watch for changes.
- Pipelines that can be connected. We have an open issue for this https://github.com/open-telemetry/opentelemetry-collector/issues/2336
- A receiver that can create other receivers. Need to figure out how it intersects with the existing receivercreator.

These bits then be composed to result in the functionality that this PR suggest, but they can also be composed in other interesting ways.

@open-telemetry/collector-approvers @open-telemetry/collector-contrib-approvers thoughts?

**Comment by newly12** [comment]
Thanks for the comment, I will take a look at confmap and see how it can be leveraged in this receiver and get back soon.

**Comment by newly12** [comment]
> Watching of configuration in external file(s). This should work for any part of the config, instead of being a feature of a particular receiver. We already [have a mechanism](https://github.com/open-telemetry/opentelemetry-collector/blob/6b27644724d821cf6b876b32d2718705dd488d0c/confmap/provider.go#L77) for this, but it is not implemented by fileprovider config provider yet. We https://github.com/open-telemetry/opentelemetry-collector/pull/6276 including external config files, but we don't watch for changes.
#5945 for watch implementation in `fileprovider`, however it looks like the current mechanism only allows external config for a component(receiver, processor?, exporter), and on config changes entire service will be restarted(by [reloadConfiguration](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/collector.go#L195-L203)), which is expensive if there is no change for some components, say exporters are not updated but only receiver configs are updated.

> Pipelines that can be connected. We have an open issue for this https://github.com/open-telemetry/opentelemetry-collector/issues/2336
#6372 for connector implementation.

> A receiver that can create other receivers. Need to figure out how it intersects with the existing receivercreator.
I think either a receiver that creates other receivers or a mechanism starts/stops pipelines dynamically. 
In fact the need is to spawn not only receivers but also processors, given usually different receivers(data source) require different processing logical, so maybe a mechanism to spawn receivers and processors(it will nice to be able to spawn exporter as well), it sounds like mechanism/ability to spawn pipelines dynamically will be needed.

**Comment by jpkrohling** [comment]
@newly12, as @tigrannajaryan pointed out, this is part of a bigger discussion. I encourage you to join the collector SIG calls if you haven't yet (I missed the last few ones myself). I'm closing this PR, but this should not discourage you from contributing features that will lead to the outcome you wanted when you proposed this.

**Pull request closed without merging**
