### PR TITLE
[chore] make update-otel

### PR DESCRIPTION
**Pull request by codeboten**

### CODE REVIEW

**Review by bryan-aguilar — APPROVED** [review]
Look like it may need another tidy.

**Comment by codeboten** [comment]
> Look like it may need another tidy.

it needed an update to the builder configuration... should really update those as part of make update-otel. will open an issue

**Comment by codeboten** [comment]
Created https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32354 to track

**Review by songy23 — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Comment by codeboten** [comment]
Superseeds https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32328

**Pull request merged**
