### PR TITLE
[chore] use a pointer receiver to fix warning

### PR DESCRIPTION
**Pull request by atoulme**

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
What is the warning being fixed by this?

**Comment by atoulme** [comment]
IntelliJ displays the following warning:
> Struct Status has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation.

**Comment by dmitryax** [comment]
Do we have any other methods on the Status struct?

**Comment by atoulme** [comment]
Yes, 
`func (s *Status) validateClass() error` and `func (s *Status) validateStability() error`

**Comment by mx-psi** [comment]
> IntelliJ displays the following warning:
> 
> > Struct Status has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation.

Would be good to have a linter that verifies this, although I haven't been able to find one :thinking: In any case, we can merge this without the linter (although could you update the PR description with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24226#issuecomment-1633521667 ?)

**Review by mx-psi — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
