### PR TITLE
[chore] Remove unmaintained file receiver

### PR DESCRIPTION
**Pull request by djaglowski**
This component never advanced beyond development status and is incomplete so I propose that it be deleted.

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Comment by crobert-1** [comment]
> Apparently this was added to the contrib distribution despite still being in development status. Consequently I think we should wait to merge this until after the release.

[That's my bad](https://github.com/open-telemetry/opentelemetry-collector-releases/pull/356), sorry about that!

**Review by crobert-1 — APPROVED** [review]

**Comment by evantorrie** [comment]
This probably should have been mentioned in the CHANGELOG for v0.95.0.

**Comment by gitck-scch** [comment]
What is required to get this file receiver back again? The file exporter should not be the dead end for supporting a offline scenario. There has to be also a corresponding file receiver beeing able to import the file persisted data again later. Or is there already another solution that supports this?

**Comment by djaglowski** [comment]
@gitck-scch, I agree it would be nice to have a file receiver with functionality that mirrors the file exporter. The primary reason this component was removed is that it was not fully implemented and no one was willing to work on it.

I would be willing to sponsor a new implementation provided that the contributor is committed to fully implementing functionality which matches the exporter. I also would require that the implementation make use of the [fileconsumer](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/stanza/fileconsumer) package so that we are not writing a redundant mechanism for tracking and reading files.

**Comment by gitck-scch** [comment]
@djaglowski, thank you for the fast reponse - I suspected already something like this.
We will take a look at the exporter and fileconsumer in order to be able to estimate the effort required for a corresponding implementation - get back to you later. 
Of course, I would also appreciate direct links to corresponding issues describing the requirements, if available.

**Comment by atoulme** [comment]
This receiver works fine: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/otlpjsonfilereceiver - feel free to make it better

**Comment by gitck-scch** [comment]
@atoulme, is this receiver capable to import files written with the file exporter (is compression (zstd) supported)? Does this receiver fulfill a different purpose in contrast to the discontinued file receiver?

**Comment by atoulme** [comment]
I don't know off the top of my head, you can check for yourself here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/otlpjsonfilereceiver

The file receiver was never completed as far as I know, so there's no real comparison to draw.

**Pull request merged**
