### PR TITLE
[exporter/clickhouse] Fix metric inserts results in empty entries

### LINKED ISSUE #18226: ClickHouse - Wrong metric inserts results in empty entries
### Component(s)

_No response_

## Description

Ingesting metrics results in empty rows. The reason is that the logic https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/sum_metrics.go#L109-L141 is wrong.

dedew

### Collector version

0.70.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  clickhouse:
    endpoint: "url"
    timeout: 10s
    database: otel
    traces_table_name: otel_traces
    logs_table_name: otel_logs
    metrics_table_name: otel_metrics
    ttl_days: 7
    sending_queue:
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 30s
      max_elapsed_time: 300s
#  logging:
#    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** Fix metric inserts results in empty entries

fix https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18226 co-author with @StarpTech

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
@Frapschen Please rebase

**Review by TylerHelmuth — COMMENTED** [review]
@Frapschen can any unit tests be add/updated to test this bug is fixed?

**Comment by Frapschen** [comment]
> @Frapschen can any unit tests be add/updated to test this bug is fixed?

The new `check Resource metadata and scope metadata` UT will test this bug is fixed

**Comment by dmitryax** [comment]
Please check the linter failures

**Comment by Frapschen** [comment]
not relate integration-test
```
coverage: 0.0% of statements
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver/internal/metadata	0.024s	coverage: 0.0% of statements [no tests to run]
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver/internal/mocks	[no test files]
?   	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/riakreceiver/internal/model	[no test files]
FAIL
```

@dmitryax ready to merge.

**Comment by dmitryax** [comment]
@Frapschen sorry for the delay. Please rebase

**Review by hanjm — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@Frapschen can you rebase to get https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18519 in your branch.  I can't get the test to pass and I've restarted multiple times.

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
I think it's ok to merge. The failing test is removed in main branch

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
