### PR TITLE
Update core to latest and configure components for the Client Authentication Extensions (2/2)

### PR DESCRIPTION
**Pull request by gramidt**
**Description:**
This is the second phase of #3507.

**Link to tracking Issue:**
#3692 

**Testing:**
Unit tests

**Documentation:**
N/A

**Notes**
Component changes are based on https://github.com/open-telemetry/opentelemetry-collector/pull/3340.

Also related to https://github.com/open-telemetry/opentelemetry-collector/issues/3282

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Looks like this needs a rebase

**Comment by gramidt** [comment]
> Looks like this needs a rebase

@jpkrohling - Most definitely will need to be rebased, and core will need to be updated as the first commit in this PR once https://github.com/open-telemetry/opentelemetry-collector/pull/3340 has been merged for it to compile. I expect I was able get the majority of the needed code in place (while not being able to compile), since my previous PRs focused on moving component clients (HTTP, gRPC) to Exporter.Start(...) were previously merged.

**Comment by gramidt** [comment]
@jpkrohling @tigrannajaryan @bogdandrutu @pavankrish123 - I can confirm after pointing the core collector module to my local core 3340 branch, `make all` was good. I'm going to do another pass, but believe we're ready to go once  https://github.com/open-telemetry/opentelemetry-collector/pull/3340 is merged.

**Comment by tigrannajaryan** [comment]
@gramidt https://github.com/open-telemetry/opentelemetry-collector/pull/3340 is merged, please go ahead with this PR.

**Comment by gramidt** [comment]
@tigrannajaryan @bogdandrutu @jpkrohling @pavankrish123 - Looks like we're ready.

**Review by pavankrish123 — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Review by tigrannajaryan — APPROVED** [review]
Thanks @gramidt !

**Pull request merged**
