### PR TITLE
Update contrib to the core v0.39.0

### LINKED ISSUE #4408: Update contrib to the latest core

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes open-telemetry/opentelemetry-collector#4408

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]
LGTM, notwithstanding flaky load tests and apparent EasyCLA outage.

**Comment by jpkrohling** [comment]
We are being affected by communitybridge/easycla#3366

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
