### PR TITLE
Remove pmm-sumo as Approver

### PR DESCRIPTION
**Pull request by pmm-sumo**
Dear community, due to a transition into another role at a different organisation I am no longer able to allocate time to be an approver of the collector-contrib

Thank you all, it was a great pleasure to work with you and also a great opportunity to learn

### CODE REVIEW

**Comment by pmm-sumo** [comment]
There will be a followup during the next couple of days with CODEOWNERS update proposal. There are several volunteers (like @swiatekm-sumo or @sumo-drosiek) that will take over some of the projects I was helping with

**Review by codeboten — APPROVED** [review]
Thank you for all your contributions!

**Review by mx-psi — APPROVED** [review]
Thank you for your contributions @pmm-sumo :)

**Review by TylerHelmuth — APPROVED** [review]
:cry:  Thanks for all you work!

**Comment by jpkrohling** [comment]
Thank you for all your help and insightful comments! Good luck on whatever you do next!

**Comment by pmm-sumo** [comment]
Wow, many thanks for the kind words @jpkrohling @TylerHelmuth @mx-psi @codeboten It was wonderful experience to work with you and be part of the community!

**Pull request merged**
