### PR TITLE
Introducing `groupbyauth` processor 

### PR DESCRIPTION
**Pull request by pmatyjasek-sumo**
**Description:** <Describe what has changed.>

The processor is based on `groupbytrace` processor. It is grouping resources associated to the same authentication token.
It is a part of multi tenant support: https://github.com/open-telemetry/opentelemetry-collector/pull/2495

**Testing:** <Describe what testing was performed and which tests were added.>
Unit tests

**Documentation:** <Describe the documentation added.>
In code comments

### CODE REVIEW

**Comment by pmatyjasek-sumo** [comment]
@jpkrohling this is related to multi tenant support opened in https://github.com/open-telemetry/opentelemetry-collector/pull/2495

**Comment by jpkrohling** [comment]
I looked at the code, and I would like to get a couple of clarifications before moving forward:

- why do you need to wait a few seconds with data in memory before releasing the data?
- wouldn't a trace come always from the same tenant? Wouldn't grouping the incoming data per trace already split tenants into different batches? I realize that you get more batches than if you group them by the auth token, but perhaps the cost isn't that high?
- if this is indeed the best way to move forward with this feature, the common parts should then be extracted on their own module. The code isn't exactly straightforward and having it mostly duplicated will most certainly cause the code to diverge in incompatible ways, causing a higher maintenance cost.

**Comment by tigrannajaryan** [comment]
>wouldn't a trace come always from the same tenant?

I am not sure this is always the case. It depends on what you call a "tenant". If a tenant is a team within one organization, each running their own service then it is quite possible that the trace may span multiple tenants if the request was handled by different teams/services.

I do not quite understand why do we need to group spans by traces if the goal is to group them by auth. IMO, trace and auth are orthogonal dimensions.

**Comment by jpkrohling** [comment]
> the trace may span multiple tenants if the request was handled by different teams/services

True, multi-tenant traces are a different use case than what I had in mind, but you are right.

**Comment by jean** [comment]
Just a note: in our case, tenant code would be running on many different devices all with their own auth tokens. Tenancy would be based on OrgId.

**Pull request closed without merging**
