### PR TITLE
[chore] update protobuf lib

### PR DESCRIPTION
**Pull request by codeboten**
This addresses various security issues raised in the repo.

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Comment by dmitryax** [comment]
Curios why renovatebot hasn't picked it up

**Review by songy23 — APPROVED** [review]
Interesting, this is picked up by dependabot but not renovatebot.

**Comment by TylerHelmuth** [comment]
They are all indirect references right? I wonder if we need to configure renovatebot to look for those.

**Comment by codeboten** [comment]
@songy23 they got picked up because they're security reports

**Pull request merged**
