### PR TITLE
Stanzareceiver

### PR DESCRIPTION
**Pull request by djaglowski**
**Description:**
- Add receiver for observIQ's [stanza](https://github.com/observIQ/stanza) log package.
- Include three basic stanza operators: [file_input](https://github.com/observIQ/stanza/blob/master/docs/operators/file_input.md), [json_parser](https://github.com/observIQ/stanza/blob/master/docs/operators/json_parser.md), [regex_parser](https://github.com/observIQ/stanza/blob/master/docs/operators/regex_parser.md)

**Testing:** 
- Unit test coverage for 100% of new code.
- [End to end tests](https://github.com/observIQ/opentelemetry-collector-contrib/blob/stanzareceiver/receiver/stanzareceiver/e2e_test.go) cover file input from a static file, as well as various file rotation scenarios.
- Simple benchmark test that measures [direct conversion](https://github.com/observIQ/opentelemetry-collector-contrib/blob/bd22e9e7a4c758173bf4c9cdf86bd2ca0c84f8ce/receiver/stanzareceiver/receiver_test.go#L84) from stanza log format to `pdata.Logs`.
- More [complex benchmark](https://github.com/observIQ/opentelemetry-collector-contrib/blob/bd22e9e7a4c758173bf4c9cdf86bd2ca0c84f8ce/receiver/stanzareceiver/receiver_test.go#L128) test that measures reading from a file, converting to `pdata.Logs`, and to emitting from the receiver.
- Testbed [scenario](https://github.com/observIQ/opentelemetry-collector-contrib/blob/bd22e9e7a4c758173bf4c9cdf86bd2ca0c84f8ce/testbed/tests/log_test.go#L33) that measures 10k logs per second flowing through stanza receiver.
- Additional functional and unit test coverage in stanza repository for [file_input](https://github.com/observIQ/stanza/blob/master/operator/builtin/input/file/file_test.go), [json_parser](https://github.com/observIQ/stanza/blob/master/operator/builtin/parser/json/json_test.go), and [regex_parser](https://github.com/observIQ/stanza/blob/master/operator/builtin/parser/regex/regex_test.go).

**Documentation:**
- `README` explains `stanza` at a high level and provides many links to `stanza` documentation.
- `testdata` contains some basic configuration examples.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@djaglowski thank you for the PR. Can you please follow these recommendations for strictiring PRs: https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#how-to-structure-prs-to-get-expedient-reviews to make sure we are able to review them quickly.

There are quite a few changes to go.sum files of other components. Please exclude them from the PR. A PR adding a component should not change anything in other components.

**Comment by djaglowski** [comment]
@tigrannajaryan No problem. I will decompose this into smaller PRs and use this one as the final.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan No problem. I will decompose this into smaller PRs and use this one as the final.

Do you want to close this PR for now? It is on my project board, I keep stumbling on it :-)

**Comment by djaglowski** [comment]
> Do you want to close this PR for now? It is on my project board, I keep stumbling on it :-)

**Pull request closed without merging**
