### PR TITLE
Add Log() to ottlfuncs

### PR DESCRIPTION
**Pull request by mterhar**
Addresses issue #18076

**Description:** <Describe what has changed.>

Adds a feature to allow OTTL expressions to get a logarithm of a value.

**Link to tracking Issue:** 18076

**Testing:** Tests were added in the same way the `Int()` function is tested

**Documentation:** Added a readme section following the same pattern as `Int()` which covers type for inputs and return values and examples.

### CODE REVIEW

**Comment by mterhar** [comment]
> [CLA Missing ID](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/196414933/18200/#/?version=2) [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/196414933/18200/#/?version=2)
> 
> * ❌ The commit ([f3b569b](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/f3b569b8e468f96d76046e78adbabd0af647ea28)). This user is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve.For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

I did this after submitting the PR. Not sure how to re-run the check since I have multiple email addresses associated with this GitHub account.

**Review by TylerHelmuth — COMMENTED** [review]
Improving how functions handle type assertion is a high priority right now in the ottl package and this PR will be affected by the outcome.  I like this function and think there is value here, but I'd like to hold off for a moment while we finalize some other PRs to minimize the amount of rework and the size of those PRs.

Related discussion: 
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18042
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16519

**Comment by TylerHelmuth** [comment]
@mterhar we're ready for a merge/rebase. I can also take up this effort if you need to hand it off.

**Comment by mterhar** [comment]
When I hit "sync fork" in the github UI it killed the pull request so I made a new one. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21825

**Pull request closed without merging**
