### PR TITLE
Remove shared use of libhoney from goroutines. Fixes #272.

### LINKED ISSUE #272: honeycombexporter.TestEmptyNode() is unstable
See https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/991/workflows/3099dddd-0525-46c2-b781-aef9b0d88bc5/jobs/1932/steps
```
==================

WARNING: DATA RACE

Write at 0x00000165f518 by goroutine 98:

  github.com/honeycombio/libhoney-go.Init()

      /home/circleci/go/pkg/mod/github.com/honeycombio/libhoney-go@v1.12.3/libhoney.go:222 +0x202

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.newHoneycombTraceExporter()

      /home/circleci/project/exporter/honeycombexporter/honeycomb.go:94 +0x1c6

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.(*Factory).CreateTraceExporter()

      /home/circleci/project/exporter/honeycombexporter/factory.go:55 +0x73

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.testTraceExporter()

      /home/circleci/project/exporter/honeycombexporter/honeycomb_test.go:82 +0x3a5

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.TestEmptyNode()

      /home/circleci/project/exporter/honeycombexporter/honeycomb_test.go:278 +0x3fd

  testing.tRunner()

      /usr/local/go/src/testing/testing.go:991 +0x1eb



Previous read at 0x00000165f518 by goroutine 52:

  github.com/honeycombio/libhoney-go.TxResponses()

      /home/circleci/go/pkg/mod/github.com/honeycombio/libhoney-go@v1.12.3/libhoney.go:511 +0x6b

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.(*honeycombExporter).RunErrorLogger()

      /home/circleci/project/exporter/honeycombexporter/honeycomb.go:287 +0x5b



Goroutine 98 (running) created at:

  testing.(*T).Run()

      /usr/local/go/src/testing/testing.go:1042 +0x660

  testing.runTests.func1()

      /usr/local/go/src/testing/testing.go:1284 +0xa6

  testing.tRunner()

      /usr/local/go/src/testing/testing.go:991 +0x1eb

  testing.runTests()

      /usr/local/go/src/testing/testing.go:1282 +0x527

  testing.(*M).Run()

      /usr/local/go/src/testing/testing.go:1199 +0x2ff

  main.main()

      _testmain.go:116 +0x337



Goroutine 52 (finished) created at:

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.(*honeycombExporter).pushTraceData()

      /home/circleci/project/exporter/honeycombexporter/honeycomb.go:121 +0xd5

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.(*honeycombExporter).pushTraceData-fm()

      /home/circleci/project/exporter/honeycombexporter/honeycomb.go:114 +0xe4

  go.opentelemetry.io/collector/exporter/exporterhelper.traceDataPusherOld.withObservability.func1()

      /home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.3.1-0.20200526215338-87af38a24676/exporter/exporterhelper/tracehelper.go:96 +0x129

  go.opentelemetry.io/collector/exporter/exporterhelper.(*traceExporterOld).ConsumeTraceData()

      /home/circleci/go/pkg/mod/go.opentelemetry.io/collector@v0.3.1-0.20200526215338-87af38a24676/exporter/exporterhelper/tracehelper.go:48 +0x14a

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.testTraceExporter()

      /home/circleci/project/exporter/honeycombexporter/honeycomb_test.go:86 +0x4b2

  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/honeycombexporter.TestExporter()

      /home/circleci/project/exporter/honeycombexporter/honeycomb_test.go:182 +0x1ae9

  testing.tRunner()

      /usr/local/go/src/testing/testing.go:991 +0x1eb

==================

--- FAIL: TestEmptyNode (0.02s)

    testing.go:906: race detected during execution of test

FAIL
```

### PR DESCRIPTION
**Pull request by paulosman**
There was a bug in a dependency causing non-deterministic test failures in the honeycomb exporter due to a data race. This change refactors RunErrorLogger to accept a channel instead of having to call methods on libhoney directly, reducing shared usage of libhoney from multiple goroutines.

See #272 for details.

### CODE REVIEW

**Comment by keitwb** [comment]
@paulosman I did an attempt at fixing a race condition in the lightstep exporter in one of the commits in my active PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/297/commits.  Can you take a look at what I did and see if it will work?  If so this can probably be closed.

**Comment by keitwb** [comment]
Hmm...looks like you might be referring to a different race.

**Comment by keitwb** [comment]
I think the following might fix it at least partially:

```diff
iff --git a/exporter/honeycombexporter/honeycomb.go b/exporter/honeycombexporter/honeycomb.go
index 338dfea..0a54538 100644
--- a/exporter/honeycombexporter/honeycomb.go
+++ b/exporter/honeycombexporter/honeycomb.go
@@ -20,6 +20,7 @@ import (

        tracepb "github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1"
        libhoney "github.com/honeycombio/libhoney-go"
+       "github.com/honeycombio/libhoney-go/transmission"
        "go.opentelemetry.io/collector/component"
        "go.opentelemetry.io/collector/component/componenterror"
        "go.opentelemetry.io/collector/consumer/consumerdata"
@@ -118,7 +119,7 @@ func (e *honeycombExporter) pushTraceData(ctx context.Context, td consumerdata.T
        // Run the error logger. This just listens for messages in the error
        // response queue and writes them out using the logger.
        ctx, cancel := context.WithCancel(ctx)
-       go e.RunErrorLogger(ctx)
+       go e.RunErrorLogger(ctx, libhoney.TxResponses())
        defer cancel()

        // Extract Node and Resource attributes, labels and other information.
@@ -289,8 +290,7 @@ func (e *honeycombExporter) Shutdown(context.Context) error {
 //
 // This method will block until the passed context.Context is canceled, or until
 // exporter.Close is called.
-func (e *honeycombExporter) RunErrorLogger(ctx context.Context) {
-       responses := libhoney.TxResponses()
+func (e *honeycombExporter) RunErrorLogger(ctx context.Context, responses chan transmission.Response) {
        for {
                select {
                case r, ok := <-responses:
```

**Comment by keitwb** [comment]
I think basically you just need to avoid accessing any of the libhoney stuff from more than one goroutine and it should be fine.

**Comment by paulosman** [comment]
> I think the following might fix it at least partially:

@keitwb I think you're right, and that's much easier than trying to protect `TxResponses()` from data races. thanks for the suggestion! I'll update the PR.

**Comment by tigrannajaryan** [comment]
@paulosman where are we with this PR? I see more failures in the testhttps://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1374/workflows/1392c193-e990-41f7-b418-51a80f488e1e/jobs/4182/steps

**Comment by paulosman** [comment]
> @paulosman where are we with this PR? I see more failures in the testhttps://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/1374/workflows/1392c193-e990-41f7-b418-51a80f488e1e/jobs/4182/steps

This is ready to merge.

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@paulosman thanks!

**Pull request merged**
