### PR TITLE
[processor/metricstransform]: Add scaling exponential histogram support

### PR DESCRIPTION
**Pull request by wildum**
**Description:** This PR adds support for the exponential histograms for the `experimental_scale_value` in the metricstransformprocessor.

The scaling works by scaling the middle value of the first bucket (the one that corresponds to the offset) and finding the offset corresponding to this new value (the method used is described here: https://opentelemetry.io/docs/specs/otel/metrics/data-model/#all-scales-use-the-logarithm-function).

The buckets are actually unchanged because they are "shifted" by the new offset. I initially remapped all the values but I ended up always having the same buckets so I left the buckets untouched to make the code simpler and save on performance.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29803

**Testing:** unit test + e2e local test

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
The code looks sane, but I need help from someone who understands about histograms. 

@carrieedwards, are you available to review this one?

**Review by carrieedwards — APPROVED** [review]
This looks good to me. I would just consider adding a comment about how there is an inherent loss of accuracy with transform exponential histogram buckets.

**Comment by wildum** [comment]
> I would just consider adding a comment about how there is an inherent loss of accuracy with transform exponential histogram buckets.

Done :)

**Comment by wildum** [comment]
@jpkrohling @dmitryax the PR is ready for another review / to be merged

**Pull request merged**
