### PR TITLE
[receiver/hostmetrics] Migrate paging scraper to the new metrics builder

### LINKED ISSUE #7139: Migrate hostmetrics / pagingscraper to the new Metrics Builder
receiver/hostmetricsreceiver/internal/scraper/pagingscraper

### PR DESCRIPTION
**Pull request by cristianciutea**
This PR migrates paging scrapper to metrics builder API (Required by open-telemetry/opentelemetry-collector-contrib#7536)

Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/10904

Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7139

### CODE REVIEW

**Comment by cristianciutea** [comment]
@dmitryax can you please approve the workflows to run? thank you!

**Comment by dmitryax** [comment]
Please rebase the PR and run `make generate`

**Comment by cristianciutea** [comment]
done

**Comment by cristianciutea** [comment]
@jpkrohling not sure if the failing checks are related with this PR. Can we re-run them? / merge the PR?

**Comment by jpkrohling** [comment]
I think I've seen only the load test failing. I rebased this and fixed the conflict on the changelog, let's see how the tests go.

**Comment by cristianciutea** [comment]
> I think I've seen only the load test failing. I rebased this and fixed the conflict on the changelog, let's see how the tests go.

Seems like all the checks have passed, can we merge this PR?

**Comment by jpkrohling** [comment]
Sorry, looks like there was a PR merged that caused a conflict with your PR. Once you rebase, and once CI is green, I'll merge this.

**Comment by cristianciutea** [comment]
> Sorry, looks like there was a PR merged that caused a conflict with your PR. Once you rebase, and once CI is green, I'll merge this.

ok, can you please run again the checks?

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
