### PR TITLE
[chore] logstransform processor - ensure context for background routines

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** 
Ensure that context used for background tasks is controlled within the lifecycle of the component.

**Link to tracking Issue:**

**Testing:** 
Need to confirm the existing tests covers this.

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
Okay, I was looking to fix the test that fails on windows but now it looks like it fails on linux too. 

Gonna spend some time investigating this to fix it.

**Comment by MovieStoreGuy** [comment]
Alright, it feels like a journey worth sharing. 

Currently using the same tests, I am at the part were the converter and then nothing happens afterwards. 

I also worry about the consumer routines can shutdown in a random order.

Currently stuck on trying to get the pipeline to return some data.

**Comment by djaglowski** [comment]
@dehaansa, would you be able to collaborate with @MovieStoreGuy on this?

**Comment by MovieStoreGuy** [comment]
Converting this to draft because I am not sure if this is still a problem.

**Comment by MovieStoreGuy** [comment]
I unfortunately haven't had much time to come back to this, so I will close this for the time being.

**Pull request closed without merging**
