### PR TITLE
[processor/cumulativetodelta]: exclude the first point after a restart in monotonic sums

### PR DESCRIPTION
**Pull request by sigilioso**
**Description:** <Describe what has changed.>

Following up #18224, this PR drops the first datapoint after a restart is detected, so unexpected spikes are avoided.

Simple example: before the changes, `100, 105, 120, 100, 110` would be converted to `5, 15, 100, 10`, when we omit the value when a restart is detected it would be `5, 15, 10`.

**Link to tracking Issue:** <Issue number if applicable>
#17190, #18053

**Testing:** <Describe what testing was performed and which tests were added.>

* A new test case was included in the proccesor to check that the value is actually omitted.
* The tracker's convert tests were updated to reflect the new behavior.

```
❯ go test ./... -race
ok      github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor  0.454s
ok      github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor/internal/tracking        1.268s
```

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by sigilioso** [comment]
As I see it, this approach would be consistent with dropping the first value (as set in #18224). Does it make sense for you?

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@sigilioso please rebase to re-trigger CI

**Review by mx-psi — APPROVED** [review]
Monotonic means it _should_ be increasing, not must, so this could cause trouble if we ever have a monotonic sum that is not increasing (see e.g. the discussion on #14956 for sums coming from statsd counts). Still, I think it makes sense to try this out for consistency; we can always reconsider if we get these edge cases in the future.

**Comment by mx-psi** [comment]
unittest (1.20) is not running (needs a rebase maybe?)

**Comment by Aneurysm9** [comment]
> Monotonic means it should be increasing, not must, so this could cause trouble if we ever have a monotonic sum that is not increasing 

Not sure this is correct.

>mon·o·ton·ic
/ˌmänəˈtänik/
adjective: monotonic
>
>    1. Mathematics
>    (of a function or quantity) varying in such a way that it either never decreases or never increases.

Monotonic means it won't go down.  `0` is a perfectly fine result from a cumulative-to-delta conversion of a monotonic sum, but not `-1`.  This is already accounted for in the existing checks.

**Comment by mx-psi** [comment]
@Aneurysm9 that's also how I use the term, but [the spec uses 'SHOULD'](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.18.0/specification/metrics/data-model.md#sums):

> A flag denoting whether the Sum is [monotonic](https://en.wikipedia.org/wiki/Monotonic_function). In this case of metrics, this means the sum is nominally increasing, which we assume without loss of generality.
> - For delta monotonic sums, this means the reader SHOULD expect non-negative values.
> - For cumulative monotonic sums, this means the reader SHOULD expect values that are not less than the previous value.

So (although I find this quite counterintuitive) I don't think we can say that an OTLP monotonic sum will never go down

**Comment by mx-psi** [comment]
@Aneurysm9 Is this PR good to go from your side?

**Review by Aneurysm9 — APPROVED** [review]

**Pull request merged**
