### PR TITLE
[CI] Never skip required matrix rollup jobs

### LINKED ISSUE #12334: [github-actions] Required check is skipped if prerequisite job fails
@djaglowski this is another example where I could merge even if lint is failing:

imagen

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12215#issuecomment-1180721087_

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #12334

Followup to #12296

### CODE REVIEW

**Comment by djaglowski** [comment]
With intentional lint and unit test failures, the rollup jobs fail.

image
image

[lint](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7342163838?check_suite_focus=true#step:3:13)
[unittest (1.18)](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7342147358?check_suite_focus=true#step:3:13)
[unittest (1.17)](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7342147532?check_suite_focus=true#step:3:13)
[windows-unittest](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7342246191?check_suite_focus=true#step:3:13)

In order to demonstrate the behavior of rerunning failed jobs, the artificial unit test failure was based on a [time constraint](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7342080844?check_suite_focus=true#step:8:133) that has now passed. Restarting the jobs should result in all of the unit test rollup jobs passing. (The lint job will still fail)

**Comment by djaglowski** [comment]
image

The `windows-unittest` job failed again, but apparently only because I ran it a bit [too soon](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7342032826?check_suite_focus=true#step:7:188) to pass the artificial time constraint. I will restart it again and it should pass this time.

**Comment by djaglowski** [comment]
I have removed the intentional failure code, so everything should pass at this point.

However, to demonstrate that the lint job can recover, I will cancel it now, and then restart it.

**Comment by djaglowski** [comment]
The rollup checks explicitly fail, even when their prerequisite jobs have been canceled:

image

---

I've now restarted the failed jobs only (most of them). We should see everything pass now.

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
