### PR TITLE
[prometheusreceiver] Handle staleNaN for `up` metric

### LINKED ISSUE #5249: Invalid "up" metric
When I use the prometheus receiver, I often see the following error:

```2021-09-16T06:28:33.422Z	warn	internal/metricsbuilder.go:139	The 'up' metric contains invalid value	{"kind": "receiver", "name": "prometheus", "value": "NaN", "scrape_timestamp": 1631773712738, "target_labels": "map[__name__:up instance:192.168.32.58:8443 job:k8s]"}```

My Prometheus scrape config is:

```
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 60s
              static_configs:
                - targets: ['0.0.0.0:8888']
            - job_name: k8s
              kubernetes_sd_configs:
              - role: pod
 ```

I run public.ecr.aws/w6n7a8r1/prometheus-example which publishes Prometheus metrics at :9090/metrics.

### PR DESCRIPTION
**Pull request by gouthamve**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5249

TODO:
- [x] Tests
- [x] Changelog

### CODE REVIEW

**Comment by gouthamve** [comment]
Noooooope, closing this because NaN is never exposed via `federate` endpoint: https://github.com/prometheus/prometheus/blob/0b41fd6e716f3e8b79016f73b6dd77fdf5fcdced/web/federate.go#L123-L129


I have another idea as to what might cause #5249, will investigate that.

**Comment by gouthamve** [comment]
DONOT MERGE: Depends on https://github.com/prometheus/prometheus/pull/10588 being merged. 

But once the above PR is merged, we will see the error in #5249 whenever a target goes away (I've verified it). I've fixed it here and will make the PR ready once upstream PR is merged.

**Comment by gouthamve** [comment]
@dashpole This is now ready for review. I am confident that #5249 will be fixed with this.

**Review by dashpole — APPROVED** [review]
Nice find

**Review by codeboten — APPROVED** [review]

**Pull request merged**
