### PR TITLE
NR expand kafka broker metrics

### PR DESCRIPTION
**Pull request by 4demos**
**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by 4demos** [comment]
@dmitryax here is the replacement of #22839

**Comment by dmitryax** [comment]
Please resolve the CI failures

**Comment by 4demos** [comment]
metrics data from sarama
[
75%,
95%,
99%,
99.9%,
count,
max,
mean,
median,
min,
stddev,
]

it doesn't look like we could fetch cumulative sum.
 
Though looks like the rates come from this source https://github.com/rcrowley/go-metrics/blob/master/meter.go
and there there are different rates: rate1, rate5, rate15, rateMean (this one returns mean rate of events per second), the rest \d+ -minute moving average rate

**Comment by dmitryax** [comment]
Isn't `count` the cumulative sum?

**Pull request closed without merging**
