### PR TITLE
Fixed k8s update event causing span to be rejected

### PR DESCRIPTION
**Pull request by linliaoy**
Instead of deleting the old ip address before updating the new ip address, it will be modified in the temporary area before updating

**Description:** Fixed the parsing bug of loadbalancingexporter k8s service, where the exporter deletes the old ip address and then updates the new ip address, instead of modifying it in the temporary area before updating it

**Link to tracking Issue:** [<Issue number if applicable>](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32482#issuecomment-2068403478)

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Can you add some tests for this? Also, do you have an example of the event that is emitted by Kubernetes on this situation? How would we receive an event that ends up with no endpoints?

**Comment by linliaoy** [comment]
> Can you add some tests for this? Also, do you have an example of the event that is emitted by Kubernetes on this situation? How would we receive an event that ends up with no endpoints?
Here is an example, I have three pods, k8s update events every 3 minutes
`{"metadata":{"name":"backends-headless","namespace":"observability","uid":"","resourceVersion":"","creationTimestamp":"2024-03-18T07:51:37Z","labels":{"service.beta.openshift.io/serving-cert-secret-name":"backends-headless","service.kubernetes.io/headless":""},"annotations":{"endpoints.kubernetes.io/last-change-trigger-time":"2024-05-06T04:37:00Z"},"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2024-05-06T04:37:00Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:endpoints.kubernetes.io/last-change-trigger-time":{}},"f:labels":{".":{},"f:service.beta.openshift.io/serving-cert-secret-name":{},"f:service.kubernetes.io/headless":{}}},"f:subsets":{}}}]},"subsets":[{"addresses":[{"ip":"172.16.12.118","nodeName":"172.16.12.19","targetRef":{"kind":"Pod","namespace":"observability","name":"otel-collector-backend-79d467c98f-tmttb","uid":""}},{"ip":"172.16.8.206","nodeName":"172.16.8.18","targetRef":{"kind":"Pod","namespace":"observability","name":"otel-collector-backend-79d467c98f-qjq8t","uid":""}},{"ip":"172.31.4.27","nodeName":"172.31.7.49","targetRef":{"kind":"Pod","namespace":"observability","name":"otel-collector-backend-79d467c98f-rvwt6","uid":""}}],"ports":[{"name":"otlp-grpc","port":4317,"protocol":"TCP","appProtocol":"grpc"},{"name":"otlp-http","port":4318,"protocol":"TCP","appProtocol":"http"}]}]}`

**Comment by linliaoy** [comment]
> Can you add some tests for this? Also, do you have an example of the event that is emitted by Kubernetes on this situation? How would we receive an event that ends up with no endpoints?

**Comment by linliaoy** [comment]
@jpkrohling I'm sorry I clicked the wrong button and the pr shut down

**Comment by linliaoy** [comment]
When I set deploy scale to 0, I waited about 3 minutes to receive an update event with empty subsets，The pod died before this update event was received。            
 `{"metadata":{"name":"backends-headless","namespace":"observability","uid":"","resourceVersion":"","creationTimestamp":"2024-03-18T07:51:37Z","labels":{"service.beta.openshift.io/serving-cert-secret-name":"backends-headless","service.kubernetes.io/headless":""},"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2024-05-06T04:33:12Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:service.beta.openshift.io/serving-cert-secret-name":{},"f:service.kubernetes.io/headless":{}}}}}]}}`

**Comment by linliaoy** [comment]
@jpkrohling What other test information do you need to provide

**Comment by jpkrohling** [comment]
> What other test information do you need to provide

I'd need a unit test to be part of this PR. I looked into creating one based on the event you provided, but the code seems pretty clear about which types of events it's interested in:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/70cfd058142279650a8c1dd77283dcd47619726f/exporter/loadbalancingexporter/resolver_k8s_handler.go#L27-L35

Do you see the log message from line 31 in your collector logs? How are your collector metrics for loadbalancer_num_resolutions ?

**Comment by linliaoy** [comment]
> When I set deploy scale to 0, I waited about 3 minutes to receive an update event with empty subsets，The pod died before this update event was received。
> 
> ```
> {"metadata":{"name":"backends-headless","namespace":"observability","uid":"","resourceVersion":"","creationTimestamp":"2024-03-18T07:51:37Z","labels":{"service.beta.openshift.io/serving-cert-secret-name":"backends-headless","service.kubernetes.io/headless":""},"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2024-05-06T04:33:12Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:service.beta.openshift.io/serving-cert-secret-name":{},"f:service.kubernetes.io/headless":{}}}}}]}}
> ```

@jpkrohling I have to admit a mistake, I received the above message immediately when the scale was 0

**Comment by linliaoy** [comment]
> > What other test information do you need to provide
> 
> I'd need a unit test to be part of this PR. I looked into creating one based on the event you provided, but the code seems pretty clear about which types of events it's interested in:
> 
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/70cfd058142279650a8c1dd77283dcd47619726f/exporter/loadbalancingexporter/resolver_k8s_handler.go#L27-L35
> 
> Do you see the log message from line 31 in your collector logs? How are your collector metrics for loadbalancer_num_resolutions ?
There is no log of 31 lines in the log message, I tested that the update event (*corev1.Endpoints) can be resolved, neither line 31 nor 73 will be executed, and there is no statistics of loadbalancer_num_resolutions in metrics。When the scale is 0, the most obvious result is otelcol_receiver_refused_spans metrics and couldn't find the exporter for the endpoint ""

**Comment by jpkrohling** [comment]
> and there is no statistics of loadbalancer_num_resolutions in metrics

This is odd, let me play with this before reviewing this PR, as this should clearly report a value.

**Comment by jpkrohling** [comment]
I see some odd things there, like a gap where no metrics were collected, but other than that, I think everything can be explained, especially by scale-down events. I'll keep investigating, but there's a gist with a reproducer and a few resources:
image

https://gist.github.com/jpkrohling/2e2ee52e8921e1a26ef91b19557fdb2b

**Comment by linliaoy** [comment]
> > and there is no statistics of loadbalancer_num_resolutions in metrics
> 
> This is odd, let me play with this before reviewing this PR, as this should clearly report a value.



> loadbalancer_num_resolutions


I'm looking at the wrong node, loadbalancer_num_resolutions are there

**Comment by linliaoy** [comment]
@jpkrohling How's the investigation going

**Comment by jpkrohling** [comment]
I'm still waiting for information: you told me you have the metric, but not how it looks like...

**Comment by linliaoy** [comment]
> I'm still waiting for information: you told me you have the metric, but not how it looks like...

This is what happens when you use the fixed code：
image

Without fixing the code similar to the picture you sent above, there is data from time to time

**Pull request closed without merging**
