### PR TITLE
[exporter/coralogixexporter] Remove old tracing client

### LINKED ISSUE #7931: version command prints jaeger errors
**Describe the bug**

version command prints jaeger errors

```
./otelcontribcol --version
2022/02/15 09:48:33 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/02/15 09:48:33 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
otelcontribcol version latest
```

**Steps to reproduce**

build v0.44.0 and run `--version`

**What did you expect to see?**

no warnings

### LINKED ISSUE #16550: [exporter/coralogix] Component is unmaintained
### Component(s)

exporter/coralogix

### Describe the issue you're reporting

This component is owned by @oded-dd and @povilasv. As stated on #16548, an issue related to this component has not received an answer within the time specified in our [guidelines](https://github.com/open-telemetry/opentelemetry-collector#unmaintained), therefore we are marking it as unmaintained.

If this component's issues are not actively attended, the component will be removed from official builds on 2023-05-30.

### PR DESCRIPTION
**Pull request by povilasv**
**Description:** <Describe what has changed.>

Removing old jaeger based tracing client from coralogix exporter so that there are no more collisions with regular jaeger exporter

**Link to tracking Issue:**  #7931

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by mx-psi** [comment]
> changelog failure seems to not like me reverting the unmaintained pr 

I added `Skip changelog` to bypass the check since the changelog is fine, will file an issue for looking into this

**Comment by mx-psi** [comment]
Didn't mean to close, sorry :)

**Comment by mx-psi** [comment]
@jpkrohling since you reviewed the previous PR about this new client, would you mind reviewing this PR too?

**Review by oded-dd — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]
LGTM, will wait for @jpkrohling review until EOD and merge otherwise

**Review by jpkrohling — APPROVED** [review]
Breaking change, but it's just removing a deprecated feature.

**Pull request merged**
