### PR TITLE
[receiver/jmx] mark receiver as deprecated

### PR DESCRIPTION
**Pull request by codeboten**
After many discussions it seems the community is leaning towards removing the components that execute subprocesses. As such, marking the JMX receiver as deprecated.

Related: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6750

If folks are ok with this path moving forward, I can follow this up with a PR to remove the component from the manifest in the releases repository in the next version.

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Comment by djaglowski** [comment]
While I generally agree with the concerns expressed by the community about running subprocesses, I did not think we had reached consensus to universally prohibit them. This receiver provides valuable functionality equivalent to a [dozen scrapers](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/jmx-metrics/README.md#target-systems) and is not easily replaced.

Technically, we still have [guidelines for running subprocesses](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#executing-external-processes) as well as [documentation describing this type of use case](https://github.com/open-telemetry/opentelemetry-collector/blob/03c7bf98f7edf6e578aac303e4d8b767f117541e/docs/security.md#subprocesses). 

I don't want to drag on what has already been an intractable issue, but before this component is deprecated, I think we should establish whether we are prohibiting subprocesses in general vs defining stricter standards that allow for subprocesses under certain circumstances.

If we are not prohibiting subprocesses in general, then I think #6750 is still a relevant conversation. [This comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6750#issuecomment-1040433979) seems to have articulated a strategy that would go a long way toward securing the component. Certainly there would be more to it as well. I'm happy to push on that thread if we are still open to keeping the component.

**Review by codeboten — COMMENTED** [review]
@djaglowski I've added this to the agenda for the SIG meeting tomorrow. I chatted with some of the maintainers/approvers about this last week and the general sense I got from that thread is that folks preferred moving in the direction of removing the components.

I'll wait until the discussion tomorrow before moving this PR, #9062, and #9058 forward.

**Review by mx-psi — CHANGES_REQUESTED** [review]
I originally approved this, but I think one important thing missing from this PR is adding a `//Deprecated:` message to jmxreceiver's go.mod file: we want downstream distros to be aware of the removal

**Comment by codeboten** [comment]
Closing this PR as per the comment: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6750#issuecomment-1090476712

**Pull request closed without merging**
