### PR TITLE
[chore] move f5cloud exporter to generated lifecycle tests

### PR DESCRIPTION
**Pull request by Frapschen**
Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27849

### CODE REVIEW

**Comment by atoulme** [comment]
Pinging @gramidt for codeowner review.

**Comment by atoulme** [comment]
It looks like there are no codeowners left on this component. I will start the work to mark this component as unmaintained.

**Comment by codeboten** [comment]
@atoulme the component is already deprecated 👍🏻

**Comment by dmitryax** [comment]
@Frapschen can you please rebase?

**Comment by atoulme** [comment]
Rebased.

**Review by dmitryax — APPROVED** [review]

**Comment by atoulme** [comment]
I would like to close this PR. The component is deprecated and will be removed soon. Please reopen if you disagree.

**Pull request closed without merging**
