### PR TITLE
[translator/zipkin] stop dropping error tags in Zipkin translator

### PR DESCRIPTION
**Pull request by SimunKaracic**
**Description:** <Describe what has changed.>
Fixing a bug - Stop dropping error tags from Zipkin spans. The old code removes all errors from those spans, rendering them useless if an actual error happened. In addition, no longer delete error tags if they contain useful information. This now only deletes them if they are "true", and thus don't contain useful information. Also fixes the whole issue of 

**Link to tracking Issue:** #16530

**Testing:** Absolutely none, I have written no Go code before this and have not even run the code.

I'm hoping CI saves me the trouble of installing and running everything locally

### CODE REVIEW

**Comment by SimunKaracic** [comment]
I realise I'm dropping out of nowhere, but this is a _simple_ issue that is completely blocking anyone who uses Tempo.
Please help me get it over the finish line

**Review by crobert-1 — APPROVED** [review]
This follows the original bug fix proposal from what I can tell, so it LGTM.

Also, I wrote some tests that failed with the original issue before your change, and now work as expected after. You're welcome to pull those in for this PR, and someone else can review those changes as well.

[New tests added](https://github.com/crobert-1/opentelemetry-collector-contrib/commit/d52c6db6063d3be05218b5b8a26e14aaf8705f1d)

**Comment by SimunKaracic** [comment]
Thank you so much @crobert-1 !
I've pulled in the tests, it should LGT everyone now 🚀

**Comment by SimunKaracic** [comment]
Is there any way this can be included in the next release? 
It would be of great help to be able to show errors in traces

**Comment by atoulme** [comment]
Please add a changelog entry.

**Comment by SimunKaracic** [comment]
Done! Is there a regular release cadence or something, so I know when to expect the release?

**Comment by crobert-1** [comment]
> Done! Is there a regular release cadence or something, so I know when to expect the release?

Releases are generally created every two weeks or so, but there isn't a set schedule. [Here are all of the releases for historic context.](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases)

**Review by atoulme — APPROVED** [review]
LGTM, I would ask a codeowner of the package to review as well.

**Comment by jpkrohling** [comment]
@MovieStoreGuy @astencel-sumo, if you could review this within the next few hours, we can include it on this week's release.

One code owner has approved this already (@crobert-1), but it would still be good to have more approvals :-)

**Review by MovieStoreGuy — APPROVED** [review]

**Pull request merged**
