### PR TITLE
[docs] Add status header for couchbase receiver

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>
Add status header for couchbase receiver

### CODE REVIEW

**Comment by mx-psi** [comment]
@djaglowski @cpheps to review as CODEOWNERS

**Review by cpheps — APPROVED** [review]

**Comment by mx-psi** [comment]
> Hey @mx-psi I can approve your PR but I think we likely are going to remove the Couchbase receiver as it's unfinished and according to #9254 the recommended way to monitor Couchbase is to use a config that uses the prometheus receiver and processors.

Should it be marked as deprecated then?

**Comment by cpheps** [comment]
>Should it be marked as deprecated then?

Probably... it was never actually finished so it doesn't even work. I'm not sure if we need to deprecate then remove or if we can just remove as it's unfinished.

**Comment by mx-psi** [comment]
I would prefer to mark it as deprecated (adding a logging message for the deprecation and also deprecating the Go module) before removing it, but I will let @djaglowski decide :)

**Comment by cpheps** [comment]
>I would prefer to mark it as deprecated (adding a logging message for the deprecation and also deprecating the Go module) before removing it, but I will let @djaglowski decide :)

Sounds good. I reached out to him outside of this PR also.

**Pull request closed without merging**
