### PR TITLE
[connector/spanmetrics] spanmetrics connector support exemplar

### LINKED ISSUE #20771: [connector/spanmetrics] spanmetrics connector do not attach exemplar any more
### Component(s)

connector/spanmetrics

## Description

After using spanmetrics connector instead of spanmetrics processor, I found that exemplar info are no longer attached to metrics.

I tried to dig and find the possible root cause is 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3dc9d21b4a10130d2f8edc481329356665cf5d0f/connector/spanmetricsconnector/internal/metrics/metrics.go#L113-L114

and I already tried to fix it and send a pr. Please correct me if I do it wrong.

## Steps to Reproduce

Just use the basic usage of spanmetrics connector and use prometheus receiver, check about the exemplar info on prometheus ui, you will find exemplar info can not be displayed

### Collector version

0.75.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** <Describe what has changed.>
fix #20771

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by kovrus — APPROVED** [review]
lgtm 👍

**Comment by fatsheep9146** [comment]
@albertteoh could you also help review about this?

**Review by albertteoh — APPROVED** [review]
Looks good!

**Comment by fatsheep9146** [comment]
@djaglowski could you help review this?

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
