### PR TITLE
[exporter/loki] Remove usage of LogRecord Name field

### LINKED ISSUE #7555: Remove usage of LogRecord Name field in lokiexporter
The LogRecord Name field [is removed](https://github.com/open-telemetry/opentelemetry-specification/pull/2271) from the specification and is [going to be removed](https://github.com/open-telemetry/opentelemetry-proto/pull/357) from the OTLP.

Please remove usage of this field in the component.

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #7555

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Changelog?

**Comment by jpkrohling** [comment]
Not sure -- are those changes affecting the end-users? I would expect instrumentation libraries to add the name as attributes in the future if that's needed. But my understanding might be wrong, in which case I will gladly add a changelog.

**Comment by mx-psi** [comment]
> Not sure -- are those changes affecting the end-users? I would expect instrumentation libraries to add the name as attributes in the future if that's needed. But my understanding might be wrong, in which case I will gladly add a changelog.

I would expect the same thing, but logs is the part of OpenTelemetry that I know the least about.

**Comment by jpkrohling** [comment]
I'll add a changelog entry to be on the safe side.

**Comment by jpkrohling** [comment]
Actually, @tigrannajaryan opened #7553 without a changelog either. Given that he was involved in the decision to remove this property from the spec, I think we should follow his lead here and not add a changelog entry.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
