### PR TITLE
Add the AWS distribution to the list of distributions

### PR DESCRIPTION
**Pull request by DewaldDeJager**
**Description:** Add the AWS Distribution for OpenTelemetry Collector (ADOT) to the list of distributions in the metadata files for the components included in the distribution. See list of components [here](https://github.com/aws-observability/aws-otel-collector/#adot-collector-built-in-components).

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22980

### CODE REVIEW

**Review by MovieStoreGuy — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Thanks for updating these. Please add the healthcheck extension as well.

**Comment by TylerHelmuth** [comment]
@bryan-aguilar @Aneurysm9 @rapphil is `aws` the correct listing or would you like `adot`?

**Comment by bryan-aguilar** [comment]
`aws` is good. Thanks for checking!

**Comment by DewaldDeJager** [comment]
> 

Thanks for catching that! I have included it now.

**Review by dmitryax — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
