### PR TITLE
[chore] reuse struct when parsing to avoid recursive parsing

### PR DESCRIPTION
**Pull request by atoulme**
**Description:** 
This is a companion PR to handle recursive state of unmarshalers with https://github.com/open-telemetry/opentelemetry-collector/pull/9750. Changing this behavior will allow the confmap.Conf object to recognize that it has already run the `Unmarshal` method on the struct, and run the mapstructure decoding of fields.

### CODE REVIEW

**Comment by mx-psi** [comment]
Looks like tests in `pkg/stanza` are failing (example of first failure, there are many more in the same matrix test):

```
=== Failed
=== FAIL: fileconsumer TestUnmarshal/include_one (0.00s)
    confmap.go:48: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/stanza/operator/operatortest/confmap.go:48
        	Error:      	Received unexpected error:
        	            	1 error(s) decoding:
        	            	
        	            	* '' has invalid keys: include, type
        	Test:       	TestUnmarshal/include_one
```

**Comment by atoulme** [comment]
Looks like the 2 PRs need each other.

**Comment by atoulme** [comment]
Splitting the `pkg/stanza` changes to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31802

**Review by crobert-1 — APPROVED** [review]

**Comment by atoulme** [comment]
This is good to go now - the PR will accommodate to the deprecation of the component.UnmarshalConfig function.

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
