### PR TITLE
Readability improvements to the EC2 resource detection processor

### PR DESCRIPTION
**Pull request by rakyll**
Move relevant types to the same file, avoid suttering in naming, providing Go-like type names not like Java.  Also share the connection instead of creating a new connection per fetch.

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Thanks!

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by tigrannajaryan** [comment]
The build failed:
```
make -j2 for-all-target TARGET=lint

make -C ./exporter/alibabacloudlogserviceexporter lint
make -C ./exporter/awsemfexporter lint
make[1]: Entering directory '/home/circleci/project/exporter/alibabacloudlogserviceexporter'
make[1]: Entering directory '/home/circleci/project/exporter/awsemfexporter'
staticcheck FAILED => static check errors:

-: could not analyze dependency github.com/open-telemetry/opentelemetry-collector-contrib/exporter/alibabacloudlogserviceexporter [github.com/open-telemetry/opentelemetry-collector-contrib/exporter/alibabacloudlogserviceexporter.test] of github.com/open-telemetry/opentelemetry-collector-contrib/exporter/alibabacloudlogserviceexporter.test (compile)
logs_exporter_test.go:49:51: AttributeHostHostname not declared by package conventions (compile)

make[1]: *** [../../Makefile.Common:98: lint-static-check] Error 1
make[1]: Leaving directory '/home/circleci/project/exporter/alibabacloudlogserviceexporter'
make: *** [Makefile:111: for-all-target-./exporter/alibabacloudlogserviceexporter] Error 2
make: *** Waiting for unfinished jobs....
Static check finished successfully
golangci-lint run --allow-parallel-runners
make[1]: Leaving directory '/home/circleci/project/exporter/awsemfexporter'

Exited with code exit status 2

CircleCI received exit code 2
```

**Comment by bogdandrutu** [comment]
@tigrannajaryan the build was fixed on master, that's why I said just to rebase

**Comment by rakyll** [comment]
Rebased, sorry I was disconnected during the holidays.

**Comment by bogdandrutu** [comment]
make[2]: Entering directory '/home/circleci/project'
running go unit test ./... + coverage in /home/circleci/project
# github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor
processor/resourcedetectionprocessor/factory.go:60:6: cannot use ec2.NewDetector (type func() (*ec2.Detector, error)) as type "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal".DetectorFactory in map value
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol [build failed]
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/internal	0.196s	coverage: [no statements]
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/internal/version	0.147s	coverage: 0.0% of statements [no tests to run]
FAIL

**Comment by bogdandrutu** [comment]
@rakyll please fix the build :), sent the error

**Comment by rakyll** [comment]
PTAL, I think the failure is coming from the code coverage.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
