### PR TITLE
[exporter/azuredataexplorer] add workload identity authentication

### PR DESCRIPTION
**Pull request by roysha1**
**Description:** 
Adding workload identity authentication option

Links:
- https://learn.microsoft.com/azure/developer/go/azure-sdk-authentication?tabs=bash#2-authenticate-with-azure
- https://github.com/Azure/azure-kusto-go/blob/11658efc9faad4d0300afdc4af9a19c470b0313a/azkustodata/kcsb.go#L294C1-L298C2

### CODE REVIEW

**Comment by roysha1** [comment]
@asaharn / @ag-ramachandran can you please review?

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by ag-ramachandran** [comment]
LGTM!

**Review by dmitryax — APPROVED** [review]

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
I don't think I have rebased against main so much in a single PR.

**Comment by ag-ramachandran** [comment]
> I don't think I have rebased against main so much in a single PR.

Hello @MovieStoreGuy , Sorry about that. I will have a look at it today as well

**Comment by ag-ramachandran** [comment]
Hello @MovieStoreGuy , lets hold on for the merge today (10/Apr/2024). There are some changes in the underlying SDK as well. Will try and see if the feature added is compatible with that

@roysha1 : will sync with you on this

**Comment by ag-ramachandran** [comment]
> Hello @MovieStoreGuy , lets hold on for the merge today (10/Apr/2024). There are some changes in the underlying SDK as well. Will try and see if the feature added is compatible with that
> 
> @roysha1 : will sync with you on this

Hello @MovieStoreGuy , Looks good to be merged. The only check that is failing is a UT test report upload.

**Pull request closed without merging**
