### PR TITLE
[docs] update README for routing

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** add status header for routing

### CODE REVIEW

**Comment by djaglowski** [comment]
@jpkrohling, as code owner, do you agree this component is beta?

**Review by codeboten — COMMENTED** [review]
Not related to this PR but i noticed on line 12 it says that `processor does not let traces to continue`, should this be updated to say traces/metrics/logs?

**Comment by jpkrohling** [comment]
@Frapschen, are you using this in production? Even though I feel that this is indeed being used in production out there, I do not have a specific one I can use as a reference. Without one, this component should still be in alpha.

**Comment by Frapschen** [comment]
> Not related to this PR but i noticed on line 12 it says that `processor does not let traces to continue`, should this be updated to say traces/metrics/logs?

added

**Comment by Frapschen** [comment]
> @Frapschen, are you using this in production? Even though I feel that this is indeed being used in production out there, I do not have a specific one I can use as a reference. Without one, this component should still be in alpha.

No,I am not, mark its status to  alpha.

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
@kovrus, would you like to review this one as well?

**Review by kovrus — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please resolve conflicts.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
