### PR TITLE
[receiver/mysql]: add mysql.uptime metric

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

add mysql.uptime metric

**Link to tracking Issue:**

#14138

**Testing:**

unit tests

**Documentation:**

`metadata.yaml`

### CODE REVIEW

**Review by djaglowski — COMMENTED** [review]
There appears to be a [likely addition to the semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/pull/2824) that would define uptime metrics. I think we should wait until that discussion is settled.

**Comment by makeavish** [comment]
This PR is closed already: https://github.com/open-telemetry/opentelemetry-specification/pull/2824
Can we reopen this PR and merge?
@sumo-drosiek

**Comment by sumo-drosiek** [comment]
> This PR is closed already: [open-telemetry/opentelemetry-specification#2824](https://github.com/open-telemetry/opentelemetry-specification/pull/2824) Can we reopen this PR and merge? @sumo-drosiek

It is closed, but is it resolved?

**Comment by djaglowski** [comment]
In my opinion, at this point we should not wait any longer on adding this metric. Let's make a best effort for now. If necessary, we'll migrate to a new standard prior to declaring the component stable.

The design here looks good to me, just need to rebase.

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
