### PR TITLE
Extending awskinesisexporter to export metrics

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** Extending the exporter to allow for exporting otel metrics to kinesis

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1305
This would implement a subset of this where we can export multiple types but don't have yet to adding additional encoding optional.

**Testing:** Additional unit tests have been added and updates to tests where interfaces / methods changed.

**Documentation:** the readme of the exporter has been updated to include changes and configuration options.

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
@irisgve isn't partitioned by trace id the same as being random? So both could still be partitioned by a random uuid?

**Comment by irisgve** [comment]
The issue is not with distribution though. With something as deterministic as a trace ID, the consumers are able to consume off a partition and know that they are processing the same trace.

**Comment by Excaleo** [comment]
Just a heads up, previously this PR was rejected as there were many caveats in the old kinesis producer which weren't implemented or replicated 1 to 1 in #1310

**Comment by MovieStoreGuy** [comment]
Aaa, sorry I wasn't aware of that. Let me break it down like that and we can hopefully contribute back to Otel :)

**Pull request closed without merging**
