### PR TITLE
[exporter/azuremonitor] Export log record attributes to Azure Monitor

### LINKED ISSUE #16557: azuremonitorexporter Logs missing CustomDementions
### Component(s)

exporter/azuremonitor

## Description
When mapping Logs to App Insights traces, it is not mapping Attributes to CustomDementions like it does for spans. This loses data when using formatted logging.

## Steps to Reproduce
Log data using formatted logs.
```csharp
logger.LogInformation("Info {data}", 123);
```

## Expected Result
Attributes (log args) display as CustomDimensions.

## Actual Result
CustomDimensions is empty.
image

### Collector version

0.66.0

## Environment
OS: Windows 10

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  # batch:

exporters:
  logging:
    verbosity: detailed
  azuremonitor:
    instrumentation_key: 00000000-0000-0000-0000-000000000000
    spaneventsenabled: true

extensions:
  health_check:
  pprof:
  zpages:


service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, azuremonitor]
    logs:
      receivers: [otlp]
      exporters: [logging, azuremonitor]
```

### Log output

```shell
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-11-30 21:44:38.6123544 +0000 UTC
SeverityText: Information
SeverityNumber: Info(9)
Body: Str(Info {data})
Attributes:
     -> dotnet.ilogger.category: Str(getting_started.Worker)
     -> data: Int(123)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bastbu**
**Description:**

Fixes #16557

With this PR we export _all_ attributes as `customDimensions` to Application Insights.

Note: This PR deviates from the export structure that e.g. [`Azure.Monitor.OpenTelemetry.Exporter`](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter) uses, as said exporter has access to more semantic information originating directly from the [`LogRecord`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Logs/LogRecord.cs) model from `opentelemetry-dotnet`. For example, the Azure SDK exporter [exports the .NET `LogRecord.EventId`](https://github.com/Azure/azure-sdk-for-net/blob/24c17577c9c4fffe5a57af36c4734aabd206943b/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/LogsHelper.cs#L76) with a different key than [what is exported in OTLP by `opentelemetry-dotnet`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/f7f535866b3c4cfef19661c4e97b41cf3a2091df/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/LogRecordExtensions.cs#L94). Since the Azure Monitor exporter only has access to OTLP-based data, which is language-agnostic, it is not a goal of this PR to achieve parity with the Azure SDK.

**Link to tracking Issue:** #16557

**Testing:** Unit tests assert that the most common attribute types are correctly represented in `customDimensions`. Manual testing confirmed that the export works with Azure Monitor.

**Documentation:** No documentation added.

### CODE REVIEW

**Review by eedorenko — APPROVED** [review]
LGTM

**Comment by codeboten** [comment]
Pinging codeowner @pcwiese please review

**Review by pcwiese — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]

**Comment by evan-bradley** [comment]
@bastbu Can you rebase on main and see if that fixes the CI failures?

**Comment by bastbu** [comment]
> @bastbu Can you rebase on main and see if that fixes the CI failures?

Sure! Merged `main` with the latest changes, let's see if that resolves the issues.

**Review by Aneurysm9 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
