### PR TITLE
Update core dependency

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Could you please upgrade it to the latest core master?

**Comment by bogdandrutu** [comment]
working on this now :)

**Comment by bogdandrutu** [comment]
Looks to be a consistent downgrade in carbon performance. Not sure I understand why

**Comment by bogdandrutu** [comment]
The only culprit that I can think of is the https://github.com/open-telemetry/opentelemetry-collector/pull/1336, Will try to revert that to 1 worker to confirm

**Comment by bogdandrutu** [comment]
I was right, loadtest passed.

**Pull request merged**
