### PR TITLE
[exporter/datasetexporter]: Release unused resources after some time

### LINKED ISSUE #31292: [exporter/datasetexporter]: Unused resources are not released
### Component(s)

exporter/dataset

## Description

If you are using `datasetexporter` for longer time period, it's memory consumption is only increasing. It should be more stable.

## Steps to Reproduce

Run otel demo for some time period.

## Expected Result

Memory usage should remain stable.

## Actual Result

Memory usage is increasing.

### Collector version

v0.94.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by martin-majlis-s1**
**Description:** Release unused resources after some time

This PR is:
* upgrading the used library from v0.17.0 to v0.18.0
* introducing new configuration option - `buffer.purge_older_than`

**Link to tracking Issue:** #31292

**Testing:** 

Issue has been in the underlying library - https://github.com/scalyr/dataset-go/pull/75 - where I have fixed the issue.

Screenshot 2024-02-16 at 12 01 40

**Documentation:** I have added documentation to the newly added configuration option - `buffer.purge_older_than`.

Fixes #31292

### CODE REVIEW

**Comment by martin-majlis-s1** [comment]
When I run it locally:
```
make otelcontribcol
cd ./cmd/otelcontribcol && GO111MODULE=on CGO_ENABLED=0 go build -trimpath -o ../../bin/otelcontribcol_darwin_arm64 \
                -tags "" .
../../exporter/datasetexporter/datasetexporter.go:15:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/api/add_events (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
../../exporter/datasetexporter/config.go:11:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/buffer (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
../../exporter/datasetexporter/config.go:12:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/buffer_config (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
../../exporter/datasetexporter/datasetexporter.go:16:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/client (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
../../exporter/datasetexporter/config.go:13:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/config (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
../../exporter/datasetexporter/datasetexporter.go:17:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/meter_config (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
../../exporter/datasetexporter/config.go:14:2: missing go.sum entry for module providing package github.com/scalyr/dataset-go/pkg/server_host_config (imported by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter); to add:
        go get github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datasetexporter@v0.94.0
make: *** [otelcontribcol] Error 1
```

It fails as well. :/

**Comment by martin-majlis-s1** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7931518095/job/21655935440?pr=31293#step:8:77 - it succeeds, but there is some error:

```
=== NAME  TestRemoteWrite/otelcollector/Counter
    counter.go:35: 
        	Error Trace:	counter.go:35
        	            				main_test.go:106
        	            				main_test.go:70
        	Error:      	Should be true
        	Test:       	TestRemoteWrite/otelcollector/Counter
        	Messages:   	found zero samples for {__name__="counter"}
```

**Review by tomaz-s1 — APPROVED** [review]
I already reviewed changes to dataset-go and in our fork (https://github.com/scalyr/dataset-go/pull/75) so I'm approving it here without any additional comments.

Thanks for fixing this.

**Comment by martin-majlis-s1** [comment]
@jpkrohling : Do you think, that it would be possible to include this PR to the upcoming release on 19th?

**Review by andrzej-stencel — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
