### PR TITLE
[chore] [exporter/azuremonitor] Incorporate SDK Version Tagging in Azure Monitor Exporter

### PR DESCRIPTION
**Pull request by rajkumar-rangaraj**
**Description:** <Describe what has changed.>

This pull request enhances the Azure Monitor Exporter by tagging telemetry data with the OpenTelemetry Collector's internal SDK version. This additional metadata will facilitate improved monitoring, troubleshooting, and analysis of data sourced from different versions of the collector.

**Changes:**
- Added functionality in `azuremonitorexporter` to append the SDK version to each telemetry envelope.
- Implemented `getCollectorVersion` to dynamically fetch the current version of the OpenTelemetry Collector.

**Sample SDK Version String:**
- The SDK version string is formatted as follows: `otelc-<version>-<os>-<arch>`
- Example: `otelc-v0.88.1-lin-amd64`

**Note:**
- Since this change pertains to internal diagnostic data enrichment and does not modify any external behavior or configuration interfaces, it does not necessitate a changelog entry.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>
- Adjusted existing unit tests to ensure the SDK version string is correctly included in the telemetry envelopes.

```json
{
	"ver": 1,
	"name": "Microsoft.ApplicationInsights.RemoteDependency",
	"time": "2023-11-06T15:21:12.9807976-08:00",
	"sampleRate": 100,
	"seq": "",
	"iKey": "Ikey",
	"tags": {
		"ai.cloud.role": "otlp-test",
		"ai.cloud.roleInstance": "2c4a6d1b-f7cb-4579-8d05-65b83b4acf7e",
		*"ai.internal.sdkVersion": "otelc-v0.88.1-lin-amd64",*
		"ai.operation.id": "0e3a010cb64d919aa8f214bf0a166334",
		"ai.operation.parentId": ""
	},
	"data": {
	}
}
```

### CODE REVIEW

**Review by songy23 — APPROVED** [review]
LGMT, pinging code owner @pcwiese for review.

**Review by pcwiese — APPROVED** [review]

**Comment by rajkumar-rangaraj** [comment]
@songy23 Got approval from code owner. Could you please help merge this PR?

**Comment by songy23** [comment]
👋 Marked as ready to merge. A maintainer will help merge this PR (I don't have permission)

**Comment by rajkumar-rangaraj** [comment]
@open-telemetry/collector-contrib-approvers Could you please help merge this PR, got an approval from the code owner.

**Pull request merged**
