### PR TITLE
[chore] fix exhaustive lint for attribute processor

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** 
related #23266

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
@fatsheep9146, there is one more switch with missing cases

**Review by codeboten — COMMENTED** [review]
```
Error: k8sattributesprocessor/processor.go:214:2: missing cases in switch of type pcommon.ValueType: pcommon.ValueTypeEmpty, pcommon.ValueTypeDouble, pcommon.ValueTypeBool, pcommon.ValueTypeMap, pcommon.ValueTypeSlice, pcommon.ValueTypeBytes (exhaustive)
level=info msg="File cache stats: 25 entries of total size 231.9KiB"
level=info msg="Memory: 1074 samples, avg is 254.8MB, max is 977.7MB"
level=info msg="Execution took 1m57.741780707s"
	switch val.Type() {
	^
Error: k8sattributesprocessor/internal/kube/client.go:757:3: missing cases in switch of type selection.Operator: selection.DoesNotExist, selection.DoubleEquals, selection.In, selection.NotIn, selection.Exists, selection.GreaterThan, selection.LessThan (exhaustive)
		switch f.Op {
		^
make[2]: *** [../../Makefile.Common:167: lint] Error 1
```

**Comment by fatsheep9146** [comment]
> ```
> Error: k8sattributesprocessor/processor.go:214:2: missing cases in switch of type pcommon.ValueType: pcommon.ValueTypeEmpty, pcommon.ValueTypeDouble, pcommon.ValueTypeBool, pcommon.ValueTypeMap, pcommon.ValueTypeSlice, pcommon.ValueTypeBytes (exhaustive)
> level=info msg="File cache stats: 25 entries of total size 231.9KiB"
> level=info msg="Memory: 1074 samples, avg is 254.8MB, max is 977.7MB"
> level=info msg="Execution took 1m57.741780707s"
> 	switch val.Type() {
> 	^
> Error: k8sattributesprocessor/internal/kube/client.go:757:3: missing cases in switch of type selection.Operator: selection.DoesNotExist, selection.DoubleEquals, selection.In, selection.NotIn, selection.Exists, selection.GreaterThan, selection.LessThan (exhaustive)
> 		switch f.Op {
> 		^
> make[2]: *** [../../Makefile.Common:167: lint] Error 1
> ```

Solved @codeboten please help review again

**Review by djaglowski — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
👍🏻

**Pull request merged**
