### PR TITLE
[Lokiexporter] Implementation ( PR 2/3 )

### PR DESCRIPTION
**Pull request by gramidt**
**Description:** 
The implementation of the Loki exporter.

**Link to tracking Issue:**
#1894

**Testing:**
Unit Tests

**Documentation:**
Godoc and README

### CODE REVIEW

**Comment by pmm-sumo** [comment]
I think something might have gone off with auto-assigning the reviewers for this PR. Also, [the community asks for this exporter](https://gitter.im/open-telemetry/opentelemetry-service?at=6013e06da0246860dc19e8a3). Perhaps it should be reopened @bogdandrutu @tigrannajaryan ?

**Comment by gramidt** [comment]
@pmm-sumo - Yeah, I plan on re-opening this PR very soon. I ended up having to refocus on other tasks the past two weeks, but will come back to this either this coming weekend or next week.

**Comment by tigrannajaryan** [comment]
Feel free to reopen. Not sure why it was not assigned to anyone. Was it a draft PR maybe?

**Comment by gramidt** [comment]
@tigrannajaryan - Yes, this was a draft PR that was still a WIP.

**Comment by gramidt** [comment]
@pmm-sumo - I also just responded in the Gitter channel letting Ferenc know I'll be finishing it in the near future. Thank you so much for bringing this to my attention!

**Comment by gramidt** [comment]
@tigrannajaryan - I'm having trouble re-opening this PR. Any chance you are able to re-open it with your permissions?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan - I'm having trouble re-opening this PR. Any chance you are able to re-open it with your permissions?

@gramidt I can't either (not sure why). Please create a new PR.

**Comment by gramidt** [comment]
Thank you for trying, @tigrannajaryan! I will create a new PR.

**Pull request closed without merging**
