### PR TITLE
[chore][receiver/sqlserver] Add direct connection config options

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

This adds config options for direct connection to a SQL server instance. For the sake of PR size, this adds no functionality, it's simply config options and validation.

**Link to tracking Issue:** <Issue number if applicable>
This was originally part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31915, but I'm breaking this out to make the original PR a more manageable size.

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30297

**Testing:** <Describe what testing was performed and which tests were added.>
Existing tests and added tests are all passing.

**Documentation:** <Describe the documentation added.>
No documentation on purpose. The added config options currently have no impact on functionality, so users shouldn't be aware of this, and shouldn't try to use them yet.

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]

**Comment by TigerC10** [comment]
Is Windows Auth supported?

**Comment by crobert-1** [comment]
> Is Windows Auth supported?

You're wondering if these configuration options are available on Windows? If so, yes they are.

**Comment by TigerC10** [comment]
> > Is Windows Auth supported?
> 
> You're wondering if these configuration options are available on Windows? If so, yes they are.

Not quite, I'm wondering if we can use windows authentication as opposed to username/password hardcoded in the config.  We run the opentelemetry collector as a windows service, and as such there is a service account associated with the opentelemetry collector.  We can grant the service account access to the database, and if Windows Authentication is supported then the collector could make a query without needing a username/password combo.

**Comment by crobert-1** [comment]
I don't believe that's supported currently, but you're welcome to open an issue to request it 👍

**Comment by TigerC10** [comment]
> I don't believe that's supported currently, but you're welcome to open an issue to request it 👍

😃  #32986

**Pull request merged**
