### PR TITLE
Removed myself as code owner for bearertokenauth and added myself as emeritus 

### PR DESCRIPTION
**Pull request by pavankrish123**
Removed myself as code owner for bearertokenauth and added myself as emeritus  cc: @jpkrohling @frzifus @atoulme atoulme

### CODE REVIEW

**Comment by atoulme** [comment]
sorry, can you also run `make update-codeowners` from the root of the checkout to regenerate the CODEOWNERS file please? Or just remove yourself from the file.

**Comment by pavankrish123** [comment]
Hi @atoulme  - i am getting an issue while running the make command 

```
$ make update-codeowners
cd cmd/githubgen && go install .
githubgen
2023/10/26 14:06:13 codeowners are not members: BinaryFissionGames, Frapschen, JonathanWamsley, MovieStoreGuy, Mrod1598, StefanKurek, VihasMakwana, adrielp, ag-ramachandran, albertteoh, alexvanboxel, altuner, antonblock, armstrmi, atingchen, atoulme, avadhut123pisal, bertysentry, bryan-aguilar, chrroberts-pure, codeboten, cparkins, cpheps, damemi, dashpole, dehaansa, dgoscn, erichsueh3, evan-bradley, fatsheep9146, fchikwekwe, gjanco, hickeyma, hughesjj, jacobmarble, jamesmoessis, jmacd, jsuereth, kentquirk, khyatigandhi6, kongluoxing, liustanley, mapno, mar4uk, martin-majlis-s1, matej-g, mcardy, mrsillydog, nslaughter, pavankrish123, pcwiese, pjanotti, portertech, povilasv, psx95, pxaws, qiansheng91, rapphil, rmfitzpatrick, rnishtala-sumo, rogercoll, samiura, schmikei, shabicheng, shalper2, srprash, tamir-michaeli, tomaz-s1, varunraiko, wangzlei, yotamloe, zdaratom
make: *** [gengithub] Error 1

```

**Comment by atoulme** [comment]
Yes, you need a PAT token as an env var GITHUB_TOKEN. Manual removal is ok.

**Review by frzifus — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Thanks @pavankrish123!

**Pull request merged**
