### PR TITLE
Add kentquirk to transformprocessor and TQL.

### PR DESCRIPTION
**Pull request by kentquirk**
**Description:** 

Adding @kentquirk per the conversation in today's Collector SIG.

### CODE REVIEW

**Comment by kentquirk** [comment]
@TylerHelmuth requested help on these components.

**Review by codeboten — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@Aneurysm9 would you like to be replaced by @kentquirk ?

**Comment by TylerHelmuth** [comment]
@kentquirk I don't think we require it, but I recommend you look into [being an official community member](https://github.com/open-telemetry/community/blob/main/community-membership.md#member) as part of working on the transform processor and telemetryquerylanguage.

**Comment by kentquirk** [comment]
Thanks for the link, @TylerHelmuth. I'm on it. Are you willing to be one of my sponsors?

**Pull request merged**
