### PR TITLE
[chore][exporter/sumologic]: add `deduplicateErrors` and `decomposeHistograms` functions

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

Adds files from Sumo Logic Distribution for OpenTelemetry which are new in order to simplify review and make simpler to move the whole component.

This PR is made to simplify #32315

**Link to tracking Issue:**

#31479

**Testing:**

Unit Tests, also this code is use by our customers and internally. It is not used by now by the component, but will be when migration will be finished

**Documentation:** N/A

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
@astencel-sumo could you add label to skip changelog please 🙏 ?

**Comment by sumo-drosiek** [comment]
@swiatekm-sumo, @astencel-sumo Please review

**Review by swiatekm — APPROVED** [review]

**Review by andrzej-stencel — CHANGES_REQUESTED** [review]
If I understand correctly, this pull request adds code that is not used. I don't think this is the right way to split a big pull request into smaller chunks.

A pull request should only add/modify code that is used. Code that is not used is effectively dead code and should not be added unless/until it's actually used.

**Comment by sumo-drosiek** [comment]
I disagree. There is a lot of dependencies in the code and this is the simplest way to move the code in small chunks. If I would have to use it, I would have to modify half of the code in addition to those files, which already takes over 400 lines.

As all files which do not modify old code are added in this PR, I would like to split next changes per signal, so they will be consistent and they will be marked as breaking changes.

**Comment by astencel-sumo** [comment]
There was a voice from another maintainer saying that this is OK because there's the draft PR that shows the full picture, which makes sense. I'm unblocking this, sorry if I was too zealous about it.

**Review by andrzej-stencel — APPROVED** [review]
To summarize, this PR introduces two new functions that can be used by the component:

- deduplicateErrors
- decomposeHistograms

I've reviewed this code like I would a library that delivers those functions, and the functions are :ok_hand: .

**Pull request merged**
