### PR TITLE
[chore][receiver/cloudfoundry] Remove @pellared from CODEOWNERS

### PR DESCRIPTION
**Pull request by pellared**
The truth is that I am not currently a code owner of this component.

### CODE REVIEW

**Comment by andrzej-stencel** [comment]
Sorry for the trouble, but the CODEOWNERS file in this repo is autogenerated from the components' `metadata.yaml` files.

You need to update the Cloud Foundry receiver's [metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a4ab41a2de98d3c36eb881117345d2db7644dd48/receiver/cloudfoundryreceiver/metadata.yaml) file too (you can move yourself to emeritus code owners if you want).

**Comment by pellared** [comment]
> Sorry for the trouble, but the CODEOWNERS file in this repo is autogenerated from the components' metadata.yaml files.

You should make step that executes `git diff --exit-code` to make sure that generated code differs.

**Comment by pellared** [comment]
> Sorry for the trouble, but the CODEOWNERS file in this repo is autogenerated from the components' metadata.yaml files.

@andrzej-stencel, this is good 👍 I think I updated the PR correctly. I make the PR as "Ready for review" after the GH workflows pass.

**Review by songy23 — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]
Looks good, thanks for your help here @pellared!

**Pull request merged**
