### PR TITLE
[prometheusremotewriteexporter] dropping the condition to replace _ with key_ as __ label is reserved and _ is not

### PR DESCRIPTION
**Pull request by saikrishna397**
__ is a reserved label and _ is not. Being able to use or not use a certain kind of naming convention would be a decision at the exporter level as the nature of the storage dictates what can and can’t be used. it would be nice if we could ideally relax this check for processors in general and backends that don't mandate it like prometheus.

Description: dropped the check to handle labels that start with '_'

Testing: All the tests worked fine

### CODE REVIEW

**Review by Aneurysm9 — CHANGES_REQUESTED** [review]
This will change the behavior of this exporter and possibly break user dashboards.  I think this needs a strong use case to justify it.  I also still don't know that we understand why it was originally deemed necessary and thus I'm reluctant to remove it without clear demonstration that it is not needed and that removing it will have no harmful effects.

**Comment by bogdandrutu** [comment]
@Aneurysm9 would recommend to make sure the CLA is signed before reviewing the code, since we are not allowed to merge the PR anyway.

**Comment by saikrishna397** [comment]
will create a new one

**Comment by Aneurysm9** [comment]
> @Aneurysm9 would recommend to make sure the CLA is signed before reviewing the code, since we are not allowed to merge the PR anyway.

I had discussed this with the author on slack and the PR is two lines.  Wasn't much to review.

**Pull request closed without merging**
