### PR TITLE
[processor/transform] Finish reflection scenarios

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:**
This PR completes the case statements in `NewFunctionCall` to handle all allowed function parameter scenarios based on the existing grammar capabilities.  It also fixes each signal's ParsePath function, which did not have proper error checks, causing `NewFunctionCall` to report incorrect errors.

After this PR, new functions can be added with a guarantee that the parameter they need can be passed successfully.  I have explicitly omitted the "slice of getter' scenario, as it felt like a pattern we shouldn't allow without a valid function proposing it.  

I also updated the unit tests in `common/functions_test.go`, with the intent of specifically testing `NewFunctionCall` itself, not any of the functions themselves.  My goal is to remove any function-specific tests to their own test files in a later PR as part of the function refactoring.  Going forward, `common/functions_test.go` should only need to be updated when new parameter types are added as the grammar expands. 

**Link to tracking Issue:**
Related to #10101

**Testing:**
Unit tests

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Thanks!

**Review by dashpole — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase.

**Comment by TylerHelmuth** [comment]
@open-telemetry/collector-approvers please review

**Comment by TylerHelmuth** [comment]
With the completion of [#10255](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10255) I need to handle the new bool type in my refactor.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
