### PR TITLE
Remove @pmm-sumo as a reviewer from CODEOWNERS - add mutliple people from Sumo Logic as a replacement

### PR DESCRIPTION
**Pull request by perk-sumo**
That is a proposition from Sumo Logic for maintainers for different components that @pmm-sumo took care before.

Complementary PR to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12493

Thank you @pmm-sumo for all your help and hard work!

### CODE REVIEW

**Comment by jpkrohling** [comment]
For Sumologic-specific components, I think this looks good. For other components, I believe the remaining approvers have to give their +1s. @pmm-sumo might have been employed by Sumo Logic by the time of his contributions, but the reputation gained was his, not his employer's.

**Review by andrzej-stencel — APPROVED** [review]
I'd be happy to step in and help 💯

**Comment by TylerHelmuth** [comment]
> For Sumologic-specific components, I think this looks good. For other components, I believe the remaining approvers have to give their +1s. @pmm-sumo might have been employed by Sumo Logic by the time of his contributions, but the reputation gained was his, not his employer's.

Agree 100%.  For components where @pmm-sumo was the only named code owner, such as `fileexporter` or `zipkinexporter`, who should we fall back on?  The Contrib approvers and maintainers or only the maintainers?

This would probably be a good time to document some official Code Owner requirements.  There is some discussion about it in the [Code Owners Wanted Issues](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3870), but I don't think we have a doc for it.

**Comment by jpkrohling** [comment]
We have something similar here, altough for code owners, not approvers: https://github.com/open-telemetry/opentelemetry-collector#unmaintained

**Comment by TylerHelmuth** [comment]
> We have something similar here, although for code owners, not approvers: https://github.com/open-telemetry/opentelemetry-collector#unmaintained

I don't see anything in the unmaintained section about how to become a code owner.  I'm picturing a doc the lays out our requirements for code ownership; hopefully something explicit.  I can open a PR for that today probably.

**Review by kasia-kujawa — APPROVED** [review]

**Review by swiatekm — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]
To give further context, as I was leaving Sumo I asked among my colleagues if someone would like to step-up and help with maintaining the components (especially that for some of them I was the sole codeowner and I was afraid they might become unmaintained). 

Then, there was an idea that instead of removing me from the CODEOWNERS first and then applying for volunteering in separate PRs, a proposal could be made in one step to ease the transition. If it doesn't make things easier (or clear), I will be happy to create a separate PR which will remove me from the CODEOWNERS and I believe each volunteer could create another PR with application for being owner of each component separately. Let us know what you prefer :)

**Review by pdelewski — APPROVED** [review]

**Comment by perk-sumo** [comment]
> For Sumologic-specific components, I think this looks good. For other components, I believe the remaining approvers have to give their +1s. @pmm-sumo might have been employed by Sumo Logic by the time of his contributions, but the reputation gained was his, not his employer's.

100% agree. Also to what @pmm-sumo said in other comment - main reason to create this PR was to show Sumo commitment to help with development. If doing it any other way would be more beneficial to the community - please let us know :)

**Review by sumo-drosiek — APPROVED** [review]

**Review by mat-rumian — APPROVED** [review]

**Comment by jpkrohling** [comment]
It will certainly be easier to manage multiple PRs changing groups of similar components than one PR changing them all at once. The Sumologic components can be one PR, and you can group components by new code owners in separate PRs.

**Comment by TylerHelmuth** [comment]
Also, please review the newly minted [Code Owner requirements](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner). Thanks @astencel-sumo for providing input during the last SIG meeting.

**Comment by pmm-sumo** [comment]
Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12663 following the suggestion

**Comment by perk-sumo** [comment]
All clear, let me close this PR then. Thank you for review and suggestions!

**Pull request closed without merging**
