### PR TITLE
[chore] upgrade to testcontainers-go 0.20.1

### PR DESCRIPTION
**Pull request by atoulme**

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
looks like you're missing `make gotidy` and it should be good?

**Comment by atoulme** [comment]
The integration tests gave me a hard time: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4942402931/jobs/8835948706?pr=21783

I'll check make tidy right away, maybe that didn't help.

**Comment by MovieStoreGuy** [comment]
I am happy to poke the CI if it gets stuck :)

**Comment by atoulme** [comment]
I reproduce the error locally but yet to determine what is going on.

**Review by dmitryax — APPROVED** [review]
Thanks, @atoulme!

**Comment by atoulme** [comment]
This should do it, this new version of testcontainers seems to return container information including the testcontainers container itself. :shrug:

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
I can't exactly pinpoint the change in testcontainers that caused this from the changelog, but @atoulme description seems to check out so I am merging

**Pull request merged**
