### PR TITLE
Header Setter Extension: add default value to configuration

### PR DESCRIPTION
**Pull request by f7o**
**Description:** <Describe what has changed.>
* default value config
* set default value in context source if metadata empty

**Link to tracking Issue: #34412

**Testing:** tbd

**Documentation:** see README.md

### CODE REVIEW

**Comment by jpkrohling** [comment]
@f7o , is this ready for review?

**Comment by f7o** [comment]
@jpkrohling implementing tests is still pending, will do soon.

**Comment by f7o** [comment]
@jpkrohling ready for review

**Review by jpkrohling — APPROVED** [review]

**Comment by f7o** [comment]
@Frapschen @jpkrohling who will/can merge this? 

I am not sure on all these checks, some seem broken, not able to pull changes, ...

**Comment by jpkrohling** [comment]
I'll merge once the CI is green

**Comment by f7o** [comment]
@jpkrohling added a changelog

CI doesn't seem to work!? workflows are pending or only running certain times?

**Pull request merged**
