### PR TITLE
[receiver/redis] Add username parameter for connecting to redis

### PR DESCRIPTION
**Pull request by NicoL49**
**Description:** Adding a feature - Adding username for redis receiver for connecting to redis over ACL

**Link to tracking Issue:** n/a

**Testing:** Running go test is ok. Generating my custom OpenTelemetry Collector binary with redis receiver and otlp exporter (using ocb). This custom Opentelemetry Collector collecting redis data by connecting with a username and password work fine. I test to collect data using password only, it works too. 

**Documentation:** Mardown file has been updated

### CODE REVIEW

**Review by frzifus — COMMENTED** [review]
thx @NicoL49, could you please add a changelog?

You can generate an entry using `make chlog-new`.

**Review by dmitryax — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]

**Comment by crobert-1** [comment]
CI failing related to this PR
```
redisreceiver/config.go:25: File is not `gci`-ed with --skip-generated -s standard -s default -s prefix(github.com/open-telemetry/opentelemetry-collector-contrib) (gci)
level=info msg="File cache stats: 23 entries of total size 149.0KiB"
level=info msg="Memory: 44 samples, avg is 158.5MB, max is 302.8MB"
level=info msg="Execution took 4.25894574s"
	Username string `mapstructure:"username"`	
make[2]: *** [../../Makefile.Common:167: lint] Error 1
```
You might need to switch the order of the `Password` and `Username` lines to make it alphabetical? You can also run `make gofmt` and `make golint` locally to possibly get more information.

**Comment by dmitryax** [comment]
@NicoL49 please rebase

**Comment by NicoL49** [comment]
After rebase, I have test with the new type of password (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24060)

**Comment by wwtepp** [comment]
this is a critical feature for us. Please reach out to me, if I can be of any help

**Pull request merged**
