### PR TITLE
Use OTel-Arrow v0.26.0

### PR DESCRIPTION
**Pull request by jmacd**
**Description:** There are no real changes here, except keeping up with collector dependencies. otel-arrow/v0.26.0 removes all the code that now resides in this repo's `internal/otelarrow` module.

### CODE REVIEW

**Review by moh-osman3 — APPROVED** [review]

**Review by mwear — APPROVED** [review]

**Review by songy23 — COMMENTED** [review]
Needs `make gotidy`

**Comment by jmacd** [comment]
> Needs make gotidy

Yes, I noticed. Is there one make rule I could always run that would cover every possible pre-commit step? I'm aware of `generate`, `gotidy`, `genotelarrowcol`, `crosslink`, `gci`, `fmt`. It's really time consuming to get all of these details correct, especially when there are cross-module updates requiring a top-level make command (which is ... slow!).

**Comment by jmacd** [comment]
^^^ this PR shows what a circus we're talking about. I ran `make gotidy`. I still have to run `genotelcontribcol`. This is a very difficult process.

**Comment by jmacd** [comment]
Reviewers and maintainers -- I appreciate the help getting this PR into a green state, but if this concerns you as well, please note that I have three other green PRs with approvals that I would appreciate being merged, that will be an even greater help. Thank you!

**Comment by songy23** [comment]
> Is there one make rule I could always run that would cover every possible pre-commit step? 

I think `make checks` is the one you're looking for - it is pretty slow though, I myself don't make much use of it

**Review by songy23 — APPROVED** [review]

**Comment by jmacd** [comment]
> make checks

Thanks. It might save time, I'll try!

**Review by codeboten — APPROVED** [review]

**Pull request merged**
