### PR TITLE
[chore] Delete otelcontribcol code

### LINKED ISSUE #30884: Remove tests from cmd/otelcontribcol
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

Those tests take a long time to compile and slow down execution of CI. They are replaced by generated tests.

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Deletes the code under `cmd/otelcontribcol`, move to build it under `cmd/otelcontribcol/_build` without checking it in.

**Link to tracking Issue:**
Fixes #30884

### CODE REVIEW

**Comment by dmitryax** [comment]
Did we move all the lifecycle tests to the components?

**Comment by atoulme** [comment]
> Did we move all the lifecycle tests to the components?

No, we still miss some, here is the list:
```
$> find . -mindepth 2 -maxdepth 2 -type d '!' -exec test -e "{}/generated_component_test.go" ';' -print | grep -E "(exporter|receiver|extension|connector|processor)"
./extension/asapauthextension
./extension/solarwindsapmsettingsextension
./extension/httpforwarder
./extension/awsproxy
./extension/encoding
./extension/storage
./extension/basicauthextension
./extension/jaegerremotesampling
./processor/deltatocumulativeprocessor
./receiver/windowseventlogreceiver
./receiver/windowsperfcountersreceiver
./receiver/elasticsearchreceiver
./receiver/awsxrayreceiver
./receiver/namedpipereceiver
./receiver/sqlserverreceiver
./receiver/filelogreceiver
./receiver/filereceiver
./receiver/journaldreceiver
./receiver/kubeletstatsreceiver
./receiver/awsecscontainermetricsreceiver
./receiver/datadogreceiver
./receiver/k8sobjectsreceiver
./receiver/osqueryreceiver
./receiver/jmxreceiver
./receiver/mongodbatlasreceiver
./receiver/activedirectorydsreceiver
./receiver/chronyreceiver
./receiver/dockerstatsreceiver
./receiver/receivercreator
./receiver/gitproviderreceiver
./receiver/iisreceiver
./receiver/k8sclusterreceiver
./connector/failoverconnector
./connector/routingconnector
./connector/datadogconnector
./exporter/loadbalancingexporter
./exporter/fileexporter
./exporter/pulsarexporter
./exporter/awskinesisexporter
./exporter/influxdbexporter
./exporter/instanaexporter
./exporter/elasticsearchexporter
./exporter/googlemanagedprometheusexporter
./exporter/awsemfexporter
./exporter/kafkaexporter
./exporter/skywalkingexporter
./exporter/coralogixexporter
./exporter/googlecloudpubsubexporter
./exporter/prometheusexporter
./exporter/f5cloudexporter
./exporter/prometheusremotewriteexporter
./exporter/lokiexporter
./exporter/zipkinexporter
./exporter/carbonexporter
./exporter/tencentcloudlogserviceexporter
./exporter/sumologicexporter
./exporter/syslogexporter
./exporter/azuredataexplorerexporter
./exporter/googlecloudexporter
./exporter/mezmoexporter
./exporter/otelarrowexporter
./exporter/cassandraexporter
./exporter/logicmonitorexporter
./exporter/opencensusexporter
```

**Review by codeboten — COMMENTED** [review]
Should this be blocked on the lifecycle changes?

**Comment by atoulme** [comment]
Yes and no ; it can be debated in a SIG meeting. Right now the current tests bail when the creation of the component fails, and the new tests are less forgiving. So our test coverage is actually probably already better with the new generated tests. That said, we don't have them done everywhere.

**Pull request closed without merging**
