### PR TITLE
[chore][exporter/elasticsearch] fix flaky assertion in TestExporterMetrics

### PR DESCRIPTION
**Pull request by mauri870**
#### Description

Sometimes the order of fields in the json strings change which causes failures in the test.

### CODE REVIEW

**Review by carsonip — COMMENTED** [review]
There are many other usages of `newESTestServer` and they also don't have `defer server.Close()`. Do they need to be fixed too?

**Comment by mauri870** [comment]
> There are many other usages of `newESTestServer` and they also don't have `defer server.Close()`. Do they need to be fixed too?

Interesting, I cannot reproduce this anymore. I think this test is failing in my runs because of something else. It is very flaky and only fails once every ten or so tries. Looking into it.

**Comment by mauri870** [comment]
Got it. This test is failing because of the order of fields when comparing a json string. I will convert this PR into a fix for this instead.

<details>
<summary></summary>

```
--- FAIL: TestExporterMetrics (0.14s)
    --- FAIL: TestExporterMetrics/otel_mode__doc_count_hint (0.01s)
        utils_test.go:51:
                Error Trace:    /home/mauri870/git/opentelemetry-collector-contrib/exporter/elasticsearchexporter/utils_test.go:51
                                                        /home/mauri870/git/opentelemetry-collector-contrib/exporter/elasticsearchexporter/exporter_test.go:1056
                Error:          Not equal:
                                expected: []elasticsearchexporter.itemRequest{elasticsearchexporter.itemRequest{Action:json.RawMessage{0x7b, 0x22, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x7b, 0x22, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x3a, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x22, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x3a, 0x7b, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x75, 0x6d, 0x22, 0x3a, 0x22, 0x67, 0x61, 0x75, 0x67, 0x65, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x2c, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x3a, 0x22, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x7d, 0x7d, 0x7d}, Document:json.RawMessage{0x7b, 0x22, 0x40, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3a, 0x22, 0x31, 0x39, 0x37, 0x30, 0x2d, 0x30, 0x31, 0x2d, 0x30, 0x31, 0x54, 0x30, 0x30, 0x3a, 0x30, 0x30, 0x3a, 0x30, 0x30, 0x2e, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x5a, 0x22, 0x2c, 0x22, 0x5f, 0x64, 0x6f, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x31, 0x30, 0x2c, 0x22, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x3a, 0x7b, 0x22, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x22, 0x3a, 0x22, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0x2c, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x7d, 0x2c, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x3a, 0x7b, 0x22, 0x73, 0x75, 0x6d, 0x22, 0x3a, 0x30, 0x2c, 0x22, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x3a, 0x7b, 0x22, 0x73, 0x75, 0x6d, 0x22, 0x3a, 0x31, 0x2e, 0x30, 0x2c, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x31, 0x30, 0x7d, 0x7d, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x3a, 0x7b, 0x22, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x30, 0x7d, 0x2c, 0x22, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x3a, 0x7b, 0x22, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x30, 0x7d, 0x7d}}}
                                actual  : []elasticsearchexporter.itemRequest{elasticsearchexporter.itemRequest{Action:json.RawMessage{0x7b, 0x22, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x7b, 0x22, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x3a, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x22, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x22, 0x3a, 0x7b, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x3a, 0x22, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x2c, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x73, 0x75, 0x6d, 0x22, 0x3a, 0x22, 0x67, 0x61, 0x75, 0x67, 0x65, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x7d, 0x7d, 0x7d}, Document:json.RawMessage{0x7b, 0x22, 0x40, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3a, 0x22, 0x31, 0x39, 0x37, 0x30, 0x2d, 0x30, 0x31, 0x2d, 0x30, 0x31, 0x54, 0x30, 0x30, 0x3a, 0x30, 0x30, 0x3a, 0x30, 0x30, 0x2e, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x5a, 0x22, 0x2c, 0x22, 0x5f, 0x64, 0x6f, 0x63, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x31, 0x30, 0x2c, 0x22, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x3a, 0x7b, 0x22, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x22, 0x3a, 0x22, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0x2c, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x7d, 0x2c, 0x22, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x3a, 0x7b, 0x22, 0x73, 0x75, 0x6d, 0x22, 0x3a, 0x30, 0x2c, 0x22, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x3a, 0x7b, 0x22, 0x73, 0x75, 0x6d, 0x22, 0x3a, 0x31, 0x2e, 0x30, 0x2c, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x31, 0x30, 0x7d, 0x7d, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x3a, 0x7b, 0x22, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x30, 0x7d, 0x2c, 0x22, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x22, 0x3a, 0x7b, 0x22, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x30, 0x7d, 0x7d}}}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -8,5 +8,5 @@
                                    00000040  6c 61 74 65 73 22 3a 7b  22 6d 65 74 72 69 63 73  |lates":{"metrics|
                                -   00000050  2e 73 75 6d 22 3a 22 67  61 75 67 65 5f 6c 6f 6e  |.sum":"gauge_lon|
                                -   00000060  67 22 2c 22 6d 65 74 72  69 63 73 2e 73 75 6d 6d  |g","metrics.summ|
                                -   00000070  61 72 79 22 3a 22 73 75  6d 6d 61 72 79 22 7d 7d  |ary":"summary"}}|
                                +   00000050  2e 73 75 6d 6d 61 72 79  22 3a 22 73 75 6d 6d 61  |.summary":"summa|
                                +   00000060  72 79 22 2c 22 6d 65 74  72 69 63 73 2e 73 75 6d  |ry","metrics.sum|
                                +   00000070  22 3a 22 67 61 75 67 65  5f 6c 6f 6e 67 22 7d 7d  |":"gauge_long"}}|
                                    00000080  7d                                                |}|
                Test:           TestExporterMetrics/otel_mode__doc_count_hint
FAIL
exit status 1
FAIL    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter        14.389s
```

</details>

**Review by carsonip — APPROVED** [review]
thanks, change lgtm. I wanted to make this change for a long time. Do you mind removing the "For https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35638" in PR description? It shouldn't be related to the leak.

**Comment by mauri870** [comment]
> thanks, change lgtm. I wanted to make this change for a long time. Do you mind removing the "For #35638" in PR description? It shouldn't be related to the leak.

Done, thanks!

**Review by carsonip — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]

**Pull request merged**
