### PR TITLE
[chore] Fix some of the load tests

### PR DESCRIPTION
**Pull request by mowies**
**Description:** <Describe what has changed.>

This PR tries to fix some of the load tests.

**Link to tracking Issue:** no issue

**Testing:** load tests are particularly hard to test since they only run on main branch and also on self hosted runners. which makes them impossible to fully reproduce on a fork... I tested them locally and got better results than upstream.

**Documentation:** NA

### CODE REVIEW

**Comment by mx-psi** [comment]
> oad tests are particularly hard to test since they only run on main branch and also on self hosted runners. which makes them impossible to fully reproduce on a fork... I tested them locally and got better results than upstream.

We could add a similar label to "Run on Windows" for load tests if that helps. Would you be up for that? (Not needed to merge this PR IMO)

**Comment by mowies** [comment]
Yes I think that could work. Although outside contributors (like myself) could still not add the label themselves, except if we also add it to the `/label` comment/command.

**Comment by mowies** [comment]
And yes, I could add that feature :D

**Comment by mx-psi** [comment]
> Yes I think that could work. Although outside contributors (like myself) could still not add the label themselves, except if we also add it to the `/label` comment/command.

That's fair, I still see it as a net improvement though

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
