### PR TITLE
[exporter/sapm] Deprecate SAPM exporter

### LINKED ISSUE #32124: [exporter/sapm] Deprecate the SAPM exporter
### Component(s)

exporter/sapm

### Describe the issue you're reporting

Consider deprecating the sapmexporter. This exporter will be replaced by OTLP. The deprecation cycle would start a timer of at least a year before eventual removal.

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Deprecate SAPM exporter

**Link to tracking Issue:**
Fixes #32124

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
The go module should also contain a deprecation warning. See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6229c6ad1c49e9cc4b41a8aab8cb5a94a7b82ea5/exporter/dynatraceexporter/go.mod#L1

**Comment by codeboten** [comment]
Ping @atoulme please update the go.mod file

**Comment by atoulme** [comment]
I'll do it in a bit, we're not quite ready.

**Comment by codeboten** [comment]
> I'll do it in a bit, we're not quite ready.

@atoulme is it ok to move this back into draft then? would be good to avoid merging it without the notice in the go.mod

**Pull request closed without merging**
