### PR TITLE
[datadogexporter] Enable traces on Windows

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

- Change datadog-agent dependency to use a version with different go modules.
- Update the code to reflect the new version
- Enable again the traces code on Windows (effectively revert #1274)

**Link to tracking Issue:** n/a

**Testing:** The unit tests pass. Full end to end testing will be done when the missing parts are merged

**Documentation:** Removed mention to Windows support from README

---

cc @ericmustin to review

### CODE REVIEW

**Comment by mx-psi** [comment]
CI is failing because of a flaky test on an unrelated component

**Review by ericmustin — APPROVED** [review]
👍 LGTM (on behalf of datadog)

**Comment by mx-psi** [comment]
Moving back to draft while I apply the change to #1266 files

**Comment by mx-psi** [comment]
@ericmustin can you review again? Thanks!

**Review by ericmustin — APPROVED** [review]
👍

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
