### PR TITLE
Revert "[chore] dockerstats receiver lifecycle generated tests"

### PR DESCRIPTION
**Pull request by djaglowski**
This PR appears to have broken windows unit tests:

```
=== Failed
=== FAIL: . TestComponentLifecycle/metrics-lifecycle (0.00s)
    generated_component_test.go:65: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/dockerstatsreceiver/generated_component_test.go:65
        	Error:      	Received unexpected error:
        	            	could not create docker client: protocol not available
        	Test:       	TestComponentLifecycle/metrics-lifecycle

=== FAIL: . TestComponentLifecycle (0.04s)

=== FAIL: . TestComponentLifecycle/metrics-lifecycle (re-run 1) (0.00s)
    generated_component_test.go:65: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/dockerstatsreceiver/generated_component_test.go:65
        	Error:      	Received unexpected error:
        	            	could not create docker client: protocol not available
        	Test:       	TestComponentLifecycle/metrics-lifecycle

=== FAIL: . TestComponentLifecycle (re-run 1) (0.05s)

DONE 2 runs, 35 tests, 4 failures in 17.831s
make[2]: *** [../../Makefile.Common:126: test] Error 1
make[1]: *** [Makefile:165: receiver/dockerstatsreceiver] Error 2
```

Observed [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8076729221/job/22065671646#step:7:736).

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
Is the dockerstats receiver not supporting Windows then?

**Comment by atoulme** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/dockerstatsreceiver/README.md?plain=1#L22 looks like it's Linux only! In that case the fix is to restrict when tests would run. I can prepare a fix.

**Comment by atoulme** [comment]
Opening https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31489 to fix.

**Comment by djaglowski** [comment]
Replaced by #31489

**Pull request closed without merging**
