### PR TITLE
[receiver/solacereceiver]: Updated the format for generated metrics and included new Solace receiver metric attribute

### PR DESCRIPTION
**Pull request by oodigie**
**Description:** Updated the format for generated metrics. Included a `receiver_name` attribute that identifies the Solace receiver that generated the metrics.

**Link to tracking Issue:** N/A

**Testing:** Updated unit tests to accommodate passing of attributes for metrics

**Documentation:** N/A

### CODE REVIEW

**Review by mcardy — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
Seems there's still an error to resolve: `Generated code is out of date, please run "make generate" and commit the changes in this PR.`

**Comment by oodigie** [comment]
Thanks @djaglowski, I have ran `make generate` and updated the PR. Should pass now.

**Comment by oodigie** [comment]
Sorry I see some tests errors, I will fix them now.

**Comment by oodigie** [comment]
Thanks @djaglowski!

**Pull request merged**
