### PR TITLE
[extension/bearertokenauthextension] Fix for extension Always return "401 Unauthorized" via HTTP connection #24656

### PR DESCRIPTION
**Pull request by nagashan**
Fix for extension Always return "401 Unauthorized" via HTTP connection #24656

**Description:** We are always trying to get the `authorization` with the lower case from headers, But The headers from Http is received as `Authorization` capitalcase even-though we sent in lower case.

**Link to tracking Issue:** <[24656](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24656)>

**Testing:** Tested in the local
Screenshot 2023-12-17 at 5 28 26 PM
Screenshot 2023-12-17 at 5 32 11 PM
Screenshot 2023-12-17 at 5 34 12 PM

### CODE REVIEW

**Comment by atoulme** [comment]
Please run `make chlog-new` and fill the changelog entry for this issue. You can use the PR number as issue number.

**Comment by nagashan** [comment]
> Please run `make chlog-new` and fill the changelog entry for this issue. You can use the PR number as issue number.

Done

**Review by crobert-1 — APPROVED** [review]

**Comment by nagashan** [comment]
@atoulme Does this commits looks good? Any changes required?

**Review by atoulme — APPROVED** [review]
lgtm. Could use a test but not a deal breaker

**Review by frzifus — APPROVED** [review]
Thanks @nagashan, I agree with @atoulme a test would be great :)

**Pull request merged**
