### PR TITLE
[pkg/translator/jaeger] decode binary tags if its base64

### LINKED ISSUE #15350: [translator/jaeger] When translating binary tags back to Jaeger return them as binary instead of string
### Is your feature request related to a problem? Please describe.

When translating binary tags from Jaeger to OTEL they are based64 encoded and put as a Str attribute

https://github.com/alejandrodnm/opentelemetry-collector-contrib/blob/47870dedc479a9a6acc3a6128a5d3030240dadcc/pkg/translator/jaeger/jaegerproto_to_traces.go#L253-L254

When translating back to Jaeger no attempt is made to decode the value and return it as binary

https://github.com/alejandrodnm/opentelemetry-collector-contrib/blob/47870dedc479a9a6acc3a6128a5d3030240dadcc/pkg/translator/jaeger/traces_to_jaegerproto.go#L138-L140

Meaning that binary Jaeger tags are returned as the base64 string representation of the binary.

### Describe the solution you'd like

When translating a Jaeger binary tag to OTEL and back to Jaeger I expect the tag returned as binary instead of the base64 string representation

### Describe alternatives you've considered

In our project, when translating binary tags we prefix them with `data:application/octet-stream; base64,` from the "data" URL scheme RFC https://www.rfc-editor.org/rfc/rfc2397#section-2 

Ex:

For the base64 encoded string `dGVzdA==`  we store it as `data:application/octet-stream; base64,dGVzdA==`

https://github.com/timescale/promscale/blob/a6d486c41ea6bd78cf75dbddfc872c1dfe983965/pkg/jaeger/store/binary_tags.go#L61-L97

When translating back from OTEL to Jaeger if the attribute is a string and it has the prefix, then it's decoded back to binary:

https://github.com/timescale/promscale/blob/a6d486c41ea6bd78cf75dbddfc872c1dfe983965/pkg/jaeger/store/binary_tags.go#L30-L59

The inconvenience is that we have to go through all the tags to encode the binary ones before passing the Jaeger spans through the translator, and when converting back from OTEL to Jaeger we have to do another pass through the tags to look for the ones that should be decoded.

### Additional context

If you think the approach of adding the prefix is good enough, I will submit a PR with the required changes.

Thanks :)

### PR DESCRIPTION
**Pull request by frzifus**
**Description:** <Describe what has changed.>

WIP - needs discussion

**Link to tracking Issue:** <Issue number if applicable>
Closes #15350

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by frzifus** [comment]
@dmitryax could you please have a look? ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15350#issuecomment-1632734037))

**Review by codeboten — APPROVED** [review]
The change looks ok, pinging @dmitryax for a second review

**Comment by dmitryax** [comment]
Sorry, I somehow missed this thread. This can hit performance significantly for 99% of the attributes that are strings. I'd suggest using OTel bytes attributes in the first place instead. Let's continue the discussion in the issue  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15350#issuecomment-1714619355

**Review by dmitryax — CHANGES_REQUESTED** [review]
needs further discussion

**Pull request closed without merging**
