### PR TITLE
Add @ycombinator as codeowner for elasticsearchexporter

### LINKED ISSUE #26647: Support Sending raw logs via Elasticsearch exporter when format option is set
### Component(s)

_No response_

### Is your feature request related to a problem? Please describe.

The current exporter automatically converts the logs into plog format which adds attribute prefixes to all the fields that break the existing dashboards and alerts for enterprises who are using the elastic search exporter. Please see the below debug logs from the Otel collector

## Event received by otel
```
ObservedTimestamp: 2023-03-29 17:47:46.28812868 +0000 UTC
Timestamp: 2023-03-29 17:47:46.071000064 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Map({"message":"{\"host\":\"17.47.219.133\",\"user-identifier\":\"shaneIxD\",\"datetime\":\"29/Mar/2023:17:47:46\",\"method\":\"HEAD\",\"request\":\"/do-not-access/needs-work\",\"protocol\":\"HTTP/1.1\",\"status\":\"500\",\"bytes\":28854,\"referer\":\"https://for.us/user/booperbot124\"}","source_type":"demo_logs"})
Attributes:
     -> protocol: Str(HTTP/1.1)
     -> host: Str(17.47.219.133)
     -> datetime: Str(29/Mar/2023:17:47:46)
     -> method: Str(HEAD)
     -> request: Str(/do-not-access/needs-work)
     -> status: Str(500)
     -> bytes: Double(28854)
     -> referer: Str(https://for.us/user/booperbot124)
     -> user-identifier: Str(shaneIxD)
Trace ID:
Span ID:
Flags: 0
	{"kind": "exporter", "data_type": "logs", "name": "logging"}
```	

## Elastic view
 
 ```
   "_source": {
    "@timestamp": "2023-03-29T17:46:42.069999872Z",
    "Attributes.bytes": 39389,
    "Attributes.datetime": "29/Mar/2023:17:46:42",
    "Attributes.host": "48.247.3.152",
    "Attributes.method": "PATCH",
    "Attributes.protocol": "HTTP/1.1",
    "Attributes.referer": "https://some.net/controller/setup",
    "Attributes.request": "/observability/metrics/production",
    "Attributes.status": "550",
    "Attributes.user-identifier": "benefritz",
    "Body.message": "{\"host\":\"48.247.3.152\",\"user-identifier\":\"benefritz\",\"datetime\":\"29/Mar/2023:17:46:42\",\"method\":\"PATCH\",\"request\":\"/observability/metrics/production\",\"protocol\":\"HTTP/1.1\",\"status\":\"550\",\"bytes\":39389,\"referer\":\"https://some.net/controller/setup\"}",
    "Body.source_type": "demo_logs",
    "SeverityNumber": 0,
    "TraceFlags": 0
  }
  ```

### Describe the solution you'd like

According to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/model.go#L51  the elasticsearch exporter automatically converts the data into plog format before sending the event to Elastic. The only way we can handle this is to add ingest pipleine on Elastic to strip off the attribute field. 

We would like to see a RAW format option like loki and kafka exporter where we can send the raw logs to elasticsearch.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter
> The following encodings are valid only for logs.
raw: if the log record body is a byte array, it is sent as is. Otherwise, it is serialized to JSON. Resource and record attributes are discarded.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter
>The following formats are supported:
logfmt: Write logs as [logfmt](https://brandur.org/logfmt) lines.
json: Write logs as JSON objects. It is the default format if no hint is present.
raw: Write the body of the log message as string representation.

### Describe alternatives you've considered

No alternatives found except for adding ingest pipelines on the Elastic

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ycombinator**
**Description:** 

This PR proposes adding @ycombinator as a codeowner for the `elasticsearch` exporter component, being an [employee of Elastic](https://www.linkedin.com/company/elastic-co/people/?keywords=shaunak) and also meeting the codeowner [requirements](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#requirements):

1. [Be a member of the OpenTelemetry organization.](https://github.com/open-telemetry/community/blob/main/community-membership.md#member)
   * https://github.com/orgs/open-telemetry/people?query=ycombinator
2. (Code Owner Discretion) It is best to have resolved an issue related to the component, contributed directly to the component, and/or review component PRs. How much interaction with the component is required before becoming a Code Owner is up to any existing Code Owners.
   * Resolved https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26647 via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29619
   * Reviewed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31553
   * Contributed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31694 as follow up to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31553
   * Reviewed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31848

### CODE REVIEW

**Comment by ycombinator** [comment]
cc: @JaredTan95 as current codeowner of the `elasticsearch` exporter.

**Review by songy23 — APPROVED** [review]

**Review by bryan-aguilar — APPROVED** [review]

**Review by crobert-1 — COMMENTED** [review]
Adding a code owner is a bit more involved than this. You'll need to add your GitHub username to the active code owners section of the [component's metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/18ef33f417c56483527d1ac537d9b44016ceec28/exporter/elasticsearchexporter/metadata.yaml#L10). Then you can run `make update-codeowners` to make sure the component's README and the `.github/CODEOWNERS` file is updated properly.

**Comment by ycombinator** [comment]
Thanks @crobert-1.  I've made the changes to the `elasticsearchexporter`'s `metadata.yaml` file in 6f11e12c05.  However, when I then ran `GITHUB_TOKEN=github_pat_XXXXXXX make update-codeowners` (from the repo's root directory), I got the following error:

```
$  GITHUB_TOKEN=github_pat_XXXXXXX make update-codeowners
cd cmd/githubgen && go install .
githubgen
2024/04/04 10:46:06 codeowners are not members: BinaryFissionGames, Frapschen, JonathanWamsley, MovieStoreGuy, Mrod1598, RichieSams, StefanKurek, VihasMakwana, adrielp, ag-ramachandran, akats7, alexvanboxel, antonblock, armstrmi, atingchen, atoulme, avadhut123pisal, bertysentry, braydonk, bryan-aguilar, chrroberts-pure, codeboten, cparkins, cpheps, damemi, dashpole, dehaansa, dgoscn, eedorenko, erichsueh3, evan-bradley, fatsheep9146, fchikwekwe, gjanco, greatestusername, hickeyma, hughesjj, jacobmarble, jamesmoessis, jmacd, jsuereth, kentquirk, khyatigandhi6, kkujawa-sumo, kongluoxing, liustanley, mapno, mar4uk, marctc, martin-majlis-s1, matej-g, mcardy, mcube8, moh-osman3, mrsillydog, nslaughter, pavankrish123, pcwiese, pjanotti, portertech, povilasv, psx95, pxaws, qiansheng91, rapphil, rmfitzpatrick, rnishtala-sumo, rogercoll, samiura, schmikei, sh0rez, shabicheng, shalper2, sinkingpoint, smithclay, splunkericl, srprash, swiatekm-sumo, tamir-michaeli, tomaz-s1, varunraiko, wangzlei, ycombinator, yotamloe, zdaratom-s1
make: *** [gengithub] Error 1
```

**Comment by crobert-1** [comment]
> I got the following error:

It looks like you don't have a [personal access token configured properly](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/18ef33f417c56483527d1ac537d9b44016ceec28/CONTRIBUTING.md#how-to-become-a-code-owner) for this command to run. The link referenced has the workaround, you can essentially just run `make generate` instead (since you've already updated the CODEOWNERS file). 👍

**Comment by ycombinator** [comment]
Thanks again, @crobert-1. Yup, it was the PAT.  I created a classic GH token with all the permissions and, with that, the `make update-codeowners` command worked.  I've since deleted the token.

**Review by crobert-1 — APPROVED** [review]
Thanks for being willing to help out here @ycombinator! 

Once the original code owner approves we'll be able to merge 👍

**Review by JaredTan95 — APPROVED** [review]

**Pull request merged**
