### PR TITLE
[receiver/filelog] check for invalid strptime format

### PR DESCRIPTION
**Pull request by bacherfl**
**Description:** Check for unsupported fractional seconds directive when converting strptime time layout to native format. This is done to prevent parsing errors which occur due to a limitation of how timestamps are being parsed in go - for more context see this comment in the related issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34390#issuecomment-2268882664

**Link to tracking Issue:** #34390

**Testing:** Added additional unit tests

**Documentation:** TODO, probably will require a note in `regex_parser.md`

### CODE REVIEW

**Review by djaglowski — COMMENTED** [review]
Thanks for taking this on @bacherfl.

I'd like to suggest a slightly different approach for a couple reasons.

This is a good thing to check during config validation but I think this implementation puts it into the critical path for parsing in some cases. Specifically, [`ParseStrptime`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/846ab5d35a2f808d626933c20596ab0c50fa65ea/internal/coreinternal/timeutils/parser.go#L18) is called directly from OTTL each time a timestamp is parsed.

Another problem is that we're _not_ covering some cases, such as when a [`pkg/stanza` operator uses Go's native timestamp format](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/846ab5d35a2f808d626933c20596ab0c50fa65ea/pkg/stanza/operator/helper/time.go#L76), which is subject to the same problem.

Here's what I suggest - can we move the check into a new `Validate` function in `timeutils`, and call it only during config validation?

**Comment by bacherfl** [comment]
> Thanks for taking this on @bacherfl.
> 
> I'd like to suggest a slightly different approach for a couple reasons.
> 
> This is a good thing to check during config validation but I think this implementation puts it into the critical path for parsing in some cases. Specifically, [`ParseStrptime`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/846ab5d35a2f808d626933c20596ab0c50fa65ea/internal/coreinternal/timeutils/parser.go#L18) is called directly from OTTL each time a timestamp is parsed.
> 
> Another problem is that we're _not_ covering some cases, such as when a [`pkg/stanza` operator uses Go's native timestamp format](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/846ab5d35a2f808d626933c20596ab0c50fa65ea/pkg/stanza/operator/helper/time.go#L76), which is subject to the same problem.
> 
> Here's what I suggest - can we move the check into a new `Validate` function in `timeutils`, and call it only during config validation?

Thank you for the review @djaglowski - Looking at the filelog receiver I had the impression that the `ToNative` function was only called during the initialisation, but with OTTL calling it during each parsing of a timestamp it makes sense to move it - thank you for making me aware of that. I will move the validation as suggested.

One related question though - currently there is a similar check if the timestamp contains decimal numbers in the same function: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34459/files#diff-4a6116a3886f046ac7b46bea0d7864d465d7d7080d5c901b68ea233bffefbeeeR125-R128
Would you also suggest to move this one as well?

**Comment by djaglowski** [comment]
> currently there is a similar check if the timestamp contains decimal numbers in the same function

That's a really good point, and looking at it further I see that essentially everything in `ToNative` is work that could be handled during config validation only. Maybe most of `ToNative` can be separated into validation and conversion, and both stanza and OTTL can call validate during config validation, and conversion can be called only as necessary.

**Comment by bacherfl** [comment]
> > currently there is a similar check if the timestamp contains decimal numbers in the same function
> 
> That's a really good point, and looking at it further I see that essentially everything in `ToNative` is work that could be handled during config validation only. Maybe most of `ToNative` can be separated into validation and conversion, and both stanza and OTTL can call validate during config validation, and conversion can be called only as necessary.

Alright, I have now moved what I believe can be extracted from `ToNative` into a separate `ValidateStrptime` function - What's left in `ToNative` is the lookup and replacement of `strptime` directives. Maybe one follow up worth looking into might be to go through the ottl package and see where we can make use of this validation function

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
