### PR TITLE
lokiexporter: Refactor #2385 to follow the current project conventions for third-party code

### PR DESCRIPTION
**Pull request by gramidt**
**Description:**
Refactor of #2385 to follow the current project conventions for third party code. 

Example: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/windowsperfcountersreceiver/internal/third_party/telegraf/win_perf_counters

**Link to tracking Issue:**
#1894

**Testing:** 
Unit Tests

**Documentation:**
Same as #2385

### CODE REVIEW

**Comment by gramidt** [comment]
@bogdandrutu - Since you reviewed #2385 I thought I would keep you in the loop with this change. I came across the 'third_party' pattern used in 'windowsperfcounterreceiver' when grokking the code this morning and decided to refactor my last PR to ensure conventions are consistent throughout the project.

**Comment by gramidt** [comment]
@jpkrohling @bogdandrutu - We'll need to review #2391 before this PR due to Codecov.

**Comment by gramidt** [comment]
@bogdandrutu - I also created #2392 to track what happened in #2385.

**Comment by gramidt** [comment]
Once #2391 is merged, I'll re-push to to kick off the build again to get the proper codecov report.

**Comment by gramidt** [comment]
@bogdandrutu - ping

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
