### PR TITLE
Dedup the duplicated aws session utils code in aws components

### PR DESCRIPTION
**Pull request by mxiamxia**
**Description:** 
We have the duplicated aws session utils code in both `awsemf` and `awsxray` exporters. This PR is to create the common aws session config `awsutil.AWSSessionSettings` for the components that need to communicate with aws services with aws sdk. 

Also, moved the session code to `internal/aws` folder as common utils.

**Link to tracking Issue:** 
n/a

**Testing:** 
`make all`

**Documentation:**
n/a

### CODE REVIEW

**Review by pingleig — COMMENTED** [review]
Can we call the package `sdkutil` or `awssdkutil` since it is only wrapping sdk init logic, creating session from config etc.

Also the package name is a bit confusing, the path is `internal/aws/util` while the package name  is `awsutil`, I think you can skip the import alias in that case. Though I'd prefer either

- use package name`util` in `interna/aws/util` and import as `awsutil`
- use package `internal/aws/awsutil` and import without alias

Actually a lengthy package name `awssdkutil` might be better since IDEs would fill the missing import directly (GoLand etc. does not work that well when they need to inject package import with alias)

**Comment by mxiamxia** [comment]
> Can we call the package `sdkutil` or `awssdkutil` since it is only wrapping sdk init logic, creating session from config etc.
> 
> Also the package name is a bit confusing, the path is `internal/aws/util` while the package name is `awsutil`, I think you can skip the import alias in that case. Though I'd prefer either
> 
> * use package name`util` in `interna/aws/util` and import as `awsutil`
> * use package `internal/aws/awsutil` and import without alias
> 
> Actually a lengthy package name `awssdkutil` might be better since IDEs would fill the missing import directly (GoLand etc. does not work that well when they need to inject package import with alias)

We'll add other aws common utils in this module as well. Don't want to limit it to only `sdkutil` instead of keeping it a general name.


> * use package name`util` in `interna/aws/util` and import as `awsutil`

I'll take this suggestion. Ty!

**Review by pingleig — APPROVED** [review]
LGTM

**Review by bjrara — APPROVED** [review]
LGTM

**Review by anuraaga — APPROVED** [review]

**Comment by anuraaga** [comment]
Nice!

**Pull request merged**
