### PR TITLE
[receiver/awsfirehose] follow receiver contract

### PR DESCRIPTION
**Pull request by VihasMakwana**
This PR enables awsfirehose to follow [the receiver contract](https://github.com/open-telemetry/opentelemetry-collector/blob/df3c9e38a80ccc3b14705462be2e2e51c628a3b3/receiver/doc.go#L10) and maintain the correct order of operations. The status code returned by the receiver should be dependent upon type of error (i.e. permanent/non-permanent error)

### CODE REVIEW

**Review by mwear — APPROVED** [review]

**Comment by VihasMakwana** [comment]
@open-telemetry/collector-contrib-approvers @andrzej-stencel  can this be merged?

**Comment by ChrsMark** [comment]
@Aneurysm9 could you also take a look?

**Comment by andrzej-stencel** [comment]
I'd be happy to merge it, but I'd like to mark it as a breaking change, as the change in the returned HTTP codes can potentially break some users' setups. @VihasMakwana can you make the change to the changelog entry?

**Comment by VihasMakwana** [comment]
@andrzej-stencel done.

**Pull request merged**
