### PR TITLE
[processor/resourcedetection] Add `host.arch` to system detector

### LINKED ISSUE #22939: [processor/resourcedetection] Add `host.arch` to system detector

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

Add `host.arch` to system detector. It is detected via `runtime.GOARCH`. 

This way of detecting may be wrong if running under an emulator or binary translator; the only common case I know of this happening in practice is on ARM64 macOS when using Rosetta. There is a way to detect this (see DataDog/gohai/pull/77) but since we provide arm64 builds for macOS, I think this is a non-issue

**Link to tracking Issue:** Fixes #22939

**Testing:** Added unit tests. Tested on my Linux AMD64 laptop

**Documentation:** Documented new attribute on README

### CODE REVIEW

**Comment by mx-psi** [comment]
Sorry for the noise, this should be ready to review

**Comment by mx-psi** [comment]
Not stale, on hold because of #21482

**Comment by mx-psi** [comment]
@dmitryax this is ready for review after #21482 has landed

Also cc @omrozowicz-splunk if you want to review that I am using the new functionality correctly :)

**Comment by omrozowicz-splunk** [comment]
> @dmitryax this is ready for review after #21482 has landed
> 
> Also cc @omrozowicz-splunk if you want to review that I am using the new functionality correctly :)

LGTM! ☺️

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
@mx-psi Please rebase

**Pull request merged**
