### PR TITLE
Remove dependabot

### PR DESCRIPTION
**Pull request by jpkrohling**
This is related to #8541 and removes the management of Go dependencies by dependabot, especially given that we are not paying attention to its PRs anymore. It's only generating noise, like 288 notifications between Mar 22 and Mar 23.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
:+1: :+1: :+1:

**Review by djaglowski — APPROVED** [review]
I think it is important that we have a standard way to update dependencies (even if very trivial). However, since we haven't actually been using dependabot to perform updates, I don't see any reason not to remove it now.

**Review by pmm-sumo — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
The [script](https://gist.github.com/codeboten/746e43d748347952125eac92bdacbbb4) I've been using to produce update uses the PRs created by dependabot. I'm happy to remove dependabot here, but it would be good to have a plan moving forward.

**Comment by jpkrohling** [comment]
> The [script](https://gist.github.com/codeboten/746e43d748347952125eac92bdacbbb4) I've been using to produce update uses the PRs created by dependabot 

I didn't know that, I thought it would do a `go get` of sorts. I agree with you then: we should have a script ready before removing dependabot then, even if we just run it locally.

**Comment by jpkrohling** [comment]
I'm converting this as draft, as we probably want to think about the replacement before merging this.

**Comment by Aneurysm9** [comment]
https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-954264074 suggests some alternatives we may want to consider that don't involve constructing and maintaining bespoke dependency update systems.

It would be good to know whether the Dependabot security advisories require modules to be enumerated in `dependabot.yaml` and whether we have a way to get those without the update PRs or some other source of security advisories.

**Pull request closed without merging**
