### PR TITLE
[statsdreceiver] fixup metamonitoring

### PR DESCRIPTION
**Pull request by diurnalist**
**Description:**
the statsd receiver does not currently emit metrics or traces about its own internal operations, making it difficult to understand if it's working properly. this introduces an integration w/ the receiverhelper.ObsReport helper, which is the standard way to emit this information.

this also changes how the transport debug logs are emitted; they are now logged via a new transport.Logger interface; the primary reason for this is to avoid confusion w/ the naming--the 'reporter' is now the ObsReport instance, and what the transport.Reporter really was doing was simply emitting debug logs.

**Link to tracking Issue:** #32335

**Testing:**
no new tests are added, but existing tests are updated to pass.

**Documentation:**
n/a

### CODE REVIEW

**Comment by diurnalist** [comment]
fixes #32335 (i had to file the issue to pass the changelog check)

**Comment by diurnalist** [comment]
this is an alternate implementation to #31839 - the approach in this PR uses the standard ObsReporter helper and hooks it onto the flush function.

**Review by atoulme — APPROVED** [review]
LGTM

**Comment by diurnalist** [comment]
duplicated by #33415

**Pull request closed without merging**
