### PR TITLE
Enable vSphere CPU and host metrics by default

### PR DESCRIPTION
**Pull request by BominRahmani**
**Description:** <Describe what has changed.>

The following PR enables the following metrics by default
```
vcenter.vm.cpu.readiness
vcenter.host.network.packet.drop.rate
vcenter.host.cpu.capacity
vcenter.host.cpu.reserve.capacity
```
**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>
Updated golden files
**Documentation:** <Describe the documentation added.>
Updated documentation using make generate

### CODE REVIEW

**Comment by crobert-1** [comment]
Enabling metrics by default that were previously disabled by default is considered a breaking change. Please add a changelog entry accordingly.

[More context](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23050) if it's helpful.

**Comment by BominRahmani** [comment]
@crobert-1 Thanks for letting me know! Will update this shortly.

**Review by StefanKurek — APPROVED** [review]
Aside from the CHANGELOG entry mentioned, looks good.

**Comment by BominRahmani** [comment]
While updating this, i noticed that the integration test was missing an update. Im not sure why it didn't error before, but it was complaining on the CI now, so I went ahead and updated that. I also noticed there was a missing metric from the mock file that caused it to not generate on the golden file, which I also updated.

I am more than happy to split this apart into its own PR if we think its necessary, but I figured since this PR already addresses updating those metrics that were in question to begin with, that I might be able to leave it in. Let me know what you think 
@djaglowski

**Comment by djaglowski** [comment]
Presumably the errors are due to enabling the metrics? Is any other reason possible?

**Comment by BominRahmani** [comment]
@djaglowski The error was specifically related to enabling the `vcenter.host.cpu.capacity` metric, I figured this out by enabling each individual metric, until i found which was causing that CI error. The `vcenter.host.cpu.capacity` was missing a spot in the integration test, so it was finding less metrics than it was expecting.
The part I was a bit confused on is why this didn't cause an error on the integration test part of the CI  when i originally introduced these metrics.

**Comment by djaglowski** [comment]
> The part I was a bit confused on is why this didn't cause an error on the integration test part of the CI when i originally introduced these metrics.

Wouldn't it be because the metric was not enabled in the integration test?

**Comment by BominRahmani** [comment]
@djaglowski Yea, but neither was the other metrics i had added.

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
