### PR TITLE
[connector/servicegraphconnector] Adds a new config option to enable messaging_system's metric generation

### PR DESCRIPTION
**Pull request by t00mas**
**Description:**

- A new configuration option `enable_messaging_system_latency_histogram` is added. When enabled, it will generate a new histogram metric for nodes of `connection_type=messaging_system`, `traces_service_graph_request_messaging_system_seconds`

**Link to tracking Issue:** [#30856](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30856)

**Testing:**

- Adds a new unit test.

**Documentation:**

- Updated README

### CODE REVIEW

**Review by mapno — COMMENTED** [review]
Maybe I'm missing something, but is this adding any new capabilities to the connector? It's simply adding a new metric with info already collected in other latency metrics. What problem is that solving?

**Comment by t00mas** [comment]
> Maybe I'm missing something, but is this adding any new capabilities to the connector? It's simply adding a new metric with info already collected in other latency metrics. What problem is that solving?

All that's true, it's just optionally enabling the creation of a new metric dedicated to messaging systems. It's adapted from https://github.com/grafana/tempo/pull/3453 and was suggested here https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30856

**Comment by mapno** [comment]
> > Maybe I'm missing something, but is this adding any new capabilities to the connector? It's simply adding a new metric with info already collected in other latency metrics. What problem is that solving?
> 
> All that's true, it's just optionally enabling the creation of a new metric dedicated to messaging systems. It's adapted from [grafana/tempo#3453](https://github.com/grafana/tempo/pull/3453) and was suggested here #30856

But that Tempo PR introduces a new way of measuring latency in messaging systems

>My proposal is as follows:
>
>Add a new latency histogram metric.
>The calculation will involve subtracting the producer end_time from the consumer start_time.

IIUC, this one does not.

**Comment by Frapschen** [comment]
Can we implement this feature in the same way the current DB type span does?

**Comment by t00mas** [comment]
Sorry I left this unattended for a while, I took a break. I'll address the missing features for this PR ASAP.

Thanks for the reviews and comments!

**Comment by JaredTan95** [comment]
@t00mas Hi, any updates? just friendly ping, take your time.

**Comment by t00mas** [comment]
> @t00mas Hi, any updates? just friendly ping, take your time.

working on this this week, sorry for the delay

**Pull request closed without merging**
