### PR TITLE
Wire up awsxrayproxy extension

### PR DESCRIPTION
**Pull request by anuraaga**
**Description:** <Describe what has changed.>

Adds awsxrayproxy to the contrib components

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]

**Review by willarmiros — APPROVED** [review]
Do we want to rename to `awsproxy` in case we want any future service requests proxied through here? Won't block on it since i can't think of any use cases right now, but just a thought for extensibility.

**Comment by bogdandrutu** [comment]
Please rebase.

**Review by jpkrohling — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by bogdandrutu** [comment]
@anuraaga not sure if it was a race, but another merge is required :(

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
