### PR TITLE
[chore] remove linux package builds and tests

### LINKED ISSUE #34748: Remove internal/buildscripts/packaging/
### Component(s)

_No response_

### Describe the issue you're reporting

We have internal/buildscripts/packaging/, which was used in the past when we used to generate the binaries from this repository. It's still there, and it's unclear what's the purpose.

Unless we have a clear purpose, I'd propose to remove it, because:

1. its Dockerfile's have vulnerabilities (ie, this module requires active maintenance)
2. it's spending CI cycles for... nothing? that's bad for the environment ;-)

### PR DESCRIPTION
**Pull request by mowies**
This PR removes the package tests from this repo since they were moved to the -releases repo in https://github.com/open-telemetry/opentelemetry-collector-releases/pull/604.

Related issues:
- Original issue: https://github.com/open-telemetry/opentelemetry-collector-releases/issues/439
- Also fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34748

Advantages of doing this:
- removal of duplicated code that has potential to diverge with linux package building and testing happening here with custom code, but the actual code that is used to build the released linux packages is in the -releases repo. This should result in lower maintenance effort and removes technical debt.

Disadvantages discussed here:
- bit of a shift-right for the linux package tests since they are now tested in the -releases repo which could lead to situations where bugs are found too late and e.g. the contrib repo already got a new tag which has a bug that only comes up in the releases repo

### CODE REVIEW

**Comment by codeboten** [comment]
Thanks @mowies, the one concern I have with removing this code is that it's caught issues in the past. Any issues these would catch would only be caught at the releases repo, which means we'd have tagged a potentially broken go module (since we tag contrib modules before the release moves on to the releases repo). Maybe the process should be changed? I'm not sure what the right thing to do is here

**Comment by mx-psi** [comment]
@codeboten Do you remember what issues it caught? Maybe we can test for those in a different way, agnostic to the actual scripts

**Comment by mowies** [comment]
@codeboten I understand. Maybe only testing in the release repo is really too late. What we could try instead is to checkout the releases repo from here and use the actual files from there. If we then also use the make targets from the releases repo directly to build and test the linux packages, there's a very high chance that we miss some error due to a mismatch between this repo's setup and the releases repo's setup.

**Comment by jpkrohling** [comment]
Perhaps we could have a nightly build somewhere (here or in the -releases repo) to catch regressions earlier?

**Comment by mowies** [comment]
Shall I create a separate issue for that here? I think my suggestion that I mentioned above could work nicely in a nightly setup.

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
I propose that we make a nightly build in the -releases repository, using the latest snapshot of core and contrib. @mowies please create an issue to take it from here. I think we're good to delete this code.

**Comment by mowies** [comment]
I created https://github.com/open-telemetry/opentelemetry-collector-releases/issues/659 👍🏼

**Review by mx-psi — APPROVED** [review]

**Comment by andrzej-stencel** [comment]
@mowies can you update the description of this PR to describe why we want to do this? What are the advantages of the removal? It will help future us and future others understand the motivation, especially given that there is a slight disadvantage to the removal as well (potential breakage in -releases repo). 

My guesses of the advantages are: removing code to decrease maintenance cost; decrease time to check PRs.

**Comment by mowies** [comment]
@andrzej-stencel done! :)

**Comment by andrzej-stencel** [comment]
Thanks a lot @mowies, the description is great! Helps a lot.

I agree with the shift-right concert, thanks for raising the issue to create nightly builds https://github.com/open-telemetry/opentelemetry-collector-releases/issues/659. @mowies would you be up for proposing a pull request for this?

**Comment by mowies** [comment]
@andrzej-stencel yes i'll start working on that once this PR is merged :)

**Comment by mx-psi** [comment]
@codeboten Please block/comment on the PR if you think we shouldn't merge this!

**Review by jpkrohling — APPROVED** [review]

**Comment by mowies** [comment]
@andrzej-stencel is anything missing to get this PR over the line? :)
@codeboten pls let us know if you're fine with merging this

**Pull request merged**
