### PR TITLE
[bugfix][apachesparkreceiver] Correct inaccurate metric units

### PR DESCRIPTION
**Pull request by mrsillydog**
**Description:** Replacing inaccurate units for the spark.job.stage.active and spark.job.stage.result metrics for the Apache Spark receiver.

**Link to tracking Issue:** [29104](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29104)

**Testing:** N/A

**Documentation:** Documentation for the metadata.yaml file was updated accordingly.

### CODE REVIEW

**Comment by mrsillydog** [comment]
Lint failure unrelated (fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29101), signalfx exporter test failure is also unrelated (see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29099)

**Review by andrzej-stencel — APPROVED** [review]
Makes sense!

**Comment by mrsillydog** [comment]
Failing integration tests unrelated

**Comment by mrsillydog** [comment]
Failing integration tests unrelated

**Pull request merged**
