### PR TITLE
[chore][cmd/configschema] Enable goleak

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

A lot of leaks were happening in this package because of the extensive list of indirect dependencies. I've filed issues and referenced them for each indirect leak.

This PR contains two main changes:
1. Enable `goleak` checks for all tests within `cmd/configschema`.
2. k8s.io/klog v1 has a leaking goroutine that was [resolved in v2](https://github.com/kubernetes/klog/issues/188). I upgraded the dependency in `recevier/awscontainerinsights` to resolve this issue. This is a code change, but is totally internal and no user impact.

**Link to tracking Issue:** <Issue number if applicable>
#30438

**Testing:** <Describe what testing was performed and which tests were added.>
goleak test is passing

**Thoughts**
1. Some of these indirect dependencies may never get fixed. For example, one source of a leaking goroutine is [cihub/seelog](https://github.com/cihub/seelog), which hasn't had a commit in 8 years.
2. Indirect dependencies that start goroutines in `init()` are the most common cause. For an example of how indirect it gets, we can look at the dbus leak.
```
crobert$ ~/dev/opentelemetry-collector-contrib/cmd/configschema $ go mod why github.com/godbus/dbus
# github.com/godbus/dbus
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/configschema/cfgmetadatagen
github.com/open-telemetry/opentelemetry-collector-contrib/internal/components
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/snowflakereceiver
github.com/snowflakedb/gosnowflake
github.com/99designs/keyring
github.com/godbus/dbus
```
The bug is in the `99designs/keyring` dependency, and the `goleak` is detected as far back as `cmd/configschema` tests.

### CODE REVIEW

**Comment by crobert-1** [comment]
If it's helpful, I can split out the klog v1 to v2 upgrade to a different PR, just let me know.

**Review by mx-psi — APPROVED** [review]
Personally I am fine with keeping the klog change here if we get an approval from @Aneurysm9 or @pxaws before merging :)

**Comment by mx-psi** [comment]
Should we remove the `klog` update and merge the rest?

**Comment by crobert-1** [comment]
> Should we remove the `klog` update and merge the rest?

I believe we still need it, as the leak is coming from the `awscontainerinsightsreceiver` usage. Without that change we need to add a goleak ignore, and we'll keep leaking the goroutine. Even though the `klog` dependency has been updated in contrib outside of this PR, the v1 reference still needs removed, as it's still a dependency alongside v2:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f69e977ba7cf2cb1c51701d5ae1fdc020e801684/go.mod#L704-L705

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
