### PR TITLE
[chore] Promote Christos Markou to triager role

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** Promote @ChrsMark to triager :tada:

- PRs reviewed: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+reviewed-by%3AChrsMark+
- PRs authored: https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+author%3AChrsMark+
- Issues created: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+author%3AChrsMark+
- Issues commented: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues?q=is%3Aissue+commenter%3AChrsMark+
- Commits: https://github.com/open-telemetry/opentelemetry-collector-contrib/commits?author=ChrsMark&since=2023-05-31&until=now

### CODE REVIEW

**Comment by mx-psi** [comment]
cc @open-telemetry/collector-approvers

**Review by evan-bradley — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]
Thanks for your help here @ChrsMark!

**Review by songy23 — APPROVED** [review]
Congrats!

**Review by TylerHelmuth — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Review by ChrsMark — APPROVED** [review]
Thank's for considering me for this! I'll do my best to further help this project!

**Review by codeboten — APPROVED** [review]
Thanks a lot @ChrsMark!

**Pull request merged**
