### PR TITLE
[opampextension] fix blocking agent shutdown due to unclosed channel

### LINKED ISSUE #36764: [Failed test][cmd/opampsupervisor] TestSupervisorStopsAgentProcessWithEmptyConfigMap constantly failed
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

E.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12257185021/job/34195668020

```
    e2e_test.go:1351: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/e2e_test.go:1356
        	            				C:/Users/runneradmin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.windows-amd64/src/runtime/asm_amd64.s:1695
        	Error:      	An error is expected but got nil.
    e2e_test.go:1351: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/e2e_test.go:1351
        	Error:      	Condition never satisfied
        	Test:       	TestSupervisorStopsAgentProcessWithEmptyConfigMap
```

### PR DESCRIPTION
**Pull request by bacherfl**
#### Description

The changes introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35892 seemed to have introduced some flakyness in the opampsupervisor e2e tests, as the shutdown of the opamp agent waits for the component health loop to end. Due to an unclosed channel within the opamp agent however, the agent does not properly shut down, and the supervisor runs into a timeout before ultimately sending a SIGKILL to the agent process.
Closing the channel in the Shutdown method of the opamp extension fixes that and the agent gets shut down properly upon the reception of the SIGINT signal

#### Link to tracking Issue:

Fixes #36764

#### Testing

This fixes the failing test mentioned in the issue (#36764)

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Thanks @bacherfl

**Review by jaronoff97 — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by evan-bradley** [comment]
One of the checks appears to be stuck, and I can't merge in main, so I put the `Run Windows` label on this PR, which isn't a bad idea anyway since the Supervisor tests deal with process management.

**Comment by codeboten** [comment]
> One of the checks appears to be stuck, and I can't merge in main, so I put the Run Windows label on this PR, which isn't a bad idea anyway since the Supervisor tests deal with process management.

It looks like the tests are running now, thanks for the reviews!

**Comment by codeboten** [comment]
Failing test might be related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36772

**Review by pjanotti — APPROVED** [review]

**Pull request merged**
