### PR TITLE
docs: add new configuration option in spanmetricsconnector

### PR DESCRIPTION
**Pull request by rotscher**
**Description:** 

Updated the README of spanmetricsconnector mentioning a new configuration option

### CODE REVIEW

**Comment by portertech** [comment]
@rotscher wonderful, thank you :+1: seems `resource_metrics_key_attributes` usage is becoming a necessary/required configuration option.

**Comment by portertech** [comment]
@fatsheep9146 @atoulme how can I help get this merged?

**Review by codeboten — APPROVED** [review]
Thanks @rotscher!

**Comment by atoulme** [comment]
@albertteoh should review as codeowner.

**Review by albertteoh — APPROVED** [review]
Thanks :)

**Pull request merged**
