### PR TITLE
Collector core internal/ migration into Collector contrib

### PR DESCRIPTION
**Pull request by alexperez52**
**Description:**
This PR follows #4700 and adds the following sub-directories to `internal/`

* internal/processor/
* internal/sharedcomponent/
* internal/internalconsumertest/
* internal/goldendataset/
* internal/idutils/

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Why is this needed?

**Comment by Saber-W** [comment]
@bogdandrutu I tried to update the collector version to v0.33.0 to fix the `unittest` failure. It was something like `using go get collector/model/pdata@v0.33.0`(not exactly the same but similar).

I could roll back to the last commit and see the error.

**Comment by Saber-W** [comment]
Hi @bogdandrutu, because these five directories is depended by the components we want to migrate.

**Comment by Aneurysm9** [comment]
I think each of the directories under `internal` created here should have a `go.mod`.  It would align with the modules that already exist there and keep the top-level module from bloating.

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
Unfortunately we broke the main branch, need to do more work to rebase to the correct main

**Comment by bogdandrutu** [comment]
Already done

**Pull request closed without merging**
