### PR TITLE
sumologicexporter: refactor sender

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

Refactor sender in order to prepare for adding OTLP formats

Reduces size of #32315

**Link to tracking Issue:** #31479

**Testing:** 

Minimal changes to unit tests to ensure that everything works like before

**Documentation:**

N/A

### CODE REVIEW

**Review by swiatekm — APPROVED** [review]

**Review by mx-psi — COMMENTED** [review]
Can you confirm this does not need a changelog entry?

**Comment by sumo-drosiek** [comment]
> Can you confirm this does not need a changelog entry?

I confirm. The only change visible for users is log:

before: `error during sending data: 500 Internal Server Error`
after: `failed sending data: status: 500 Internal Server Error`

**Review by mx-psi — APPROVED** [review]

**Comment by songy23** [comment]
Looks like this leads to test failures: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8800270788/job/24151351338

**Comment by mx-psi** [comment]
@sumo-drosiek This was reverted by #32639

**Pull request merged**
