### PR TITLE
[processor/spanprocessor] Allow changing of span.kind

### PR DESCRIPTION
**Pull request by boostchicken**
Signed-off-by: John D <john@boostchicken.dev>

**Description:** Add the ability to change Span.Kind

**Link to tracking Issue:** #6883

**Testing:** New unit tests added

**Documentation:** README.md updated

### CODE REVIEW

**Comment by boostchicken** [comment]
@ @Aneurysm9  @pmm-sumo can I get somen eyes on this?

**Comment by TylerHelmuth** [comment]
I believe this PR duplicates functionality that already exists in the transformprocessor.  I'm not saying thats unacceptable necessarily, but this is possible to do in the collector today.

**Comment by TylerHelmuth** [comment]
@open-telemetry/collector-contrib-approvers how do we want to handle duplicate functionality?  @boostchicken would users always need a unique instance of the spanprocessor thats dedicated to changing span.kind or could it be added to an existing config of the processor?  Is it conditional, or would every incoming span have its kind updated?

**Comment by boostchicken** [comment]
> @open-telemetry/collector-contrib-approvers how do we want to handle duplicate functionality? @boostchicken would users always need a unique instance of the spanprocessor thats dedicated to changing span.kind or could it be added to an existing config of the processor? Is it conditional, or would every incoming span have its kind updated?

Please see the issue.  The SpanProcessor is the problem this.  I am not aware of this being a duplicate functionality.

**Pull request closed without merging**
