### PR TITLE
[datadogexporter] Consistent `hostname` and default metrics behavior

### LINKED ISSUE #3216: Datadog Exporter: 'running' metric for traces does not have 'otel' prefix
**Describe the bug**
As per pull request #2308, both the _running_ metrics (i.e. the metrics generated by the Datadog Exporter itself to let Datadog know it's running properly) should be prefixed with the string _otel_. Instead, only the _running_ metric for _metrics_ has the _otel_ prefix -- the one for _traces_ does not.
i.e. I see `otel.datadog_exporter.metrics.running` for metrics as expected, but for traces I see `datadog_exporter.traces.running`

**Steps to reproduce**
- Download and install `v0.24.0` of the contrib collector ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb))
- Configure the collector to receive traces and metrics via the OTLP receiver
- Launch a SpringBoot app with `v1.1.0` of the Java auto-instrumentation jar ([opentelemetry-javaagent-all.jar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.1.0))
- Generate some traces by hitting the app's REST endpoint

**What did you expect to see?**
In Datadog, I expected to see the Datadog Exporter's _running_ metrics with the following names:
```
otel.datadog_exporter.traces.running
otel.datadog_exporter.metrics.running
```

**What did you see instead?**
In Datadog, I saw the Datadog Exporter's _running_ metrics with the following names:
```
     datadog_exporter.traces.running
otel.datadog_exporter.metrics.running
```

**What version did you use?**
- `v0.24.0` of the contrib collector ([otel-contrib-collector_0.24.0_amd64.deb](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.24.0/otel-contrib-collector_0.24.0_amd64.deb))
- `v1.1.0` of the Java auto-instrumentation jar ([opentelemetry-javaagent-all.jar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.1.0))

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  datadog:
    api:
      key: "..."

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
```

**Environment**
OS: `Ubuntu 18.04`

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

1. Fix an issue where the `hostname` configuration setting behavior was not consistent between the metrics and traces exporter. The `hostname` flag now consistently acts as a fallback option if no hostname is available in attributes.
2. Fix an issue where the running metric for traces was not namespaced under `otel.`.
3. Refactor code to make errors like these less likely to happen by
   - creating complete metrics (with namespace and hostname) in the `DefaultMetrics` function and 
   - passing the fallback hostname to mapping functions explicitly. 

**Link to tracking Issue:** Fixes #3216

**Testing:** Amended unit tests. Tested in end to end environment

cc @KSerrania to review

### CODE REVIEW

**Review by KSerrania — APPROVED** [review]
LGTM. The CI is failing because of an unrelated error in the `statsdreceiver`.

**Review by ericmustin — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by mx-psi** [comment]
@bogdandrutu done

**Comment by ericmustin** [comment]
@bogdandrutu @mx-psi got a notification this was stale, i think it lgtm, anything we can help w/to get it merged?

**Comment by mx-psi** [comment]
I added the `ready-to-merge` label as discussed in a previous Collector SIG

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
