### PR TITLE
Enable Instana exporter

### LINKED ISSUE #13395: New component: Instana Exporter
## The purpose and use-cases of the new component

The Instana exporter converts OpenTelemetry trace data to Instana content and then sends it to the [Instana Backend](https://www.ibm.com/docs/en/instana-observability/current?topic=references-getting-started-instana).

## Example configuration for the component

The configuration parameters are:

- endpoint: The Instana backend endpoint that the Exporter connects to. It depends on your region and it starts with `https://serverless-`. It corresponds to the Instana environment variable `INSTANA_ENDPOINT_URL`.
- agent_key: Your Instana Agent key. The same agent key can be used for host agents and serverless monitoring. It corresponds to the Instana environment variable `INSTANA_AGENT_KEY`.

### Example:

```yaml
[...]

exporters:
  instana:
    endpoint: ${INSTANA_ENDPOINT_URL}
    agent_key: ${INSTANA_AGENT_KEY}

[...]

service:
  pipelines:
    traces:
      exporters: [instana]

[...]
```

## Telemetry data types supported

Trace

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

Yes

## Sponsor (Optional)

@jpkrohling

### PR DESCRIPTION
**Pull request by hickeyma**
Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>

**Description:** <Describe what has changed.>

This is the third of 3 PRs which adds the new component, Instana exporter. This PR
enables the exporter.

**Link to tracking Issue:** <Issue number if applicable>

Closes #13395

**Testing:** 

Integration test

**Documentation:** 

README updated

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
Don't forget to include it in the contrib's manifest: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

**Comment by hickeyma** [comment]
Need to fix `go.sum`.

**Comment by hickeyma** [comment]
@jpkrohling Fixed the CI issues, needed to updated `cmd/configschema/go.mod`. PTAL again.

**Comment by hickeyma** [comment]
Thanks @jpkrohling for reviews and merge

**Comment by hickeyma** [comment]
> Don't forget to include it in the contrib's manifest: https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml

https://github.com/open-telemetry/opentelemetry-collector-releases/pull/189 pushed.

**Pull request merged**
