### PR TITLE
Map summary metrics to Splunk hec metrics

### PR DESCRIPTION
**Pull request by atoulme**
**Description:** 
Adds mapping of the summary data type to Splunk HEC metrics.

**Link to tracking Issue:** 
#3319 

**Testing:** 
One unit test.

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by bogdandrutu** [comment]
Please update PR title to more verbose sentence :)

**Comment by atoulme** [comment]
Sure, done.

**Comment by bogdandrutu** [comment]
@atoulme this seems related to your change:

```
running go unit test ./... + coverage in /home/circleci/project/exporter/splunkhecexporter
--- FAIL: Test_metricDataToSplunk (0.01s)
    --- FAIL: Test_metricDataToSplunk/double_gauge_empty_data_point (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/double_gauge_empty_data_point
    --- FAIL: Test_metricDataToSplunk/int_gauge_empty_data_point (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/int_gauge_empty_data_point
    --- FAIL: Test_metricDataToSplunk/int_histogram_empty_data_point (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 2
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/int_histogram_empty_data_point
    --- FAIL: Test_metricDataToSplunk/double_histogram_empty_data_point (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 2
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/double_histogram_empty_data_point
    --- FAIL: Test_metricDataToSplunk/int_sum_empty_data_point (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/int_sum_empty_data_point
    --- FAIL: Test_metricDataToSplunk/double_sum_empty_data_point (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/double_sum_empty_data_point
    --- FAIL: Test_metricDataToSplunk/double_histogram_no_upper_bound (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 2
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/double_histogram_no_upper_bound
    --- FAIL: Test_metricDataToSplunk/int_histogram_no_upper_bound (0.00s)
        metricdata_to_splunk_test.go:622: 
            	Error Trace:	metricdata_to_splunk_test.go:622
            	Error:      	Not equal: 
            	            	expected: 2
            	            	actual  : 0
            	Test:       	Test_metricDataToSplunk/int_histogram_no_upper_bound
```

**Comment by atoulme** [comment]
Fixed. Rerunning CI.

**Pull request merged**
