### PR TITLE
Updated otel core dependency to v0.6.0

### PR DESCRIPTION
**Pull request by owais**

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Review by lizthegrey — APPROVED** [review]

**Comment by lizthegrey** [comment]
This can be post-facto merged, as a release has already been cut based on it, right?

**Comment by lizthegrey** [comment]
`TestStabilityTracesZipkin: test_case.go:327: CPU consumption is 64.9%, max expected is 60%`

This is persistently failing, I think we have a regression @owais

**Review by flands — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@owais please rebase, will be fixed.

**Comment by lizthegrey** [comment]
> @owais please rebase, will be fixed.

This has already been released, don't think it can be safely rebased without rewriting a commit published and tagged.

**Comment by owais** [comment]
I cherry picked the fix to make CI pass but did not squash commits. We can merge it after it passes without squashing.

**Comment by lizthegrey** [comment]
merge commits temporarily enabled on this repo to enable a merge rather than squash.

**Comment by lizthegrey** [comment]
and merge commits disabled again. we should be good to go.

**Pull request merged**
