### PR TITLE
[all][chore] Moved from interface{} to any for all go code

### PR DESCRIPTION
**Pull request by lucasoskorep**
**Description:** <Describe what has changed.>

Migrated all code that used interface{} to use the more modern any keyword instead.

Additionally added a golangci-lint.yaml update to automatically apply this change to new code going forward

**Link to tracking Issue:** <23811>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23811

**Testing:** 
No tests added but all existing tests are passing

**Documentation:** 

No documentation updates

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please fix linter https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6804330912/job/18501695939?pr=29072#step:8:268

**Review by Aneurysm9 — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by lucasoskorep** [comment]
@songy23 @atoulme @Aneurysm9  lint should work locally and in the pipeline now - approval needed before the pipeline will run though it seems

**Comment by lucasoskorep** [comment]
Only reported issue is a go vuln based on the version of go being used - should not be related to this PR 

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6804651066/job/18503913770?pr=29072

**Review by songy23 — APPROVED** [review]

**Review by fatsheep9146 — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Will wait until https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29080 is merged and update the branch

**Review by codeboten — APPROVED** [review]

**Pull request merged**
