### PR TITLE
[ottl/pkg] Remove the ottlarg struct tag for the arguments and rely on field ordering

### PR DESCRIPTION
**Pull request by rnishtala-sumo**
Remove the ottlarg struct tag and rely on field ordering
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24874

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]
@rnishtala-sumo thanks for handling this. I am going to hold off merging until @evan-bradley has gotten a chance to review next week.

**Review by evan-bradley — COMMENTED** [review]
I like red PRs like this, thanks for taking this on. Could you add an API changelog for this change and update all filterottl and transform processor functions to remove the `ottlarg` struct tag as well? Since it isn't a user-facing change for the other components I think it would be easier just to remove the tag in one go.

**Review by evan-bradley — APPROVED** [review]
This looks good to me. Tyler and I discussed this offline and we can handle my asks in a follow-up PR.

**Comment by rnishtala-sumo** [comment]
@TylerHelmuth @evan-bradley thanks for merging this. Apologies I couldn't get to this earlier as I took some time off.

**Pull request merged**
