### PR TITLE
[pkg/stanza] Overhaul reader management

### PR DESCRIPTION
**Pull request by djaglowski**
- Change `knownFiles` to `[]*reader.Metadata`. No files are held here.
- Introduce new `previousPollReaders` list, which holds open files from the previous poll interval. If for any reason a file is closed, it should immediately be removed from the list and its metadata should be added to `knownFiles`.
- Introduce notion that each `reader.Metadata` should be treated as a singleton. When a reader is closed, it pops out its `Metadata` so it can be appended to `knownFiles`.

### CODE REVIEW

**Comment by djaglowski** [comment]
@VihasMakwana, I've mentioned previously a need to simplify the way we manage readers, which should in turn simplify the design of your proposal. I believe I finally have substantial step in the right direction. This does not immediately enable your changes but I think it is a good start towards narrowing the problem which asynchronous polling must solve. I plan to break this into smaller PRs but I'd welcome your careful review of these preliminary changes.

**Comment by djaglowski** [comment]
This PR is currently ready but I've moved it back to a draft because I think it could be made less complex but pulling a few changes into smaller PRs.

**Comment by djaglowski** [comment]
I've opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27823 to extract one additional small subset of changes from this PR.

**Comment by djaglowski** [comment]
This is ready for a proper review now.

**Comment by VihasMakwana** [comment]
> I've opened #27823 to extract one additional small subset of changes from this PR.

Would this be one of #28491 or #28493? Because #27823 refers to the current PR.

**Review by VihasMakwana — APPROVED** [review]
Looks good. This will surely help our problem with the asynchronous solution.

**Comment by djaglowski** [comment]
> > I've opened #27823 to extract one additional small subset of changes from this PR.
> 
> Would this be one of #28491 or #28493? Because #27823 refers to the current PR.

Oops, I meant #28580. Either way, already merged. Thanks for the review.

**Review by MovieStoreGuy — APPROVED** [review]
The changes look decent, however, are the changes covered by existing test cases?

**Comment by djaglowski** [comment]
Thanks for the review @MovieStoreGuy.

> are the changes covered by existing test cases?

I think we have pretty good coverage for overall functionality. However, this change is in part motivated by the need to simplify and decompose the package in order to make it more testable.

**Pull request merged**
