### PR TITLE
fix: remove squash on configtls.TLSClientSetting for splunkhecexporter

### PR DESCRIPTION
**Pull request by hyunuk**
**Description:**
This PR removes squash on`configtls.TLSClientSetting` and update corresponding yaml file for splunkhecexporter.
See history [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5454)

**Link to tracking Issue:**
#5433

### CODE REVIEW

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Review by dmitryax — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@hyunuk  Please resolve the merge conflict.

**Comment by hyunuk** [comment]
> @hyunuk Please resolve the merge conflict.

@tigrannajaryan Done! took longer than expected due to the consistent test failure.

**Review by tigrannajaryan — APPROVED** [review]
Thank you!

**Pull request merged**
