### PR TITLE
[chore] Consistent copyright first line

### PR DESCRIPTION
**Pull request by bogdandrutu**
* Remove year, we don't have that in majority of the files
* Remove double space between "Copyright" and "The"

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Comment by dashpole** [comment]
Do we have a copyright checker?

**Comment by bogdandrutu** [comment]
We do, but all these pass, because the copyright is present and year is not mandatory for the check.

**Comment by dashpole** [comment]
Can we disallow the year to keep it consistent?  Or maybe it isn't worth it

**Comment by djaglowski** [comment]
I agree this is the better format, but want to note that the `addlicense` tool generates the double space, so we'll continue to see this in new files without an additional change.

**Comment by djaglowski** [comment]
Looks like the extra space issue was [addressed recently](https://github.com/google/addlicense/pull/125), but the change has not yet been released.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
