### PR TITLE
[chore] remove what looks to be debugging code from instanaexporter

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@jpkrohling please pay attention in the future at reviews when you are sponsor. In this case there is no point in maintaining this copied code here, just adds unnecessary maintenance effort on us.

**Review by hickeyma — APPROVED** [review]
LGTM, thanks for finding this @bogdandrutu

**Comment by hickeyma** [comment]
> @jpkrohling please pay attention in the future at reviews when you are sponsor. In this case there is no point in maintaining this copied code here, just adds unnecessary maintenance effort on us.

@bogdandrutu Sorry, I missed this as well. It probably was during the reviews when logging was changed.

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
> It probably was during the reviews when logging was changed.

I remember seeing this code and noticing it was a duplication of existing code, but should indeed have been more critical in accepting this duplication.

**Pull request merged**
