### PR TITLE
[chore] [processor/filter] Fix unit tests

### LINKED ISSUE #17055: [processor/filterprocessor] Broken `TestLoadingConfigOTTL` tests
Part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17037

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3706734880/jobs/6282715360

```
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/filterprocessor'
go test -race -timeout 300s --tags="" ./...
--- FAIL: TestLoadingConfigOTTL (0.04s)
    --- FAIL: TestLoadingConfigOTTL/filter/bad_syntax_span (0.00s)
        config_test.go:9[38](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3706734880/jobs/6282715360#step:9:39): 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/filterprocessor/config_test.go:938
            	Error:      	Error message not equal:
            	            	expected: "1:24: unexpected token \"[\" (expected <opcomparison> Value)"
            	            	actual  : "1:24: unexpected token \"[\" (expected <opcomparison> Value); unable to parse OTTL statement, ensure the statement's syntax is correct; common mistakes include missing parentheses, missing double quotes and incorrect function name case"
            	Test:       	TestLoadingConfigOTTL/filter/bad_syntax_span
    --- FAIL: TestLoadingConfigOTTL/filter/bad_syntax_spanevent (0.00s)
        config_test.go:938: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/filterprocessor/config_test.go:938
            	Error:      	Error message not equal:
            	            	expected: "1:24: unexpected token \"[\" (expected <opcomparison> Value)"
            	            	actual  : "1:24: unexpected token \"[\" (expected <opcomparison> Value); unable to parse OTTL statement, ensure the statement's syntax is correct; common mistakes include missing parentheses, missing double quotes and incorrect function name case"
            	Test:       	TestLoadingConfigOTTL/filter/bad_syntax_spanevent
    --- FAIL: TestLoadingConfigOTTL/filter/bad_syntax_metric (0.00s)
        config_test.go:938: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/filterprocessor/config_test.go:938
            	Error:      	Error message not equal:
            	            	expected: "1:33: unexpected token \"[\" (expected <opcomparison> Value)"
            	            	actual  : "1:33: unexpected token \"[\" (expected <opcomparison> Value); unable to parse OTTL statement, ensure the statement's syntax is correct; common mistakes include missing parentheses, missing double quotes and incorrect function name case"
            	Test:       	TestLoadingConfigOTTL/filter/bad_syntax_metric
    --- FAIL: TestLoadingConfigOTTL/filter/bad_syntax_datapoint (0.00s)
        config_test.go:938: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/filterprocessor/config_test.go:938
            	Error:      	Error message not equal:
            	            	expected: "1:24: unexpected token \"[\" (expected <opcomparison> Value)"
            	            	actual  : "1:24: unexpected token \"[\" (expected <opcomparison> Value); unable to parse OTTL statement, ensure the statement's syntax is correct; common mistakes include missing parentheses, missing double quotes and incorrect function name case"
            	Test:       	TestLoadingConfigOTTL/filter/bad_syntax_datapoint
    --- FAIL: TestLoadingConfigOTTL/filter/bad_syntax_log (0.00s)
        config_test.go:938: 
            	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/filterprocessor/config_test.go:938
            	Error:      	Error message not equal:
            	            	expected: "1:24: unexpected token \"[\" (expected <opcomparison> Value)"
            	            	actual  : "1:24: unexpected token \"[\" (expected <opcomparison> Value); unable to parse OTTL statement, ensure the statement's syntax is correct; common mistakes include missing parentheses, missing double quotes and incorrect function name case"
            	Test:       	TestLoadingConfigOTTL/filter/bad_syntax_log
```

### PR DESCRIPTION
**Pull request by dmitryax**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17055

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
I'll add back the detailed error message once our unit test issue is resolved.

**Comment by dmitryax** [comment]
Fixed related tests in transform processor

**Comment by dmitryax** [comment]
> I'll add back the detailed error message once our unit test issue is resolved.

Do you think it needs to be that verbose? Please suggest different message, I can update it

**Comment by TylerHelmuth** [comment]
@dmitryax we can leave it off for now.

**Review by TylerHelmuth — APPROVED** [review]

**Pull request merged**
