### PR TITLE
[receiver/mongodb]: Add oplog.size metric

### PR DESCRIPTION
**Pull request by davidji99**
#17368

----

**Description:** <Describe what has changed.>
Add `mongodb.oplog.size` metric.

----

@djaglowski I'm curious if you are familiar with mongodb? I believe this metric only exists when you have a mongodb setup with a primary replicating to secondary. I also think I used the correct admin command to retrieve this metric based on what I saw in Percona's mongodb exporter.

### CODE REVIEW

**Comment by djaglowski** [comment]
> @djaglowski I'm curious if you are familiar with mongodb? I believe this metric only exists when you have a mongodb setup with a primary replicating to secondary. I also think I used the correct admin command to retrieve this metric based on what I saw in Percona's mongodb exporter.

I'm not very familiar with replication or this particular diagnostic command. Can you link me to documentation about both the metric and command used to collect it?

I think we need to do a bit more legwork before adding this:
1. Does the command require any additional permissions?
2. Does the command introduce a notable performance impact?
3. Need to document specifically when it is applicable, vs when not to expect the metric.
4. Are there conditions where we should not attempt to collect the metric? (e.g. Doing so would cause an error, or based on the config we may know ahead of time that it will not be available)

**Comment by davidji99** [comment]
> > @djaglowski I'm curious if you are familiar with mongodb? I believe this metric only exists when you have a mongodb setup with a primary replicating to secondary. I also think I used the correct admin command to retrieve this metric based on what I saw in Percona's mongodb exporter.
> 
> I'm not very familiar with replication or this particular diagnostic command. Can you link me to documentation about both the metric and command used to collect it?
> 
> I think we need to do a bit more legwork before adding this:
> 
> 1. Does the command require any additional permissions?
> 2. Does the command introduce a notable performance impact?
> 3. Need to document specifically when it is applicable, vs when not to expect the metric.
> 4. Are there conditions where we should not attempt to collect the metric? (e.g. Doing so would cause an error, or based on the config we may know ahead of time that it will not be available)

The metric: https://www.mongodb.com/docs/manual/core/replica-set-oplog/#oplog-size

I can't find the command from [official documentation](https://www.mongodb.com/docs/manual/reference/command/nav-diagnostic/) for the command `getDiagnosticData` but I did find an article from Percona: https://www.percona.com/blog/2020/09/22/new-mongodb-exporter-released-with-percona-monitoring-and-management-2-10-0/. I did confirm locally that the command works when setting up mongodb with a primary and secondary deployment. From the output of `getDiagnosticData`, it seems to have overlapping data from the other commands currently in use by the receiver (https://github.com/percona/mongodb_exporter/issues/284#issuecomment-853805045). I guess it's an aggregator of various data. Based on it's output, this command might be the only command the receiver needs for metric scraper.

For your questions:

> 1. Does the command require any additional permissions?
Not that I am aware of. The command works fine locally with no additional permissions required.

> 2. Does the command introduce a notable performance impact?
I don't believe so. I ran the following command `db.collection.explain("getDiagnosticData").aggregate()` and got:
```
{"plannerVersion": new NumberInt("1"), "namespace": "admin.collection", "indexFilterSet": false, "parsedQuery": {}, "optimizedPipeline": true, "winningPlan": {"stage": "EOF"}, "rejectedPlans": []}
```

The output doesn't tell me much but `optimizedPipeline` is `true` so that might count for something here.

> 3. Need to document specifically when it is applicable, vs when not to expect the metric.
I add a blurb to `documentation.md` about when to expect this metric, which I believe only exists when the mongodb setup is in a replicaset.

> 4. Are there conditions where we should not attempt to collect the metric? (e.g. Doing so would cause an error, or 
It is likely we don't need to collect it in a single node mongodb instance.

**Comment by djaglowski** [comment]
@davidji99, I did some digging of my own and found that `getDiagnosticData` is listed as an [unsupported command](https://www.mongodb.com/docs/atlas/unsupported-commands/), so I don't think we should take this on as a dependency. 

The official documentation has [this section about retrieving the size of the oplog](https://www.mongodb.com/docs/manual/tutorial/troubleshoot-replica-sets/#check-the-size-of-the-oplog). Have you looked into this yet?

**Comment by davidji99** [comment]
> @davidji99, I did some digging of my own and found that `getDiagnosticData` is listed as an [unsupported command](https://www.mongodb.com/docs/atlas/unsupported-commands/), so I don't think we should take this on as a dependency.
> 
> The official documentation has [this section about retrieving the size of the oplog](https://www.mongodb.com/docs/manual/tutorial/troubleshoot-replica-sets/#check-the-size-of-the-oplog). Have you looked into this yet?

Dang okay. @djaglowski:

Well in my latest commit, I added a feature flag that enables and disables scraping for replication related metrics. This should save an unnecessary command execution if the target mongodb instance isn't a replicaSet. Though I am wondering if it better for this flag to be a `Config` setting instead? In any event, I then run the `replSetGetStatus` to actually check the status of the replica set. If the command doesn't error out, then the target mongodb instance is a replSet.

As for getting the actual oplog metric, I was going to use diagnostic data but you say it's unsupported. [`db.getReplicationInfo()`](https://www.mongodb.com/docs/manual/reference/method/db.getReplicationInfo/) is the other command I was looking at but this is 'function'. It would print out:

```
stage:SECONDARY> db.getReplicationInfo()
{
        "logSizeMB" : 5000,
        "usedMB" : 4966.63,
        "timeDiff" : 11808110,
        "timeDiffHours" : 3280.03,
        "tFirst" : "Sat Sep 17 2022 05:00:24 GMT+0000",
        "tLast" : "Tue Jan 31 2023 21:02:14 GMT+0000",
        "now" : "Tue Jan 31 2023 21:02:25 GMT+0000"
}
```

You referenced `rs.PrintReplicationInfo()` but I'm not sure how to translate this Golang and stating`mongosh` in the instructions means it can't be pulled by the Golang mongodb driver?

**Comment by djaglowski** [comment]
> As for getting the actual oplog metric, I was going to use diagnostic data, but you say it's unsupported. [db.getReplicationInfo()](https://www.mongodb.com/docs/manual/reference/method/db.getReplicationInfo/) is the other command I was looking at, but this is a 'function'. It would print out:

It might be worth some more research - I'd be surprised if there is not a supported command for this.

**Pull request closed without merging**
