### PR TITLE
Propose @kovrus as approver

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]
I support! Thanks @kovrus for your help with OTTL.

**Review by codeboten — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Comment by codeboten** [comment]
Pinging @kovrus please approve :)

**Comment by jpkrohling** [comment]
I'm sure he'll approve it during EU working hours :-)

**Comment by codeboten** [comment]
@jpkrohling for sure, just want to make sure folks dont get marked as approver without their approvals :D

**Review by kovrus — APPROVED** [review]
LGTM :) I really appreciate the opportunity!

**Pull request merged**
