### PR TITLE
feat: implement JWT extension

### LINKED ISSUE #20539: New component: JWT server authenticator
### The purpose and use-cases of the new component

This extension authenticates users who want to send data to your collector with a JWT, enabling multi-tenant use cases easier. Based on the auth claims data, you can use a processor like [`attributesprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) to filter or enrich the data. Authenticity is ensured by signing the JWT token with the same secret before.

### Example configuration for the component

```yaml
extensions:
  jwt:
    secret: "secret"

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: jwt

processors:
  # Extract the project id from the auth context
  attributes/from_auth_context:
    actions:
      - key: project.id
        from_context: auth.project_id
        action: insert

exporters:
  logging:
    logLevel: debug

service:
  extensions: [jwt]
  pipelines:
    traces:
      receivers: [otlp]
      # Apply the processor
      processors: [attributes/from_auth_context]
      exporters: [logging]
```

### Telemetry data types supported

traces, metrics and logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

_No response_

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20524

### PR DESCRIPTION
**Pull request by StarpTech**
**Description:** <Describe what has changed.>

Fix #20539 

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

Unit tests

**Documentation:** <Describe the documentation added.>

https://github.com/wundergraph/opentelemetry-collector-contrib/blob/dustin/add_jwt_authenticator/extension/jwtauthextension/README.md

### CODE REVIEW

**Review by ggeijteman-wg — APPROVED** [review]

**Comment by ggeijteman-wg** [comment]
@jpkrohling Morning, could we get your approval to finish the workflows so we can pass all tests and get all the checkmarks green ✅? We went ahead and updated his PR to match `0.78.0`.

**Comment by StarpTech** [comment]
Please reopen.

**Comment by jpkrohling** [comment]
Sorry for not getting back sooner to this. This component still has no sponsors. It won't be accepted until you have one. Please, look at the following page for more info on this:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

Here's a list of maintainers and approvers who are eligible for being sponsors:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/README.md#contributing

**Comment by StarpTech** [comment]
Can we keep it open? @jpkrohling

**Comment by jpkrohling** [comment]
I reopened, but note that this will not be merged until you have sponsors for it.

**Comment by RichardoC** [comment]
Any chance we could get this reopened? I'd love for this to be part of the project, rather than having to put a proxy infront

**Pull request closed without merging**
