### PR TITLE
Revert "Update module github.com/haimrubinstein/go-syslog/v3 to v3.0.3"

### PR DESCRIPTION
**Pull request by djaglowski**
Reverts open-telemetry/opentelemetry-collector-contrib#31199

It's unclear why renovate detected an updated version or what the version includes. Until this is clear, I suggest we pin to v3.0.0.

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]

**Comment by djaglowski** [comment]
@haimrubinstein, since you're managing the fork, can you help us get to the bottom of this?

**Review by mx-psi — APPROVED** [review]

**Review by songy23 — COMMENTED** [review]
This broke mainline https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8100262351/job/22137954249

**Comment by crobert-1** [comment]
> This broke mainline https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8100262351/job/22137954249

I've had ~5 PRs that failed requiring `make gotidy` to be run with this issue as well.

**Comment by songy23** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31515

**Pull request merged**
