### PR TITLE
bump github.com/openshift/client-go, github.com/openshift/api versions

### PR DESCRIPTION
**Pull request by roycald245**
**Description:** Upgrading openshift packages to a higher version to avoid dependencies with critical vulnerabilities

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/security/advisories/GHSA-9v8f-9h75-jxwh

**Testing:** Ran `make gotest`

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Please rebase against main and resolve conflicts

**Comment by roycald245** [comment]
Not sure what to do about go.sums updating constantly, causing conflicts.

**Comment by mx-psi** [comment]
`make gotidy` should take care of the conflicts for you, since it removes the `go.sum` files and recreates them from scratch

**Comment by roycald245** [comment]
Yes thats what I am doing. But I fear that until the next review it will be conflicted again since it changes frequently.

**Comment by mx-psi** [comment]
> Yes thats what I am doing. But I fear that until the next review it will be conflicted again since it changes frequently.

You can split the PR into smaller PRs and get those merged if you prefer. We need to do frequent dependency updates and we also had a release, so I cannot guarantee that go.sum files won't change again.

**Comment by roycald245** [comment]
Yes of course dependencies need to change frequently. But the diff will stay mostly the same, so it might not block the pr

**Pull request closed without merging**
