### PR TITLE
[processor/transform] Add declarative syntax to config

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
This PR adds the ability to configure the transform processor using declarative syntax.  This is achieved by using the parser's internal data model. 

**Link to tracking Issue:** 
#11852

**Testing:** 
Added new tests

**Documentation:** 
Updated README.

### CODE REVIEW

**Comment by kentquirk** [comment]
I really don't like exposing ParsedQuery directly -- the query structure is quite deep and it means that changes to the grammar that are more than casual (for example, the work I just did to add chains of AND and OR) would break existing configurations.

I would definitely not want to do that while the query language is in flux. 

And even if it weren't, it's also, as you note, quite hard to use. Even writing tests for the parser is cumbersome (and slow). 

What about something like:

```yaml
traces:
  - set:
      field1: value
    conditions:
      service.name: login
```

There are definitely interesting questions around the detailed syntax of conditions (and vs or) but they're probably tractable.

And done this way we can probably write a fairly simple thing that translates these mechanically to the SQL-like text that the parser can understand.

Alternatively, the parser could grow up to be more composable (parse the individual clauses).

**Comment by TylerHelmuth** [comment]
I agree, I think we need something in between or our config will always be changing and cumbersome. 

I like the idea of using the parser to be the translator between the config and the TQL. I'll play around with that.

**Comment by TylerHelmuth** [comment]
I am going to close this PR and come back to this concept once #11751 is completed

**Pull request closed without merging**
