### PR TITLE
[chore] update otel core

### PR DESCRIPTION
**Pull request by codeboten**

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
Needs `make genotelcontribcol` and a few more fixes.

**Review by bogdandrutu — APPROVED** [review]

**Comment by codeboten** [comment]
This is a question for the @open-telemetry/collector-maintainers, the following changes are needed as a result of https://github.com/open-telemetry/opentelemetry-collector/commit/6b12cc3203488429a3e3d101ee9e9dd152936c6a:

-  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30167/commits/a8ee98b44e6437cf8b76d45b1e4e4bd82e4e370d
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30167/commits/3b3f0c9b1db69d66c2e24f515bc01f308a1c7ea9

The second change (randomization setting) was a bug, but in both of those changes, the validation which wasn't triggered before now causes an error. This could be a breaking change for the users of those components that rely on retry settings. What's the best way to move forward? Pinging @bogdandrutu as the author of the change

**Comment by bogdandrutu** [comment]
> The second change (randomization setting) was a bug, but in both of those changes, the validation which wasn't triggered before now causes an error. This could be a breaking change for the users of those components that rely on retry settings. What's the best way to move forward? Pinging @bogdandrutu as the author of the change

Let's analyze them:

1. Multiplier

    - If 0, DivisionByZero exception will be thrown in the `backoff.NextBackOff()` -> `backoff.incrementCurrentInterval()`
    - If <0, a negative `currentInterval` can be calculated, which means no sleep between retries and continue retrying. Also can get into an infinite retries scenario if next gets lower and lower every time is re-calculated and will never exceed `MaxElapsedTime`, see `NextBackOff()`

2. RandomizationFactor

    - If <0, a negative `next` can be calculated, which means no sleep between retries and continue retrying. Also can get into an infinite retries scenario if next gets lower and lower every time is re-calculated and will never exceed `MaxElapsedTime`, see `NextBackOff()`

Both these scenarios are bugs and possible undefined behaviors, so because of that failing faster in these scenario cannot be called "breaking change" in my opinion.

**Comment by codeboten** [comment]
> Both these scenarios are bugs and possible undefined behaviors, so because of that failing faster in these scenario cannot be called "breaking change" in my opinion.

Right, they are bugs but the behaviour is breaking as users didn't have to configure these fields before (I suspect there was a default being set somewhere) meaning that if a users has retry configuration set somewhere without those fields today, and they upgrade to the next version of the collector, their collectors will crash because of this validation.

To be clear I'm not saying that the new behaviour is incorrect, just that it potentially breaks existing deployments. I guess an alternative here would be for the exporters to set a default value for users?

I haven't had the chance to dig into why that validation wasn't triggered before, but agree that it would have allowed buggy configuration to exist.

**Comment by bogdandrutu** [comment]
> Right, they are bugs but the behaviour is breaking as users didn't have to configure these fields before (I suspect there was a default being set somewhere) meaning that if a users has retry configuration set somewhere without those fields today, and they upgrade to the next version of the collector, their collectors will crash because of this validation.

Who is the user in this case? If you think of the end-user that writes the yaml file, they will most likely (99.99%) not have any problem, we have defaults for these values. And as I explained if they did not set a value for `Multiplier` they will crash a bit later. If they would have manually set in their yaml a negative value for any of these fields then yes, that will crash validation, but I would not call that a breaking behavior.

**Comment by codeboten** [comment]
> Who is the user in this case? If you think of the end-user that writes the yaml file, they will most likely (99.99%) not have any problem, we have defaults for these values. 


So here is the problem I'm seeing with the following config (the values are pulled straight from the test file, and note the missing multiplier):

```yaml
receivers:
  otlp:
    protocols:
      http:

exporters:
  azuredataexplorer:
    # Kusto cluster uri
    cluster_uri: "https://CLUSTER.kusto.windows.net"
    # Client Id
    application_id: "f80da32c-108c-415c-a19e-643f461a677a"
    # The client secret for the client
    application_key: "xx-xx-xx-xx"
    # The tenant
    tenant_id: "21ff9e36-fbaa-43c8-98ba-00431ea10bc3"
    # database for the logs
    db_name: "oteldb"
    # raw metric table name
    metrics_table_name: "OTELMetrics"
    # raw log table name
    logs_table_name: "OTELLogs"
    # raw traces table
    traces_table_name: "OTELTraces"
    # type of ingestion managed or queued
    ingestion_type: "managed"
    #export helper options
    timeout: 10s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 10
    retry_on_failure:
      enabled: true
      initial_interval: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [azuredataexplorer]
```

In v0.91.0, the result would be this:

```
./bin/otelcontribcol_darwin_amd64 --config ../config.yaml
2024-01-03T20:01:09.991-0800    info    service@v0.91.0/telemetry.go:86 Setting up own telemetry...
2024-01-03T20:01:09.992-0800    info    service@v0.91.0/telemetry.go:203        Serving Prometheus metrics      {"address": ":8888", "level": "Basic"}
2024-01-03T20:01:09.993-0800    info    service@v0.91.0/service.go:145  Starting otelcontribcol...      {"Version": "0.91.0-dev", "NumCPU": 8}
2024-01-03T20:01:09.993-0800    info    extensions/extensions.go:34     Starting extensions...
2024-01-03T20:01:09.993-0800    warn    internal@v0.91.0/warning.go:40  Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks      {"kind": "receiver", "name": "otlp", "data_type": "traces", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
2024-01-03T20:01:09.993-0800    info    otlpreceiver@v0.91.0/otlp.go:101        Starting HTTP server    {"kind": "receiver", "name": "otlp", "data_type": "traces", "endpoint": "0.0.0.0:4318"}
2024-01-03T20:01:09.993-0800    info    service@v0.91.0/service.go:171  Everything is ready. Begin running and processing data.
```

In this current version (with the changes in core), the result is:

```
./bin/otelcontribcol_darwin_amd64 --config ../config.yaml
Error: invalid configuration: exporters::azuredataexplorer: 'multiplier' must be positive
2024/01/03 19:57:07 collector server run finished with error: invalid configuration: exporters::azuredataexplorer: 'multiplier' must be positive
```

Is this not by definition a breaking change? Without changing my config, because the defaults are no longer applied, the collector will not start.

**Comment by sfc-gh-bdrutu** [comment]
>Is this not by definition a breaking change? Without changing my config, because the defaults are no longer applied, the collector will not start.

Once you receive the first item and try to export it you will crash, because of https://github.com/cenkalti/backoff/blob/a04a6fe64ffb0e3fd0816460529d300be5f252df/exponential.go#L116C30-L116C43

**Comment by codeboten** [comment]
I'm not seeing the collector crash on retry, it's showing me errors like:

```
2024-01-04T12:58:59.272-0800	info	exporterhelper/retry_sender.go:154	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "azuredataexplorer", "error": "problem getting 
authorization context from Kusto via Mgmt: Op(OpMgmt): Kind(KInternal): Error while getting token : 
ClientSecretCredential: unable to resolve an endpoint: http call(https://login.microsoftonline.com/21ff9e36-fbaa-43c8-
98ba-00431ea10bc3/v2.0/.well-known/openid-configuration)(GET) error: reply status code was 
400:\n{\"error\":\"invalid_tenant\",\"error_description\":\"AADSTS90002: Tenant ...."}", "interval": "0s"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter.(*adxDataProducer).ingestData
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter@v0.91.0/adx_exporter.go:67
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter.(*adxDataProducer).tracesDataPusher
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter@v0.91.0/adx_exporter.go:122
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).Export
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/traces.go:58
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/timeout_sender.go:38
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/retry_sender.go:119
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/traces.go:171
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).consume
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/queue_sender.go:115
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/bounded_memory_queue.go:55
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*QueueConsumers[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/consumers.go:43
2024-01-04T12:58:59.272-0800	error	exporterhelper/queue_sender.go:123	Exporting failed. No more retries left. 
Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "azuredataexplorer", "error": "interrupted due to
 shutdown problem getting authorization context from Kusto via Mgmt: Op(OpMgmt): Kind(KInternal): Error while 
getting token : ClientSecretCredential: unable to resolve an endpoint: http 
call(https://login.microsoftonline.com/21ff9e36-fbaa-43c8-98ba-00431ea10bc3/v2.0/.well-known/openid-
configuration)(GET) error: reply status code was 
400:\n{\"error\":\"invalid_tenant\",\"error_description\":\"AADSTS90002: ...}", "dropped_items": 2}
```

Note I don't have a valid azure account (i'm not sure how to set one up for free). It doesn't crash because it's a division by `0.0` which results in `+Inf`. I tested this with:

```
import "fmt"

type thing struct {
	multiplier float64
}

func main() {
	a := thing{}
	fmt.Printf("%0.2f", 5/a.multiplier)
}

```
Which prints out:

`+Inf`

**Comment by bogdandrutu** [comment]
Learned something new (that division by 0 is +Inf), but still don't think is correct because:
* If division by 0 is +Inf, then `b.currentInterval` will become 0. Which means will continuously (without stop) retry until MaxElapsed is passed, which will technically work, though not sure is expected.
* In your example MaxElapsed is 0, so will not retry at all after the initial failure. Arguably, I think we should make this an error in the validation since users may expect their operations to retry.

**Comment by codeboten** [comment]
> Learned something new (that division by 0 is +Inf), but still don't think is correct because:

Ditto! This adventure is turning out to be the most fun update of the core repo yet 😄 

To be clear I also agree the validation is the right thing to do, my only concern remains w/ the fact that this configuration change causes what could have been happily working for a user (that might have configured a retry but never actually uses it for example), to have a collector that will no longer start. Maybe this isn't a big deal, but it should still be recorded as a breaking change I think. WDYT?

**Comment by mx-psi** [comment]
In [VERSIONING.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/VERSIONING.md#configuration-structures) we recently added the following wording:

>  A valid configuration struct as defined by its Validate method return value must continue to be valid after a change to the validation rules, **except when the configuration struct would cause an error on its intended usage** (e.g. when calling a method or when passed to any method or function in any module under opentelemetry-collector).

I guess the decision that we need to make is whether this was an error on its intended usage. If this reliably leads to crashes, then I think this is not to be considered a breaking change

**Review by atoulme — APPROVED** [review]

**Pull request merged**
