### PR TITLE
[chore] add generate commands to build targets for otelcontribcol and oteltestbedcol

### LINKED ISSUE #35631: make otelcontribcol is now failing due to no Go files in ./cmd/otelcontribcol
### Component(s)

cmd/otelcontribcol

### What happened?

I was trying to build otelcontribcol using a make target `otelcontribcol` but it started failing after v0.111.0 because there are no Go files anymore in .cmd/otelcontribcol, is this some sort of a bug or is there any new way of building the project?

Thanks.

### Collector version

x.x.x

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mowies**
#### Link to tracking issue
Fixes #35631 

#### Testing
- run `make otelcontribcol` with a clean working directory, it should succeed
- run `make oteltestbedcol` with a clean working directory, it should succeed

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
cc @bogdandrutu @andrzej-stencel

**Comment by TylerHelmuth** [comment]
Downside to removing the code from the repo is that these make targets will take longer now.  I agree with this as a solution for now tho.

**Review by sfc-gh-bdrutu — COMMENTED** [review]
Found lots of things to change, I fired https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35707

**Comment by bogdandrutu** [comment]
Sorry, I fixed all comments in a different PR. If you still need more change feel free to re-open the PR.

**Comment by mowies** [comment]
ok 😅

**Pull request closed without merging**
