### PR TITLE
feat(routingprocessor): route on resource attributes

### LINKED ISSUE #5538: routingprocessor: use resource attributes instead of context
**Is your feature request related to a problem? Please describe.**

Hi everyone,

I would like to use the [routingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor) to route my records to different exporters based on a resource attribute value.
Currently, the routingprocessor uses context to find the attribute.

**Describe the solution you'd like**

I'd like to add a new configuration option like `attribute_source`, which could be set to `context` or `resource` and would default to `context` to keep backwards compatibility. If set to `resource`, the processor would look for the attribute specified in `from_attribute` not in the context, but in resource attributes.

At the same time, I'd like to extend the scope of the processor from traces only to logs and metrics as well (this could be a separate pull request if that makes sense).

**Describe alternatives you've considered**

I don't really see any alternative.

**Additional context**

Not much

### PR DESCRIPTION
**Pull request by pmalek-sumo**
**Description:** Add a feature to `routingprocessor` to route traces on resource attributes and make it configurable (retaining previous default to read from context).

**Link to tracking Issue:** Fixes #5538

**Testing:** Added unit tests.

**Documentation:** Changed README.

---

Huge shout-out to @astencel-sumo for this patch! 🙇

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
This PR is great! I had only a few minor comments, but overall, this is a great addition and will make the routing processor way more useful than it currently is.

**Review by jpkrohling — APPROVED** [review]

**Comment by astencel-sumo** [comment]
Fixes #5538

**Comment by bogdandrutu** [comment]
Manually triggered CircleCI.

**Comment by bogdandrutu** [comment]
Lint and unittest failure.

**Comment by pmalek-sumo** [comment]
> Lint and unittest failure.

Looks unrelated. I've rebased on `HEAD` of main.

**Comment by tigrannajaryan** [comment]
I file a bug report: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5726

**Comment by bogdandrutu** [comment]
Re-triggered manually CircleCi

**Pull request merged**
