### PR TITLE
Update zdaratom codeowner since nick has changed

### PR DESCRIPTION
**Pull request by zdaratom**
Description: Update zdaratom codeowner for datasetexporter since nick has changed
Link to tracking Issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20660
Testing: NA
Documentation: NA

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
This will require an update to the readme as well correct?

**Comment by zdaratom-s1** [comment]
My account is not listed in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/README.md

**Comment by codeboten** [comment]
@zdaratom-s1 i meant this one: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datasetexporter

**Comment by zdaratom-s1** [comment]
Good catch, I have fixed that as well

**Review by martin-majlis-s1 — APPROVED** [review]
LGTM

**Comment by martin-majlis-s1** [comment]
@zdaratom-s1 / @zdaratom : It looks to me, that you still should run `make generate` to regenerate that README.md file.

**Review by tomaz-s1 — APPROVED** [review]

**Comment by atoulme** [comment]
Please change exporter/datasetexporter/metadata.yaml.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
