### PR TITLE
[chore] update swiatekm-sumo to swiatekm

### PR DESCRIPTION
**Pull request by codeboten**
@swiatekm please review :)

### CODE REVIEW

**Comment by codeboten** [comment]
Found by owners check:

```
Run GITHUB_TOKEN=*** make gengithub
cd cmd/githubgen && go install .
githubgen
2024/07/04 13:49:02 codeowners are not members: swiatekm-sumo
make: *** [Makefile:296: gengithub] Error 1
Error: Process completed with exit code 2.
```

**Review by swiatekm — CHANGES_REQUESTED** [review]
I'm not at Sumo Logic anymore, so I should really just be removed from these components. Apologies for not submitting a PR immediately after changing my username - I can see how the current state might lead to confusion. I can do that right now, and we can close this PR, if that's ok with you @codeboten .

**Comment by codeboten** [comment]
@swiatekm sure! that works. just link you're pr here and we can close this one

**Review by sumo-drosiek — APPROVED** [review]

**Review by sumo-drosiek — CHANGES_REQUESTED** [review]
Just in case 😅

**Review by fatsheep9146 — APPROVED** [review]

**Comment by codeboten** [comment]
This has been replaced by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33931

**Pull request closed without merging**
