### PR TITLE
[exporter/influxdb] Update README.md to explain URL path behavior

### PR DESCRIPTION
**Pull request by clarkington3**
**Description:** Updated the documentation of the mandatory endpoint parameter to clarify the behavior when no path (or root path) is specified as the example doesn't include a path and the resulting behavior in that scenario (insertion of path /api/v2/write) can be surprising. Additionally, updated endpoint description to note HTTP or HTTPS can be used (as example and documentation only referenced HTTP).

**Link to tracking Issue:** N/A

**Testing:** Confirmed behavior continues to work consistently - nothing is broken, merely documenting functionality a little more explicitly.

**Documentation:** Made two changes to README.md file to add information on endpoint URL path functionality and that endpoint supports both HTTP and HTTPS.

### CODE REVIEW

**Comment by djaglowski** [comment]
@clarkington3, thank you for the contribution. Please sign the CLA

**Comment by clarkington3** [comment]
> @clarkington3, thank you for the contribution. Please sign the CLA

Done, thanks!

**Comment by djaglowski** [comment]
@jacobmarble, please review as code owner

**Comment by djaglowski** [comment]
@jacobmarble, please review as code owner

**Comment by clarkington3** [comment]
@djaglowski Is it possible to get someone else to review my documentation change?

**Comment by djaglowski** [comment]
@clarkington3, let's give the code owner 2 more weeks. If this has not been reviewed, we will mark it as an [unmaintained component](https://github.com/open-telemetry/opentelemetry-collector#unmaintained).

cc @jacobmarble

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
