### PR TITLE
[processor/metricstransformprocessor] Add operation for conversion of camel case metric names to snake case

### PR DESCRIPTION
**Pull request by clarkjohnd**
**Description:** <Describe what has changed.>

Have added an operation to the metrics transform processor which allows metric names to be converted from camel case to snake case (e.g. `CurrentCPUUtilization` -> `current_cpu_utilization`) in line with common naming conventions of metrics.

```yaml
# convert all camel case metric names to snake case: e.g. MyMetric -> my_metric
include: (.*)
match_type: regexp
action: update
operations:
  - action: case_convert
```

Other parameters in `operations` elements have no effect on the operation.

AWS CloudWatch Metric Streams output metrics (into OpenTelemetry Collector) with camel case names, so this feature helps to normalize the names, particularly into the same standard as Prometheus metric names. There will also be other use cases and metrics providers this may help with, but admittedly this is somewhat of a rare problem being solved.

The feature has no effect on metrics already named appropriately (`current.cpu.utilization`, `current_cpu_utilization` etc.) so using a ".*" regex include with this operation should be safe, but not sure of performance implications if any, so may be wise if using with a catch-all to use with a specific collector pipeline expecting mostly camel case metrics etc., rather than a part of a pipeline where every single metric flows through and gets analysed.

No effect on any other existing feature or implications on collectors being upgraded.

**Testing:** <Describe what testing was performed and which tests were added.>

A development docker image with this feature was built from the branch and deployed into my test environment (replacing the production OpenTelemetry Colllector currently in place) currently receiving said AWS CloudWatch metrics with `include` set to `".*"` and once the configuration was updated as above, it immediately started converting them as expected to snake case, with no effect on other metrics that are already named appropriately.

Various test cases added to the code, including handling wildcard regex, strict include, already-snake-case, multiple uppercase characters etc. metric names.

**Documentation:** <Describe the documentation added.>

README has been updated with a description of the feature and an example.

### CODE REVIEW

**Comment by clarkjohnd** [comment]
Bumping this @dmitryax @Aneurysm9 , any feedback etc.? Thanks.

**Comment by TylerHelmuth** [comment]
@Aneurysm9 yes this would be a great use case for the transform processor because it is focus on changing the metric name itself and not more complicated data transformations.  The function to switch case could be implemented now and could be used within the transform processor to change metric names.

**Comment by clarkjohnd** [comment]
I can look to migrate this over to transform processor instead then if we're happy with that route @TylerHelmuth @Aneurysm9

**Comment by TylerHelmuth** [comment]
@clarkjohnd yes please!

**Comment by clarkjohnd** [comment]
Superseded by #16070 - migrated to transform processor.

**Pull request closed without merging**
