### PR TITLE
[processor/transformprocessor] Transform processor metric function to convert names to snake case

### PR DESCRIPTION
**Pull request by clarkjohnd**
**Description:** <Describe what has changed.>

Based off of #15379, ported from `metricstransformprocessor` to `transformprocessor`. Tested in real environment with the same outcome as previous PR. @dmitryax @Aneurysm9 @TylerHelmuth 

Have added an operation to the transform processor which allows metric names to be converted from camel case to snake case (e.g. `CurrentCPUUtilization` -> `current_cpu_utilization`) in line with common naming conventions of metrics.

```yaml
# convert all camel case metric names to snake case: e.g. MyMetric -> my_metric
transform:
  metrics:
    statements:
      - convert_camel_case_to_snake_case()
```

Works with `where` filters and all metric types as expected.

AWS CloudWatch Metric Streams output metrics (into OpenTelemetry Collector) with camel case names, so this feature helps to normalize the names, particularly into the same standard as Prometheus metric names. There will also be other use cases and metrics providers this may help with, but admittedly this is somewhat of a rare problem being solved.

The feature has no effect on metrics already named appropriately (`current.cpu.utilization`, `current_cpu_utilization` etc.) so using a catch-all with this operation should be safe, but not sure of performance implications if any, so may be wise if using with a catch-all to use with a specific collector pipeline expecting mostly camel case metrics etc., rather than a part of a pipeline where every single metric flows through and gets analysed.

No effect on any other existing feature or implications on collectors being upgraded.

**Testing:** <Describe what testing was performed and which tests were added.>

A development docker image with this feature was built from the branch and deployed into my test environment (replacing the production OpenTelemetry Collector currently in place) currently receiving said AWS CloudWatch metrics without a `where` filter (so catching all metrics in the pipeline), and once the configuration was updated as above, it immediately started converting them as expected to snake case, with no effect on other metrics that are already named appropriately.

Various test cases added to the code (no op, simple change, multi-uppercase, use of hyphens).

**Documentation:** <Describe the documentation added.>

README has been updated with a description of the feature and an example.

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
@clarkjohnd thanks for switching this into the transformprocessor. 

I think this function is generic enough that it can live in pkg/OTTL and be used in the transform processor. Since we already have a "set" function I think this can be a function that takes a string and spits out snake case (or it can be generic to spot out any case). Then it can be used in combination with "set". 

It'll follow a similar patter to the other Factory Functions like Concat or Int. 

Does that make sense?

**Comment by dmitryax** [comment]
I agree with @TylerHelmuth . It's hard to justify introducing such function because the use case is too specific and not related to OTel standards where we use dots to separate words. I wish this can be achieved with regexp substitution, so we can just enhance `set` function to support regexp in some way.

**Comment by clarkjohnd** [comment]
@TylerHelmuth @dmitryax Thanks for feedback. Just to be clear, are you suggesting I move the convert case function code to `ottlfuncs` and then import it into `transformprocessor` to be used as a function inside `set` so it can be used on any string parameter (names, resource attributes etc.)?

I've got a new dev branch as described above working (yet to build and deploy into a pipeline to properly test) where I've:

- Made a new `ConvertToSnakeCase` function inside `ottlfuncs` (string in, string out)
- Importing this as a common function into `transformprocessor` along with `Concat` etc.
- Used `ConvertToSnakeCase` inside a `set` operation test case within `transformprocessor` like below:

`set(metric.name, ConvertToSnakeCase(metric.name)) where metric.name == "operationA"`

The above changes `metric.name` from `operationA` to `operation.a` successfully (having switched `_` for `.` as I should have done previously). What do you think?

**Comment by dmitryax** [comment]
@clarkjohnd Thanks for the update, that is a much better approach. Just one concern:

> set(metric.name, ConvertToSnakeCase(metric.name)) where metric.name == "operationA"

> The above changes metric.name from operationA to operation.a successfully (having switched _ for . as I should have done previously). What do you think?

The name and behavior don't mach now :) I'd say it's probably better to keep the name and `_` instead of `.`. Dots in OTel have special meaning and cannot be always used as word separators, so `_` probably a better choice given that we don't touch existing `.` in the word.

**Comment by TylerHelmuth** [comment]
> `set(metric.name, ConvertToSnakeCase(metric.name)) where metric.name == "operationA"`

@clarkjohnd this is perfect.  Looking at things, I'm starting to feel stronger about making this a generic function that can handle different types of case changes. We can stick with just implementing "snake" for now, but it'll open things up for "upper" or "lower" as well in the future.  How do you feel about:

`set(metric.name, ConvertCase(metric.name, "snake")) where metric.name == "operationA"`

It would be great for `"snake"` to be an enum, but we don't have a way yet for functions to add enum symbols to a context so lets stick with string for now.

**Comment by clarkjohnd** [comment]
@dmitryax No problem, will change it back!

@TylerHelmuth Good idea, will change it to that, I can do `upper` and `lower` while I'm here if desired. For convention is this better to do over 2 separate PRs - one for ottl and one for transformprocessor? Cheers

**Comment by TylerHelmuth** [comment]
> For convention is this better to do over 2 separate PRs - one for ottl and one for transformprocessor?


@clarkjohnd ya it's normally done that way.

**Pull request closed without merging**
