### PR TITLE
482 add support for taskdefinitionfamily placeholder on log stream name

### PR DESCRIPTION
**Pull request by aateeqi**
**Description:** 
Add TaskDefinitionFamily placeholder support for log stream naming in awsemfexporter

**Link to tracking Issue:**
aws-observability/aws-otel-collector#482

**Testing:** 
Added test case that sets log stream name to {TaskId}-{TaskDefinitionFamily} (as desired in issue 482)

**Documentation:** 
Included TaskDefinitionFamily placeholder usage in README

### CODE REVIEW

**Comment by aateeqi** [comment]
@hossain-rayhan would you be able to take a look at this?

**Review by hossain-rayhan — COMMENTED** [review]
Looks good. Can we add another unit test with `aws.ecs.task.family`?

**Review by hossain-rayhan — APPROVED** [review]
LGTM. Thanks.

**Comment by aateeqi** [comment]
@anuraaga Could you take another look at this?

**Review by hossain-rayhan — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]

**Pull request merged**
