### PR TITLE
Upgrade to latest core, fix deprecate usages

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by dmitryax** [comment]
Looks like the tests are still failing

**Comment by dmitryax** [comment]
Did we add a few dependancies in core that causes 20k+ in `go.sum` changeset here?

**Comment by bogdandrutu** [comment]
@dmitryax not that I know of, (jsoniter should have been there from traces, but not sure why now changed).

**Review by dmitryax — APPROVED** [review]
LGTM

**Pull request merged**
