### PR TITLE
Remove anuraaga from transformprocessor reviewers

### PR DESCRIPTION
**Pull request by anuraaga**
Since not in org

### CODE REVIEW

**Comment by anuraaga** [comment]
@jmacd You're right - removed the text

**Comment by TylerHelmuth** [comment]
@anuraaga I added you as a code owner for the telemetryquerylanguage package. Are you stepping down from that as well?

**Comment by anuraaga** [comment]
@TylerHelmuth Yes thanks for reminding. Got a high fever today so will update after it dies down

**Review by TylerHelmuth — APPROVED** [review]
Thanks for all your contributions!

**Review by codeboten — APPROVED** [review]

**Pull request merged**
