### PR TITLE
Initial draft of sysdig exporter

### PR DESCRIPTION
**Pull request by mms2409**

### CODE REVIEW

**Comment by dmitryax** [comment]
Hi @mms2409 . Please follow the adding new component guidelines https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

**Comment by mms2409** [comment]
@dmitryax Is there a way to create a distribution image from this unmerged PR?

**Comment by dmitryax** [comment]
> Is there a way to create a distribution image from this unmerged PR?

Not in OTel, you can make a custom build yourself

**Comment by MovieStoreGuy** [comment]
Please sign the CLA.

**Pull request closed without merging**
