### PR TITLE
[exporter/prometheus] clean up expired metrics on Accumulate()

### PR DESCRIPTION
**Pull request by fabiokung**
Before this change, `prometheusexporter` only removed expired metrics during `Collect()`, which can cause a memory leak when nothing is scraping the prometheus handler.

This change allows GC to happen periodically (controlled by the `metric_expiration` config) during `Accumulate()` as well, so memory won't leak in case nothing hits the prom handler, and we have a chance to clean up expired metrics as memory usage grows.

----

We have a use case where metrics are being frequently scraped (by a `prometheusreceiver`) into a `prometheusexporter` handler that is only rarely hit. In that case, we saw memory leak unbounded, and investigation led to `pmetric` objects being held by the exporter, as shown by the pprof/heap snippet below:

prom-otel-leak

### CODE REVIEW

**Comment by fabiokung** [comment]
ping @dmitryax @gouthamve to get some eyes

**Comment by mx-psi** [comment]
@dmitryax @gouthamve @Aneurysm9 @dashpole PTAL!

**Review by dashpole — COMMENTED** [review]
Is there a way to unit test this?

**Pull request closed without merging**
