### PR TITLE
Google Cloud Spanner Receiver: added transaction tag label to metadata config for top transaction stats.

### PR DESCRIPTION
**Pull request by ydrozhdzhal**
Added exporting of **transaction_tag** column value as **transaction_tag** label for top transaction stats metrics.

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Shouldn't there be a change in the tests as well?

**Comment by ydrozhdzhal** [comment]
> Shouldn't there be a change in the tests as well?

No, tests on metadata config functionality and metadata config parsing are already there. Also there is sanity check test for loading and constructing metadata for existing config.

**Review by jpkrohling — APPROVED** [review]

**Review by kostia-hospodarysko — APPROVED** [review]

**Comment by ydrozhdzhal** [comment]
@jpkrohling , somewhy some jobs were cancelled.

**Comment by jpkrohling** [comment]
Don't worry, they are skipped for PRs, IIRC.

**Pull request merged**
