### PR TITLE
[chore] Remove haproxy from receivers list test

### PR DESCRIPTION
**Pull request by dmitryax**
To fix https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3708704666/jobs/6286642456

Another change towards unblocking CI https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17037

### CODE REVIEW

**Comment by MovieStoreGuy** [comment]
Should we be added a receiver that is not yet complete into the components?

**Comment by dmitryax** [comment]
Hm... you're right, the receiver doesn't do anything at this point. let me exclude it

**Comment by dmitryax** [comment]
@MovieStoreGuy, removed it for the receivers test list

cc @atoulme

**Review by atoulme — APPROVED** [review]
LGTM

**Review by MovieStoreGuy — APPROVED** [review]

**Pull request merged**
