### PR TITLE
[receiver/filelog] Promote component to beta

### PR DESCRIPTION
**Pull request by djaglowski**
This is a proposal to move `filelogreceiver` to beta status.

I believe this receiver is sufficiently stable, that it has been extensively used in many real world workloads, and that there are no breaking changes expected.

There are two points in particular that I would like to discuss to ensure other stakeholders are in agreement.
1. Batching. The receiver reads log entries one at a time, but emits them in batches because it has some performance benefits. This is not strictly necessary and I can image there is a case to be made against it. If this were to be removed, it would require removal of the associated configuration section. My opinion is that this should stay, but if there are objections I would appreciate hearing them now.
2. Operators. There is an intention to enhance the `transformprocessor` with functionality equivalent to the `pkg/stanza` operators. While this would provide an alternative approach to parsing logs, I do not believe it invalidates the rationale for keeping operators in the receiver. The main reason to embed these operators is that it empowers the receiver to meaningfully interpret logs _into the OTel data model_. Resource attributes, scope, severity, timestamp, etc, are commonly extracted at the time of ingest. I believe this is appropriate and that users naturally expect that the receiver can be configured to represent their logs according to the OTel data model.

2a. Operator stability. It is worth noting that their stability is directly relevant to the stability of the receiver, assuming they are not removed. While there are no anticipated breaking changes to operators, I believe that the operator framework provides a reasonable escape hatch for the case where a breaking change is necessary. Specifically, an existing operator can be forked, corrected, and made available as a new operator.

### CODE REVIEW

**Comment by djaglowski** [comment]
cc/ @dmitryax @bogdandrutu @tigrannajaryan @atoulme @dineshg13

**Comment by tigrannajaryan** [comment]
> 1. Batching. The receiver reads log entries one at a time, but emits them in batches because it has some performance benefits. This is not strictly necessary and I can image there is a case to be made against it. If this were to be removed, it would require removal of the associated configuration section. My opinion is that this should stay, but if there are objections I would appreciate hearing them now.

If we are not certain then perhaps keep batching behavior but remove the config option so that we are free to change it in the future? What controls it? Is it `force_flush_period`?

**Comment by tigrannajaryan** [comment]
>The main reason to embed these operators is that it empowers the receiver to meaningfully interpret logs into the OTel data model. Resource attributes, scope, severity, timestamp, etc, are commonly extracted at the time of ingest. I believe this is appropriate and that users naturally expect that the receiver can be configured to represent their logs according to the OTel data model.

I have the same opinion. This also allows creating self-contained receiver definitions that know how to get the logs from a particular 3rd party log file and transform it into Otel log data model. These self-contained receiver definitions can become includable snippets of configuration that we put in a repository of "plugins".

**Comment by tigrannajaryan** [comment]
>Operator stability. It is worth noting that their stability is directly relevant to the stability of the receiver, assuming they are not removed. While there are no anticipated breaking changes to operators, I believe that the operator framework provides a reasonable escape hatch for the case where a breaking change is necessary. Specifically, an existing operator can be forked, corrected, and made available as a new operator.

Presumably this is what may happen if we want to consolidate similar operators with the proposed flex metric receiver. I think this is not a problem. We can introduce new operators and deprecate old ones if necessary.

**Comment by dmitryax** [comment]
> 2a. Operator stability. It is worth noting that their stability is directly relevant to the stability of the receiver, assuming they are not removed. While there are no anticipated breaking changes to operators, I believe that the operator framework provides a reasonable escape hatch for the case where a breaking change is necessary. Specifically, an existing operator can be forked, corrected, and made available as a new operator.

Are all the operators listed in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/stanza/docs/operators available for use in the filelog receiver? Do we really need all of them to support the configuration interface going forward? For example I'm not sure why we need `stdin` or `stdout` operators. Maybe we can declare stability levels for the operators separately from the receivers? Especially given that they can be used in different receivers...

**Comment by TylerHelmuth** [comment]
> I'm not sure why we need stdin or stdout operators.

These have been requested by users in the past to help debug their filelog receiver config.

**Comment by atoulme** [comment]
Reference to a request to enable stdin/stdout operators: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13758

**Comment by dineshg13** [comment]
I have used filelog receiver for testing Otel logs support at Datadog , you can see some config i had to do for opentelemetry-demo application here, https://github.com/DataDog/opentelemetry-helm-charts/blob/92f3484f60c3d084f79a2658f14bfc06b67679ef/charts/opentelemetry-demo-datadog/otelcol-config.yaml#L40 .  

 I think we should simplify the operators, it took quite some effort to set them . I believe there are 3 operators which every filelogreciever should do by default 
* traceparser
* serverity_parser
* timestamp_parser
For example if there is json log, with serverity , we should be able to parse it without user configuring the parsing. This would simplify adoption of this filelogreceiver. Let me know your thoughts. I can open issue and work on it as well.

**Comment by djaglowski** [comment]
> Are all the operators listed in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/stanza/docs/operators available for use in the filelog receiver? Do we really need all of them to support the configuration interface going forward? For example I'm not sure why we need `stdin` or `stdout` operators. 
The list of operators available to filelog is defined [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/adapter/register.go).

As others have noted, `stdout` is useful for troubleshooting configs. `file` is there for the same reason.

I don't think `stdin` is actually used, so that could be removed. In any case, this one is not available to filelog.

> Maybe we can declare stability levels for the operators separately from the receivers? Especially given that they can be used in different receivers...

I'm not opposed to that, but it would complicate things. Would this limit filelog's stability level, or would we consider them independent to the extent that filelog can be beta while some operators are alpha?

**Comment by djaglowski** [comment]
> I believe there are 3 operators which every filelogreciever should do by default
> 
> * traceparser
> * serverity_parser
> * timestamp_parser
>   For example if there is json log, with serverity , we should be able to parse it without user configuring the parsing. This would simplify adoption of this filelogreceiver. Let me know your thoughts. I can open issue and work on it as well.

I disagree. I think explicit configuration is preferable. Inference as to what parsing is appropriate in a generic receiver is likely to cause unexpected behaviors. 

That said, feel free to propose a detailed solution. However, I think any inference capabilities should be disabled by default, so this would not be a breaking change.

**Comment by atoulme** [comment]
In my opinion, this component is ready to be marked as beta. It is used extensively by our helm chart solution, has been field tested successfully with many users, and supports production workloads.

**Comment by tigrannajaryan** [comment]
I support marking it beta, ideally after we hide some of the config options that we are not certain will stay.

**Comment by TylerHelmuth** [comment]
It is also being used directly by the open-telemetry/opentelemetry-collector helm chart.

**Comment by djaglowski** [comment]
Here is the PR that would remove converter configuration: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15696

**Comment by atoulme** [comment]
#15696 is merged - can we merge this PR?

**Comment by djaglowski** [comment]
@tigrannajaryan, @dmitryax, I believe this is ready to go. Please take a look.

**Review by tigrannajaryan — APPROVED** [review]

**Review by dineshg13 — APPROVED** [review]
Agree this is good to beta. We have been running in prod in k8s for a while

**Comment by astencel-sumo** [comment]
> > If we are not certain then perhaps keep batching behavior but remove the config option so that we are free to change it in the future?
> 
> That might be the right approach. @pmalek-sumo, any thoughts on this?

Sadly Patryk Małek is no longer with Sumo Logic. I know I'm late to this party, but I'm just going to say I support marking Filelog receiver as beta. Sumo Logic has been using it successfully in production (in Kubernetes) for a couple months now. Also, we never had the need to use the `converter` configuration option. :slightly_smiling_face:

**Review by andrzej-stencel — APPROVED** [review]

**Comment by djaglowski** [comment]
@dmitryax, it would be nice to have your approval on this too if you want to review it.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by dmitryax** [comment]
I'm good with marking it as beta. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filelogreceiver/filelog.go#L28 should be updated as well

**Review by dmitryax — APPROVED** [review]

**Comment by matthewmodestino** [comment]
Glad to see logs moving forward!

One item I wanted to point out on the operator support side is the extreme importance of the `recombine` operator in providing multiline log parsing support for customers, which is likely the biggest feature request made by anyone dealing with logs in kubernetes.

Also after helping many customers deploy otel native logging, the operators are very attractive feature in allowing them some pre-parsing ability prior to sending to a backend. 

I would definitely recommend they are kept.

**Pull request merged**
