### PR TITLE
[receiver/solacereceiver] Added publish topic as attribute on propagated spans

### PR DESCRIPTION
**Pull request by mcardy**
**Description:** Added a new attribute `messaging.destination` to the receiver's propagated traces

**Link to tracking Issue:** None

**Testing:** Unit tests updated

**Documentation:** No required changes

@djaglowski FYI 😄

### CODE REVIEW

**Comment by djaglowski** [comment]
@mcardy, I seem to have missed this one. It looks like you'll need to rebase in order to pick up some CI fixes.

**Comment by mcardy** [comment]
@djaglowski I've rebased. I noticed that the changelog job failed since I don't have an associated issue. Should I just open an issue describing the enhancement?

**Comment by djaglowski** [comment]
@mcardy, you can use the PR # instead.

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
Added a new attribute messaging.destination to the receiver's propagated traces

**Pull request merged**
