### PR TITLE
[exporter/elasticsearch] fix lint for exporter/elasticsearch

### PR DESCRIPTION
**Pull request by fatsheep9146**
Signed-off-by: Ziqi Zhao <zhaoziqi9146@gmail.com>

**Description:** <Describe what has changed.>
fix errcheck issue for exporter/elasticsearch

**Link to tracking Issue:** <Issue number if applicable>
#9749

### CODE REVIEW

**Comment by djaglowski** [comment]
Code owners @urso, @faec, @blakerouse, please review.

**Comment by fatsheep9146** [comment]
@djaglowski @mx-psi could you help remove the stale label？

**Comment by djaglowski** [comment]
Code owners @urso, @faec, @blakerouse, please review.

**Comment by jpkrohling** [comment]
Code owners, second ping: @urso, @faec, @blakerouse

**Comment by djaglowski** [comment]
Code owners @urso, @faec, @blakerouse, please review.

**Comment by JaredTan95** [comment]
@djaglowski @jpkrohling pls help add `skip changelog` :-P

**Comment by djaglowski** [comment]
Please fix lint errors. Otherwise, this lgtm.

**Review by djaglowski — APPROVED** [review]

**Review by JaredTan95 — APPROVED** [review]

**Pull request merged**
