### PR TITLE
[exporter/azuremonitor] map enduser.id to UserID tag

### PR DESCRIPTION
**Pull request by bschoenmaeckers**
**Description:** <Describe what has changed.>
The official exporters made by Microsoft map enduser.id to azure's anonymous user id tag. The collector exporter should do the same thing.

[Java exporter](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java#L800-L805)
[Python exporter](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/trace/_exporter.py#L127-L128)

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>
I have added the optional attribute to some tests to make sure everything works.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
Changes look good. Please add a changelog entry and we're good to go.

**Comment by bschoenmaeckers** [comment]
I've added the changelog. Should be good to go now!

**Review by codeboten — COMMENTED** [review]
Pinging code owner @pcwiese

**Comment by codeboten** [comment]
One more ping to code owner @pcwiese, please review this PR so we can get this merged

**Comment by bschoenmaeckers** [comment]
Is there someone else who can review? Thanks in advance!

**Review by pcwiese — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
@bschoenmaeckers yes! Thanks for the reminder, i'd missed the review from the code owner. Cheers!

**Pull request merged**
