### PR TITLE
[exporter/humioexporter] remove deprecated humioexporter

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Remove the deprecated humio exporter.
**Link to tracking Issue:**
#17013

### CODE REVIEW

**Comment by dmitryax** [comment]
Has it been deprecated for more than 2 releases? Please see https://github.com/open-telemetry/opentelemetry-collector#deprecated

**Comment by atoulme** [comment]
No, just one. We can merge after 0.69.0 is out.

**Comment by atoulme** [comment]
Rebased after 0.69.0 release.

**Comment by dmitryax** [comment]
@xitric PTAL as a code owner

**Comment by djaglowski** [comment]
@Xitric, it appears you've already acknowledged this change [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17013#issuecomment-1349590167). It be great to have your direct approval as well before we finalize this.

As this PR has been open for two weeks already, I suggest we give just a couple more days and then move forward with it either way.

**Review by bogdandrutu — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please rebase

**Comment by atoulme** [comment]
@codeboten done

**Pull request merged**
