### PR TITLE
[chore] use multimod sync to update otel core

### PR DESCRIPTION
**Pull request by codeboten**
This will reduce the amount of time spent updating core at release time

### CODE REVIEW

**Comment by codeboten** [comment]
This is in draft until https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/422 is merged

**Review by dmitryax — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]
`$(MULITMOD)` :sweat_smile:

**Comment by codeboten** [comment]
not stale, waiting for update of prom dependency before this can move forward

**Comment by codeboten** [comment]
this can be unblocked on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29314 is merged

**Pull request merged**
