### PR TITLE
[extension/bearertokenauthextension] Fix typo in README

### PR DESCRIPTION
**Pull request by PaulBernier**
**Description:** <Describe what has changed.>

The Bearer token auth extension is to be used with exporters, not receivers

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by PaulBernier** [comment]
Waiting on Slunk's CLA manager to approve my request

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Will be merged once CLA is signed

**Review by codeboten — APPROVED** [review]

**Comment by PaulBernier** [comment]
Closing this MR that was committed with my personal email address and cannot receive CLA approval.
I have recreated it with a corporate commit here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17016
Sorry for the trouble

**Pull request closed without merging**
