### PR TITLE
[pkg/stanza] fix collector start fail with '--feature-gates=logs.json…

### PR DESCRIPTION
**Pull request by ahern-pro**
**Description:** <Describe what has changed.>
fix bug: collector start fail with '--feature-gates=logs.jsonParserArray'
how to fix: add Gate.featureGateEnableFunc, called when --feature-gates registered

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32313

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by li-zeyuan** [comment]
depend on：https://github.com/open-telemetry/opentelemetry-collector/pull/9964

**Comment by djaglowski** [comment]
Thanks @li-zeyuan. I've approved CI on both PRs.

Hopefully https://github.com/open-telemetry/opentelemetry-collector/pull/9964 can be merged quickly but if not we can look at registering always and then failing later. It's not ideal though so I appreciate the effort to fix this in the featuregate package.

**Comment by li-zeyuan** [comment]
> Thanks @li-zeyuan. I've approved CI on both PRs.
> 
> Hopefully [open-telemetry/opentelemetry-collector#9964](https://github.com/open-telemetry/opentelemetry-collector/pull/9964) can be merged quickly but if not we can look at registering always and then failing later. It's not ideal though so I appreciate the effort to fix this in the featuregate package.

https://github.com/open-telemetry/opentelemetry-collector/pull/9964 It's backward compatible

After the merger of https://github.com/open-telemetry/opentelemetry-collector/pull/9964 is successful, I will modify the version of 'go.opentelemetry.io/collector/featuregate' in go.mod. Is that okay?

**Comment by djaglowski** [comment]
> > Thanks @li-zeyuan. I've approved CI on both PRs.
> > Hopefully [open-telemetry/opentelemetry-collector#9964](https://github.com/open-telemetry/opentelemetry-collector/pull/9964) can be merged quickly but if not we can look at registering always and then failing later. It's not ideal though so I appreciate the effort to fix this in the featuregate package.
> 
> [open-telemetry/opentelemetry-collector#9964](https://github.com/open-telemetry/opentelemetry-collector/pull/9964) It's backward compatible
> 
> After the merger of [open-telemetry/opentelemetry-collector#9964](https://github.com/open-telemetry/opentelemetry-collector/pull/9964) is successful, I will modify the version of 'go.opentelemetry.io/collector/featuregate' in go.mod. Is that okay?

This change doesn't work without https://github.com/open-telemetry/opentelemetry-collector/pull/9964 so backwards compatibility isn't a concern. I think likely we can get that one merged quickly though.

**Comment by li-zeyuan** [comment]
@djaglowski 
Sorry, I thought of another implementation method, resubmit a MR

**Pull request closed without merging**
