### PR TITLE
Moving fluentextension to contrib repo.

### PR DESCRIPTION
**Pull request by evkuzin**
**Description:** Fluentbit Extension migration from the core to the contrib repo

**Link to tracking Issue:** [2674](https://github.com/open-telemetry/opentelemetry-collector/issues/2674)

**Testing:** whole fluent bit extension without changes was moved. All tests succeed locally

### CODE REVIEW

**Comment by evkuzin** [comment]
@bogdandrutu Any idea why lint failed? I cannot get it. And should I add additional tests to pass code coverage?

**Comment by evkuzin** [comment]
Maybe I'm wrong, but it looks like at first we have to make modules from these packages:
```	
"go.opentelemetry.io/collector/component/componenttest"
"go.opentelemetry.io/collector/config/configmodels"
"go.opentelemetry.io/collector/config/configtest"
```

**Comment by evkuzin** [comment]
Only windows tests are failing. AFAIK Windows could restrict ports for some reasons

```shell
netsh interface ipv4 show excludedportrange protocol=tcp
```

could provide more info. Probably thats the reason for failing windows tests

**Review by bogdandrutu — APPROVED** [review]

**Comment by evkuzin** [comment]
@bogdandrutu Thank you for checking it out on a weekend man!
But it still blocked by codecov :(

**Pull request merged**
