### PR TITLE
add skywalking receiver metric

### PR DESCRIPTION
**Pull request by maokitty**
**Description:** <Describe what has changed.>

**Link to tracking Issue:** [27832](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27832)

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by JaredTan95 — APPROVED** [review]
thx, LGTM

**Comment by maokitty** [comment]
Looking forward to your review @dmitryax

**Comment by JaredTan95** [comment]
@maokitty can you resolve conflicts?

**Comment by JaredTan95** [comment]
@maokitty pls resolve conflicts :-P

**Comment by maokitty** [comment]
I am creating a new PR here, sorry for the late update. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30076

**Pull request closed without merging**
