### PR TITLE
Add isNaN function

### LINKED ISSUE #28591: [pkg/ottl] Add IsNaN Converter
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

OTTL has no way to check if a double value is `NaN`. https://pkg.go.dev/math#IsNaN

### Describe the solution you'd like

Add a new Converter, IsNaN that returns true if the given value is NaN. It should return false if the value is not a double. 

The implementing PR should

- [ ] Implement the function
- [ ] Add new unit tests for the function
- [ ] Add the function to pkg/ottl/ottlfuncs/functions.go
- [ ] Update the README at pkg/ottl/ottlfuncs/README.md

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lkwronski**
**Description:** Adds a new IsNaN function to facilitate type checking.

**Link to tracking Issue:** Fixes #28591

**Testing:** Added unit test

**Documentation:** Updated the func readme.

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
LGTM

**Comment by lkwronski** [comment]
I just did a rebase. PR is ready to be merged.

**Comment by atoulme** [comment]
@TylerHelmuth @bogdandrutu @evan-bradley @kentquirk please review

**Review by TylerHelmuth — COMMENTED** [review]
I'd like to re-review if this function is actually useful. I've been trying to think of ways we could end up with `NaN` and haven't come up with any yet.

@lkwronski can you add some e2e tests in `pkg/ottl/e2e` that test this function returning true and false?

**Comment by lkwronski** [comment]
After your doubts @TylerHelmuth , I also don't see how this feature is useful, at least for now. For me, it is fine to close this PR and ticket by rejecting them. I can start working on something else.

**Pull request closed without merging**
