### PR TITLE
[pkg/ottl] Rename ottllogs to ottllog

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
Renames `ottllogs` to `ottllog` to align with singular contexts

**Testing:**
Unit Tests

**Documentation:**
Updated READMEs

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
ottllog seems hard to type, since it's already under ottl/context why not call this package `log`? Or would that cause too many naming conflicts?

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
>ottllog seems hard to type, since it's already under ottl/context why not call this package log? Or would that cause too many naming conflicts? 

We prefix this everywhere, good question if we should not.

**Comment by TylerHelmuth** [comment]
@codeboten with the way the package is structured I _think_ if we named the package `log` then the default reference would be `log.<something in the package>` right?  Users would have to do a named import every time to avoid any conflicts.

**Review by evan-bradley — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
I'm ok with the change as is, though it still seems like the ergonomics of using the package need a bit more thinking. I agree that `log`, `span`, `datapoint`... would likely end up with conflicts, just not sure that prefixing with `ottl` is the right solution

**Comment by bogdandrutu** [comment]
needs rebase

**Review by kovrus — APPROVED** [review]

**Pull request merged**
