### PR TITLE
[receiver/dockerstats] Change cpu utilization metric

### PR DESCRIPTION
**Pull request by carlossscastro**
**Description:**
This change starts the process for deprecating the metric `container.cpu.percent` in favor of `container.cpu.utilization` to adhere to semantic convention.
New metric naming is under a feature-gate that can be enabled with:
```
./otelcontribcol --feature-gates=+receiver.dockerstats.changeCpuUtilization
```

**Link to tracking Issue:** #21807

**Testing:** 
```
❯ go clean -testcache
❯ make test
go test -race -timeout 300s -parallel 4 --tags="" ./...
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver	0.829s
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver/internal/metadata	0.375s
❯ go test --tags integration ./...
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver	9.873s
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver/internal/metadata	0.235s
```

**Documentation:** 
Metrics documentation was updated using `mdatagen`

### CODE REVIEW

**Comment by astencel-sumo** [comment]
@carlossscastro sorry I should have thought about this and mentioned this before: with a metric name change like this, we should be able to get away without a feature gate, instead using the regular metric enabling/disabling capabilities and a description of the deprecation in the README file. See similar issue and PRs in the Host Metrics receiver:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14327
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14927
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17276
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18531

Do you think we can do it this way? Again, very sorry for bringing this up after you implemented the feature gate. :worried:

**Comment by carlossscastro** [comment]
> Do you think we can do it this way? Again, very sorry for bringing this up after you implemented the feature gate. 😟

No problem at all @astencel-sumo. I will work on this and resubmit the PR. Thanks again for the guidance.

**Comment by atoulme** [comment]
@carlossscastro please take a look at the PR, I think you have had a weird push.

**Comment by carlossscastro** [comment]
Resubmitting in a new PR

**Pull request closed without merging**
