### PR TITLE
[receiver/kubeletstats] fix use network io as network errors bug

### PR DESCRIPTION
**Pull request by tianlin**
**Description:** <Describe what has changed.>

fix bug: internal/network.go use network io as network errors
**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14318
**Testing:** <Describe what testing was performed and which tests were added.>
UT
**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by dmitryax** [comment]
@tianlin please sign the CLA.

This change is applied to kubelet reciever, but the issue is submitted for hostmetrics receiver. Please update the PR or crete another relevant issue

**Comment by tianlin** [comment]
> @tianlin please sign the CLA.
> 
> This change is applied to kubelet reciever, but the issue is submitted for hostmetrics receiver. Please update the PR or crete another relevant issue

Done

**Comment by dmitryax** [comment]
Please address the ask in the second paragraph

**Comment by tianlin** [comment]
> Please address the ask in the second paragraph

Do you mean add changelog file under unrelease dir?

**Comment by dmitryax** [comment]
I was able to reproduce the bug and validate the fix. Thank you @tianlin!

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
