### PR TITLE
[chore] [exporter/datasetexporter]: Update dataset-go to 0.14.0

### PR DESCRIPTION
**Pull request by martin-majlis-s1**
**Description:** Upgrade dataset-go from 0.12.1 to 0.14.0

Next release is happening on 2023-08-28 (Monday) - https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md - but next dependant is running on 2023-08-31 (Wednesday) - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/dependabot.yml - so it will not get updated on time.

**Link to tracking Issue:** 
**Testing:** Unit tests are passing

**Documentation:** No documentation was added

### CODE REVIEW

**Review by tomaz-s1 — APPROVED** [review]
LGTM, thanks.

**Comment by tomaz-s1** [comment]
And to clarify why this update is needed / a good idea - latest version of ``dataset-go`` includes some small bug fixes - https://github.com/scalyr/dataset-go/releases (primary one being fix for the internal buffer stats accounting and reporting).

**Review by songy23 — APPROVED** [review]

**Comment by martin-majlis-s1** [comment]
It's failing in the [lint-matrix (other)](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5962553735/job/16174177362?pr=26094) - on some timeout. There is 5 minutes timeout but it runs for 5m12s.

```
...
make -C cmd/oteltestbedcol lint
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/oteltestbedcol'
...
level=info msg="[runner] linters took 5m12.040489591s with stages: goanalysis_metalinter: 5m12.035469399s"
...
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
make[2]: *** [../../Makefile.Common:168: lint] Error 4
```

On my machine it runs for 2 minutes, so I am not surprised that it's above 5 minutes here.


Longer snippet:

...
make -C cmd/oteltestbedcol lint
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/oteltestbedcol'
level=info msg="[linters_context/goanalysis] analyzers took 18m2.665528381s with top 10 stages: buildir: 15m23.633994882s, buildssa: 27.442185081s, nilness: 23.501729877s, exhaustive: 21.21577015s, inspect: 20.68441103s, printf: 9.593619837s, the_only_name: 8.446910563s, ctrlflow: 8.415530453s, fact_purity: 8.295297357s, fact_deprecated: 6.855801831s"
level=info msg="[runner] Issues before processing: 8, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): identifier_marker: 8/8, cgo: 8/8, skip_files: 8/8, exclude: 8/8, exclude-rules: 0/8, filename_unadjuster: 8/8, path_prettifier: 8/8, skip_dirs: 8/8, autogenerated_exclude: 8/8"
level=info msg="[runner] processing took 4.413382ms with stages: autogenerated_exclude: 1.533828ms, identifier_marker: 1.375126ms, path_prettifier: 878.816µs, exclude-rules: 561.91µs, skip_dirs: 47.401µs, cgo: 7.601µs, nolint: 2.1µs, filename_unadjuster: 1.2µs, max_same_issues: 1µs, skip_files: 600ns, sort_results: 500ns, fixer: 500ns, exclude: 400ns, uniq_by_line: 400ns, max_from_linter: 400ns, source_code: 400ns, severity-rules: 400ns, diff: 300ns, path_shortener: 300ns, path_prefixer: 200ns, max_per_file_from_linter: 0s"
level=info msg="[runner] linters took 5m12.040489591s with stages: goanalysis_metalinter: 5m12.035469399s"
level=info msg="File cache stats: 19 entries of total size 39.7KiB"
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
make[2]: *** [../../Makefile.Common:168: lint] Error 4
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/configschema'
make[1]: *** [Makefile:174: cmd/configschema] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by martin-majlis-s1** [comment]
When I check some previous [workflows](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/workflows/build-and-test.yml):
* OK - 4:39, 5m84??? - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5961787911/job/16171714668#step:8:140
* OK - 2:52 / 3:36 - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5963520728/job/16176905185#step:8:128
* Fail - 6:01 - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5964755252/job/16180895102

**Comment by songy23** [comment]
I restarted it, have seen it multiple times and seems it's occurring more frequently recenlty.

**Review by codeboten — APPROVED** [review]

**Comment by martin-majlis-s1** [comment]
@codeboten : Do you think, that it would be possible to merge it before the next release?

**Review by codeboten — COMMENTED** [review]
@martin-majlis-s1 just waiting on CI to pass to get this merged 👍🏻

**Pull request merged**
