### PR TITLE
[pkg/stanza] - Use trie for previous poll readers

### PR DESCRIPTION
**Pull request by VihasMakwana**
**Description:** This is my attempt to use Trie to store readers from previous poll cycles.

### CODE REVIEW

**Comment by VihasMakwana** [comment]
@djaglowski I was thinking, can we constraint our trie to accept only **_comparable_** types? This way it would lead to read-friendly code.

**Comment by VihasMakwana** [comment]
@swiatekm-sumo how would we determine the length of file prefix when re-discover a file in future poll cycles? We do have hashes stored in history, but how would we determine a "match"?

**Comment by VihasMakwana** [comment]
@djaglowski I will add benchmark comparisons in PR descriptions.

**Comment by swiatekm-sumo** [comment]
> I can think of only one way i.e. loop through the array, calculate hash till the previous length and see if there's any match, right? Am I understanding it correctly?

That's the basic idea, yeah. You have a set of old readers from the previous cycle, and those readers have fingerprints with lengths {x, y, z}, ordered by size. So you calculate fingerprints for your new readers up to x, y and z lengths respectively, and compare at each level. This may seem wasteful, but I think it'd be more performant in practice due to:

1. Hashes are calculated iteratively byte-by-byte anyway, so you don't incur any cost for stopping at a particular length.
2. Hashes are actually just int64s, so comparisons are very fast.
3. In the vast majority of cases, the set of lengths will be very small. It's very rare to have a lot of files smaller than the fingerprint size.

Admittedly, I haven't tested this, but I wanted to point out it's an option if we're going down the path of adding a trie just to be able to compare fingeprints more efficiently. Storing the whole fingerprint is an awkward solution to begin with in my opinion, but its primary value is that it's very simple. If we're willing to make it more complex, then we should consider alternatives.

**Comment by VihasMakwana** [comment]
you know what, now that you've pointed this idea I might give it a try and compare results. Thanks for pointing this out.
Alternatively, I can close this PR if you're already planning to work on this. Just let me know!

**Comment by swiatekm-sumo** [comment]
I hadn't started anything, and won't this week, so feel free to give it a shot! I'm cool with this PR staying, though we should probably move this discussion to an issue.

**Pull request closed without merging**
