### PR TITLE
Add region parameter comment

### PR DESCRIPTION
**Pull request by ralongit**
**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please sign the CLA.

**Comment by tigrannajaryan** [comment]
@yyyogev please review.

**Comment by tigrannajaryan** [comment]
> I work with @yyyogev Can you add me as a second codeowner for this exporter? Should I submit a PR somewhere?

@jkowall yes, please submit a PR.

**Comment by jkowall** [comment]
@tigrannajaryan #3156 thx!

**Comment by jkowall** [comment]
Good to merge on this one too, thanks!

**Review by yyyogev — APPROVED** [review]
Awesome! Looks good to me.

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
