### PR TITLE
[chore] update-otel

### PR DESCRIPTION
**Pull request by codeboten**

### CODE REVIEW

**Comment by dmitryax** [comment]
Looks like deprecated `obsreport.NewReceiver` usages need to be replaced

**Comment by dmitryax** [comment]
`TestEndToEndSummarySupport` is failing at least on Windows. Can this be related to upgrade or just flaky one?

**Comment by codeboten** [comment]
> `TestEndToEndSummarySupport` is failing at least on Windows. Can this be related to upgrade or just flaky one?

Looks like the logger is nil in some tests, will fix.

**Comment by codeboten** [comment]
Separated the fix to the prometheus exporter https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16068

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
