### PR TITLE
[receiver/filelogreceiver] Fix testdata parse_from

### PR DESCRIPTION
**Pull request by cdmitri**
**Description:** 

When running the actual `config.yaml` example got errors below. Fixed the references in `config.yaml` to accommodate recent changes. 

**Was:**
...
```
2022-05-12T00:44:51.347Z        error   helper/transformer.go:110       Failed to process entry {"kind": "receiver", "name": "filelog", "operator_id": "regex_parser", "operator_type": "regex_parser", "error": {"description": "time parser: log entry does not have the expected parse_from field", "suggestion": "ensure that all entries forwarded to this parser contain the parse_fro\
m field", "details": {"parse_from": "body.time"}}, "action": "send", "entry": {"observed_timestamp":"2022-05-12T00:44:51.347132293Z","timestamp":"0001-01-01T00:00:00Z","body":"2020-08-25 INFO Something routine","attributes":{"log.file.name":"simple.log","msg":"Something routine","sev":"INFO","time":"2020-08-25"},"severity":0,"scope_name":""}}
```
...
...and...

```
          "logRecords": [
            {
              "observedTimeUnixNano": "1652316291347132293",
              "body": {
                "stringValue": "2020-08-25 INFO Something routine"
              },
```
...

**Now:** no errors and fields are parsed correctly with tests passing.
...
```
          "logRecords": [
            {
              "timeUnixNano": "1598313600000000000",
              "observedTimeUnixNano": "1652316379391504515",
              "severityNumber": "SEVERITY_NUMBER_INFO",
              "severityText": "Info",
              "body": {
                "stringValue": "2020-08-25 INFO Something routine"
              },
```
...

### CODE REVIEW

**Comment by dmitryax** [comment]
@cdmitri thanks for the contribution. Please sign the CLA

**Comment by cdmitri** [comment]
@dmitryax Thanks for letting me know! Signed.

**Comment by pmm-sumo** [comment]
> @dmitryax Thanks for letting me know! Signed.

Hmm, EasyCLA check is still failing. Did you follow the process as [described in contributing guidelines](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md#sign-the-cla) @cdmitri ? Perhaps the code needs to be refreshed for bot to redo the check

**Comment by pmm-sumo** [comment]
The last one is OK but seems the first two commits still need to be fixed :)

**Comment by cdmitri** [comment]
I will reopen, thank you!

**Pull request closed without merging**
