### PR TITLE
Move tailsamplingprocessor to contrib

### LINKED ISSUE #2010: Move the tail-based sampling to contrib
As discussed on Gitter with @tigrannajaryan, we are moving the tail-based sampling processor to contrib, as other components that are critical to it are already there, such as the `groupbytrace` processor and the future `loadbalancing` exporter. This issue is to track this move.

### PR DESCRIPTION
**Pull request by jpkrohling**
**Description:** Completes the move of the tail-based sampling processor to contrib.

**Link to tracking Issue:** Closes open-telemetry/opentelemetry-collector#2010

**Testing:** n/a

**Documentation:** n/a

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This will fail until:

1. #1377 is merged (this will be rebased on top of that)
1. open-telemetry/opentelemetry-collector#2012 is merged

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by jpkrohling** [comment]
I believe codecov can be ignored for this one, as this is merely moving the code from core to contrib.

**Comment by jpkrohling** [comment]
@tigrannajaryan could you please merge this one?

**Review by tigrannajaryan — APPROVED** [review]
Approving, won't review, this is moving already reviewed code from core repo.

**Pull request merged**
