### PR TITLE
[receiver/statsd] Fix metrics with a colon

### PR DESCRIPTION
**Pull request by dirceumaranhaopn**
**Description:** <Describe what has changed.>
Fixing the bug: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12120

**Link to tracking Issue:** [<Issue number if applicable>](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12120)

### CODE REVIEW

**Comment by dmitryax** [comment]
@dirceumaranhaopn please sign the CLA

**Comment by dirceumaranhaopn** [comment]
Hi @dmitryax, I have signed. Thx.

**Review by dmitryax — APPROVED** [review]

**Comment by dirceumaranhaopn** [comment]
@dmitryax would you know why it is failing... I have not change the changelog, and I have added the unreleased yaml file. It seems a false positive.

**Comment by dmitryax** [comment]
Hm... I don't know why it's failing. The changelog entry looks good to me. @djaglowski do you know what's the problem here?

**Review by dmitryax — APPROVED** [review]

**Comment by djaglowski** [comment]
I believe it is failing due to the same reason as #11442. I'll make a PR asap.

**Comment by jmacd** [comment]
:sob: If only we could fix the thing with commas in metric attributes now. :grin:

**Pull request merged**
