### PR TITLE
[receiver/wavefront] do not skip lifecycle tests

### LINKED ISSUE #29995: [receiver/wavefront] do not skip lifecycle tests
These tests should not be skipped.

              add issue to not skip these

_Originally posted by @codeboten in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29982#discussion_r1429196678_

### PR DESCRIPTION
**Pull request by ChrsMark**
**Description:** <Describe what has changed.>

This PR removes skipping of lifecycle test for wavefront receiver.

**Link to tracking Issue:** <Issue number if applicable>

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29995

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by mx-psi** [comment]
Looks like the lifecycle tests failed:

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7449012325/job/20264677584?pr=30325

**Comment by ChrsMark** [comment]
Thanks! It seems that the error `accept tcp 127.0.0.1:2003: use of closed network connection` is related to the default config [endpoint](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/875225e80d4e721f9307a4a5984feee473374ff2/receiver/wavefrontreceiver/README.md#L43). 

I'm not familiar with the lifecycle tests concept here but do I need to ensure any mock endpoints for this tests to work?
Or does this failure have to do with the specific tested version maybe?

Also on my end the lifecycle test seems to work:
```
=== RUN   Test_ComponentLifecycle/metrics-lifecycle
--- PASS: Test_ComponentLifecycle (0.00s)
    --- PASS: Test_ComponentLifecycle/metrics-shutdown (0.00s)
    --- PASS: Test_ComponentLifecycle/metrics-lifecycle (0.00s)
```

**Comment by atoulme** [comment]
The lifecycle tests test that you can start and stop the receiver. When you start a receiver, it should try its best and run, and report errors via the component status reporting. This receiver should start, and try to connect to an endpoint until it succeeds. Instead, it tries to connect synchronously and returns an error and fails right away.

**Comment by ChrsMark** [comment]
Is there any such example for another receiver? Because I see that https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d155707bf0417fc9484c75b9da1aa8f50481db76/receiver/apachereceiver/generated_component_test.go#L72 does exactly the same but it doesn't fail. So I'm trying to understand the difference here 🤔 .

**Pull request closed without merging**
