### PR TITLE
[processor/transform] Fix metric accessor bugs

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:**
Some accessors for metrics were not returned proper data types, breaking their usage in conditions. This PR fixes those bugs.

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10350

**Testing:** 
Updated/Added unit tests

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@open-telemetry/collector-contrib-approvers please review

**Review by anuraaga — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please resolve conflicts

**Comment by TylerHelmuth** [comment]
> Please resolve conflicts

Done

**Review by codeboten — APPROVED** [review]

**Pull request merged**
