### PR TITLE
[CI] Never skip required matrix-rollup jobs

### LINKED ISSUE #12334: [github-actions] Required check is skipped if prerequisite job fails
@djaglowski this is another example where I could merge even if lint is failing:

imagen

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12215#issuecomment-1180721087_

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #12334

The solution here works as follows:

### The Matrix Job
- An [output value](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-setting-a-value) is defined for each of the matrix jobs. By default, this value is empty.
- If a job does not succeed (failed, cancelled, or skipped) its output value is set to a non-empty value.

### The Rollup Job
- _Always_ runs. 
- Concatenates all of the output values from the corresponding matrix jobs.
- If all of the output values are empty (all jobs passed), the concatenated value is empty as well. 
- Success or failure of the rollup job is determined by evaluating whether the concatenated value is empty or not.

### CODE REVIEW

**Comment by djaglowski** [comment]
With the intentional failures introduced by the last change, the appropriate rollup jobs have all failed:
image
image

Links to failure messages:
- [lint](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7306623592?check_suite_focus=true#step:2:20)
- [unittest (1.18](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7306594100?check_suite_focus=true#step:2:20)
- [unittest 1.17](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7306594244?check_suite_focus=true#step:2:20)
- [windows-unittest](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7306719818?check_suite_focus=true#step:2:20)

**Comment by djaglowski** [comment]
With the intentional failures removed, everything passes as expected. 

Direct links to rollup job validation steps:
- [lint](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7307013242?check_suite_focus=true#step:2:20)
- [unittest (1.18)](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7307103562?check_suite_focus=true#step:2:20)
- [unittest (1.17)](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7307103749?check_suite_focus=true#step:2:20)
- [windows-unittest](https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7307197659?check_suite_focus=true#step:2:20)

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Thank you for having a look Daniel!!

**Comment by mx-psi** [comment]
Looks like the rollup job can fail even if all jobs have passed https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/7318709078?check_suite_focus=true

**Comment by mx-psi** [comment]
It sounds like the issue only happens if you re-run failed jobs

**Pull request merged**
