### PR TITLE
[exporter/datadog] Deprecate peer_service_aggregation in favor of peer_tags_aggregation

### PR DESCRIPTION
**Pull request by songy23**
**Description:**
Deprecate peer_service_aggregation in favor of peer_tags_aggregation. Counterpart of https://github.com/DataDog/datadog-agent/pull/20550.

### CODE REVIEW

**Comment by songy23** [comment]
cc @jdgumz

**Review by mx-psi — COMMENTED** [review]
Can you add the flag to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1d4cf910e1a87f19b1ae6cbf614e0f52b67b58fb/exporter/datadogexporter/config_warnings.go#L27 ?

**Review by mx-psi — APPROVED** [review]
LGTM, should we wait for @jdgumz to review?

**Review by songy23 — COMMENTED** [review]
Thanks, I think this should be good to go, it is mostly just making use of https://github.com/DataDog/datadog-agent/pull/20550.

**Pull request merged**
