### PR TITLE
[exporter/opensearch] chore: remove redundant config Validate call

### PR DESCRIPTION
**Pull request by rogercoll**
**Description:** <Describe what has changed.>

Configuration validation is done during collector's startup, making it redundant when being called inside component's logic. This PR removes the Validate call done during exporter's constructor.

**Link to tracking Issue:** <Issue number if applicable> https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33498 (Last component, will close the issue)

**Testing:** <Describe what testing was performed and which tests were added.> Added default config use case (validate error)

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by rogercoll** [comment]
Skip changelog

**Comment by jpkrohling** [comment]
Not sure I was added as reviewer, the code owners for this are: @Aneurysm9 @MitchellGale @MaxKsyunz @YANG-DB

**Comment by YANG-DB** [comment]
@rogercoll thanks for your contribution
We will review this as soon as we can

**Comment by rogercoll** [comment]
@YANG-DB Any update on this PR? I think its the only component missing in order to close https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33498

**Review by YANG-DB — APPROVED** [review]

**Comment by YANG-DB** [comment]
@rogercoll 
Thanks 👍 - I reviewed and approved

**Review by VihasMakwana — APPROVED** [review]
LGTM!
Can someone from @open-telemetry/collector-contrib-approvers take a look?

**Review by MovieStoreGuy — APPROVED** [review]

**Pull request merged**
