### PR TITLE
[prometheusexporter] Expose the same metric from different targets correctly

### LINKED ISSUE #4986: Prometheus Receiver: scraping metrics from multiple targets that emits metrics of the same name and label keys
Reopen of open-telemetry/opentelemetry-collector#1076 

This issue is not resolved and can be seen in latest version

@liamawhite

### PR DESCRIPTION
**Pull request by gouthamve**
Fixes: #4986

See: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4986#issuecomment-1164409948

The new test fails on old code.

cc @dashpole

### CODE REVIEW

**Review by dashpole — APPROVED** [review]
LGTM otherwise

**Comment by arpitjindal97** [comment]
Thanks a lot @gouthamve

**Review by mx-psi — COMMENTED** [review]
The changelog process [changed](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-a-changelog-entry). Could you revert your changes to `CHANGELOG.md` and follow the instructions to create a new changelog entry? You may need to create a tracking issue. Thanks!

**Comment by gouthamve** [comment]
@mx-psi Thanks a lot! This is now done!

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
