### PR TITLE
[chore] cache telemetrygen image to avoid test flakiness

### LINKED ISSUE #24223: [processor/k8sattribute] e2e test fails to setup pod in required time limit
### Component(s)

processor/k8sattributes

## Description

Logs from test failure:

```
=== RUN   TestE2E
    k8s_telemetrygen.go:64: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/k8stest/k8s_telemetrygen.go:64
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:75
        	Error:      	Condition never satisfied
        	Test:       	TestE2E
        	Messages:   	telemetrygen pod of Workload [Job] in datatype [logs] haven't started within 3 minutes, latest pod phase is 
W0710 [14](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065#step:11:15):50:11.23[17](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065#step:11:18)66   17282 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
W0710 14:50:11.427792   17282 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
W0710 14:50:11.628093   17282 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
--- FAIL: TestE2E ([19](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065#step:11:20)7.01s)
```
[Test failure link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5509366365/jobs/10042200389?pr=24065)

This occurred on an unrelated [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24065), so I assume it's a flaky test and just wasn't able to set up the environment within the time limit. I have not investigated further to confirm though.

### Collector version

v0.81.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by atoulme**
Fixes #24223

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
I might be missing some context here, but were the failures caused by the download of the image? I couldn't find logs indicating this in the linked issue

**Comment by atoulme** [comment]
> I might be missing some context here, but were the failures caused by the download of the image? I couldn't find logs indicating this in the linked issue

I couldn't extract logs from the failing tests either. This seems like the main moving part that can invite lag in the test right now, and it's at least reducing risk. It's also allowing us to test telemetrygen as part of those tests.

**Review by songy23 — APPROVED** [review]
LGTM

**Review by fatsheep9146 — APPROVED** [review]
Although not all of failed tests maybe caused by this reason, but I think this improvement still helps a lot.

**Review by MovieStoreGuy — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Pull request merged**
