### PR TITLE
Add opensearch exporter

### PR DESCRIPTION
**Pull request by TomasLongo**
Added Exporter to push signals to open search.

### CODE REVIEW

**Comment by TomasLongo** [comment]
As a first time committer this, rather unpolished, PR helps to get the foot in the door into the projects pr-workflow.

Since this is a new component, I would be happy to act as a sponsor for it. Not sure where I have to set/post/announce this though.

**Review by codeboten — COMMENTED** [review]
Welcome to the project @TomasLongo! The best place to start is by opening an issue with the new component template: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/new?assignees=&labels=new+component&template=new_component.md&title=New+component%3A+

**Comment by TomasLongo** [comment]
@codeboten Not sure if you're the right person to ping. But, as I understand it, a reviewer has to kick off the workflows. Could you do that?

**Comment by TomasLongo** [comment]
@dmitryax Thanks for starting the workflow. It seems that the download of the dependencies is constantly failing (`make gomoddownlaod`). However, I'm not able to reproduce it. I'm fairly new to go's module system  and surely missing a crucial point here. 

Could someone point me into the right direction on how to make that step work in the workflow?

**Comment by dmitryax** [comment]
@TomasLongo please make sure that replace statements are added in all the files using this nw module. I believe cmd/configschema/go.mod needs it.

I also recommend starting with creating a simple small PR, maybe unrelated to this exporter. This will make you a "contributor" in this repo, and the tests here will be triggered automatically after that

**Comment by JaredTan95** [comment]
I think `elasticsearch exporter` in otel contrib supports `opensearch` very well at the moment?

**Comment by cuichenli** [comment]
@TomasLongo thanks for the great work. I noticed there are still some `elasticsearch` stuff (doc and elasticsearch specific config etc) left in the code base.

I have made some changes to my local version based on the one from https://github.com/binjip978/opentelemetry-collector-contrib/tree/opensearch-exporter/exporter/opensearchexporter to replace those `elasticsearch` stuff with `opensearch`, to reduce the duplicated work, feel free to cherry-pick [the commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/944783630ebf44573d2fd6025db58f04833602e9) if you want!

Personally I would also like to add one option for specifying `bulk_action`. I have made a [commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/cda69d07f1f7555e204a15091501aff63b0727e4) as well, if the change makes sense to you, feel free to cherry-pick it as well.

But of course, also feel free to reject those commits!

Thank you again!

**Comment by arnitolog** [comment]
Hello, 
I'm wondering if this PR can be merged into the main before the next release.

**Comment by cuichenli** [comment]
> Hi @cuichenli, when will this valuable PR be merged please? Thanks.

Hi @wantdrink , unfortunately I am neither author of the PR nor maintainer of the repo. 

BTW, looks like the author has been inactive on this for a while. I am not sure if I should fork the change and open another PR ?

**Comment by wantdrink** [comment]
Thanks @cuichenli. I'm not sure.
Is there anyone who can suggest? Thanks.

**Comment by clarkjohnd** [comment]
@dmitryax @codeboten Seems this PR has gone quiet (@TomasLongo ?). Would be keen to pick this up and get the component into contrib as could really use as a feature in the official build down the line. @cuichenli would you be keen to pick up with me assisting? I see you've already made some valuable changes in your own branch.

**Comment by cuichenli** [comment]
Hi @clarkjohnd , yes I would like to help. But not sure what should I do next? Should I just open another PR from my fork? Thanks!

**Comment by dbason** [comment]
I'm a developer on [Rancher Opni[(https://github.com/rancher/opni) and we're also interested in this feature as we use Opensearch for our logging stack.  I'm  also happy to help push this forward.

I suspect at this point the best bet may be to just open a new PR but maybe @dmitryax is a better person to comment on this

**Comment by dbason** [comment]
@cuichenli FYI I've also forked and have rebased your branch and fixed up the deprecated code for v0.71.0 - https://github.com/dbason/opentelemetry-collector-contrib/tree/opensearch-exporter

**Comment by atoulme** [comment]
Before a new PR, please make sure you find a sponsor for the component on the issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7905.

**Pull request closed without merging**
