### PR TITLE
[docs] Add status header for dotnetdiagnostics receiver

### PR DESCRIPTION
**Pull request by Frapschen**
**Description:** <Describe what has changed.>
Add status header for dotnetdiagnostics receiver

### CODE REVIEW

**Comment by mx-psi** [comment]
@pmcollins @davmason to review as CODEOWNERS

**Comment by Frapschen** [comment]
@pmcollins @davmason  can you review this PR?

**Comment by djaglowski** [comment]
Should we mark this component as alpha for now?

**Comment by mx-psi** [comment]
> Should we mark this component as alpha for now?

Sounds good to me

**Comment by Frapschen** [comment]
status header changed

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
