### PR TITLE
[chore] Change receiver config tests to unmarshal config only for that component. (part4)

### PR DESCRIPTION
**Pull request by kovrus**
**Description:** <Describe what has changed.>

Change receivers config tests to unmarshal config only for that component.

- [x] pulsarreceiver
- [x] rabbitmqreceiver
- [x] redisreceiver
- [x] riakreceiver
- [x] saphanareceiver
- [x] sapmreceiver
- [x] signalfxreceiver
- [x] simpleprometheusreceiver
- [x] skywalkingreceiver
- [x] solacereceiver

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13224

### CODE REVIEW

**Comment by kovrus** [comment]
@dmitryax

**Comment by djaglowski** [comment]
This appears to contain many of the same changes as part 3 (memcached -> postgresql).

**Comment by kovrus** [comment]
dropped `memcached` and `postgresqlreceiver` changes.

**Comment by djaglowski** [comment]
I should have been more clear, but I meant to point out the whole range of receivers between memcached and postgresql, everything before pulsar. Really it doesn't matter that much but it'll allow for quicker approval and avoid a rebase.

**Comment by kovrus** [comment]
ah.. @djaglowski dropped the whole range.

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
