### PR TITLE
[Processor/transform]If vals is nil, no need to add the delimiter

### PR DESCRIPTION
**Pull request by yuzhiquantubi**
**Description:** <Describe what has changed.>
If vals is nil, there is no need to add the delimiter.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by evan-bradley** [comment]
Hello, thanks for opening a PR to improve OTTL.

Currently we [stringify nil](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24896/files#diff-ffd7ce028e16f170f52e07f46e2f37a22f7ded356e4db0554f15514fa8f15a0eR42), so `Concat("hello", nil, "world")` would output `hello,<nil>,world`. With this proposed change, it would print `hello,<nil>world` which doesn't seem correct to me since it's no longer clear that `<nil>` and `world` come from separate arguments to `Concat`. What behavior you would expect to see here?

**Comment by yuzhiquantubi** [comment]
> Hello, thanks for opening a PR to improve OTTL.
> 
> Currently we [stringify nil](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24896/files#diff-ffd7ce028e16f170f52e07f46e2f37a22f7ded356e4db0554f15514fa8f15a0eR42), so `Concat("hello", nil, "world")` would output `hello,<nil>,world`. With this proposed change, it would print `hello,<nil>world` which doesn't seem correct to me since it's no longer clear that `<nil>` and `world` come from separate arguments to `Concat`. What behavior you would expect to see here?

Thanks for the reply, we concat the attributes http_path1 and http_path2 with "/" as new attribute for trace,  but if http_path2 does not match anything, the "/" shoud not join in the new string, like this:
```
 /http_path1/http_path2/http_path3
# if http_path2 is nil,should
 /http_path1/http_path3
```

**Comment by yuzhiquantubi** [comment]
> > Hello, thanks for opening a PR to improve OTTL.
> > Currently we [stringify nil](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24896/files#diff-ffd7ce028e16f170f52e07f46e2f37a22f7ded356e4db0554f15514fa8f15a0eR42), so `Concat("hello", nil, "world")` would output `hello,<nil>,world`. With this proposed change, it would print `hello,<nil>world` which doesn't seem correct to me since it's no longer clear that `<nil>` and `world` come from separate arguments to `Concat`. What behavior you would expect to see here?
> 
> Thanks for the reply, we concat the attributes http_path1 and http_path2 with "/" as new attribute for trace, but if http_path2 does not match anything, the "/" shoud not join in the new string, like this:
> 
> ```
>  /http_path1/http_path2/http_path3
> # if http_path2 is nil,should
>  /http_path1/http_path3
> ```

So i want add an args `ignoreNil`, to support this behavior...

**Comment by TylerHelmuth** [comment]
Another option is to perform the concat with no where clause and then use `replace_pattern` to search for `\\` and replace it with `""`

**Comment by yuzhiquantubi** [comment]
> > Thanks for the reply, we concat the attributes http_path1 and http_path2 with "/" as new attribute for trace, but if http_path2 does not match anything
> 
> OTTL tends to be verbose, so usually you would explicitly handle `http_path2` being unavailable like this:
> 
> ```yaml
> x_statements:
> - [...] Concat([attributes["http_path1"], attributes["http_path2"], attributes["http_path3"]], "/") where attributes["http_path1"] != nil and attributes["http_path2"] != nil and attributes["http_path3"] != nil
> - [...] Concat([attributes["http_path1"], attributes["http_path3"]], "/") where attributes["http_path1"] != nil and attributes["http_path2"] == nil and attributes["http_path3"] != nil
> ```
> 
> Would this fit your use case?

Cool, i would like to give a try for this expression, thanks!

**Comment by yuzhiquantubi** [comment]
Thanks, guys, get the expect result.

**Pull request closed without merging**
