### PR TITLE
Logzio exporter

### PR DESCRIPTION
**Pull request by yyyogev**
**Description**: Added a logz.io traces exporter

**Link to tracking Issue**: #686

**Testing**: Added test for each of the components in the new exporter

**Documentation**: Added a readme specifying how to use the exporter and its parameters with an example.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Can you please follow the contributions guidelines (see core collector contributing.md for how to create a the PRs for a new component) and some more details about contrib in this repo contributing.md

**Comment by yyyogev** [comment]
I have, did I miss something?

**Comment by tigrannajaryan** [comment]
> I have, did I miss something?

If possible please split this into 3 parts to make reviewing easier/faster, see https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#how-to-structure-prs-to-get-expedient-reviews

>Consider submitting different PRs for (more details about adding new components here) :
>    First PR should include the overall structure of the new component:
>        Readme, configuration, and factory implementation usually using the helper factory structs.
>        This PR is usually trivial to review, so the size limit does not apply to it.
>    Second PR should include the concrete implementation of the component. If the size of this PR is larger than the recommended size consider splitting it in multiple PRs.
>    Last PR should enable the new component and add it to the otelcontribcol binary by updating the components.go file. The component must be enabled only after sufficient testing, and there is enough confidence in the stability and quality of the component.

**Comment by yyyogev** [comment]
@tigrannajaryan so you want me to close this one and open a new one with just the initial implementation

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan so you want me to close this one and open a new one with just the initial implementation

Yes, please do that or update this PR to include just the initial implementation as it is recommended in the contrib docs (make sure the PR description / commit message reflects it).

**Comment by yyyogev** [comment]
@tigrannajaryan that's the initial. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1091
Should I wait for it to be approved before opening the second?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan that's the initial. #1091
> Should I wait for it to be approved before opening the second?

No need to wait (unless you think there a chance for rejection). You can stack PRs on top of the first one, but be prepared for possible changes to the initial PR which may require changes in subsequent ones.

**Comment by tigrannajaryan** [comment]
@yyyogev if you plan to open separate PRs I advise to close this one.

**Pull request closed without merging**
