### PR TITLE
Edited `make gendependabot` Task to Enable Dependabot for GitHub Actions

### PR DESCRIPTION
**Pull request by andresbeckruiz**
**Description:** 
Enabled Dependabot for GitHub Actions by editing the `make gendependabot` task in Makefile. For now, I have set the update frequency to weekly (this can be easily changed).

**Link to tracking Issue:** 
#3445 

**Testing:**
All tests running `make` passed, no new tests were added. 

**Documentation:** 
N/A

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@andresbeckruiz we need a similar PR to core collector.

**Comment by andresbeckruiz** [comment]
@bogdandrutu will get to that right now

**Comment by andresbeckruiz** [comment]
@bogdandrutu done in both core and contrib PRs :)

**Comment by bogdandrutu** [comment]
:( sorry to ask to rebase :(

**Comment by andresbeckruiz** [comment]
sorry, could you clarify what you mean by rebasing?

**Comment by bogdandrutu** [comment]
Screen Shot 2021-05-26 at 2 01 54 PM

**Comment by andresbeckruiz** [comment]
@bogdandrutu done

**Pull request merged**
