### PR TITLE
[receiver/awss3receiver] Add obsreport usage for receiver metrics

### PR DESCRIPTION
**Pull request by adcharre**
**Description:** Add metrics using obsreport to the S3 receiver

**Link to tracking Issue:** #30750 

**Testing:** Full stack test, confirmed `otelcol_receiver_accepted_spans` and `otelcol_receiver_refused_spans` was being exported for the `awss3` receiver.

**Documentation:** None

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
LGTM

**Comment by atoulme** [comment]
Sorry please resolve conflicts.

**Comment by andrzej-stencel** [comment]
Can you please fix the conflicts @adcharre

**Comment by adcharre** [comment]
> Can you please fix the conflicts @adcharre

@andrzej-stencel - done

**Pull request merged**
