### PR TITLE
receiver/*: eliminate use of .Append()

### PR DESCRIPTION
**Pull request by Aneurysm9**
**Description:** Removes use of deprecated .Append() methods.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/2488

### CODE REVIEW

**Review by jrcamp — CHANGES_REQUESTED** [review]
I think all the PRs can be cleaned up more to avoid the extra allocations. For example:

```diff
diff --git a/receiver/fluentforwardreceiver/conversion.go b/receiver/fluentforwardreceiver/conversion.go
index 8dae4e57c..8688fe2ba 100644
--- a/receiver/fluentforwardreceiver/conversion.go
+++ b/receiver/fluentforwardreceiver/conversion.go
@@ -411,7 +411,7 @@ func (pfe *PackedForwardEventLogRecords) parseEntries(entriesRaw []byte, isGzipp
 
 	msgpReader := msgp.NewReader(reader)
 	for {
-		lr := pdata.NewLogRecord()
+		lr := pfe.LogSlice.AppendEmpty()
 		err := parseEntryToLogRecord(msgpReader, lr)
 		if err != nil {
 			if msgp.Cause(err) == io.EOF {
@@ -421,8 +421,5 @@ func (pfe *PackedForwardEventLogRecords) parseEntries(entriesRaw []byte, isGzipp
 		}
 
 		lr.Attributes().InsertString(tagAttributeKey, tag)
-
-		tgt := pfe.LogSlice.AppendEmpty()
-		lr.CopyTo(tgt)
 	}
 }
```

**Comment by Aneurysm9** [comment]
> I think all the PRs can be cleaned up more to avoid the extra allocations. For example:

Applying the suggested change results in a test failure as the `pfe.LogSlice` is left with unwanted empty records when the `parseEntryToLogRecord()` function returns an error.  I'm not sure I'm comfortable changing the test expectations for an allocation microöptimization without input from the original authors.

**Comment by jrcamp** [comment]
> Applying the suggested change results in a test failure as the `pfe.LogSlice` is left with unwanted empty records when the `parseEntryToLogRecord()` function returns an error. I'm not sure I'm comfortable changing the test expectations for an allocation microöptimization without input from the original authors.

Yeah it's a good point, I didn't look into it too deeply but some care would have to be taken on error. Perhaps `logSlice.Resize(logSlice.Len()-1)`. But I agree component owners should be involved in any logic changes. Seems like this is one potential downside to not having `Append()`: how do you create a value that you may end up discarding *without* resulting in an additional allocation with `CopyTo`. 

@bogdandrutu thoughts?

**Comment by bogdandrutu** [comment]
@jrcamp one potential solution is to add a "remove", we talked about that, that will result in a call to remove when dropping (error) happens.

**Comment by jrcamp** [comment]
> @jrcamp one potential solution is to add a "remove", we talked about that, that will result in a call to remove when dropping (error) happens.

@bogdandrutu yeah but that's still more error-prone than the status quo of calling `Append()` after the error conditions are passed and you know you want to add to the slice. Maybe Append shouldn't necessarily be deprecated but Append/AppendEmpty be used based on what's right for the situation.

**Comment by bogdandrutu** [comment]
> Maybe Append shouldn't necessarily be deprecated but Append/AppendEmpty be used based on what's right for the situation.

Append will stop us on doing other optimizations in the future. The case of error can also be avoided by calculating everything needed then creating the metric instead of create the metric then check for errors.

For the time being let's remove Append and do the extra copy for the case of errors, and try some of the suggested ideas, if these are not working we will think about that.

**Review by jrcamp — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Pull request merged**
