### PR TITLE
[exporter/logicmonitorexporter] Adds traces support in Logicmonitor Exporter

### PR DESCRIPTION
**Pull request by avadhut123pisal**
**Description:** Support for Traces is added in Logicmonitor Exporter

**Link to tracking Issue:** #19646

**Testing:** Unit testing

**Documentation:**  Updated README with tracing support related details.

### CODE REVIEW

**Comment by avadhut123pisal** [comment]
cc: @khyatigandhi6

**Review by atoulme — COMMENTED** [review]
Some nits on first pass.

**Review by atoulme — APPROVED** [review]
just so it's clear my review has been addressed, I approve this PR, but a code owner should review and approve as well. Code looks good to me, thanks for the contrib!

**Comment by avadhut123pisal** [comment]
@khyatigandhi6  will you please review the PR ?

**Comment by khyatigandhi6** [comment]
LGTM

**Comment by mx-psi** [comment]
needs a rebase

**Comment by avadhut123pisal** [comment]
> needs a rebase

Done. But not sure why `TestElasticsearchIntegration` is failing. Can you re-run the action for the same ?

**Pull request merged**
