### PR TITLE
Add timestampprocessor

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
**Description:** 
Adds a new metrics processor that rounds timestamps to a configured precision, eg 1 second, 5 seconds, 1 minute, etc.

This is useful for back-end systems that combine multiple metrics into fewer larger structures and use the metric timestamps as grouping criteria.

NOTE: This has not been added to `internal/components/components.go` yet.

**Link to tracking Issue:**
N/A

**Testing:**
Added unit tests for config, factory and the timestamp processor.

**Documentation:**
Adds README information on what config properties are required.

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
Ah, I see that I'm missing the local go.mod & go.sum for the processor, which I think is contributing the the linter errors. I'll add those soon.

**Comment by MikeGoldsmith** [comment]
@open-telemetry/collector-approvers @tigrannajaryan @bogdandrutu 

I've fixed the linting / import errors, but now unit test step failed with PrometheusExporter's End2EndTest - any advice?

Thanks

**Comment by MikeGoldsmith** [comment]
Bump -- looking for help resolving the PrometheusExporter's End2EndTest

**Comment by MikeGoldsmith** [comment]
bump

**Review by bogdandrutu — COMMENTED** [review]
Can you explain a bit the overall architecture that needs this, my concerns are:
1. If backend supports OTLP then this can happen on the backend side.
2. If backend has custom protocol then this can happen during the translation.

I don't see this as a helpful operation to happen before hitting the backend or during backend's protocol translation. This seems like an operation that will not help other processors in our pipeline.

**Comment by bogdandrutu** [comment]
Per comment, and no response for 20d, closing this.

**Pull request closed without merging**
