### PR TITLE
Prototype implementation of experimental metric configuration service

### PR DESCRIPTION
**Pull request by wtong98**
This implementation relates to the experimental metric config specification, found [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/experimental/metrics/config-service.md). It acts as the server for [this service](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/experimental/metrics/configservice/configservice.proto)

An [example](https://github.com/vmingchen/opentelemetry-go-contrib/tree/master/sdk/dynamicconfig/example) is included to show how it works.

Its counterpart on the Go contrib SDK is available [here](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/223)

### CODE REVIEW

**Comment by jrcamp** [comment]
@wtong98 is this an intern project? has somebody reviewed it yet at the sponsoring company?

**Comment by wtong98** [comment]
@jrcamp Yup! That's correct. The other members are:
* Ming Chen @vmingchen (host)
* Josh Montana @jdmontana (co-host)
* Churan Chen @churanchen (other intern)

And yes, it has been approved before this PR was made

**Comment by bogdandrutu** [comment]
@vmingchen   @jdmontana please try to pre-review and also help interns to split the PR in more reasonable size PRs. I am confident that this would not be merged in the internal codebase as 10K lines change :)

**Comment by tigrannajaryan** [comment]
@wtong98 is it possible to split this PR as @bogdandrutu asked?

**Comment by wtong98** [comment]
@tigrannajaryan Yup! The current hope is to present the prototype for dynamic per-metric configuration as a complete package, on both the SDK and Collector contrib (for example, https://github.com/open-telemetry/opentelemetry-go-contrib/pull/223#issuecomment-686177176).

Since it's difficult to present the whole picture without presenting all the code, we decided to give everything in these PRs rather than fracture them into many smaller ones. However if the large-scale architecture of our solution looks acceptable, we can then absolutely break it into reasonable PRs that can be individually scrutinized and merged.

This project is intended for **after GA**.

Note: my former supervisors, @vmingchen and @jdmontana, will be the main points of contact moving forward, though I will definitely keep an eye on this project.

**Comment by tigrannajaryan** [comment]
@vmingchen @jdmontana is there an intent to continue working on this PR?

>This project is intended for after GA.

Can we convert to Draft if this is not for now? Alternatively if no-one is actively working on this consider closing the PR.

**Pull request closed without merging**
