### PR TITLE
Codesmon/exporter/azuremonitor/persistent queue

### PR DESCRIPTION
**Pull request by codesmon**
Description:
Added a new config item to support the QueueSettings values.
Extended the exportHelper.New[Metrics|Logs|Traces]Exporter call to pass in the QueueSettings config, thus enabling persistent_queue for this exporter.

Link to tracking Issue:
Fixes issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25859

Testing:
Extending unit tests to check configuration changes are picked up.

Documentation:
Added sending_queue config items to README.md's configuration section.

### CODE REVIEW

**Review by pcwiese — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
Not stale

**Comment by atoulme** [comment]
Rerunning coverage.

**Comment by rajkumar-rangaraj** [comment]
@codesmon Could you please fix conflicts on this PR?

**Review by rajkumar-rangaraj — APPROVED** [review]

**Comment by rajkumar-rangaraj** [comment]
@open-telemetry/collector-contrib-approvers, could you please help merge this PR?

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
