### PR TITLE
Add OTel-Arrow components to contribcol; mark these alpha

### PR DESCRIPTION
**Pull request by jmacd**
**Description:** Labels the `otelarrowexporter` and `otelarrowreceiver` as alpha, adds them to the contribcol.

**Link to tracking Issue:** #26491

### CODE REVIEW

**Review by lquerel — APPROVED** [review]
LGTM

**Comment by atoulme** [comment]
Yes, I'd wait for 0.103.0 to be out and then fix conflicts.

**Comment by jmacd** [comment]
> Also, just in case it's not obvious, make sure to submit a PR to the releases repository to add these components to the contrib distribution, as described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#releasing-new-components).

@crobert-1 Asking for slight clarification: The internal/components code has no documentation -- the above text is the only reference to it -- and it appears to be auto-generated? Is it the same as cmd/otelcontribcol/components.go?

**Comment by jmacd** [comment]
@crobert-1 Also, who determines which distribution these components can go into? Speaking as the developer, we are hoping to recommend OTel-Arrow as a more-performant and 100% compatible replacement for the OTLP exporter and receiver. Therefore, I would recommend adding OTel-Arrow components to every distribution that has an OTLP exporter or receiver component.

**Comment by jmacd** [comment]
https://github.com/open-telemetry/opentelemetry-collector-releases/pull/582 FYI

**Comment by codeboten** [comment]
> Also, who determines which distribution these components can go into

The rules for inclusion are listed in each distribution's readme file listed at the bottom of the doc here: https://github.com/open-telemetry/opentelemetry-collector-releases

**Comment by crobert-1** [comment]
> > Also, just in case it's not obvious, make sure to submit a PR to the releases repository to add these components to the contrib distribution, as described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#releasing-new-components).
> 
> @crobert-1 Asking for slight clarification: The internal/components code has no documentation -- the above text is the only reference to it -- and it appears to be auto-generated? Is it the same as cmd/otelcontribcol/components.go?

Thanks for pointing that out, it looks like the `internal/components` documentation is out of date, I've submitted https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33690 to remove this reference.

**Review by crobert-1 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Awesome! Thanks @jmacd

**Pull request merged**
