### PR TITLE
[receiver/googlecloudmonitoringreceiver] Adding Google Cloud monitoring receiver

### PR DESCRIPTION
**Pull request by abhishek-at-cloudwerx**
**Description**: Adding Google Cloud Monitoring receiver

**Link to tracking Issue**: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33762

**Testing**: Test cases for configuration added

**Documentation**: README file added for describing the component

### CODE REVIEW

**Comment by crobert-1** [comment]
_It looks like a lot of changes from this PR may be due to not being up to date with `main`, so I'm going to update the branch._

**Comment by crobert-1** [comment]
@abhishek-at-cloudwerx, can you please sign the EasyCLA? This PR can't proceed until it's signed.

**Review by crobert-1 — COMMENTED** [review]
It looks like this PR has deleted a lot of changelog entries, and includes quite a few unrelated changes. Please remove unrelated changes.

**Comment by abhishek-at-cloudwerx** [comment]
Closing in favour of Org CLA

**Pull request closed without merging**
