### PR TITLE
Revert "[processor/spanmetrics] Emit metrics every n seconds (#16601)"

### PR DESCRIPTION
**Pull request by codeboten**
This reverts commit a5678b524a4c9a0e87ba7e03f3cc75f13a2d04d6.

This change causes the following failure: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3708080812/jobs/6285497829

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17040

### CODE REVIEW

**Comment by codeboten** [comment]
Ping @albertteoh, reverting the change as it's causing failures, please take a look.

**Review by MovieStoreGuy — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]
Thanks!

**Comment by dmitryax** [comment]
cc @albertteoh, please re-submit your PR again once https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17037 is resolved and CI is unblocked

**Comment by albertteoh** [comment]
Thanks @dmitryax @codeboten , I've resubmitted the PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17307.

**Pull request merged**
