### PR TITLE
Upgrade to latest core, fix googlecloudexporter deps

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by punya** [comment]
@bogdandrutu I made a PR to your branch that fixes this (using an unreleased version of GoogleCloudPlatform/opentelemetry-operations-go). Please take a look.

**Comment by punya** [comment]
Sorry, I missed a couple more things -- update coming up.

**Comment by bogdandrutu** [comment]
@punya added a new commit to run the go tidy

**Comment by punya** [comment]
@bogdandrutu there's a bit more unfortunately.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
