### PR TITLE
[receiver/datadog][bug-fix] Add DD span `metrics` as attributes

### PR DESCRIPTION
**Pull request by lopes-felipe**
**Description:** <Describe what has changed.>
Datadog [divides the span's tags](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java#L210-L212) into [two fields](https://github.com/DataDog/datadog-agent/blob/1739a048156d968bbe5fd8a1ace8e07c997d16d9/pkg/proto/datadog/trace/span.proto#L50-L55), `meta` for string values and `metrics` for numeric ones.

Currently, the receiver isn't considering the `metrics` field when building the OTel span's attributes, losing this metadata during the conversion. This PR fixes this issue.

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by lopes-felipe** [comment]
Test failing due to [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35119) unrelated issue.

**Comment by lopes-felipe** [comment]
@jpkrohling @MovieStoreGuy, would you mind reviewing this? It's a pretty straightforward change. Thank you :)

**Review by jpkrohling — APPROVED** [review]
LGTM

**Comment by lopes-felipe** [comment]
Thank you for the review @jpkrohling. Any chances we get this merged as well?

**Review by carrieedwards — APPROVED** [review]

**Pull request merged**
