### PR TITLE
[sumologicexporter] Enable metrics pipeline

### PR DESCRIPTION
**Pull request by sumo-drosiek**
**Description:**

Enable metrics pipeline for sumologicexporter. For now only prometheus format is supported. Rest of formats it's going to be implemented in future PRs

**Link to tracking Issue:**

#1498 

**Testing:**

Unit tests

**Documentation:**

In-code comments

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
cc: @pmm-sumo @pmalek-sumo

**Comment by bogdandrutu** [comment]
@sumo-drosiek was this reviewed by someone that is in the owners for sumologic exporter?

**Comment by sumo-drosiek** [comment]
> @sumo-drosiek was this reviewed by someone that is in the owners for sumologic exporter?

cc: @pmalek-sumo

**Review by pmalek-sumo — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]
Tested the metrics exporting and all looks good overall. I would just clarify README.md with the actually supported export formats (e.g. `carbon2` is not supported yet)

**Comment by pmm-sumo** [comment]
@sumo-drosiek the test needs to be fixed

**Comment by sumo-drosiek** [comment]
@bogdandrutu Could we merge this PR?

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
