### PR TITLE
Add Circle CI config

### LINKED ISSUE #8: Set up continuous integration.

### PR DESCRIPTION
**Pull request by songy23**
Fixes #8.

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please fix the build :)

**Comment by songy23** [comment]
Fixed - I forgot I already had the tools installed on my workstation. For CI they need to be installed first.

**Comment by bogdandrutu** [comment]
Still needs more work :)

**Comment by songy23** [comment]
Finally got it working - please merge.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
