### PR TITLE
[exporter/dynatrace] Improve logging of metrics ingest responses

### PR DESCRIPTION
**Pull request by evan-bradley**
**Description:**

Add additional logging to the Dynatrace exporter to help debug failure scenarios and provide ingestion confirmation in success scenarios.

**Testing:**

Unit tests were added.

### CODE REVIEW

**Review by dyladan — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Comment by evan-bradley** [comment]
@jpkrohling could you give this a look?

**Comment by evan-bradley** [comment]
@jpkrohling Could you review this when you have an opportunity?

**Comment by evan-bradley** [comment]
@jpkrohling Please take a look when you are able.

**Comment by evan-bradley** [comment]
@codeboten could you give this a review?

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
