### PR TITLE
Add internal localhostgate package

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

Follow up to open-telemetry/opentelemetry-collector/pull/8622

**Link to tracking Issue:** First step of #30702

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
Should there be a changelog or a README for the feature gate?

**Comment by mx-psi** [comment]
> Should there be a changelog or a README for the feature gate?

I was thinking we can do a changelog item once we actually use it in individual components, listing all the components we are using this in. I can also add the changelog item now with an empty list of components if you think that's better

**Comment by songy23** [comment]
Yes I think it makes sense to start a list now and expand it when changes are made to each component.

**Comment by crobert-1** [comment]
I'm wondering if there's a good way to enforce keeping this up to date `core`. There will be times they differ, but it should only be temporarily. There should be a PR opened for both repositories, one will just get merged before the other.

It could be a CI check that simply fails whenever a user changes the contents of these files, warning the user that `core` needs updated as well. A `triager`, `approver`, or `maintainer` could then come, confirm a PR is also opened against core, and then add some kind of `skip` label that ignores the check? Or just approve and merge it with the failing CI action knowing it's not an issue. If it's a CI action it would also need to be in core to make sure contrib stays up to date as well.

Otherwise we could add a CI action that simply compared file contents and fails when they don't match. This would be a bit more involved and would fail in unrelated PRs, which would be confusing.

I don't want to make it too complicated but speaking from experience, a comment at the top of a file is pretty easy to miss.

**Comment by mx-psi** [comment]
@crobert-1 I don't expect much to change here, but it makes sense to have something like this. I filed #30793 to do this, but I would like to do it separately (I want to unblock PRs that start to use this feature gate in components)

**Review by songy23 — APPROVED** [review]
Needs `make tidy`

**Pull request merged**
