### PR TITLE
[connector/spanmetricsconnector] fix default metrics initialization

### PR DESCRIPTION
**Pull request by LaserPhaser**
**Description:** Added an ability to remove default labels from metrics
Fixing [GH-16344]

**Link to tracking Issue:** [GH-16344]

**Testing:** Test added to the config_tests.go file

**Documentation:** Readme.md updated

### CODE REVIEW

**Comment by kovrus** [comment]
@LaserPhaser have you considered using the `delete_key` or `keep_keys` functions of the transform processor to achieve the same goal?

**Comment by kovrus** [comment]
Let me know if it works for you.

**Comment by LaserPhaser** [comment]
> Let me know if it works for you.
Updated.

**Comment by rlex** [comment]
Also interested in this. I need only _calls part. 

I managed to remove unneded transform keep_keys, but i can't seemingly remove duration metrics.

i tried 
```
          connectors:
            spanmetrics:
              namespace: span.metrics
          processors:
            transform/spanmetrics_attributes_cleanup:
              metric_statements:
                - context: datapoint
                  statements:
                    - keep_keys(attributes, ["service.name", "status.code"])
            filter/spanmetrics_filterlist:
              metrics:
                exclude:
                  match_type: regexp
                  metric_names:
                    - span_metrics_duration_.*
 ```

Bit i still see all span_metrics_duration metrics arriving to my tsdb. Am i missing something?

**Comment by kovrus** [comment]
> Also interested in this. I need only _calls part.
> 
> I managed to remove unneeded labels with transform keep_keys, but i can't seemingly remove duration metrics.
> 
> i tried
> 
> ```
>           connectors:
>             spanmetrics:
>               namespace: span.metrics
>           processors:
>             transform/spanmetrics_attributes_cleanup:
>               metric_statements:
>                 - context: datapoint
>                   statements:
>                     - keep_keys(attributes, ["service.name", "status.code"])
>             filter/spanmetrics_filterlist:
>               metrics:
>                 exclude:
>                   match_type: regexp
>                   metric_names:
>                     - span_metrics_duration_.*
> ```
> 
> Bit i still see all span_metrics_duration metrics arriving to my tsdb. Am i missing something?


In your case, `spanmetrics` duration will be generating the OTel `span.metrics.duration` metric. I am not sure whether it is possible to drop metrics with the `transform` processor (I have to look it up), but you can definitely filter it out with the `filter` processor.

**Comment by LaserPhaser** [comment]
> Let me know if it works for you.

works for me 
thx

**Comment by rlex** [comment]
> > Also interested in this. I need only _calls part.
> > I managed to remove unneeded labels with transform keep_keys, but i can't seemingly remove duration metrics.
> > i tried
> > ```
> >           connectors:
> >             spanmetrics:
> >               namespace: span.metrics
> >           processors:
> >             transform/spanmetrics_attributes_cleanup:
> >               metric_statements:
> >                 - context: datapoint
> >                   statements:
> >                     - keep_keys(attributes, ["service.name", "status.code"])
> >             filter/spanmetrics_filterlist:
> >               metrics:
> >                 exclude:
> >                   match_type: regexp
> >                   metric_names:
> >                     - span_metrics_duration_.*
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Bit i still see all span_metrics_duration metrics arriving to my tsdb. Am i missing something?
> 
> In your case, `spanmetrics` duration will be generating the OTel `span.metrics.duration` metric. The name that you should be filtering is `span.metrics.duration`. It becomes `span_metrics_duration_{count/sum/bucket}` once exported with Prometheus exporters.

That worked, thanks! May i ask why dot-delimited format is needed? Because it's internal opentelemetry-collector metric and not produced by any external sources? span_metrics_duration hasn't worked for me for some reason.

**Pull request closed without merging**
