### PR TITLE
Bug-Fix: Updated config path in the documentation

### PR DESCRIPTION
**Pull request by scaratec**
The provided example in the README.md contained small bug. The config file is mounted to the wrong path. This is a showstopper for new users as the configuration is simply not loaded and the collector us using defaults.

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by codeboten — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Lint errors

**Comment by scaratec** [comment]
> Lint errors

Anything I need to do? My changes are not causing the lint errors as they are purely in the README.md

**Review by TylerHelmuth — APPROVED** [review]
@scaratec rebasing/merging in latest from main should resolve the build issues.

**Comment by dmitryax** [comment]
@scaratec can you please rebase your change?

**Comment by scaratec** [comment]
> @scaratec can you please rebase your change?

Let's see if I can do that without messing up this PR :-)

**Review by codeboten — APPROVED** [review]
@scaratec looks like you did! 😄

**Pull request merged**
