### PR TITLE
[receiver/awscontainerinsight] Fix memory leak on shutdown in k8s API server

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

This change has 4 main parts:
1. Shutdown the k8s API server's broadcaster during `Shutdown` as it has its own running goroutines that need shutdown to avoid leaking.
2. Call `Shutdown` in the failure scenarios of `New`. This is required because once again, goroutines are started during the k8s API server's `New` call stack. Since it returns `nil` on error, there's no way to shutdown once it returns. This means `Shutdown` must be called on error.
3. Only set the server's broadcaster after passed in options are complete. This will help avoid a goroutine leak as well, as explained in the added comment in the code.
4. Add `goleak` checks to help ensure no goroutines are being leaked.

**Link to tracking Issue:** <Issue number if applicable>
#30438

**Testing:** <Describe what testing was performed and which tests were added.>
All existing tests are passing, as well as added `goleak` checks.

### CODE REVIEW

**Comment by crobert-1** [comment]
Failures are frequencies of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32391 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32396, I've added references on both issues.

**Review by fatsheep9146 — APPROVED** [review]

**Comment by fatsheep9146** [comment]
nicely ping @Aneurysm9 for review

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
@Aneurysm9 please review

**Review by codeboten — COMMENTED** [review]
Pinging code owners @Aneurysm9 @pxaws

**Comment by atoulme** [comment]
Pinging code owners @Aneurysm9 @pxaws

**Pull request closed without merging**
