### PR TITLE
[pkg/translator/jaeger] Preserve binary attribute values

### LINKED ISSUE #32204: Jaeger translator performs unnecessary conversion of binary attributes to strings
### Component(s)

pkg/translator/jaeger

## Description

When implementing e2e integration tests for jaeger-v2 we encountered a conversion issue https://github.com/jaegertracing/jaeger/pull/5322#issuecomment-2033748607

## Expected Result

binary attributes in OTEL should be represented as binary tags in Jaeger

## Actual Result

transformers in both directions encode binary as base64. Behavior introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14574

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5f1488f0c31f67aec0e962f3bbfcae5c3e8724e3/pkg/translator/jaeger/traces_to_jaegerproto.go#L141-L143

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5f1488f0c31f67aec0e962f3bbfcae5c3e8724e3/pkg/translator/jaeger/jaegerproto_to_traces.go#L242-L243

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5f1488f0c31f67aec0e962f3bbfcae5c3e8724e3/pkg/translator/jaeger/jaegerthrift_to_traces.go#L152-L153

### Collector version

0.97

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### LINKED ISSUE #32304: Support component health setting
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

OpAMP [now supports component health](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#componenthealth-message) it would be great if the opamp extension sent this with its messages.

### Describe the solution you'd like

Use component status reporting as described [here](https://github.com/open-telemetry/opentelemetry-collector/blob/de3ef01bff4f1e4db0eee94abce862c66582f208/extension/extension.go#L54-L63)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yurishkuro**
**Description:** translate binary attribute values to/from Jaeger as is, without encoding them as base64 strings

**Link to tracking Issue:**  Resolves #32204

**Testing:** unit tests in the package

**Documentation:** none

### CODE REVIEW

**Review by Frapschen — APPROVED** [review]
LGTM

**Comment by yurishkuro** [comment]
@open-telemetry/collector-contrib-approvers what's blocking this PR?

**Review by crobert-1 — APPROVED** [review]

**Comment by yurishkuro** [comment]
@codeboten can we merge this?

**Comment by bryan-aguilar** [comment]
This is still awaiting a review from codeowner. cc @frzifus

**Review by frzifus — APPROVED** [review]

**Review by bryan-aguilar — APPROVED** [review]

**Pull request merged**
