### PR TITLE
Moved the groupbytrace processor to contrib

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

**Description:**
Added the groupbytrace processor, as the second step in moving it to the contrib repository.
See https://github.com/open-telemetry/opentelemetry-collector/pull/1891

**Link to tracking Issue:** None.

**Testing** unit tests + manual testing by building a custom otelcol binary with the builder. Apparently, the current master of -contrib breaks with the latest otelcol.

**Documentation:** Nothing new, the existing README was moved here.

### CODE REVIEW

**Comment by jpkrohling** [comment]
CI seems to be failing because master is pointing to a core version that contains the `groupbytrace` processor already:

```
Checking otel-contrib-collector service status ...
● otel-contrib-collector.service - OpenTelemety Contrib Collector
   Loaded: loaded (/lib/systemd/system/otel-contrib-collector.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-10-02 12:17:44 UTC; 3s ago
  Process: 108 ExecStart=/usr/bin/otelcontribcol --config /etc/otel-contrib-collector/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 108 (code=exited, status=1/FAILURE)
```

**Comment by tigrannajaryan** [comment]
Please rebase and make sure the build passes. You may need to disable the component for now, I am not sure 2 components with the same name are allowed.

**Comment by jpkrohling** [comment]
Will rebase once we agree on the order of things (see https://github.com/open-telemetry/opentelemetry-collector/pull/1891#issuecomment-703462810).

**Comment by jpkrohling** [comment]
@tigrannajaryan, PR updated and the build is passing.

**Comment by tigrannajaryan** [comment]
@jpkrohling to confirm: this is a copy of groupby processor from core repository, right? I will not review the since it is a copy of already reviewed code. If you made any changes to the code let me know what changes so that I can have a look.

**Comment by jpkrohling** [comment]
That's correct. While writing this comment, I double-checked the metric names and found out that they were diverging, hence this last commit.

Apart from that, the only divergences are:

- Moved away from the internal structures over to pdata.TraceID and pdata.SpanID
- How the metrics views are registered. It's now in the factory.go, like this:

```go
	// TODO: find a more appropriate way to get this done, as we are swallowing the error here
	_ = view.Register(MetricViews()...)
```

I believe those changed are minimal and inline with how other components work.

**Comment by jpkrohling** [comment]
Test failure:

```
2020/10/14 14:21:18 RAM consumption is 81 MiB, max expected is 80 MiB
    test_case.go:324: RAM consumption is 81 MiB, max expected is 80 MiB
```

Is this a new flaky test?

**Comment by tigrannajaryan** [comment]
> Test failure:
> 
> ```
> 2020/10/14 14:21:18 RAM consumption is 81 MiB, max expected is 80 MiB
>     test_case.go:324: RAM consumption is 81 MiB, max expected is 80 MiB
> ```
> 
> Is this a new flaky test or should I worry about it?

@jpkrohling please check previous builds to see if it was close to the limit. If it was close than it is probably due to small fluctuation which we can ignore. If we see a big jump than we need to be more careful. In the past we had cases when seemingly unrelated code changes in other components resulted in performance degradation due to the new component bringing newer version of dependencies (ProtoBuf I believe had a regressions like that).

**Comment by jpkrohling** [comment]
I updated this PR to fix the metric names in the test which was another cause for the CI failure. The build is now failing with:

```
exec: "gcc": executable file not found in %PATH%
FAIL	github.com/DataDog/opentelemetry-collector-contrib/exporter/datadogexporter [build failed]
FAIL
```

Seems like the same problem as my other open PR (#1257).

**Comment by tigrannajaryan** [comment]
@jpkrohling please rebase, build failure fixed now.

**Comment by jpkrohling** [comment]
PR rebased.

**Comment by jpkrohling** [comment]
Everything is green now.

**Comment by jpkrohling** [comment]
Rebased once again.

**Review by tigrannajaryan — APPROVED** [review]
Approving, this is a copy of the code that was previously in the core and is reviewed.

**Comment by tigrannajaryan** [comment]
@jpkrohling sorry, more conflicts, please rebase so that I can merge.

**Comment by jpkrohling** [comment]
Rebased.

**Comment by jpkrohling** [comment]
@bogdandrutu, @tigrannajaryan please, do *not* release OpenTelemetry Collector Contrib 0.13.0 without this change!

**Comment by tigrannajaryan** [comment]
> @bogdandrutu, @tigrannajaryan please, do _not_ release OpenTelemetry Collector Contrib 0.13.0 without this change!

@bogdandrutu looks like you missed the notice, we have a release without this processor. It was removed from core and now missing in contrib.

**Review by anuraaga — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@tigrannajaryan @jpkrohling my bad

We can do a patch release tomorrow

**Pull request merged**
