### PR TITLE
Update core dependency and adopt code to the API changes

### PR DESCRIPTION
**Pull request by dmitryax**
Remove usage of deprecated API:
- `pdata.AttributeMap`
- `pdata.NewAttributeMap`
- `pdata.NewAttributeMapFromMap`
- `pdata.AttributeValueSlice`
- `pdata.NewAttributeValueSlice`

Remove usage of deleted `pdata.InternalRep`

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Please rebase now that https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8807 is merged

**Comment by dmitryax** [comment]
@codeboten done

**Review by codeboten — COMMENTED** [review]
doh! as i was reviewing another pr got merged and there's a new conflict to resolve

**Comment by dmitryax** [comment]
@codeboten no problem. I rebased and got the the tests passing. PTAL

**Review by codeboten — APPROVED** [review]

**Pull request merged**
