### PR TITLE
[exporter/kafkaexporter] add zipkin encoding for traces

### PR DESCRIPTION
**Pull request by yaroliakh**
**Description:** <Describe what has changed.>
Adding Zipkin v2 encoding support for traces in kafkaexporter 

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21102

**Testing:** <Describe what testing was performed and which tests were added.>
Test for `tracesMarshalers` has been extended with zipkin JSON test case.

### CODE REVIEW

**Comment by atoulme** [comment]
Changes look good to me. Please resolve the conflicts. I will take another look and make sure the build runs.

**Comment by yaroliakh** [comment]
@atoulme thanks for reviewing! Conflicts should be resolved now.

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by yaroliakh** [comment]
@atoulme @MovieStoreGuy are we good to merge this? Just want to avoid it drifting too much from the main branch.

**Review by iblancasa — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
LGTM please resolve the conflicts sorry, and we can get it merged.

**Comment by yaroliakh** [comment]
@atoulme done!

**Pull request merged**
