### PR TITLE
K8s Processor: logs support

### PR DESCRIPTION
**Pull request by pmm-sumo**
**Description:** Adds log support to `k8sprocessor`

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/1654

**Testing:** unit tests cover logs use-cases, manual tests via fluentforward protocol done (and spans to confirm nothing breaks)

**Documentation:** updated `doc.go` and cleared-out (hopefully) how is the pod IP address determined

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@keitwb @owais please review.

**Review by keitwb — APPROVED** [review]
LGTM

**Review by owais — APPROVED** [review]

**Comment by pmm-sumo** [comment]
While working on this PR I noticed two things: 
* Shouldn't we move the config description from `doc.go` to `README.md` (as for other processors)? There is a closed issue on that but I am not sure if it has the originally intended outcome: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/97
* Perhaps we could extract some of the hardcoded behaviour into config entries: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1077

Let me know what do you think, those should be quick to add if they make sense

**Comment by bogdandrutu** [comment]
> Shouldn't we move the config description from doc.go to README.md (as for other processors)? There is a closed issue on that but I am not sure if it has the originally intended outcome: #97

Using README is more consistent

> Perhaps we could extract some of the hardcoded behaviour into config entries: #1077, #1078, #1079, #1080

Sounds like a good idea

**Pull request merged**
