### PR TITLE
[pkg/ottl]  Update Parser to understand solo conditions

### PR DESCRIPTION
**Pull request by TylerHelmuth**

### CODE REVIEW

**Comment by kovrus** [comment]
It looks good! @TylerHelmuth thanks for playing around with it. 

However, as it was mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14783#issuecomment-1275340283 transform processor now can parse both `conditionStatement` and `transformationStatement` I am not sure whether it should be allowed since using `conditionStatement` doesn't make much sense there. I am wondering whether we should pass smth that would verify supported statement types, maybe later we can do smth between these lines when creating an instance of `ottl.Parser` in components: 

```go
... = NewParser(
         statements,
         WithFunctions(functions),
         WithSettings(settings),
         WithSupportedStatements(Statement.TRANSFORMARION), 
      )
```

**Comment by TylerHelmuth** [comment]
Yes we could add something like that in the future and use it during validation, but I think it could be added later in its own PR.

**Comment by kovrus** [comment]
Can I somehow help to move this idea forward?

**Comment by kovrus** [comment]
> @kovrus I've been unable to make this work a priority as I've been working on other things. Are you able to take over?

@TylerHelmuth I can try! I'll take a look at it the next week.

**Pull request closed without merging**
