### PR TITLE
[processor/transform] Added CONTRIBUTING.md

### LINKED ISSUE #10101: [processor/transform] Refactor function structure
[The transform processor currently uses reflection to call functions.](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e2d24b5a36ce989b58effaf8ea89d6474f6795a0/processor/transformprocessor/internal/common/functions.go#L143)  Reflection is working, but is complicated to maintain and adapt when new functions are added.

This issue will track the following steps to removing reflection and improving function add process:
- [x]  Update reflection in `NewFunctionCall`.  Any new functions should be able to access any parameters from `Value`
- [x] Refactor functions into their own files/modules.  This is how [log-collection](https://github.com/open-telemetry/opentelemetry-log-collection/tree/main/operator) is organized, and I think it helps organize the code.  If we continue to put all shared functions in `common/functions.go`, the file will become huge.  
- [x] Think about how to refactor unit tests for functions.  Right now each time a function is added it will need test scenarios in `common /functions_test.go` and each signal's `functions_test.go`.  This process has a lot of room for missed tests.  Want to figure out if there is a better way to handle testing functions for all the different scenarios.
- [ ] Add a CONTRIBUTING.md for how to add new functions and how to add new features to the parser.

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
This PR adds a CONTRIBUTING.md to help those interested in adding new functions or updates to the grammar.

**Link to tracking Issue:** 
Closes #10101

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@djaglowski how do we handle check-links when the link goes to a new file?

**Comment by djaglowski** [comment]
@TylerHelmuth, I believe in this case you can likely make this a relative link `[CONTRIBUTING.md](../../CONTRIBUTING.md)`, so it does not expect the file to be on the main branch yet.

**Comment by TylerHelmuth** [comment]
> @TylerHelmuth, I believe in this case you can likely make this a relative link `[CONTRIBUTING.md](../../CONTRIBUTING.md)`, so it does not expect the file to be on the main branch yet.

Won't that link to the repo's root CONTRIBUTING.md?  I'd like to link from the processor's README to the processor's CONTRIBUTING.md

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
