### PR TITLE
[receiver/simpleprometheus] Add support for static labels

### PR DESCRIPTION
**Pull request by newly12**
**Description:** <Describe what has changed.>

Add support for static labels in simpleprometheusreceiver

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>
1 test has been updated to include static label 

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Thanks for the contribution! Please add a note about this enhancement to CHANGELOG.md.

Pinging code owner @asuresh4

**Comment by newly12** [comment]
Thanks! changelog is updated.

**Comment by newly12** [comment]
Hi @asuresh4, any update?

**Comment by bogdandrutu** [comment]
@codeboten he is no longer with the project :)

**Comment by vjsamuel** [comment]
@codeboten @bogdandrutu , is there any way we can move forward with this? @newly12 please rebase.

**Review by codeboten — APPROVED** [review]
Although I don't have a lot of familiarity with this receiver, the change looks fine.

**Pull request merged**
