### PR TITLE
[chore] Update collector core dependency

### PR DESCRIPTION
**Pull request by dmitryax**

### CODE REVIEW

**Review by Aneurysm9 — CHANGES_REQUESTED** [review]
I'm working on this same change, but including the `replace` directives needed to allow those of us who can't use the Go module proxy to build.  I'd rather not have to do this yet again to deal with merge conflicts.

**Comment by dmitryax** [comment]
I just wanted to ensure that https://github.com/open-telemetry/opentelemetry-collector/pull/7324 is included in the release, and this PR is needed as an intermediate step for that. Otherwise, we will end up releasing it with a partially upgraded otel go dependency

**Comment by Aneurysm9** [comment]
I believe I've squashed the last of the issues and I'm running `make update-otel` for (hopefully) the last time now.  I'll have a PR up as soon as it is done and then we can move forward in the core repo.

**Comment by Aneurysm9** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19342

**Pull request closed without merging**
