### PR TITLE
[exporter/AlibabaCloudLogServiceExporter] Fix issue that promethus occuring error when resource labels contains dot

### PR DESCRIPTION
**Pull request by qiansheng91**
## Description

As issue #3429 mentioned, PR #3454 missed sanitizing the resource metric labels. The Prometheus still occurring issue when the resource metrics label contains a dot. 

## How to fix
Just sanitize those labels when appending resource labels.  

PR #3454 has already added sanitize logical in the `KeyValues.Append` Method. Just like [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/alibabacloudlogserviceexporter/metricsdata_to_logservice.go#L69). So the sanitize logically will be active when the resource metric labels call the `Append`  method.

```golang
func (kv *KeyValues) Append(key, value string) {
	key = sanitize(key)
	kv.keyValues = append(kv.keyValues, KeyValue{
		key,
		value,
	})
}
```

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
pinging @shabicheng @kongluoxing as code owners

**Review by shabicheng — APPROVED** [review]
LGTM

**Review by TylerHelmuth — APPROVED** [review]

**Comment by pingxin0521** [comment]
How soon will this PR be merged?

**Comment by jpkrohling** [comment]
I'll merge this once the CI is green.

**Pull request merged**
