### PR TITLE
[chore][pkg/ottl] Use faster json parsing library

### PR DESCRIPTION
**Pull request by djaglowski**
This follows https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33785 by switching to a faster json library.

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]
**Suggestion:** I don't think it's entirely necessary, but adding a changelog might be nice. Sharing that this is a performance enhancement is a plus, and it'd be slightly more easy to find this as a change to `pkg/ottl` if this ends up causing any unexpected bugs. Just a thought.

**Comment by atoulme** [comment]
Any benchmarks?

**Comment by djaglowski** [comment]
@BinaryFissionGames pointed out to me offline that the benchmark was just getting the function but not executing it.

Now I see a nice improvement:

```
benchstat pkg/ottl/old.txt pkg/ottl/new.txt                                                                                              ✭ ✱
goos: darwin
goarch: arm64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/ottlfuncs
             │ pkg/ottl/old.txt │          pkg/ottl/new.txt           │
             │      sec/op      │   sec/op     vs base                │
ParseJSON-10        278.0µ ± 2%   246.3µ ± 3%  -11.38% (p=0.000 n=10)

             │ pkg/ottl/old.txt │           pkg/ottl/new.txt           │
             │       B/op       │     B/op      vs base                │
ParseJSON-10       26.84Ki ± 0%   10.89Ki ± 0%  -59.43% (p=0.000 n=10)

             │ pkg/ottl/old.txt │          pkg/ottl/new.txt          │
             │    allocs/op     │ allocs/op   vs base                │
ParseJSON-10         206.0 ± 0%   169.0 ± 1%  -17.96% (p=0.000 n=10)
```

**Review by TylerHelmuth — APPROVED** [review]
@djaglowski please handle the merge conflicts

**Review by codeboten — APPROVED** [review]
👍🏻

**Pull request merged**
