### PR TITLE
[extension/sigv4authextension] Enable component

### PR DESCRIPTION
**Pull request by erichsueh3**
**Description:**
Enables the `sigv4authextension` component

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Comment by erichsueh3** [comment]
Looks like I need to run `go mod tidy` to get these tests to set up correctly, but when I do that I get a `gopkg.in/DataDog/dd-trace-go.v1@v1.37.0 requires
	github.com/go-chi/chi/v4@v4.0.0-rc1: reading github.com/go-chi/chi/go.mod at revision v4.0.0-rc1: unknown revision v4.0.0-rc1` error, and I'm not too sure what to do about this.

**Comment by mx-psi** [comment]
> Looks like I need to run `go mod tidy` to get these tests to set up correctly, but when I do that I get a `gopkg.in/DataDog/dd-trace-go.v1@v1.37.0 requires github.com/go-chi/chi/v4@v4.0.0-rc1: reading github.com/go-chi/chi/go.mod at revision v4.0.0-rc1: unknown revision v4.0.0-rc1` error, and I'm not too sure what to do about this.

The dependency can be found on the official Go proxy (you can download it here https://proxy.golang.org/github.com/go-chi/chi/v4/@v/v4.0.0-rc1.zip) but not on Github (https://github.com/go-chi/chi/releases/tag/v4.0.0-rc1 returns a 404). 

You are probably not using the official Go proxy (what does `go env | grep GOPROXY` output?) while CI is, which would explain this. If you set `GOPROXY="https://proxy.golang.org,direct"` it should work (unless you can't access the official Go proxy, in which case... I can do it for you maybe?).

I will try to report this upstream and also to our APM team (I work at Datadog) so that this doesn't happen.

**Comment by mx-psi** [comment]
Reported at https://github.com/DataDog/dd-trace-go/pull/1188#issuecomment-1070750453 and https://github.com/go-chi/chi/issues/713

**Review by mx-psi — COMMENTED** [review]
~~Remember that to include this on the binaries you have to make a PR on the releases repo, see e.g. https://github.com/open-telemetry/opentelemetry-collector-releases/pull/78~~ I see you already did that 😅

**Review by jpkrohling — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
I can't seem to create a PR to your branch @erichsueh3, but here's the `gotidy` change: https://github.com/codeboten/opentelemetry-collector-contrib/commit/5b76e2d0c308990943caca344f23325a8d58bd61

**Comment by Aneurysm9** [comment]
> You are probably not using the official Go proxy (what does `go env | grep GOPROXY` output?) while CI is, which would explain this. If you set `GOPROXY="https://proxy.golang.org,direct"` it should work (unless you can't access the official Go proxy, in which case... I can do it for you maybe?).

We cannot access the official Go proxy, so I consider us canaries for bad modules! :)

**Comment by erichsueh3** [comment]
> > You are probably not using the official Go proxy (what does `go env | grep GOPROXY` output?) while CI is, which would explain this. If you set `GOPROXY="https://proxy.golang.org,direct"` it should work (unless you can't access the official Go proxy, in which case... I can do it for you maybe?).
> 
> We cannot access the official Go proxy, so I consider us canaries for bad modules! :)

Tried the suggested change to set `GOPROXY="https://proxy.golang.org,direct"` and yes, it still doesn't work

**Review by mx-psi — COMMENTED** [review]
Needs a changelog entry

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
