### PR TITLE
[chore][extension/opampextension] Enable goleak check

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

This enables the `goleak` check for the opamp extension, to help ensure it's not leaking any goroutines. This is a test only change, a `Shutdown` call was missing.

**Link to tracking Issue:** <Issue number if applicable>
#30438

**Testing:** <Describe what testing was performed and which tests were added.>
All existing tests are passing, as well as the added `goleak` check

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
It would also great to enable this on https://github.com/open-telemetry/opamp-go

**Review by evan-bradley — APPROVED** [review]
Thanks for adding this. Looks like there are some conflicts with main, can you rebase?

**Comment by crobert-1** [comment]
> Thanks for adding this. Looks like there are some conflicts with main, can you rebase?

Apologies for the delay, I've rebased. 👍

**Comment by crobert-1** [comment]
Failures are due to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31493 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31443.

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
approved as codeowner and approver. This is ready for merge.

**Pull request merged**
