### PR TITLE
Added implementation of Google Cloud Spanner receiver - 2nd part(metadata parser and metadata config)

### PR DESCRIPTION
**Pull request by ydrozhdzhal**
This part of implementation contains metadata parser implementation and metadata config file.
This stuff will be used for constructing metrics metadata and metric readers(will be added as separate MRs).

### CODE REVIEW

**Review by kostia-hospodarysko — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]
Apart from some minor nits, looks good to me. Note that, like the part 1, I can't judge the business of this PR, as I don't know Cloud Spanner.

**Comment by ydrozhdzhal** [comment]
@jpkrohling , all you comments were resolved. Thank you for quick feedback. Whom can I ask to merge this, @tigrannajaryan ?

**Comment by ydrozhdzhal** [comment]
@jpkrohling , can you review one more time and approve(all checks/jobs passed)?

**Review by jpkrohling — APPROVED** [review]

**Review by asukhyy — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Comment by ydrozhdzhal** [comment]
> Please also populate the commit message, not just a one-liner (in most cases should be a copy of the PR description).
> 
> I copy/pasted this time before merging.

Ok, will take this into account.

**Pull request merged**
