### PR TITLE
Add pulsar exporter (#3164)

### PR DESCRIPTION
**Pull request by hanjm**
**Description:**
Export metrics, traces, logs data to pulsar. 

opentelemetry-collector has kafkaexporter and kafkareceiver, [Apache Pulsar](https://pulsar.apache.org/) is a cloud-native, distributed messaging and streaming platform. 

**Link to tracking Issue:** 
#3164

**Testing:** 
unittest
integration test at Macos

### CODE REVIEW

**Comment by hanjm** [comment]
need help:
1. pulsar sdk need cgo, but windows test env does not has cgo gcc.
```
# runtime/cgo
exec: "gcc": executable file not found in %PATH%
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol [build failed]
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/pulsarexporter [build failed]
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/internal/version	0.032s [no tests to run]
FAIL

Exited with code exit status 2
```
2. diff test coverage target need 95.00%, need setup broker for connect ..

**Comment by hanjm** [comment]
```
Workflow: build-publish
setup - Success
lint - Success
integration-tests - Success
windows-test - Failed
unit-tests - Failed
cross-compile - Success
deb-package - Success
loadtest - Success
windows-msi - Success
rpm-package - Success
publish-check - Blocked
build-examples - Success
```

1. windows-test - Failed 

error message

```
# github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol.test
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 171369
collect2.exe: error: ld returned 1 exit status

FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol [build failed]
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/pulsarexporter	6.831s
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/internal/version	0.031s [no tests to run]
FAIL
```

it need go version 1.15.11, but the choco does not have this package.

2. unit-tests - Failed

```
running go unit test ./... + coverage in /home/circleci/project/exporter/loadbalancingexporter
==================
WARNING: DATA RACE
Read at 0x00c0004c8048 by goroutine 69:
  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.TestRollingUpdatesWhenConsumeLogs()
      /home/circleci/project/exporter/loadbalancingexporter/log_exporter_test.go:493 +0x1784
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1123 +0x202

Previous write at 0x00c0004c8048 by goroutine 70:
  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*dnsResolver).resolve()
      /home/circleci/project/exporter/loadbalancingexporter/resolver_dns.go:160 +0xace
  github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*dnsResolver).periodicallyResolve()
      /home/circleci/project/exporter/loadbalancingexporter/resolver_dns.go:105 +0x273

```

it need fix by modify loadbalancingexporter.

**Comment by hanjm** [comment]
```
Workflow: build-publish
windows-test - Failed
integration-tests - Success
setup - Success
cross-compile - Success
windows-msi - Success
rpm-package - Success
deb-package - Success
loadtest - Success
unit-tests - Success
lint - Success
publish-check - Blocked
build-examples - Success
```

windows-test fail, error message: 
```
2021-04-18T11:43:03.363Z	DEBUG	groupbytraceprocessor/event.go:92	recording current state of the queue	{"num-events": 0}
--- FAIL: TestPeriodicMetrics (0.04s)
    event_test.go:416: 
        	Error Trace:	event_test.go:416
        	            				event_test.go:365
        	Error:      	Not equal: 
        	            	expected: int(0)
        	            	actual  : float64(1)
        	Test:       	TestPeriodicMetrics
```

**Comment by hanjm** [comment]
```
Workflow: build-publish
setup - Success
cross-compile - Success
windows-msi - Success
loadtest - Success
deb-package - Success
rpm-package - Success
unit-tests - Failed
build-examples - Success
lint - Success
windows-test - Failed
integration-tests - Success
publish-check - Blocked
```

```
running go unit test ./... + coverage in /home/circleci/project/exporter/elasticsearchexporter
--- FAIL: TestExporter_PushEvent (0.88s)
    --- FAIL: TestExporter_PushEvent/no_retry (0.00s)
        --- FAIL: TestExporter_PushEvent/no_retry/fail_item (0.00s)
            --- FAIL: TestExporter_PushEvent/no_retry/fail_item/retry.enabled_is_false (0.20s)
                logger.go:130: 2021-04-18T12:00:25.736Z	DEBUG	Request roundtrip completed.	{"path": "/_bulk", "method": "POST", "duration": "1.363379ms", "status": "500 Internal Server Error"}
                logger.go:130: 2021-04-18T12:00:25.739Z	DEBUG	Request roundtrip completed.	{"path": "/_bulk", "method": "POST", "duration": "531.825µs", "status": "500 Internal Server Error"}
                logger.go:130: 2021-04-18T12:00:25.740Z	ERROR	Bulk indexer error: flush: %!s(<nil>)
                logger.go:130: 2021-04-18T12:00:25.741Z	ERROR	Bulk indexer error: flush: [500 Internal Server Error] oops
                exporter_test.go:212: 
                    	Error Trace:	exporter_test.go:212
                    	Error:      	Not equal: 
                    	            	expected: 1
                    	            	actual  : 2
                    	Test:       	TestExporter_PushEvent/no_retry/fail_item/retry.enabled_is_false
            --- FAIL: TestExporter_PushEvent/no_retry/fail_item/max_requests_limited (0.20s)
                logger.go:130: 2021-04-18T12:00:25.737Z	DEBUG	Request roundtrip completed.	{"path": "/_bulk", "method": "POST", "duration": "1.017157ms", "status": "500 Internal Server Error"}
                logger.go:130: 2021-04-18T12:00:25.739Z	DEBUG	Request roundtrip completed.	{"path": "/_bulk", "method": "POST", "duration": "600.928µs", "status": "500 Internal Server Error"}
                logger.go:130: 2021-04-18T12:00:25.740Z	ERROR	Bulk indexer error: flush: %!s(<nil>)
                logger.go:130: 2021-04-18T12:00:25.741Z	ERROR	Bulk indexer error: flush: [500 Internal Server Error] oops
                exporter_test.go:212: 
                    	Error Trace:	exporter_test.go:212
                    	Error:      	Not equal: 
                    	            	expected: 1
                    	            	actual  : 2
                    	Test:       	TestExporter_PushEvent/no_retry/fail_item/max_requests_limited
FAIL
```

fail agin, try fix elasticsearchexporter unittest.

**Comment by tigrannajaryan** [comment]
Please follow the PR process for new components: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

**Comment by hanjm** [comment]
Workflow: build-publish
windows-test - Failed
setup - Success
lint - Success
unit-tests - Success
integration-tests - Success
build-examples - Success
cross-compile - Success
deb-package - Success
windows-msi - Success
rpm-package - Success
loadtest - Success
publish-check - Blocked
```
2021-04-29T02:30:08.742Z	WARN	groupbytraceprocessor/processor.go:118	failed to process batch	{"error": "couldn't add spans to new trace: some unexpected error", "traceID": "01020304000000000000000000000000"}
github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.(*groupByTraceProcessor).processResourceSpans
	C:/Users/circleci/project/processor/groupbytraceprocessor/processor.go:118
github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor.TestErrorOnProcessResourceSpansContinuesProcessing
	C:/Users/circleci/project/processor/groupbytraceprocessor/processor_test.go:595
testing.tRunner
	C:/Program Files/Go/src/testing/testing.go:1194
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor	0.660s
FAIL

Exited with code exit status 1
```

**Comment by bogdandrutu** [comment]
@hanjm please rebase the PR, upgrade otel core deps, and follow the steps in https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

**Comment by hanjm** [comment]
> @hanjm please rebase the PR, upgrade otel core deps, and follow the steps in https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

i see，thank you.

**Comment by hanjm** [comment]
> @hanjm please rebase the PR, upgrade otel core deps, and follow the steps in https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

hi @bogdandrutu , the fist PR of this component has done~

**Comment by sparam** [comment]
@hanjm Just curious to know any reason this PR was not merged? would you be able to reopen this PR?

**Comment by bogdandrutu** [comment]
@sparam the reason is simple, we have a process for adding new components, and the PR did not follow that. Consider to follow the process by starting with filing a new issue for this exporter. See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components

**Pull request closed without merging**
