### PR TITLE
Cloud Foundry receiver step 2 - implementation

### PR DESCRIPTION
**Pull request by agoallikmaa**
**Description:** Adds implementation to the Cloud Foundry receiver skeleton merged in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4626 .

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5320

**Testing:** Some implementation parts have been unit tested, the rest will be added as integration tests, in a separate PR which tests against a local HTTP server which will respond with prerecorded responses (recorded from running it against Tanzu Application Service).

**Documentation:** Configuration was updated in documentation to reflect using `HTTPClientSettings` instead of custom fields.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
```
receiver/cloudfoundryreceiver/config_test.go: Import groups are not in the proper order: ["Std" "Third party" "Third party"]
receiver/cloudfoundryreceiver/factory.go: Import groups are not in the proper order: ["Std" "Third party" "Third party"]
receiver/cloudfoundryreceiver/uaa.go: Import groups are not in the proper order: ["Std" "Third party" "Third party"]

impi verification failed: Found 3 errors
make: *** [Makefile.Common:107: impi] Error 1
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 2.
```

**Comment by mx-psi** [comment]
@pellared can you review?

@agoallikmaa please rebase

**Review by pellared — APPROVED** [review]
A left a few last minor comments. But it is great as it is. Nice work 👍

**Comment by pellared** [comment]
@tigrannajaryan Can you review it again, please?

**Comment by mx-psi** [comment]
@agoallikmaa needs a rebase

@tigrannajaryan friendly ping to give a final review

**Review by tigrannajaryan — APPROVED** [review]
Can be merged once rebased.

**Pull request merged**
