### PR TITLE
[receiver/windowsperfcounters] Returning partial errors for failures

### PR DESCRIPTION
**Pull request by chrislbs**
Returning partial errors for failures during scraping to prevent throwing out all successfully retrieved metrics.

**Description:** Fixing a bug where a single instance of a windows performance object prevents metrics for all other valid instances from being published.

**Link to tracking Issue:** [16712](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16712)

**Testing:**  I added additional tests that verifies if some scrapers fail to retrieve metrics, the ones that don't fail continue to publish their metrics.

**Documentation:**

### CODE REVIEW

**Comment by chrislbs** [comment]
Am I missing something to get this PR completed?

**Review by mx-psi — APPROVED** [review]
Nothing blocking this, I assume @dashpole didn't have time to look at this.

This LGTM, I will give a few days in case @alxbl wants to have a look and merge if not

**Comment by alxbl** [comment]
LGTM!

Can't approve it yet as I'm not a code owner just yet, though :P

**Comment by mx-psi** [comment]
@alxbl Thank you! Also, feel free to approve or review any PR, whether you are a codeowner or not :) All reviews are welcome, no matter what your formal role is

**Pull request merged**
