### PR TITLE
Promote the OpAMP extension to alpha stability

### PR DESCRIPTION
**Pull request by evan-bradley**
The extension has a decent set of features now and should be ready for basic testing by users.

### CODE REVIEW

**Review by crobert-1 — COMMENTED** [review]
```
Generated code is out of date, please run "make gendistributions" and commit the changes in this PR.
```

**Comment by crobert-1** [comment]
I assume a PR to the collector releases repo will be posted as a follow up to this PR? (Just want to confirm to make sure we don't miss it 👍)

**Review by jaronoff97 — APPROVED** [review]
🎉

**Review by tigrannajaryan — APPROVED** [review]

**Comment by astencel-sumo** [comment]
I ran `make gendistributions` to fix one of the CI checks.

**Review by andrzej-stencel — APPROVED** [review]

**Comment by crobert-1** [comment]
```Generated code is out of date, please run "make generate" and commit the changes in this PR.```

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
