### PR TITLE
return concrete types!

### LINKED ISSUE #31264: [receiver/azuremonitor] Return concrete types
### Component(s)

receiver/azuremonitor

### Describe the issue you're reporting

This was raised by @michalpristas as a tangential comment to changes in #30224. I believe that the instance of this receiver's code more idiomatic approach of returning concrete types will make our code more maintainable - likely highlighting where we benefit from the layer of abstraction in interfaces and... where we don't.

### PR DESCRIPTION
**Pull request by led0nk**
concrete/iface

**Description:** <Describe what has changed.>
As requested this PR removes the unnecessary use of 
```
func (s *azureScraper) getArmClient() (armClient, error) 
func (s *azureScraper) getMetricsDefinitionsClient() (metricsDefinitionsClientInterface, error)
func (s *azureScraper) GetMetricsValuesClient() (metricsValuesClient, error)
```
Those methods returned interfaces which later got implemented by fields of the `*azureScraper`.
Now we directly assign them with their concrete types, which were handled through their interfaces before. The implementation of errorhandling was already done earlier.

**Link to tracking Issue:** <Issue number if applicable>
- resolves #31264  

**Testing:** <Describe what testing was performed and which tests were added.>
Testing was done through the given `scraper_test.go`.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by led0nk** [comment]
image

do we solve this in this PR or do we have to raise another one?

**Comment by nslaughter** [comment]
> do we solve this in this PR or do we have to raise another one?

IMO this is a separate issue / PR.

**Review by nslaughter — APPROVED** [review]
I have reviewed the deletions and approve providing for checks passing. This PR deletes unnecessary code and replaces usage with essential code.

Filling out the PR comment may be important for getting approvers' review.

**Comment by led0nk** [comment]
> Filling out the PR comment may be important for getting approvers' review.

I will take care of this, thanks

**Pull request closed without merging**
