### PR TITLE
AWSEMFExporter - Enhance unit tests for metric value validation. Always use float64 as calculated rate.

### PR DESCRIPTION
**Pull request by shaochengwang**
**Description:** 
* Enhance unit tests for metric value validation. 
* Always use float64 as calculated rate.

**Testing:** 
Added Unit tests

**Documentation:** 
Added unit tests to cover all metric value validation for all data types.
Use float64 as calculated rate for IntSum to ensure the precision.

### CODE REVIEW

**Comment by anuraaga** [comment]
Can we change the type of `rateState.value` too?

**Comment by shaochengwang** [comment]
> Can we change the type of `rateState.value` too?

Thanks for reviewing this PR. Actually, the `rateState.value` is not for the calculated rate value. It is representing the raw metric value for both `IntSum` and `DoubleSum` data types. We use the raw metric value stored in `rateState.value` to calculate the rate, but the rate value is always float64 no matter what is the data type of the raw metric value.

**Comment by anuraaga** [comment]
@shaochengwang I see - can we just store ints as floats in the state too though? I guess if there is any precision loss, it would happen at the final computeRate step anyways so treating the raw values as float doesn't seem to hurt and could simplify the code a lot.

**Comment by shaochengwang** [comment]
> @shaochengwang I see - can we just store ints as floats in the state too though? I guess if there is any precision loss, it would happen at the final computeRate step anyways so treating the raw values as float doesn't seem to hurt and could simplify the code a lot.

Agree, it doesn't hurt and can simplify the code. Thanks :)

**Review by anuraaga — APPROVED** [review]
Sweet, thanks

**Comment by tigrannajaryan** [comment]
Please make sure the build passes.

**Comment by shaochengwang** [comment]
The build seems fail at `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zookeeperreceiver` https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-collector-contrib/8064/workflows/eaebce99-8884-4206-a6c9-884dd6916c05/jobs/65742
I don't think the changes in this PR could affect that unit test.

**Pull request merged**
