### PR TITLE
dependabot updates Mon Apr 11 14:30 PDT 2022

### PR DESCRIPTION
**Pull request by dmitryax**

### CODE REVIEW

**Comment by dmitryax** [comment]
It fails due to go library issue https://github.com/open-telemetry/opentelemetry-go/issues/2781 which should be resolved shortly

**Comment by Aneurysm9** [comment]
@dmitryax New metrics release is shipped and should resolve the failures.

**Comment by dmitryax** [comment]
Thanks @Aneurysm9. PR updated

**Review by codeboten — APPROVED** [review]
Thanks @dmitryax

**Review by codeboten — COMMENTED** [review]
A lint failure:

```
 Error: internal/common/parser.go:122:26: cannot use ([]lexer.Rule literal) (value of type []lexer.Rule) as []lexer.SimpleRule value in argument to lexer.MustSimple (typecheck)
	lex := lexer.MustSimple([]lexer.Rule{
```

**Comment by dmitryax** [comment]
@codeboten the lint issue is fixed

**Pull request merged**
