### PR TITLE
[chore] Add @rapphil to PRW exporter CODEOWNERS

### PR DESCRIPTION
**Pull request by Aneurysm9**

### CODE REVIEW

**Review by rapphil — APPROVED** [review]

**Review by TylerHelmuth — CHANGES_REQUESTED** [review]
@rapphil we're excited in your interest in the project, but it doesn't look like you are a member of the open-telemetry organization, which is a requirement for [becoming a code owner](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#becoming-a-code-owner) so that we can assign you issues and PRs.  If you meet the requirements for becoming a member of the open-telemetry organization please follow [these instructions to become a member](https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements) and I will sponsor your membership.  If not, please work on a couple PRs/issues on anything in the repository and then I will sponsor your membership.

Related issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20868

**Comment by rapphil** [comment]
Thank you @TylerHelmuth I will take care of that.

**Comment by rapphil** [comment]
@TylerHelmuth I created the issue requesting membership https://github.com/open-telemetry/community/issues/1456

**Review by TylerHelmuth — APPROVED** [review]
Welcome!

**Review by codeboten — APPROVED** [review]
🎉

**Pull request merged**
