### PR TITLE
Add Syslog UDP test

### PR DESCRIPTION
**Pull request by chaitanyaphalak**
**Description:** Added test case for Syslog UDP log collection plugin

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3095

### CODE REVIEW

**Comment by djaglowski** [comment]
Hi @chaitanyaphalak, thanks for the PR.

This solution was considered before [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3419/files#r634439373). Unfortunately, it doesn't solve the root problem, so we should find a more robust solution. (see linked conversation)

**Comment by djaglowski** [comment]
Also worth noting that basically the same test was removed in #3532 due to instability.

**Comment by chaitanyaphalak** [comment]
@djaglowski thanks for the feedback, do you know whats the root cause? When I run the test locally, the logs are clean without any errors.

**Comment by djaglowski** [comment]
@chaitanyaphalak Thanks for looking at this. I think the problem and possibly solution are best described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3419/files#r636241182). Basically, the testbed waits for the udp port to be available, but this is not a guarantee that the server is ready to receive data. It works fine most of the time but sometimes starts sending data too soon.

**Comment by djaglowski** [comment]
@chaitanyaphalak Thanks for making an attempt at this one. Based on the writeup I linked, I'm going to close this for now but feel free to reopen with a more robust solution if you are inclined.

**Pull request closed without merging**
