### PR TITLE
[receiver/simpleprometheus] Support customizing job name

### LINKED ISSUE #31502: [simple prometheus receiver]Support customized job name in configuration
### Component(s)

receiver/simpleprometheus

### Is your feature request related to a problem? Please describe.

Hi team, we use the simple prometheus receiver within the receiver creator to scrape metrics from k8s pods with specific annotations, the config is like:
```
receiver_creator/application:
      receivers:
        prometheus_simple/app_pods:
          rule: type == "port" && pod.annotations["prometheus.io/scrape"] == "true" && ( string(port) == pod.annotations["prometheus.io/port"] || name == pod.annotations["prometheus.io/port"] )
          config:
            endpoint: '`endpoint`'
            metrics_path: '`"prometheus.io/path" in pod.annotations ? pod.annotations["prometheus.io/path"] : "/metrics"`'
            collection_interval: '`"prometheus.io/collection_interval" in pod.annotations ? pod.annotations["prometheus.io/collection_interval"] : "30s"`'
```
it works good, but a small problem is that the simple prometheus receiver uses the `prometheus_simple/$endpoint` as the `job name` which would be transformed to `service.name` label in the metric.

It will be great if we can customize the job name here.

### Describe the solution you'd like

Add a job name setting in the configuration. The setting is optional.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenlujjj**
**Description:** <Describe what has changed.>

Resolve https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31502

**Link to tracking Issue:** 31502

### CODE REVIEW

**Comment by chenlujjj** [comment]
Hi @fatsheep9146 , the CI has passed, could you pls review? Thanks

**Comment by chenlujjj** [comment]
hi @fatsheep9146  kind reminder

**Review by atoulme — APPROVED** [review]

**Comment by dashpole** [comment]
@fatsheep9146 are you able to review?

**Comment by chenlujjj** [comment]
not stale, 
Can anyone help to assign the reviewer ?

**Review by jmichalek132 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
This looks ok to me, pinging @fatsheep9146 as the code owner for a review

**Pull request merged**
