### PR TITLE
[extension/jaegerencodingextension] Enhance jaegerEncodingExtension

### PR DESCRIPTION
**Pull request by dao-jun**
**Description:**

#### 2. Marshal traces in `[]*jaegerproto.Batch` level instead of in `Span` level
  The existing exporters exports traces in `*jaegerproto.Batch` level, this PR will be compatible with previous implementations.
#### 3. Introducer `readonlyLengthFieldBuffer` and `writeOnlyLengthFieldBuffer` for trace marshal/unmarshal

**Testing:**
Unit tests

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
LGTM - needs a changelog.

**Comment by atoulme** [comment]
Please rebase

**Comment by dao-jun** [comment]
> Please rebase

branch updated

**Comment by dao-jun** [comment]
@atoulme @MovieStoreGuy Could you please help merge this PR？

**Pull request closed without merging**
