### PR TITLE
[chore] update collector/exporter dependencies

### PR DESCRIPTION
**Pull request by codeboten**
This supports the split of otlp/otlphttp/logging exporters. It required a change to `update-dep` script.

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Working through the failures

**Comment by codeboten** [comment]
Was blocked by https://github.com/open-telemetry/opentelemetry-collector/pull/6405, updating otel once more now

**Review by bogdandrutu — APPROVED** [review]

**Comment by codeboten** [comment]
There's a test failing in the datadogexporter, @mx-psi if you can confirm that it's ok for me to set and environment variable for this test to pass, please review https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15657/commits/3a5b446350502b9451baf7dccb303beeec5d51b1

Failing test, I believe this is caused by the quick failure on validation:
```
--- FAIL: TestExamples (0.01s)
    --- FAIL: TestExamples/collector.yaml (0.00s)
        examples_test.go:55: 
                Error Trace:    /Users/alex.boten/workspace/opentelemetry-collector-contrib/exporter/datadogexporter/examples_test.go:55
                Error:          Received unexpected error:
                                exporter "datadog" has invalid configuration: api.key is not set
                Test:           TestExamples/collector.yaml
                Messages:       All yaml config must validate. Please ensure that all necessary component factories are added in newTestComponents()
```

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
There are more tests failing on the `receivercreator`:

```
 === RUN   TestInvalidResourceAttributeEndpointType
    config_test.go:142: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/receivercreator/config_test.go:142
        	Error:      	Error message not equal:
        	            	expected: "error reading receivers configuration for \"receiver_creator\": resource attributes for unsupported endpoint type \"not.a.real.type\""
        	            	actual  : "cannot unmarshal the configuration: error reading top level configuration sections: 1 error(s) decoding:\n\n* error decoding 'receivers': error reading receivers configuration for \"receiver_creator\": resource attributes for unsupported endpoint type \"not.a.real.type\""
        	Test:       	TestInvalidResourceAttributeEndpointType
--- FAIL: TestInvalidResourceAttributeEndpointType (0.01s)
```

**Comment by codeboten** [comment]
> There are more tests failing on the `receivercreator`:
> 
> ```
>  === RUN   TestInvalidResourceAttributeEndpointType
>     config_test.go:142: 
>         	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/receivercreator/config_test.go:142
>         	Error:      	Error message not equal:
>         	            	expected: "error reading receivers configuration for \"receiver_creator\": resource attributes for unsupported endpoint type \"not.a.real.type\""
>         	            	actual  : "cannot unmarshal the configuration: error reading top level configuration sections: 1 error(s) decoding:\n\n* error decoding 'receivers': error reading receivers configuration for \"receiver_creator\": resource attributes for unsupported endpoint type \"not.a.real.type\""
>         	Test:       	TestInvalidResourceAttributeEndpointType
> --- FAIL: TestInvalidResourceAttributeEndpointType (0.01s)
> ```

who knew we had so many invalid tests 😆

**Pull request merged**
