### PR TITLE
[chore] add go.work to gitignore

### PR DESCRIPTION
**Pull request by codeboten**

### CODE REVIEW

**Comment by dmitryax** [comment]
Looking at https://github.com/golang/go/issues/53502, it seems beneficial to keep it in cases with many interdependent modules... Why do we want to exclude before trying?

**Comment by dmitryax** [comment]
SGTM, do we still want to adopt the workspaces and update all the make targets to use it?

**Comment by codeboten** [comment]
> SGTM, do we still want to adopt the workspaces and update all the make targets to use it?

I've not found a way to successfully use workspaces for purposes other than making intellisense happy :D in other words, i'm not sure if there is much to be gained by updating make targets at this point in time.

**Review by dmitryax — APPROVED** [review]

**Comment by mx-psi** [comment]
@pellared is working on making `crosslink` update and understand `go.work` (see open-telemetry/opentelemetry-go-build-tools/pull/311). We may want to revert this PR once that work is completed.

**Pull request merged**
