### PR TITLE
[chore] [receiver/haproxy] Use generated pdata output in the test

### PR DESCRIPTION
**Pull request by dmitryax**
Cutting it from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24444 to reduce the change set

### CODE REVIEW

**Comment by dmitryax** [comment]
> Any chance we can merge https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24560 first?

Are they conflicting in any way?

**Comment by atoulme** [comment]
I expect some of the expectations associated with the integration test would change.

**Comment by dmitryax** [comment]
Not sure I understand. This one doesn't do anything with integration tests, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24560 doesn't touch the unit test

**Comment by dmitryax** [comment]
Actually, if this is merged first, you'd need to update the `scraper/expected.yaml`. But it's always better to improve test coverage before introducing functional changes, not otherwise

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
Let's get it in then. Thanks Dmitrii!

**Pull request merged**
